### ISSUE TITLE
Healthcheck: Changing/extending AS path on up/down

### ISSUE THREAD

**Issue by mzealey** [Exa-Networks/exabgp#1007]
https://github.com/Exa-Networks/exabgp/blob/933c759a5dde0f44b7d9ff13f8fdaa00be04b35a/lib/exabgp/application/healthcheck.py#L367

Is it possible to add some new flags like `--up-as-path` and `--down-as-path`? This would be the same as the `--*-metric` commands but affecting the `--as-path` flag. Some providers don't support ECMP based on metric but rather the only way to withdraw is to double up the path so it is not the preferred one any more?

**Comment by thomas-mangin** [comment]
need forward-port
