### ISSUE TITLE
cannot send eor manually after exabgp restarted via api

### ISSUE THREAD

**Issue by iddq** [Exa-Networks/exabgp#1012]
** Bug Report **

cannot send eor manually after exabgp restarted via api

**Describe the bug**

cannot send eor manually after exabgp restarted via api

**To Reproduce**

./exabgp/bin/exabgpcli 'restart'     
command: restart
restart in progress
./exabgp/bin/exabgpcli 'announce eor'
command: announce eor

End-of-RIB is not arrived to the router.

**Expected behavior**

End-of-RIB

**Environment (please complete the following information):**

 - OS: Debian
 - Version master

**Additional context**

**Comment by thomas-mangin** [comment]
can you please try: "announce eor ipv4 unicast" or "announce eor ipv6 unicast". The code needs the family to generate the message. There should be an error message on the exabgp output, but looking quickly the code error does not seems to be reported to the API .. which is wrong.
