### ISSUE TITLE
neighbor-changes

### ISSUE THREAD

**Issue by iddq** [Exa-Networks/exabgp#1014]
** Bug Report **

"connected" message received via API even if the neighbor is unreachable (No route to host)

up or connected message should be received after the BGP session established

https://github.com/Exa-Networks/exabgp/blob/db4166917edaaa8ccfd48db1c6dc10501777443e/lib/exabgp/reactor/protocol.py#L111

https://github.com/Exa-Networks/exabgp/blob/db4166917edaaa8ccfd48db1c6dc10501777443e/lib/exabgp/reactor/network/outgoing.py#L43

**Comment by iddq** [comment]
plus, neighbor IP up message received only when the remote router is the connection initiator. you can easily reproduce it if you bind to other port than 179 and you can see the session will be negotiated but you won't receive any "up" message through API.

**Comment by thomas-mangin** [comment]
perhaps naming the function "establish" was not super wise. it is about establishing the TCP connection and not getting to the established state in BGP. connected is not established... :-)
