### ISSUE TITLE
Can I set exabgp server as RR

### ISSUE THREAD

**Issue by EthanYue** [Exa-Networks/exabgp#1018]
The exabgp server can establish neighbor with routers, what I want to asked is that the exabgp server can be configured as the RR?

**Comment by thomas-mangin** [comment]
This is not ExaBGP use, one could write a backend to make it act as a route-server (possibly modifying routes on the way).

**Comment by EthanYue** [comment]
> This is not ExaBGP use, one could write a backend to make it act as a route-server (possibly modifying routes on the way).

Thanks for your reply
