### ISSUE TITLE
ExaBGP lost the helper process for this peer

### ISSUE THREAD

**Issue by ZhiYiFang** [Exa-Networks/exabgp#1019]
I downloaded the project on my mac computer and ran the example below etc. It can run normally, but I run the same example on my server and it will report an error
12:49:50 | 14940  | welcome       | Thank you for using ExaBGP
12:49:50 | 14940  | version       | 4.2.11
12:49:50 | 14940  | interpreter   | 3.5.3 (default, Nov 18 2020, 21:09:16)  [GCC 6.3.0 20170516]
......
12:49:50 | 14940  | cli control   |  - /run/exabgp/
12:49:50 | 14940  | cli control   |  - /run/0/
12:49:50 | 14940  | cli control   |  - /run/
12:49:50 | 14940  | cli control   |  - /var/run/exabgp/
12:49:50 | 14940  | cli control   |  - /var/run/0/
12:49:50 | 14940  | cli control   |  - /var/run/
12:49:50 | 14940  | cli control   |  - /usr/local/run/exabgp/
12:49:50 | 14940  | cli control   |  - /usr/local/run/0/
12:49:50 | 14940  | cli control   |  - /usr/local/run/
12:49:50 | 14940  | cli control   |  - /usr/local/var/run/exabgp/
12:49:50 | 14940  | cli control   |  - /usr/local/var/run/0/
12:49:50 | 14940  | cli control   |  - /usr/local/var/run/
12:49:50 | 14940  | cli control   | please make them in one of the folder with the following commands:
12:49:50 | 14940  | cli control   | > mkfifo /root/exabgp/etc/exabgp/run/exabgp.{in,out}
12:49:50 | 14940  | cli control   | > chmod 600 /root/exabgp/etc/exabgp/run/exabgp.{in,out}
12:49:50 | 14940  | configuration | performing reload of exabgp 4.2.11
12:49:50 | 14940  | reactor       | loaded new configuration successfully
12:49:50 | 14940  | process       | ExaBGP lost the helper process for this peer - stopping
The os on the server is Debian.

**Comment by thomas-mangin** [comment]
ExaBGP just told you what is wrong: "ExaBGP lost the helper process for this peer".
I wish you good luck finding out why .. this is not a bug with ExaBGP.

**Comment by ZhiYiFang** [comment]
I have solved the problem. 
Running exabgp with root privileges will produce this problem.
We can change the environment to solve the problem.
1. Create a file : /usr/local/etc/exabgp/exabgp.env
2. Execute : exabgp --fi > /usr/local/etc/exabgp/exabgp.env
3. Edit the /usr/local/etc/exabgp/exabgp.env and change user = 'nobody' to user = 'root'
Finally, exabgp will run with this environment file.
If you also execute exabgp with root privileges, you can solve the problems by these steps. 
Hope it can help others.

**Comment by markusju** [comment]
Thanks, @ZhiYiFang Thank you, you left a helpful comment here :)

@thomas-mangin This is a kind of a default configuration setting issue in my view. Also it seems distribution packages put "exabgp" in /usr/sbin/ which makes this issue worse, as users are tempted to run exabgp as root with these default settings.
