### ISSUE TITLE
Poetry usage

### ISSUE THREAD

**Issue by ahmet2mir** [Exa-Networks/exabgp#1021]
Hello,

I see that exabgp uses pyproject and do you think that we could completly move to poetry and remove setuptools things ?

I mean setup.py requirements.txt are useless with poetry.

I have a local copy with a Makefile to setup fmt test build upload etc without setup.py, I could create a MR

**Comment by thomas-mangin** [comment]
Poetry is under try in master. The stable branch does not use it.

**Comment by ahmet2mir** [comment]
Do you wan't that I create a MR to test it up to eleven ? :)

**Comment by ahmet2mir** [comment]
Added the pull request, you could check @thomas-mangin (it's what I will to package and release exabgp internally)

**Comment by thomas-mangin** [comment]
Thank you, I will look into it when I have a little bit of time.
