### ISSUE TITLE
Enforce commit signature verification

### ISSUE THREAD

**Issue by ZiqianXu** [Exa-Networks/exabgp#1024]
Hi exabgp dev,

I noticed all the exabgp releases do not have signature verification, so when download the source tarball to our system, we can not be assured that your commits come from a trusted source.

Can exabgp sign tags and commits locally using GPG or S/MIME? Therfore these tags or commits are marked as verified on GitHub so other people can trust that the changes come from a trusted source.

https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification

Thanks

**Comment by thomas-mangin** [comment]
This may be something we do but would probably be part of a commercial offering.

**Comment by erahn** [comment]
Thomas - at the very least is it possible to make sure your tags are verified when signing those on github? It seems that the majority of those are not even signed.

**Comment by thomas-mangin** [comment]
releases are now PGP signed (from 4.2.19)
