### ISSUE TITLE
FlowSpec traffic-rate 2-bytes as# updates

### ISSUE THREAD

**Issue by eitanick** [Exa-Networks/exabgp#1026]
Hey Thomas,
I have a project in which I've been trying to configure the AS value of traffic rate.
I am using your EXABGP version 3.4.23, and was wondering whether there has been an update regarding setting the as# in the traffic-rate.
Do you know of any way of setting the router AS through the exabgp.conf?
Communities: traffic-rate:0:1000 is the line I want to set in the router.
thanks,

**Comment by thomas-mangin** [comment]
The only rate-limiting possibly configured via BGP is using flowspec and this does not have an ASN:
https://github.com/Exa-Networks/exabgp/blob/master/etc/exabgp/conf-flow.conf#L40

So I am not fully understanding what you are trying to achieve. What BGP feature / RFC are you looking to get working?
