### ISSUE TITLE
flowspec issue with flow nlri with match not-a-fragment

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#1027]
From a private email:

There are issues with processing incoming bgp packets with flow nlri matches fragment flag not-a-fragment by exabgp.
Exabgp sends these packets with zero fragment type byte. But when it receives the same packets BitResource can not return name of this zero bit, although there is in the names of Fragment. Zero is not a bit and matches nothing.

```
--- protocol/resource.py.orig   2020-08-14 20:00:17.000000000 +0300
+++ protocol/resource.py        2021-03-13 10:58:07.695201253 +0300
@@ -61,7 +61,7 @@
     def bits(self):
         value = int(self)
         for bit in self.names.keys():
-            if value & bit:
+            if value & bit or value == bit:
                 yield self.names[bit]
                 value -= bit
         if value:
```

When you match for not-a-fragment Juniper produces packet with set NOT and IsF bytes. And this packet exabgp interprets in json as "is-fragment" and at the same time in compatibility string extensive and _rules set it as "!is-fragment". It's done due to bit processing doesn't consider operator flags in json.

For example when juniper matches not-a-fragment and is-fragment flags, it generates fragment type set to NOT+IsF and IsF (0C 0202 8002).
```
NLRI      ipv4 flow          without path-information     payload 2801 20C0 A800 0202 18C0 A8FF 0301 0681 1104 0117 0115 13FD E9D5 FFFF 0A03 0045 6391 FFFF 0C02 0280 02
update json { "neighbor": { "message": { "update": { "announce": { "ipv4 flow": { "fragment": [ "is-fragment", "is-fragment" ], "string": "flow fragment [ !is-fragment is-fragment ]" } ] } } } } } }
```

So there are different mapping of fragment type in json and compatibility. And if turn off special processing of FLAG the fragment will be the same.

```
--- bgp/message/update/nlri/flow.py.orig        2020-08-14 20:00:17.000000000 +0300
+++ bgp/message/update/nlri/flow.py     2021-03-13 11:25:24.345709730 +0300
@@ -637,7 +637,12 @@
                 if idx and not rule.operations & NumericOperator.AND:
                     s.append(', ')
                 if rule.FLAG:
-                    s.append(', '.join('"%s"' % flag for flag in rule.value.named_bits()))
+                    op = rule.operations & (CommonOperator.EOL ^ 0xFF)
+                    op_flag = rule._string.get(op, "")
+                    s.append(', '.join('"%s%s"' % (op_flag, flag) for flag in rule.value.named_bits()))
+                    if rule.ID == 0x0C:
+                        if s[-1]:
+                            s[-1] = s[-1].replace('!is-fragment', rule.value.names.get(rule.value.NOT))
                 else:
                     s.append('"%s"' % rule)
             string.append(' "%s": [ %s ]' % (rules[0].NAME, concat_strs_i(str(_) for _ in s).replace('""', '')))
```

**Comment by thomas-mangin** [comment]
@vincentbernat are you fine if I merge this request?

**Comment by vincentbernat** [comment]
Are you sure it's me you wanted to tag? I don't think I have ever worked on this part of the code :)

**Comment by thomas-mangin** [comment]
🤦 wrong issue !
