### ISSUE TITLE
API Deadlock with large amounts of route announce

### ISSUE THREAD

**Issue by mavericm1** [Exa-Networks/exabgp#1034]
** Bug Report **

last message in -d 

19:53:48 7      process         responding to add-remove-v4 : done

**Describe the bug**

using nlri routes in api-add-remove.run

```
#!/usr/bin/env python

import os
import sys
import time

messages = [
'announce attributes origin IGP as-path [1 2 3 4] med 100 local-preference 100 community [1:1 2:2] next-hop 2.2.2.2 nlri 1.0.0.0/24 1.0.1.0/24',
^lots of lines like above parsed from mrt table dump
'stop'
]

time.sleep(60)
while messages:
    message = messages.pop(0)
    if message == 'stop':
        break
    sys.stdout.write(message + '\n')
    sys.stdout.flush()
    time.sleep(0.000003)

while True:
    time.sleep(5)



**To Reproduce**

testing i am able to move the stop line just before where the deadlock occurs and it will no longer deadlock.   It isn't the next api announce api message either as i can comment out this line and it fails at the next below.   it happens at ~13106 message in the api code.  

i'm able to send ipv4 unicast 212713 routes and ipv6 mpls-nlri ipv4 15046 routes

**Expected behavior**

allow for sending as many routes as needed.

**Environment (please complete the following information):**

ExaBGP : 4.2.6
Python : 3.9.5 (default, May 12 2021, 15:36:59)  [GCC 8.3.0]
Uname  : Linux 073a94fef398 5.4.0-70-generic #78~18.04.1-Ubuntu SMP Sat Mar 20 14:10:07 UTC 2021 x86_64


**Additional context**

api ack is disabled.

exabgp.log.configuration=true
exabgp.tcp.acl=false
exabgp.tcp.port=179
exabgp.log.level=INFO
exabgp.log.packets=false
exabgp.log.parser=false
exabgp.log.enable=true
exabgp.log.all=false
exabgp.daemon.pid=/etc/exabgp/exabgp.pid
exabgp.daemon.umask=0o137
exabgp.api.cli=true
exabgp.api.ack=false
exabgp.tcp.delay=0
exabgp.log.network=true
exabgp.log.reactor=true
exabgp.daemon.user=root
exabgp.api.respawn=true
exabgp.log.processes=true
exabgp.log.daemon=true
exabgp.daemon.drop=true
exabgp.log.routes=true
exabgp.bgp.openwait=60
exabgp.profile.enable=false
exabgp.api.terminate=false
exabgp.cache.attributes=false
exabgp.reactor.speed=1.0
exabgp.log.message=false
exabgp.log.rib=false
exabgp.api.compact=false
exabgp.api.chunk=1
exabgp.pdb.enable=false
exabgp.bgp.passive=false
exabgp.tcp.once=false
exabgp.log.short=true
exabgp.cache.nexthops=false
exabgp.tcp.bind=192.168.65.50
exabgp.log.destination=/var/log/exabgp.log
exabgp.api.pipename=exabgp
exabgp.api.encoder=json
exabgp.daemon.daemonize=false
exabgp.log.timers=false

**Comment by thomas-mangin** [comment]
Looks to me that ack is not disabled. Please text by running with prefixing with env forcing it off.

**Comment by mavericm1** [comment]
That appears to be working the environment variable is set to false so i'm not exactly sure why it would work setting it at runtime vs it being just set as an environment variable in this case i'm setting it in ENV in a Dockerfile.

# how to build and run exabgp using docker (using github)
# this Dockerfile does not require a local installation

# docker build --build-arg version=master -f Dockerfile.remote  -t exabgp.remote ./
# docker run -it exabgp.remote exabgp

FROM python:3-slim-buster

ARG version="master"



ENV exabgp.profile.enable=false \
exabgp.pdb.enable=false \
exabgp.daemon.pid=/etc/exabgp/exabgp.pid \
exabgp.daemon.user=root \
exabgp.daemon.daemonize=false \
exabgp.daemon.drop=true \
exabgp.daemon.umask=0o137 \
exabgp.log.enable=true \
exabgp.log.level=INFO \
exabgp.log.destination=/var/log/exabgp.log \
exabgp.log.all=false \
exabgp.log.configuration=true \
exabgp.log.reactor=true \
exabgp.log.daemon=true \
exabgp.log.processes=true \
exabgp.log.network=true \
exabgp.log.packets=false \
exabgp.log.rib=false \
exabgp.log.message=false \
exabgp.log.timers=false \
exabgp.log.routes=true \
exabgp.log.parser=false \
exabgp.log.short=true \
exabgp.tcp.once=false \
exabgp.tcp.delay=0 \
exabgp.tcp.bind=192.168.65.50 \
exabgp.tcp.port=179 \
exabgp.tcp.acl=false \
exabgp.bgp.passive=false \
exabgp.bgp.openwait=60 \
exabgp.cache.attributes=false \
exabgp.cache.nexthops=false \
exabgp.api.ack=false \
exabgp.api.chunk=1 \
exabgp.api.encoder=json \
exabgp.api.compact=false \
exabgp.api.respawn=true \
exabgp.api.terminate=false \
exabgp.api.cli=true \
exabgp.api.pipename=exabgp \
exabgp.reactor.speed=1.0 \
    APP_HOME=/etc/exabgp

RUN apt update \
    && apt -y dist-upgrade \
    && apt install -y git net-tools nano\
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

RUN cd /tmp \
    && echo Building ${version} \
    && pip install -U setuptools \
    && pip install git+https://github.com/Exa-Networks/exabgp.git@${version}

WORKDIR $APP_HOME

# CMD exabgp -d $APP_HOME/exabgp.conf  <----doesn't work

CMD env exabgp.api.ack=false exabgp -d $APP_HOME/exabgp.conf   <---works   but as you can see ENV variables are set above.


##### even running exabgp env  shows that its set correct with the docker ENV variables 
 docker exec exabgp exabgp env

[exabgp.api]
ack = false
chunk = 1
cli = true
compact = false
encoder = json
pipename = 'exabgp'
respawn = true
terminate = false

[exabgp.bgp]
openwait = 60
passive = false

[exabgp.cache]
attributes = false
nexthops = false

[exabgp.daemon]
daemonize = false
drop = true
pid = '/etc/exabgp/exabgp.pid'
umask = '0o137'
user = 'root'

[exabgp.log]
all = false
configuration = true
daemon = true
destination = '/var/log/exabgp.log'
enable = true
level = INFO
message = false
network = true
packets = false
parser = false
processes = true
reactor = true
rib = false
routes = true
short = true
timers = false

[exabgp.pdb]
enable = false

[exabgp.profile]
enable = false
file = ''

[exabgp.reactor]
speed = 1.0

[exabgp.tcp]
acl = false
bind = '192.168.65.50'
delay = 0
once = false
port = 179

**Comment by thomas-mangin** [comment]
It could be that the "." is not working and that you need to use "_" in the environment variables when set via docker. This is a sysadmin question about how docker work and not a bug with ExaBGP.

As I am no docker expert, I will let you investigate. Good luck !
