### ISSUE TITLE
Socket remains in CLOSED state after the interface goes down. Peer cannot reconnect afterwards. Fix suggested.

### ISSUE THREAD

**Issue by borjam** [Exa-Networks/exabgp#1035]
** Bug Report **

**Describe the bug**

At least it happens on FreeBSD 12.2 and FreeBSD 13, ExaBGP 4.2.11 with Python 3.7. It happened to me on 
a configuration with three peers, it would fail to reconnect to two of them. This is a regression, it worked perfectly
on ExaBGP 3 with Python2.7.

Simple symptom: ExaBGP running, interface goes down (I rebooted the switch). After the switch
goes alive again and the interface recovers, ExaBGP cannot connect again to the peer.

Thu, 27 May 2021 11:36:49 52422  outgoing-4    connection to 192.168.1.1:179 failed
Thu, 27 May 2021 11:36:49 52422  outgoing-4    Could not connect to peer 192.168.1.1:179 ([Errno ECONNREFUSED] [Errno 61] Connection refused)
Thu, 27 May 2021 11:36:50 52422  outgoing-4    attempting connection to 192.168.1.1:179
Thu, 27 May 2021 11:36:50 52422  outgoing-4    connection to 192.168.1.1:179 failed
Thu, 27 May 2021 11:36:50 52422  outgoing-4    Could not connect to peer 192.168.1.1:179 ([Errno ECONNREFUSED] [Errno 61] Connection refused)
Thu, 27 May 2021 11:36:51 52422  outgoing-4    attempting connection to 192.168.1.1:179
Thu, 27 May 2021 11:36:51 52422  outgoing-4    connection to 192.168.1.1:179 failed

Using netstat I noticed a connection staying in CLOSED state. It seemed that ExaBGP was reusing the socket without closing it properly before issuing a connect() again. 

**To Reproduce**

In my case, rebooting a switch so that the Ethernet interface of the FreeBSD box goes down. That makes the connection fail and it failed to reconnect.

**Expected behavior**

It should reconnect once the network is recovered. Indeed there is connectivity after the switch has rebooted, but it fauls to reconnect while a socket remains in CLOSED state. 

**Environment (please complete the following information):**

 - OS: [e.g. OSX, Ubuntu, ..]
 - Version [e.g. master, pip version installed, ... ]

SUGGESTED FIX:

Using the spaghetti launching approach I noticed that there is one instance on outgoing.py in which the socket is not closed after a connection failure. 

    def _connect(self):
        if not self.io:
            setup_issue = self._setup()
            if setup_issue:
                return setup_issue
        try:
            connect(self.io, self.peer, self.port, self.afi, self.md5)
            return None
        except NetworkError as exc:
            return exc

Adding this:
    self.io.close()
    self.io = None

before the last return exc 

so it becomes

    def _connect(self):
        if not self.io:
            setup_issue = self._setup()
            if setup_issue:
                return setup_issue
        try:
            connect(self.io, self.peer, self.port, self.afi, self.md5)
            return None
        except NetworkError as exc:
            self.io.close()
            self.io = None
            return exc

seems to solve it. I guess it's not the best place (I guess the socket should have been closed after a previous exception when the interface was shut down) but at least this breaks the vicious circle. Now, when I reboot the switch ExaBGP is able to recover completely.

**Comment by thomas-mangin** [comment]
Thank you for the report and fix 👍

**Comment by borjam** [comment]
> On 27 May 2021, at 16:35, Thomas Mangin ***@***.***> wrote:
> 
> 
> Thank you for the report and fix 👍

Thank _you_ for this useful program! :)

A pleasure. Thankfully that one was easy to spot!





Borja.

**Comment by borjam** [comment]
I have just checked 4.2.13 (which for example is the current version offered on FreeBSD ports) and I noticed that the fix for this bug wasn't included?

Looking at the relevant file, reactor/network/outgoing.py

I see this: After an exception the socket is not closed explicitly. Is this correct (ie is it being closed upstream) or did you miss the bug fix?



    def _connect(self):
        if not self.io:
            setup_issue = self._setup()
            if setup_issue:
                return setup_issue
        try:
            connect(self.io, self.peer, self.port, self.afi, self.md5)
            return None
        except Exception as exc:
            return exc



Cheers

**Comment by borjam** [comment]
Yep, the bug is back on 4.2.13.

root@elnuc:/usr/ports/net/exabgp4 # netstat -f inet -n | fgrep 179
tcp4       0      0 192.168.1.155.21959    192.168.1.1.179        CLOSED     
tcp4       0      0 192.168.1.155.26247    192.168.1.195.179      CLOSED    

This happened after disabling the switch port for several minutes. ExaBGP is stuck.

**Comment by borjam** [comment]
I see it was my fault :/ I reported it for 4.2.11 but 4.2.13 already existed and I didn't notice :/ Same bug.

Sorry.
