### ISSUE TITLE
Unable to build 4.2.13 package

### ISSUE THREAD

**Issue by Firm** [Exa-Networks/exabgp#1046]
Running **python2 setup.py build** on 4.2.13 sources does nothing comparing to 3.4.28 release.

How to reproduce:
tar zxf exabgp-3.4.28.tar.gz
cd exabgp-3.4.28
python2 setup.py build
[lots of output]

tar zxf exabgp-4.2.13.tar.gz
cd exabgp-4.2.13
python2 setup.py build
(nothing happens)

**Comment by Firm** [comment]
It looks that pyrhon2 support is broken. Changing to python3 explicitly make things much better. Spec file need to be updated then.

**Comment by thomas-mangin** [comment]
Yes, exabgp 4 is python3 only.

**Comment by Firm** [comment]
redhat/python-exabgp.spec uses python2.

**Comment by Firm** [comment]
One more question: does python-ipaddr package (centos 7) fit into python3?

**Comment by thomas-mangin** [comment]
converted the spec file to python3 (pure guesswork)

**Comment by thomas-mangin** [comment]
I am keeping this open to review and warn that the code does not work with python2 anymore

**Comment by thomas-mangin** [comment]
the code using ipaddr need converting.
