### ISSUE TITLE
could not send command to ExaBGP (command timeout)[

### ISSUE THREAD

**Issue by heyjacleu** [Exa-Networks/exabgp#1050]
I was able to get exabgp running on Centos7 and I am peering with my test router no problem. I am not able to get the exabgpcli command working though. When I attempt to send any command, like show neighbor summary, the following error occurs.

[tester@exabgptest1:/opt/exabgp/bin]$ ./exabgpcli show neighbor summary
command: show neighbor summary
could not send command to ExaBGP (command timeout)

I'm very new to this so maybe something simple I'm missing and could  use some direction where to look to troubleshoot.

**Comment by thomas-mangin** [comment]
The CLI is not enabled by default, if you read the output of ExaBGP it does tell how to set it up.

**Comment by heyjacleu** [comment]
Thanks. I don't see anything in the output that talks about enabling it or are you referring to another output?  This was installed via git clone.

● exabgp.service - ExaBGP
   Loaded: loaded (/etc/systemd/system/exabgp.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2021-09-22 17:24:06 UTC; 1 day 1h ago
     Docs: man:exabgp(1)
           man:exabgp.conf(5)
           https://github.com/Exa-Networks/exabgp/wiki
  Process: 3363 ExecStartPre=/bin/bash -c /usr/bin/mkfifo -m 0666 /opt/exabgp/src/exabgp/application/run/exabgp.{in,out} (code=exited, status=0/SUCCESS)
  Process: 3361 ExecStartPre=/bin/mkdir /opt/exabgp/src/exabgp/application/run (code=exited, status=0/SUCCESS)
 Main PID: 3367 (python3)
   CGroup: /system.slice/exabgp.service
           └─3367 /usr/bin/python3 /opt/exabgp/src/exabgp/application/main.py /etc/exabgp/exabgp.conf

**Comment by thomas-mangin** [comment]
This is really an UNIX system administration question. I _ASSUME_ that it may be a user and/or permission accessing the files preventing things to work.

It is not an issue with the software itself but I will admit to having no documentation on these matters, which will not help you much.

I am not using or maintaining Redhat/CentOS packages, and I do not know who does. I develop using OS X and the team at Exa run ExaBGP on Ubuntu.

Users contributed system.d file in the repository, I do not know where you got yours from.
https://github.com/Exa-Networks/exabgp/blob/master/etc/systemd/exabgp.service

Perhaps someone on the slack channel may be able to give you advice / have figured out what to do.

**Comment by heyjacleu** [comment]
Ok, I was able to get by using sbin so probably I'll just need to dig some more from my end. This was cloned from your github here FYI
https://github.com/Exa-Networks/exabgp.git

Thanks for pointing out the slack channel. I'll def make use of that.

**Comment by thomas-mangin** [comment]
@heyjacleu in that case you should update to the latest master (b46c65e6f9ae8e689fff6dc9484eb21b05071bae at time of writing) or use the lastest (4.2.15) release :-)
