### ISSUE TITLE
Are Flowspec TCP_Flags CWR, ECE and NS supported

### ISSUE THREAD

**Issue by enag11** [Exa-Networks/exabgp#1052]
** Bug Report **

**Describe the bug**
When will exabgp4 support tcp flags CWR, ECE and NS.

RFC 7125 contains the updated changes for RFC 793 and RFC3168.  RFC 7125 includes the TCP header definitions for NS, CWR, ECE, URG, ACK, PSH, RST, SYN, FIN

**Comment by thomas-mangin** [comment]
Hi there 👋 it is a feature request and not a bug. And unless people are offering to pay for my time to add features or fix bugs, I would appreciate if I was the one deciding to assign myself to issues. Thank you.

**Comment by enag11** [comment]
Hi Thomas, it was not my intention to assign or dictate your work but when I opened my two issues they were automatically assigned.  I will open this issue as a feature.  Thanks for the direction

**Comment by enag11** [comment]
Closing Bug Report and opening a Feature request
