### ISSUE TITLE
BGP incorrect aspath path element handling

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [Exa-Networks/exabgp#1055]
** Bug Report **

**Describe the bug**

https://datatracker.ietf.org/doc/html/rfc4271#section-5.1.2
https://datatracker.ietf.org/doc/html/rfc5065#section-3

AS_PATH path attribute is an **ordered** list of path elements of type AS_SET / AS_SEQUENCE / AS_CONFED_SEQUENCE / AS_CONFED_SET

currently exabgp implementation assumes

- the list is unordered
- path element of each type show up at most once

neither of these assumptions is RFC-compliant

**To Reproduce**

receive BGP update with AS_PATH 300 {301,302} 303

**Expected behavior**

exabgp should be able to retain the aspath ordering

**Environment (please complete the following information):**

**Additional context**

For reference BIRD's handling of aspath element types (ordered, each path element type can appear any number of times) https://gitlab.nic.cz/labs/bird/-/blob/master/nest/a-path.c#L370

exabgp puts each path element type into its own field (not retaining order of path elements, does not support a path element type showing up more than once)
https://github.com/Exa-Networks/exabgp/blob/0fcaf2cabe1e1148361a021517629d963dea3eed/src/exabgp/bgp/message/update/attribute/aspath.py#L134-L141

**Comment by thomas-mangin** [comment]
Thank you for that, I will into changing the code on master.

**Comment by thomas-mangin** [comment]
The functional testing is working but it could be that some tests and/or other things need checking. This is a initial release to allow feedback.
