### ISSUE TITLE
Support for BGP AFI 16388 SAFI 72 (RFC7752)

### ISSUE THREAD

**Issue by hkml2000** [Exa-Networks/exabgp#1056]
Dears,

I'm working on topology acquisition through BGP-LS from a Juniper devices,

It works fine when I export TED database,

but when I try to export IGP Database (to have information about non RSVP links), the BGP session with exaBGP goes down with the following message on juniper:    

**unsupported AF 16388 SAFI 72**

here is the additional config on juniper to export IGP topology
**set protocols ospf traffic-engineering igp-topology
set protocols mpls traffic-engineering database import igp-topology bgp-link-state**

Is there a plan to implement, in a future releases, SAFI 72 as described in RFC7752 ?

Thanks a lot!

**Comment by thomas-mangin** [comment]
Yes, this is the correct fix :-) the 4.2 branch was updated. Master is not affected as the code changed quite a bit and this was already changed as a side effect.
