### ISSUE TITLE
Bash Script in Health check Not Working

### ISSUE THREAD

**Issue by mike53187** [Exa-Networks/exabgp#1059]
Full disclosure, I'm a network engineer so understand BGP very well, but Linux on the other hand I'm very junior. Anyways, I have BGP functional.. at least the neighbors are up and running, but no routes are being exchanged. I want to leverage anycast and would like the advertisement of the anycast address to be conditional. I wrote a very simple bashscript that works, but I can't seem to get an integrated into the exabgp process correctly because everytime I try and restart exabgp it fails. I keep getting the error "Too many death for SplunkUpdate (5) terminating program"
Here's the bash script:
#!/bin/bash

HOST=[ip address goes here]

ping $HOST -c 1 -t 30 &> /dev/null
pingReturn=$?

if [ $pingReturn -eq 0 ]; then
        systemctl is-active [service to verify it's running] && echo announce route [this would be the anycast address]/32 next-hop self
    exit 0
else
    # No access
    echo "Fail"
    exit 1
fi
Here's the config file that keeps failing when I try to integrate:
process SplunkUpdate {
                run ./[the above bash script];
                encoder text;
        }

neighbor 192.168.109.55 {
    router-id 192.168.108.33;
    local-address 192.168.108.33;
    local-as 65000;
    peer-as 65000;

    capability {
        graceful-restart;
        }
    api {
        processes [ SplunkUpdate ];
}

}
___________________

I've tried all sorts of things to get it to work, so any help/guidance would be appreciated. Thanks in advance.
ExaBGP : 4.2.6
Python : 3.6.8 (default, Sep  9 2021, 07:49:02)  [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
Uname  : Linux Lab-DNS.pickles.com 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 8 13:30:15 EST 2021 x86_64
Root   : /opt/exabgp

**Comment by thomas-mangin** [comment]
Yes, indeed: your script must not terminate (therefore calling exit is a no-no). There is plenty of examples in the etc folder of the repository.

There is already an healthcheck coming with ExaBGP:
https://vincent.bernat.ch/en/blog/2013-exabgp-highavailability

depending on your installed version the way to call it may have changed:
https://github.com/Exa-Networks/exabgp/issues/1058

**Comment by mike53187** [comment]
> Yes, indeed: your script must not terminate (therefore calling exit is a no-no). There is plenty of examples in the etc folder of the repository.
> 
> There is already an healthcheck coming with ExaBGP: https://vincent.bernat.ch/en/blog/2013-exabgp-highavailability
> 
> depending on your installed version the way to call it may have changed: #1058

Thanks Thomas. I fixed the bash script, but still getting the error. I found plenty of examples in the etc folder and I've tried multiple variations to no avail. Now, I feel like I'm just throwing darts and hoping something sticks. LOL. Alot of the documentation I'm finding look to be old versions which don't work with my version.
I'm using version 4.2.6

**Comment by thomas-mangin** [comment]
Hi Mike,

If you still see that error, it is unlikely that you really fixed your script (otherwise it would work 😉). I appreciate your difficulty, I wish you good luck to get to grip with Unix and bash programming.

I will once more point you toward the build-in checker unless you are doing something really bespoke as it was well documented by Vincent and is well written.

It is true that a lot of documentation is written for 3.4 but you can keep it working by following the information on this page.
https://github.com/Exa-Networks/exabgp/wiki/Migration-from-3.4-to-4.0

4.6 is quite old but should work as expected, what you are seeing is not a bug in the code.

**Comment by mike53187** [comment]
Hi Thomas, you were right on the bash script... i ended up creating a for loop. I ended up having to make a few other changes.... the way I was calling the script in the config file was wrong too and the service lacked permissions to /run/exabgp.in and /run/exabgp.out (what are these actually for?).  thanks so much for your help and for suppporting exabgp.... we will be using it for load balancing anycast services.

**Comment by mike53187** [comment]
this guide really helped me because it was written using the 4.x code:
https://www.dasblinkenlichten.com/working-with-exabgp-4/
