### ISSUE TITLE
Adding update message sequencing/keys

### ISSUE THREAD

**Issue by spakka** [Exa-Networks/exabgp#106]
It would be useful for later ordering/sequencing of update messages (for later playback into a RIB state machine from a database of updates, for example), if the received messages (parsed or raw) output had a sequence counter on them.

Thanks
Colin

**Comment by fobser** [comment]
Does this need a config option? As far as I can tell from the code it should always do this.
I'm expecting a field 'counter' in json, but it's not there:

{
  "neighbor": {
    "message": {
      "update": {
        "announce": {
          "ipv4 unicast": {
            "193.0.4.28": {
              "41.221.108.0/23": {},
              "41.221.105.0/24": {}
            }
          }
        },
        "attribute": {
          "community": [
            [
              3257,
              8077
            ],
            [
              3257,
              30100
            ],
            [
              3257,
              50003
            ],
            [
              3257,
              58520
            ],
            [
              3257,
              58521
            ]
          ],
          "atomic-aggregate": false,
          "confederation-path": [],
          "as-path": [
            12654,
            3257,
            6762,
            36969,
            36969,
            36969
          ],
          "origin": "igp"
        }
      }
    },
    "asn": {
      "peer": "12654",
      "local": "65000"
    },
    "address": {
      "peer": "193.0.4.28",
      "local": "193.0.19.22"
    },
    "ip": "193.0.4.28"
  },
  "exabgp": "3.4.6",
  "time": 1430732098.32,
  "host": "rrc-test.ripe.net",
  "pid": "7992",
  "ppid": "1",
  "type": "update",
  "header": "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF005F02",
  "body": "00000040400101005002001A02060000316E00000CB900001A6A000090690000906900009069400304C100041CC008140CB91F8D0CB975940CB9C3530CB9E4980CB9E4991829DD691729DD6C"
}

with this configuration:

    process receive-routes {
        encoder json;
	run /opt/exabgp/bin/queuer.py /export/exabgp/message-queues/0;
        receive {
            updates;
            parsed;
            packets;
            consolidate;
            open;
            keepalive;
            neighbor-changes;
        }
    }

Thanks!

**Comment by thomas-mangin** [comment]
No, I will check the code. It may be that only the time was implemented but adding it would not be too hard

**Comment by thomas-mangin** [comment]
https://github.com/thomas-mangin/exabgp/commit/ad02f855cfdcdfa0a1fcdbf0702b4e3eaaad0a6d
Let me know if you need this back ported to 3.4 ( as the patch does not apply as it ).

**Comment by fobser** [comment]
On 07/05/15 21:09, Thomas Mangin wrote:
> thomas-mangin@ad02f85 <https://github.com/thomas-mangin/exabgp/commit/ad02f855cfdcdfa0a1fcdbf0702b4e3eaaad0a6d>
> Let me know if you need this back ported to 3.4 ( as the patch does not apply as it ).

that would be very helpful there are just to many changes in your repo that break
stuff on our end.

**Comment by thomas-mangin** [comment]
I feared you would say that ..  :sob:

**Comment by thomas-mangin** [comment]
Hello, could you please check that the 3.4 branch does what you expect it to do ?

**Comment by fobser** [comment]
works for me, thanks!

**Comment by thomas-mangin** [comment]
Thank you (again) for checking
