### ISSUE TITLE
Can some one help in sharing commands to announce l2vpn evpn type 2 and type 5 routes 

### ISSUE THREAD

**Issue by Shaffath** [Exa-Networks/exabgp#1061]

**Comment by thomas-mangin** [comment]
Please have a look into the etc/ folder of the repository for examples.

**Comment by Shaffath** [comment]
Thanks @thomas-mangin .. i already had a look into the folder.. i dont see any announce commands example for l2vpn evpn routes via exabgp cli.. i see only l2vpn vpls command only. am i missing something ?

**Comment by thomas-mangin** [comment]
I have implemented it years ago and never used it. I can only invite you to read the RFC which should help you connect your operational understanding with what is required, unfortunately, I will not be able to help you more than that.

**Comment by thomas-mangin** [comment]
I take from the lack of feedback that you are on your own, you could ask on slack ...
