### ISSUE TITLE
NS Flag Error in 4.2.16 

### ISSUE THREAD

**Issue by enag11** [Exa-Networks/exabgp#1064]
I've been using the master build and the tcp flags fix is good but when I switched to 4.2 6bd3dfa build, flag NS returns
error message: ord() expected a character, but string of length 2 found

CWR and ECE flags are good.  This is in reference to feature fix #1053

**Comment by thomas-mangin** [comment]
It was not released .. now in 4.2.17 ..
https://github.com/Exa-Networks/exabgp/releases/tag/4.2.17

**Comment by enag11** [comment]
Thanks Thomas
