### ISSUE TITLE
raw message output as well as parsed

### ISSUE THREAD

**Issue by spakka** [Exa-Networks/exabgp#107]
Hi,

It would be useful to be able to output a json object containing the raw message, in addition to the parsed version. This would allow easy conversion of the messages into MRT update format. This should also be synchronised with parsed message (if both messages contain the same unique key) so they can be correlated later.

This also means we capture the raw data to parse at a later date for new attributes etc that are not currently understood by the parser.

Thanks
Colin

**Comment by fobser** [comment]
Hi,
so we have raw messages for OPEN, UPDATE and KEEPALIVE.
NOTIFICATION messages seem to be missing entirely. A parsed version is transported in type: "state" message in json:

```
{
  "neighbor": {
    "reason": "out loop, peer reset, message [notification received (6,1)] error[Cease / Maximum Number of Prefixes Reached]",
    "state": "down",
    "asn": {
      "peer": "65002",
      "local": "65001"
    },
    "address": {
      "peer": "193.0.10.47",
      "local": "193.0.10.124"
    }
  },
  "type": "state",
  "counter": 10,
  "ppid": 13520,
  "pid": 2572,
  "host": "rrc.guestnet.ripe.net",
  "time": 1432811720.02,
  "exabgp": "3.5.0"
}
```

Can we have a dedicated type: "notification" message with the raw message?
Maybe exabgp can already do that and it's only a configuration error on my end:
```
    process receive-routes {
        encoder json;
        run /opt/exabgp/bin/queuer.py;
        neighbor-changes;
        receive {
           update;
           parsed;
           packets;
           consolidate;
           open;
           keepalive;
           notification;
        }
    }
```

Thanks,
Florian

**Comment by thomas-mangin** [comment]
It should have been sent, I will investigate.

**Comment by thomas-mangin** [comment]
ok should now be fixed both in the 3.4 branch and master.

**Comment by thomas-mangin** [comment]
PS: please open new issues for new bugs (even if related) otherwise I may miss the comment.

**Comment by fobser** [comment]
On 28/05/15 14:55, Thomas Mangin wrote:
> PS: please open new issues for new bugs (even if related) otherwise I may miss the comment.
> 

Thanks, I was actually wondering what you prefer (new or reopen). Will do the next time.
I'll test asap.
