### ISSUE TITLE
Two additional icmp-type additions

### ISSUE THREAD

**Issue by enag11** [Exa-Networks/exabgp#1073]
As a follow-up to #1069 can the following two icmp-types also be added and include in exabgp4 
253	RFC3692-style Experiment 1	[RFC4727]
254	RFC3692-style Experiment 2	[RFC4727]

Thanks

**Comment by thomas-mangin** [comment]
also in commit 430aaf21f71cf1a730e1918683b58bec0fe1e1eb

**Comment by enag11** [comment]
Thank-you

**Comment by enag11** [comment]
Pulled the latest version, exabgp 4.2.18, and see #1073 fix but do not see #1069 where icmp-types 40, 41, 42, 43 were added
