### ISSUE TITLE
Release is 4.218 not 4.2.18?

### ISSUE THREAD

**Issue by garybuhrmaster** [Exa-Networks/exabgp#1076]
Was it intentional for the latest release to be 4.218 and not (the sort of expected) 4.2.18?

**Comment by thomas-mangin** [comment]
Thank you for reporting it, fixed it but it is weird ..

```
> git log --oneline --decorate --graph
* 20d2936c (HEAD -> 4.2, origin/4.2) force use of python3 on release
* 026f2f39 fix tag release
* 25113b70 use tag -s when releasing
* 75bbea8e (tag: 4.2.18) updating version to 4.2.18
* 4e1fde90 update release note
* a6695841 ICMP experimental codes, closes #1073
* aac654d7 add FBGP to readme
* 29d4a27a preparation for 4.2.18
* e3f1dba3 (tag: 4.2.17) updating version to 4.2.17
```

```
❯ git tag -l | grep 18
3.2.18
3.4.18
4.2.18
```

So the tag is well 4.2.18, but I could see like you on the release page it being presented as 4.218 ...
I edited the released picking it again and it now correctly shows `4.2.18` ... The commit ID linked did not change. It is listed as `75bbea8` - not sure why the final `e` is not showing if you compare with git log.

So I am not not sure why a tag which did not exist was referenced but I fixed whatever was wrong ...
