### ISSUE TITLE
bgpls: TypeError when json encoding link igpmetric (isis wide metric case)

### ISSUE THREAD

**Issue by ds3366714** [Exa-Networks/exabgp#1079]
```bash
$ exabgp --version
ExaBGP : 4.2.18
Python : 3.10.4 (main, Apr  2 2022, 12:32:41) [GCC 9.4.0]
Uname  : Linux xxxx 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64
```

```python
lib/python3.10/site-packages/exabgp/bgp/message/update/attribute/bgpls/link/igpmetric.py", line 62, in json
    return '"igp-metric": %d' % int(self.igpmetric)
 TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'
```

TypeError is raised as the following line returns a list instead of int.

https://github.com/Exa-Networks/exabgp/blob/6d3ee0b789f45f3977ac4d1e83d88f0e3b9b22cd/lib/exabgp/bgp/message/update/attribute/bgpls/link/igpmetric.py#L56

**Comment by thomas-mangin** [comment]
Thank you, I have fixed this particular issue but there are a few issues with the BGP-LS in 4.2. The code is better in master after a refactoring (as I was not the original author). 

You could/should use master if you intend to use bgp-ls as I do not think I will be backporting the changes.
