### ISSUE TITLE
API presentation of capability negotiation

### ISSUE THREAD

**Issue by spakka** [Exa-Networks/exabgp#108]
It would be great if we could get additional output providing the detail of what capabilities were advertised with the peer in the OPEN message.

Thanks
Colin

**Comment by sanjmonkey** [comment]
+1 for this feature enhancement.  I would love to know what capabilites the session has negotiated. I'm not necesarily interested in who sent what (though I can obvioulsy derive it given both sent/received).  Perhaps we can see it in one of the first state messages?
Cheers, Sandy

**Comment by thomas-mangin** [comment]
I complained like hell the first time I implemented BMP as I could not say if ASN4 was enabled on the sessions or not !  This is not hard to do, hopefully it will done soon and will make the raw data much more useful.

**Comment by thomas-mangin** [comment]
now presenting issue about non-shared MP, which is the number 1 source of bug report in the log but not yet the JSON.

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/commit/62eb0d414325d4c5b020df361e26651586ef1032

A new "negotiated" message can be received with the negotiated data.
```
{ "exabgp": "4.0.0", "time": 1495890263.575503, "host" : "ptr-41.212.219.82.rev.exa.net.uk", "pid" : 19165, "ppid" : 19164, "counter": 2, "type": "negotiated", "neighbor": { "address": { "local": "127.0.0.1", "peer": "127.0.0.1" }, "asn": { "local": "65512", "peer": "65512" }, "negotiated": { "message_size": 4096, "hold_time": 30, "asn4": true, "multisession": false, "operational": false, "refresh": "absent", "families": [ "ipv4 unicast" ,"ipv6 unicast" ], "add_path": { "send": [  ], "receive": [  ] } }  } }
```
