### ISSUE TITLE
exabgp 4.2.18  missing icmp-types #1069

### ISSUE THREAD

**Issue by enag11** [Exa-Networks/exabgp#1083]
Latest release 4.2.18 is missing icmp-type  #1069
    EXPERIMENTAL_MOBILITY = 0x29
    EXTENDED_ECHO_REQUEST = 0x2A
    EXTENDED_ECHO_REPLY = 0x2B

**Comment by enag11** [comment]
Hi, would you add all valid icmp-types to exabgp4.  4.2.18 is missing four not three as previously reported. thanks

**Comment by thomas-mangin** [comment]
Not a bug but a request for a backport ... ack. will do.

**Comment by thomas-mangin** [comment]
Is 5a0373ebfd5837d2cd8bae9fad6dee44addac4a9 what you were looking for?

**Comment by enag11** [comment]
yes, thank-you

**Comment by thomas-mangin** [comment]
released 4.2.19 with fix.
