### ISSUE TITLE
Cannot keep the log level at INFO and not having a lot of logs with healtcheck route announcements? Seems

### ISSUE THREAD

**Issue by bonomani** [Exa-Networks/exabgp#1086]
Hello, 
I try many possibilities and I dont know if it is normal or a bug, but I cannot reduce my logs in a good way?
-ExaBGP 4.2.8 on Debian 5.10.113-1

May 12 10:25:15 dc2tsde011 exabgp[153862]: 10:25:15 | 153862 | api             | route added to neighbor 10.0.245.252 local-ip 10.0.245.11 local-as 4273662731 peer-as 4273600014 router-id 10.0.245.11 family-allowed in-open : 10.0.0.101/32 next-hop 10.0.245.11 med 100
May 12 10:25:16 dc2tsde011 exabgp[153862]: 10:25:16 | 153862 | api             | route added to neighbor 10.0.245.252 local-ip 10.0.245.11 local-as 4273662731 peer-as 4273600014 router-id 10.0.245.11 family-allowed in-open : 10.0.0.101/32 next-hop 10.0.245.11 med 100

I would like to keep the log at the "INFO" level and not having a lot of logs, but is seems not possible ? but it is maybe normal? (should I open a feature request or maybe I do not have understand someting?)

My config:

process announce-routes {
    run python3 -m exabgp healthcheck --no-syslog --cmd "dig @127.0.0.1 i01.test.org. a +short +tries=1 +time=1" --ip 10.0.0.101 --next-hop 10.0.245.11 --withdraw-on-down -i 1 --rise 1 --fall 1;
    encoder text;
}

 
[exabgp.log]
all = false
configuration = false
daemon = false
destination = 'stdout'
enable = true
level = INFO
message = false
network = false
packets = false
parser = false
processes = false
reactor = false
rib = false
routes = false
short = false
timers = false

**Comment by thomas-mangin** [comment]
The healthcheck logs are not controlled by the exabgp configuration, healthcheck was authored by @vincentbernat and only integrated later.

https://github.com/Exa-Networks/exabgp/blob/master/src/exabgp/application/healthcheck.py#L161

Control the level of debugging. There is no command-line interface for it. We would have to add an option to set the debug level, so this would be a feature request if you do not want to change the code yourself.

**Comment by thomas-mangin** [comment]
Sorry, I may have replied too quickly.
