### ISSUE TITLE
Unexpected behavior of 'clear adj-rib out' and 'flush adj-rib out' with route-refresh feature enabled

### ISSUE THREAD

**Issue by moonsky219** [Exa-Networks/exabgp#1087]
**Describe the bug**

When route-refresh feature is enabled,
`neighbor x.x.x.x clear adj-rib out` does not withdraw routes in its adj-rib out table, actually I didn't observe any BGP messages with tcpdump.
`neighbor x.x.x.x flush adj-rib out` triggers an OPEN message to switch instead of resending routes in its adj-rib out table.

**To Reproduce**

- Add route-refresh in config and establish BGP session between exabgp and switch x.x.x.x.
- Send several routes to the switch.
- Try commands `neighbor x.x.x.x clear adj-rib out` and `neighbor x.x.x.x flush adj-rib out`

**Expected behavior**

With route-refresh capability negotiated between ExaBGP and switch,
`neighbor x.x.x.x clear adj-rib out` should still withdraw all routes in adj-rib out table.
`neighbor x.x.x.x flush adj-rib out` should still resend all routes in adj-rib out table.

**Environment (please complete the following information):**

 - OS: Debian GNU/Linux 9.13 (stretch)
 - Version 4.2.18 with Python 3.7.3
 ```conf
neighbor x.x.x.x {
        local-address y.y.y.y;
        router-id y.y.y.y;
        local-as 1;
        peer-as 2;
        description "xxx";

        family {
                ipv4 unicast;
        }

        capability {
                add-path send/receive;
                route-refresh;
        }

        api {
                processes [ announce-routes ];
        }
}
```

**Additional context**

- Both Route refresh capability (2) and Enhanced route refresh capability (70) are negotiated.
- I also tried to fire `neighbor x.x.x.x clear adj-rib out` and `neighbor x.x.x.x flush adj-rib out` after the BGP session is established with route-refresh, I notice that all following `neighbor x.x.x.x announce route ...` seems not working.

**Comment by thomas-mangin** [comment]
Thank you for the report, I will look into it when I can. I will first have to build a set of tests for the CI and then debug it. It will not be immediate. What is the impact of this issue on your work?

**Comment by moonsky219** [comment]
Hi @thomas-mangin, thank for your response. This issue blocked our efforts to improve our network availability. It would be very nice if you can look into the issue at your convenience time.

**Comment by thomas-mangin** [comment]
we now have a test for this and it is correctly failing (after fixing other rib related things) - just to indicate that I am working on the issue, but it is not yet finished.

**Comment by thomas-mangin** [comment]
Could you re-perform your tests with the latest master please.

**Comment by thomas-mangin** [comment]
Closing the issue. Feel free to re-open if you find that the tests `api-rib` and `api-rr-rib` did not cover your issue reported.
