### ISSUE TITLE
TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by scobowski** [Exa-Networks/exabgp#1103]
Thank you for using ExaBGP
4.2.19
3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0]
Linux wanguard-filter 5.4.0-117-generic #132-Ubuntu SMP Thu Jun 2 00:39:06 UTC 2022 x86_64
/usr/local
named pipes for the cli are:
to send commands  /run/exabgp/exabgp.in
to read responses /run/exabgp/exabgp.out
performing reload of exabgp 4.2.19
loaded new configuration successfully
connected to peer-1 with outgoing-1 94.154.666.17-94.154.666.253
connected to peer-2 with outgoing-1 94.154.666.17-94.154.666.254
/usr/bin/python3 /usr/local/bin/exabgpclips aux | grep exacan't concat str to bytes

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 248, in run
    self.loop()
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 225, in loop
    consume(self.r_pipe)
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 209, in consume
    store[source] += read[source](1024)
TypeError: can't concat str to bytes
can't concat str to bytes

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 248, in run
    self.loop()
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 225, in loop
    consume(self.r_pipe)
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 209, in consume
    store[source] += read[source](1024)
TypeError: can't concat str to bytes

root@wanguard-filter:/exabgp/exabgp-git# /usr/bin/python3 /usr/local/bin/exabgpcli show neighbor summary
Peer            AS        up/down state       |     #sent     #recvd
94.154.666.254  203417    0:03:49 established           2          2
94.154.666.253  203417    0:03:49 established           2          2
root@wanguard-filter:/exabgp/exabgp-git# /usr/bin/python3 /usr/local/bin/exabgpcli show neighbor summary

warning: no end of command message received
warning: normal if exabgp.api.ack is set to false otherwise some data may get stuck on the pipe
warning: otherwise it may cause exabgp reactor to block
root@wanguard-filter:/exabgp/exabgp-git# /usr/bin/python3 /usr/local/bin/exabgpcli show neighbor summary
can't concat str to bytes

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 248, in run
    self.loop()
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 225, in loop
    consume(self.r_pipe)
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 209, in consume
    store[source] += read[source](1024)
TypeError: can't concat str to bytes
^[[A

warning: no end of command message received
warning: normal if exabgp.api.ack is set to false otherwise some data may get stuck on the pipe
warning: otherwise it may cause exabgp reactor to block
root@wanguard-filter:/exabgp/exabgp-git# /usr/bin/python3 /usr/local/bin/exabgpcli show neighbor summary
^[[A
^[[A^[[A^[[A^[[B^[[B^[[B^[[B

warning: no end of command message received
warning: normal if exabgp.api.ack is set to false otherwise some data may get stuck on the pipe
warning: otherwise it may cause exabgp reactor to block
root@wanguard-filter:/exabgp/exabgp-git# 

root@wanguard-filter:/exabgp/exabgp-git# /usr/bin/python3 /usr/local/bin/exabgpcli show neighbor summary

warning: no end of command message received
warning: normal if exabgp.api.ack is set to false otherwise some data may get stuck on the pipe
warning: otherwise it may cause exabgp reactor to block
root@wanguard-filter:/exabgp/exabgp-git# 
root@wanguard-filter:/exabgp/exabgp-git# 
root@wanguard-filter:/exabgp/exabgp-git#

**Comment by scobowski** [comment]
root@wanguard-filter:/exabgp/exabgp-git# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@wanguard-filter:/exabgp/exabgp-git# python3 -V
Python 3.8.10
root@wanguard-filter:/exabgp/exabgp-git#

**Comment by scobowski** [comment]
Kindly release it (and push somebody to put it on pip?)

**Comment by thomas-mangin** [comment]
Sure ...

**Comment by scobowski** [comment]
Sure ;-)

**Comment by thomas-mangin** [comment]
Sure! Done! 4.2.20 is out.

**Comment by scobowski** [comment]
Luv ya :-)
