### ISSUE TITLE
Problem trying to advertise routes to neighbors

### ISSUE THREAD

**Issue by nkukard** [Exa-Networks/exabgp#1108]
**Describe the bug**

I've recently updated to version 4.2.20 and seem to be having an issue announcing routes as I did in the past.

**To Reproduce**

Here is my config...

```
1: neighbor 100.64.0.1 {
2:     router-id 0.0.0.2;
3:     local-as 65001;
4:     peer-as 65000;
5:     local-address 100.64.0.2;
6:      family {
7:              ipv4 unicast;
8:      }
9: }
10:
11: neighbor fc00:100::1 {
12:     router-id 0.0.0.2;
13:     local-as 65001;
14:     peer-as 65000;
15:     local-address fc00:100::2;
16:     family {
17:             ipv6 unicast;
18:     }
19: }

```
here is what I used to send and am sending now...

```
1: neighbor 100.64.0.1 announce route 100.64.101.0/24 next-hop 100.64.0.2 large-community [  ]
2: neighbor fc00:100::1 announce route fc00:101::/48 next-hop fc00:100::2 large-community [ ]
```

here is the error I"m getting...

```
Sun, 17 Jul 2022 21:36:57 36     reactor       connected to peer-1 with outgoing-1 100.64.0.2-100.64.0.1
Sun, 17 Jul 2022 21:36:57 36     reactor       connected to peer-2 with outgoing-2 fc00:100::2-fc00:100::1
Sun, 17 Jul 2022 21:36:57 36     api           no neighbor matching the command : announce route 100.64.101.0/24 next-hop 100.64.0.2 large-community [ ]
Sun, 17 Jul 2022 21:36:57 36     api           no neighbor matching the command : announce route fc00:101::/48 next-hop fc00:100::2 large-community [ ]
```

**Expected behavior**

A version or two back the above worked (without the family specified either).

I'd appreciate if anyone can give me some tips?

**Comment by thomas-mangin** [comment]
I am creating a test for this and I will look into it promptly

**Comment by nkukard** [comment]
> I am creating a test for this and I will look into it promptly

Thanks so much for the quick reply and I really appreciate the time. :)

**Comment by thomas-mangin** [comment]
This should be fixed on 4.2 with the release of 4.2.21 and on master too.

**Comment by nkukard** [comment]
I'll test and revert back, thanks!!

**Comment by nkukard** [comment]
62k tests I have all passing! Thanks so much @thomas-mangin , very much appreciated.
