### ISSUE TITLE
BGP Routes in issue.

### ISSUE THREAD

**Issue by pizu** [Exa-Networks/exabgp#1110]
Hi,

We have a BGP between exabgp on ubuntu server towards a firewall, when we shut the bgp from the firewall the routes are remaining in the routing table.

ExaBGP : 4.2.4
Python : 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0]
Uname  : Linux mstdns03 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64
Root   : 

The below capabilities are enabled:
    route-refresh;
    graceful-restart 120;

Thanks.

**Comment by thomas-mangin** [comment]
If GR is negotiated as you indicate, for 120 seconds, the route will remain 120 seconds in the RIB of the peer (the firewall?) even after BGP going down - this is what GR was created to do.

Not a bug.
