### ISSUE TITLE
ExBGP stuck in  OPEN CONFIRM  state sometime

### ISSUE THREAD

**Issue by c0D3M** [Exa-Networks/exabgp#1136]
** Bug Report **

Version : exabgp 4.2.3
Happens when some high traffic is running and router 

**Describe the bug**

Tried to reset the BGP connection from Mikrotik router but exabgp got stuck in the OPEN CONFIRM state.

**To Reproduce**

Run traffic and reset from router end.

**Expected behavior**

ExaBGP should move to Idle State.

Anyone has seen this issue, restarting ExaBGP fixes the issue.

**Comment by thomas-mangin** [comment]
Hello @c0D3M

Two things:
 * 4.2.3 is ANCIENT (Jan 2020), we only support master and the lastest 4.2 release (4.2.21 from last summer)
 * I am not magical: how do you expect me to find what could go wrong without technical information

So I will close this issue. If you can reproduce the issue with the latest stable version and master, then please run exabgp with "-d" and provide ALL the logs, without that I will not be able to help.

Also, you also did not provide the RouterOS version. So even if I wanted (and I do not have the time), I could not recreate your environment.
