### ISSUE TITLE
[Question] srv6 Configuration

### ISSUE THREAD

**Issue by infinitydon** [Exa-Networks/exabgp#1137]
Hi,

I am trying to understand the way exabgp srv6 is configured. 

Referring to https://github.com/Exa-Networks/exabgp/blob/main/etc/exabgp/conf-prefix-sid-srv6.conf, I need clarification on what the following:

- **_bgp-prefix-sid-srv6 ( l3-service 2001:3:0:0:: 0x13 [48,16,0,0,16,64] );_** --- What does 0x13 and [48,16,0,0,16,64] stand for?

- **_label 3_**  -- Is this needed for srv6 (I am assuming this refers to mpls related configuration)

- **_rd and extended-community [ target:4:100 ]_**  -- Are they compulsory? I am trying to setup basic srv6 (without vrfs)

**Comment by thomas-mangin** [comment]
Hi @infinitydon

I did not implement this RFC and it has been years since I last configured a BGP router part of my role, so I will not be able to be of much help. If you ask on slack perhaps someone else may be able to help. Good luck!
