### ISSUE TITLE
Error in ExaBGP

### ISSUE THREAD

**Issue by felipevideiraa** [Exa-Networks/exabgp#1158]
Hi, team!

I received this error during the installation of exabgp on my ubuntu server 20.04 LTS. 

the logs are :

root@wanguard:/etc/netplan# env exabgp.log.destination=syslog exabgp.daemon.daemonize=true exabgp /etc/exabgp.conf
03:24:26 | 2342   | welcome       | Thank you for using ExaBGP
03:24:26 | 2342   | version       | 4.2.4
03:24:26 | 2342   | interpreter   | 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0]
03:24:26 | 2342   | os            | Linux wanguard 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64
03:24:26 | 2342   | installation  |
03:24:26 | 2342   | cli control   | named pipes for the cli are:
03:24:26 | 2342   | cli control   | to send commands  /run/exabgp/exabgp.in
03:24:26 | 2342   | cli control   | to read responses /run/exabgp/exabgp.out

********************************************************************************
EXABGP HAD AN INTERNAL ISSUE / HELP US FIX IT
********************************************************************************

Sorry, you encountered a problem with ExaBGP and we could not keep the program
running.

There are a few things you can do to help us (and yourself):
- make sure you are running the latest version of the code available at
  https://github.com/Exa-Networks/exabgp/releases/latest
- if so report the issue on https://github.com/Exa-Networks/exabgp/issues
  so it can be fixed (github can be searched for similar reports)

PLEASE, when reporting, do include as much information as you can:
- do not obfuscate any data (feel free to send us a private  email with the
  extra information if your business policy is strict on information sharing)
  https://github.com/Exa-Networks/exabgp/wiki/FAQ
- if you can reproduce the issue, run ExaBGP with the command line option -d
  it provides us with much needed information to fix problems quickly
- include the information presented below

Should you not receive an acknowledgment of your issue on github (assignement,
comment, or similar) within a few hours, feel free to email us to make sure
it was not overlooked. (please keep in mind the authors are based in GMT/Europe)

********************************************************************************
-- Please provide ALL the information below on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

ExaBGP version : 4.2.4
Python version : 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0]
System Uname   : #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023
System MaxInt  : 9223372036854775807

-- Traceback

Traceback (most recent call last):
  File "/usr/sbin/exabgp", line 11, in <module>
    load_entry_point('exabgp==4.2.4', 'console_scripts', 'exabgp')()
  File "/usr/lib/python3/dist-packages/exabgp/application/__init__.py", line 13, in run_exabgp
    main()
  File "/usr/lib/python3/dist-packages/exabgp/application/bgp.py", line 304, in main
    run(env,comment,configurations,root,options["--validate"])
  File "/usr/lib/python3/dist-packages/exabgp/application/bgp.py", line 372, in run
    exit_code = Reactor(configurations).run(validate,root)
  File "/usr/lib/python3/dist-packages/exabgp/reactor/loop.py", line 227, in run
    self.daemon.daemonise()
  File "/usr/lib/python3/dist-packages/exabgp/reactor/daemon.py", line 185, in daemonise
    if self._is_socket(sys.__stdin__.fileno()) or os.getppid() == 1:
  File "/usr/lib/python3/dist-packages/exabgp/reactor/daemon.py", line 155, in _is_socket
    s = socket.fromfd(fd, socket.AF_INET, socket.SOCK_RAW)
  File "/usr/lib/python3.8/socket.py", line 544, in fromfd
    return socket(family, type, proto, nfd)
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 88] Socket operation on non-socket

-- Configuration

-- Logging History

03:24:26 | 2342   | welcome       | Thank you for using ExaBGP
03:24:26 | 2342   | version       | 4.2.4
03:24:26 | 2342   | interpreter   | 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0]
03:24:26 | 2342   | os            | Linux wanguard 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64
03:24:26 | 2342   | installation  |
03:24:26 | 2342   | cli control   | named pipes for the cli are:
03:24:26 | 2342   | cli control   | to send commands  /run/exabgp/exabgp.in
03:24:26 | 2342   | cli control   | to read responses /run/exabgp/exabgp.out

********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

Thanks for your attention to this case.

Long life to this community!

Kind Regards,
Felipe Videira
Network Analyst

**Comment by thomas-mangin** [comment]
You are reporting a bug with ExaBGP `4.2.4`, the latest stable is `4.2.21` from 2020.

```
commit 51747863832312fd406be7b0cbd46c34ac2492aa (tag: 4.2.4)
Author: Thomas Mangin <thomas.mangin@exa.net.uk>
Date:   Tue Jan 21 01:18:50 2020 +0000
```

Please de-install exabgp and re-install using pip, or clone the repository and create a zipapp (see instruction on main github page).

It is very unlikely that this bug still exists.

**Comment by felipevideiraa** [comment]
Hello, Thomas!

thanks for your assistance.

i install the 4.2.21 (pip install exabgp==4.2.21)  and the bug is solved.

`
10.100.69.2           65001          9          8       0       1        2:31 Establ
  inetflow.0: 2/2/2/0
`

Kind Regards,
Felipe Videira
Network Analyst
