### ISSUE TITLE
Exabgpcli command run and stuck

### ISSUE THREAD

**Issue by JamesTuMarines** [Exa-Networks/exabgp#1164]
Hi Team,

I met a strange problem when I tried to use exabgpcli to show some information.

It shows the output but does not return to the bash command prompt.
So, I have to use Ctrl+C to break it.

![image](https://github.com/Exa-Networks/exabgp/assets/90703900/a2f4b069-1a0c-4093-b66e-448634a4156b)
![image](https://github.com/Exa-Networks/exabgp/assets/90703900/1fd8e723-2c39-41db-9137-ae3141ab2646)

That's the information shown on the screen.

```
********************************************************************************
-- Please provide ALL the information below on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

ExaBGP version : 4.2.13
Python version : 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
System Uname   : #1 SMP Tue Mar 16 18:28:22 UTC 2021
System MaxInt  : 9223372036854775807


-- Traceback


Traceback (most recent call last):
  File "/usr/local/bin/exabgpcli", line 11, in <module>
    load_entry_point('exabgp==4.2.13', 'console_scripts', 'exabgpcli')()
  File "/usr/local/lib/python3.6/site-packages/exabgp/application/__init__.py", line 38, in run_cli
    main()
  File "/usr/local/lib/python3.6/site-packages/exabgp/application/cli.py", line 275, in main
    r, _, _ = select.select([reader], [], [], 0.01)
KeyboardInterrupt


-- Configuration





-- Logging History







```

I never met this problem on other devices that installed Exabgp.

Would you please tell me where I should check next?

Thank you.

**Comment by JamesTuMarines** [comment]
Hi Team,

I think I found the reason.

When I set exabgp.api.ack to false, the command would stuck.

Is it the expected behavior?
If so, is any workaround for this?

We would like to set exabgp.api.ack to false and also use the command.

Thank you.

Best regards,
James

**Comment by thomas-mangin** [comment]
Correct, same issue as https://github.com/Exa-Networks/exabgp/issues/1159

**Comment by JamesTuMarines** [comment]
Hi Thomas,

OK, I see.

Thank you.
