### ISSUE TITLE
on 4.2.21, setup.py doesn't work with python3.11

### ISSUE THREAD

**Issue by DamienWykland** [Exa-Networks/exabgp#1165]
Hello !

**Describe the bug**

Rocky 8.8 is now shipped with python3.11 so I tried to build exabgp 4.2.21 with python3.11 on my CI.
However it's failing with error : 
`ModuleNotFoundError: No module named 'setuptools'`

I tried installing the mentionned package manually but it doesn't help.

** To reproduce **
Try to build exabgp 4.2.21 with python3.11

**Environment (please complete the following information):**
c
 - OS: [Rocky Linux 8.8]
 - Version [ exabgp 4.2.21, python3.11]
 - 
![image](https://github.com/Exa-Networks/exabgp/assets/19306521/7f23ade8-afc3-4c33-ac68-73e9975396e6)

**Comment by thomas-mangin** [comment]
master works on 3.11 and 3.12 so I will close this issue.
