### ISSUE TITLE
Is there an option to reduce the time the exabgp will re-try the connection establishment after the peering goes down (default seems to be 60s)

### ISSUE THREAD

**Issue by ijukic2003** [Exa-Networks/exabgp#1176]
**Describe the bug**

Is there an option to reduce the time the exabgp will re-try the connection establishment after the peering goes down (default seems to be 60s). The exabgp establishes the BGP peering, and if that connection goes down (like the peer not reachable anymore), the exabgp will re-try to establish the new connection only once in 60s. 
This is not enough when using exabgp to simulate the huge number of peers connecting at the same time.

**Comment by thomas-mangin** [comment]
Does this patch make things work better for you?

```patch
diff --git a/src/exabgp/reactor/peer.py b/src/exabgp/reactor/peer.py
index 2dc5f5c8..7123f879 100644
--- a/src/exabgp/reactor/peer.py
+++ b/src/exabgp/reactor/peer.py
@@ -419,6 +419,7 @@ class Peer(object):
         self.neighbor.rib.outgoing.replace_restart(previous, current)
         self.neighbor.previous = None
 
+        self._delay.reset()
         while not self._teardown:
             # we are here following a configuration change
             if self._neighbor:
```

I wrote this without any testing at a conference so it may wrong but it may simply be that I was missing a reset of the exponential delay timer when we successfully establish a connection.

**Comment by ijukic2003** [comment]
Hi Thomas,

Sorry for the delay with the testing, still the same, after the connection goes down, the SYN is sent exactly every 60s.

**Comment by thomas-mangin** [comment]
Thank you for the feedback, I will look into it again.

**Comment by ijukic2003** [comment]
Hi Thomas,

Yes, sorry, I see now that after the connection drop, it tries to connect pretty fast, and then the time interval between the retries starts increasing exponentially with every new connection attempt.
The problem I have is that, for the scale tests I am doing, it takes around 4-5 minutes for the network to stabilize after the connection down trigger and the peer becomes ready again to accept the BGP connection. By that time the Exa re-try timer already gets increased back to 60s.
Is there any way to make this a configurable option in the code, so I can set some more aggressive fixed timer?

**Comment by thomas-mangin** [comment]
As far as I know, this behaviour is now fixed on master, if it need backporting let me know

**Comment by thomas-mangin** [comment]
no news is good news, closing the issue.

**Comment by ijukic2003** [comment]
Sorry, forgot to update the thread, yes the behavior has been fixed. Thanks for the help. 
Btw, I think it would be good to have a configurable option for the connect timer - it would be useful when doing the test for failover times for different vendors.

**Comment by thomas-mangin** [comment]
You may be able to use the exabgp.tcp.once option as is done in the test suite and run two commands back to back
