### ISSUE TITLE
Parsing some l2vpn-evpn messages causes session flap

### ISSUE THREAD

**Issue by ottorei** [Exa-Networks/exabgp#1195]
With version 4.2.21 peering with Juniper MX router as a route reflector client with family l2vpn-evpn, the BGP-session seems to constantly flap. Attachment contains the last errors being logged on ExaBGP side.

[exa-errors.txt]

**Comment by thomas-mangin** [comment]
Please provide enough information for me to help. Output of the full log using exabgp -d.

**Comment by ottorei** [comment]
The full log file would be quite large since there are over 100k evpn routes being received. Would it help to capture the single raw message that causes this issue?

**Comment by thomas-mangin** [comment]
When using -d the logs contain the exchanged open messages and shared updates. The lines with the opens and way down the update before the crash is what I would need.
A few other working similar updates would also be good to add to the test suite.
Thank you

**Comment by thomas-mangin** [comment]
Also please check with the main branch as this is where I will fix it.

**Comment by ottorei** [comment]
> When using -d the logs contain the exchanged open messages and shared updates. The lines with the opens and way down the update before the crash is what I would need. A few other working similar updates would also be good to add to the test suite. Thank you

Thanks. Perhaps this log has this information. At least there is one working decode before the crash.
[exa-mpls-evpn-debug.txt](https://github.com/Exa-Networks/exabgp/files/13870161/exa-mpls-evpn-debug.txt)

**Comment by ottorei** [comment]
Any change getting this fix merged on 4.2 release?

**Comment by thomas-mangin** [comment]
@ottorei I could backport but no one confirmed that the change worked as expected.

**Comment by ottorei** [comment]
> @ottorei I could backport but no one confirmed that the change worked as expected.

I'll patch my local instance and try it later this week.

**Comment by thomas-mangin** [comment]
no news good news. closing as fixed in master.
