### ISSUE TITLE
Can two exabgp establish BGP?

### ISSUE THREAD

**Issue by perhon** [Exa-Networks/exabgp#1197]
Use Notebooks A and B installed exabgp v4.2.21 separately. The configuration files are as follows:
A:
neighbor 192.168.0.102 {
  router-id 192.168.0.100;
  local-address 192.168.0.100;
  local-as 65000;
  peer-as 65000;
  passive true;
}

B:
neighbor 192.168.0.100 {
  router-id 192.168.0.102;
  local-address 192.168.0.102;
  local-as 65000;
  peer-as 65000;
}

BGP neighbors cannot be established between A and B. Through wireshark packet capture, it is found that TCP SYN packets are received by the peer, and peer send RST, CAN NOT establish TCP.
Modify the passive to be true or false, the symptom still exists.

Is there any problem with the configuration file?

**Comment by thomas-mangin** [comment]
There is a clear template to ask questions for ExaBGP - including providing full logs using `exabgp -d`, which was not done here.

Unfortunately, I do not have enough time to be a free BGP consultant. Therefore, I wish you good luck figuring out what is incorrect. If you have a BUG with ExaBGP, you will happily look into what you believe is wrong.

That said, you are probably:
- misconfiguring your network - RST is issued by the networking stack, not ExaBGP
- misconfiguring BGP: You should read about what router-id is - it is not peer-ip ..

You should make sure that L2 connectivity works between your devices (ping, telnet to port 179) and then look at the extended ExaBGP logs, they tend to give you lots of info.

**Comment by perhon** [comment]
Hi, thomas-mangin:

Thank you for your timely response.

If I encounter any problem later, I will attach the debug information.  Sorry.

This phenomenon may not be bug. I close this issue.

:)
