### ISSUE TITLE
healthcheck: Loopback IP Parsing

### ISSUE THREAD

**Issue by clwluvw** [Exa-Networks/exabgp#1199]
** Bug Report **

**Describe the bug**

When having two ips with labels like `labelname` and `labelname-something`, specifying `--label labelname` would pick both `labelname` and `labelname-something`.

**Expected behavior**

Only the desired label be chosen.

**Additional context**

It must be probably because of the `startswith` func here (https://github.com/Exa-Networks/exabgp/blob/main/src/exabgp/application/healthcheck.py#L221)

**Comment by clwluvw** [comment]
I see a backslash in the end of the label from `/sbin/ip -o address show dev lo` output.

**Comment by vincentbernat** [comment]
I don't remember if it was the reason I have used `startswith`. Maybe the right fix would be:
```
if lmo.groupdict().get("label", "").rstrip("\\") == label:

**Comment by vincentbernat** [comment]
Sorry, looking at the documentation string, this is something expected. Labels need to be unique, so that's why there is a `startswith()`. If you want to use several loopbacks, you label them `haproxy1`, `haproxy2`, `haproxy3` and you use `--label haproxy`.

**Comment by clwluvw** [comment]
hmm - maybe a better approach was to support regex as an arg so this wouldn't be confusing. I mean now you can't use it unless you change the names completely.

**Comment by thomas-mangin** [comment]
@clwluvw if you wish to add an option ( --use-interface-numbering ?? ) to have the code use numbering while keeping backward compatibility for previous users when not used, I will happily have a look at it and merge it if it looks good.

As I develop on mac, testing Linux networking is a pain (and yes, I know about VM and containers). As I agree with @vincentbernat that this is not a big problem, I do not feel like working on it.

Still, if you care enough to put the work into it, I will perform the code review on behalf of Vincent. If you do not wish to do so, please fell free to close the issue.
