### ISSUE TITLE
I am new to exaBGP please help me sample configuration file

### ISSUE THREAD

**Issue by bhimraojabraska** [Exa-Networks/exabgp#1213]
I am new to exaBGP please help me sample configuration file which will receive routes from neighbor I want parse that information to graphana for monitoring.

**Comment by thomas-mangin** [comment]
You will find examples on the git repository:
https://github.com/Exa-Networks/exabgp/tree/main/etc/exabgp

Many presentations from people using ExaBGP on the wiki page with confs.
https://github.com/Exa-Networks/exabgp/wiki

**Comment by thomas-mangin** [comment]
Please close this issue if you have no further questions.
