### ISSUE TITLE
Exporting a blacklist example similar to exabgp-edgerouter

### ISSUE THREAD

**Issue by elico** [Exa-Networks/exabgp#1228]
**Is your feature request related to a problem? Please describe.**
I want to be able to use exabgp as a blackholing peer.
There is an option to blackhole traffic in FRR and other routing daemons like the example with VyOS:
* <https://forum.vyos.io/t/bgp-next-hop-blackhole/8232>

One old solution I have seen is:
* <https://github.com/infowolfe/exabgp-edgerouter>
However it was written with the old style of config and also works on python2 and not python3.

**Describe the solution you'd like**
I would like to write a new implementation as an example for such a function. 

**Describe alternatives you've considered**
Adding manually the routes into FRR via a FRR script based on the plain text blacklist files.

**Comment by thomas-mangin** [comment]
There was a PR proposed to show how to do it and it was merged.

**Comment by elico** [comment]
@thomas-mangin How can I find it?

I managed to make it work eventually manually but now I am facing another issue with Mikrotik RouterOS.
I will investigate the RouterOS issue later on.

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/commit/68230ef80cb01167081da7c2f9ad7a5b7b071bc2

**Comment by elico** [comment]
Thanks!

@thomas-mangin I managed to make this work and it seems to work as expected but now I have the issue with Mikrotik RouterOS.

I am unsure how to configure the RouterOS BGP connection/session.
From A RouterOS device to RouterOS device I am able to create a BGP session but not between exabgp to a RouterOS device.

For now I will close the issue and will open another one about Mikrotik RouterOS
