### ISSUE TITLE
can exabgp run as a route-server?

### ISSUE THREAD

**Issue by kona3266** [Exa-Networks/exabgp#1230]
hi, i am a new bee to exabgp. Can exabgp run as a bgp route server, which can be connected from many ebgp  client?

**Comment by kona3266** [comment]
if it can, can you give me an example。

**Comment by thomas-mangin** [comment]
It needs to be programmed to do so. I have no example
As I never implemented such behaviour.

**Comment by kona3266** [comment]
> It needs to be programmed to do so. I have no example As I never implemented such behaviour.

thanks for the answer.
