### ISSUE TITLE
How to annnouce a L2VPN EVPN route

### ISSUE THREAD

**Issue by jibwf** [Exa-Networks/exabgp#1235]
Here is EPVN type 3 route parsed result
```
json { "exabgp": "4.0.1", "time": 1726195244.60685, "host" : "CXLabs-UBUNTU22", "pid" : 397134, "ppid" : 394161, "counter": 634, "type": "update", "neighbor": { "address": { "local": "5.5.5.2", "peer": "29.4.4.2" }, "asn": { "local": 65011, "peer": 65011 } , "direction": "in", "message": { "update": { "attribute": { "origin": "igp", "local-preference": 100, "originator-id": "29.4.4.64", "cluster-list": [ "29.4.4.2" ], "extended-community": [ { "value": 842170072323815, "string": "target:65011:22247" }, { "value": 219550481834311688, "string": "encap:VXLAN" } ], "pmsi": "pmsi:ingressreplication:0:1390(22247):29.5.4.64" }, "announce": { "l2vpn evpn": { "29.5.4.64": [ { "code": 3, "parsed": true, "raw": "031100011D04044088C600000000201D050440", "name": "Inclusive Multicast Ethernet Tag", "rd": "29.4.4.64:35014", "ethernet-tag": 0, "ip": "29.5.4.64" } ] } } } } } }
```
I tried to use below line to announce route, but failed to parse due to extended-community. 
```
string = "neighbor 29.4.4.2, announce attributes origin igp local-preference 100 originator-id 1.1.1.1 cluster-list 29.4.4.2 extended-community [target:65011:100 encap:VXLAN ] l2vpn evpn 1.1.1.1 code 3 name Inclusive Multicast Ethernet Tag rd 1.1.1.1:100 ip 1.1.1.1"
```
```
04:55:45 | 425707 | api           | command could not parse route in : announce attributes origin igp local-preference 100 originator-id 1.1.1.1 cluster-list 29.4.4.2 extended-community [ target:65011:100 , encap:VXLAN ] l2vpn evpn 1.1.1.1 code 3 name Inclusive Multicast Ethernet Tag rd 1.1.1.1:100 ip 1.1.1.1
04:55:45 | 425707 | api           | reason: invalid extended community , - lc+gc
```

My question:

Is it possible to announce route with json format?
Please help on EVPN route announcement

**Comment by thomas-mangin** [comment]
> Is it possible to announce routes using a JSON format?

Sorry, but it is not possible. There is also no plan to implement this feature.

> Help

`29.4.4.2,` you should remove the `,` after the IP. For the issue with -lc+gc .. I will look into it but I may not haved authored that part of the code.

> announce attributes origin igp local-preference 100 originator-id 1.1.1.1 cluster-list 29.4.4.2 extended-community [target:65011:100 encap:VXLAN ] l2vpn evpn 1.1.1.1 code 3 name Inclusive Multicast Ethernet Tag rd 1.1.1.1:100 ip 1.1.1.1

`encap:VXLAN` is not a known extended community encoding. I will need to find the VXLAN RFC and look at how it should be interpreted.

`code 3` I think this is an information about the payload and is not required for encoding
`name Inclusive Multicast Ethernet` same thing and if it was a paramater it would have required quoting
`Tag` same thing only `rd` is required

This command seems to work (without the VLAN info).

`announce attributes origin igp local-preference 100 originator-id 1.1.1.1 cluster-list 29.4.4.2 extended-community [target:65011:100 ] rd 1.1.1.1:100 nlri 1.1.1.1"                          
command: announce attributes origin igp local-preference 100 originator-id 1.1.1.1 cluster-list 29.4.4.2 extended-community [target:65011:100 ] rd 1.1.1.1:100 nlri 1.1.1.1`

**Comment by thomas-mangin** [comment]
no news, good news. Closing.
