### ISSUE TITLE
Support of VPLS Auto-Discovery messages in ExaBGP

### ISSUE THREAD

**Issue by ptitbic** [Exa-Networks/exabgp#163]
RFC 4761 describe the use of BGP for L2VPN VPLS service.
There are 2 types of BGP messages for VPLS: Signaling (already implemented and functionnal :-)), and Auto-Discovery (RFC 4761 part 3.1).

In many provider networks, the signaling is handled by LDP while the VPLS membership discovery and announcement is done via BGP.

I can provide captures of BGP VPLS AD update if needed.
Regards,
Pierre

**Comment by thomas-mangin** [comment]
No update - closing as AFAICS nothing has to be done.
