### ISSUE TITLE
debian changelog file is not updated to match release version

### ISSUE THREAD

**Issue by thardie** [Exa-Networks/exabgp#207]
Please update the debian/changelog file to be in sync with the release version mentioned in CHANGELOG

**Comment by thomas-mangin** [comment]
this is now automatically updated on release 
https://github.com/thomas-mangin/exabgp/commit/f1a22f91e91128351d7547d77982650046fb7d53

**Comment by thomas-mangin** [comment]
Thank you for pointing this out early enough that 3.4.6 could be fixed !
