### ISSUE TITLE
Immediately bring down a BGP peer upon failure of the underlying TCP session

### ISSUE THREAD

**Issue by lvanbever** [Exa-Networks/exabgp#211]
Instead of waiting for the hold-timer to expire, ExaBGP could immediately tear down the BGP session upon failure of the underlying transport session (e.g., upon router failure). In situations where fast convergence is paramount, this can greatly speed up the overall convergence time (especially if ExaBGP already knows backup paths).

**Comment by thomas-mangin** [comment]
Hi Laurent, I had a look at the code and AFAICS, on TCP failure the code will immediately try to reconnect.
If I am correct on socket failure, the socket is marked with "with data" by select, we will then try to read it, find the issue and raise an network error which is intercepted by the main loop and perform a peer cleanup and force an immediate reconnection.
Could you please let tell me when you saw some stalling ?
