### ISSUE TITLE
Is it possible to send a BGP UPDATE message with multiple NLRI?

### ISSUE THREAD

**Issue by a16** [Exa-Networks/exabgp#220]
Hi Thomas,

This is a feature request, maybe...

When exabgp generate to send BGP UPDATE messages using ```static route```, it seems to send BGP UPDATE messages per ```route``` respectively even if all of the ```route``` have the same PATH attributes. I've confirmed the messages on the wire using packet capture.

```
neighbor 192.168.0.100 {
        router-id 192.168.0.1;
        local-address 192.168.0.1;
        local-as 65001;
        peer-as 65100;
        hold-time 90;

        family {
                ipv4 unicast;
        }

        static {
                route 172.16.0.0/32 next-hop 192.168.0.1;
                route 172.16.0.1/32 next-hop 192.168.0.1;
        }
}

```
For example, if I use the above config, exabgp would send 2 BGP UPDATE messages. One is for "172.16.0.1/32", the other is for "172.16.0.2/32".

Sometimes I want to send a BGP message with multiple NLRI for converting from pcap.
IMHO, I would be happy if the config like below can be parsed and send one message.
This is just my idea.
```
neighbor 192.168.0.100 {
        -- snip --
        static {
                route [ 172.16.0.0/32 172.16.0.1/32 ] {
                        next-hop 192.168.0.1;
                }
        }
}

```

What do you think?

**Comment by thomas-mangin** [comment]
Hello :smile: 

I believe you will be happy :

```
./sbin/exabgp qa/conf/simple-v4.conf | grep -A1 -B1 'group-updates '

Thu, 29 Jan 2015 17:04:54 | WARNING  | 47655  | configuration | --------------------------------------------------------------------------------
Thu, 29 Jan 2015 17:04:54 | WARNING  | 47655  | configuration | group-updates not enabled for peer 10.0.0.3, it surely should, the default will change to true soon
Thu, 29 Jan 2015 17:04:54 | WARNING  | 47655  | configuration | --------------------------------------------------------------------------------
```

So all you have to do is enable upgrade grouping with your peer.

**Comment by thomas-mangin** [comment]
There is also an unofficial API to announce routes with the same update. The new configuration format goes one step further and does explicitly create named attribute groups and you must apply theses groups to NLRI .. However it is not yet ready, hopefully later this year.

**Comment by a16** [comment]
:+1:  Just what I wanted!! It worked. Thanks!

**Comment by thomas-mangin** [comment]
:smile: :clap:
