### ISSUE TITLE
feature request: allow easy configuration of groups of peers by defining a prefix as neighbor

### ISSUE THREAD

**Issue by job** [Exa-Networks/exabgp#221]
It would be really nice if you could configure an IPv4 or IPv6 prefix as neighbor rather then a single IP address, to easily share configuration between peers. Example configuration:

```
neighbor 10.0.0.0/24 {
  description "all ebgp speakers at the IXP";
  router-id 10.0.0.1;
  local-address 10.0.0.1;
  local-as 15562;
  graceful-restart;
}
```

Considerations:
- If a prefix is configured as `neighbor`, automatically `passive;` should be enabled
- From the `OPEN` message exabgp should derive what the peer's ASN is
- Don't forget IPv6 support

**Comment by thomas-mangin** [comment]
Hi Job, do you need this feature real soon now, or is it just a wish list as it would be nice to have (but no rush for it).

**Comment by job** [comment]
I'd classify this as a ```Defcon 5```

**Comment by thomas-mangin** [comment]
Hi @job - this is implemented in master (only for passive neighbor).
