### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#223]
We lost our debian package: https://tracker.debian.org/pkg/exabgp
@vincentbernat @henry-nicolas

**Comment by vincentbernat** [comment]
Yes, unfortunately. And it's too late to get them back for next stable release. However, when Jessie is out, they can be pushed in jessie-backports. If @henry-nicolas doesn't have time anymore, I can take care of the packaging.

**Comment by thomas-mangin** [comment]
@henry-nicolas did not reply last time we discussed this. I will email him directly once more and ask him to comment one way or another here.

**Comment by henry-nicolas** [comment]
Sorry guys, I'm quite busy at the moment with family changes and work. So, yes, if Vincent can continue working on it, it would be best for ExaBGP

**Comment by thomas-mangin** [comment]
@henry-nicolas thank you for letting us know.

**Comment by thomas-mangin** [comment]
@henry-nicolas - thank you for you help over the years - all the best with the family and work.
@vincentbernat closing this issue, thank you very much for offering your help.

**Comment by vincentbernat** [comment]
I am wondering, could we generate the manual page from another source?

**Comment by thomas-mangin** [comment]
I have a private mail from @he32 with a man page. I will forward you the mail.
