### ISSUE TITLE
Change the maintainer in setup.py

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#233]
@vincentbernat  I invited you to join the dev team ( so I can assign issues to you .. ahahaha - evil laugh ).

We should update setup.py so new release have you as the maintainer for debian and correctly update the debian/changelog file ( and whatever else more you need ).

**Comment by vincentbernat** [comment]
I will update the packaging this week-end or next week-end. In the meantime, I can just update the names if you want.

**Comment by thomas-mangin** [comment]
I am happy to let you do what need to be done :relaxed:

**Comment by thomas-mangin** [comment]
@vincentbernat 
Planning to release 3.4.9 this week-end (as soon as I have confirmation that the new MD5 code work on more than my laptop VM) . updating your email address - anything more I should do ?

**Comment by vincentbernat** [comment]
I am currently updating packaging. Should be done by today.

**Comment by thomas-mangin** [comment]
Great - Thank you very much - much appreciated.
