### ISSUE TITLE
Official Debian packaging

### ISSUE THREAD

**Issue by vincentbernat** [Exa-Networks/exabgp#240]
Hey Thomas!

Do you mind if I use the repository for the official packaging in Debian too? This will add a `debian/sid` branch (and maybe other if we backport to older versions, more if you wanted a PPA for some Ubuntu versions), as well as a bunch of `debian/sid/XXXX` tags (idem).

Otherwise, I can put that on Debian's own hosting platform. No big difference for me.

**Comment by thomas-mangin** [comment]
No issues at all.

**Comment by thomas-mangin** [comment]
As I want to release a LTS release at the end of the 3.x cycle it would make sense too.

**Comment by vincentbernat** [comment]
I would also need that you push the 3.4.9 tag. :)

**Comment by thomas-mangin** [comment]
It should have been pushed ! python setup.py release does it ..
```
> git tag | sort -n | tail -1
3.4.9
> git push --tags upstream
Everything up-to-date
```

**Comment by vincentbernat** [comment]
Hummm, never noticed that `git fetch` didn't fetch them automatically. My bad.
