### ISSUE TITLE
Web interface for flowspec management

### ISSUE THREAD

**Issue by pavel-odintsov** [Exa-Networks/exabgp#244]
Hello, folks!

I tough many nights about flowspec and found very challenging problem. In most popular cases we are deploying flowspec with upstream for attack mitigation. But flowspec implemented only by Juniper. What should I do if I haven't Juniper equipment? 

Well, I could install exabgp and code for it. But in case of DDoS attack will be fine to get web interface with interactive interface for building rulesets according to Juniper specification and upstream restrictions (my upstream provide only 10 rules).

The second challenging task with flow spec is monitoring. AFAIK, there are no ways to check "how much traffic hit this rule" and every ISP should implement custom interface. Will be fine implement some standard approach to this task.

Both management and monitoring task could be implemented in web or console interface. 

Anybody interested in this?

**Comment by thomas-mangin** [comment]
Hello, Pavel. Flowspec is now supported by Cisco on XR. https://supportforums.cisco.com/document/12226726/asr9000xr-understanding-bgp-flowspec-bgp-fs

I started to work on a DDOS mitigation solution but progress has halted ( lack of time ) I intend to continue and integrate it with ExaBGP when I can ...

Many people would be interested few have the time to create it / participate.

**Comment by pavel-odintsov** [comment]
Maybe we could integrate it with my toolkit https://github.com/FastVPSEestiOu/fastnetmon? Unfortunately it's written not in Python but I could implement API and bindings. 

I working on action part of FastNetMon which could convert "attack snapshot" into flow spec ruleset for spreading over backbone.

**Comment by thomas-mangin** [comment]
Sure, there is an "PIPE" API - not very well documented but plenty of examples in the qa/ folder. I will gladly help.

**Comment by pavel-odintsov** [comment]
Thanks so much. I will try to implement support for it!

**Comment by pavel-odintsov** [comment]
Thomas my great thanks for your tool! I have configured external management for ExaBGP: http://www.stableit.ru/2015/04/how-to-control-exabgp-from-external-tool.html and will add integration to my FastNetMon detection toolkit shortly.

**Comment by pavel-odintsov** [comment]
Awesome news! ExaBGP integration for DDoS detection toolkit FastNetMon have implemented: https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/EXABGP_INTEGRATION.md
 :) It works with charm and my GREAT thanks to ExaBGP for this capability.

**Comment by thomas-mangin** [comment]
@pavel-odintsov this is great ! Thank you for adding this integreation, much appreciated ! If you ever need a feature on ExaBGP's side, let us know !

**Comment by pavel-odintsov** [comment]
Thomas, I need your help again :(

I want implement BGP flow spec interface for all my firewalls (netmap-ipfw) and manage whole DDoS mitigation process with it.

I have two hosts:
- DDoS detector which announces dangerous flows to firewall with BGP Flow Spec
- Firewall, it receives flow spec announces and send notification to netmap-ipfw daemon.

Config for detector:
```bash
group Core_v4 {
    hold-time 180;
    local-as 65001;
    peer-as 1234;
    router-id 10.0.3.114;
    graceful-restart 1200;

    neighbor 10.0.3.115 {
        local-address 10.0.3.114;
        description "Quagga";
   }

        flow {
            route block_traffic_to_proxy {
                match {
                    source 10.0.0.1/32;
                    destination 10.0.0.2/32;
                    destination-port =3128;
                    protocol tcp;
                }   
                then {
                    discard;
               }   
            }   
        } 
}
```

Config for firewall:
```bash
group Core_v4 {
    hold-time 180;
    local-as 1234;
    peer-as 65001;
    router-id 10.0.3.115;
    graceful-restart 1200;

    neighbor 10.0.3.114 {
        local-address 10.0.3.115;
        description "Quagga";
    }

    process dump-all-text {
        neighbor-changes;
        receive-routes;
        send-packets;
        receive-packets;
        run /etc/exabgp/exabgp_update_writer.py;
    }
}
```

Code of exabgp_update_writer here: https://gist.github.com/pavel-odintsov/288845a2b619cc51c560

Firewall listen on 179 port and receive connections from detector but no information passed to script :( 

Could you show me my error in configuration?

**Comment by thomas-mangin** [comment]
what version of ExaBGP are you using ? if it is a recent one ( 3.4.10 or 3.4 stable branch ) then the receive-routes; and send-packets; options do not exist anymore.
3.5 ( master ) change ( sigh ) once more the format. try:
```
   process rule-the-world {
      run /etc/exabgp/exabgp_update_writer.py;
      encoder json;
      receive {
         parsed;
         updates;
      }   
      }
   }
```

You can find the latest example for the current version in the qa folder.

**Comment by pavel-odintsov** [comment]
Hello

Thanks for fast answer. My ExaBGP : 3.4.10 on both servers

I tried and modern syntax too:
```bash
group Core_v4 {
    hold-time 180;
    local-as 1234;
    peer-as 65001;
    router-id 10.0.3.115;
    graceful-restart 1200;

    neighbor 10.0.3.114 {
        local-address 10.0.3.115;
        description "Quagga";
    }  

    process stdout {
        receive {
           parsed;
	   update;
        }
	
        encoder json;
        run /etc/exabgp/exabgp_update_writer.py;
    }
}
```

But there are no results. 

Monitor log:
```bash
Thu, 14 May 2015 23:21:31 | INFO     | 6025   | daemon        | PIDfile already exists, not updated /var/run/exabgp.pid
Thu, 14 May 2015 23:21:31 | ERROR    | 6025   | reactor       | could not update PID, not starting
Thu, 14 May 2015 23:21:31 | DEBUG    | 6025   | network       | out loop, intialising
Thu, 14 May 2015 23:21:34 | INFO     | 6025   | network       | Connected to peer neighbor 10.0.3.115 local-ip 10.0.3.114 local-as 65001 peer-as 1234 router-id 10.0.3.114 family-allowed in-open (out)
```

Firewall log:
```bash
Thu, 14 May 2015 22:21:27 | INFO     | 3705   | daemon        | PIDfile already exists, not updated /var/run/exabgp.pid
Thu, 14 May 2015 22:21:27 | ERROR    | 3705   | reactor       | could not update PID, not starting
Thu, 14 May 2015 22:21:27 | DEBUG    | 3705   | network       | out loop, intialising
Thu, 14 May 2015 22:21:32 | INFO     | 3705   | reactor       | accepted connection from  10.0.3.114 - 10.0.3.115
Thu, 14 May 2015 22:21:32 | DEBUG    | 3705   | network       | in loop, intialising
Thu, 14 May 2015 22:21:32 | INFO     | 3705   | network       | Peer      10.0.3.114 ASN 65001   connection to peer failed
Thu, 14 May 2015 22:21:33 | DEBUG    | 3705   | network       | out loop, intialising
Thu, 14 May 2015 22:21:34 | INFO     | 3705   | network       | Connected to peer neighbor 10.0.3.114 local-ip 10.0.3.115 local-as 1234 peer-as 65001 router-id 10.0.3.115 family-allowed in-open (in)
Thu, 14 May 2015 22:21:34 | INFO     | 3705   | network       | Peer      10.0.3.114 ASN 65001   connection to peer failed
Thu, 14 May 2015 22:21:34 | DEBUG    | 3705   | network       | out loop, stopping, other one is established
```

**Comment by pavel-odintsov** [comment]
Well, suppose I fix it!

**Comment by pavel-odintsov** [comment]
Working config.

Monitor:
```bash
group Core_v4 {
    hold-time 180;
    local-as 65001;
    peer-as 1234;
    router-id 10.0.3.114;
    graceful-restart 1200;

    neighbor 10.0.3.115 {
        local-address 10.0.3.114;
        description "Quagga";

        #static {
        #    route 10.10.10.1/32 next-hop 10.0.3.114 community 65001:666;
        #}

        flow {
            route block_traffic_to_proxy {
                match {
                    source 10.0.0.1/32;
                    destination 10.0.0.2/32;
                    destination-port =3128;
                    protocol tcp;
                }   
                then {
                    discard;
               }   
            }   
        } 
    }
}
```

Firewall:
```bash
group Core_v4 {
    hold-time 180;
    local-as 1234;
    peer-as 65001;
    router-id 10.0.3.115;
    graceful-restart 1200;

    neighbor 10.0.3.114 {
        local-address 10.0.3.115;
        description "Quagga";

        process stdout {
            receive {
                parsed;
                update;
            }   
    
            encoder json;
            run /etc/exabgp/exabgp_update_writer.py;
        }   
    }  
}
```

Dump:
```bash
{ "exabgp": "3.4.8", "time": 1431636063, "host" : "synproxied.fv.ee", "pid" : "3825", "ppid" : "3462", "type": "update", "neighbor": { "ip": "10.0.3.114", "address": { "local": "10.0.3.115", "peer": "10.0.3.114"}, "asn": { "local": "1234", "peer": "65001"}, "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 65001 ], "confederation-path": [], "extended-community": [ 9225060886715039744 ] }, "announce": { "ipv4 flow": { "none": { "flow-0": { "": [ "10.0.0.2/32" ], "": [ "10.0.0.1/32" ], "protocol": [ "=TCP" ], "destination-port": [ "=3128" ], "string": "flow  10.0.0.2/32  10.0.0.1/32 protocol =TCP destination-port =3128" } } } } } }} }
```

And everything works fine. But I suddenly hit new bug: https://github.com/Exa-Networks/exabgp/issues/260

**Comment by thomas-mangin** [comment]
fixed the code in the 3.4 branch and 3.5 master, some keys were missing. I still need to fix the "none" key which is clearly wrong too.

**Comment by pavel-odintsov** [comment]
Awesome! Thank you!

**Comment by pavel-odintsov** [comment]
Looks more pretty! Thanks!

{ "exabgp": "3.5.0", "time": 1431716393, "host" : "synproxied.fv.ee", "pid" : 2599, "ppid" : 2008, "counter": 1, "type": "update", "neighbor": { "address": { "local": "10.0.3.115", "peer": "10.0.3.114" }, "asn": { "local": "1234", "peer": "65001" }, "direction": "receive", "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 65001 ], "confederation-path": [], "extended-community": [ 9225060886715039744 ] }, "announce": { "ipv4 flow": { "no-nexthop": { "flow-0": { "destination-ipv4": [ "10.0.0.2/32" ], "source-ipv4": [ "10.0.0.1/32" ], "protocol": [ "=tcp" ], "destination-port": [ "=3128" ], "string": "flow destination-ipv4 10.0.0.2/32 source-ipv4 10.0.0.1/32 protocol =tcp destination-port =3128" } } } } } } } }
