### ISSUE TITLE
unable to advertise a vpnv4 prefix.

### ISSUE THREAD

**Issue by m4ccbr** [Exa-Networks/exabgp#245]
ExaBGP version : 3.4.9
Python version : 2.7.3 (default, Dec 18 2014, 19:03:52)  [GCC 4.6.3]
System Uname   : #57~precise1-Ubuntu SMP Tue Jul 15 03:50:54 UTC 2014
System MaxInt  : 2147483647

peer 100.100.11.11 ASN 100     

<class 'struct.error'>
'H' format requires 0 <= number <= 65535
Traceback (most recent call last):
  File "/opt/exabgp-3.4.9/lib/exabgp/reactor/peer.py", line 584, in _run
    for action in self._main(direction):
  File "/opt/exabgp-3.4.9/lib/exabgp/reactor/peer.py", line 534, in _main
    new_routes.next()
  File "/opt/exabgp-3.4.9/lib/exabgp/reactor/protocol.py", line 269, in new_update
    for message in update.messages(self.negotiated):
  File "/opt/exabgp-3.4.9/lib/exabgp/bgp/message/update/__init__.py", line 197, in messages
    packed = mp_packed_generator.next()
  File "/opt/exabgp-3.4.9/lib/exabgp/bgp/message/update/attribute/mprnlri.py", line 63, in packed_attributes
    chr(0) + ''.join(nlris)
  File "/opt/exabgp-3.4.9/lib/exabgp/bgp/message/update/attribute/attribute.py", line 163, in _attribute
    len_value = pack('!H',length)
error: 'H' format requires 0 <= number <= 65535

********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

Sun, 29 Mar 2015 21:19:03 | INFO     | 5243   | network       | Peer   100.100.11.11 ASN 100     out loop, peer reset, message [] error[]
Sun, 29 Mar 2015 21:19:03 | DEBUG    | 5243   | wire          | session 1 outgoing, closing connection from 100.100.11.103 to 100.100.11.11
Sun, 29 Mar 2015 21:19:03 | DEBUG    | 5243   | wire          | session 1 outgoing 100.100.12.103 / 100.100.12.12   RECEIVED FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 02
Sun, 29 Mar 2015 21:19:03 | DEBUG    | 5243   | wire          | session 1 outgoing 100.100.12.103 / 100.100.12.12   RECEIVED 0000 0007 900F 0003 0001 80
Sun, 29 Mar 2015 21:19:03 | DEBUG    | 5243   | timers        | peer 100.100.12.12 ASN 100     Receive Timer 89 second(s) left
Sun, 29 Mar 2015 21:19:03 | DEBUG    | 5243   | timers        | peer 100.100.12.12 ASN 100     Send Timer 29 second(s) left
Sun, 29 Mar 2015 21:19:03 | INFO     | 5243   | routes        | peer 100.100.12.12 ASN 100     << UPDATE (1)
Sun, 29 Mar 2015 21:19:03 | DEBUG    | 5243   | wire          | session 1 outgoing 100.100.12.103 / 100.100.12.12   SENDING FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 0200 0000 0790 0F00 0300 0180
Sun, 29 Mar 2015 21:19:03 | INFO     | 5243   | message       | Peer   100.100.12.12 ASN 100     >> EOR ipv4 mpls-vpn
Sun, 29 Mar 2015 21:19:03 | INFO     | 5243   | message       | peer 100.100.12.12 ASN 100     >> EOR(s)
Sun, 29 Mar 2015 21:19:03 | DEBUG    | 5243   | timers        | peer 100.100.12.12 ASN 100     Receive Timer 89 second(s) left
Sun, 29 Mar 2015 21:19:03 | DEBUG    | 5243   | timers        | peer 100.100.12.12 ASN 100     Send Timer 29 second(s) left
Sun, 29 Mar 2015 21:19:03 | DEBUG    | 5243   | timers        | peer 100.100.12.12 ASN 100     Receive Timer 89 second(s) left
Sun, 29 Mar 2015 21:19:03 | DEBUG    | 5243   | timers        | peer 100.100.12.12 ASN 100     Send Timer 29 second(s) left
Sun, 29 Mar 2015 21:19:03 | DEBUG    | 5243   | network       | out loop, intialising
Sun, 29 Mar 2015 21:19:04 | DEBUG    | 5243   | timers        | peer 100.100.12.12 ASN 100     Receive Timer 88 second(s) left
Sun, 29 Mar 2015 21:19:04 | DEBUG    | 5243   | timers        | peer 100.100.12.12 ASN 100     Send Timer 28 second(s) left
Sun, 29 Mar 2015 21:19:04 | DEBUG    | 5243   | wire          | Attempting connection to 100.100.11.11
^CSun, 29 Mar 2015 21:19:05 | INFO     | 5243   | reactor       | ^C received
Sun, 29 Mar 2015 21:19:05 | INFO     | 5243   | reactor       | Performing shutdown
Sun, 29 Mar 2015 21:19:05 | ERROR    | 5243   | network       | Closing the session without notification
Sun, 29 Mar 2015 21:19:05 | INFO     | 5243   | network       | Peer   100.100.12.12 ASN 100     graceful restarted negotiated, closing without sending any notification
Sun, 29 Mar 2015 21:19:05 | DEBUG    | 5243   | wire          | session 1 outgoing, closing connection from 100.100.12.103 to 100.100.12.12
^CSun, 29 Mar 2015 21:19:05 | INFO     | 5243   | reactor       | ^C received
Sun, 29 Mar 2015 21:19:05 | INFO     | 5243   | reactor       | Performing shutdown
Sun, 29 Mar 2015 21:19:05 | DEBUG    | 5243   | wire          | session 1 outgoing 100.100.11.103 / 100.100.11.11   SENDING FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0037 0104 0064 00B4 6464 64FD 1A02 0840 0600 B400 0180 8002 0601 0400 0100 8002 0641 0400 0000 64
Sun, 29 Mar 2015 21:19:05 | INFO     | 5243   | message       | Peer   100.100.11.11 ASN 100     >> OPEN version=4 asn=100 hold_time=180 router_id=100.100.100.253 capabilities=[Multiprotocol(ipv4 mpls-vpn), Graceful Restart Flags 0x0 Time 180 ipv4/mpls-vpn=0x80, ASN4(100)]
Sun, 29 Mar 2015 21:19:05 | DEBUG    | 5243   | timers        | peer 100.100.11.11 ASN 100     Receive Timer 59 second(s) left
Sun, 29 Mar 2015 21:19:05 | DEBUG    | 5243   | wire          | session 1 outgoing 100.100.11.103 / 100.100.11.11   RECEIVED FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0043 01
Sun, 29 Mar 2015 21:19:05 | DEBUG    | 5243   | wire          | session 1 outgoing 100.100.11.103 / 100.100.11.11   RECEIVED 0400 6400 5A64 6464 0B26 0206 0104 0001 0001 0206 0104 0001 0080 0202 8000 0202 0200 0204 4002 0078 0206 4104 0000 0064
Sun, 29 Mar 2015 21:19:05 | INFO     | 5243   | message       | Peer   100.100.11.11 ASN 100     << OPEN
Sun, 29 Mar 2015 21:19:05 | INFO     | 5243   | message       | Peer   100.100.11.11 ASN 100     << OPEN version=4 asn=100 hold_time=90 router_id=100.100.100.11 capabilities=[Multiprotocol(ipv4 unicast,ipv4 mpls-vpn), Route Refresh, Graceful Restart Flags 0x0 Time 120 , ASN4(100), Route Refresh]
Sun, 29 Mar 2015 21:19:05 | DEBUG    | 5243   | timers        | peer 100.100.11.11 ASN 100     Receive Timer 59 second(s) left
Sun, 29 Mar 2015 21:19:05 | DEBUG    | 5243   | wire          | session 1 outgoing 100.100.11.103 / 100.100.11.11   SENDING FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
Sun, 29 Mar 2015 21:19:05 | INFO     | 5243   | message       | Peer   100.100.11.11 ASN 100     >> KEEPALIVE (OPENCONFIRM)
Sun, 29 Mar 2015 21:19:05 | DEBUG    | 5243   | wire          | session 1 outgoing 100.100.11.103 / 100.100.11.11   RECEIVED FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
Sun, 29 Mar 2015 21:19:05 | INFO     | 5243   | message       | Peer   100.100.11.11 ASN 100     << KEEPALIVE
Sun, 29 Mar 2015 21:19:05 | DEBUG    | 5243   | timers        | peer 100.100.11.11 ASN 100     Receive Timer 89 second(s) left
Sun, 29 Mar 2015 21:19:05 | DEBUG    | 5243   | wire          | session 1 outgoing 100.100.11.103 / 100.100.11.11   SENDING FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0027 0306 0350 6565 7220 4465 2D63 6F6E 6669 6775 7265 64
Sun, 29 Mar 2015 21:19:05 | INFO     | 5243   | message       | Peer   100.100.11.11 ASN 100     >> NOTIFICATION (6,3,"Peer De-configured")
Sun, 29 Mar 2015 21:19:05 | INFO     | 5243   | network       | Peer   100.100.11.11 ASN 100     automatic protocol cleanup
Sun, 29 Mar 2015 21:19:05 | DEBUG    | 5243   | wire          | session 1 outgoing, closing connection from 100.100.11.103 to 100.100.11.11
^CSun, 29 Mar 2015 21:19:06 | INFO     | 5243   | reactor       | ^C received
root@omega:/opt/exabgp-3.4.9/sbin# 
root@omega:/opt/exabgp-3.4.9/sbin# cat bgp-3 
group rs {
   neighbor 100.100.11.11 {
     router-id 100.100.100.253;
     local-address 100.100.11.103;
     local-as 100;
     peer-as 100;
     graceful-restart;
     group-updates;
     static {
        route 11.0.0.0/18 rd 100:254 next-hop 100.100.100.7 extended-community [ 0x0002FDE800000001 0x0002271000000001 ] label 1000 split /32;
     }
     family {
      inet4 mpls-vpn;
     }
   }
   neighbor 100.100.12.12 {
     router-id 100.100.100.253;
     local-address 100.100.12.103;
     local-as 100;
     peer-as 100;
     graceful-restart;
     group-updates;
     family {
      inet4 mpls-vpn;
     }
   }
}

**Comment by thomas-mangin** [comment]
Hi - should be fixed with this patch.
https://github.com/Exa-Networks/exabgp/commit/79d20e3e632ea8ece6e2443475c61ad31a531908
