### ISSUE TITLE
pip does not install example files

### ISSUE THREAD

**Issue by ARCHAJ** [Exa-Networks/exabgp#247]
Hello everyone,
I have a question , I couldn't find the configuration files on my Ubuntu 14.04 lts.
![exabgp_3-4-9_files](https://cloud.githubusercontent.com/assets/11909376/7105023/ca3ee8e4-e0f3-11e4-8eb4-c16f328cfe81.png)

**Comment by thomas-mangin** [comment]
@vincentbernat for more information, I got a mail from @ARCHAJ telling me that under unbuntu there was no configuration file anymore ( perhaps not even an example ). Could it be as they updated to the latest debian version ? should we make sure a sample file is present ?

**Comment by vincentbernat** [comment]
The screenshot is not from the Debian package (use of `/usr/local`). But, yes, in the Debian package, there is no more a default `/etc/exabgp/exabgp.conf` (which was empty with a comment pointing to `/usr/share/doc/exabgp/examples`) because we use that to know if we should start the daemon. This is considered as the right thing to do for daemons where no default sensible configuration file can be provided.

**Comment by ARCHAJ** [comment]
Thank you for response :)
I have searched at /usr/share/doc there is no exabgp folder there.

**Comment by vincentbernat** [comment]
I am a bit lost about what this bug report is about. How did you install exabgp?

**Comment by ARCHAJ** [comment]
I installed pip , and after i made: 
root..#pip install exabgp

**Comment by thomas-mangin** [comment]
@ARCHAJ pip does not install the documentation. I will be updating it to do so but in the meanwhile the solution would be to use the github repository to find what you need. Thank you for reporting this issue to us.

**Comment by thomas-mangin** [comment]
For clarity, ExaBGP's documentation is nearly non-existent and you will need to learn about it looking at the various examples in the qa folder.

**Comment by ARCHAJ** [comment]
could you precise me , where shall i make the qa folder,or the exabgp config file to work with it . 
another question ,witch operating system and a way to install exabgp do you suggest ?

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/tree/master/qa/conf
