### ISSUE TITLE
 capability asn4 unexpected behavior (v.3.4.10)

### ISSUE THREAD

**Issue by Orangefish** [Exa-Networks/exabgp#250]
When i turn off 4b ASN (capability  asn4 disable)
ExaBGP  send AS-number in AS_PATH PA  as  4b value.

For example :
capability  asn4 disable;
announce route with as-path [ 100 ]

neighbor router turn down session and:
"%BGP-3-NOTIFICATION: sent to neighbor 1.1.1.1 3/11 (invalid or corrupt AS path) 9 bytes 40020602 01000000 64"

AS_PATH contain 4b value (00 00 00 64):
40 02 06 02 01 00 00 00 64

But correct AS_PATH :
40 02 06 02 01 00 64

**Comment by thomas-mangin** [comment]
Hello @Orangefish - could you please confirm that the issue is well/still present on 3.4.10 ?

**Comment by thomas-mangin** [comment]
And I can not read :laughing: - will look at it and fix.

**Comment by thomas-mangin** [comment]
@Orangefish - this patch should fix the issue if you apply it on 3.4.10
https://github.com/thomas-mangin/exabgp/commit/ee7179ae4c08ba645bdc682c516f1a9b14e01cd5

I need to look at how best use git to create a 3.4 stable branch and apply the two last patch which are bug fixes only.

**Comment by thomas-mangin** [comment]
This patch is now also on a new branch called 3.4 which will contain only bug fixes which can be backported from master (3.5.x) to (3.4.x)
