### ISSUE TITLE
processes started as root

### ISSUE THREAD

**Issue by fobser** [Exa-Networks/exabgp#252]
On 3.4.10 (don't know when it started, it's working fine on 3.4.5) processes are started as root.
Depending on what you are doing hilarity ensues (e.g. writing json out to disk, the files will be owned by the wrong user etc.)
exabgp itself drops to nobody which then means that you can no longer stop exabgp because it tries to take down the forked processes which it no longer can do.

When killing a forked process exabgp will respawn it and of course now the process is running as nobody.

**Comment by pyke369** [comment]
Saw the exact same problem here: a privileges drop for the main exabgp process, but helper processes running as root _on the first launch_ (but then running as the same use as the main exabgp process when re-started, with the exact same "hanging" issue as described above).

**Comment by thomas-mangin** [comment]
I had complication during the development of the incoming MD5 connection as the way the kernel handle the binding. This bug is likely a side effect of this ! I will rectify.

**Comment by thomas-mangin** [comment]
This should be fixed both on 3.5 and 3.4 with this commit d803487

**Comment by thomas-mangin** [comment]
This also could have been related to https://github.com/Exa-Networks/exabgp/commit/a97353bb4923fa755926430a6beaed3403129a20

**Comment by fobser** [comment]
works for me

**Comment by thomas-mangin** [comment]
And again - much appreciated :smile:
