### ISSUE TITLE
bin/exabgp missing when turning into a python wheel

### ISSUE THREAD

**Issue by fobser** [Exa-Networks/exabgp#253]
When I turn 3.4.10 into a wheel and pip install it (in a virtualenv) on centos 6 bin/exabgp is not there. Curiously it turns up when installing the wheel on OS X. So it might be pip version related?
This used to work on 3.4.5.

It looks like bin/exabgp is somehow generated as a post-install action? I'm wondering why it's not shipped as a data/script/... thingy.

**Comment by fobser** [comment]
Ok, we figured it out. It's a pip version problem. I.e. pip from epel is to old. If we update pip in the virtual env it works just fine. Also we think what you are doing in setup.py with entry_points is kinda nice :)

**Comment by thomas-mangin** [comment]
Thank you for finding out what it was .. I would have been hard pressed to reproduce the issue !
