### ISSUE TITLE
BGP flow spec parser/crafter separation to dedicated library

### ISSUE THREAD

**Issue by pavel-odintsov** [Exa-Networks/exabgp#261]
Hello, Thomas!

Do you have any ideas about providing BGP flow spec parser/crafter as separate Python library? 

I found so much very interesting code for this task:

``` bash
lib/exabgp/protocol/ip
lib/exabgp/protocol/ip/__init__.py
lib/exabgp/protocol/ip/address.py
lib/exabgp/protocol/ip/fragment.py
lib/exabgp/protocol/ip/icmp.py
lib/exabgp/protocol/ip/tcp
lib/exabgp/protocol/ip/tcp/__init__.py
lib/exabgp/protocol/ip/tcp/flag.py
```

And I and everyone need strong and reliable parser for generating flow spec for ExaBGP and for parsing flow spec from ExaBGP. 

And your code is awesome and haven't any competitors. 

I could help with it (my Python is as bad as my english but I could try!).

**Comment by thomas-mangin** [comment]
Yes, sure, if the code can be helpful then yes. I need to work on other area first but if you give it a try I will help you.

**Comment by pavel-odintsov** [comment]
Hi!

Thomas, I have finished some investigation and found few very interesting things. First of all, I found you have used Juniper syntax and it's awesome because Cisco and Alcatel syntax is very complex and scary.

But I found significant differences in config format for announces and receives sides.

I have following announce:
```bash
        flow {
            route block_traffic_to_proxy {
                match {
                    source 10.0.0.1/32;
                    destination 10.0.0.2/32;
                    destination-port =3128;
                    source-port =1234;
                    tcp-flags syn;
                    fragment is-fragment;
                }   
                then {
                    discard;
               }
            }
        }
```

On receiving side in "string" field I have it in different format:
```bash
flow destination-ipv4 10.0.0.2/32 source-ipv4 10.0.0.1/32 destination-port =3128 source-port =1234 tcp-flags =syn fragment =is-fragment
```

But I can't specify this line: ```tcp-flags =syn``` because it requires only "tcp-flags syn" format without equal sign.

In ExaBGP configuration:
```bash
Sat, 16 May 2015 21:01:41 | ERROR    | 3524   | configuration | syntax error in section match
Sat, 16 May 2015 21:01:41 | ERROR    | 3524   | configuration | line 18: tcp-flags =syn ;
```

Same issue with "fragment =is-fragment". I could specify "fragment is-fragment" in Exa config but can't specify: "fragment =is-fragment".

What about full compatibility in field names for both sides?

**Comment by pavel-odintsov** [comment]
Will be fine if we can got string representation of flow from receiver side and put it in ExaBGP configuration without any changes. With this approach we could use same parser for generation (for ExaBGP config) and for parsing (from update API hook) for passing data forward.

**Comment by pavel-odintsov** [comment]
We could use same approach as blackhole announce. I found in examples:
```bash
self.wfile.write(' example: withdraw flow route {\\n match {\\n source 10.0.0.1/32;\\n destination 1.2.3.4/32;\\n }\\n then {\\n discard;\\n }\\n }\\n\n')
```

**Comment by pavel-odintsov** [comment]
And will be fine to get single line flow rule representation because current implementation of remote triggered flow announce saw very complex:
```bash
self.wfile.write(' example: withdraw flow route {\\n match {\\n source 10.0.0.1/32;\\n destination 1.2.3.4/32;\\n }\\n then {\\n discard;\\n }\\n }\\n\n')
```

And sing line representation looks more pretty:
```bash
flow route { match { source 10.0.0.1/32; destination 1.2.3.4/32; } then { discard; } }'
```

**Comment by thomas-mangin** [comment]
The printing is Junos like but the format is configuration like ( using list ) so you need 
`fragment [ is-fragement ]`
if I recall correctly.

**Comment by thomas-mangin** [comment]
Hi @pavel-odintsov , it would be nice if you tried to not mix threads as following what is happening is quite hard.
This whole thead is supposed to be about separation of library and it is not :p Could you please re-open the initial question in a new issue and I will rename this thread to match the content. Thank you.

**Comment by pavel-odintsov** [comment]
Oh, sorry. Will sure create new ticket ASAP! :)

**Comment by pavel-odintsov** [comment]
Moved to new ticket: https://github.com/Exa-Networks/exabgp/issues/266 This ticket dedicated for library discussion only.

**Comment by thomas-mangin** [comment]
The code is already used as a library by BaGPipe. I would rather be able to change the code when needed without having to worry about any compatibility so as there is little demand for it. I would say no, and close the issue.
