### ISSUE TITLE
Need offical documentation and script examples for collecting BGP routes

### ISSUE THREAD

**Issue by victor-sudakov** [Exa-Networks/exabgp#262]
There is neither documentation nor script examples for collecting/saving BGP routes for further processing (like building src/dst ACLs for squid for example). I would like some to be provided in the distribution.

**Comment by pyke369** [comment]
Hello Victor,

You may want to take a look at https://github.com/pyke369/exabgp-helpers/tree/master/exaprefixdb. This little ExaBGP helper script will actually dump the routes/prefixes received from an arbitrary number of BGP sessions in multiple files at a regular interval, relying on filters like ASPath, BGP community or BGP peers. It actually works fine with multiples copies of the global Internet public table, received from multiple routers with multiple Tier-1 transit links.

I will add some documentation later, but there is an example configuration file (JSON-based) along with the corresponding ExaBGP configuration file. You may then export the generated text files into fast-lookup databases using https://github.com/pyke369/prefixdb for instance (this comes handy for SDN/applicative routing management). 

Cheers.

**Comment by thomas-mangin** [comment]
@pyke369 how about integrating this tool within the exabgp repository ? I would be fine giving you commit access to be able to maintain the code.

**Comment by victor-sudakov** [comment]
@pyke369 Are you sure there is no error in line 10 of exaprefixdb-sample.conf? I am almost sure there should be no comma there.

**Comment by pyke369** [comment]
@victor-sudakov yes, you are absolutely right:

```
$ cat exaprefixdb-sample.conf | python -mjson.tool
Expecting property name: line 11 column 4 (char 234)
```

I fixed it in the repository. Please note this already is an advanced configuration (with 4 BGP sessions and a lot of filtering). The simplest one you could start with is more like:

```
{
   "exports":
   [
      { "database": "all" }
   ]
}
```
This will dump all received routes from all established BGP sessions in /tmp/all.db every 10 minutes. You could start with this and then introduce more complexity if needed.

**Comment by pyke369** [comment]
@thomas-mangin sure thing. let me just clean the repo. a little bit and push a small documentation first.

**Comment by victor-sudakov** [comment]
@pyke369 I'm trying to test it with exabgp-3.4.8 with a simple config (see below) but my database comes out empty all the time. Any ideas why?

exaprefixdb.conf:
{
   "interval": 180,
   "backups":  5,
   "basepath": "/var/tmp/prefixdb",
   "aliases":
   {
       "212.73.125.217": "gateway",
       "212.73.125.216": "leopard"
   },
   "exports":
   [
      { "database": "all" }
   ]
}

exabgp.conf:
        process mkdb {
                encoder json;
                receive {
                        parsed;
                        update;
                }
                run /usr/local/etc/exabgp/exaprefixdb.py /usr/local/etc/exabgp/exaprefixdb.conf;
}

**Comment by pyke369** [comment]
@victor-sudakov could you check the following please?

- the exaprefixdb.py is being started by exabgp and running properly
- the user running the exaprefixdb.py process has write access to the the /var/tmp/prefixdb folder
- you waited at least <interval> seconds (180 seconds in your case, we wait that long to make sure the first dump is not empty or partial, especially with Internet full-tables)
- your BGP peers are actually sending routes updates

You may try to start ExaBGP in foreground mode ("exabgp exabgp.conf") and check the messages on the screen (search for routes updates). In addition, try to "kill -USR1 <exaprefixdb.py PID>" to activate additional syslog debug messages.

**Comment by victor-sudakov** [comment]
Yes to your first three questions. Because the file /var/tmp/prefixdb/all.db is indeed being created, but it contains only a linefeed and no prefixes. It would not be created if there were permission or starting problems.

As to the fourth question. The cisco router thinks it's sending prefixes to exabgp, but I cannot make sure it is receiving them.

Sat, 16 May 2015 23:11:45 | WARNING  | 96069  | daemon        | Created PIDfile /var/run/exabgp/exabgp.pid with value 96072
Sat, 16 May 2015 23:11:45 | INFO     | 96069  | reactor       | Performing reload of exabgp 3.4.8
Sat, 16 May 2015 23:11:51 | INFO     | 96069  | reactor       | New peer setup: neighbor 212.73.125.216 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open
Sat, 16 May 2015 23:11:51 | INFO     | 96069  | reactor       | New peer setup: neighbor 212.73.125.217 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open
Sat, 16 May 2015 23:11:51 | INFO     | 96069  | processes     | Forked process mkdb
Sat, 16 May 2015 23:11:54 | INFO     | 96069  | network       | Connected to peer neighbor 212.73.125.216 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open (out)
Sat, 16 May 2015 23:11:54 | INFO     | 96069  | network       | Connected to peer neighbor 212.73.125.217 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open (out)
Sat, 16 May 2015 23:12:02 | INFO     | 96069  | reactor       | SIG USR1 received - reload configuration
Sat, 16 May 2015 23:12:02 | INFO     | 96069  | reactor       | Performing reload of exabgp 3.4.8
Sat, 16 May 2015 23:12:09 | INFO     | 96069  | reactor       | Peer definition identical, updating peer routes if required for neighbor 212.73.125.216 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open
Sat, 16 May 2015 23:12:09 | INFO     | 96069  | reactor       | Peer definition identical, updating peer routes if required for neighbor 212.73.125.217 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open
Sat, 16 May 2015 23:12:09 | INFO     | 96069  | processes     | process already running
Sat, 16 May 2015 23:12:56 | INFO     | 96069  | reactor       | SIG USR1 received - reload configuration
Sat, 16 May 2015 23:12:57 | INFO     | 96069  | reactor       | Performing reload of exabgp 3.4.8
Sat, 16 May 2015 23:13:04 | INFO     | 96069  | reactor       | Peer definition identical, updating peer routes if required for neighbor 212.73.125.216 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open
Sat, 16 May 2015 23:13:04 | INFO     | 96069  | reactor       | Peer definition identical, updating peer routes if required for neighbor 212.73.125.217 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open
Sat, 16 May 2015 23:13:04 | INFO     | 96069  | processes     | process already running
Sat, 16 May 2015 23:11:45 | WARNING  | 96069  | daemon        | Created PIDfile /var/run/exabgp/exabgp.pid with value 96072
Sat, 16 May 2015 23:11:45 | INFO     | 96069  | reactor       | Performing reload of exabgp 3.4.8
Sat, 16 May 2015 23:11:51 | INFO     | 96069  | reactor       | New peer setup: neighbor 212.73.125.216 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open
Sat, 16 May 2015 23:11:51 | INFO     | 96069  | reactor       | New peer setup: neighbor 212.73.125.217 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open
Sat, 16 May 2015 23:11:51 | INFO     | 96069  | processes     | Forked process mkdb
Sat, 16 May 2015 23:11:54 | INFO     | 96069  | network       | Connected to peer neighbor 212.73.125.216 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open (out)
Sat, 16 May 2015 23:11:54 | INFO     | 96069  | network       | Connected to peer neighbor 212.73.125.217 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open (out)
Sat, 16 May 2015 23:12:02 | INFO     | 96069  | reactor       | SIG USR1 received - reload configuration
Sat, 16 May 2015 23:12:02 | INFO     | 96069  | reactor       | Performing reload of exabgp 3.4.8
Sat, 16 May 2015 23:12:09 | INFO     | 96069  | reactor       | Peer definition identical, updating peer routes if required for neighbor 212.73.125.216 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open
Sat, 16 May 2015 23:12:09 | INFO     | 96069  | reactor       | Peer definition identical, updating peer routes if required for neighbor 212.73.125.217 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open
Sat, 16 May 2015 23:12:09 | INFO     | 96069  | processes     | process already running
Sat, 16 May 2015 23:12:56 | INFO     | 96069  | reactor       | SIG USR1 received - reload configuration
Sat, 16 May 2015 23:12:57 | INFO     | 96069  | reactor       | Performing reload of exabgp 3.4.8
Sat, 16 May 2015 23:13:04 | INFO     | 96069  | reactor       | Peer definition identical, updating peer routes if required for neighbor 212.73.125.216 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open
Sat, 16 May 2015 23:13:04 | INFO     | 96069  | reactor       | Peer definition identical, updating peer routes if required for neighbor 212.73.125.217 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open
Sat, 16 May 2015 23:13:04 | INFO     | 96069  | processes     | process already running

**Comment by victor-sudakov** [comment]
And where did you learn about exabgp_log_all ? It's not found anywhere in the exabgp code as "pkg info -l exabgp | xargs grep -i exabgp_log_all" shows nothing. 

Neither does "exabgp /usr/local/etc/exabgp/exabgp.conf" start anything in the foreground. In FreeBSD exabgp is started from a rc.d script and looks like this in the ps output:

97002 ??  R        0:06,39 /usr/local/bin/python2.7 /usr/local/lib/python2.7/site-packages/exabgp/application/bgp.py --folder /usr/local/etc/exabgp /usr/local/etc/exabgp/exabgp.conf
97022 ??  RL       0:00,01 /usr/local/bin/python2.7 /usr/local/etc/exabgp/exaprefixdb.py /usr/local/etc/exabgp/exaprefixdb.conf

**Comment by pyke369** [comment]
"exabgp_log_all=true" is just a way of setting an environment variable before starting the exabgp process itself. you can find about environment variables by just starting exabgp with no argument (see option 4) to set env. variables below).

```
ExaBGP will automatically look for its configuration file (in windows ini format):
 * in the etc/exabgp folder located within the extracted tar.gz
 * in /etc/exabgp/exabgp.env

Individual configuration options can be set using environment variables, such as:
 > env exabgp.daemon.daemonize=true ./sbin/exabgp
or:
 > env exabgp.daemon.daemonize=true ./sbin/exabgp
or:
 > export exabgp.daemon.daemonize=true; ./sbin/exabgp

Multiple environment values can be set, the order of preference being:
 1) command line environment value using dot separated notation
 2) exported value from the shell using dot separated notation
 3) command line environment value using underscore separated notation
 4) exported value from the shell using underscore separated notation
 5) the value in the ini configuration file
 6) the built-in defaults
```

I don't know about the specifics of the FreeBSD packaging (I'm using Linux), but you should probably stop the stock ExaBGP daemon first (using the rc.d script, something like "/etc/rc.d/exabgp stop") and then try:

exabgp_daemon_daemonize=false exabgp_log_all=true exabgp <your_conf_file>

(to make sure ExaBGP does not daemonize itself). As for your trace above, I don't see any "routes" messages showing routes updates from the Cisco router. Try adding "exabgp_log_routes=true" just in case (but "exabgp_log_all=true" should already take care of this).

**Comment by victor-sudakov** [comment]
I don't see the environment variable "exabgp_log_all" anywhere in the exabgp code. How does it make sense?

**Comment by thomas-mangin** [comment]
./sbin/exabgp -h

https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/configuration/setup.py
https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/configuration/environment.py

**Comment by victor-sudakov** [comment]
This must be some FreeBSD specific issue then. Look:

# /usr/local/sbin/exabgp -h
# /usr/local/sbin/exabgp 
===> To start exabgp, you should use:
===>   service exabgp start
# grep log_all /usr/local/lib/python2.7/site-packages/exabgp/configuration/environment.py
# 

All is empty, as you see. Is there anything I could put into exabgp.conf to enable debug?

**Comment by victor-sudakov** [comment]
It must be some FreeBSD specific issue then.  Look:

$ /usr/local/sbin/exabgp
===> To start exabgp, you should use:
===>   service exabgp start
$ /usr/local/sbin/exabgp -h
$ grep log_all /usr/local/lib/python2.7/site-packages/exabgp/configuration/environment.py
$ 

Is there anything I can put into exabgp.conf itself to enable debug?

**Comment by pyke369** [comment]
Not in exabgp.conf directly, but in exabgp.env. This file should be located in the /etc/exabgp folder (and if it does not already exists, you can still use "exabgp --fi" to generate a first template and go from there).

```
[exabgp.log]
all = true
routes = true
```

```
ExaBGP will automatically look for its configuration file (in windows ini format):
 * in the etc/exabgp folder located within the extracted tar.gz
 * in /etc/exabgp/exabgp.env
```

**Comment by victor-sudakov** [comment]
Bingo, now I have a very detailed exabgp log with lots of updates. For some reason however, those updates are not passed to the script which I run from the "process" section. The only thing I see passed to this script is the line 

{ "exabgp": "3.4.8", "time": 1431858703, "host" : "noc.sibptus.ru", "pid" : "3455", "ppid" : "1", "counter": 1, "type": "notification", "notification": "shutdown"}

and then nothing.

The exabgp log can be downloaded from ftp://ftp.sibptus.ru/pub/vas/exabgp.log.zip

It's mostly a question to Thomas I guess.

**Comment by thomas-mangin** [comment]
If you are running master make sure "parsed" is in your receive section.

**Comment by victor-sudakov** [comment]
@thomas-mangin I have published the complete log at ftp://ftp.sibptus.ru/pub/vas/exabgp.log.zip
it includes also the config file, could you please look if anything is missing or in the wrong section?

**Comment by thomas-mangin** [comment]
Updates generated from ExaBGP itself are not send to the script. If you need this feature you need to use master and then to change the section from "receive" to "send" to see what was generated.

**Comment by victor-sudakov** [comment]
@thomas-mangin I don't need updates generated by ExaBGP itself. I need updates received by ExaBGP from its two peers to be sent to the script.

Let's consider the prefix 31.211.40.0/22 received by ExaBGP from 212.73.125.216
You can see in the log that ExaBGP is receiving this prefix.

Sun, 17 May 2015 17:04:26 | INFO     | 49814  | parser        | parsed announce nlri 31.211.40.0/22 next-hop 213.183.111.225 payload 161F D328

Why is this prefix not sent to the script?

**Comment by thomas-mangin** [comment]
Because the current parser is brain dead, put the process section before your neighbors and tell me if it fixes it.

**Comment by victor-sudakov** [comment]
Yes, putting the process section before the neighbors fixes it. Who might think!

**Comment by victor-sudakov** [comment]
Now exaprefixdb is also working as expected. Thank you guys!

**Comment by thomas-mangin** [comment]
I will close this thread. Clearly no documentation was written but it is of little use for everyone and docs are a know issue - they do not need an entry here :cry:
