### ISSUE TITLE
Different format of slow spec in ExaBGP config for announcements and from receiving side

### ISSUE THREAD

**Issue by pavel-odintsov** [Exa-Networks/exabgp#266]
Hi!

Thomas, I have finished some investigation and found few very interesting things. First of all, I found you have used Juniper syntax and it's awesome because Cisco and Alcatel syntax is very complex and scary.

But I found significant differences in config format for announces and receives sides.

I have following announce:
```bash
        flow {
            route block_traffic_to_proxy {
                match {
                    source 10.0.0.1/32;
                    destination 10.0.0.2/32;
                    destination-port =3128;
                    source-port =1234;
                    tcp-flags syn;
                    fragment is-fragment;
                }   
                then {
                    discard;
               }
            }
        }
```

On receiving side in "string" field I have it in different format:
```bash
flow destination-ipv4 10.0.0.2/32 source-ipv4 10.0.0.1/32 destination-port =3128 source-port =1234 tcp-flags =syn fragment =is-fragment
```

But I can't specify this line: ```tcp-flags =syn``` because it requires only "tcp-flags syn" format without equal sign.

In ExaBGP configuration:
```bash
Sat, 16 May 2015 21:01:41 | ERROR    | 3524   | configuration | syntax error in section match
Sat, 16 May 2015 21:01:41 | ERROR    | 3524   | configuration | line 18: tcp-flags =syn ;
```

Same issue with "fragment =is-fragment". I could specify "fragment is-fragment" in Exa config but can't specify: "fragment =is-fragment".

What about full compatibility in field names for both sides? 

Will be fine if we can got string representation of flow from receiver side and put it in ExaBGP configuration without any changes. With this approach we could use same parser for generation (for ExaBGP config) and for parsing (from update API hook) for passing data forward.

And will be fine to get single line flow rule representation because current implementation of remote triggered flow announce saw very complex:
```bash
self.wfile.write(' example: withdraw flow route {\\n match {\\n source 10.0.0.1/32;\\n destination 1.2.3.4/32;\\n }\\n then {\\n discard;\\n }\\n }\\n\n')
```

And sing line representation looks more pretty:
```bash
flow route { match { source 10.0.0.1/32; destination 1.2.3.4/32; } then { discard; } }'
```

**Comment by thomas-mangin** [comment]
For the simple case of = for flag, protocol, icmp type, icmp code, fragment, this has been added with https://github.com/Exa-Networks/exabgp/commit/7f0406b33dcdef266d50a06021a5cae565b96ea7

**Comment by thomas-mangin** [comment]
added trick to allow single line flow https://github.com/Exa-Networks/exabgp/commit/8f5fb1352653f0ed8c1c7ca459919e7224d10f3c

**Comment by pavel-odintsov** [comment]
Now:
```bash
tcp-flags =syn;
fragment =is-fragment;
```

Are working fine!

**Comment by pavel-odintsov** [comment]
Hell, I have issues with single line format.

Old fashioned way works perfectly:
```bash
fl=open("/var/run/exabgp.cmd", "w")
fl.write("announce flow route {\\n match {\\n source 10.0.0.1/32;\\n destination 1.2.3.4/32;\\n }\\n then {\\n discard;\\n }\\n }\\n\n")
fl.write("withdraw flow route {\\n match {\\n source 10.0.0.1/32;\\n destination 1.2.3.4/32;\\n }\\n then {\\n discard;\\n }\\n }\\n\n")
fl.flush()
```

But modern did not work:
```bash
fl=open("/var/run/exabgp.cmd", "w")
fl.write("announce flow route { match { source 10.0.0.1/32; destination 1.2.3.4/32; }  then {  discard;  } } ")
fl.flush()
```

And will be fine if you add some logging when ExaBGP read something from scripts. It will simplify debugging in this case.

**Comment by thomas-mangin** [comment]
I will look into it when I can - must be a silly thing.

**Comment by pavel-odintsov** [comment]
I have created separate ticket for single line flow spec rules because this ticket about another issues.

**Comment by thomas-mangin** [comment]
Must have been a missing \n at the end of the single line 😊
