### ISSUE TITLE
Withdrawal of flow spec announce on ExaBGP daemon interruption

### ISSUE THREAD

**Issue by pavel-odintsov** [Exa-Networks/exabgp#267]
Hello, Tomas!

I have implemented very draft integration of netmap-ipfw and flow spec with huge help from ExaBGP!

Now I could add filtering rules from flow spec announces https://github.com/FastVPSEestiOu/fastnetmon/blob/master/src/scripts/firewall_queue.py :)

But when I interrupt ExaBGP which announces this flows I expected withdrawal of announces because I want to remove they from firewall tables. But there are no actions in update log about it after CTRL+C.

Maybe you can add this feature for explicit switching off announced flows?

Additionally, will be fine to get way to notify my tool about "wasted flows", i.e. flows from peers which go away.

**Comment by thomas-mangin** [comment]
Hello Pavel, This is because on shutdown BGP does not send the the withdrawn routes, so there is nothing to send. It just send a notification. So you you make sure you keep a copy of the routes you installed and in the process section register for "neighbour-changes" and on shutdown or peer down, you should remove the routes you added.

**Comment by pavel-odintsov** [comment]
Looks good, I could add information about source of my flows and remove they on peer down. Looks good. Will try it shortly.

**Comment by pavel-odintsov** [comment]
Yes, works for me:

``bash
{   u'counter': 18,
    u'exabgp': u'3.5.0',
    u'host': u'filter.fv.ee',
    u'neighbor': {   u'address': {   u'local': u'10.0.3.115',
                                     u'peer': u'10.0.3.114'},
                     u'asn': {   u'local': u'1234', u'peer': u'65001'},
                     u'reason': u'in loop, peer reset, message [closing connection] error[the TCP connection was closed by the remote end]',
                     u'state': u'down'},
    u'pid': 8334,
    u'ppid': 7369,
    u'time': 1431885455,
    u'type': u'state'}
{   u'exabgp': u'3.5.0',
    u'host': u'filter.fv.ee',
    u'notification': u'shutdown',
    u'pid': 8334,
    u'ppid': 7369,
    u'time': 1431885461,
    u'type': u'notification'}
```

ExaBGP config (maybe someone will be interested in it?):
```bash
group Core_v4 {
    hold-time 180;
    local-as 1234;
    peer-as 65001;
    router-id 10.0.3.115;
    graceful-restart 1200;

    neighbor 10.0.3.114 {
        local-address 10.0.3.115;
        description "Quagga";

        process stdout {
            neighbor-changes;

            receive {
                parsed;
                update;
            }   
    
            encoder json;
            # run /etc/exabgp/exabgp_update_writer.py;
            run /usr/src/fastnetmon/src/scripts/exabgp_queue_writer.py ;
        }   
    }  
}
```
