### ISSUE TITLE
How to distinguish announce and withdraw for BGP Flow Spec from receiver side

### ISSUE THREAD

**Issue by pavel-odintsov** [Exa-Networks/exabgp#270]
Bonjour!

Next step of tests.

I execute following commands from announce peer:
```bash
fl=open("/var/run/exabgp.cmd", "w")
fl.write("announce flow route {\\n match {\\n source 10.0.0.1/32;\\n destination 1.2.3.4/32;\\n }\\n then {\\n discard;\\n }\\n }\\n\n")
fl.flush()
fl.write("withdraw flow route {\\n match {\\n source 10.0.0.1/32;\\n destination 1.2.3.4/32;\\n }\\n then {\\n discard;\\n }\\n }\\n\n")
fl.flush()
````

From ExaBGP side I could perfectly see information about announce:
```bash
{ "exabgp": "3.5.0", "time": 1431939381, "host" : "filter.fv.ee", "pid" : 9683, "ppid" : 9623, "counter": 18, "type": "update", "neighbor": { "address": { "local": "10.0.3.115", "peer": "10.0.3.114" }, "asn": { "local": "1234", "peer": "65001" }, "direction": "receive", "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 65001 ], "confederation-path": [], "extended-community": [ "0x8006000000000000" ] }, "announce": { "ipv4 flow": { "no-nexthop": { "flow-0": { "destination-ipv4": [ "1.2.3.4/32" ], "source-ipv4": [ "10.0.0.1/32" ], "string": "flow destination-ipv4 1.2.3.4/32 source-ipv4 10.0.0.1/32" } } } } } } } }
```

But when I trigger "withdraw" from peer I got enough useless message:
```bash
{ "exabgp": "3.5.0", "time": 1431939400, "host" : "filter.fv.ee", "pid" : 9683, "ppid" : 9623, "counter": 19, "type": "update", "neighbor": { "address": { "local": "10.0.3.115", "peer": "10.0.3.114" }, "asn": { "local": "1234", "peer": "65001" }, "direction": "receive", "message": { "update": { "announce": { "ipv4 unicast": { "null": { "eor": { "afi" : "ipv4", "safi" : "unicast" } } } } } } } }
```

Is it possible to get some ID for this de-announced rule or complete flow spec description? Without this feature ability to disable flow speak announces is useless ;(

**Comment by thomas-mangin** [comment]
This looks wrong - I will investigate.

**Comment by thomas-mangin** [comment]
I added some testing code and it looks right to me :

`{ "exabgp": "3.4.8", "time": 1431975215, "host" : "mangin.local", "pid" : "19692", "ppid" : "19683", "counter": 9, "type": "update", "neighbor": { "ip": "127.0.0.1", "address": { "local": "82.219.212.34", "peer": "127.0.0.1"}, "asn": { "local": "65534", "peer": "65533"}, "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 65533 ], "confederation-path": [], "extended-community": [ 9225060886715039744 ] }, "announce": { "ipv4 flow": { "none": { "flow-6": { "destination": [ "10.0.0.2/32" ], "source": [ "10.0.0.1/32" ], "protocol": [ "=TCP" ], "destination-port": [ "=3128" ], "string": "flow destination 10.0.0.2/32 source 10.0.0.1/32 protocol =TCP destination-port =3128" } } } } } }} }`

`{ "exabgp": "3.4.8", "time": 1431975214, "host" : "mangin.local", "pid" : "19692", "ppid" : "19683", "counter": 8, "type": "update", "neighbor": { "ip": "127.0.0.1", "address": { "local": "82.219.212.34", "peer": "127.0.0.1"}, "asn": { "local": "65534", "peer": "65533"}, "message": { "update": { "withdraw": { "ipv4 flow": { "flow-5": { "destination": [ "10.0.0.2/32" ], "source": [ "10.0.0.1/32" ], "protocol": [ "=TCP" ], "destination-port": [ "=3128" ], "string": "flow destination 10.0.0.2/32 source 10.0.0.1/32 protocol =TCP destination-port =3128" } } } } }} }`

**Comment by thomas-mangin** [comment]
The EOR message you received may have been what is known as an End of RIB (EOR) marker following the full loading of the configuration file. It let the remote router knows that it can sync the routes to the forwarding plane as no more are coming part of the initial route dump.

**Comment by pavel-odintsov** [comment]
Awesome!

I got it for enable announce:
```bash
{ "exabgp": "3.5.0", "time": 1431988410, "host" : "filter.fv.ee", "pid" : 10655, "ppid" : 9979, "counter": 18, "type": "update", "neighbor": { "address": { "local": "10.0.3.115", "peer": "10.0.3.114" }, "asn": { "local": "1234", "peer": "65001" }, "direction": "receive", "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 65001 ], "confederation-path": [], "extended-community": [ 9225060886715039744 ] }, "announce": { "ipv4 flow": { "no-nexthop": { "flow-0": { "destination-ipv4": [ "1.2.3.4/32" ], "source-ipv4": [ "10.0.0.1/32" ], "source-port": [ "=1" ], "string": "flow destination-ipv4 1.2.3.4/32 source-ipv4 10.0.0.1/32 source-port =1" } } } } } } } }
```

And this for disable announce:
```bash
{ "exabgp": "3.5.0", "time": 1431988415, "host" : "filter.fv.ee", "pid" : 10655, "ppid" : 9979, "counter": 19, "type": "update", "neighbor": { "address": { "local": "10.0.3.115", "peer": "10.0.3.114" }, "asn": { "local": "1234", "peer": "65001" }, "direction": "receive", "message": { "update": { "withdraw": { "ipv4 flow": { "flow-1": { "destination-ipv4": [ "1.2.3.4/32" ], "source-ipv4": [ "10.0.0.1/32" ], "source-port": [ "=1" ], "string": "flow destination-ipv4 1.2.3.4/32 source-ipv4 10.0.0.1/32 source-port =1" } } } } } } }
```

**Comment by pavel-odintsov** [comment]
And now I have way to distinguish announce and disable route with: ```"announce": { "ipv4 flow" .. }``` and ```"withdraw": { "ipv4 flow": ... } ```

Thanks!
