### ISSUE TITLE
Please add single line way to specify flow spec

### ISSUE THREAD

**Issue by pavel-odintsov** [Exa-Networks/exabgp#271]
Hello!

As mentioned in https://github.com/Exa-Networks/exabgp/issues/266 will be fine to add support for single line slow spec format.

**Comment by pavel-odintsov** [comment]
Implemented.

And works perfectly:
```python
#!/usr/bin/python

import time
fl=open("/var/run/exabgp.cmd", "w")

i = 1024
# Trailing "\n" is VERY IMPORTANT
fl.write("announce flow route { match { packet-length =1517; source 10.0.0.1/32; source-port =" + str(i) + "; destination 1.2.3.4/32; } then { discard; } } }" + "\n");
fl.flush()
fl.close()
```

**Comment by pavel-odintsov** [comment]
I have checked multiple times against Git version and could not achieve ability to work without trailing "\n". But examples in qa/ folder provide ability to work without trailing "\n".  How?)

**Comment by thomas-mangin** [comment]
There is an example in ./qa/self/flow/

**Comment by thomas-mangin** [comment]
@pavel-odintsov  oh ! and btw, run env exabgp.api.file=/var/run/exabgp.cmd ./sbin/exabgp `configuration file` and look the magic happen ( on 3.5 only ). This named pipe will be for the API (and therefore should not be used by applications but hey - I thought it may be useful for quick checks

**Comment by pavel-odintsov** [comment]
Really useful feature for me ;) Any plans about standard client?

**Comment by thomas-mangin** [comment]
See https://plus.google.com/+ThomasMangin/posts/AD8L7vBikWS

**Comment by pavel-odintsov** [comment]
The requested URL was not found on this server. That’s all we know.

:(

On Friday, May 22, 2015, Thomas Mangin <notifications@github.com> wrote:

> See https://plus.google.com/+ThomasMangin/posts/AD8L7vBikWS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Exa-Networks/exabgp/issues/271#issuecomment-104667198>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by thomas-mangin** [comment]
Ah ! You need to join the G+ ExaBGP community ...
