### ISSUE TITLE
Better control of the relation between process and neighbor

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#280]
Following the report in #268 , add to the configuration format an explicit relation between peer and process section such as 

```
process announce-routes {
   run /run.me;
   encoder json;
}

neighbor ip {
   api receive-mostly  {
      processes [ announce-routes ];
      send {
          open;
      }
      receive {
         packets;
         consolidate;
         open;
         update;
      }
   }
}
```

```
process announce-routes {
   run /run.me;
   encoder json;
}

process raw-consummer {
   run /run.it;
   encoder json;
}

process backup {
   run /run.it;
   encoder json;
}

group notified {
   api parsed-data {
      processes [ announce-routes ];
      send {
          open;
         update;
         notification;
      }
      receive {
         open;
         update;
         notification;
      }
   }
   api raw-dump {
     process [ raw-consummer backup ];
      send {
         packets;
      }
      receive {
         packets;
      }
   }
}
```

Due to the current parser however, it is likely that the process group will need to be created before the neighbor and that having group { neighbor, process, neighbor } will only add the process communication to the second neighbor only.

**Comment by pyke369** [comment]
Hi Thomas,

Do you plan to add this type of relation at the group level? Or will one have to add this directive to each neighbor within a group?

Thx.
Pierre-Yves

**Comment by thomas-mangin** [comment]
I can also add it at group level but I will have to charge you a few beer for the feature :black_joker:

**Comment by thomas-mangin** [comment]
You read the example correctly, it is indeed how I would expect it to work

**Comment by pyke369** [comment]
After some thinking, having the feature at the group level may not really be necessary, since the processes array directive (in each neighbor section) will provide the same thing in a nice way (pfiou, I saved a few beers here ^_^). Do you know when you plan to work on this new syntax? Will you backport it to 3.4.X? Thx.

**Comment by thomas-mangin** [comment]
I will try to put this to the top of the queue, the group feature is only a few lines of code so you will get it anyway .. I plot for beer failed !
The feature is not hard but turn the way the code works around, so it will not be a small patch. Furthermore after thought, I believe the send/receive options should be set per process for finer grained control. So it may end up being.
```
process announce-routes {
   run /run.me;
   encoder json;
}

neighbor ip {
   process announce-routes {
      send {
          open;
      }
      receive {
         packets;
         consolidate;
         open;
         update;
      }
   }
}
```


```
process announce-routes {
   run /run.me;
   encoder json;
}

group notified {
   process announce-routes {
      send {
          open;
      }
      receive {
         packets;
         consolidate;
         open;
         update;
      }
      neighbor ip {
      }
      neighbor ip {
      }
   }
}
```

Due to the current parser however, it is likely that the process group will need to be created before the neighbor and that having group { neighbor, process, neighbor } will only add the process communication to the second neighbor only.

**Comment by pyke369** [comment]
As long as it's clearly stated in the documentation, that shouldn't be a problem. Tell me if you want some help coding this, I'll be glad to help.

**Comment by thomas-mangin** [comment]
@pyke369 .. ok, if you want documentation, the price is not beer anymore, it is wine :smiling_imp: 
Like most programmers I prefer features to bugs and bugs to documentation ... I know this is not good.
BUT you can expect all the examples in the qa/conf folder to have been updated, so it is not all bad ...

**Comment by thepacketgeek** [comment]
I love documentation. I've been following updates for a bit and am trying to familiarize myself with the project and I'd love to help on the docs side. I hope to start making some contributions soon!

**Comment by thomas-mangin** [comment]
@thepacketgeek That is great news to hear. If you need any help or have any question, feel free to grab me on Gitter or IRC.

**Comment by thepacketgeek** [comment]
Will do, I'm about to head away on vacation but would love to sync up the
week after.

**Comment by thomas-mangin** [comment]
I removed a long thread of discussion with @pyke369 and @thepacketgeek as I modified the format of the configuration since the ticket was created and it made it clearer.

**Comment by thomas-mangin** [comment]
implemented on master
