### ISSUE TITLE
Backend process negotiated information on crash / restart

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#282]
ExaBGP currently can send OPEN, then UPDATE message to the backend process. The OPEN information is required to be able to decode UPDATE ( ASN4, and ADD-PATH negotiation ).

Should the process crash, the process need to have persistently store this data otherwise parsing is impossible.

ExaBGP could help by (both or either):
- allow the backend process to re-request both send/received OPEN
- include the OPEN negotiation information in each UPDATE

**Comment by thomas-mangin** [comment]
@fobser - created following our discussion with Colin but unless you really need this feature I would rather push it development down the line.

**Comment by fobser** [comment]
For what we are doing it would be more helpful to have the negotiated capabilities in every update message. We are streaming the data into hadoop and then a job produces update mrt dumps.
It could store the negotiated capabilities somewhere and look it up as needed but from what I understand from our hadoop developer that's pretty inconvenient.
The way the system is setup we can't easily request a re-send of the OPEN message either.

I might have a stab at implementing this myself unless you beat me to it :)

**Comment by thomas-mangin** [comment]
A better way may be to detect when a process has died and re-send any open. It would only require :
 - to save in the neighbor the OPEN send and received
 - to check when forking the process if : 
    * this is not the first time we are starting the process
    * if not then check if OPEN are available, and them them
    * add to the OPEN JSON a way to know if a message is an original or duplicate
The coding for this should be much easier.

**Comment by thomas-mangin** [comment]
I realise this require the backend code to be able to decode the OPEN, so alternatively, we could generate JSON representation of the OPEN negotiation and send this. But this will be ExaBGP specific when the OPEN way mean that the backend only need to be able to unpack JSON and understand BGP.

**Comment by thomas-mangin** [comment]
Forgot about this issue - will work on it when possible.

**Comment by thomas-mangin** [comment]
done with cb9599e3
