### ISSUE TITLE
Provide State Machine Information via API

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#283]
When ExaBGP is used to generate MRT file from a received routing table, the MRT dump need to include BGP FSM code. Currently the backend process needs to generate this data based on the event received ( connection up, peer up, peer down ). It would simplify the code of the backend process if ExaBGP were to generate this data.

**Comment by thomas-mangin** [comment]
@fobser - created following our discussion with Colin but unless you really need this feature I would rather push it development down the line.

**Comment by fobser** [comment]
The BGP4MP_STATE_CHANGE{,_AS4} subtypes contain old state and new state, so that's what we need in json output.

**Comment by thomas-mangin** [comment]
The code was changed to improve the FSM, it should now be easy to hook a JSON call once the option is added.

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/commit/4aa37b03d37b8f90149e529a6133480feb05ca18

Now I have not checked that all the state are correct (mostly IDLE/ACTIVE) - just under two years .. Not really a stellar response time.
