### ISSUE TITLE
Unsupported Optional Parameter

### ISSUE THREAD

**Issue by irom77** [Exa-Networks/exabgp#289]
Setup BGP with Checkpoint Gaia and getting Unsupported Optional Parameter notification , see below:

Fri, 05 Jun 2015 10:38:32 | INFO     | 13387  | network       | Peer      10.29.1.68 ASN 65000   out loop, peer reset, message [notification received (2,4)] error[OPEN message error / Unsupported Optional Parameter]

No problem with Cisco router at the same time, how I can debug exaBGP ?

**Comment by thomas-mangin** [comment]
Please run exabgp with -d on the command line and provide the output on this issue. Can you please run either 3.4.11 or the 3.4 branch when testing, to make sure the bug is not already fixed.

**Comment by irom77** [comment]
I 'fixed' it by adding ' ipv4 unicast;' 

family {
        ipv4 unicast;
    }        
Thnx

**Comment by thomas-mangin** [comment]
This is great news but it should not have been an issue in the first place. Could you please still send me the output ? Thank you.

**Comment by irom77** [comment]
Here it is :
Sun, 07 Jun 2015 09:54:14 | DEBUG    | 4340   | wire          | Attempting connection to 10.29.1.68
Sun, 07 Jun 2015 09:54:16 | DEBUG    | 4340   | wire          | session 1 outgoing 10.29.1.102 / 10.29.1.68         SENDING  (312) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 007D 0104 FDE8 00B4 0A1D 0166 6002 0601 0400 0100 0102 0601 0400 0100 0202 0601 0400 0100 0402 0601 0400 0100 8002 0601 0400 0100 8502 0601 0400 0100 8602 0601 0400 0200 0102 0601 0400 0200 8002 0601 0400 0200 8502 0601 0400 0200 8602 0601 0400 1900 4102 0641 0400 00FD E8
Sun, 07 Jun 2015 09:54:16 | INFO     | 4340   | message       | Peer      10.29.1.68 ASN 65000   >> OPEN version=4 asn=65000 hold_time=180 router_id=10.29.1.102 capabilities=[Multiprotocol(ipv4 unicast,ipv4 multicast,ipv4 nlri-mpls,ipv4 mpls-vpn,ipv4 flow,ipv4 flow-vpn,ipv6 unicast,ipv6 mpls-vpn,ipv6 flow,ipv6 flow-vpn,l2vpn vpls), ASN4(65000)]
Sun, 07 Jun 2015 09:54:16 | DEBUG    | 4340   | timers        | peer 10.29.1.68 ASN 65000   Receive Timer 59 second(s) left
Sun, 07 Jun 2015 09:54:16 | DEBUG    | 4340   | wire          | session 1 outgoing 10.29.1.102 / 10.29.1.68         RECEIVED  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001D 01
Sun, 07 Jun 2015 09:54:16 | DEBUG    | 4340   | wire          | session 1 outgoing 10.29.1.102 / 10.29.1.68         RECEIVED  (24) 04FD E800 B403 0301 0A00
Sun, 07 Jun 2015 09:54:16 | INFO     | 4340   | message       | Peer      10.29.1.68 ASN 65000   << OPEN
Sun, 07 Jun 2015 09:54:16 | INFO     | 4340   | message       | Peer      10.29.1.68 ASN 65000   << OPEN version=4 asn=65000 hold_time=180 router_id=3.3.1.10 capabilities=[]
Sun, 07 Jun 2015 09:54:16 | DEBUG    | 4340   | timers        | peer 10.29.1.68 ASN 65000   Receive Timer 59 second(s) left
Sun, 07 Jun 2015 09:54:16 | DEBUG    | 4340   | wire          | session 1 outgoing 10.29.1.102 / 10.29.1.68         SENDING  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
Sun, 07 Jun 2015 09:54:16 | INFO     | 4340   | message       | Peer      10.29.1.68 ASN 65000   >> KEEPALIVE (OPENCONFIRM)
Sun, 07 Jun 2015 09:54:16 | DEBUG    | 4340   | wire          | session 1 outgoing 10.29.1.102 / 10.29.1.68         RECEIVED  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0015 03
Sun, 07 Jun 2015 09:54:16 | DEBUG    | 4340   | wire          | session 1 outgoing 10.29.1.102 / 10.29.1.68         RECEIVED  (4) 0204
Sun, 07 Jun 2015 09:54:16 | INFO     | 4340   | message       | Peer      10.29.1.68 ASN 65000   << NOTIFICATION
Sun, 07 Jun 2015 09:54:16 | INFO     | 4340   | network       | Peer      10.29.1.68 ASN 65000   out loop, peer reset, message [notification received (2,4)] error[OPEN message error / Unsupported Optional Parameter]
Sun, 07 Jun 2015 09:54:16 | DEBUG    | 4340   | wire          | session 1 outgoing, closing connection from 10.29.1.102 to 10.29.1.68

**Comment by thomas-mangin** [comment]
Thank you :+1: , I will investigate

**Comment by thomas-mangin** [comment]
Ok, The peer is sending us a notification (2,4) during the setup instead of a KEEPALIVE to get into OPENCONFIRM. So, IMHO the BGP implementation of the vendor is broken and can not handle the Multi Protocol extension we are sending ( it should just ignore it ).
Thank you for this, AFAICS, nothing I can do to improve ExaBGP and/or prevent to hit the bug.

**Comment by irom77** [comment]
Agreed, Thnx
