### ISSUE TITLE
Multiple IPv6 MPREACH attributes in one UPDATE can not be decoded

### ISSUE THREAD

**Issue by stroboscope** [Exa-Networks/exabgp#298]
Hello

Can you explain - this is a problem with configuration or incorrect exabgp behavior?

There are 2 routes in config.

        static {
                 route a:b:c:22::a1/128 next-hop a:b:c:20::11;
                 route a:b:c:22::a2/128 next-hop a:b:c:21::11;
        }

Got this reply from neighbor (cisco) on exabgp update: 
UPDATE Message Error (3), subcode Malformed Attribute List (1)

exabgp creates update message for these routes as shown

        Update Message (2), length: 119
          Origin (1), length: 1, Flags [T]: IGP
          AS Path (2), length: 0, Flags [T]: empty
          Local Preference (5), length: 4, Flags [T]: 100
          Multi-Protocol Reach NLRI (14), length: 38, Flags [O]: 
            AFI: IPv6 (2), SAFI: Unicast (1)
            nexthop: a:b:c:20::11, nh-length: 16, no SNPA
              a:b:c:22::a1/128
          Multi-Protocol Reach NLRI (14), length: 38, Flags [O]: 
            AFI: IPv6 (2), SAFI: Unicast (1)
            nexthop: a:b:c:21::11, nh-length: 16, no SNPA
              a:b:c:22::a2/128

PS
From bird, for example, update formed this way:

        Update Message (2), length: 78
          Origin (1), length: 1, Flags [T]: IGP
          AS Path (2), length: 0, Flags [T]: empty
          Local Preference (5), length: 4, Flags [T]: 100
          Multi-Protocol Reach NLRI (14), length: 38, Flags [O]: 
            AFI: IPv6 (2), SAFI: Unicast (1)
            nexthop: a:b:c:20::11, nh-length: 16, no SNPA
              a:b:c:22::a1/128
        Update Message (2), length: 78
          Origin (1), length: 1, Flags [T]: IGP
          AS Path (2), length: 0, Flags [T]: empty
          Local Preference (5), length: 4, Flags [T]: 100
          Multi-Protocol Reach NLRI (14), length: 38, Flags [O]: 
            AFI: IPv6 (2), SAFI: Unicast (1)
            nexthop: a:b:c:21::11, nh-length: 16, no SNPA
              a:b:c:22::a2/128

and all is ok.

**Comment by thomas-mangin** [comment]
Sorry for the slow answer, I just only noticed your issue.

Recent master do turn-on group update ( reducing the number of UPDATE message generated ) by default. In your example ExaBGP generate an update with two MPREACH attribute ( the place IPv6 routes are stored into ). It would seems that this is what is causing Cisco to be un-happy.

Two things:
 - what I am doing is illegal as not allowed in the RFC ( which is possible and will check )
 - what I do is a grey area of the RFC but some implementations do not support it
 - what I do is valid and this is not implemented by CISCO ( most unlikely case )

The way to fix the solution immediately is to add "group-updates false" to your neighbor configuration while I investigate and fix the issue. Please use the 3.4 branch for production work as master is currently going through lots of changes.

**Comment by hide** [comment]
according to RFC4271 (section 6.3), do not set multiple MP-REACH NLRIs in the UPDATE message.
>   If any attribute appears more than once in the UPDATE message, then
>   the Error Subcode MUST be set to Malformed Attribute List.

see also error handling draft (https://tools.ietf.org/html/draft-ietf-idr-error-handling-19).
>   g.  If the MP_REACH_NLRI attribute or the MP_UNREACH_NLRI [RFC4760]
>       attribute appears more than once in the UPDATE message, then a
>       NOTIFICATION message MUST be sent with the Error Subcode
>       "Malformed Attribute List".  If any other attribute (whether
>       recognized or unrecognized) appears more than once in an UPDATE
>       message, then all the occurrences of the attribute other than the
>       first one SHALL be discarded and the UPDATE message continue to
>       be processed.

**Comment by thomas-mangin** [comment]
@hide Thank you very much for pointing me to my mistake .. I will update the code to only group IPv4.

**Comment by stroboscope** [comment]
Thank you !

**Comment by thomas-mangin** [comment]
This patch should correct this behaviour ..
https://github.com/Exa-Networks/exabgp/commit/a85245d30347f30f7d8e4fb64ae432f70e3dbf6e

Sigh, this does create lots of CPU waste as the Attributes much be decoded again and again for each NLRI !  But thinking about it, ExaBGP itself probably does not accept such update as the MPR[U]NLRI classes used to decode it are also expecting a single attribute presence.
