### ISSUE TITLE
Flowspec TCP Flags bit-match and exact-match

### ISSUE THREAD

**Issue by hengchai** [Exa-Networks/exabgp#301]
Juniper flowspec parses "tcp-flags syn" as bit-match and "tcp-flags =syn" as an exact-match. Exabgp only does exact match even without = (equals). Please consider allowing for bit matches?

[edit] set routing-options flow route test match tcp-flags syn
\# show route table inetflow.0 
\*,\*,tcp-flag:02/term:1 <== Matches any packet with SYN flag regardless of any other flags

[edit] set routing-options flow route test match tcp-flags =syn
\# show route table inetflow.0 
\*,\*,tcp-flag=02/term:1 <== Matches packets with SYN flag only.

**Comment by thomas-mangin** [comment]
This was already requested (and forgotten about) on the mailing list
https://groups.google.com/forum/#!searchin/exabgp-users/colon/exabgp-users/nCJPndfK3EY/mxygwg5kMqAJ

Thank you @hengchai to have pointed me to it.

**Comment by thomas-mangin** [comment]
"Type 9 - TCP flags" 

         Bitmask values can be encoded as a 1- or 2-byte bitmask.  When 
         a single byte is specified, it matches byte 13 of the TCP 
         header [RFC0793], which contains bits 8 though 15 of the 4th 
         32-bit word.  When a 2-byte encoding is used, it matches bytes 
         12 and 13 of the TCP header with the data offset field having a 
         "don't care" value.

**Comment by thomas-mangin** [comment]
I believe the fix for #314 also fixed this issue.

**Comment by hengchai** [comment]
Yep confirmed the patch fixed this and now "syn" is a bit match, "=syn" is exact match.

**Comment by thomas-mangin** [comment]
:+1:
