### ISSUE TITLE
Problems with exabgp.api.file

### ISSUE THREAD

**Issue by pavel-odintsov** [Exa-Networks/exabgp#302]
Hello, Thomas!

I could use Git master again :) Thanks for it!

I'm trying to check this feature: https://plus.google.com/+ThomasMangin/posts/AD8L7vBikWS

But haven't any success with it.

``` bash
env  exabgp.api.file=/tmp/exabgp.cmd exabgp.daemon.user=root exabgp.daemon.daemonize=false exabgp.daemon.pid=/var/run/exabgp.pid exabgp.log.destination=/var/log/exabgp.log sbin/exabgp -d /etc/exabgp_flowspec.conf 
exabgp 28583  reactor       performing reload of exabgp 3.9.0
exabgp 28583  configuration > neighbor         | '127.0.0.1'
exabgp 28583  configuration . router-id        | '1.2.3.4'
exabgp 28583  configuration . local-address    | '127.0.0.1'
exabgp 28583  configuration . local-as         | '1'
exabgp 28583  configuration . peer-as          | '1'
exabgp 28583  configuration . group-updates    | 'false'
exabgp 28583  configuration > family           | 
exabgp 28583  configuration . ipv4             | 'flow'
exabgp 28583  configuration . ipv6             | 'flow'
exabgp 28583  configuration < family           | 
exabgp 28583  configuration < neighbor         | 
exabgp 28583  reactor       new peer: neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 1 peer-as 1 router-id 1.2.3.4 family-allowed in-open
exabgp 28583  configuration loaded new configuration successfully
```

But there are no any socket files in /tmp:

``` bash
ls -la /tmp/|grep exa|wc -l
0
```

And no open handles at all:

``` bash
ls -al /proc/28583/fd
total 0
dr-x------ 2 root root  0 Jul 13 17:34 .
dr-xr-xr-x 9 root root  0 Jul 13 17:28 ..
lrwx------ 1 root root 64 Jul 13 17:34 0 -> /dev/pts/1
lrwx------ 1 root root 64 Jul 13 17:34 1 -> /dev/pts/1
lrwx------ 1 root root 64 Jul 13 17:34 2 -> /dev/pts/1
l-wx------ 1 root root 64 Jul 13 17:34 3 -> /var/log/exabgp.log
lr-x------ 1 root root 64 Jul 13 17:34 8 -> /dev/urandom
```

Example configuration:

``` bash
cat /etc/exabgp_flowspec.conf 
neighbor 127.0.0.1 {
    router-id 1.2.3.4;
    local-address 127.0.0.1;
    local-as 1;
    peer-as 1;
    group-updates false;

    family {
        ipv4 flow;
        ipv6 flow;
    }
}
```

**Comment by thomas-mangin** [comment]
This feature is not completed and now broken on master. I intend to have it fixed for the release.

**Comment by ton31337** [comment]
@thomas-mangin any news about this? Is there any other way to query without CLI connection status (Connected, OpenSent, OpenConfirm, Active)?

**Comment by thomas-mangin** [comment]
@ton31337 This is one of the next things coming up ( the only reason it is not yet being worked on is that I am on summer holidays and that the weather is good :p ) The state machine currently in master ( first attempt ) is wrong but I know how to fix it.

**Comment by ton31337** [comment]
cheers and waiting for fix \o/ ;-)

**Comment by pavel-odintsov** [comment]
Will be fine to get this option :) Because it's very hard do finish good 2 way integration with ExaBGP without internal API :(

**Comment by thomas-mangin** [comment]
@pavel-odintsov - the way you used to do should still work. So what features are you missing ?

**Comment by pavel-odintsov** [comment]
I need some way to query ExaBGP about prefixes and flow spec announces who is being announced now. Because sometimes my toolkit hangs or customer want to restart it and I need learn routes which was announced before.

is there any way to do it now?

**Comment by ton31337** [comment]
@thomas-mangin I'm not sure if it's somehow related, but:
```
~$ /usr/src/exabgp/bin/exabgpcli
ExaBGP 3.9.0 CLI
Traceback (most recent call last):
  File "/usr/src/exabgp/lib/exabgp/application/cli.py", line 263, in <module>
    main()
  File "/usr/src/exabgp/lib/exabgp/application/cli.py", line 259, in main
    ExaBGP('').cmdloop()
  File "/usr/src/exabgp/lib/exabgp/application/cli.py", line 246, in __init__
    Connection.__init__(self,name)
  File "/usr/src/exabgp/lib/exabgp/application/cli.py", line 229, in __init__
    self.read = open(name,'r+')
IOError: [Errno 2] No such file or directory: ''
```
If running like: `env exabgp.api.file=/etc/exabgp/exabgp.cmd ./exabgp /etc/exabgp/exabgp.conf`, no api file is created as this issue states. Will this be solved, right?

**Comment by thomas-mangin** [comment]
Yes, it will be solved when I get to work on it.

**Comment by ton31337** [comment]
Great :)

**Comment by thomas-mangin** [comment]
@pavel-odintsov - you can use the commands "show routes" and "show routes extensive"

**Comment by thomas-mangin** [comment]
@pavel-odintsov : here are all the commands currently supported / known

# grep "@Text" ./lib/exabgp/reactor/api/command/text.py
@Text('shutdown')
@Text('reload')
@Text('restart')
@Text('version')
@Text('teardown')
@Text('show neighbor')
@Text('show neighbors')
@Text('show routes')
@Text('show routes extensive')
@Text('announce watchdog')
@Text('withdraw watchdog')
@Text('flush route')
@Text('announce route')
@Text('withdraw route')
@Text('announce vpls')
@Text('withdraw vpls')
@Text('announce attributes')
@Text('withdraw attributes')
@Text('announce flow')
@Text('withdraw flow')
@Text('announce eor')
@Text('announce route-refresh')
@Text('announce operational')

At some point I will use this function registration to auto-generate some documentation :p

**Comment by pavel-odintsov** [comment]
Looks like "show routes" is what I'm looking for :)

**Comment by pavel-odintsov** [comment]
We need following options from ExaBGP side:
- Announce  some BGP Flow Spec rule
- Withdrawal some BGP Flow Spec rule
- Get full list of announced rules

So we need somehthing more flexible than "pipe" integration because we read and write information from/to ExaBGP.

I have used this code:
```bash
process announce-routes {
    run /usr/bin/socat stdout pipe:/var/run/exabgp.cmd;
    encoder json;
}

neighbor 127.0.0.1 {
    router-id 1.2.3.4;
    local-address 127.0.0.1;
    local-as 1;
    peer-as 1;
    group-updates false;

  family {
        ipv4 flow;
    }
    api {
        processes [ anounce-routes ];
    }
}
```

But I have not ideas how to implement approach where I could read and write data to/from ExaBGP in same time.

Thomas, could you offer some example how I can do this?

**Comment by pavel-odintsov** [comment]
Sorry for bothering you on vacations, it's not very important question :)

**Comment by pyke369** [comment]
2015-08-07 19:36 GMT+03:00 Pavel Odintsov <notifications@github.com>:

> We need following options from ExaBGP side:
>
>    - Announce some BGP Flow Spec rule
>    - Withdrawal some BGP Flow Spec rule
>    - Get full list of announced rules
>
> So we need somehthing more flexible than "pipe" integration because we
> read and write information from/to ExaBGP.
>
> I have used this code:
>
> process announce-routes {
>     run /usr/bin/socat stdout pipe:/var/run/exabgp.cmd;
>     encoder json;
> }
>
> neighbor 127.0.0.1 {
>     router-id 1.2.3.4;
>     local-address 127.0.0.1;
>     local-as 1;
>     peer-as 1;
>     group-updates false;
>
>   family {
>         ipv4 flow;
>     }
>     api {
>         processes [ anounce-routes ];
>     }
> }
>
> But I have not ideas how to implement approach where I could read and
> write data to/from ExaBGP in same time.
>
> Thomas, could you offer some example how I can do this?
>

You can have a look here:
https://github.com/pyke369/exabgp-helpers/blob/master/exasrv/exasrv.py#L221-L226
for an example of an helper program that read announces from exabgp (to
program a Unix system routing table locally)
and also send announces to exabgp (depending on an external service
availability status).

-- 
Pierre-Yves

**Comment by thomas-mangin** [comment]
@pavel-odintsov as @pyke369 indicated what you want to do is already possible. There is also some examples in the qa folder. data can be read on stdin and written on stdout. You should make sure your read are not blocking, or you can use two threads .. up to you, my code using the async way.

**Comment by ton31337** [comment]
@thomas-mangin any news?

**Comment by thomas-mangin** [comment]
For the moment it is possible to do the same thing using the helper process, I will fix and re-add the api file soon but I am currently crawling under work and had little time for dev.

**Comment by ton31337** [comment]
@thomas-mangin by the way, maybe there is another way to just extract/get connection status? I mean I need just to monitor if session is up, down, active, etc?

**Comment by thomas-mangin** [comment]
A few years down the line ...

It is now `exabgp.api.cli` but it is working, no option to change the name as I would like to keep that an 'internal' behaviour and be able to change it without much notice. That said, free free to hack the control.py file and add the option if really really you need.

On master exabgpcli is in bin and does what you need. even updated the wiki.  `./bin/exabgpcli help` for more info 😉
