### ISSUE TITLE
PYTONPATH setting in bin/ scripts sketchy

### ISSUE THREAD

**Issue by he32** [Exa-Networks/exabgp#310]
Hi,

the new scripts (in 3.4.12) in the bin/ directory, healthcheck, exabgpcli and exanetlink
all contain this line:

export PYTHONPATH="$path"/lib:/usr/share/exabgp/lib/3.4.4

This seems ... non-portable (exabgp's bits are not necessarily installed
in that location), uses the wrong version number (this is 3.4.12), and it's
not clear to me what the last part is attempting to do.
Comments?

Regards,
Håvard

**Comment by thomas-mangin** [comment]
Thank you for raising this, now removed - it is not required anymore
https://github.com/Exa-Networks/exabgp/commit/d189aa357ff955ac02fc790d6f46cd45629a834e

**Comment by thomas-mangin** [comment]
For the clarity of doubt, this is not installed and only used when running from the tarball.
