### ISSUE TITLE
invalid keyword "multihop" ?

### ISSUE THREAD

**Issue by irom77** [Exa-Networks/exabgp#311]
How do i setup multihop in exabgp to peer with cisco ?

cisco: 
router bgp ASN2
neighbor 10.73.21.200 ebgp-multihop 255

exabgp:
Thu, 06 Aug 2015 16:51:55 | ERROR    | 27849  | configuration | syntax error in section group
Thu, 06 Aug 2015 16:51:55 | ERROR    | 27849  | configuration | line 4: multihop 10 ;
Thu, 06 Aug 2015 16:51:55 | ERROR    | 27849  | configuration | 
Thu, 06 Aug 2015 16:51:55 | ERROR    | 27849  | configuration | invalid keyword "multihop"
[exabgp@nms01m ~]$ cat conf.ini
group LT {                         
    router-id 10.73.21.200;          
    multihop 10; 
    
    neighbor x.x.x.x {              
        local-address 10.73.21.200;   
        local-as ASN1;             
        peer-as ASN2;             
    }
}

**Comment by thomas-mangin** [comment]
ExaBGP does not enforce any hop restrictions.

You can set a TCP TTL with the ttl option under the neighbor but not multi hop.
