### ISSUE TITLE
healthcheck.py when run as process unable to add loopback IP

### ISSUE THREAD

**Issue by Millnert** [Exa-Networks/exabgp#312]
https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/application/healthcheck.py#L296

Running rpm of 3.4.12 tag on RHEL7; SELinux not the culprit.

My process line:

      process testservice1 {
        run /usr/bin/python -m exabgp healthcheck --cmd "test -f /tmp/testservice1" --ip 10.19.25.253;
      }

When executed from shell, it works as expected and it manages to add the IP.

But when exabgp executes this line, it does not manage to add an IP:

    Aug 10 00:16:16 exabgp-dev-host1 exabgp: Mon, 10 Aug 2015 00:16:16 | WARNING  | 7217   | configuration | Loaded new configuration successfully
    Aug 10 00:16:16 exabgp-dev-host1 exabgp: Mon, 10 Aug 2015 00:16:16 | INFO     | 7217   | processes     | Forked process testservice2
    Aug 10 00:16:16 exabgp-dev-host1 exabgp: Mon, 10 Aug 2015 00:16:16 | INFO     | 7217   | processes     | Forked process testservice1
    Aug 10 00:16:16 exabgp-dev-host1 healthcheck[7220]: Uncatched exception: Command '[u'ip', u'address', u'add', '10.19.25.252', u'dev', u'lo']' returned non-zero exit status 2
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/exabgp/application/healthcheck.py", line 454, in main
        setup_ips(options.ips, options.label)
      File "/usr/lib/python2.7/site-packages/exabgp/application/healthcheck.py", line 273, in setup_ips
        cmd, stdout=fnull, stderr=fnull)
      File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
        raise CalledProcessError(retcode, cmd)
    CalledProcessError: Command '[u'ip', u'address', u'add', '10.19.25.252', u'dev', u'lo']' returned non-zero exit status 2

retcode 2 is for example what one gets when one runs the add command and an IP already exists:

    [root@exabgp-dev-host1 exabgp]# ip a s dev lo | grep 252
    [root@exabgp-dev-host1 exabgp]# ip address add 10.19.25.252 dev lo
    [root@exabgp-dev-host1 exabgp]# echo $?
    0
    [root@exabgp-dev-host1 exabgp]# ip address add 10.19.25.252 dev lo
    RTNETLINK answers: File exists
    [root@exabgp-dev-host1 exabgp]# echo $?
    2

I haven't yet checked what other cases in iproute2 that returns 2 on address add.
also, there should be a text output somewhere from the add command, that one could look into as well I suppose.  It's puzzling.

**Comment by Millnert** [comment]
The error is:

    RTNETLINK answers: Operation not permitted

SELinux in permissive mode. Looking into it further.

**Comment by Millnert** [comment]
OK, exabgp runs as a regular user, which explains why it's not allowed to add an IP address.

**Comment by thomas-mangin** [comment]
@Millnert - sorry for the time I will take to handle this issue - but I am trying to not connect too often during this last week of holidays.

@vincentbernat any idea on how to best handle root permission / capabilities ? Running ExaBGP as root is not ideal if it is only to give the sub-process access to NETLINK. Should we change healthcheck to be safe if chmod'ed +t and have this as the best option ?

**Comment by Millnert** [comment]
@thomas-mangin np, I was just gathering info and storing it here.
In some Linux distros you can give away net capabilities as well, but I'm not sure what is worse or better.

For our deployment I think I'm deferring IP address management outside any specific application to our common host IP address management system, because I want to be certain it has happened before an application's daemons start, since daemons may want to bind to these addresses, etc, etc.

**Comment by thomas-mangin** [comment]
@Millnert the way my business implements it is to have the ip address setup as a /32 on the loopback, configure sysctl to not have the mac address broadcasted on any ethX and ip source verification is disabled. 

Full configuration available here :
http://thomas.mangin.com/data/pdf/SYSADMIN%204%20-%20Mangin%20-%20BGP%20for%20sysadmin.pdf

**Comment by vincentbernat** [comment]
I suppose you mean `+s`. That's not possible for a Python script.

Either set your loopback addresses outside the healthcheck process or run the healthcheck process as root (with sudo for example). We could drop privileges if needed to avoid staying root.

**Comment by vincentbernat** [comment]
I did push a commit for dropping user privileges.

**Comment by thomas-mangin** [comment]
@vincentbernat, yes I meant +s and it is true that you need a C wrapper to do something like it - forgot.

@Millnert, it seems that the only way is to tempt the devil with something like that and that we can not really do anything in the code to help, so I will close the issue. Feel free to re-open if required.
