### ISSUE TITLE
ExtCommunity flowspec format

### ISSUE THREAD

**Issue by dfox-spb** [Exa-Networks/exabgp#313]
Little question: How to encode extended-community in json output (like "extended-community": [ 9225150068611567616 ] }) to a human view ( like "rate-limit 5000" ) or a may be to a source hex ( 8006511C47435000 ) ?

**Comment by thomas-mangin** [comment]
This is not as simple as it first seems as the signification of the community is very AFI/SAFI dependant : ( the same community for an IPv6 unicast route would hold no particular meaning) and this information is (currently) not available when parsing an UPDATE.

I will look into what is required to make the rendering more human friendly.

**Comment by dfox-spb** [comment]
Thank you! 
may be possible add into json original hex? In addition to 'extended-community'?

in debug mode I`m see that parsing working in exabgp 
Fri, 14 Aug 2015 11:55:35 | INFO     | 8377   | parser        | parsing flag c0 type 10 (extended-community) len 08 payload  (19) 8006 0000 0000 0000

Fri, 14 Aug 2015 11:55:35 | INFO     | 8377   | routes        | peer 172.16.111.1 ASN 64999   << UPDATE (1) (72)  attributes origin igp as-path [ 64999 ] extended-community rate-limit 0
Fri, 14 Aug 2015 11:55:35 | INFO     | 8377   | routes        | peer 172.16.111.1 ASN 64999   << UPDATE (1) nlri  (45) flow destination 11.11.11.11/32 protocol =TCP

8006 0000 0000 0000 = rate-limit 0 but I`m dont understand that "9225060886715039744" in json mean, parsing hex much easier :)

**Comment by thomas-mangin** [comment]
I believe I have done it and undone it, but I can not remember why. It is possible that the code in master now displays hex as I allowed non-backwards compatible chance as the next major release will be 4.0.0

**Comment by thomas-mangin** [comment]
I believe I have done it and undone it, but I can not remember why. It is possible that the code in master now displays hex as I allowed non-backwards compatible change as the next major release will be 4.0.0

**Comment by thomas-mangin** [comment]
in master.
