### ISSUE TITLE
Valid commands being read as invalid

### ISSUE THREAD

**Issue by qqTYXn7** [Exa-Networks/exabgp#315]
I'm performing experiments using exabgp that require me to run several instances of exabgp in parallel, each announcing a large amount of routes (over 100,000 each, some up to 540,000).
There's a bug that has been causing me a large amount of trouble, and that is that sometimes exabgp seems to misread commands, causing it to not announce some of the routes.
When it occurs I get warning messages such as these:

```
Fri, 14 Aug 2015 05:05:18 | WARNING  | 47201  | reactor       | Command from process not understood : hop self
Fri, 14 Aug 2015 05:05:19 | WARNING  | 47203  | reactor       | Command from process not understood : 104.138.128.0/17 as-path [ 11164 7843 11426 ] next-hop self
Fri, 14 Aug 2015 05:05:19 | WARNING  | 47198  | reactor       | Command from process not understood : ext-hop self
Fri, 14 Aug 2015 05:05:19 | WARNING  | 47205  | reactor       | Command from process not understood : route 198.246.109.0/24 as-path [ 11537 10490 13611 ] next-hop self
```

The bug seems to occur randomly, but since I'm running multiple instances of exabgp there's a high chance that it occurs in at least one instance.

Here's version information about my setup:
```
$ ./exabgp -v
ExaBGP : 3.4.11
Python : 2.7.10 (default, Jul  4 2015, 08:25:12)  [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]
Uname  : FreeBSD 10.1-RELEASE-p16 #0: Tue Jul 28 12:04:19 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
```

I can't give you my announcement commands files, but they just consist of announce commands.
I highly doubt it's a problem with my commands as the problem doesn't occur 100% of the time when running just a single exabgp instance.

Here is the configuration file for one of my exabgp instances (with the server & router IP addresses removed):
```
group testgroup {
  router-id x.x.x.x;
  local-address x.x.x.x;
  local-as 3356;

  neighbor y.y.y.y {
    peer-as 65002;
    adj-rib-out disable;
  }

  process add-routes {
    run /bin/sh -c 'cat /usr/home/kang/exabgp-3.4.11/sbin/commands.4.53.34.25; echo `date` > /tmp/DONE; sleep 600; expect /usr/home/kang/exabgp-3.4.11/sbin/clearer.expect > /usr/home/kang/exabgp-3.4.11/sbin/expect.out; sleep 10; cat /usr/home/kang/exabgp-3.4.11/sbin/commands.4.53.34.25; echo `date` > /tmp/DONE2; sleep 86400;';
  }
 }
```

**Comment by thomas-mangin** [comment]
Hi @qqTYXn7 Could you please run exabgp with '-d' on the command line and provide me the log around the area you are seeing the problem (at least 10 lines up and down).

**Comment by qqTYXn7** [comment]
Here:
http://pastebin.com/NVHxcUTg

**Comment by thomas-mangin** [comment]
''' 
Fri, 14 Aug 2015 09:50:28 | INFO     | 55487  | processes     | Command from process add-routes : announce route 103.12.192.0/24 as-path [ 3356 9498 58659 ] next-hop self 
Fri, 14 Aug 2015 09:50:28 | INFO     | 55487  | reactor       | Route added to neighbor 198.180.152.3 local-ip 198.180.152.128 local-as 3356 peer-as 65002 router-id 198.180.152.128 family-allowed in-open : 0.0.0.0/0 next-hop 198.180.152.128 as-path [ 3356 ]
Fri, 14 Aug 2015 09:50:28 | INFO     | 55487  | reactor       | Performing dynamic route update
Fri, 14 Aug 2015 09:50:28 | INFO     | 55487  | reactor       | Updated peers dynamic routes successfully
Fri, 14 Aug 2015 09:50:28 | DEBUG    | 55487  | timers        | peer 198.180.152.3 ASN 65002   Receive Timer 177 second(s) left
Fri, 14 Aug 2015 09:50:28 | DEBUG    | 55487  | timers        | peer 198.180.152.3 ASN 65002   Send Timer 57 second(s) left
Fri, 14 Aug 2015 09:50:28 | DEBUG    | 55487  | wire          | session 1 outgoing 198.180.152.128 / 198.180.152.3  SENDING  (109) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 002C 0200 0000 1440 0101 0040 0206 0201 0000 0D1C 4003 04C6 B498 8000
Fri, 14 Aug 2015 09:50:28 | INFO     | 55487  | message       | Peer   198.180.152.3 ASN 65002   >> 1 UPDATE(s)
Fri, 14 Aug 2015 09:50:28 | INFO     | 55487  | processes     | Command from process add-routes :  route 103.12.193.0/24 as-path [ 3356 9498 58659 ] next-hop self 
Fri, 14 Aug 2015 09:50:28 | WARNING  | 55487  | reactor       | Command from process not understood : route 103.12.193.0/24 as-path [ 3356 9498 58659 ] next-hop self
Fri, 14 Aug 2015 09:50:28 | INFO     | 55487  | processes     | Command from process add-routes : announce route 103.12.194.0/24 as-path [ 3356 9498 58659 ] next-hop self 
Fri, 14 Aug 2015 09:50:28 | INFO     | 55487  | processes     | Command from process add-routes : announce route 103.12.195.0/24 as-path [ 3356 9498 58659 ] next-hop self 
'''

It seems the word announce was "lost". So another manifestation of the bug. I will need to build a FreeBSD dev vm as this is not the first time python does not behave exactly identically with Linux when using sync io

**Comment by thomas-mangin** [comment]
Could you please perform a test for me and not use cat but force the file to be displayed line by line with a sync between each line print as it is doomed to be a buffering issue. I would guess that cat send more than our 4k read buffer and that it causes some line truncation/garbage.

I should still look at why this append but it should be trivial to avoid with a 5 line script replacing cat.

**Comment by qqTYXn7** [comment]
I don't quite understand what you mean.
Could you please rephrase that?
You want me to use a different program than cat?

**Comment by thomas-mangin** [comment]
I am currently travelling - so no easy way to help you but yes something like 
```
for line in `cat file`; do
  echo $line
done
```

**Comment by qqTYXn7** [comment]
I used a short perl script instead of cat:
```#!/usr/local/bin/perl
use strict;

while(my $line = <>){
        print $line;
}
```
The problem still happened.

**Comment by thomas-mangin** [comment]
This code still suffers from buffering issue. in the shell script, the data will have been flushed after each echo (or so do I naively believe), this is not the case in perl : http://perl.plover.com/FAQs/Buffering.html

in python you could use:
```
import os
import sys

with open (sys.argv[1],'r') as file:
  for line in file:
    sys.stdout.write(line)
    sys.stdout.flush()
```

**Comment by thomas-mangin** [comment]
To be exact, the perl code would not change how buffering work - it has no issue, it does not change how things would be :wink:

**Comment by qqTYXn7** [comment]
I replaced cat with your python script and that seemed to have fixed it.
Thanks for your help.

**Comment by thomas-mangin** [comment]
This is good news. Now that I am sure of what the issue is, I will look into how/if I can make 'cat' work.

**Comment by vincentbernat** [comment]
I think you will need to allocate a pty to prevent libc doing buffering. Some programs may have their own flags to avoid that (`python -u` for example), some don't.

**Comment by thomas-mangin** [comment]
@vincentbernat ... I do not mind if there is some buffering, ExaBGP should be able to correctly handle truncation of data due to reaching the max size of the read() buffer. But if you have a good pointer for me to read on this I would not mind it :smile:

**Comment by vincentbernat** [comment]
I didn't read the whole bug report, I thought issue was about buffering. Using a PTY to circumvent that is quite easy. Use `pty.openpty()`. Provide the first file descriptor to the subprocess and you can read unbuffered data from the second file descriptor. That's not exactly the same as doing flush after each line since you may read character per character. So, definitely not a solution if the problem is incorrect handling of truncated data.

**Comment by vincentbernat** [comment]
However, note that by default, with libc, you'll get line buffering when connected to a PTY.

**Comment by thomas-mangin** [comment]
After fixing the fix. hopefully cat will be our friend again ..
