### ISSUE TITLE
Filter updates by address-family

### ISSUE THREAD

**Issue by dfox-spb** [Exa-Networks/exabgp#318]
I want to only use "ipv4 flow"/"ipv6 flow" AF and configuring neighbors as

```
family {
ipv4 flow;
}
```

but if neighbor sent me ipv4 updates (FullView for example) it is parsed and sent to my script. Can I`m limit this and receive only configured address family?

from configured neighbor I`m see that NLRI ipv4 unicast support advertised by exabgp

```
 show bgp neighbor x.x.x.x | match adv 
 NLRI advertised by peer: inet-unicast inet-flow 
```

and one more little question:
is it possible to configure max-prefix limit in AF on neighbor?

**Comment by dfox-spb** [comment]
And how about implement max-prefix limit ? It would be a useful feature...

**Comment by thomas-mangin** [comment]
Hello,

I have a dilema on this issue. Initially I was doing what you said, which is to filter ipv4 unicast routes if the capability was not announced. But I am not sure how the RFC should be read and after user feedback I went back to accept IPv4 unicast (as it can be sent without the MP capability announcement).

I will re-look the RFC and see if this is indeed correct and if I can not make my mind ask on the IETF-IDR list.

For max-prefix, sure ! please open another issue but it will not be done soon ( setting expectations )

Thomas

**Comment by dfox-spb** [comment]
Thanks! Will wait :)

**Comment by thomas-mangin** [comment]
Not forgotten - just busy :cry:

**Comment by thomas-mangin** [comment]
You can not force other implementation to send IPv4 Unicast on a session, but ExaBGP will not send any route out if the family is not configured ...
