### ISSUE TITLE
Getting error "attempting to accept connections, socket not ready" when using md5 and setting exabgp 3.4.12 to listen to a port

### ISSUE THREAD

**Issue by racompton** [Exa-Networks/exabgp#321]
I am trying to get exabgp to listen on port 179 for incoming BGP connections.  I can see python listening on the port:
   rcompton@exabgp:/etc/exabgp$ sudo lsof -i -n | grep bgp
   python2.7 18335     root    4u  IPv4  32272      0t0  TCP *:bgp (LISTEN)
   python2.7 18335     root    5u  IPv4  32408      0t0  TCP 96.34.X.X:48444->154.35.X.X:bgp (SYN_SENT)
but I am getting an error that says "attempting to accept connections, socket not ready" in stdout.  In my tcpdump I see SYNs coming in from the other device on port 179 but I don't see any response from my side.
Here's what my config file looks like:
        neighbor 154.35.X.X {
                peer-as XXXX;
                md5 XXXXXXXXX;
                router-id 51.128.X.X;
                local-as XXXX;
                local-address 96.34.X.X;
                router-id 96.34.X.X;
                hold-time 180;
                group-updates;
        }﻿

If I comment out the MD5 configuration, I do not get the "attempting to accept connections, socket not ready" error.

**Comment by thomas-mangin** [comment]
Sorry - somehow I missed this issue - is it still a problem ?

**Comment by racompton** [comment]
No, I�m sorry.  I was able to get this to work.  It was a configuration issue on my side.

**Comment by thomas-mangin** [comment]
No issue - pleased to hear that it was not me :relieved:

**Comment by alexcf** [comment]
@racompton What was the issue with your config? :)
