### ISSUE TITLE
can "show routes" command work?

### ISSUE THREAD

**Issue by liuheyang** [Exa-Networks/exabgp#329]
in my exabgp application, one exabgp connects to 2 vyatta virtual router by IBGP

on the exabgp side, we can "announce/withdraw route" and "show neighbors", 

but  for command  "show routes", only the successful is returned, without any routing entry.

how can i get the routing entry?

**Comment by thomas-mangin** [comment]
will answer as soon as possible.

**Comment by thomas-mangin** [comment]
From memory, I believe that "show routes" is showing the "ADJ-RIB-OUT" and not IN. So if you did not send any routes to the Vyatta, it will not show anything. 

I am due to create a fully featured cli for ExaBGP and it is now overdue. It will happen soon.

**Comment by liuheyang** [comment]
thanks, i am looking forward to the fully featured CLI. 
1) i firstly announce route to vyatta and it is successful, then send the "show routes" command.  announce route is act as "ADJ-RIB-OUT"
2) my topology: Vyatta A ----ebgp----Vyatta B,  exabgp---ibgp---Vyatta A; exabgp---ibgp---Vyatta B
    "neighbor Vyatta A  announce route 100.10.0.0/16 next-hop self community [65001:1]", the route is relayed to Vyatta B and Vyatta B should send it back to exabgp controller, it's   "ADJ-RIB-IN"
  So, there is  "ADJ-RIB-OUT" and  "ADJ-RIB-IN" in exabgp controller, but no route entry output for "show routes" command.

**Comment by xiaopeng163** [comment]
@thomas-mangin Generally, I think `show routes` means the local BGP RIB table, just like cisco router's `show ip bgp`

```
RP/0/0/CPU0:XR5#sh ip bgp
Wed Sep  9 09:43:51.943 UTC
BGP router identifier 5.5.5.5, local AS number 100
BGP generic scan interval 60 secs
BGP table state: Active
Table ID: 0xe0000000   RD version: 56
BGP main routing table version 56
BGP scan interval 60 secs

Status codes: s suppressed, d damped, h history, * valid, > best
              i - internal, r RIB-failure, S stale, N Nexthop-discard
Origin codes: i - IGP, e - EGP, ? - incomplete
   Network            Next Hop            Metric LocPrf Weight Path
*> 1.1.1.1/32         0.0.0.0                  0         32768 i
*>i1.1.1.50/32        192.168.1.100                 100      0 i
* i1.1.1.113/32       192.0.3.1                     100      0 i
*>i1.1.1.123/32       192.168.1.100                 100      0 i
*>i1.1.1.124/32       192.168.1.100                 100      0 i
*>i1.1.1.200/32       192.168.1.100                 100      0 i
*>i1.1.1.250/32       192.168.1.100                 100      0 i
*> 192.168.1.105/32   0.0.0.0                  0         32768 i
*> 192.168.2.105/32   0.0.0.0                  0         32768 i

Processed 9 prefixes, 9 paths
RP/0/0/CPU0:XR5#
```

for the RIB out table, like routes send to neighbor 10.75.44.11
```
RP/0/0/CPU0:XR5#sh bgp advertised neighbor 10.75.44.11 summary 
Wed Sep  9 09:42:27.328 UTC
Network            Next Hop        From            AS Path
1.1.1.1/32         10.124.1.221    Local           i
192.168.1.105/32   10.124.1.221    Local           i
192.168.2.105/32   10.124.1.221    Local           i

Processed 3 prefixes, 3 paths
```

so I suggest we should use different CMD for get RIB IN and RIB OUT.

**Comment by thomas-mangin** [comment]
@xiaopeng163 ExaBGP does not have a RIB ...

**Comment by thomas-mangin** [comment]
@liuheyang I will have a look as soon as I can

**Comment by coxley** [comment]
:+1: for viewing ADJ-RIB-IN for easy route analysis without polling routers

**Comment by thomas-mangin** [comment]
I will add this feature on 4.0 but this will require LOTS of memory so this will need to be an optional feature.

**Comment by thomas-mangin** [comment]
master has `show adj-rib in` and `show adj-rib out` need to tidy the interface to better link it to neighbor but it is there (adj-rib in storing is enabled by default). I will most likely improve the format over time and provide a JSON format when I can find time to code it.
