### ISSUE TITLE
ASN4 issue

### ISSUE THREAD

**Issue by victor-sudakov** [Exa-Networks/exabgp#331]
Exabgp 3.4.12 would not talk to a Cisco 3660 route reflector tearing down the BGP session all the time with the following notification: 'can not decode update message of type "2"'. The packet dump of a failed BGP session is available at ftp://ftp.sibptus.ru/pub/vas/badbgp.cap  (the ExaBGP speaker being at 212.73.124.11).

The error message on the router is
Sep 15 11:06:33.473 TSK: %BGP-5-ADJCHANGE: neighbor 212.73.124.11 Up
Sep 15 11:06:33.637 TSK: %BGP-3-NOTIFICATION: received from neighbor 212.73.124.11 1/0 (header: unknown subcode) 41 bytes 63616E20 6E6F7420 6465636F 64652075 70
gateway#
Sep 15 11:06:33.637 TSK: %BGP-5-ADJCHANGE: neighbor 212.73.124.11 Down BGP Notification received
gateway#

And on the ExaBGP side:

exabgp 14202  network       Connected to peer neighbor 212.73.125.217 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open (out)
exabgp 14202  network       Peer  212.73.125.217 ASN 43859   out loop, peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]
exabgp 14202  network       Connected to peer neighbor 212.73.125.217 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open (out)
exabgp 14202  network       Peer  212.73.125.217 ASN 43859   out loop, peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]

**Comment by thomas-mangin** [comment]
Current traveling, should be able to look into it later today.

**Comment by victor-sudakov** [comment]
How do I attach the debug output here ? it says ZIP file type is not supported.

**Comment by victor-sudakov** [comment]
Oh well, put it to ftp://ftp.sibptus.ru/pub/vas/exabgp.log.zip

**Comment by thomas-mangin** [comment]
Thank you - downloaded

**Comment by victor-sudakov** [comment]
Is the problem not around the "type object 'AS4Path' has no attribute '_AS4Path__new_aspaths'" issue? The IOS on the route reflector is a rather old 12.2(46a)

**Comment by thomas-mangin** [comment]
Can replicate :
```
./sbin/exabgp ./qa/conf/simple-v4.conf --decode "FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 005E 02 0000 003B 4001 0100 4002 0802 0321 3E86 AF5B A040 0304 D5B7 6FE1 8004 0400 0000 0040 0504 0000 0064 800A 0400 0000 C880 0904 D449 7DDB E011 0602 0100 0311 1616 D53B 8818 D53B 8A18 D53B 8B"
```

**Comment by thomas-mangin** [comment]
Turning off ASN4 will hide the bug until I can code a fix.

**Comment by victor-sudakov** [comment]
Turning off where? This Cisco router does not support them.

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/blob/3.4/qa/conf/no-asn4.conf

```
capability {
		asn4 disable;
}
```

**Comment by victor-sudakov** [comment]
Put this into neighbor context:

       neighbor 212.73.125.217 {
                description "gateway.sibptus.ru";
                capability {
                        asn4 disable;
                        }
                }

Did not help.

**Comment by thomas-mangin** [comment]
Can you please send me the log with the new configuration - so I can look into it later on please.

**Comment by victor-sudakov** [comment]
Put new log to  ftp://ftp.sibptus.ru/pub/vas/exabgp.log2.zip 

The error message on the router remained the same:
Sep 15 15:44:33.004 TSK: %BGP-5-ADJCHANGE: neighbor 212.73.124.11 Up
Sep 15 15:44:33.368 TSK: %BGP-3-NOTIFICATION: received from neighbor 212.73.124.11 1/0 (header: unknown subcode) 41 bytes 63616E20 6E6F7420 6465636F 64652075 70
gateway#
Sep 15 15:44:33.368 TSK: %BGP-5-ADJCHANGE: neighbor 212.73.124.11 Down BGP Notification received
gateway#

**Comment by victor-sudakov** [comment]
I don't understand why it's resetting the peer now:

exabgp 39896  network       Connected to peer neighbor 212.73.125.217 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open (out)
exabgp 39896  network       Peer  212.73.125.217 ASN 43859   out loop, peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]
exabgp 39896  network       Connected to peer neighbor 212.73.125.217 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open (out)
exabgp 39896  network       Peer  212.73.125.217 ASN 43859   out loop, peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]
exabgp 39896  network       Connected to peer neighbor 212.73.125.217 local-ip 212.73.124.11 local-as 43859 peer-as 43859 router-id 212.73.124.11 family-allowed in-open (out)
exabgp 39896  network       Peer  212.73.125.217 ASN 43859   out loop, peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]

**Comment by thomas-mangin** [comment]
Short version : exabgp is buggy, noticing the problem and tearing down the session (to not affect other peers).

**Comment by victor-sudakov** [comment]
I thought disabling asn4 would have been a workaround, that's why I was surprised.

**Comment by thomas-mangin** [comment]
I thought it too but until I can really look into it, it was guest work .. sorry, it did not work :cry:

**Comment by victor-sudakov** [comment]
Thank you in advance.

**Comment by thomas-mangin** [comment]
I just pushed a patch both in the 3.4 and master branch. I hope this fixes the issue.

**Comment by thomas-mangin** [comment]
```
type object 'AS4Path' has no attribute '_AS4Path__new_aspaths'
```

The class AS4Path4 inherit from ASPath but could not use the function __new_aspaths as it was set as private.

**Comment by victor-sudakov** [comment]
Excuse me, what's the git command to obtain the patch for 3.4.12, before the patched version makes it into the FreeBSD ports?

I am a svn and hg guy, git perplexes me.

**Comment by victor-sudakov** [comment]
Ah, 
git diff 4499fd23c3f6eaee941c94bf6339524e4c36cac7 8ff7dc071bce2dd4524ad484d84117ced9e876bc

makes it. Thank you!

**Comment by thomas-mangin** [comment]
@victor-sudakov - Can I close this issue please ?

**Comment by victor-sudakov** [comment]
Thank you, let's close it.
