### ISSUE TITLE
ttl-security issues or I am confused

### ISSUE THREAD

**Issue by borjam** [Exa-Networks/exabgp#335]
I am trying to use the ttl-security option and at least on FreeBSD it doesn't work.

I found a couple of issues:

First, in reactor/network/tcp.py, the call to io.setsockopt passes a hardcoded value for TTL, 20, rather than getting the ttl parameter. The correct line would be:
        io.setsockopt(socket.IPPROTO_IP, socket.IP_TTL, ttl)

Second, in reactor/outgoing.py I see that you call the TTL function from Outgoing.establish(). I understand that this function would be called, if used at all, after a connect() has been done. I am not sure if you can do a setsockopt() to change the TTL after the connection has been established, but at least it wasn´t working for me. 

I have added the call to TTL(self.io, peer, ttl) after the call to MD5() (before bind() and connect()) and now it works as it should. I've verified that my packets indeed have the right TTL value.

All that said, there are two different usages for the TTL in a BGP session. You can set it to a low value (which routers use to do as a default unless you specify a "multi-hop" session) or you can force packets to have a ttl of 255 and specify a *minimum TTL* of 255 so that the connection will drop packets with a TTL less than 255. In that case, however, the maximum allowed value for ttl-security should be 255, not 254.

And in order to be valid for both purposes, ttl-security should set *both* the connection TTL and the minimum TTL. Although I am checking and a setsockopt with IP_MINTTL doesn't work, it's not used by Python 2.7 despite being defined on FreeBSD. Maybe this is an OS dependent feature?

The TTL of 255 has an interesting property: it should avoid the resource consumption caused by a bombardment of TCP packets to a BGP listener using a MD5 key. Packets from a remote network would indeed have a TTL of less than 255 and they should be discarded before trying to verify the MD5 signature.

**Comment by borjam** [comment]
I've done some tests with Juniper, Mikrotik and Ubiquiti.

A Juniper configured as passive with the default TTL of 1 sends the SYN+ACK packet with a TTL of 255 and it switches to TTL 1 after it receives the first BGP OPEN message from the peer.

Mikrotik and Ubiquiti are more interesting. Both run Linux kernels. Whatever value I specify for the TTL, when configured as passive peers, both send the SYN+ACK packet with a TTL of 64 which seems to be hardcoded. After the three way handshake has been completed they switch to the configured TTL.

If I enable the MINTTL with a hack (as the IP_MINTTL constant is not defined in Python 2.7 I have put the value manually) ExaBGP can't complete the connection to Mikrotik or Ubiquiti (their SYN+ACK packet is discarded) but it should work with JunOS, I will try later today.

**Comment by thomas-mangin** [comment]
@borjam - sorry - catching up with ExaBGP issues today !

Thank you very much for reporting this problem. The hardcoding was clearly an oversight ... sigh !

Could I ask you to provide me with your changes in a PR please ?

Also documenting this behaviour in the wiki ( just copying the information in this issue ) would also be a great help for other users.

**Comment by borjam** [comment]
Oh my god, I am demanding my money back!!

Sure. I will send something more formal. Regarding the ttl-security mechanism I think there is some kind of confusion that merits some discussion.

In order to avoid confusion, I think it would be better to have *two* different parameters. 

First: "ttl", which would specify the classical ttl approach. You just specify the TTL for your outgoing packets.

Second: "ttl-threshold" or just "minimum-ttl" would affect the incoming packets instead. At least on FreeBSD there's a setsockopt() option (IP_MINTTL). I don't think it's available on Linux (it isn't on Mac OS X) but it would be a nice addition anyway. A similar funcionality can be obtained by using some internal firewall facility, of course.

But as far as I know, "ttl-security" is used by Cisco for the second case, to specify a threshold, which could be somewhat surprising for Cisco people.

**Comment by borjam** [comment]
For the Wiki explanation we can maybe wait until a decision is made regarding the two possible options?

**Comment by borjam** [comment]
I forgot, for now I've just fixed the TTL issue for the outgoing sessions. Working on the incoming sessions now.

(It should set the configured ttl for the neighbor after the accept() )

**Comment by thomas-mangin** [comment]
@borjam I would be happy to take on any improvement you do see fit. Thank you for your help.

**Comment by thomas-mangin** [comment]
Mission accomplished
https://github.com/Exa-Networks/exabgp/commit/a004cc2609e08cba753a4319fd194f30fa1097ee
