### ISSUE TITLE
Exabgp - Port Expression

### ISSUE THREAD

**Issue by giprohost** [Exa-Networks/exabgp#338]
I read the exabgp man pages where destination-port <port-number-expression> , and packet-length <packet-length-express> - is there documentation on what expression this takes?

**Comment by pavel-odintsov** [comment]
You could find multiple examples here https://github.com/FastVPSEestiOu/fastnetmon/blob/master/src/fastnetmon_tests.cpp or in ExaBGP source code.

**Comment by thomas-mangin** [comment]
This is not documented ( but should ). You can find many example in the ```./qa/conf folder```, please look at the ```flow*``` files.

The parsing engine is generic so all the data are parsed the same way. So if you look any test for port range validation, you can apply the same syntax to packet-length.

The "comment" for the class in master is :
```
class ParseFlowMatch (Section):
	definition = [
		'source 10.0.0.0/24',
		'source ::1/128/0',
		'destination 10.0.1.0/24',
		'port 25',
		'source-port >1024',
		'destination-port [ =80 =3128 >8080&<8088 ]',
		'packet-length [ >200&<300 >400&<500 ]',
		'tcp-flags [ 0x20+0x8+0x1 #name-here ]  # to check',
		'(ipv4 only) protocol [ udp tcp ]',
		'(ipv4 only) fragment [ not-a-fragment dont-fragment is-fragment first-fragment last-fragment ]',
		'(ipv6 only) next-header [ udp tcp ]',
		'(ipv6 only) flow-label >100&<2000',
		'(ipv6 only) icmp-type 35  # to check',
		'(ipv6 only) icmp-code 55  # to check',
	]
```

A space can be see as a way to ```or``` the tests defined.
So ``` >200&<300 >400&<500``` matches a number between 201 and 299 or 401 and 499.

For numeric operators, you can use ``` = > >= < <= ``` 

(master only - not in the 3.4 branch) 

For binary operators, you can use ``` = ! ``` 

```=``` will force an exact bit match when not using it will force a check for the bit. I have not written any test case for this I was told the code generated by  ```= first-fragment&= dont-fragment``` and ``` first-fragment&dont-fragment ``` is correct and did what the user which reported this issue expected.
I never had to use it so I am unsure of how it matches packets on the wire.

**Comment by thomas-mangin** [comment]
Sorry for the delay in answering - I had a bad flu following too much travelling and missed your question until @pavel-odintsov replied.
