### ISSUE TITLE
Provide a message to backend processes on SIGUSR2

### ISSUE THREAD

**Issue by marc-barry** [Exa-Networks/exabgp#339]
We use `SIGUSR2` to reload configuration and processes. One issue we are having is that it is important  for the child processes to know the BGP session state of the neighbour. For example, when we restart ExaBGP we get the `"state": "connected"` message. So the child processes are aware that the session is up. We also get `"state": "down"` messages to know when it is down. But when using `SIGUSR2` the processes come up with no idea about the state of the BGP session. It is basically unknown until some state change happens on the BGP session. This is because ExaBGP doesn't tell the restarted processes the current state.

Is the above intentional or have you just never had a need to make sure the child process has the current BGP session state? Any ideas on what we could do to determine the state within the restarted child processes?

**Comment by spakka** [comment]
In our use case, we use the state messages to indicate to our RIB processor that a BGP peer session has reset. Our child process is just a message recorder/queuer. If it restarts, we actually *don't* want a new state message, as that would look (to us) like a peer reset in the message stream, when in fact that did not happen.

In contrast to your situation, our ExaBGP child process is effectively stateless - we derive state from the message stream elsewhere.

Maybe the solution could be an optional config flag on the process, to send the latest/current state message on process restart/startup?

**Comment by thomas-mangin** [comment]
The master version of ExaBGP (in heavy dev) does differentiate between messages sent and messages received and can now relay to the working process the routes which are being sent too. This may allow you to do what you want.

**Comment by thomas-mangin** [comment]
@marc-barry what would you like to see from ExaBGP on SIGUSR messages ? a notification it was used ?

**Comment by thomas-mangin** [comment]
The reason we never had this request is that I would expect users with an backend API to not need to use signal.
signals were designed before the API and would allow to change the config and force a reload and update the announcements. This now can be done fully using the API so I always considered both as orthogonal features.

**Comment by thomas-mangin** [comment]
@marc-barry @spakka should I close this issue or is there something you would like done ?

**Comment by spakka** [comment]
For me there is nothing to do here, but if this is added as a new feature, I'd like a flag to be able to turn it off (as it conflicts with my existing assumptions, as I stated above)

**Comment by thomas-mangin** [comment]
I changed the the issue to a feature request wording so I know what to do with it. I will introduce a new message to be passed on SIGUSR2 to the backend process so it known about it. If the session is up, it may also re-send the connected and open message (if configured) so the backend-process can parse any raw data it may have decided to receive.

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/commit/ccb27e55aa198fb23618c6171ae8ffb9f3332a8d

Seems to work with my naive test but more testing would be welcomed.
