### ISSUE TITLE
Feature to request ExaBGP to withdraw routes from Adj-Rib-Out

### ISSUE THREAD

**Issue by joshrain** [Exa-Networks/exabgp#343]
ExaBGP does not have a feature to withdraw all the routes present in the Ajd-RIB-OUT.
request to please add this feature.

**Comment by thomas-mangin** [comment]
Thank you for opening this issue. I will implement this feature before the release of version 4 (i.e.: current master)

**Comment by thomas-mangin** [comment]
Untested but should work `clear adj-rib [in|out]`
5ccab9c2
