### ISSUE TITLE
what is the entrance for the receiving packet process?

### ISSUE THREAD

**Issue by liuheyang** [Exa-Networks/exabgp#346]
we use exabgp as a controller, which connects to routers by ibgp session.
the controller can announce a route entry to routers, but on other side, router will also spread the routing information  to the controller, then how can controller receive and process the message from the  router and where is the entry, thanks!

**Comment by thomas-mangin** [comment]
Please have a look at the examples present in the ./qa/conf folder :
https://github.com/Exa-Networks/exabgp/tree/master/qa/conf

Then if you have some more specific question, feel free to update this issue.

**Comment by liuheyang** [comment]
I have check all examples, but i can't find one, which receive and process packet from router? can you tell me a specific one, thanks!

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/blob/master/qa/conf/api-api.conf
https://github.com/dpiekacz/gixlg/blob/master/exabgp/exabgp.conf

**Comment by liuheyang** [comment]
i try the first example, but it reports error in configuration.py " if self.section('root') is not True" and give the following message, i don't know the reason, thanks
"	Fri, 16 Oct 2015 17:14:47 | INFO     | 57486  | reactor       | performing reload of exabgp 3.9.0
Fri, 16 Oct 2015 17:14:47 | INFO     | 57486  | configuration | > process          | 'expecting-a-keepalive'
Fri, 16 Oct 2015 17:14:47 | INFO     | 57486  | configuration | . run              | './api-api.receive.run'
Fri, 16 Oct 2015 17:14:47 | ERR      | 57486  | configuration | problem with the configuration file, no change done
Fri, 16 Oct 2015 17:14:47 | ERR      | 57486  | configuration | "

**Comment by liuheyang** [comment]
i try the first example, but it reports error in configuration.py " if self.section('root') is not True" and give the following message, i don't know the reason, thanks
"	Fri, 16 Oct 2015 17:14:47 | INFO     | 57486  | reactor       | performing reload of exabgp 3.9.0
Fri, 16 Oct 2015 17:14:47 | INFO     | 57486  | configuration | > process          | 'expecting-a-keepalive'
Fri, 16 Oct 2015 17:14:47 | INFO     | 57486  | configuration | . run              | './api-api.receive.run'
Fri, 16 Oct 2015 17:14:47 | ERR      | 57486  | configuration | problem with the configuration file, no change done
Fri, 16 Oct 2015 17:14:47 | ERR      | 57486  | configuration | "

**Comment by liuheyang** [comment]
the version is 3.9.0, master branch.  if i used  3.4.12, but no example in this version. i am puzzled how to do, thanks for your help

**Comment by thomas-mangin** [comment]
@liuheyang please ask for help on the #irc or gitter channel. I can not support normal use case at the moment ( I do not have the time ). I appreciate that the documentation is more than lacking.
These links may help you:
https://thepacketgeek.com/tag/exabgp/
https://github.com/Exa-Networks/exabgp/wiki/Related-articles

**Comment by thomas-mangin** [comment]
btw - I just fixed an issue in the 3.4 branch which may have been the source of your problem.
once you have clone exabgp, run " git checkout 3.4" to use the 3.4 branch. Make sure to remove all the *.pyc file before changing version otherwise you are going to have issue, so the best is to do this on a clean installation.

**Comment by liuheyang** [comment]
we can't setup the example, so in another way, can you give me the  api for send bgp packet to router and  receive bgp packet from router, we can make development base the APIs, thanks!

**Comment by thomas-mangin** [comment]
All the documentation which exists (the little of it) is on the wiki and the presentation I done. I am sorry, it is not a lot. Best to looks at tools using the API like https://erco.xyz

**Comment by pyke369** [comment]
@liuheyang You may have a look at https://github.com/pyke369/exabgp-helpers/blob/master/exasrv/exasrv.py#L230-L236 (reading announces from ExaBGP) and https://github.com/pyke369/exabgp-helpers/blob/master/exasrv/exasrv.py#L396-L406 (send announces to ExaBGP). The same external script does both within the same running loop.

**Comment by thomas-mangin** [comment]
@pyke369 thank you :+1:

**Comment by liuheyang** [comment]
@pyke369 @thomas-mangin thanks for your great help!

**Comment by thomas-mangin** [comment]
@liuheyang Leaving the issue open should you have any more question - feel free to close it when you are happy.

**Comment by liuheyang** [comment]
@pyke369 @thomas-mangin I'am a python beginner, by the way exabgp use subprocess, how can i share memory between main process and its subprocesses, for example, RIB table, main process, rx subprocess and tx subprocess can write or read RIB table. can i use the Value and Manager as share mem like mulitproccess. i 've done some vertification, but it can work correctly, thanks !

**Comment by thomas-mangin** [comment]
* how can i share memory between main process and its subprocesses

You can't. unless a program use (and is designed to use) mapped memory and ExaBGP does not do it. 
If you want to access data, you are bound to the API with the subprocess.

* can i use the Value and Manager as share mem like mulitproccess. i 've done some vertification, but it can work correctly

I do not understand this statement.

**Comment by liuheyang** [comment]
thank your great help, the issue is solved
