### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by gklinich** [Exa-Networks/exabgp#348]
I'm attempting to use exabgp to test our own internal BGP daemon.  I have an internal exabgp process running that is generating a random set of announcements and withdraws as a "torture" test for our system.   The maximum number of routes announced is 600 but the BGP attributes are constantly changing.  The test goes like this 

a) generate 600 prefixes
b) generate 100 next-hops
c) generate 1000 aspaths
d) generate 1000 community sets

then create an announcement by randomly select from a-d above and announce send it.  One out of 5 (again determined randomly) times send a withdrawal for one of the previously sent prefixes.   I'm doing this about 20-50 times / second.   I realize this is an insane test, but it is meant to be a torture test. 

The problem is that if allow this to run for about an hour the exabgp process ends up consuming about 2G of memory.  If I let it run longer it will eventually consume the entire 16G of memory on our test box.  Does this memory consumption seem reasonable?   Is there something I can do to reduce it?

This is how I'm running exabgp

`nice -n 10 env exabgp.daemon.daemonize=true exabgp.daemon.user=xxx      exabgp.cache.attributes=false exabgp.log.destination=Exabgp/exabgp-192.168.252.110.log  ~/exabgp-3.4.13/sbin/exabgp Exabgp/exabgp-192.168.252.110.conf > Exabgp/exabgp-192.168.252.110.out 2> Exabgp/exabgp-192.168.252.110.err`

**Comment by thomas-mangin** [comment]
I am surprise it uses so much memory .. please try to disable this option:
```
exabgp.cache.attributes      : cache all attributes (configuration and wire) for faster parsing. default (true)
```

**Comment by thomas-mangin** [comment]
oh - sorry, I just noticed you already did - so I need to look more into it. Can you please run the latest 3.4 branch so I can fix the issue there if any and have you to check.

**Comment by thomas-mangin** [comment]
If you run
```
env \
    exabgp.daemon.daemonize=true \
    exabgp.daemon.user=xxx \
    exabgp.cache.attributes=false \
    exabgp.log.destination=Exabgp/exabgp-192.168.252.110.log \
    nice -n 10 \
        ~/exabgp-3.4.13/sbin/exabgp \
            --memory \
            Exabgp/exabgp-192.168.252.110.conf \
> Exabgp/exabgp-192.168.252.110.out \
2> Exabgp/exabgp-192.168.252.110.err
```
and exit with Control^C when the memory is high, it will generate some memory profiling information (a png and text output. Could you please share this with me.

**Comment by gklinich** [comment]
Below is the memory dump after allowing the memory climb to over 1G.  I did not see a png.  I will try again 

memory utilisation

ASN                        1393604
list                       1266180
dict                       507847
SAFI                       253274
AFI                        253264
IPv4                       253260
NextHop                    253258
Change                     253258
Attributes                 253258
MPLS                       253258
ASPath                     253151
Communities                253150
function                   2765
Community                  1957
wrapper_descriptor         1071
tuple                      937
builtin_function_or_method 723
weakref                    615
method_descriptor          447
getset_descriptor          378
None

**Comment by thomas-mangin** [comment]
Thank you, you should get something like 
```
Tue, 27 Oct 2015 20:23:21 | INFO     | 2455   | reactor       | performing shutdown
Tue, 27 Oct 2015 20:23:22 | INFO     | 2455   | processes     | Terminating process announce-routes
memory utilisation

str               14442
function          5784
int               5523
code              3925
builtin-code      2646
tuple             2539
dict              1026
type              828
builtin_function  692
list              541
getset_descriptor 447
module            330
staticmethod      293
set               142
classmethod       131
member_descriptor 111
property          95
weakref           90
long              85
float             80
None


generating memory utilisation graph

Graph written to /var/folders/_q/j5yrh4ns27v95qc9fds_79z00000gn/T/objgraph-fKmlm7.dot (12 nodes)
Graph viewer (xdot) not found, generating a png instead
Image generated as /var/folders/_q/j5yrh4ns27v95qc9fds_79z00000gn/T/objgraph-fKmlm7.png
```

**Comment by thomas-mangin** [comment]
From your data, it seems that you are generating many many more ASN that are live on the internet :wink:

**Comment by thomas-mangin** [comment]
If you update to the latest master version (dev code) I have this patch there for you:
https://github.com/Exa-Networks/exabgp/commit/b13ac57506038be91aa0173158d8b3d171ed4a27
It reduces the memory usage for ASN by de-deplicating memory allocation.
I will do the same with AFI and SAFI ( but I am not sure what the "list" object is without the graph )

**Comment by thomas-mangin** [comment]
I have extended caching to all "Resources" subclasses - this should reduce memory footprint even more

**Comment by thomas-mangin** [comment]
@gklinich if you can not generate the data, could you please share your stress test script - I could use it to check memory usage regression.

**Comment by thomas-mangin** [comment]
As this issue has been dormant, and many memory improvement added I will close it.
