### ISSUE TITLE
bgp update packet is delayed when i send it to outside by exabgp

### ISSUE THREAD

**Issue by liuheyang** [Exa-Networks/exabgp#349]
hi,
   in my testbed, we set up a process P1 to send bgp update packet packet from exabgp controller to switch.
   packet interval is 0.5s, for example packet A--0.5s--Packet B--0.5s---Packet C,  but we capture the three packet on the tx ethernet port, the interval is A--0.9s--Packet B--0.1s---Packet C  or  A--0.1s--Packet B--0.9s---Packet C. what is the problem? 
thanks and expect your help

**Comment by thomas-mangin** [comment]
@liuheyang ExaBGP's reactor is a loop running and sleeping every second. So for sub second precision, you should try to change the `exabgp.reactor.speed` from `1.0` (default) to something like `0.1`.

```
 - exabgp.reactor.speed         : reactor loop time
                                  use only if you understand the code.. default (1.0)
```

**Comment by liuheyang** [comment]
thank you very much. My problem has been solved by your help. i will close the issue
