### ISSUE TITLE
about print output 

### ISSUE THREAD

**Issue by liuheyang** [Exa-Networks/exabgp#350]
hi, in our application, we start up two subproccesses of exabgp, one for send packet and one for receive packet. in our debug,  there is no output when we use print instruction. only can use stderr then flush it. it is not convenient for debug. 
   can the print be opened for debug, thanks for your help

**Comment by thomas-mangin** [comment]
This can be done but I do not have the time atm, to get you through all the steps.
Please look at the example in the ./qa/conf folder the `api-api.conf` example.

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/blob/3.4/qa/conf/api-api.conf
