### ISSUE TITLE
subproccesses will running several times

### ISSUE THREAD

**Issue by liuheyang** [Exa-Networks/exabgp#351]
hi, in my exabgp application, the subproccess will run more than one time, and with the following error message in the exabgp
processes  |Too many respawn for %s (%d) terminating program
reactor       | Problem when sending message(s) to helper program, stopping
   what's the problem, and how can I solved it. thanks and expect your response

**Comment by thomas-mangin** [comment]
Please read the information available at https://github.com/Exa-Networks/exabgp/wiki/Related-articles
The process should never terminate.
