### ISSUE TITLE
route-refresh request from router causes exaBGP throw an exception

### ISSUE THREAD

**Issue by yuriya** [Exa-Networks/exabgp#354]
ExaBGP version : 3.4.13
Python version : 2.7.6 (default, Mar 22 2014, 22:59:56)  [GCC 4.8.2]
System Uname   : #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
System MaxInt  : 9223372036854775807

peer A.B.C.D ASN 200

<type 'exceptions.AttributeError'>
'RouteRefresh' object has no attribute 'messages'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 587, in _run
    for action in self._main(direction):
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 537, in _main
    new_routes.next()
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/protocol.py", line 269, in new_update
    for message in update.messages(self.negotiated):
AttributeError: 'RouteRefresh' object has no attribute 'messages'

**Comment by thomas-mangin** [comment]
This should be fixed.

**Comment by yuriya** [comment]
Thanks a lot!
The exabgp is a wonderful project!
Yuriy.



On Feb 27, 2016, at 20:28, Thomas Mangin <notifications@github.com<mailto:notifications@github.com>> wrote:


This should be fixed.

**Comment by thomas-mangin** [comment]
You are welcome - sorry for the time it took to fix.
