### ISSUE TITLE
timestamps in log

### ISSUE THREAD

**Issue by kartoffelbaer** [Exa-Networks/exabgp#356]
hi,

please add timestamps to logfiles, thanks alot! :)

regards,
kartoffelbaer

**Comment by thomas-mangin** [comment]
will do, will do .. :wink:

**Comment by thomas-mangin** [comment]
Ok - it just took a few month for these few lines.
https://github.com/Exa-Networks/exabgp/commit/4f1c96b72b890cb35155eb54429cdc4c1b640d9e
