### ISSUE TITLE
PYPI.rst missing in exabgp-3.4.13.tar.gz on pipy

### ISSUE THREAD

**Issue by nkts** [Exa-Networks/exabgp#357]
PYPI is missing in exabgp-3.4.13.tar.gz which can be downloaded from pipy mirror:

exabgp-3.4.13 $ python setup.py build
removing left-over egg
Traceback (most recent call last):
  File "setup.py", line 287, in <module>
    description_rst = open('PYPI.rst').read() % {'version': version}
IOError: [Errno 2] No such file or directory: 'PYPI.rst'

**Comment by thomas-mangin** [comment]
Hi,

Thank you, I need to update the setup.py script to include this file it seems.
If you use the tar file on github, all is fine.

```
tar ztvf 3.4.13.tar.gz | grep PYPI
-rw-rw-r--  0 root   root     2522 22 Sep 12:39 exabgp-3.4.13/PYPI.rst
```
