### ISSUE TITLE
Per neighbor option for peer's remote port

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#358]
As requested by @dbarrosop

**Comment by dbarrosop** [comment]
Great! Let me know if you need help with this. Happy to help coding if you don't have the time.

**Comment by thomas-mangin** [comment]
This was really simple so I done it during lunch (and had lunch). Not tested but very likely to not bring any surprises (3.4 only atm - so I am not closing the issue)

https://github.com/Exa-Networks/exabgp/commit/bcf51caef12f0adcea1cdf136d5eea90b066e052

**Comment by dbarrosop** [comment]
Thanks!

**Comment by thomas-mangin** [comment]
forward ported to master
https://github.com/Exa-Networks/exabgp/commit/0cb9a917414c19fffe0d1650591fb40140e2bd91

**Comment by commiespy** [comment]
How do you configure this? I can't find any reference to this parameter in the docs. Thanks.

**Comment by thomas-mangin** [comment]
it is in the patch - connect, and listen keyword under the peer.
