### ISSUE TITLE
How to getting start Exabgp ?

### ISSUE THREAD

**Issue by andy19910403** [Exa-Networks/exabgp#362]
Hi :
recently , I study exabgp article and I install exabgp software,but I have no idea to make first lab
could someone can give me articles or web links?

and I have some question ,hoped somebody can help me.

1. why the command line appear different output when I install exabgp on 2 VMs and i input "exabgp" command?

2. what does the relation both exabgp and quagga?

3. How does the experiment process of exabgp?  
is first write a config script and input "exabgp <config>" in command line 

4. when I execute  "exabgp ebgp4-simple.txt"  the  error messages (Peer        10.0.0.1 ASN 65533   could not bind to local ip 10.0.0.1 - [Errno 99] Cannot assign requested address)

then i modified the neighbor and local-address to this VM itself (10.0.0.2) and execute again.
it appear 
(could not connect to peer (if you use MD5, check your passwords): [Errno 111] Connection refused) error messages.(the VM IP is 10.0.0.2  and I set neighbor and local-address same as 10.0.0.2 ) 
I can not fix it

then I use another VM execute same command it appear
 (Thu, 24 Dec 2015 11:19:38 | INFO     | 2939   | network       | Peer        10.0.0.1 ASN 65533   connection to 10.0.0.1:179 failed) error massages.(the VM IP is 10.0.0.1  and I set neighbor and local-address same as 10.0.0.1 ) 
I was accept TCP port 179 but it doesn't help me anymore

---------------------------The complete messages are following--------------------------------

Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | reactor       | performing reload of exabgp 3.9.0
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | > neighbor         | '10.0.0.1'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . description      | 'a quagga test peer'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . router-id        | '192.168.127.1'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . local-address    | '10.0.0.1'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . local-as         | '65500'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . peer-as          | '65533'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . hold-time        | '180'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | > static           |
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | > route            | '10.0.1.0/24'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . next-hop         | '10.0.255.254'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | < route            |
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | > route            | '10.0.2.0/24'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . next-hop         | '10.0.255.254'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . community        | '30740:30740'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | < route            |
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | > route            | '10.0.3.0/24'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . next-hop         | '10.0.255.254'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . community        | '[' '30740:30740' '30740:0' ']'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | < route            |
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | > route            | '10.0.4.0/24'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . next-hop         | '10.0.255.254'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . local-preference | '200'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | < route            |
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . route            | '10.0.5.0/24' 'next-hop' '10.0.255.254' 'local-preference' '200'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . route            | '10.0.6.0/24' 'next-hop' '10.0.255.254' 'community' '30740:30740'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . route            | '10.0.7.0/24' 'next-hop' '10.0.255.254' 'local-preference' '200' 'community' '30740:30740'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . route            | '10.0.8.0/24' 'next-hop' '10.0.255.254' 'community' '30740:30740' 'local-preference' '200'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . route            | '10.0.7.0/24' 'next-hop' '10.0.255.254' 'local-preference' '200' 'community' '[' '30740:0' '30740:30740' ']'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | . route            | '10.0.8.0/24' 'next-hop' '10.0.255.254' 'community' '[' '30740:0' '30740:30740' ']' 'local-preference' '200'
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | < static           |
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | configuration | < neighbor         |
Thu, 24 Dec 2015 11:27:43 | INFO     | 2948   | reactor       | new peer: neighbor 10.0.0.1 local-ip 10.0.0.1 local-as 65500 peer-as 65533 router-id 192.168.127.1 family-allowed in-open
Thu, 24 Dec 2015 11:27:43 | WARNING  | 2948   | configuration | loaded new configuration successfully
Thu, 24 Dec 2015 11:27:47 | INFO     | 2948   | network       | Peer        10.0.0.1 ASN 65533   connection to 10.0.0.1:179 f
---------------------------The complete messages are following--------------------------------

**Comment by thomas-mangin** [comment]
1- ExaBGP is not a command is it a daemon, it is use to announce route to another BGP speaker
2- quagga is another BGP deamon which can program the host to route packets ( ExaBGP only receive / announce without causing local changes )
3- I can not understand the question
4- ExaBGP's configuration should only reference IP addresses existing on the host

I would advise you to read some online material on IP networking ( IP addressing, static routing, and then dynamic routing ). I will support issue with ExaBGP - bugs, feature requests but I can not help every users with networking.

Good luck - have a festive end of year.
