### ISSUE TITLE
EL 7.2 conflict with python-enum34

### ISSUE THREAD

**Issue by Millnert** [Exa-Networks/exabgp#367]
On a system with exabgp 3.4.13, healthcheck.py conflicts with python-enum34.

    [root@ext-dev-haproxy1 ~]# /usr/bin/python -m exabgp healthcheck --cmd "/etc/exabgp/healthchecks/https_healthcheck.sh api-dev.cloud.ipnett.se 443 /haproxy 185.19.66.177" --ip 185.19.66.177 --interval 30 --no-ip-setup --withdraw-on-down
    ERROR[healthcheck] Uncatched exception: __call__() takes at most 5 arguments (7 given)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/exabgp/application/healthcheck.py", line 466, in main
        loop(options)
      File "/usr/lib/python2.7/site-packages/exabgp/application/healthcheck.py", line 338, in loop
        "DOWN",                 # Service is considered as down.
    TypeError: __call__() takes at most 5 arguments (7 given)

I suppose the fix is on import side.
Other details:

    [root@ext-dev-haproxy1 ~]# yum list installed | grep -E '^python(\.|.*addr|-enum)'
    python.x86_64                    2.7.5-34.el7                @rhel-7-server-rpms
    python-enum34.noarch             1.0.4-1.el7                 @rhel-7-server-rpms
    python-ipaddr.noarch             2.1.9-5.el7                 @rhel-7-server-rpms
    python-netaddr.noarch            0.7.5-7.el7                 @rhel-7-server-rpms

This is fixed in master. But there's no stable release with the fix yet. Any plans on that?

We generally prefer to try to reduce amount of projects that we build nightly in CI. And in the case of exabgp I'm not sure what the status is on 4.0/master anyway.
Anyway, the history is lost on https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/application/healthcheck.py , but this part of the code does appear fixed in master

**Comment by vincentbernat** [comment]
In fact, I "fixed" this in master by accident. pylint was complaining about the function with a capital letter. So, I just used the same version for Python 2.7 and Python 3.x. It seems that the code never was compatible with Python3.4+ enum library. I'll push a fix shortly.

**Comment by thomas-mangin** [comment]
@vincentbernat Thank you very much for the very quick fix. To fix this, I will release a new 3.4 version later this week.

**Comment by Millnert** [comment]
"A++++++++ will try again"

Thanks!
