### ISSUE TITLE
allow exabgp to start without any neighbours

### ISSUE THREAD

**Issue by fobser** [Exa-Networks/exabgp#372]
It would simplify our orchestration if we could start a fixed amount of instances on a host without any neighbours configured.
Over time neighbours would be added and exabgp instructed to reload its configuration.
Currently exabgp just exits.
Thanks,
Florian

**Comment by thomas-mangin** [comment]
Oh - yes - I want this feature too .. Do you have a deadline by which you need this feature ?

**Comment by fobser** [comment]
On 05/02/16 17:17, Thomas Mangin wrote:
> Oh - yes - I want this feature too .. Do you have a deadline by which you need this feature ?
Not really, no. When it's ready ;)

**Comment by thomas-mangin** [comment]
Let's look the calendar for 2020 then ... :tongue: I will try to find some time for ExaBGP in the next weeks.

**Comment by thomas-mangin** [comment]
I had a thought on how to best do this. I am planning to add a way to tag a peer as a template and then give an API command to clone it and one to remove a clone. I will try to implement this once I have fixed all reported bugs.

**Comment by doddt** [comment]
I would also like to have this functionality... somewhat sooner than 2020. :-)

**Comment by thomas-mangin** [comment]
I am enjoying some holidays. I will ask you more questions in a few days to make sure I get what you need right.

**Comment by doddt** [comment]
Basically, I want exabgp to run even if there are no peers in the .conf currently. When I add some peers I'll signal him to reload. Other than not having any peering sessions, exabgp should behave normally. If queried for neighbors or routes, exabgp should indicate that there aren't any. LMK if you have more questions. Thanks!

**Comment by thomas-mangin** [comment]
Need to be forward ported to master

**Comment by thomas-mangin** [comment]
or not .. as it seems to already do it.
