### ISSUE TITLE
Support for DDoS-Alert Extensions

### ISSUE THREAD

**Issue by dpiekacz** [Exa-Networks/exabgp#373]
Extensions to BGP-4 to enable the exchange of information about detected malicious traffic (e.g., Distributed Denial of Service Attacks) and provide options for coordinated, collaborative responses to mitigate such traffic.  The extensions are backward compatible - a BGP speaker that supports the extensions can interoperate with speakers that do not support the extensions.

https://tools.ietf.org/html/draft-green-idr-ddosae-00

**Comment by pavel-odintsov** [comment]
Nice idea! But who from vendor side will support it?

**Comment by thomas-mangin** [comment]
Adding to #200 and will implement if I see any vendor support.
