### ISSUE TITLE
Runtime Error when using JSON encoding

### ISSUE THREAD

**Issue by lisroach** [Exa-Networks/exabgp#376]
I just attempted to add encoder json to my configuration file, and exa dumped the following error (with the -d flag enabled):

```
ExaBGP version : 3.4.12
Python version : 2.7.10 (default, Oct 14 2015, 16:09:02)  [GCC 5.2.1 20151010]
System Uname   : #1 SMP Mon Dec 7 11:52:55 PST 2015
System MaxInt  : 9223372036854775807


peer 10.25.0.32 ASN 65000

<type 'exceptions.RuntimeError'>
no update.nlri: <class 'exabgp.bgp.message.update.Update'> ['CODE', 'EOR', 'HEAnpack_message']r_message', 'registered_message', 'split', 'string', 'unpack', 'un
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 587, in _run
    for action in self._main(direction):
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 456, in _main
    for message in proto.read_message():
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/protocol.py", line 168, in read_message
    self.peer.reactor.processes.message(msg_id,self.peer,message,'','')
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 273, in closure
    return function(self,*args)
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 309, in message
    self._dispatch[message_id](self,peer,message,header,*body)
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 317, in wrap
    function(*args)
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 336, in _update
    self.write(process,self._encoder[process].update(peer,update,header,body),peer)
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/api/encoding.py", line 338, in update
    'message': '{ %s}' % self._update(update)})),header,body,peer.neighbor.identificator(),self.count(peer),message_type='update')
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/api/encoding.py", line 322, in _update
    raise RuntimeError('no update.nlri: %s %s' % (type(update),dir(update)))
RuntimeError: no update.nlri: <class 'exabgp.bgp.message.update.Update'> ['CODE, 'unpack', 'unpack_message']r_message', 'registered_message', 'split', 'string',

```

My config file:
```
 router-id 10.25.0.6;

        static {
                #ERCO CONTROLLED PART
                #END OF ERCO CONTROLLED PART
        }

         process monitor-neighbors {
                encoder json;
                receive {
                        parsed;
                        updates;
                        neighbor-changes;
                }
                run /usr/bin/python /home/cisco/exabgp/routes.py;
        }

        neighbor 10.25.0.32 {
                local-address 10.25.0.6;
                local-as 65000;
                peer-as 65000;
        }

```
I am running in an Ubuntu 15.10 LXC that is communicating with a BGP daemon on another server. Everything worked until I added the encoder json line to the file. Let me know what else I can tell you to help, or if I just made an obvious mistake ;)

**Comment by thomas-mangin** [comment]
Thank you for the bug report Lisa. Sorry this bug :disappointed: 

Can I ask you two things as I do not have enough information to help you with this issue yet.
 - run the latest version of the 3.4 branch
 - and if the bug is still there provide more of the debug (do not just cut the trace but a least a few 10s of the lines before)

To get the lastest 3.4
> git@github.com:Exa-Networks/exabgp.git
> cd exabgp
> git checkout 3.4

**Comment by thomas-mangin** [comment]
```
        static {
                #ERCO CONTROLLED PART
                #END OF ERCO CONTROLLED PART
        }
```
Also the static section is exactly like on cisco where statically configured routes are setup to be announced. So this is not at all an ERCO controlled section.

**Comment by lisroach** [comment]
Hey Thomas,

Thanks for the reply! I upgraded my version and the issue completely went away! Guess I should've tried that first, d'oh!

Thanks for the comment about the Erco section, my colleague has been working on getting it up and running and I know it has been a bit challenging. I will forward your feedback on to him.

Thank you,
Lisa

**Comment by thomas-mangin** [comment]
Good to hear. Please feel free to open a new issue or ask on G+ or Gitter if you have any more questions

**Comment by thomas-mangin** [comment]
Hi Lisa,

Sorry ExaBGP's documentation is ... well, what it is .. My advise would be 'read the source' if you need but reading the examples in the qa/conf may help even more. You know where to find me if you need more help.

Sincerely yours (as we are formal it seems :p)

Thomas

**Comment by lisroach** [comment]
Haha sorry for the formality! I am in work-mode right now, hard to break out of. I'll definitely be reaching out, probably G+, as I do have a couple more questions...

Warm Regards,
Lisa

**Comment by thomas-mangin** [comment]
Good luck with your project. I assume you are working with Bertrand .. Let me know if I can be of any help.
