### ISSUE TITLE
JSON parsed output gives wrong exaBGP version

### ISSUE THREAD

**Issue by lisroach** [Exa-Networks/exabgp#377]
Just a cosmetic error, when I get my output encoded as JSON, it always says my exaBGP version is 3.4.8. My version now is actually 3.4.13, so I'm pretty sure this is a bug, or else I messed up something real bad and I'm secretly running version 3.4.8.

Here is the beginning of my JSON output:

```
{
 "exabgp": "3.4.8",
  "time": 1455834643,
  "host": "LXC_NAME",
  "pid": "15660",
  "ppid": "1",
  "counter": 1,
```

Thanks!

**Comment by thomas-mangin** [comment]
Well spotted :wink: but this is not an error - it is the version at which the JSON format was last modified. So if you update you can make sure that your code will not bomb out due to a format change.

**Comment by lisroach** [comment]
Gotcha, makes sense, thank you!

[cid:image001.png@01D16AF9.708E4CF0][Image - Check URL if not visible]

Lisa Roach
SOFTWARE SYSTEMS ENGINEER.US SALES
lisroach@cisco.com
Phone: +1 408 424 1270

Cisco Systems Limited

US
Cisco.com<http://www.cisco.com/>





[Think before you print.]Think before you print.

This email may contain confidential and privileged material for the sole use of the intended recipient. Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender by reply email and delete all copies of this message.
For corporate legal information go to:
http://www.cisco.com/web/about/doing_business/legal/cri/index.html
