### ISSUE TITLE
output: add the parsed extended community

### ISSUE THREAD

**Issue by nskalis** [Exa-Networks/exabgp#378]
Hi Thomas,

Could you please add the **parsed** bgp extended community (instead of the decimal value)
in the output of the exabgp process ? possibly in v4.0 ?
many thanks.

Nikos

**Comment by thomas-mangin** [comment]
I will \_add\_ it to the list before the release of 4.0

**Comment by pavel-odintsov** [comment]
I have some time and could check all extended community encodings relates with flow spec  :)

**Comment by thomas-mangin** [comment]
Time being something we are normally all short on - I will gladly take your offer. Making sure we do have some testing generated at the end of it to prevent regression would also be great (if you can).
Do you look at the qa/conf folder and how qa/bin/conversation works to add some more test there ?

**Comment by pavel-odintsov** [comment]
So I have pretty.... (ugly?) test environment. I have GoBGP compiled as linux dynamic library. I call it and prepare glow spec messages. Then I feed they to ExaBGP's decode command and compare output.

Also I have custom flow spec implementation in C++ and use it when sometimes going wrong ;)

**Comment by thomas-mangin** [comment]
Congratulation - that's a pass - you can keep this lab in your home folder :stuck_out_tongue_winking_eye:

**Comment by pavel-odintsov** [comment]
Haha :)

**Comment by rtrcwby** [comment]
Bumping to follow.  This is exactly what I'm trying to do!  Thanks!

**Comment by thomas-mangin** [comment]
This update https://github.com/Exa-Networks/exabgp/commit/4badd3427338e5b8b0ebd6abd1e4df56f81ee9ec  change the extended-community to return both the value and decoded string when possible.
@tmmorin 
I also slightly changed the output of the class with https://github.com/Exa-Networks/exabgp/commit/fbba99b1370e1c0ff4229dfefa9fcf0eb4fa60d7 can you please confirm bagpipe will not suffer from it ...

**Comment by thomas-mangin** [comment]
with no complain from @tmmorin - I am closing the issue - I am sure Thomas knows how to re-open it if I caught it during some yearly vacation or conference ...
