### ISSUE TITLE
self configuring neighbors

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#38]
_From [thomas.mangin](https://code.google.com/u/thomas.mangin/) on July 25, 2013 09:14:42_

It would be practical when accepting many connections from many peers from a trusted range to not have to specify the details of the connection.

A BGP speaker receiving a connection can extract from the OPEN message sent from the peer all the information it needs to reply. Only the router-id need to be configured locally to prevent collision.

Practically it could look like :

neighbor 4.3.2.1 {
  reflection;
  router-id 10.20.30.40;
}

_Original issue: http://code.google.com/p/exabgp/issues/detail?id=38_

**Comment by plajjan** [comment]
You could potentially derive router-id from your own IP address if you really want to minimise the configuration as much as possible ;)

**Comment by thomas-mangin** [comment]
@plajjan yes, the example is not good. And indeed it can be take from TCP.

**Comment by thomas-mangin** [comment]
done on master
