### ISSUE TITLE
BGP connection resets on a route refresh

### ISSUE THREAD

**Issue by bryanschwerer** [Exa-Networks/exabgp#380]
Using two instances of ExaBGP 3.4.13 to exchanged mpls-vpn routes.  When issuing the command "announce  route-refresh ipv4 mpls-vpn" to refresh routes, we see ExaBGP reset the connections to the BGP peer and re-establish the peer, which in turn, does refresh the routes.

A typical conf.ini would look like this for us

```
group test {  
# Define peer
    neighbor 192.168.107.26 {  
        local-address 10.11.13.50;
        local-as 65002; 
        peer-as 65001;  
	group-updates;
        family {
            ipv4 mpls-vpn;
        }

        process exa-shim {
           encoder json;
           receive {
              parsed;
              updates;
              neighbor-changes;
           }
           run /usr/bin/python /home/exabgp/http_api2.py;
        }
    }
}
```

I see this output from the far end.

`{ "exabgp": "3.4.8", "time": 1456407362, "host" : "192-168-156-70", "pid" : "18057", "ppid" : "5770", "counter": 10, "type": "state", "neighbor": { "ip": "10.11.13.119", "address": { "local": "192.168.156.70", "peer": "10.11.13.119"}, "asn": { "local": "65000", "peer": "65001"}, "state": "down", "reason": "in loop, peer reset, message [] error[]"} }
`

I've tried changing the family to ipv4 unicast and see the same thing.  In my limited time that they let me run against a Juniper, I don't see this.

**Comment by bryanschwerer** [comment]
This is the log output when it gets a refresh

```
ExaBGP version : 3.4.13
Python version : 2.7.5 (default, Jun 17 2014, 18:11:42)  [GCC 4.8.2 20140120 (Red Hat 4.8.2-16)]
System Uname   : #1 SMP Tue Oct 20 10:21:38 EDT 2015
System MaxInt  : 9223372036854775807


peer 10.11.13.119 ASN 65001   

<type 'exceptions.AttributeError'>
'RouteRefresh' object has no attribute 'messages'
Traceback (most recent call last):
  File "/ovn/exabgp/lib/exabgp/reactor/peer.py", line 587, in _run
    for action in self._main(direction):
  File "/ovn/exabgp/lib/exabgp/reactor/peer.py", line 537, in _main
    new_routes.next()
  File "/ovn/exabgp/lib/exabgp/reactor/protocol.py", line 269, in new_update
    for message in update.messages(self.negotiated):
AttributeError: 'RouteRefresh' object has no attribute 'messages'

********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************
```

**Comment by thomas-mangin** [comment]
Thank you for this report. This is not tested by the functional testing but I was able to reproduce easily and therefore fix by doing.

First shell
```
> cd qa/self/refresh
> ./first
```
Second shell
```
> cd qa/self/refresh
> ./second
```

Hopefully this fix this mistake. Sorry for the bug.

**Comment by thomas-mangin** [comment]
This issue is now fixed in the 3.4 branch - feel free to re-open if there was still an issue.

**Comment by bryanschwerer** [comment]
Thomas,

Works great after I momentarily stopped being an idiot.

Thanks,

Bryan

**Comment by thomas-mangin** [comment]
Thank you for letting me know :+1:
