### ISSUE TITLE
add support for 6PE [RFC4798]

### ISSUE THREAD

**Issue by nskalis** [Exa-Networks/exabgp#382]
hi Thomas,

if you could provide support for `labeled unicast` address family, 
advertising IPv6 prefixes over IPv4 MPLS,
that would be great !

more specifically: AFI=2, SAFI=4, labeled IPv6 (6PE)
```
https://tools.ietf.org/html/rfc4798
```

corresponding JUNOS configlet:
```
family inet6 {
    labeled-unicast {
        explicit-null;
    }
}
```

**Comment by nskalis** [comment]
Correction: *RFC3107* and is supported in ExaBGP with the **nlri-mpls** configuration :)
Please feel free to close this issue.

**Comment by thomas-mangin** [comment]
Just took me to know that it was also called 6PE :smile:
