### ISSUE TITLE
Bogus BGP state message declares the neighbor connection is down.

### ISSUE THREAD

**Issue by bryanschwerer** [Exa-Networks/exabgp#383]
Occasionally, I see a "down" state message come out well after the BGP connection to the peer is established.  I can still announce routes via the peer, so I know the BGP state is actually up.  Here are the JSON messages.

```
{ "exabgp": "3.4.8", "time": 1457031781, "host" : "10-64-156-70", "pid" : "32263", "ppid" : "9126", "counter": 5, "type": "state", "neighbor": { "ip": "10.11.13.119", "address": { "local": "10.64.156.70", "peer": "10.11.13.119"}, "asn": { "local": "65000", "peer": "65001"}, "state": "connected"} }

{ "exabgp": "3.4.8", "time": 1457031783, "host" : "10-64-156-70", "pid" : "32263", "ppid" : "9126", "counter": 6, "type": "state", "neighbor": { "ip": "10.11.13.119", "address": { "local": "10.64.156.70", "peer": "10.11.13.119"}, "asn": { "local": "65000", "peer": "65001"}, "state": "up"} }

{ "exabgp": "3.4.8", "time": 1457031859, "host" : "10-64-156-70", "pid" : "32263", "ppid" : "9126", "counter": 8, "type": "state", "neighbor": { "ip": "10.11.13.119", "address": { "local": "10.64.156.70", "peer": "10.11.13.119"}, "asn": { "local": "65000", "peer": "65001"}, "state": "down", "reason": "connection to peer failed"} }
```

As you can see, the message at least 60 seconds after the connection has been negotiated and it doesn't try to re-establish it.  It doesn't happen every time and I don't have the exact sequence of events that duplicate it.  It happens after killing and restarting the peer, which in this case is also exabgp.  No interesting message is the log.

I am using these messages to track the BGP state, so this ends up with a sticky false "down" state when BGP is actually "up".  Is there some other way to poll the BGP state as a workaround?

Config

```
group  BGPVPN {
    process exa-shim {
      encoder json;
      receive {
        parsed;
        updates;
        neighbor-changes;
      }
      run /ovn/grpcEnv/bin/python  /ovn/python/exabgp_shim/ExaBGP_server.py ;
    }
  neighbor 10.11.13.119 {
    local-address 10.64.156.70;
    local-as 65000;
    peer-as 65001;
    group-updates;

    capability {
      route-refresh;
      graceful-restart 2;
    }
    family {
      ipv4 mpls-vpn;
#     ipv4 unicast;
    }
  }
}
```

Start command

`env exabgp.daemon.user=root exabgp.tcp.bind="0.0.0.0"              exabgp.tcp.port=179 exabgp.daemon.pid=/var/run/exabgp.pid           exabgp.log.destination=/var/log/exabgp.log /ovn/exabgp/sbin/exabgp /tmp/ExaBGP.ini`

Thanks,

Bryan Schwerer

**Comment by thomas-mangin** [comment]
I need more time to investigate but I have like the feeling that it is due to the fact that two TCP sessions are alive at the same time ( one incoming and one outgoing ). The peer then tear down one of the two session (as the connection is in state ESTABLISHED in the other) and ExaBGP does not take this in consideration.

**Comment by thomas-mangin** [comment]
Can you please confirm if the latest 3.4 stable branch fixes your issue please ?
https://github.com/Exa-Networks/exabgp/commit/3fdcca4363d5a4d459ca133bce4c25c40140f846

**Comment by thomas-mangin** [comment]
This bugs still exists in master so please do not close the issue, however the FSM code in master is in the middle of the rewrite so it must be completed first before it can be fixed correctly.

**Comment by bryanschwerer** [comment]
>Can you please confirm if the latest 3.4 stable branch fixes your issue please ?

Yes, 3.4

**Comment by thomas-mangin** [comment]
Thanks, this is great - I will read this as "Yes, 3.4 does fix it" ..
