### ISSUE TITLE
ttl_security should allow 255

### ISSUE THREAD

**Issue by causey** [Exa-Networks/exabgp#387]
Hello,

We use a ttl_security value of of 255 in our configuration, which is incompatible with this validation:

https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/configuration/neighbor/parser.py#L85

Can I just update this value to be 256 and submit a PR?
Thanks!

Matt

**Comment by causey** [comment]
Here's the related PR:

https://github.com/Exa-Networks/exabgp/pull/388

**Comment by thomas-mangin** [comment]
Thank you - fixed with another patch - help much appreciated.
