### ISSUE TITLE
How can I show neighbors routes

### ISSUE THREAD

**Issue by andyccccc** [Exa-Networks/exabgp#390]
Hi~
I  used exabgp connection to juniper router,and I have type some static routes  on juniper router.
Now I want to checked those routes  by exabgp, but I don't know how to show neighbors routes.

I know "show routes"  but it can't show neighbors routes.

thanks.
Andy

**Comment by thomas-mangin** [comment]
Yes - show routes, shows SENT routes. There is no command ATM to see the ADJ-RIB-IN as the routes are not stored. You would need a helper process to get the routes and store them for you.

**Comment by andyccccc** [comment]
Thank you.
If I modify the exabgp code , can I resolve the request?

**Comment by thomas-mangin** [comment]
It would be some work but it is possible to do - all the 'framework' code is there already.

**Comment by andyccccc** [comment]
@thomas-mangin thank your help, 
Now,I traced the code and want to find  the code of bgp packet for reception. 
can you tell me where is the filename

(I think to find the reception code,first
and find update packet .
last parsed the NLRI information) 

thank you

**Comment by thomas-mangin** [comment]
The class Message is in charge of it, but the work is dispatched to the sub classes (Update, Open, etc.).

**Comment by andyccccc** [comment]
HI @thomas-mangin :
 I completed the work.
Thank your help, it give me great help

**Comment by thomas-mangin** [comment]
@andyccccc - Great to hear, If you want to share your work, I would be happy to cleanup and merge back - otherwise that's cool too.

**Comment by andyccccc** [comment]
I appreciate your suggestion,I updated in the follow url "https://github.com/andyccccc/reactor"
It recover your exabgp/lib/reactor directory,it could be work 
by the way I am a python beginner so there are some disarray code

**Comment by thomas-mangin** [comment]
@andyccccc - Thank you. however I can not really do anything with this. Could you fork the ExaBGP on github, then add your change into it and commit - so I can see what you changed. Otherwise I will not be able to take your work in.

**Comment by thomas-mangin** [comment]
added `show adj-rib [in|out]` to the API - so completed.
