### ISSUE TITLE
receive NOTIFICATION _dispatch bug

### ISSUE THREAD

**Issue by minglvyy** [Exa-Networks/exabgp#392]
hi, I used exabgp 3.4.13 ,when recveive NOTIFICATION  message,
self._dispatch[message_id](self,peer,message,header,*body) 
in lib/exabgp/reactor/api/processes.py will throw exception;
cause no register_process defined for NOTIFICATION  ;
but exabgp 4.0 seems to handle this case,could you fix it ?

**Comment by thomas-mangin** [comment]
Hello @minglvyy 

Sure I want to help and fix any issue you may have. Can you please send us the trace (the message ExaBGP is printing and asking you to copy and paste) here so I can have a look at it and if you prefer email it to me directly.

Without this information I can not help you.

**Comment by thomas-mangin** [comment]
Also could you please make sure the bug was not already fixed with the latest release. This issue rings a bell.

**Comment by minglvyy** [comment]
xabgp: 47710  message       Peer    10.101.29.31 ASN 100   << NOTIFICATION

********************************************************************************
EXABGP MISBEHAVED / HELP US FIX IT
********************************************************************************

Sorry, you encountered a problem with ExaBGP, as the problem only affects one
peer, we are trying to keep the program running.

There are a few things you can do to help us (and yourself):
- make sure you are running the latest version of the code available at
  https://github.com/Exa-Networks/exabgp/releases/latest
- if so report the issue on https://github.com/Exa-Networks/exabgp/issues
  so it can be fixed (github can be searched for similar reports)

PLEASE, when reporting, do include as much information as you can:
- do not obfuscate any data (feel free to send us a private  email with the
  extra information if your business policy is strict on information sharing)
  https://github.com/Exa-Networks/exabgp/wiki/FAQ
- if you can reproduce the issue, run ExaBGP with the command line option -d
  it provides us with much needed information to fix problems quickly
- include the information presented below

Should you not receive an acknowledgment of your issue on github (assignement,
comment, or similar) within a few hours, feel free to email us to make sure
it was not overlooked. (please keep in mind the authors are based in GMT/Europe)

********************************************************************************
-- Please provide ALL the information below on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

ExaBGP version : 3.4.13
Python version : 2.6.6 (r266:84292, May 29 2014, 05:49:27)  [GCC 4.4.6 20110731 (Red Hat 4.4.6-3)]
System Uname   : #1 SMP Mon Jan 28 17:12:52 CST 2013
System MaxInt  : 9223372036854775807


peer 10.101.29.31 ASN 100  

<type 'exceptions.KeyError'>
3
Traceback (most recent call last):
  File "/home/work/agentInstall/test1/exabgpAgent/newlyExabgp/exabgp/lib/exabgp/reactor/peer.py", line 587, in _run
    for action in self._main(direction):
  File "/home/work/agentInstall/test1/exabgpAgent/newlyExabgp/exabgp/lib/exabgp/reactor/peer.py", line 456, in _main
    for message in proto.read_message():
  File "/home/work/agentInstall/test1/exabgpAgent/newlyExabgp/exabgp/lib/exabgp/reactor/protocol.py", line 168, in read_message
    self.peer.reactor.processes.message(msg_id,self.peer,message,'','')
  File "/home/work/agentInstall/test1/exabgpAgent/newlyExabgp/exabgp/lib/exabgp/reactor/api/processes.py", line 270, in closure
    return function(self,*args)
  File "/home/work/agentInstall/test1/exabgpAgent/newlyExabgp/exabgp/lib/exabgp/reactor/api/processes.py", line 306, in message
    self._dispatch[message_id](self,peer,message,header,*body)
KeyError: 3

********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************


I add some code to lib/exabgp/reactor/api/processes.py as follows

    @register_process(Message.CODE.NOTIFICATION,_dispatch)
    def  _notification (self, peer, message, header, body):
        for process in self._notify(peer,'receive-notifications'):
            self.write(process,self._encoder[process].notification(peer,message,header,body),peer)

seems to work,I'm not sure if there are any other effects

exabgp 3.x newest version has no such code,so I this it does not resolve yet

**Comment by thomas-mangin** [comment]
@minglvyy - very well spotted and thanks for the fix :-)

**Comment by thomas-mangin** [comment]
I will surely release 3.5.16 soon - probably this week.

**Comment by minglvyy** [comment]
good news!

**Comment by minglvyy** [comment]
good news!
