### ISSUE TITLE
bug to parse 4 byte AS number?

### ISSUE THREAD

**Issue by pubyun** [Exa-Networks/exabgp#394]
exabgp unable to parse 4 byte AS number:

echo "announce route xxx.xxx.176.110/32 next-hop 172.16.255.46 community [1348xx:666]" > /var/run/exabgp.cmd

it give me:

exabgp: 1938879 processes     Command from process service-dynamic : announce route xxx.xxx.176.110/32 next-hop 172.16.255.46 community [1348xx:666]
exabgp: 1938879 reactor       Command could not parse route in : announce route xxx.xxx.176.110/32 next-hop 172.16.255.46 community [1348xx:666]

it's ok to parse any 2 byte AS number:

echo "announce route xxx.xxx.176.110/32 next-hop 172.16.255.46 community [65001:666]" > /var/run/exabgp.cmd

**Comment by thomas-mangin** [comment]
This is not an exabgp bug.

Communities are not big enough to store ASN4. the practice of encoding the ASN in community this way only work for 16 bits ASN.
