### ISSUE TITLE
router-id is not validated as IPv4 address, causing corruption in handshake packet

### ISSUE THREAD

**Issue by yuriya** [Exa-Networks/exabgp#395]
Hi,

We encountered the following situation: while connecting to IPv6 peer, we mistakenly used IPv6 address as our local router id.
This caused the BGP handshake packet to be corrupt: since IPv6 address is 16 bytes and IPv4 is 4 bytes, the 12 bytes immediately after the router id came out corrupted.
This caused a subtle bug where Juniper router (in our case) complained that it received unknown capabilities.
We suggest to add validation to router id field, or throw an exception with clear message, or hash any router id to 4 bytes string.

Thanks, Yuriy.

P.S. Example of wrong configuration:
group defenseflow  {
… 
  neighbor 20.20.20.20 {
    description "20.20.20.20";
    router-id 2001:5:5::7;
    local-address 2001:5:5::7;
    local-as 150;
    peer-as 150;
    hold-time 180;
  }
}

**Comment by thomas-mangin** [comment]
neighbor `<IPv4>` with local-address `<IPv6>` . That will also hurt.
Your are right that the RouterID class does accept some IPv6 entry -- it was not expected ! I will fix the issue.

**Comment by yuriya** [comment]
Thanks a lot Thomas!
