### ISSUE TITLE
support for user defined mp_reach_nlri, mp_unreach_nlri

### ISSUE THREAD

**Issue by Sachji** [Exa-Networks/exabgp#403]
Hello,

Is there any way to pass user defined mprnlri and mpunlri to exaBGP? For example pass these attributes through config.ini as hexadecimal string to exaBGP process, which would send it blindly to another exaBGP process?

I don't know if this could be possible, but I have an idea, that when there is some nlri with unknown SAFI, sending exaBGP process would just take data and send them to another exaBGP process. 
Similar receiving exaBGP process would just detect unknown SAFI and pass these data to my program to parse it.

I suppose I would have to implement it myself, in this case could you give me some hints, where or how would this change be implemented in code?

Thank you very much and have a nice day :-)

**Comment by thomas-mangin** [comment]
Yes, you can use the 'attribute' keyword to pass any binary (hex) data you want to your peer.

**Comment by thomas-mangin** [comment]
You can find an example of use here
https://github.com/Exa-Networks/exabgp/blob/master/qa/conf/attributes.conf

**Comment by Sachji** [comment]
I tried to send  mpnlri from node A to node B 


A:config.ini 

neighbor 192.168.51.96 {

        router-id 192.168.51.94;
        local-address 192.168.51.94;
        local-as 65000;
        peer-as 65000;
        group-updates false;

        family {
                ipv4 unicast;
                #ipv4 flow;
                #ipv4 flow-vpn;
                #ipv6 flow;
        }

        static {
                 route 10.0.0.7/32 {
                        # 0x0e: MP_REACH_NLRI
                        # 0x80: Optional, Transitive
                        # 0x01: AFI(IPv4)
                        # 0x96: SAFI(unicast)
                        # 0x10: Length of Next Hop Address
                        # 0xffffff00: Network address of Next Hop
                        # 0x00: Reserved
                        next-hop 10.0.255.7;
                        attribute [ 0x0e 0x80 0x019610ffffff0000 ];
                }

        }
}


B:config.ini

neighbor 192.168.51.94 {

        router-id 192.168.51.96;
        local-address 192.168.51.96;
        local-as 65000;
        peer-as 65000;
        group-updates false;

        process flowspec-parser {
            run //flowspec-parser.py;
            encoder json;
            receive {
                        parsed;
                        packets;
                        consolidate;
                        neighbor-changes;
                        notification;
                        #open;
                        #keepalive;
                        update;
                        refresh;
                        operational;
            }
        }
}

Node B does not output mplnri in hex format. There is an error in json output:

```
{
  "exabgp": "3.4.8",
  "time": 1460022663,
  "host": "tiger",
  "pid": "31037",
  "ppid": "30434",
  "counter": 6,
  "type": "state",
  "neighbor": {
    "ip": "192.168.51.94",
    "address": {
      "local": "192.168.51.96",
      "peer": "192.168.51.94"
    },
    "asn": {
      "local": "65000",
      "peer": "65000"
    },
    "state": "down",
    "reason": "out loop, peer reset, message [notification sent (3,0)] error[UPDATE message error \/ Unspecific \/ presented a non-negotiated family 406\/16]"
  }
}
```

In command line I can see it was parsed well:

```
Thu, 07 Apr 2016 11:51:03 | INFO     | 31037  | message       | Peer   192.168.51.94 ASN 65000   << UPDATE
Thu, 07 Apr 2016 11:51:03 | INFO     | 31037  | parser        | parsing flag 40 type 01 (origin) len 01 payload  (2) 00
Thu, 07 Apr 2016 11:51:03 | INFO     | 31037  | parser        | parsing flag 40 type 02 (as-path) len 00  (0) 
Thu, 07 Apr 2016 11:51:03 | INFO     | 31037  | parser        | parsing flag 40 type 03 (next-hop) len 04 payload  (9) 0A00 FF07
Thu, 07 Apr 2016 11:51:03 | INFO     | 31037  | parser        | parsing flag 40 type 05 (local-preference) len 04 payload  (9) 0000 0064
Thu, 07 Apr 2016 11:51:03 | INFO     | 31037  | parser        | parsing flag 80 type 0e (mp-reach-nlri) len 08 payload  (19) 0196 10FF FFFF 0000

```


negotiated family 406/16 does not make sense to me,  afi/safi   406/16 
Am I missing anything? 

Thank you

**Comment by thomas-mangin** [comment]
Yes, it was parsed but as the AFI/SAFI pair was not negotiated part of the OPEN exchange, so the daemon is mandated to terminate the session as it is illegal to send non-negotiated families.
I will need to add a feature to allow numerical AFI/SAFI in the family section so that your new NLRI is accepted. I will try to do this this week - it is not very long but I am quite busy ATM.

**Comment by Sachji** [comment]
I am really sorry, I badly understood what is truly needed. You don't need to change anything eventually it won't help us.

The deal is I need to send my proprietary filter data **along with** flowspec filter data AFI = 1, SAFI = 133. So it would help me to somehow force exaBGP to send/receive this data and possibly output them hexadecimal string in json along with standard flowspec filters, I think this would require to change sender/receiver and define new filter types.

Thank you Thomas,

**Comment by thomas-mangin** [comment]
@Sachji - still not sure what you are trying to achieve.

If your data is defined in an IETF draft - I can try to see if it can be (hopefully easily) implemented.

ExaBGP should just ignore unknown flowspec components - not sure if the JSON will contain them tho. If not this behaviour may be changed to allow it.

**Comment by Sachji** [comment]
In nutshell I am trying to filter traffic not only on standard filters like , destination, source, port, but also with another protocol specific filters. These filters are not defined in any draft and I currently don't know how many are needed. I think JSON cannot contain them, because flowspec format defined in RFC 5575  does not define filter length and almost all filter in RFC 5575 are fixed length.

I have an idea how to support my new filters :

sending exaBGP process config.ini example (Note: **raw [ hexvalue ];**):


			match {
				source 10.0.0.9/32;
				destination 192.168.0.1/32;
				port [ =80 =8080 ];
				destination-port [ >8080&<8088 =3128 ];
				source-port >1024;
				protocol [ udp tcp ];
                raw [ hexvalue ];
			}
			then {
				redirect 65500:12345;
			}

and receiving exaBGP process output of raw field will be the same as extended commodity field output:

**"raw": [ hexvalue ]**

**hexvalue ** would be in flowspec format and it would be a tuple of flowspec filters.
Problem is hexvalue can be variable so when receiving exaBGP would encounter unknown flowspec component it would just take rest of flowspec NLRI part and output it in JSON format defined above along with source, destination etc. Could it be possible?

Thank you for your time and consideration Thomas,

**Comment by thomas-mangin** [comment]
I will re-read the code and RFC to see how this could be achieved. It will be on the master branch.

**Comment by Sachji** [comment]
Maybe I am making it difficult. I am complete beginner in Python, so I don't know how simple it would be to add new filters in your code.  It seems I just need to create new classes ( and their new convert, decode functions) in flow.py file.  Am I right? If I am then I think this is the way to go.
