### ISSUE TITLE
exabgp do not send updata message

### ISSUE THREAD

**Issue by wuxg** [Exa-Networks/exabgp#406]
when the connection between exabgp and peer vyatta is ready,i execute the code 
                print "neighbor 192.1.2.1 announce route 1.1.0.1 next-hop self community [100:22]"
but the update message was sent out thousands of seconds later,how can i resolve this problem?

**Comment by wuxg** [comment]
the update message was sent out ten minutes later

**Comment by thomas-mangin** [comment]
Please can you make sure you force a flush on the stdout. By default IO operation are buffered.

**Comment by wuxg** [comment]
Some of the files are modified by my workmate,this problem is gone after I recover these files.I'm sorry to have wasted your time.

**Comment by thomas-mangin** [comment]
No worries - good luck !
