### ISSUE TITLE
how can i announce a multi-next hops(equal cost multpath, ECMP)

### ISSUE THREAD

**Issue by liuheyang** [Exa-Networks/exabgp#408]
hi, 
    i announce a  prefix with 2 next-hops to router, but the router only show one of the next-hops.
announce route command:
   'neighbor 192.168.2.3 announce route 10.10.31.0/24 next-hop 192.31.41.31'
   'neighbor 192.168.2.3 announce route 10.10.31.0/24 next-hop 192.41.44.44'
bgp routing table:
    VPN-Instance vpn3, Router ID 192.168.2.3:
        Network            NextHop        MED        LocPrf    PrefVal Path/Ogn
 *>i    10.10.31.0/24      192.41.44.44               100        0       i
 *>     10.10.41.0/24      0.0.0.0                          0          0       ?

**Comment by liuheyang** [comment]
in the application, exabgp only send one bgp update packet with prefix 10.10.31.0/24 and next-hop 192.41.44.44. there is no update packet for  10.10.31.0/24 next-hop 192.31.41.31

**Comment by xiaopeng163** [comment]
I thinks both are sent out.  The first prefix's nexthop is 192.31.41.31, then exabgp will send a prefix update with new nexthop: 192.31.41.44

**Comment by liuheyang** [comment]
but i can't catch the route update packet with nexthop  192.31.41.31 by wirkshark, i think maybe there is something in exabgp

**Comment by liuheyang** [comment]
@xiaopeng163, hi,  as you say, I send these two route announcement to the route seperately, but the old one is updated by the new one, how can i active these two route, thanks!

**Comment by xiaopeng163** [comment]
1.  if there is just one BGP session, maybe BGP add path feature can help
2. you can start two exabgp process and setup two BGP sessions with your router, all exabgp sessions advertise the same prefix but with different nexthop.

**Comment by thomas-mangin** [comment]
Sorry for the delay in answering.

I do not know how vendor have implemented ECMP. you can try to use the per peer option "adj-rib-out" (and set it to false) to disable the adj-rib-out.

I am not sure anymore if ExaBGP will explicitly withdraw a route when a new annoucement is sent. If this is the case this option should just do what you need.

In that case, ExaBGP will not re-announce routes if the BGP session is lost (this will be something the backend-process will need to take care of) but with this option ExaBGP does not look at the Adj-RIB-Out.

Feel free to update this issue if you have more information. Thanks.

**Comment by liuheyang** [comment]
thanks @xiaopeng163 @thomas-mangin. i have solved it according to @xiaopeng163's idea
