### ISSUE TITLE
add-path capability is advertising for a single family only

### ISSUE THREAD

**Issue by alexander-bespalov** [Exa-Networks/exabgp#409]
I have enabled 'add-path send/receive' for a neighbor with multiple address families and see that the capability is advertising just for one family.

My configuration is:
```
neighbor 192.168.255.17 {
        group-updates true;
        local-address 192.168.255.2;
        peer-as 65000;
        local-as 65000;
        add-path send/receive;
        family {
                ipv4 unicast;
                ipv4 nlri-mpls;
        }
}
```

Add path has been advertising only for ipv4 nlri-mpls. Output from neighbor:
```
> show bgp neighbor 192.168.255.2 | grep path
  NLRI's for which peer can send and receive multiple paths: inet-labeled-unicast
```

My exabgp version is 3.4.16.

**Comment by thomas-mangin** [comment]
Can you please run exabgp with the -d option and please provide me the OPEN message which were exchanged. I want to see what has been sent and received. If you peer did not announce IPv4 unicast for add-path, it be why.

**Comment by thomas-mangin** [comment]
To clarify what you shown is that add-path was only negotiated for inet-labeled-unicast, which does not mean that it was ExaBGP which did not announce to its peer that it did not also support it for ipv4 unicast.

**Comment by alexander-bespalov** [comment]
Thomas,

On the peer I see that ExaBGP is advertising add-path capability only for one family - inet-labeled-unicast in the example above.

If I remove ipv4 nlri-mpls from the ExaBGP configuration it is successfully negotiating add-path for unicast family.

**Comment by thomas-mangin** [comment]
@alexander-bespalov what version of exabgp are you using ?

**Comment by alexander-bespalov** [comment]
3.4.16

**Comment by thomas-mangin** [comment]
ok - looking (for as long as my battery last ..)

**Comment by thomas-mangin** [comment]
@alexander-bespalov Can you please send me, as I previously asked, the output of ExaBGP including the OPEN message sent and received as AFAICS, ExaBGP does generate the right OPEN message.

(Pdb++) print self
OPEN version=4 asn=1 hold_time=180 router_id=1.2.3.4 capabilities=[Multiprotocol(ipv4 unicast,ipv4 nlri-mpls), ASN4(1), AddPath(send/receive ipv4 unicast,send/receive ipv4 nlri-mpls)]

**Comment by alexander-bespalov** [comment]
@thomas-mangin I have checked tcpdump... The difference between Juniper and ExaBGP is the following (the peer is Juniper box in my setup). ExaBGP is advertising separate capabilities for different address families. But Juniper is advertising and expecting single add-path capability for several families.

According to draft-ietf-idr-add-paths-13 it should be single capability message with multiple address families:
   A BGP speaker that wishes to indicate support for multiple AFI/SAFI
   MUST do so by including the information in a single instance of the
   ADD-PATH Capability.

[ExaBGP-2.zip](https://github.com/Exa-Networks/exabgp/files/227974/ExaBGP-2.zip)


> 

>

**Comment by thomas-mangin** [comment]
@alexander-bespalov understood - thank you for this. Silly bug I never noticed before !
Should be fixed by this patch
https://github.com/Exa-Networks/exabgp/commit/a9ef67106698dd8e55abf149db0319ad9dedfe24

**Comment by thomas-mangin** [comment]
The wording came with -13
https://tools.ietf.org/rfcdiff?difftype=--hwdiff&url2=draft-ietf-idr-add-paths-13.txt

So I will claim that I was indeed 'compliant' with -11 (and yes, I am not serious here).

**Comment by thomas-mangin** [comment]
Sorry - this patch is buggy

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/commit/f5e4c65ca070289da81c7b81e3f8559a0efe761a

**Comment by thomas-mangin** [comment]
@alexander-bespalov hopefully this fixes the issue - sorry for this bug.

**Comment by thomas-mangin** [comment]
sorry - coding in a conference - not ideal
https://github.com/Exa-Networks/exabgp/commit/3dce7bfbdccb45456c600a0cb72b76d63e7d9bfb

**Comment by alexander-bespalov** [comment]
@thomas-mangin Thanks a lot! Looks like it is working as expected now.

BTW: just have seen enhancement record to enable add-path per address family - will be very useful...
