### ISSUE TITLE
about exabgp announce route performancce

### ISSUE THREAD

**Issue by liuheyang** [Exa-Networks/exabgp#413]
hi, @thomas-mangin 
    in my application, my exabgp as a controller connects to several hundreds of vrouters, and announce routes to these routers at the same time. but i found exabgp may not send the  announce commands or discard the commands, how can i improve the route announce performance of exabgp
thanks!

**Comment by thomas-mangin** [comment]
@liuheyang very sorry, I have not yet looked into this issue as other matters have been taking all my time. I have not forgotten tho.

**Comment by thomas-mangin** [comment]
@liuheyang you should look at the CPU used by ExaBGP. Python can not take advantage of multi-core processor. So the best way would be to break your peers in group and run multiple ExaBGP, would it be an acceptable work around ?
