### ISSUE TITLE
 exabgp it not works with 6 digit numbers AS

### ISSUE THREAD

**Issue by sl-net** [Exa-Networks/exabgp#414]
exabgp: 1800   reactor       Command could not parse route in : announce route 192.168.11.50/32 next-hop 192.0.2.1 community 199999:666

ExaBGP : 3.4.16
Python : 2.7.9 (default, Mar  1 2015, 12:57:24)  [GCC 4.9.2]
Uname  : #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08)

**Comment by hide** [comment]
BGP community is 32bit value.
You must be set <2octet ASN>:<2octet Value> or <4octet value>.

**Comment by sl-net** [comment]
Thanks for the answer, but
 <2octet ASN> is only 16 bit value not 32. We have 4octet ASN?

**Comment by hide** [comment]
I think there is no way to encode 4octet ASN.
Wide BGP community is proposed as IETF I-D.

**Comment by thomas-mangin** [comment]
Hello @sl-net,

@hide is correct, there is no way to encode a 32 bits value using the binary format of the normal community. I know this is frustrating .. 

The support for wide community is still in discussion at the IETF:
https://tools.ietf.org/html/draft-ietf-idr-registered-wide-bgp-communities-01
