### ISSUE TITLE
Process message does not work 

### ISSUE THREAD

**Issue by pugna0** [Exa-Networks/exabgp#415]
I use exabgp to communicate with my quagga bgp router.
exabgp version: 3.4.16
os : Fedora 23
python: 2.7

Error details and codes are shown in the project below.
https://github.com/pugna0/exabgp-issue.git

**Comment by thomas-mangin** [comment]
```
sudo /opt/exabgp-3.4.16/sbin/exabgp -e ~/gitlab/nxg-exabgp-suit/conf/message-handler.env ~/gitlab/nxg-exabgp-suit/conf/bgp-message-dev.cfg
exabgp: 21435  reactor       Performing reload of exabgp 3.4.16
exabgp: 21435  configuration parsing | process       | 'encoder' 'json' ';'
exabgp: 21435  configuration parsing | process       | 'receive' '{'
exabgp: 21435  configuration parsing | receive       | 'notification' '{'
exabgp: 21435  configuration Problem with the configuration file, no change done
exabgp: 21435  configuration
exabgp: 21435  configuration syntax error in section receive
exabgp: 21435  configuration line 16: notification {
```

Support for notification is only available on master and is a feature planned for 4.0.0 - I do not intend to backport the code to 3.4 it would be too intrusive and would surely have some side effect when 3.4 is a stable branch.

Sorry for this answer. You can try master (knowing that the configuration format is changing without warning and that you should be careful when updating).

I recently (this week) updated the sample code at 
https://github.com/Exa-Networks/exabgp/blob/master/etc/exabgp/processes/read-write.py

You may want to take my improvements / fix in.

**Comment by pugna0** [comment]
Tue, 10 May 2016 14:33:02 | INFO     | 20380  | reactor       | performing reload of exabgp 4.0.0
Tue, 10 May 2016 14:33:02 | INFO     | 20380  | configuration | > neighbor         | '10.6.5.120'
Tue, 10 May 2016 14:33:02 | INFO     | 20380  | configuration | . description      | 'Message handler'
Tue, 10 May 2016 14:33:02 | INFO     | 20380  | configuration | . router-id        | '127.0.0.1'
Tue, 10 May 2016 14:33:02 | INFO     | 20380  | configuration | . local-address    | '10.6.5.120'
Tue, 10 May 2016 14:33:02 | INFO     | 20380  | configuration | . local-as         | '65518'
Tue, 10 May 2016 14:33:02 | INFO     | 20380  | configuration | . peer-as          | '65517'
Tue, 10 May 2016 14:33:02 | INFO     | 20380  | configuration | . hold-time        | '90'
Tue, 10 May 2016 14:33:02 | INFO     | 20380  | configuration | > family           | 
Tue, 10 May 2016 14:33:02 | INFO     | 20380  | configuration | . ipv4             | 'unicast'
Tue, 10 May 2016 14:33:02 | INFO     | 20380  | configuration | < family           | 
Tue, 10 May 2016 14:33:02 | INFO     | 20380  | configuration | > process          | 'message-handler'
Tue, 10 May 2016 14:33:02 | ERROR    | 20380  | configuration | problem with the configuration file, no change done
Tue, 10 May 2016 14:33:02 | ERROR    | 20380  | configuration | 
Tue, 10 May 2016 14:33:02 | ERROR    | 20380  | configuration | syntax error in section neighbor
Tue, 10 May 2016 14:33:02 | ERROR    | 20380  | configuration | line 11: process message-handler {
Tue, 10 May 2016 14:33:02 | ERROR    | 20380  | configuration | 
Tue, 10 May 2016 14:33:02 | ERROR    | 20380  | configuration | section process is invalid in neighbor, neighbor

I used 4.0.0 on master before, was the prammar for configuration file same as 3.4.16?

**Comment by thomas-mangin** [comment]
No the grammar is different, and still changing. You will find plenty of examples in the qa/conf folder.
