### ISSUE TITLE
Invalid JSON messages

### ISSUE THREAD

**Issue by lamehost** [Exa-Networks/exabgp#416]
I think that i have found an issue in how ExaBGP formats the messages with the announced prefixes.

The problem is the list of the prefixes is surrounded by curly braces which imply an object and if the list contains VPNV4 prefixes a duplicate name may arise.

This is a simplified example of what i have found in a production environment:
```
"announce": { 
  "ipv4 mpls-vpn": { 
    "192.0.2.1": { 
      "198.51.100.0/29": { "label": [ 11903 ], "route-distinguisher": "65412:1" }, 
      "198.51.100.0/29": { "label": [ 48298 ], "route-distinguisher": "64512:2" }
    }
  }
}
```

If you parse the above with json or ujson (Python here) they will dump the object as follows:
```
"announce": { 
  "ipv4 mpls-vpn": { 
    "192.0.2.1": { 
      "198.51.100.0/29": { "label": [ 48298 ], "route-distinguisher": "64512:2" }
    }
  }
}
``` 

That is beacuse the JSON specifications state that an object is a dictionary-like collection of name/value pairs.

I'd suggest to format the list as follows:
```
"announce": { 
  "ipv4 mpls-vpn": { 
    "192.0.2.1": { 

  "ipv4 mpls-vpn": { 
    "192.0.2.1": { 
      "198.51.100.0/29": { "label": [ 11903 ], "route-distinguisher": "65412:1" }, 
      "198.51.100.0/29": { "label": [ 48298 ], "route-distinguisher": "64512:2" }
    }
  }
}
```

If you parse the above with json or ujson (Python here) they will dump the object as follows:
```
"announce": { 
  "ipv4 mpls-vpn": { 
    "192.0.2.1": { 
      "198.51.100.0/29": { "label": [ 48298 ], "route-distinguisher": "64512:2" }
    }
  }
}
``` 

That is beacuse the JSON specifications state that an object is a dictionary-like collection of name/value pairs.

I'd suggest to format the name of the item in the object as follows:
```
"announce": { 
  "ipv4 mpls-vpn": { 
    "192.0.2.1": { 
      "64512:1:198.51.100.0/29": { "label": [ 11903 ], "route-distinguisher": "65412:1" }, 
      "64512:2:198.51.100.0/29": { "label": [ 48298 ], "route-distinguisher": "64512:2" }
    }
  }
}
```

**Comment by thomas-mangin** [comment]
Ok, I can see how the current format can "eat" data and it is very undesirable.
What about this:
```
"announce": { 
  "ipv4 mpls-vpn": { 
    "192.0.2.1": [
      { "nlri": 198.51.100.0/29": { "label": [ 11903 ], "route-distinguisher": "65412:1" }, 
      { "nlri": 198.51.100.0/29": { "label": [ 48298 ], "route-distinguisher": "64512:2" }
    ]
  }
}
````

**Comment by lamehost** [comment]
Looks good

**Comment by thomas-mangin** [comment]
Could also change the format to have IPv4 and IPv6 unicast as a list of nlri without having the object.

**Comment by thomas-mangin** [comment]
Could you please test this :
```
diff --git a/lib/exabgp/bgp/message/update/nlri/inet.py b/lib/exabgp/bgp/message/update/nlri/inet.py
index 266e0d7..60cea40 100644
--- a/lib/exabgp/bgp/message/update/nlri/inet.py
+++ b/lib/exabgp/bgp/message/update/nlri/inet.py
@@ -69,7 +69,10 @@ class INET (NLRI):
                return [self.path_info.json()]

        def json (self, announced=True):
-               return '"%s": { %s }' % (self.cidr.prefix(),", ".join(self._internal(announced)))
+               internal = ", ".join(self._internal(announced))
+               if internal:
+                       return '{ "nrli": "%s", %s }' % (self.cidr.prefix(),internal)
+               return '"%s"' % self.cidr.prefix()

        @classmethod
        def _pathinfo (cls, data, addpath):
diff --git a/lib/exabgp/bgp/message/update/nlri/vpls.py b/lib/exabgp/bgp/message/update/nlri/vpls.py
index 50fd0e2..f8c1484 100644
--- a/lib/exabgp/bgp/message/update/nlri/vpls.py
+++ b/lib/exabgp/bgp/message/update/nlri/vpls.py
@@ -83,7 +83,7 @@ class VPLS (NLRI):
                        '"offset": %s' % self.offset,
                        '"size": %s' % self.size,
                ])
-               return '"vpls-%s": { %s }' % (self.unique, content)
+               return '{ %s }' % (content)

        def extensive (self):
                return "vpls%s endpoint %s base %s offset %s size %s %s" % (
```

**Comment by lamehost** [comment]
I have backported the patch to 3.4.16 and the outcomes are good, but there are a few things left to handle:
```
diff --git a/lib/exabgp/bgp/message/update/nlri/inet.py b/lib/exabgp/bgp/message/update/nlri/inet.py
index 266e0d7..60cea40 100644
--- a/lib/exabgp/bgp/message/update/nlri/inet.py
+++ b/lib/exabgp/bgp/message/update/nlri/inet.py
@@ -69,7 +69,10 @@ class INET (NLRI):
                return [self.path_info.json()]

        def json (self, announced=True):
-               return '"%s": { %s }' % (self.cidr.prefix(),", ".join(self._internal(announced)))
+               internal = ", ".join(self._internal(announced))
+               if internal:
+                       return '{ "nrli": "%s", %s }' % (self.cidr.prefix(),internal)
+               return '"%s"' % self.cidr.prefix()
```

As per my understanding the above returns two different formats depending on the presence of attributes in the NLRI.
I don't think that is the best behavior because if forces you to check the type of the element (if str or dict/obj/ash) during parsing.
Do you think that you can always return an object instead?

Also, at least on 3.4.16, the patch breaks the support of EOR messages.

**Comment by thomas-mangin** [comment]
It is a lot of extra parsing for IPV4 unicast, I may add this optimisation as an option on the peer ...

**Comment by MadDog2K** [comment]
@thomas-mangin 

Is it correct this affects output for all families, eg. also 'ipv4/ipv6 unicast' routes (non-MPLS)  ?

"announce": { 
  "ipv4 unicast": { 
    "192.0.2.1": [
      { "nlri": 198.51.100.0/29", }, 
      { "nlri": 198.51.101.0/29", }
    ]
  }
}

And is it correct that compact=true modifies this to the following ?


"announce": { 
  "ipv4 unicast": { 
    "192.0.2.1": [ 
       "198.51.100.0/29", 
       "198.51.101.0/29" 
    ]
  }
}


What would be the pro's or con's of compact=true ?

**Comment by MadDog2K** [comment]
In any case, I have some problem with the new format (with compact=false)

JSON returned : 

{ "exabgp": "3.5.0", "time": 1467654789.08, "host" : "jafar.management.is", "pid" : 8604, "ppid" : 1, "counter": 3, "type": "update", "neighbor": { "address": { "local": "10.86.2.221", "peer": "10.86.2.218" }, "asn": { "local": "65099", "peer": "15879" }, "direction": "receive", "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 15879 ], "confederation-path": [], "community": [ [ 15879, 999 ] ] }, "announce": { "ipv4 unicast": { "10.86.2.218": [ { "nlri": "185.55.131.0/24",  }, { "nlri": "185.55.130.0/24",  } ] } } } } } }

decoding that with json.loads() fails

Test case python 2.6 :  

echo '{ "exabgp": "3.5.0", "time": 1467654789.08, "host" : "jafar.management.is", "pid" : 8604, "ppid" : 1, "counter": 3, "type": "update", "neighbor": { "address": { "local": "10.86.2.221", "peer": "10.86.2.218" }, "asn": { "local": "65099", "peer": "15879" }, "direction": "receive", "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 15879 ], "confederation-path": [], "community": [ [ 15879, 999 ] ] }, "announce": { "ipv4 unicast": { "10.86.2.218": [ { "nlri": "185.55.131.0/24",  }, { "nlri": "185.55.130.0/24",  } ] } } } } } }' | python -m json.tool
Expecting property name: line 1 column 499 (char 499)

Test case with Pyhon 3.3.5 : 

echo '{ "exabgp": "3.5.0", "time": 1467654789.08, "host" : "jafar.management.is", "pid" : 8604, "ppid" : 1, "counter": 3, "type": "update", "neighbor": { "address": { "local": "10.86.2.221", "peer": "10.86.2.218" }, "asn": { "local": "65099", "peer": "15879" }, "direction": "receive", "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 15879 ], "confederation-path": [], "community": [ [ 15879, 999 ] ] }, "announce": { "ipv4 unicast": { "10.86.2.218": [ { "nlri": "185.55.131.0/24",  }, { "nlri": "185.55.130.0/24",  } ] } } } } } }' | python3.3 -m json.tool
Expecting property name enclosed in double quotes: line 1 column 500 (char 499)

**Comment by thomas-mangin** [comment]
From the top of my head: correct

Pros
- easier/faster to use/parse

Cons
- you need to interpret the output of IPv4/IPv6 unicast differently from other familes
