### ISSUE TITLE
Include negotiated AFI/SAFI in the open message

### ISSUE THREAD

**Issue by lamehost** [Exa-Networks/exabgp#417]
It would be useful to have in the _neighbor-changes/up_ the list of the negotiated AFI/SAFI during the setup of the session (at least in JSON format).

As per my understanding you already have to parse them during that phase, so you only have to propagate the proper strings.

The JSON object may be like:
{ 
    "exabgp": "2.0", 
    "time": 1388408061, 
    "neighbor": { 
        "ip": "10.0.0.2", 
        "state": "up" 
    } 
    family {
        ipv4 unicast;
        ipv6 unicast;
        ipv4 mpls-vpn;
    }
 }

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/commit/62eb0d414325d4c5b020df361e26651586ef1032
