### ISSUE TITLE
separated flow (question)

### ISSUE THREAD

**Issue by azlux** [Exa-Networks/exabgp#418]
Hi,
I'm still reading the wiki of exabgp. I have multiple router I control with BGP route and few routers I control with flowspec.
When I read the wiki for [limiting diffusion of routes] (https://github.com/Exa-Networks/exabgp/wiki/Controlling-ExaBGP-:-limiting-diffusion-of-routes), there are the possibility for announce a route to one one or multiple neighbor.
Do there are the possibility to announce to a group, that way, we can separate fowspec and bgp route when routers cannot handle both.

Thank a lot.

**Comment by azlux** [comment]
ok, my fault, we need one process (service-dynamic) by neighbor.
So i I have multiple peer, i need to launch the service-dynamic for each peer.
Sorry for the issue.
My option is to add parameter to my script, and it's work well.

Thank a lot

**Comment by thomas-mangin** [comment]
Be careful, on 3.4 the separation does not work well. The other solution is to limit the families you want to announce to each peer as again under 3.4 the announce command from the backend process will only send routes if the family was configured.

**Comment by azlux** [comment]
Indeed with specific families, exabgp filter rules.
But i cannot resolve my problem. When i launch one service dynamic rule with two neighbor, only the first one have the route added.
And if I add one process for each neighbor, only the first one will start.

**Comment by thomas-mangin** [comment]
You can split the config in two files and pass them both to exabgp (which will fork two processes for you).

**Comment by azlux** [comment]
no other way to send rules by service dynamic to multiple neighbors ?

**Comment by thomas-mangin** [comment]
The order in which you declare element matters, for example:

neighbor
process
neighbor

may not bring the same result as 

process 
neighbor
neighbor

If you really want to control things clearly, master, while not finished is stable and surely a better option.

**Comment by thomas-mangin** [comment]
(You will have to adjust a little bit your code when 4.0 is released as some changes will occur but it should not be much).

**Comment by azlux** [comment]
ok, find the problem, after having the good order, log are not good.
I've test with 2 router. (one accept flow and the other unicast)
Exabgp told me : Route added to neighbor <IP> twice with the same IP. But in the reality, It send the route to my two router.

**Comment by thomas-mangin** [comment]
ah .. ok - let me see that !

**Comment by thomas-mangin** [comment]
Can I have this output to try to understand what it happening please ?

**Comment by azlux** [comment]
````
Wed, 01 Jun 2016 17:26:51 | INFO     | 8975   | processes     | Command from process service-dynamic : announce route 8.8.8.7/32 next-hop 128.***.***.171 community 16347:9999
Wed, 01 Jun 2016 17:26:51 | INFO     | 8975   | reactor       | Route added to neighbor 128.***.***.4 local-ip **** local-as 12395 peer-as 12395 router-id **** family-allowed in-open : 8.8.8.7/32 next-hop 128.***.***.171 community 16347:9999
Wed, 01 Jun 2016 17:26:51 | INFO     | 8975   | reactor       | Route added to neighbor 128.***.***.4 local-ip **** local-as 12395 peer-as 12395 router-id **** family-allowed in-open, neighbor 128.***.***.2 local-ip **** local-as 12395 peer-as 12395 router-id **** family-allowed in-open : 8.8.8.7/32 next-hop 128.***.***.171 community 16347:9999
Wed, 01 Jun 2016 17:26:52 | INFO     | 8975   | reactor       | Performing dynamic route update
Wed, 01 Jun 2016 17:26:52 | INFO     | 8975   | reactor       | Updated peers dynamic routes successfully
````
My conf : 
````

group dca {
    router-id ****;
    
    process service-dynamic {
       run "/root/exabgp/dynamic_route.py";
    }
    neighbor 128.***.***.4 {
        local-address ****;
        local-as 12395;
        peer-as 12395;
        family {
            inet4 unicast;
            inet4 flow;
            inet6 unicast;
            inet6 flow;
        }
    }
    
    neighbor 128.***.***.2 {
        local-address *****
        local-as 12395;
        peer-as 12395;
        family {
            inet4 unicast;
            inet6 unicast;
        }
    }
}
````
the log said it try to send to .2 twice. (and the second neighbor was out of screen (my bad) because of the big line)

**Comment by thomas-mangin** [comment]
Hi - this is a different issue, can I please have a new issue, but yes something is not right.
