### ISSUE TITLE
Method for triggering route dump to child process

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#42]
It would be rather helpful to us to have some method to cause exabgp to provide it's entire route table to the child process.

This would allow a restarted downstream process to have the full table available to it without having to restart exa to force a resend.
As it is, if the child process restarts it is only told about subsequent route changes and thus is unaware of most of the table.  This presents a problem if the child process is relaying that data to another process where it is less than ideal to persist the route table to disk.

A possible implementation, if SIGUSR2's current behaviour is as intended, would be to add a config command to the process block, something like "receive-full-at-start" perhaps, which would allow SIGUSR2 to cause the route table to be sent without breaking backward compatibility.
As a bonus, this could also let the child get a full table if it exited for another reason, rather than being killed by SIGUSR2.

Running HG tip on ubuntu 64 bit.

_From [kaithar....@gmail.com](https://code.google.com/u/102968841564747236710/) on August 08, 2013 12:42:41_
_Original issue: http://code.google.com/p/exabgp/issues/detail?id=42_

**Comment by icb-** [comment]
Adding to this, I would like to be able to request a dump of current routes from each peer at any time (`show routes received [from <peer> [<peer> ...]]`?), not just at script start. Ideally for me, the dump would be in a single message (per peer) to the script.

**Comment by thomas-mangin** [comment]
`show adj-rib in` and `show adj-rib out`
