### ISSUE TITLE
Python3 compatability

### ISSUE THREAD

**Issue by JonasGroeger** [Exa-Networks/exabgp#421]
As of yet, exabgp cannot be run on python3. Is this planned?

**Comment by thomas-mangin** [comment]
Python 3 would require quite some work, it was considered for the release of 4.0 but it now look like it will require a major release on its own. So it is considered but not going to happen very soon.

**Comment by JonasGroeger** [comment]
I mean its not THAT big, since we can launch python3 scripts from within exabgp.
