### ISSUE TITLE
IOS-XR BGP next-hop issues in latest -master

### ISSUE THREAD

**Issue by chrisk-de** [Exa-Networks/exabgp#423]
I am seeing the following error on our IOS-XR boxes for routes announced with:
announce route removed /24 extended-community [12306:6999 12306:9200 12306:6900]

RP/0/RSP0/CPU0:Jun 1 14:34:48.817 CEST: bgp[1050]: %ROUTING-BGP-3-MALFORM_UPDATE : Malformed UPDATE message received from neighbor (VRF: default) - message length 68 bytes, error flags 0x00000800, action taken "TreatAsWdr". Error details: "Error 0x00000800, Field "Attr-missing", Attribute 3 (Flags 0x00, Length 0), Data []". NLRIs: [IPv4 Unicast] removed /24

I have sent you the requested details via mail, as I do not want to disclose the entire raw data to the public :-)

**Comment by thomas-mangin** [comment]
Hi Christian,

Thank you for the bug report and off-line data to diagnose it, much appreciated.

The route you were trying to send was invalid. I was not checking for the presence of a next-hop when parsing routes from the API.

I have now fixed this on master https://github.com/Exa-Networks/exabgp/commit/b12a94aa3e05a1c9c95fb4d70f87aa7b70c0a759 and ExaBGP will now refuse to announce it.

Could you please try the patch, and if it does indeed prevent the announcement, then add a `next-hop 'IP'` to your command to make sure the router can accept it.
