### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by azlux** [Exa-Networks/exabgp#426]
Is the IPv6 working with ExaBGP ? I have this message (it's a clone of the master branch)
````
Wed, 08 Jun 2016 15:01:58 | INFO     | 24093  | processes     | Command from process service-dynamic : announce flow route {\n match {\n source 2a01:728:101:11:594b:bf07:136c:79c9/64;\n  protocol 17;\n }\n then {\n discard;\n }\n }\n
Wed, 08 Jun 2016 15:01:58 | WARNING  | 24093  | reactor       | callback | handling 'announce flow route {\n match {\n source 2a01:728:101:11:594b:bf07:136c:79c9/64;\n protocol 17;\n }\n then {\n discard;\n }\n }\n' with announce_flow
Wed, 08 Jun 2016 15:01:58 | INFO     | 24093  | reactor       | callback | installing announce_flow
Wed, 08 Jun 2016 15:01:58 | INFO     | 24093  | reactor       | callback | running
Wed, 08 Jun 2016 15:01:58 | INFO     | 24093  | configuration | > route            |
Wed, 08 Jun 2016 15:01:58 | INFO     | 24093  | configuration | > match            |
Wed, 08 Jun 2016 15:01:58 | INFO     | 24093  | configuration | . source           | '2a01:728:101:11:594b:bf07:136c:79c9/64'
Wed, 08 Jun 2016 15:01:58 | INFO     | 24093  | configuration |
Wed, 08 Jun 2016 15:01:58 | INFO     | 24093  | configuration | syntax error in api command route/match
Wed, 08 Jun 2016 15:01:58 | INFO     | 24093  | configuration | line 3: source 2a01:728:101:11:594b:bf07:136c:79c9/64 ;
Wed, 08 Jun 2016 15:01:58 | INFO     | 24093  | configuration |
Wed, 08 Jun 2016 15:01:58 | INFO     | 24093  | configuration | invalid literal for int() with base 10: '2a01:728:101:11:594b:bf07:136c:79c9'
Wed, 08 Jun 2016 15:01:58 | WARNING  | 24093  | reactor       | command could not parse flow in : announce flow route {\n match {\n source 2a01:728:101:11:594b:bf07:136c:79c9/64;\n protocol 17;\n }\n then {\n discard;\n }\n }\n
Wed, 08 Jun 2016 15:01:58 | WARNING  | 24093  | reactor       | reason: invalid literal for int() with base 10: '2a01:728:101:11:594b:bf07:136c:79c9'
Wed, 08 Jun 2016 15:01:58 | INFO     | 24093  | reactor       | responding to service-dynamic : error
Wed, 08 Jun 2016 15:01:58 | INFO     | 24093  | reactor       | callback | removing
````

**Comment by thomas-mangin** [comment]
please try source-ipv6 - the syntax changed.

**Comment by azlux** [comment]
ok, the traceback is [here] (https://azlux.fr.nf/bin/?40ad0e1c677ea806#Ub08wzMfV4RRHiHz1ciO2AZld5JXgJYieXVDTIlZ4Eg=). Still having error, but this time it's crashing to exabgp. (do we have the new configuration file example ?)

**Comment by thomas-mangin** [comment]
That crash was fixed in the latest master I think but the underlying cause should not have been there. investigating.

**Comment by thomas-mangin** [comment]
On master could you please change
```
announce flow route {\n match {\n source-ipv6 2a01:728:101:11:594b:bf07:136c:79c9/64;\n protocol 17;\n }\n then {\n discard;\n }\n }\n
```
by 
```
announce flow route { match { source-ipv6 2a01:728:101:11:594b:bf07:136c:79c9/64; protocol 17; } then { discard; } }\n
```
removing all the \n but the last one, the parser can now handle the command in one line and give me the error you are getting. It would save me time investigating.

**Comment by thomas-mangin** [comment]
Sorry - code now pushed.

**Comment by azlux** [comment]
ok, I will try that tomorrow. thank for your work

**Comment by azlux** [comment]
Still the error ([here](https://azlux.fr.nf/bin/?ba869d4e46ef99df#MiY4GgnK4s29ByE3dXb5ttqOYEI+qTVyLkdpfdIkwig=))

**Comment by thomas-mangin** [comment]
Can you please git pull - I changed that line 
https://github.com/Exa-Networks/exabgp/commit/8bb61db9500d9f1444f748649c216bed5af5bde2

**Comment by azlux** [comment]
Ho, i forgot, sorry.
[Here the traceback of the crash](https://azlux.fr.nf/bin/?40ef4f1877aba793#dgKFAcBH6VJv06JOTcg4EE2hHB1kYn8SLXzE3LN/ePk=)

**Comment by thomas-mangin** [comment]
Ok - thanks. This should fix the issue:
https://github.com/Exa-Networks/exabgp/commit/608742cb5b00d57b406a95f750ed94572caf2beb

**Comment by azlux** [comment]
:+1:  it's stop crashing.
I suppose it's just a syntax problem now ? 
````
Thu, 09 Jun 2016 11:55:48 | WARNING  | 26310  | reactor       | command could not parse flow in : announce flow route { match { source-ipv6 2a01:728:101:11:594b:bf07:136c:79c9/64; protocol 17; } then { discard; } }\n
Thu, 09 Jun 2016 11:55:48 | WARNING  | 26310  | reactor       | reason: invalid literal for int() with base 10: '2a01:728:101:11:594b:bf07:136c:79c9'
````

**Comment by thomas-mangin** [comment]
The code to parse ipv6 is now 
```
def source (tokeniser):
	data = tokeniser()
	if data.count('/') == 1:
		ip,netmask = data.split('/')
		raw = ''.join(chr(int(_)) for _ in ip.split('.'))
		yield Flow4Source(raw,int(netmask))
	else:
		ip,netmask,offset = data.split('/')
		yield Flow6Source(IP.pton(ip),int(netmask),int(offset))
```

So it seems that for IPv6 two / are expected but one should work and does not atm .. I need to change the code .. I will try to find some time later on today.

**Comment by azlux** [comment]
it's now working
And I don't have the second parsing error with this announce : 
````
announce flow route { match { source-ipv6 2a01:728:101:11:594b:bf07:136c:79c9/64; protocol 17; } then { discard; } }
````
(without the \n at the end of the line)

**Comment by thomas-mangin** [comment]
I am confused - what did you change please ?

**Comment by azlux** [comment]
check the [pull request](https://github.com/Exa-Networks/exabgp/pull/428).
When you check the number of " / " every IP will be treated as a IPv4 (It why we have the "ValueError: invalid literal for int() with base 10" error). So i check the number of " . " instead (because ipv4 only have 4 points)

**Comment by thomas-mangin** [comment]
Ah ! yes, sorry I thought you were sending a '\n' not writing it.
