### ISSUE TITLE
Possible to query peer state?

### ISSUE THREAD

**Issue by sroytman** [Exa-Networks/exabgp#427]
Is it possible to learn a neighbor's peering state through the CLI in ExaBGP 3.4.16?  The events labelled "neighbor-changes" in https://github.com/Exa-Networks/exabgp/wiki/Controlling-ExaBGP-:-API-for-received-messages are tantalizingly close to what I want, and the status must exist somewhere internally, but I don't see it reported in the output of "show neighbors" or elsewhere.  Please forgive me if I'm missing something obvious; I'm still digging through the code to see if I can find the answer for myself, but thought I'd send a message here as well in case there is a simple answer.

Thank you!

**Comment by thomas-mangin** [comment]
I am very very sorry - no it is not possible atm - it is really really missing.

**Comment by sroytman** [comment]
Would adding the following code to the 3.4.16 command.py do what I expect?  I see established() returning True if either ['in'] or ['out'] has a state of ESTABLISHED.  ['in'] and ['out'] (from their names and the way they are used) in turn look like descriptions of incoming and outgoing requests to peer.  This seems like the right thing.

def show_neighbor_status (self, reactor, service, command):
        def callback ():
                for p in reactor.peers:
                        updown = reactor.peers[p].established()
                        updown_string = "UP" if updown else "DOWN"
                        reactor.answer(service, "%s : %s" % (p.split()[1], updown_string))
                        yield True
                reactor.answer(service,"done")

        reactor.plan(callback())
        return True

**Comment by sroytman** [comment]
(Well, that was ugly.  How about with code formatting.)

```
def show_neighbor_status (self, reactor, service, command):
    def callback ():
        for p in reactor.peers:
            updown = reactor.peers[p].established()
            updown_string = "UP" if updown else "DOWN"
            reactor.answer(service, "%s : %s" % (p.split()[1], updown_string))
            yield True
        reactor.answer(service,"done")

    reactor.plan(callback())
    return True
```

**Comment by thomas-mangin** [comment]
well, it looks like to would work as long as no signal was sent to reconfigure the neighbor so it should be more:
```
for peer_name in reactor.peers:
   peer = reactor.peer.get(peer_name,None)
   if not peer:
      continue
   state = peer.established()
   ....
```
If you were kind enough to:
   - update this code to make it a patch for both 3.4 and master
   - update the CHANGELOG on 3.4 and master to say you added the feature
I would pull .. otherwise I will do it but ... surely bit later ..

**Comment by thomas-mangin** [comment]
`show neighbor status` now reports the FSM state
