### ISSUE TITLE
Parsing without configuration

### ISSUE THREAD

**Issue by iLLogical2007** [Exa-Networks/exabgp#430]
It would be interesting if you could use the parsing (to JSON) capabilities of hexadecimal formatted messages without any configuration files. This way it would be way more easy to analyze them.

**Comment by thomas-mangin** [comment]
The issue is that the encoding depends on what features were negotiated between the peers, so a single binary blob cam sometimes be understood differently.

This is why ExaBGP let you specify what you expect to be the setup with a neighbor and then decode the data.

You can use command such as exabgp `config-file` --decode `HEX_MESSAGE` to decode a packet.
Taking an example from issue 381:

```
./sbin/exabgp qa/conf/flow.conf -d --decode "ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 00 32 02 00 00 00 1b 80 0e 09 00 01 85 00 00 03 0c 80 0c 40 01 01 02 c0 10 08 80 06 00 00 00 00 00 00"
[...]
Fri, 26 Feb 2016 09:24:22 | INFO     | 46325  | parser        | decoded update 1 flow fragment first-fragment|last-fragment origin incomplete extended-community rate-limit 0
Fri, 26 Feb 2016 09:24:22 | INFO     | 46325  | parser        | update json { "exabgp": "3.4.0", "time": 1456478662, "host" : "Thomas.local", "pid" : "46325", "ppid" : "42095", "counter": 1, "type": "update", "neighbor": { "ip": "127.0.0.1", "address": { "local": "127.0.0.1", "peer": "127.0.0.1"}, "asn": { "local": "1", "peer": "1"}, "message": { "update": { "attribute": { "origin": "incomplete", "extended-community": [ 9225060886715039744 ] }, "announce": { "ipv4 flow": { "none": { "flow-11": { "fragment": [ "first-fragment|last-fragment" ], "string": "flow fragment first-fragment|last-fragment" } } } } } }} }
```

Is it what you were looking for ?

**Comment by iLLogical2007** [comment]
Yes, but more universal. I've many BGP setups with many BGP messages in a single PCAP file and I'm trying to parse them. Wireshark is capable of parsing the raw BGP packet without any configuration parameter of the origin BGP setup.

I don't understand what could be decoded differently. Do you have an example for that scenario?

**Comment by thomas-mangin** [comment]
I know the maintainer of the wireshark code and he uses heuritics. No I do not have any example at hand and explaining it would require going into the details of the NLRI encoding but if you want to read https://tools.ietf.org/html/draft-ietf-idr-add-paths-15, it should become clear how it can happen.
