### ISSUE TITLE
Can I add a route with a label stack through the add route API?

### ISSUE THREAD

**Issue by russellkelly** [Exa-Networks/exabgp#431]
Hi Have the following options in the configuration file;

neighbor 10.164.2.53 {
group-updates true;
local-address 10.164.1.77;
router-id 10.164.1.77;
local-as 64512;
peer-as 64512;
family {
ipv4 nlri-mpls;
}
static {
route 10.255.255.8/32 {
next-hop 10.164.1.77;
label [ 800005 800007 800006 800008 ];

But I would like to add the next hop and label stack in the add route API.  I can add the next-hop and community, but not the label stack.

Is this supported?

**Comment by thomas-mangin** [comment]
No idea without reading at the RFC and recalling what I done :p If this is valid it should be supported, if not, please show me the static route you want to generate and I will look at why it does not work - also are you using 3.4 or master ?

**Comment by russellkelly** [comment]
Thanks Thomas

I am adding the following address family and attributes to the route (highlighted below)

family {
ipv4 nlri-mpls;
}
static {
route 10.255.255.8/32 {
next-hop 10.164.1.77;
label [ 800005 800007 800006 800008 ];
}
}

This works just fine in the config options (per group or per neighbor), but if I try to use the “announce route” option with the same attribute in a .py file it doesn’t work.  No route is added.  If I just try the normal ipv4 route with community and next hop the add route works fine.

I am using 3.4.16 as with the 4.0.0 version I was getting errors with groups being configured at “root”  not sure what they meant, but it seemed the formats had changed and I could find any information on this.

Is this the information you need?

Cheers
Russ

**Comment by thomas-mangin** [comment]
Can I have the exact 'announce' line you are attempting please so I can try to reproduce.

**Comment by russellkelly** [comment]
Here’s the .py file.



from sys import stdout
from time import sleep

messages = [
‘announce route 10.255.255.8/32 next-hop 10.164.1.77 label [ 800005 800007 800006 800008 ]‘
]

sleep(5)

#Iterate through messages
for message in messages:
    stdout.write( message + '\n')
    stdout.flush()
    sleep(1)

#Loop endlessly to allow ExaBGP to continue running
while True:
    sleep(1)
~
~

**Comment by thomas-mangin** [comment]
Thank you - will replicate and fix.

**Comment by thomas-mangin** [comment]
Hello @russellkelly - you did not provide the configuration you used for this program. Can I please have it too. Thanks.

**Comment by russellkelly** [comment]
Hi Thomas,

Is this what you’re looking for?

config file

neighbor 10.164.2.54 {
group-updates true;
local-address 10.164.1.77;
router-id 10.164.1.77;
local-as 64512;
peer-as 64512;
family {
ipv4 nlri-mpls;
}
process addroutes {
run /usr/bin/python add-route.py;
}
}


Here is the add-route.py file

add-route.py

from sys import stdout
from time import sleep

messages = [
‘announce route 10.255.255.8/32 next-hop 10.164.1.77 label [ 800005 800007 800006 800008 ]‘
]

sleep(5)

#Iterate through messages
for message in messages:
    stdout.write( message + '\n')
    stdout.flush()
    sleep(1)

#Loop endlessly to allow ExaBGP to continue running
while True:
    sleep(1)
~
~

**Comment by thomas-mangin** [comment]
Seems to work 3.4.16
```
Fri, 24 Jun 2016 11:54:06 | INFO     | 5202   | reactor       | New peer setup: neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open
Fri, 24 Jun 2016 11:54:06 | INFO     | 5202   | configuration | Loaded new configuration successfully
Fri, 24 Jun 2016 11:54:06 | INFO     | 5202   | processes     | Forked process addroutes
Fri, 24 Jun 2016 11:54:07 | INFO     | 5202   | processes     | Command from process addroutes : announce route 10.255.255.8/32 next-hop 10.164.1.77 label [ 800005 800007 800006 800008 ]
Fri, 24 Jun 2016 11:54:07 | INFO     | 5202   | reactor       | Route added to neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open : 10.255.255.8/32 next-hop 10.164.1.77 label [ 800005 800007 800006 800008 ]
Fri, 24 Jun 2016 11:54:06 | INFO     | 5202   | reactor       | New peer setup: neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open
Fri, 24 Jun 2016 11:54:06 | INFO     | 5202   | configuration | Loaded new configuration successfully
Fri, 24 Jun 2016 11:54:06 | INFO     | 5202   | processes     | Forked process addroutes
Fri, 24 Jun 2016 11:54:07 | INFO     | 5202   | processes     | Command from process addroutes : announce route 10.255.255.8/32 next-hop 10.164.1.77 label [ 800005 800007 800006 800008 ]
Fri, 24 Jun 2016 11:54:07 | INFO     | 5202   | reactor       | Route added to neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open : 10.255.255.8/32 next-hop 10.164.1.77 label [ 800005 800007 800006 800008 ]Fri, 24 Jun 2016 11:54:06 | INFO     | 5202   | reactor       | New peer setup: neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open
Fri, 24 Jun 2016 11:54:06 | INFO     | 5202   | configuration | Loaded new configuration successfully
Fri, 24 Jun 2016 11:54:06 | INFO     | 5202   | processes     | Forked process addroutes
Fri, 24 Jun 2016 11:54:07 | INFO     | 5202   | processes     | Command from process addroutes : announce route 10.255.255.8/32 next-hop 10.164.1.77 label [ 800005 800007 800006 800008 ]
Fri, 24 Jun 2016 11:54:07 | INFO     | 5202   | reactor       | Route added to neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open : 10.255.255.8/32 next-hop 10.164.1.77 label [ 800005 800007 800006 800008 ]Fri, 24 Jun 2016 11:54:06 | INFO     | 5202   | reactor       | New peer setup: neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open
Fri, 24 Jun 2016 11:54:06 | INFO     | 5202   | configuration | Loaded new configuration successfully
Fri, 24 Jun 2016 11:54:06 | INFO     | 5202   | processes     | Forked process addroutes
Fri, 24 Jun 2016 11:54:07 | INFO     | 5202   | processes     | Command from process addroutes : announce route 10.255.255.8/32 next-hop 10.164.1.77 label [ 800005 800007 800006 800008 ]
Fri, 24 Jun 2016 11:54:07 | INFO     | 5202   | reactor       | Route added to neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open : 10.255.255.8/32 next-hop 10.164.1.77 label [ 800005 800007 800006 800008 ]
```

generating
```
0000 002B 4001 0100 4002 0040 0504 0000 0064 800E 1A00 0104 040A A401 4D00 80C3 5050 C350 70C3 5060 C350 810A FFFF 08
```

decoded as 
```
Fri, 24 Jun 2016 11:55:39 | INFO     | 5271   | parser        | decoded update 1 10.255.255.8/32 next-hop 10.164.1.77 label [ 800005 800007 800006 800008 ] origin igp local-preference 100
Fri, 24 Jun 2016 11:55:39 | INFO     | 5271   | parser        | update json { "exabgp": "3.4.0", "time": 1466765739, "host" : "Thomas.local", "pid" : "5271", "ppid" : "942", "counter": 1, "type": "update", "neighbor": { "ip": "127.0.0.1", "address": { "local": "127.0.0.1", "peer": "127.0.0.1"}, "asn": { "local": "64512", "peer": "64512"}, "message": { "update": { "attribute": { "origin": "igp", "local-preference": 100 }, "announce": { "ipv4 nlri-mpls": { "10.164.1.77": { "10.255.255.8/32": { "label": [ 800005, 800007, 800006, 800008 ] } } } } } }} }
```

**Comment by russellkelly** [comment]
Hi Thomas - on this one it was my script I think.  This seems to work fine!! Thanks.

I have logged another separate issue w.r.t route refresh capabilities....

Thanks
Russ

**Comment by thomas-mangin** [comment]
Thank you for letting me know :-)
