### ISSUE TITLE
Dynamic BGP Peers

### ISSUE THREAD

**Issue by Ben-be** [Exa-Networks/exabgp#433]
Is there a plan to support dynamic BGP Peers at all? It is very handy when dealing with large networks. 

Example:
http://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/xe-3sg/irg-xe-3sg-book/irg-dynamic-neighbor.html
https://www.juniper.net/techpubs/en_US/junos11.4/topics/usage-guidelines/routing-configuring-bgp-groups-and-peers.html#id-13213602

**Comment by thomas-mangin** [comment]
Hi Ben, Yes, I already have an issue open for it... It is due for 4.0 which is currently moving at snail pace.
