### ISSUE TITLE
malformed JSON: quotes in a string should be converted

### ISSUE THREAD

**Issue by rob-barnes** [Exa-Networks/exabgp#434]
in version 3.4.16

The below is a message in JSON format, which contains a string value for the "reason" key, and this string values has embedded quotes around the number 2 ("2"). 
```
{ "exabgp": "3.4.8", "time": 1466620850, "host" : "miab1", "pid" : "28251", "ppid" : "28221", "counter": 50, "type": "state", "neighbor": { "ip": "10.120.1.1", "address": { "local": "10.101.0.1", "peer": "10.120.1.1"}, "asn": { "local": "65015", "peer": "65015"}, "state": "down", "reason": "out loop, peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]"} }
```
The above json can not be properly deserialized because of the incorrect delimiter expected after the doublequote preceding the 2 character in:

"out loop, peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]"

For objects that must be converted to JSON, consider:
changing or removing quotes
inserting \\ before quotes (better)
using a JSON serializer, such as json.dumps (best)

(also note the incorrect version key,value "exabgp": "3.4.8". I'll log another bug for that.)

**Comment by thomas-mangin** [comment]
Thank you for the report Rob. Fixed with:
https://github.com/thomas-mangin/exabgp/commit/d5529cb311d4592b7d7cae810fcd24fa7a38401c

**Comment by thomas-mangin** [comment]
(Yes I should create dict and then serialise them with JSON.dumps - it is something I want to do but not for today ..)

**Comment by rob-barnes** [comment]
There are some interesting speed considerations for json vs simplejson (for python2.7):
http://stackoverflow.com/questions/712791/what-are-the-differences-between-json-and-simplejson-python-modules
