### ISSUE TITLE
wrong version in JSON messages

### ISSUE THREAD

**Issue by rob-barnes** [Exa-Networks/exabgp#435]
There is a history of changing JSON message formats across past Exabgp versions, such that helper scripts need different message parse functions, depending on the version.
3.4.16 and 3.4.13 (and probably more) versions have 3.4.8 in the JSON messages, but this probably should be updated with each new version so that the version string in the JSON matches the actual Exabgp version that generates it.

{ "exabgp": "3.4.8", "time": 1466686912, "host" : "miab1", "pid" : "40032", "ppid" : "39855", "counter": 263079, "type": "update", "neighbor": { "ip": "10.200.20.1", "address": { "local": "10.101.0.1", "peer": "10.200.1.1"}, "asn": { "local": "65015", "peer": "65015"}, "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 14745, 22132, 14745, 2914, 9304, 4623 ], "confederation-path": [], "med": 1000, "local-preference": 25000, "community": [ [ 65000, 65015 ], [ 65050, 14745 ] ], "originator-id": "10.80.6.2", "cluster-list": [ "10.180.4.3" ] }, "announce": { "ipv4 unicast": { "10.120.2.5": { "10.77.15.0/24": { "path-information": "0.0.0.3" } } } } } }} }

**Comment by thomas-mangin** [comment]
The version is the version of ExaBGP when the format last CHANGED. So if you have some code developed with 3.4.8, you know that your upgrade will not cause you any worries, and that otherwise you need to read the CHANGELOG file.

**Comment by rob-barnes** [comment]
Oh, sorry Thomas! That does make sense! and thanks!
