### ISSUE TITLE
IPv6 flow-components not correctly added in nlri/flow.py

### ISSUE THREAD

**Issue by stoffi92** [Exa-Networks/exabgp#436]
Flow components in for IPv6 flowspec are not added when the same component exists in IPv4:

This is due to the assumption in nlri/flow.py (Line 431ff) that a component is either IPv4 or IPv6 (if / elif):
```
for content in dir():
	kls = globals().get(content,None)
	if not isinstance(kls,type(IComponent)):
		continue
	if not issubclass(kls,IComponent):
		continue
	if issubclass(kls,IPv4):
		_afi = AFI.ipv4
	elif issubclass(kls,IPv6):
		_afi = AFI.ipv6
	else:
```
For example destination-port is a component that exists for IPv4 and IPv6. The resulting decode list looks like this and does not allow to decode most of the IPv6-flow components:
```
{1: {1: 'prefix',
     2: 'prefix',
     3: 'numeric',
     4: 'numeric',
     5: 'numeric',
     6: 'numeric',
     7: 'binary',
     8: 'binary',
     9: 'binary',
     10: 'numeric',
     11: 'numeric',
     12: 'numeric'},
 2: {1: 'prefix', 2: 'prefix', 3: 'numeric', 11: 'numeric', 13: 'numeric'}}
```
Stoffi

**Comment by thomas-mangin** [comment]
Hum, could you please elaborate.

**Comment by stoffi92** [comment]
Hi Thomas,

Sorry for being not clear enough, cool code by the way - nice to read. We are currently doing a rather large flowspec interop test (Huawei, Cisco, Juniper, Alcatel). And noticed that a ipv6 flowspec Update that is sent by exabgp after traversing our test-network leads to a notification when received by exabgp again.

This is part of the output that we see during the issue on exabgp (hope that this is what you expected):

Fri, 24 Jun 2016 13:25:15 | DEBUG    | 19643  | timers        | peer fd50:2::1 ASN 65002   Receive Timer 89 second(s) left
Fri, 24 Jun 2016 13:25:15 | INFO     | 19643  | routes        | peer fd50:2::1 ASN 65002   << UPDATE (2) (61)  attributes origin igp as-path [ 65004 ] local-preference 100
Fri, 24 Jun 2016 13:25:15 | INFO     | 19643  | routes        | peer fd50:2::1 ASN 65002   << UPDATE (2) nlri  (30) fd50:4::/48 next-hop fd50:2::1
Fri, 24 Jun 2016 13:25:15 | DEBUG    | 19643  | wire          | session 1 outgoing fd50:2::2 / fd50:2::1            RECEIVED  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0061 02
Fri, 24 Jun 2016 13:25:15 | DEBUG    | 19643  | wire          | session 1 outgoing fd50:2::2 / fd50:2::1            RECEIVED  (194) 0000 004A 4001 0100 4002 0602 0100 00FD EC40 0504 0000 0064 900E 0032 0002 8500 002C 0180 00FD 5000 0400 00FF FF00 0000 0000 00FF FF02 8000 FD50 00FF 00FF 0000 0000 0000 0000 0004 0381 0605 8150
Fri, 24 Jun 2016 13:25:15 | INFO     | 19643  | message       | Peer       fd50:2::1 ASN 65002   << UPDATE
Fri, 24 Jun 2016 13:25:15 | INFO     | 19643  | parser        | parsing flag 40 type 01 (origin) len 01 payload  (2) 00
Fri, 24 Jun 2016 13:25:15 | INFO     | 19643  | parser        | parsing flag 40 type 02 (as-path) len 06 payload  (14) 0201 0000 FDEC
Fri, 24 Jun 2016 13:25:15 | INFO     | 19643  | parser        | parsing flag 40 type 05 (local-preference) len 04 payload  (9) 0000 0064
Fri, 24 Jun 2016 13:25:15 | INFO     | 19643  | parser        | parsing flag 90 type 0e (mp-reach-nlri) len 32 payload  (124) 0002 8500 002C 0180 00FD 5000 0400 00FF FF00 0000 0000 00FF FF02 8000 FD50 00FF 00FF 0000 0000 0000 0000 0004 0381 0605 8150
Fri, 24 Jun 2016 13:25:15 | INFO     | 19643  | parser        | parsing 2/133 nlri payload  (112) 2C01 8000 FD50 0004 0000 FFFF 0000 0000 0000 FFFF 0280 00FD 5000 FF00 FF00 0000 0000 0000 0000 0403 8106 0581 50
Fri, 24 Jun 2016 13:25:15 | DEBUG    | 19643  | wire          | session 1 outgoing fd50:2::2 / fd50:2::1            SENDING  (192) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 004D 0303 0A75 6E6B 6E6F 776E 2066 6C6F 7773 7065 6320 636F 6D70 6F6E 656E 7420 7265 6365 6976 6564 2066 6F72 2061 6464 7265 7373 2066 616D 696C 7920 35
Fri, 24 Jun 2016 13:25:15 | INFO     | 19643  | message       | Peer       fd50:2::1 ASN 65002   >> NOTIFICATION (3,10,"unknown flowspec component received for address family 5")
Fri, 24 Jun 2016 13:25:15 | INFO     | 19643  | network       | Peer       fd50:2::1 ASN 65002   out loop, peer reset, message [notification sent (3,10)] error[UPDATE message error / Invalid Network Field / unknown flowspec component received for address family 5]
Fri, 24 Jun 2016 13:25:15 | DEBUG    | 19643  | wire          | session 1 outgoing, closing connection from fd50:2::2 to fd50:2::1

I added some more debugging printouts in the library and figured out that it is unable to decode the destination-port flow component (Type 5 - the actual error message is a bit misleading) in case of an IPv6 flow. For IPv4 flows this works fine.

The flow-spec that we are sending via EXAbgp is:

      flow {
         route {
            match {
               source fd50:ff:ff::3/128/0;
               destination fd50:3:ff::ffff/128/0;
               destination-port =80; ### this is the first component that fails to get decoded by exabgp
               protocol tcp;
            }
            then {
               accept;
            }
         }
      }

This behaviour can be seen for all flow components are subclasses (flow-components) of IPv4 _and_ IPv6:

class FlowIPProtocol (IOperationByte,NumericString,IPv4): <- not for this component
class FlowNextHeader (IOperationByte,NumericString,IPv6): <- not for this component
class FlowAnyPort (IOperationByteShort,NumericString,IPv4,IPv6): <- but for this (because it is IPv4 and IPv6)
class FlowDestinationPort (IOperationByteShort,NumericString,IPv4,IPv6): <- also for this (because it is IPv4 and IPv6)
 
The array that is build from these classes in the lines following "for content in dir():" does not contain IPv6 components when they are also a subclass of IPv4 at the same time.

Christoph

**Comment by thomas-mangin** [comment]
Thank you very much, I can reproduce with
```
./sbin/exabgp qa/conf/flow.conf --decode "0000 004A 4001 0100 4002 0602 0100 00FD EC40 0504 0000 0064 900E 0032 0002 8500 002C 0180 00FD 5000 0400 00FF FF00 0000 0000 00FF FF02 8000 FD50 00FF 00FF 0000 0000 0000 0000 0004 0381 0605 8150"
```

**Comment by thomas-mangin** [comment]
Hopefully the code will now behave as should. Thank you for reporting this issue.
