### ISSUE TITLE
how do exabgp annouce route to the specific neighbors with local ip address sperately?

### ISSUE THREAD

**Issue by liuheyang** [Exa-Networks/exabgp#437]
hi,
   in my application, there is two bgp session: exabgp server has two ip address, and the neighbor device only one ip address, how exabgp annouce route to the two neighbors ?
expecting your help
best regards 
thanks

**Comment by thomas-mangin** [comment]
@liuheyang - can you please be more precise ? you can announce different routes per peer using the static block within the neighbor block or via the API using "announce IP,IP,IP route ..." for example

**Comment by liuheyang** [comment]
for example,  command like, neighbor 192.188.2.31 announce route 12.1.2.1 next-hop 192.188.2.111 community [31:1], the announcement has the neighbor address, how can i specified the local ip address, for example,  neighbor 192.188.2.31 local-ip 192.188.2.2  announce...

**Comment by thomas-mangin** [comment]
@liuheyang the answer should be there 
https://github.com/Exa-Networks/exabgp/wiki/Controlling-ExaBGP-:-limiting-diffusion-of-routes

If not please let me know so we can update the documentation with the information you need.

**Comment by liuheyang** [comment]
it is what i need, thanks, i will close the isssue
