### ISSUE TITLE
Flow-Route config "Protocol" component does only allow a list

### ISSUE THREAD

**Issue by stoffi92** [Exa-Networks/exabgp#438]
Hi Thomas,

In 3.4 the flow-route protocol statement (flow component) is treated as a list. While the standard allows all kinds of ranges exactly like it does for port numbers.

This is not really a bug - we just noticed that it is impossible to have a configuration like below to announce a route with protocol matching like it works with ports (ranges of protocols):

For example:

```
     route {
       match {
            source 10.12.255.0/24;
            destination 10.11.255.0/24;
            source-port =3 =4 >200&<210;
            protocol =3 =4 >200&<210;
       }
       then {
         accept;
       }
```

in the configuration/ancient.py we hacked this in order to have the protocol be treated like ports... (with all the drawbacks): 

```
    def _flow_route_protocol (self, scope, tokens):
            return self._flow_generic_condition(scope,tokens,FlowIPProtocol)
```

however this may break named-protocol configurations like this (we did not test):

```
         protocols =tcp =udp >tcp&<udp
```

Many of the other flow components are also treated as a list which may be perfectly fine for most applications. But may not allow to use the full flexibility of the RFC itself.

Cheers

Christoph

**Comment by thomas-mangin** [comment]
Good point. I will modify the code on master to allow this, but will most likely not backport it to 3.4 as I have not seen any user requirement and 3.4 is our stable branch and I am trying to not introduce any surprise.

**Comment by stoffi92** [comment]
Today a ran over this again since I needed this for our production environment that takes flowspec-configurations from a commercial platform, transforms it and announces the result via exaBGP. Since the commercial plattform allows most of the flow-components to use ranges (as allowed in the RFC) I patched exaBGP 3.4 to do the same. BTW the original issue only included "protocol" as flow-components that should get this enhancement. But in fact a more complete list is:

- protocol (for IPv6 next-header)
- icmp-type
- icmp-code

This is just for the record in order to have a possible future patch also include icmp-type and icmp-code as "ranges"

Christoph

**Comment by thomas-mangin** [comment]
If you have more than one value to an option it should be between `[ ]` if so I would expect things to work.

**Comment by stoffi92** [comment]
(this is actually an update on a rather old enhancement ticket - you may have missed this) - I was just adding 2 more flow-components that seem to suffer from the same limitations. I understand that I could possibly have a match of multiple "protocols" "icmp-types" ... But I talk about ranges (something that the flow-spec rfc allows) like:

protocol =tcp =udp >tcp&<udp;

or 

protocol >=10&<=30;

(you may replace protocol by icmp-type, -code).  The flowspec protocol, icmp-type, icmp-code encoding is equal to the port, src-port, dst-port encoding but with protocol, icmp-type, icmp-code those ranges are not supported by exaBGP while for the port components exaBGP supports these ranges.

**Comment by thomas-mangin** [comment]
AFAIR (as I did not check) this was fixed on master (for all type) but will not be back ported to 3.4.
Does that sounds right ?

**Comment by stoffi92** [comment]
Hi,

I was just reading the master. It seems that you are right. It was fixed, but only for protocol  and not for icmp-type and icmp-code (the ICMP components were originally not in this ticket, I just added these yesterday - actually I should have opened another issue, but since this one was still open I did not even read the current master. sorry):

from exabgp/lib/exabgp/bgp/message/update/nlri/flow.py:

class FlowIPProtocol (IOperationByte,NumericString,IPv4):

but 

class FlowICMPType (IOperationByte,**BinaryString**,IPv4,IPv6):
class FlowICMPCode (IOperationByte,**BinaryString**,IPv4,IPv6):

Since we are currently actively working on an updated version of rfc5575 -> ietf-idr-rfc5575bis I am also looking into many of the different flow-spec implementations and exaBGP is really **the** primary tool I use for reference since it already (sometimes with patches) is the most flexible implementation.

**Comment by thomas-mangin** [comment]
I could not run the code to check tonight but looking at the code logic there should be no difference between a BinaryString and NumericString ... Going to have to run tests

**Comment by thomas-mangin** [comment]
Oh - sorry it could be a mis-understanding of the RFC on my side ... BinaryString allow negation operation but not range comparaison ... Should the patch to just change this to NumericString ?

**Comment by thomas-mangin** [comment]
and `FlowFragment` be a BinaryString ?

**Comment by thomas-mangin** [comment]
Reading https://tools.ietf.org/html/draft-loibl-bacher-idr-flowspec-clarification-00 - You should have pointed me that way 😉

**Comment by thomas-mangin** [comment]
There is two class `BinaryString` and `NumericString` as it made no sense to allow range comparaison to binary field such as `TCPFlag`. It seems that in the case of ICMP Code both could/should be allowed.

The right solution may be to have the creation of a new class which allows both binary and range comparaison .. and a correct review of what is what to make sure it makes logical sense ...

I could have allowed "everything everywhere" but, back in the days, I had crashed my M7i enough time when I first developed the feature to know better and tried to make sure users could not input something harmful in prod.

**Comment by stoffi92** [comment]
Yes. ICMP-type and ICMP-code are encoded exactly like port numbers. -> NumericString (always!)
Type 9 - TCP flags and Type 12 - Fragment: are encoded as BinaryString (defined on page 8 of rfc5575) - no comparison available. (always)

No third type required.

Since I am reading all your messages as they come in (chat-like feeling) :-) ...

We abondend flowspec-clarification-00 already and merged everything into https://www.ietf.org/id/draft-ietf-idr-rfc5575bis-01.txt

There are only 2 types of operators. The one you call "NumericString" (rfc5575bis sec 4.2.3.) and the other that you call "BinaryString" (rfc5575bis sec 4.2.9. only used for type-9 and type-12) 

The new rfc5575bis also x-references from each flow-type to the section where the operator is defined. 

There are still ways to produce a BGP-notification with a perfectly well flow-spec update. We worked on an interop paper:
http://p4.tix.at/~cl/fs/loibl-bacher-bgp-flowspec-interop-012017.pdf

**Comment by thomas-mangin** [comment]
Thank you for providing me all the information to not have to re-read 5575 tonight :-)
Not sure the full fix was back ported in 3.4 but what is in this thread was and master should be good.

I will read the new draft and PDF (so please do not close the issue - so I do not forget :wink:)

**Comment by thomas-mangin** [comment]
(note to self, need to be able to decode own generated string with true and false)

**Comment by stoffi92** [comment]
I see that you already found our optimised operator definition in the draft. Our rfc5575bis draft requires hardly any changes to exabgp. If you like I will write a short summary for you the following days. It is supposed to be 100% compatible with the current rfc5575 but clearly defines some previously undefined corner cases.

**Comment by thomas-mangin** [comment]
It would be much appreciated.

**Comment by stoffi92** [comment]
Opened a new case for the promised rfc5575bis summary (since this is unrelated to this case): #612

**Comment by thomas-mangin** [comment]
true and false implemented / tested - closing this issue and will continue work on 612
