### ISSUE TITLE
4s lag on restarting a peering session

### ISSUE THREAD

**Issue by doddt** [Exa-Networks/exabgp#440]
If I trigger a config reload, exabgp will shut down peering sessions for a peers whose configuration has changed (for instance, if I add/delete an address family). Testing shows a 4s gap between the terminating Notification message and the Open message to initiate a new session. Why so long?

I'm running 3.4.16.

**Comment by thomas-mangin** [comment]
Long to explain, it is due to the reactor - it could be optimised. if you look I am using co-routines as async function (async did not exist when I wrote this code) and depending on what I return (true or false), I wait for a full reactor loop (which sleeps one second betwen loop) to continue

**Comment by doddt** [comment]
I'd be interested in testing that change when it's available. Thanks!

**Comment by thomas-mangin** [comment]
I had a quick look at the code and the reason for the delay is not obvious. 
You can change the environment value exabgp_reactor_speed to be 0.1 as a 'quick fix' until I can investigate this more.

**Comment by doddt** [comment]
Setting exabgp.reactor.speed to 0.1 gives a ten-fold improvement: the lag is now a little under 0.4s on average. This is much better but still not ideal. Thanks.

**Comment by thomas-mangin** [comment]
You can reduce the value further, all it does is reduce the idle sleep time, so the reactor will run more often but all it will check is if there was any new data on the filedescriptors with poll - so the CPU overhead should really be minimal.

**Comment by doddt** [comment]
Thanks. I was wondering what the implications of even smaller values would be. I need to figure out how fast we need this to be. It's pretty likely we'll want a smaller value.

**Comment by thomas-mangin** [comment]
This was fixed in the latest master on the way to 4.0.1 - it flies - however while working very well for small numbers of peers the code does not have much testing for large numbers (but I see no reason for it to not behave).
