### ISSUE TITLE
Routes are resent unnecessarily on config reload

### ISSUE THREAD

**Issue by doddt** [Exa-Networks/exabgp#441]
On a config reload, routes are resent to existing peers that have not been modified. Why is this done? Also, the announcements/withdrawals are not packaged efficiently: they are spread across several packets in a haphazard fashion when they could be sent in a single packet.

I'm running 3.4.16.

**Comment by thomas-mangin** [comment]
reload: 

It should not be done, the peer should be ignored ... Somewhere a comparaison test is failing.

packets:

You should have a warning when ExaBGP starts ..
```
Tue, 28 Jun 2016 16:52:20 | WARNING  | 10787  | configuration | --------------------------------------------------------------------------------
Tue, 28 Jun 2016 16:52:20 | WARNING  | 10787  | configuration | group-updates not enabled for peer 10.0.0.3, it surely should, the default will change to true soon
Tue, 28 Jun 2016 16:52:20 | WARNING  | 10787  | configuration | --------------------------------------------------------------------------------
```
you need to enable group-updates for the peer.

It is not hapharzard .. but yes, it is not not ordered.

**Comment by doddt** [comment]
Thanks for the your quick response. I enabled group-updates (and disabled auto-flush for good measure), but he's still resending routes on reload. Here're the pertinent log messages:
---
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration | parsing | neighbor      | '}'
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration | neighbor 10.8.9.52 {
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   description "r10";
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   router-id 10.8.22.14;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   local-address 10.8.22.14;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   local-as 5000;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   peer-as 5000;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   hold-time 180;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   manual-eor false;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   group-updates: True;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   auto-flush: false;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   adj-rib-out: true;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   ttl-security: ;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   capability {
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |     asn4 enable;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |     route-refresh enable;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |     graceful-restart disable;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |     add-path disable;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |     multi-session disable;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |     operational disable;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |     aigp disable;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   }
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   family {
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |     inet4 unicast;
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   }
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   process {
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |   }
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration | }
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration |
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration | parsing | group         | 'process' 'my-shim' '{'
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration | parsing | process       | 'run' '"/usr/local/bin/python /home/tdodd/test.py"' ';'
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration | parsing | process       | '}'
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | configuration | parsing | group         | '}'
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | reactor       | Peer definition identical, updating peer routes if required for neighbor 10.8.9.52 local-ip 10.8.22.14 local-as 5000 peer-as 5000 router-id 10.8.22.14 family-allowed in-open
Tue, 28 Jun 2016 16:10:27 | WARNING  | 28479  | configuration | Loaded new configuration successfully
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | processes     | process already running
Tue, 28 Jun 2016 16:10:27 | INFO     | 28479  | message       | Peer       10.8.9.52 ASN 5000    >> 4 UPDATE(s)
---

Those four updates are my two static and two dynamic routes. Am I still missing something?

**Comment by thomas-mangin** [comment]
I wrote: reload: It should not be done, the peer should be ignored ... Somewhere a comparaison test is failing.

And classified this as a bug ..

**Comment by thomas-mangin** [comment]
This still need fixing .. will try to find time to do it. Sorry for the delay!

**Comment by doddt** [comment]
Thanks Thomas. Fixing this would enable some significant performance improvements on our side because we won't have to go through the child process any more to avoid sending duplicate announcements. It makes a big difference for large numbers of routes.

**Comment by thomas-mangin** [comment]
It is on my todo but as I have been  swamped recently and it is unlikely to be a quick fix and as you seems to be able to cope, I have not yet handled it ... It is not forgotten .. Just need to find the few hours I need ..

**Comment by doddt** [comment]
Thanks for the update. Yes we can cope, but looking forward to the fix. :-)

**Comment by thomas-mangin** [comment]
AFAIK this was fixed on master. Could you please confirm if not.

**Comment by brijohn** [comment]
@thomas-mangin Was this actually fixed? 

When I tested this last week it was still resending all routes for peers that were not changed during reload.

**Comment by thomas-mangin** [comment]
then not .. I thought one your patch fixed it..

**Comment by thomas-mangin** [comment]
rewrote half the RIB code .. hopefully this was handled with the changes but a test for this would be good ...

**Comment by thomas-mangin** [comment]
Nope - looking into the code the reload does force always the routes to be resent.

**Comment by thomas-mangin** [comment]
Note to self, as after investigation it may take me some time to implement the solution:

On peer update, we have two lists of routes to compare.

Checking for an element in a list is O(n) so with large configuration this part of the code could take ages. As it is not async, it could cause BGP sessions to drop. The solution to prevent this was to mark all current routes as withdrawn, and then re-announce all the routes. Hammer - but works.

On 3.4, the announce after the withdraw would cause the withdraw to be removed and only the announce would be sent. We found out that this optimisation could cause issue, so on master, all the route will be explicitly withdrawn and then re-announced. 

This optimisation could be re-considered for this case - re-adding the code but only enabling it when we are doing this double loop work.

One solution would be to have the routes in the peer as dict and not list. Then take all the new routes and remove them from the old dict(). What would be left would be the routes to remove.
If a route was removed then the route does not need to be announced. The route not removed then would make our announcement.

That solution should be fast enough ..

**Comment by 4mig4** [comment]
What is the status of this ?

**Comment by thomas-mangin** [comment]
the label is "fixed need testing" .. so AFAIK should work.

**Comment by thomas-mangin** [comment]
closing as due to the lack of feedback.
