### ISSUE TITLE
OPEN message graceful restart decoding issue

### ISSUE THREAD

**Issue by florinz** [Exa-Networks/exabgp#442]
Debugging a issue in ExaBGP with graceful restart it seems that the Address family flag (which indicates that the routes for a address family were preserved) is not correctly decoded in the open message when a Graceful restart capable peer re-sends the open message.

After making sure that the neighbour sends the correct data and its not getting corrupted anywhere I managed to tracked down the issue to the method _unpack_capability_ under the file _graceful.py_ in the open capability folder of messages (i.e. exabgp/bgp/message/open/capability/graceful.py). [https://github.com/Exa-Networks/exabgp/blob/4.0/lib/exabgp/bgp/message/open/capability/graceful.py](https://github.com/Exa-Networks/exabgp/blob/4.0/lib/exabgp/bgp/message/open/capability/graceful.py)

Line 79 where the flag_family is being extracted from the message binary it seems that the address family offset is being decoded instead of the flag offset

Here is the block of code that I am refering to.
```python
while data:
			afi = AFI.unpack(data[:2])
			safi = SAFI.unpack(data[2])
			flag_family = ord(data[0])
```

The fix is very trivial and it just involves changing the flag_family to use data offset 3 (the next 8 bits after the previous 2 byte AFI and 1 byte SAFI).

```python
while data:
			afi = AFI.unpack(data[:2])
			safi = SAFI.unpack(data[2])
			flag_family = ord(data[3])
```

I am not quite sure if this was intentional however I can't see any reason to decode the address family instead of the flag when parsing the graceful restart capability. This issue seems to be present in both the master branch and the 4.0.

**Comment by thomas-mangin** [comment]
Thank you, it is a typo - well spotted and thank you for the fix.

**Comment by thomas-mangin** [comment]
let me know if it does indeed fix the issue for you so I can close the issue.

**Comment by florinz** [comment]
Hi, I have re-tested the changes made. The decode seems to be working fine now. Thanks.

**Comment by thomas-mangin** [comment]
Great :-) Once again thanks for the report and the solution 👍
