### ISSUE TITLE
issue on master with the announce/withdraw command

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#443]
Reported by mail:

If I announce for example the following route :
`announce route 10.55.130/24 next-hop 100::1 community [ 15879:666  ]`

and do a 'show routes', I can see the prefix :
`neighbor 213.133.37.226 10.55.130.0/24 next-hop 100::1`
`neighbor 213.133.37.227 10.55.130.0/24 next-hop 100::1`

However, I'm unable to withdraw it....

I tried for example :

`withdraw 10.55.130.0/24`
`withdraw 10.55.130.0/24 next-hop 100::1`

But the route simply stays....  I can only restart ExaBGP to clear it.

Here some output from the log :

```
Thu, 30 Jun 2016 17:23:06 3473   processes     Command from process jafar-exabgp-tcpserver : withdraw route 10.55.130.0/24
Thu, 30 Jun 2016 17:23:06 3473   reactor       callback | handling 'withdraw route 10.55.130.0/24' with withdraw_route
Thu, 30 Jun 2016 17:23:06 3473   reactor       callback | installing withdraw_route
Thu, 30 Jun 2016 17:23:06 3473   reactor       callback | running
Thu, 30 Jun 2016 17:23:06 3473   configuration . route            | '10.55.130.0/24'
Thu, 30 Jun 2016 17:23:06 3473   reactor       route removed from neighbor 213.133.37.226 local-ip 213.133.37.229 local-as 65099 peer-as 15879 router-id 213.133.37.229 family-allowed in-open, neighbor 213.133.37.227 local-ip 213.133.37.229 local-as 65099 peer-as 15879 router-id 213.133.37.229 family-allowed in-open : 10.55.130.0/24
Thu, 30 Jun 2016 17:23:06 3473   reactor       responding to jafar-exabgp-tcpserver : done
Thu, 30 Jun 2016 17:23:06 3473   reactor       callback | removing
Thu, 30 Jun 2016 17:23:07 3473   reactor       performing dynamic route update
Thu, 30 Jun 2016 17:23:07 3473   reactor       updated peers dynamic routes successfully
Thu, 30 Jun 2016 17:23:16 3473   processes     Command from process jafar-exabgp-tcpserver : show routes
Thu, 30 Jun 2016 17:23:16 3473   reactor       callback | handling 'show routes' with show_routes
Thu, 30 Jun 2016 17:23:16 3473   reactor       callback | installing show_routes
Thu, 30 Jun 2016 17:23:16 3473   reactor       callback | running
Thu, 30 Jun 2016 17:23:16 3473   reactor       responding to jafar-exabgp-tcpserver : neighbor 213.133.37.226 10.55.131.0/24 next-hop 213.133.37.229
Thu, 30 Jun 2016 17:23:16 3473   reactor       responding to jafar-exabgp-tcpserver : neighbor 213.133.37.226 10.55.130.0/24 next-hop 100::1
Thu, 30 Jun 2016 17:23:16 3473   reactor       callback | running
Thu, 30 Jun 2016 17:23:16 3473   reactor       responding to jafar-exabgp-tcpserver : neighbor 213.133.37.227 10.55.131.0/24 next-hop 213.133.37.229
Thu, 30 Jun 2016 17:23:16 3473   reactor       responding to jafar-exabgp-tcpserver : neighbor 213.133.37.227 10.55.130.0/24 next-hop 100::1
Thu, 30 Jun 2016 17:23:16 3473   reactor       callback | running
Thu, 30 Jun 2016 17:23:16 3473   reactor       responding to jafar-exabgp-tcpserver : done
Thu, 30 Jun 2016 17:23:16 3473   reactor       callback | removing
```

The next-hop specified is not valid in this case obviously, because it's an IPv6 next-hop.
So I think either 'announce' should deny it, or withdraw should function.
(Not 100% sure if the IPv6 next-hop can have a valid use case for an IPv4 prefix)

Also, the reason I came across this issue is because I did some testing with advertising IPv6 prefixes to IPv4 neighbors (family inet + family inet6),
and was struggling with the next-hop to specify in the announcement in this case...

If I specify the IPv4-address or self, the session with the neighbor (JunOS) seems to break.

Any suggestions on how to accomplish this ? (it's an eBGP session in this case for that matter)

I also still haven't found a solution that if a child process is terminated/killed,
that ExaBGP 4.x does not restart it. In 3.x, it simply did that.
I fiddled with 'respawn = true' for exabgp.api, but it just does not restart.

Same thing is that if I kill my own 'tcpserver' process (written in Perl),
that process becomes defunct.

**Comment by MadDog2K** [comment]
Announcing and withdrawing IPv6 routes over IPv4 session seems to work fine if we specify the next-hop as an IPv4 mapped address, eg. ::ffff:<self ip>

I'll retest again with 'self' as the next-hop, but IIRC that doesn't do the right thing in this case

Possible fix would perhaps be to check if prefix has a : in it (or better: is a valid IPv6 prefix) and if the neigbor is an IPv4 address, make sure the specified or self IP is converted from IPv4 to the IPv4 mapped address

**Comment by thomas-mangin** [comment]
Test 2 of ./qa/bin/conversation is also failing, I believe it is related. So I will fix it first and then look into this one.
`self` was added to help a friend and somehow now I regret the feature (as it is was as straight forward as expected). I will try to get this done this week-end.

**Comment by thomas-mangin** [comment]
this fixes the issue with a withdraw without next-hop 
https://github.com/Exa-Networks/exabgp/commit/5958a738f4ad69b6709a780f1264671f57d8e29e

**Comment by MadDog2K** [comment]
Hi Thomas,

I've just downloaded the latest from git and run it, but if I install this route :

neighbor 10.86.2.218 10.55.129.0/24 next-hop 100::1

unfortunately I still can't withdraw it. Also my BGP session with the Juniper peer is flapping.

Jul  2 20:52:36  olive rpd[1661]: bgp_read_v4_update:10590: NOTIFICATION sent to 10.86.2.221 (External AS 65099): code 3 (Update Message Error) subcode 3 (missing well known attribute) value 3, Reason: peer 10.86.2.221 (External AS 65099) UPDATE no next hop found


Sat, 02 Jul 2016 20:53:04 6048   processes     Command from process jafar-exabgp-tcpserver : withdraw route 10.55.129.0/24
Sat, 02 Jul 2016 20:53:04 6048   reactor       callback | handling 'withdraw route 10.55.129.0/24' with withdraw_route
Sat, 02 Jul 2016 20:53:04 6048   reactor       callback | installing withdraw_route
Sat, 02 Jul 2016 20:53:04 6048   reactor       callback | running
Sat, 02 Jul 2016 20:53:04 6048   configuration . route            | '10.55.129.0/24'
Sat, 02 Jul 2016 20:53:04 6048   reactor       route removed from neighbor 10.86.2.218 local-ip 10.86.2.221 local-as 65099 peer-as 15879 router-id 10.86.2.221 family-allowed in-open : 10.55.129.0/24
Sat, 02 Jul 2016 20:53:04 6048   reactor       responding to jafar-exabgp-tcpserver : done
Sat, 02 Jul 2016 20:53:04 6048   reactor       callback | removing
Sat, 02 Jul 2016 20:53:05 6048   reactor       performing dynamic route update
Sat, 02 Jul 2016 20:53:05 6048   reactor       updated peers dynamic routes successfully
Sat, 02 Jul 2016 20:53:14 6048   processes     Command from process jafar-exabgp-tcpserver : show routes
Sat, 02 Jul 2016 20:53:14 6048   reactor       callback | handling 'show routes' with show_routes
Sat, 02 Jul 2016 20:53:14 6048   reactor       callback | installing show_routes
Sat, 02 Jul 2016 20:53:14 6048   reactor       callback | running
Sat, 02 Jul 2016 20:53:14 6048   reactor       responding to jafar-exabgp-tcpserver : neighbor 10.86.2.218 10.55.131.99/32 next-hop 10.86.2.221
Sat, 02 Jul 2016 20:53:14 6048   reactor       responding to jafar-exabgp-tcpserver : neighbor 10.86.2.218 10.55.129.0/24 next-hop 100::1
Sat, 02 Jul 2016 20:53:14 6048   reactor       callback | running
Sat, 02 Jul 2016 20:53:14 6048   reactor       responding to jafar-exabgp-tcpserver : neighbor 10.86.2.218 10.55.131.0/24 next-hop 10.86.2.221
Sat, 02 Jul 2016 20:53:14 6048   reactor       responding to jafar-exabgp-tcpserver : neighbor 10.86.2.218 fd00:89f:9999::9999/128 next-hop ::ffff:10.86.2.221
Sat, 02 Jul 2016 20:53:14 6048   reactor       callback | running
Sat, 02 Jul 2016 20:53:14 6048   reactor       responding to jafar-exabgp-tcpserver : neighbor 10.86.2.218 fd00:89f:9999::/48 next-hop ::ffff:10.86.2.221
Sat, 02 Jul 2016 20:53:14 6048   reactor       responding to jafar-exabgp-tcpserver : done
Sat, 02 Jul 2016 20:53:14 6048   reactor       callback | removing


Or was this commit not yet supposed to be the fix  ?

**Comment by thomas-mangin** [comment]
@MadDog2K two things:
- now that the syntax is accepted, you found the next issue - I will fix it.
- why are you sending an IPv4 route with an IPv6 next-hop - the fact that it works is a bug not a feature.

**Comment by thomas-mangin** [comment]
Ok - this patch should prevent the sending of invalid routes to your peer.
https://github.com/Exa-Networks/exabgp/commit/48ca518c7d64a5f2ac7b3017481d0b1be5e1e830

**Comment by MadDog2K** [comment]
@thomas-mangin 

I applied the new version and there seems to be no change in behaviour (the invalid next-hop is still send, hence flapping session)
But... the patch is code for withdraw route... should it not be within announce route,  to 'prevent' the sending of invalid route ? :)

The reason I'm sending invalid route is just that I came across this while testing.

Could you specify the exact command you want me to test for IPv6 and withdraw ?
You mean 'withdraw <IPv6-route>' ?

**Comment by thomas-mangin** [comment]
@MadDog2K 

I asked `why are you sending an IPv4 route with an IPv6 next-hop ? if it works, it is a bug not a feature.`
No RFC define this behaviour. The parser let you type this line but it does not mean that it can work !

**Comment by thomas-mangin** [comment]
@MadDog2K oh ! so the issue was not with the withdrawal ...
it would be nice if you could test that tho 😉

**Comment by MadDog2K** [comment]
@thomas-mangin 

Yes, it's a bug that we can send an IPv4 route with an IPv6 next-hop :)
It's probably easy to fix, as long as we know all the criteria that have to be met.

Eg. :

IPv4 route with IPv4 nexthop over IPv4 session : valid
IPv6 route with IPv6 nexthop over IPv6 session : valid

IPv4 route with IPv4 nexthop over IPv6 session : invalid??
IPv6 route with IPv4 nexthop over IPv4 session: Only allowed if the inet6 family is enabled for the IPv4 session, AND the next-hop is an IPv4 mapped address (::ffff:<ipv4-address>)



Well the withdrawal still does not work despite both patches applied ;)
I suspect it's because the session is constantly flapping, and perhaps the route can not be removed due to that.... because the neighbor is down at the point it wants to remove the route ?
(assumption)

**Comment by thomas-mangin** [comment]
IPv4 route with IPv4 nexthop over IPv4 session : valid
IPv6 route with IPv6 nexthop over IPv6 session : valid
IPv4 route with IPv4 nexthop over IPv6 session : valid
IPv6 route with IPv6 nexthop over IPv4 session: valid

The underlying protocol does not matter for BGP.

IPv6 route with IPv4 nexthop .. invalid
IPv6 route with IPv6 nexthop which can be mapped to IPv4: valid, it is simply an IPv6.

`Well the withdrawal still does not work despite both patches applied ;)
I suspect it's because the session is constantly flapping, and perhaps the route can not be removed due to that.... because the neighbor is down at the point it wants to remove the route ?
(assumption)`

It seems you issues are due to the incorrect use of families.

**Comment by MadDog2K** [comment]
@thomas-mangin 

this could be perhaps some lead. When the session is flapping due to sending an invalid route (out loop, peer reset, message [notification received (3,3)] error[UPDATE message error / Missing Well-known Attribute / 0x03]) then no routes seem to be able to get removed from ADJ-RIB-OUT

However, once we shut down the session on the remote neighbor and once exabgp has logged : 

out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]

then we _can_ withdraw any route from the ADJ-RIB-OUT, and after the session get's established again, the withdrawn routes do no appear on the remote neighbor (which is good)

So it seems it's a certain state of the neighbor / session, where withdraw is not working as expected ?

**Comment by thomas-mangin** [comment]
@MadDog2K I will improve the parsing the check the family when I change the configuration format - at the moment I can not really do it. Feel free to open a feature request for it.

For the other issue - I will look into what is different.

**Comment by MadDog2K** [comment]
@thomas-mangin 

Awesome! Hope it's something small...

And will open a feature req for the parsing after my vacation
