### ISSUE TITLE
Various issues when trying to use ipv4 nrli-mpls

### ISSUE THREAD

**Issue by russellkelly** [Exa-Networks/exabgp#445]
Hi There,

I am trying to get ExaBGP to force a route-refresh, because the "announce route" call does not seem to send the route if the advertised label path hasn't changed.

Firstly, is this expected that exabgp will not send the route is the next-hop and label attribute hasn't changed?  I have confirmed this on the router where the bgp process is not even receiving the route from exabgp if nothing changed.  It works fine if the label stack changes.

Secondly - is route-refresh meant to fix this?

If so, I am having trouble getting this working.  So far I have this in my configuration file:

```
group vMX {
        local-address 10.164.1.77;
        router-id 10.164.1.77;
        local-as 64512;
        peer-as 64512;
        group-updates;
        family {
                ipv4 nlri-mpls;
                }
                capability route-refresh {
                        route-refresh enable;
                }
                neighbor 10.164.2.52 {
                }
                neighbor 10.164.2.66 {
                }
                process addroutes {
                        run /usr/bin/python /home/rbutme/app.py;
                }
                process monitorroutes {
                        receive-routes;
                        parse-routes;
                        neighbor-changes;
                        peer-updates;
                        run /usr/bin/python /home/rbutme/dynamictrackobjects-v4.py;
                }
        }
```

When I try the following in dynamictrackobjects-v4.py:

```
                stdout.write('announce route-refresh 13.0.0.0/8 ipv4 nrli-mpls next-hop 172.20.2.2 label [800003 800005 800004 ' + str(label2_value) + ']' + '\n')
                stdout.flush()
                sleep(20)
```

I get the following error:

```
Fri, 01 Jul 2016 02:37:32 | INFO     | 15942  | network       | Connected to peer neighbor 10.164.2.52 local-ip 10.164.1.77 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open (out)
Fri, 01 Jul 2016 02:37:32 | INFO     | 15942  | network       | Connected to peer neighbor 10.164.2.66 local-ip 10.164.1.77 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open (out)
Fri, 01 Jul 2016 02:37:35 | INFO     | 15942  | processes     | Command from process monitorroutes : ROUTE: 192.168.1.30 => LABEL: 300480 
Fri, 01 Jul 2016 02:37:35 | WARNING  | 15942  | reactor       | Command from process not understood : ROUTE: 192.168.1.30 => LABEL: 300480
Fri, 01 Jul 2016 02:37:35 | INFO     | 15942  | processes     | Command from process monitorroutes : announce route-refresh 13.0.0.0/8 ipv4 nrli-mpls next-hop 172.20.2.2 label [800003 800005 800004 300480] 
Fri, 01 Jul 2016 02:37:35 | INFO     | 15942  | reactor       | Command could not parse flow in : announce route-refresh 13.0.0.0/8 ipv4 nrli-mpls next-hop 172.20.2.2 label [ 800003 800005 800004 300480 ]
```

This works fine with just the announce route stdout.write() call when the label stack changes (i.e. the link goes down then up again), but exabgp doesn't send the route again if the while loop spins around to it again and send it the same route to advertise...

Any suggestions?

Thanks
Russ

**Comment by thomas-mangin** [comment]
'announce route-refresh' clearly does not do what you believe it does. It is its own RFC. It does not announce any route, the syntax should be something like 'announce route-refresh ipv4 unicast', which will force a re-announcement of the routes in the ADJ-RIB-OUT to the peer again.

The index (which make a route unique) for a ipvpn route is:
```
	def index (self, negotiated=None):
		addpath = 'no-pi' if self.path_info is PathInfo.NOPATH else self.path_info.pack()
		mask = chr(len(self.rd)*8 + self.cidr.mask)
		return NLRI._index(self) + addpath + mask + self.rd.pack() + self.cidr.pack_ip()
```

So two routes with different labels are considered the same. I believe it is what the RFC specifies, so the second one is ignored. 

The best way to prevent this issue for you would be to disable the ADJ-RIB-OUT, using `adj-rib-out false` on the peer.

**Comment by thomas-mangin** [comment]
Also, I would define the process section BEFORE the peer. The parser in 3.4 is a bit temperamental and it may make a difference.

**Comment by russellkelly** [comment]
Thanks Thomas  - yes I misunderstood the refresh capability - and the adj-rib-out (false) fixed the update issue for routes that haven't changed.  

Unfortunately I am also using POST to update routes to the routers and see some odd issues, out lined below.

When I have adj-rib-out  disabled I post the following route:

neighbor 10.164.2.66 withdraw route 12.0.0.0/8 next-hop 192.168.1.23 label [ 800001 800005 800004 ]

This works fine.  I then post a more specific prefix route - this gets added fine (no traffic loss):

neighbor 10.164.2.66 announce route 12.0.1.0/24 next-hop 192.168.1.23 label [ 800008 800003 800005 ]

Now when I go to remove the more specific route with the command:

neighbor 10.164.2.66 withdraw route 12.0.1.0/24 next-hop 192.168.1.23 label [ 800008 800003 800005 ]

This removes ALL routes in the 12/8 prefix range and I get packet loss.  

Now with adj-rib-out set to true after a second or so the original 12/8 route gets added back in.    Not ideal.  But more of an issue is that with the adj-rib-out set to false the original route is flushed and never re-advertised.

Question:  Is there a config option to stop the 12/8 being removed from the RIB when I remove a more specific in the subnet range?  Surely it should just be flushing the more specific route anyway.. Correct?

Thanks for you ongoing help.

**Comment by thomas-mangin** [comment]
@russellkelly the message you see here in the log mean that some invalid route was sent to the peer - it causes the BGP session to bounce and all the route sent are then removed from the neighbor RIB.
Could you please run exabgp with the -d option , and paste here all the logs (or email them) so I can try to figure out what is wrong. 
Having a copy of the log from the other router for BGP would also be most useful.

**Comment by russellkelly** [comment]
Hi Thomas

I have got the logs from exabgp and from the router.  The router side is set to debug and is quite verbose.  I separated out each update below - and in the attached files they are separaed by ~10 return lines (the router is about 2 seconds behind the exabgp process).  Extracted messages are below:

Route Update 1 (13.0.0.0/8 from monitoring routes process):
-----------------------

Exabgp 

Sat, 02 Jul 2016 14:40:29 | INFO     | 10520  | processes     | Command from process monitorroutes : announce route 13.0.0.0/8 next-hop 172.20.2.2 label [800003 800005 800004 300864] 
Sat, 02 Jul 2016 14:40:29 | INFO     | 10520  | reactor       | Route added to neighbor 10.164.2.52 local-ip 10.164.1.77 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open : 13.0.0.0/8 next-hop 172.20.2.2 label [ 800003 800005 800004 300864 ]
Sat, 02 Jul 2016 14:40:29 | INFO     | 10520  | reactor       | Route added to neighbor 10.164.2.52 local-ip 10.164.1.77 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open, neighbor 10.164.2.66 local-ip 10.164.1.77 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open : 13.0.0.0/8 next-hop 172.20.2.2 label [ 800003 800005 800004 300864 ]


Router

Jul  2 14:40:31.003592 BGP RECV 10.164.1.77+54063 -> 10.164.2.66+179
Jul  2 14:40:31.003607 BGP RECV message type 2 (Update) length 63
Jul  2 14:40:31.003617 BGP RECV Update PDU length 63
Jul  2 14:40:31.003634 BGP RECV flags 0x40 code Origin(1): IGP
Jul  2 14:40:31.003645 BGP RECV flags 0x40 code ASPath(2) length 0: <null>
Jul  2 14:40:31.003654 BGP RECV flags 0x40 code LocalPref(5): 100
Jul  2 14:40:31.003666 BGP RECV flags 0x80 code MP_reach(14): AFI/SAFI 1/4
Jul  2 14:40:31.003685 BGP RECV 	nhop 172.20.2.2 len 4
Jul  2 14:40:31.004806 BGP RECV 	13.0.0.0/8 (label 800003) (label 800005) (label 800004) (label 300864)
Jul  2 14:40:31.004911 bgp_should_merge_as2_and_as4_path():2111 AS4-Peer 10.164.1.77 (Internal AS 64512)(RECV): No merge of as-paths required as the peer is 4 byte as capable
Jul  2 14:40:31.004936 bgp_process_aspath_and_aggr_attr():2603 AS4-Peer 10.164.1.77 (Internal AS 64512)(RECV): bgp_should_merge_as2_and_as4_path() says NO
Jul  2 14:40:31.004957 bgp_process_aspath_and_aggr_attr():2640 AS4-Peer 10.164.1.77 (Internal AS 64512)(RECV): Merged asp: path_len 0, path_seg_len 0, path2_len 0, path2_seg_len 0, path4_len 0, path4_seg_len 0, path_attr_len 0, path_aggr_len 0, path4_aggr_len 0, path4_flags 0x0, path_flags 0x0
Jul  2 14:40:31.005044 bgp_rcv_nlri: Peer 10.164.1.77 (Internal AS 64512)
Jul  2 14:40:31.005067 bgp_rcv_nlri: 13.0.0.0/8
Jul  2 14:40:31.005208 ADD      13.0.0.0/8          nhid 0  BGP      pref 13/-101 metric  <Hidden Int Ext>  as 64512
Jul  2 14:40:31.005489 CHANGE   13.0.0.0/8          nhid 0 gw 192.168.1.23    BGP      pref 13/-101 metric  <Active Int Ext>  as 64512
Jul  2 14:40:31.005539 CHANGE   13.0.0.0/8          nhid 0 gw 192.168.1.23    BGP      pref 13/-101 metric  <Active Int Ext>  as 64512
Jul  2 14:40:31.005585 bgp_rt_add: rt 13.0.0.0/8 { nhid 0x0 gw 192.168.1.23 <Active Int Ext> <Accepted> from 10.164.1.77 (Internal AS 64512) } Sync rt add for resolution
Jul  2 14:40:31.005612 bgp_multipath_check: rth 13.0.0.0/8 { nentries 1 ac 0x9dcd9e0 } Skip calc. multipath, was_mp_active=0, act_is_mp=0 
Jul  2 14:40:31.005636 bgp_rt_add: rt 13.0.0.0/8 { nhid 0x0 gw 192.168.1.23 <Active Int Ext> <Accepted> from 10.164.1.77 (Internal AS 64512) } Done rt add
Jul  2 14:40:31.005656 rt_close: 2 routes proto BGP_64512_64512.10.164.1.77
Jul  2 14:40:31.005656 


Route Update (add - just before withdraw failure)  12.0.0.0/8 from addroutes process (POST)
---------------------------------------------------------------------------------------------------------------------------
Exabgp


Sat, 02 Jul 2016 14:41:19 | INFO     | 10520  | processes     | Command from process addroutes : neighbor 10.164.2.66 announce route 12.0.0.0/8 next-hop 192.168.1.23 label [ 800001 800003 800005 800004 ] 
10.164.0.37 - - [02/Jul/2016 14:41:19] "POST / HTTP/1.1" 200 -
Sat, 02 Jul 2016 14:41:19 | INFO     | 10520  | reactor       | Route added to neighbor 10.164.2.66 local-ip 10.164.1.77 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open : 12.0.0.0/8 next-hop 192.168.1.23 label [ 800001 800003 800005 800004 ]
Sat, 02 Jul 2016 14:41:19 | INFO     | 10520  | reactor       | Performing dynamic route update


Router:

Jul  2 14:41:21.054132 bgp_read_v4_message: receiving packet(s) from 10.164.1.77 (Internal AS 64512)
Jul  2 14:41:21.054200 
Jul  2 14:41:21.054200 BGP RECV 10.164.1.77+54063 -> 10.164.2.66+179
Jul  2 14:41:21.054217 BGP RECV message type 2 (Update) length 63
Jul  2 14:41:21.054227 BGP RECV Update PDU length 63
Jul  2 14:41:21.054261 BGP RECV flags 0x40 code Origin(1): IGP
Jul  2 14:41:21.054274 BGP RECV flags 0x40 code ASPath(2) length 0: <null>
Jul  2 14:41:21.054296 BGP RECV flags 0x40 code LocalPref(5): 100
Jul  2 14:41:21.054306 BGP RECV flags 0x80 code MP_reach(14): AFI/SAFI 1/4
Jul  2 14:41:21.054345 BGP RECV 	nhop 192.168.1.23 len 4
Jul  2 14:41:21.054398 BGP RECV 	12.0.0.0/8 (label 800001) (label 800003) (label 800005) (label 800004)
Jul  2 14:41:21.054545 bgp_should_merge_as2_and_as4_path():2111 AS4-Peer 10.164.1.77 (Internal AS 64512)(RECV): No merge of as-paths required as the peer is 4 byte as capable
Jul  2 14:41:21.054575 bgp_process_aspath_and_aggr_attr():2603 AS4-Peer 10.164.1.77 (Internal AS 64512)(RECV): bgp_should_merge_as2_and_as4_path() says NO
Jul  2 14:41:21.054586 bgp_process_aspath_and_aggr_attr():2640 AS4-Peer 10.164.1.77 (Internal AS 64512)(RECV): Merged asp: path_len 0, path_seg_len 0, path2_len 0, path2_seg_len 0, path4_len 0, path4_seg_len 0, path_attr_len 0, path_aggr_len 0, path4_aggr_len 0, path4_flags 0x0, path_flags 0x0
Jul  2 14:41:21.054649 bgp_rcv_nlri: Peer 10.164.1.77 (Internal AS 64512)
Jul  2 14:41:21.054678 bgp_rcv_nlri: 12.0.0.0/8
Jul  2 14:41:21.054944 bgp_rt_change: rt 12.0.0.0/8 { nhid 0x0 gw 192.168.1.23 <Active Int Ext> <Accepted> from 10.164.1.77 (Internal AS 64512) } Sync rt change
Jul  2 14:41:21.054972 bgp_multipath_check: rth 12.0.0.0/8 { nentries 1 ac 0x9dcdd7c } Skip calc. multipath, was_mp_active=0, act_is_mp=0 
Jul  2 14:41:21.055007 bgp_rt_change: rt 12.0.0.0/8 { nhid 0x0 gw 192.168.1.23 <Active Int Ext> <Accepted> from 10.164.1.77 (Internal AS 64512) } Refreshed rt timestamp
Jul  2 14:41:21.055038 bgp_rt_change: rt 12.0.0.0/8 { nhid 0x0 gw 192.168.1.23 <Active Int Ext> <Accepted> from 10.164.1.77 (Internal AS 64512) } Done rt change - flashed=Y, afmets=Y, locrib=Y, changed=Y

Route Withdraw failure  12.0.0.0/8 from addroutes process (POST)
---------------------------------------------------------------------------------------------------------------------------
Exabgp

Sat, 02 Jul 2016 14:41:32 | INFO     | 10520  | processes     | Command from process addroutes : neighbor 10.164.2.66 withdraw route 12.0.0.0/8 next-hop 192.168.1.23 label [ 800001 800005 800004 ] 
10.164.0.37 - - [02/Jul/2016 14:41:32] "POST / HTTP/1.1" 200 -
Sat, 02 Jul 2016 14:41:32 | INFO     | 10520  | reactor       | Route removed : 12.0.0.0/8 next-hop 192.168.1.23 label [ 800001 800005 800004 ]
Sat, 02 Jul 2016 14:41:32 | INFO     | 10520  | reactor       | Performing dynamic route update
Sat, 02 Jul 2016 14:41:32 | INFO     | 10520  | reactor       | Updated peers dynamic routes successfully
Sat, 02 Jul 2016 14:41:32 | INFO     | 10520  | network       | Peer     10.164.2.66 ASN 64512   out loop, peer reset, message [notification received (3,10)] error[UPDATE message error / Invalid Network Field]
Sat, 02 Jul 2016 14:41:36 | INFO     | 10520  | network       | Connected to peer neighbor 10.164.2.66 local-ip 10.164.1.77 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open (out)


Router:


Jul  2 14:41:34.066783 background dispatch running job Read peer for task BGP_Listen.0.0.0.0+179
Jul  2 14:41:34.066816 bgp_read_v4_message: receiving packet(s) from 10.164.1.77 (Internal AS 64512)
Jul  2 14:41:34.066903 
Jul  2 14:41:34.066903 BGP RECV 10.164.1.77+54063 -> 10.164.2.66+179
Jul  2 14:41:34.066925 BGP RECV message type 2 (Update) length 40
Jul  2 14:41:34.066932 BGP RECV Update PDU length 40
Jul  2 14:41:34.066955 BGP RECV flags 0x80 code MP_unreach(15): AFI/SAFI 1/4
Jul  2 14:41:34.067069 BGP RECV 	0.0.0.0/56 (label 800001)
Jul  2 14:41:34.067084 BGP RECV Prefix length (195) requires more data than remaining in message (6 bytes)
Jul  2 14:41:34.067220 bgp_should_merge_as2_and_as4_path():2111 AS4-Peer 10.164.1.77 (Internal AS 64512)(RECV): No merge of as-paths required as the peer is 4 byte as capable
Jul  2 14:41:34.067241 bgp_process_aspath_and_aggr_attr():2603 AS4-Peer 10.164.1.77 (Internal AS 64512)(RECV): bgp_should_merge_as2_and_as4_path() says NO
Jul  2 14:41:34.067261 bgp_process_aspath_and_aggr_attr():2640 AS4-Peer 10.164.1.77 (Internal AS 64512)(RECV): Merged asp: path_len 0, path_seg_len 0, path2_len 0, path2_seg_len 0, path4_len 0, path4_seg_len 0, path_attr_len 0, path_aggr_len 0, path4_aggr_len 0, path4_flags 0x0, path_flags 0x0
Jul  2 14:41:34.067363 bgp_rcv_unreach: Peer 10.164.1.77 (Internal AS 64512)
Jul  2 14:41:34.067483 BGP_IGNORING_INVALID_PREFIX: bgp_rcv_unreach: peer 10.164.1.77 (Internal AS 64512) UPDATE ignoring invalid unreachable route 0.0.0.0/56 (7 of -4)
Jul  2 14:41:34.067514 bgp_rcv_unreach:10257: NOTIFICATION sent to 10.164.1.77 (Internal AS 64512): code 3 (Update Message Error) subcode 10 (bad address/prefix field), Reason: peer 10.164.1.77 (Internal AS 64512) UPDATE prefix length 195 exceeds unreachable prefix data remaining (6 bytes)
Jul  2 14:41:34.067585 bgp_send: sending 21 bytes to 10.164.1.77 (Internal AS 64512)
Jul  2 14:41:34.067966 
Jul  2 14:41:34.067966 BGP SEND 10.164.2.66+179 -> 10.164.1.77+54063
Jul  2 14:41:34.067984 BGP SEND message type 3 (Notification) length 21
Jul  2 14:41:34.067992 BGP SEND Notification code 3 (Update Message Error) subcode 10 (bad address/prefix field)
Jul  2 14:41:34.068975 task_timer_ucreate: created timer BGP_64512_64512.10.164.1.77_Suppress Logging  flags <>
Jul  2 14:41:34.069012 task_timer_uset: timer BGP_64512_64512.10.164.1.77_Suppress Logging <Touched> set to offset 0 at 14:41:34.068975
Jul  2 14:41:34.069370 bgp_peer_close: closing peer 10.164.1.77 (Internal AS 64512), state is 7 (Established)
Jul  2 14:41:34.069399 task_job_delete: delete background job Read peer for task BGP_Listen.0.0.0.0+179
Jul  2 14:41:34.069436 bgp_event: peer 10.164.1.77 (Internal AS 64512) old state Established event RecvUpdate new state Idle
Jul  2 14:41:34.069733 bgp_close_socket: peer 10.164.1.77 (Internal AS 64512)
Jul  2 14:41:34.069753 task_close: close socket 69 task BGP_64512_64512.10.164.1.77
Jul  2 14:41:34.069768 task_reset_socket: task BGP_64512_64512.10.164.1.77 socket 69
Jul  2 14:41:34.071059 task_timer_delete: BGP_64512_64512.10.164.1.77_Keepalive <Latest>
Jul  2 14:41:34.071089 task_timer_delete: BGP_64512_64512.10.164.1.77_Hold <Touched>
Jul  2 14:41:34.071101 task_timer_delete: BGP_64512_64512.10.164.1.77_Suppress Logging <Touched>
Jul  2 14:41:34.071147 task_job_create_background: create prio 4 job BGP closing job for task BGP_RT_Background
Jul  2 14:41:34.071176 background dispatch completed job Read peer for task BGP_Listen.0.0.0.0+179
Jul  2 14:41:34.071310 background dispatch running job BGP closing job for task BGP_RT_Background
Jul  2 14:41:34.071616 CHANGE   12.0.0.0/8          nhid 0 gw zero-len        BGP      pref 13/-101 metric  <Delete Int Ext>  as 64512
Jul  2 14:41:34.071735 CHANGE   13.0.0.0/8          nhid 0 gw zero-len        BGP      pref 13/-101 metric  <Delete Int Ext>  as 64512
Jul  2 14:41:34.071751 rt_close: 2 routes proto BGP_RT_Background
Jul  2 14:41:34.071751 


Looks like the router got a bad update from exabgp:

Jul  2 14:41:34.066955 BGP RECV flags 0x80 code MP_unreach(15): AFI/SAFI 1/4
Jul  2 14:41:34.067069 BGP RECV 	0.0.0.0/56 (label 800001)
Jul  2 14:41:34.067084 BGP RECV Prefix length (195) requires more data than remaining in message (6 bytes)



[router-bgplogexabgp.txt](https://github.com/Exa-Networks/exabgp/files/344755/router-bgplogexabgp.txt)
[exaBGPerror.txt](https://github.com/Exa-Networks/exabgp/files/344756/exaBGPerror.txt)

**Comment by russellkelly** [comment]
Here is the debug log - I had to run afterwards -  apologies - not much more on the route information.

Relevant updates below:

Add 12/8



Sat, 02 Jul 2016 15:13:54 | INFO     | 10601  | processes     | Command from process addroutes : neighbor 10.164.2.66 announce route 12.0.0.0/8 next-hop 192.168.1.23 label [ 800001 800003 800005 800004 ] 
10.164.0.37 - - [02/Jul/2016 15:13:54] "POST / HTTP/1.1" 200 -
Sat, 02 Jul 2016 15:13:54 | INFO     | 10601  | reactor       | Route added to neighbor 10.164.2.66 local-ip 10.164.1.77 local-as 64512 peer-as 64512 router-id 10.164.1.77 family-allowed in-open : 12.0.0.0/8 next-hop 192.168.1.23 label [ 800001 800003 800005 800004 ]
Sat, 02 Jul 2016 15:13:55 | INFO     | 10601  | reactor       | Performing dynamic route update
Sat, 02 Jul 2016 15:13:55 | INFO     | 10601  | reactor       | Updated peers dynamic routes successfully



Remove 12/8



10.164.0.37 - - [02/Jul/2016 15:14:03] "POST / HTTP/1.1" 200 -
Sat, 02 Jul 2016 15:14:03 | INFO     | 10601  | processes     | Command from process addroutes : neighbor 10.164.2.66 withdraw route 12.0.0.0/8 next-hop 192.168.1.23 label [ 800001 800005 800004 ] 
Sat, 02 Jul 2016 15:14:03 | INFO     | 10601  | reactor       | Route removed : 12.0.0.0/8 next-hop 192.168.1.23 label [ 800001 800005 800004 ]
Sat, 02 Jul 2016 15:14:03 | DEBUG    | 10601  | wire          | session 1 outgoing 10.164.1.77 / 10.164.2.52        RECEIVED  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
Sat, 02 Jul 2016 15:14:03 | INFO     | 10601  | message       | Peer     10.164.2.52 ASN 64512   << KEEPALIVE
Sat, 02 Jul 2016 15:14:03 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Receive Timer 89 second(s) left
Sat, 02 Jul 2016 15:14:03 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Send Timer 1 second(s) left
Sat, 02 Jul 2016 15:14:03 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Receive Timer 89 second(s) left
Sat, 02 Jul 2016 15:14:03 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Send Timer 1 second(s) left
Sat, 02 Jul 2016 15:14:04 | INFO     | 10601  | reactor       | Performing dynamic route update
Sat, 02 Jul 2016 15:14:04 | INFO     | 10601  | reactor       | Updated peers dynamic routes successfully
Sat, 02 Jul 2016 15:14:04 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Receive Timer 89 second(s) left
Sat, 02 Jul 2016 15:14:04 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Send Timer 0 second(s) left
Sat, 02 Jul 2016 15:14:04 | DEBUG    | 10601  | wire          | session 1 outgoing 10.164.1.77 / 10.164.2.52        SENDING  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
Sat, 02 Jul 2016 15:14:04 | INFO     | 10601  | message       | Peer     10.164.2.52 ASN 64512   >> KEEPALIVE
Sat, 02 Jul 2016 15:14:04 | DEBUG    | 10601  | timers        | peer 10.164.2.66 ASN 64512   Receive Timer 85 second(s) left
Sat, 02 Jul 2016 15:14:04 | DEBUG    | 10601  | timers        | peer 10.164.2.66 ASN 64512   Send Timer 0 second(s) left
Sat, 02 Jul 2016 15:14:04 | DEBUG    | 10601  | wire          | session 1 outgoing 10.164.1.77 / 10.164.2.66        SENDING  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
Sat, 02 Jul 2016 15:14:04 | INFO     | 10601  | message       | Peer     10.164.2.66 ASN 64512   >> KEEPALIVE
Sat, 02 Jul 2016 15:14:04 | DEBUG    | 10601  | wire          | session 1 outgoing 10.164.1.77 / 10.164.2.66        SENDING  (99) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0028 0200 0000 1180 0F0E 0001 0450 C350 10C3 5050 C350 410C
Sat, 02 Jul 2016 15:14:04 | INFO     | 10601  | message       | Peer     10.164.2.66 ASN 64512   >> 1 UPDATE(s)
Sat, 02 Jul 2016 15:14:04 | DEBUG    | 10601  | wire          | session 1 outgoing 10.164.1.77 / 10.164.2.66        RECEIVED  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0015 03
Sat, 02 Jul 2016 15:14:04 | DEBUG    | 10601  | wire          | session 1 outgoing 10.164.1.77 / 10.164.2.66        RECEIVED  (4) 030A
Sat, 02 Jul 2016 15:14:04 | INFO     | 10601  | message       | Peer     10.164.2.66 ASN 64512   << NOTIFICATION
Sat, 02 Jul 2016 15:14:04 | INFO     | 10601  | network       | Peer     10.164.2.66 ASN 64512   out loop, peer reset, message [notification received (3,10)] error[UPDATE message error / Invalid Network Field]
Sat, 02 Jul 2016 15:14:04 | DEBUG    | 10601  | wire          | session 1 outgoing, closing connection from 10.164.1.77 to 10.164.2.66
Sat, 02 Jul 2016 15:14:05 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Receive Timer 88 second(s) left
Sat, 02 Jul 2016 15:14:05 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Send Timer 29 second(s) left
Sat, 02 Jul 2016 15:14:05 | DEBUG    | 10601  | network       | out loop, intialising
Sat, 02 Jul 2016 15:14:06 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Receive Timer 87 second(s) left
Sat, 02 Jul 2016 15:14:06 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Send Timer 28 second(s) left
Sat, 02 Jul 2016 15:14:06 | DEBUG    | 10601  | wire          | Attempting connection to 10.164.2.66
Sat, 02 Jul 2016 15:14:07 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Receive Timer 86 second(s) left
Sat, 02 Jul 2016 15:14:07 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Send Timer 27 second(s) left
Sat, 02 Jul 2016 15:14:08 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Receive Timer 85 second(s) left
Sat, 02 Jul 2016 15:14:08 | DEBUG    | 10601  | timers        | peer 10.164.2.52 ASN 64512   Send Timer 26 second(s) left

[exaBGPerror-debuglevel.txt](https://github.com/Exa-Networks/exabgp/files/344758/exaBGPerror-debuglevel.txt)

**Comment by russellkelly** [comment]
I removed all other functions except the flask script I am using to allow POST to the routers.   I still have the same issue.  Again if I have #adj-rib-out false (no active) then at least the 12/8 route comes back.

Attached are the configuration files, .py files and the debug.  Same route add/withdrawl as before.

[dynamictrackobject.txt](https://github.com/Exa-Networks/exabgp/files/344851/dynamictrackobject.txt)

[exaBGPerror-debug.txt](https://github.com/Exa-Networks/exabgp/files/344852/exaBGPerror-debug.txt)


Please let me know what you find...seems a serious issue - somewhere.......

**Comment by thomas-mangin** [comment]
looking into it. ExaBGP can decode the route
```
./sbin/exabgp qa/conf/api-vpnv4.conf --decode "FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0028 0200 0000 1180 0F0E 0001 0450 C350 10C3 5050 C350 410C" 2>&1 | grep "update json"
Sun, 03 Jul 2016 10:52:57 | INFO     | 11773  | parser        | update json { "exabgp": "3.5.0", "time": 1467539577.29, "host" : "ptr-34.212.219.82.rev.exa.net.uk", "pid" : 11773, "ppid" : 27602, "counter": 1, "type": "update", "neighbor": { "address": { "local": "127.0.0.1", "peer": "127.0.0.1" }, "asn": { "local": "1", "peer": "1" }, "direction": "in", "message": { "update": { "withdraw": { "ipv4 nlri-mpls": [ { "nlri": "12.0.0.0/8", , "label": [ 800001, 800005, 800004 ] } ] } } } } }
```
```
Jul  2 14:41:34.066925 BGP RECV message type 2 (Update) length 40
Jul  2 14:41:34.066932 BGP RECV Update PDU length 40
Jul  2 14:41:34.066955 BGP RECV flags 0x80 code MP_unreach(15): AFI/SAFI 1/4
Jul  2 14:41:34.067069 BGP RECV     0.0.0.0/56 (label 800001)
Jul  2 14:41:34.067084 BGP RECV Prefix length (195) requires more data than remaining in message (6 bytes)
Jul  2 14:41:34.067483 BGP_IGNORING_INVALID_PREFIX: bgp_rcv_unreach: peer 10.164.1.77 (Internal AS 64512) UPDATE ignoring invalid unreachable route 0.0.0.0/56 (7 of -4)
```

The reason is that the withdrawn route should be as defined in RFC 3107
```
   A BGP speaker can withdraw a previously advertised route (as well as
   the binding between this route and a label) by either (a) advertising
   a new route (and a label) with the same NLRI as the previously
   advertised route, or (b) listing the NLRI of the previously
   advertised route in the Withdrawn Routes field of an Update message.
   The label information carried (as part of NLRI) in the Withdrawn
   Routes field should be set to 0x800000.  (Of course, terminating the
   BGP session also withdraws all the previously advertised routes.)
```

So the announcement should be:
`withdraw route 12.0.0.0/8 next-hop 192.168.1.23 label [ 800000 ]`

Until the family is added to the withdraw command, I do not know if the route is an IPv4 unicast or IPv4 nlri-mpls .. so I can not 'fix' the label for the user.

Changing the syntax of the API before the release of 4.0 is planned but it will be an intrusive change I have not yet started.

**Comment by russellkelly** [comment]
Hi Thomas - yep that worked removing the prefix just using the label 800000.  This is ok, as the longer prefix just takes over, until a new more specific is added on the other router.

Will wait for the family enhancement in the withdraw command and test it out.

Thanks for all your help.  Exabgp is a fantastic tool/product.!

Cheers Russ

**Comment by russellkelly** [comment]
Hey Thomas - simple question - I thought I'd find the answer in a jiffy - but can I import and call EXBGP from another python script?  

I'd like to interactively get some input from the users before firing up the exabgp process, or do I have to import os and simply run the command I'd run @ cli?

Cheers
Russ

**Comment by thomas-mangin** [comment]
@russellkelly I missed your question - do you still need an answer ? 
I do not see any easy way to do what you want - but without explaining more what you want to achieve I could miss something.
