### ISSUE TITLE
JSON message parse error

### ISSUE THREAD

**Issue by MadDog2K** [Exa-Networks/exabgp#446]
I guess introduced with #416 , I have some problem with the new format (with compact=false)

JSON returned : 

{ "exabgp": "3.5.0", "time": 1467654789.08, "host" : "jafar.management.is", "pid" : 8604, "ppid" : 1, "counter": 3, "type": "update", "neighbor": { "address": { "local": "10.86.2.221", "peer": "10.86.2.218" }, "asn": { "local": "65099", "peer": "15879" }, "direction": "receive", "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 15879 ], "confederation-path": [], "community": [ [ 15879, 999 ] ] }, "announce": { "ipv4 unicast": { "10.86.2.218": [ { "nlri": "185.55.131.0/24", }, { "nlri": "185.55.130.0/24", } ] } } } } } }

decoding that with json.loads() fails

Test case python 2.6 : 

echo '{ "exabgp": "3.5.0", "time": 1467654789.08, "host" : "jafar.management.is", "pid" : 8604, "ppid" : 1, "counter": 3, "type": "update", "neighbor": { "address": { "local": "10.86.2.221", "peer": "10.86.2.218" }, "asn": { "local": "65099", "peer": "15879" }, "direction": "receive", "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 15879 ], "confederation-path": [], "community": [ [ 15879, 999 ] ] }, "announce": { "ipv4 unicast": { "10.86.2.218": [ { "nlri": "185.55.131.0/24", }, { "nlri": "185.55.130.0/24", } ] } } } } } }' | python -m json.tool
 Expecting property name: line 1 column 499 (char 499)

Test case with Pyhon 3.3.5 : 

echo '{ "exabgp": "3.5.0", "time": 1467654789.08, "host" : "jafar.management.is", "pid" : 8604, "ppid" : 1, "counter": 3, "type": "update", "neighbor": { "address": { "local": "10.86.2.221", "peer": "10.86.2.218" }, "asn": { "local": "65099", "peer": "15879" }, "direction": "receive", "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 15879 ], "confederation-path": [], "community": [ [ 15879, 999 ] ] }, "announce": { "ipv4 unicast": { "10.86.2.218": [ { "nlri": "185.55.131.0/24", }, { "nlri": "185.55.130.0/24", } ] } } } } } }' | python3.3 -m json.tool
 Expecting property name enclosed in double quotes: line 1 column 500 (char 499)

Apparently, because of the "," behind each route/prefix

If I modify JSON to :

echo '{ "exabgp": "3.5.0", "time": 1467654789.08, "host" : "jafar.management.is", "pid" : 8604, "ppid" : 1, "counter": 3, "type": "update", "neighbor": { "address": { "local": "10.86.2.221", "peer": "10.86.2.218" }, "asn": { "local": "65099", "peer": "15879" }, "direction": "receive", "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 15879 ], "confederation-path": [], "community": [ [ 15879, 999 ] ] }, "announce": { "ipv4 unicast": { "10.86.2.218": [ { "nlri": "185.55.131.0/24"  }, { "nlri": "185.55.130.0/24"  } ] } } } } } }' | python -m json.tool

It works

**Comment by thomas-mangin** [comment]
Just trying to be to cleaver it seems - hopefully this patch does what the previous should have

**Comment by MadDog2K** [comment]
Yes, this fixes the issue 👍
