### ISSUE TITLE
Question on ExaBGP Logging to terminal

### ISSUE THREAD

**Issue by russellkelly** [Exa-Networks/exabgp#447]
Hi,

I have EXABGP runnning and I need to only receive the print messages from the .py program.

Is there anyway to make this so.  I currently have the .env file set as below (short messaginf, everything except process disabled).  But I am getting the process messages related to stdout.write announce routes (which makes sense) - so wondering if there's a knob to tweak so I only get messages with print() statements?

[exabgp.log]
all = false
configuration = false
daemon = false
destination = 'stdout'
enable = true
level = INFO
message = false
network = false
packets = false
parser = false
processes = true
reactor = false
rib = false
routes = false
short = true
timers = false

Thanks
Russ

**Comment by florinz** [comment]
Hi,



I am not quite sure what you mean by show only print() and not stdout.write(). Aren't those two things essentially the same?

If by the .py script you are referring to the python script that you bind in your API to exaBGP then writing and reading to standard in and out is redirected straight to ExaBGP. This means that if you call print or stdout.write in your .py script then the output should not go to the console.

That being said you can use a stderr output from the .py script to output things to the console. You can disable any exaBGP output by simply setting enable = false (from the env file you have provided above). This will only show what you have outputted to stderr out from your .py script.

If you want to keep the exaBGP output as well you can also redirect it to a file, if that helps. Here is a extract from the Ubuntu manpage which describes the env attribute to do this:

```
exabgp.log.destination: Controls where logging should be sent. 
                           syslog (or no setting) sends the data to the local syslog
                           server.  host:<location> sends the data to a remote
                           syslog server.  stdout sends the data to stdout.
                           stderr sends the data to stderr.  <filename> sends
                           the data to the named file.  Default: stdout.
```

Just be careful if you are trying to pipe the output from exaBGP to another app as your .py script console output will be redirected to stderr not stdout.

You could also write a quick log function in your .py script that writes the output to a file. This however will depend on what you are using the output for.

Hopefully that helps. Also here is a link to the Ubuntu manpage for ExaBGP that contains some of the env variables supported and descriptions about them (just in case you are unsure what some do).

[http://manpages.ubuntu.com/manpages/wily/man1/exabgp.1.html](http://manpages.ubuntu.com/manpages/wily/man1/exabgp.1.html)

**Comment by thomas-mangin** [comment]
change level = INFO to level = CRITICAL and only critical message will make it to the screen.
all = false should really however prevent logging .. could you please show me here what you see.
