### ISSUE TITLE
Configure exabgp as daemon...

### ISSUE THREAD

**Issue by AjdinGH** [Exa-Networks/exabgp#449]
Hi,

Can you please tell me how to make script to start exabgp as daemon(service) and have an option to reload like "exabgp reload" command.

Kind regards.

**Comment by azlux** [comment]
Hi @AjdinGH 
Check the wiki about the signals you can send to the process :  https://github.com/Exa-Networks/exabgp/wiki/Signal-:-_-README-first

**Comment by thomas-mangin** [comment]
'exabgp --help' should give you the information you need. signal for reload and and deamonize option. I fear there is currently a issue open regarding a bug with the signal for reload tho ..
