### ISSUE TITLE
Support for MD5 authentication?

### ISSUE THREAD

**Issue by doddt** [Exa-Networks/exabgp#451]
Are there any plans to add support for MD5 authentication (per https://tools.ietf.org/html/rfc2385)?

**Comment by xiaopeng163** [comment]
It's already supported...

**Comment by doddt** [comment]
Oh is that the 'md5' item in the neighbor config? I missed that before.

**Comment by thomas-mangin** [comment]
Hi @doddt - yes it is there -  good luck !
