### ISSUE TITLE
Starting multiple instances of exabgp from the command line specifying multiple configuration files.

### ISSUE THREAD

**Issue by russellkelly** [Exa-Networks/exabgp#452]
Hi All,

Sorry for posting to the issues forum - for some reason the google groups is not adding the post for me.

I recall seeing an option in some past posting where one could reference 2 configuration files sand fork 2 exabgp processes from the command line.  I recall there was the -d option in  the command line and you specificed multiple configuration files.

I can no longer find the post I am positive I saw.  Does anyone have any information about this?

Thanks Russ

**Comment by thomas-mangin** [comment]
possible - just have multiple configuration file name on the comman line.
'-d' is for debugging.
