### ISSUE TITLE
Issue With 

### ISSUE THREAD

**Issue by russellkelly** [Exa-Networks/exabgp#453]
Hi again,

More a question than an issue.  I am calling a process in the exabgp configuration file that now opens and writes to a file.  

I can run this python program myself (and could call it in the main() program), but I thought I could run from the process in the exbgp.conf file, however I get a permission error (below)

I have tried the daemonize option with a username and I have chmod 777 on the file - both have not helped.

Is there any way to specify in exabgp to run the program as a user with the correct permissions?

    f = open('PeerToLabelMapping','w')
IOError: [Errno 13] Permission denied: 'PeerToLabelMapping'
Command from process addroutes :  
Issue with the process' PIPE, terminating it and restarting it
Terminating process addroutes
Forked process addroutes

Thanks
Russ

**Comment by azlux** [comment]
Hi,
ExaBGP execute your program into a thread and read the std.out, but ExaBGP drop all permission before, so it's the user <em>nobody</em> who execute your program.

So you can run sudo command for example to take some user permission (no recommended). For you, the best way to test your program is with the command : 
``
sudo -u nobody <path_of_your_python_program>
``
It's only a permission problem in your case, not a ExaBGP issue.


Azlux

**Comment by russellkelly** [comment]
Cool.  Understood it was a required tweak in exa to run with the correct permission.  Tried a few things with the exa config file and adding user nobody.....

But in the end I took the other way and moved these functions out of the exa process and into the main Python program.

Thanks!
Russ

**Comment by azlux** [comment]
If it's ok, you can rename this issue and close it.

Azlux

**Comment by thomas-mangin** [comment]
@azlux thanks for replying ... in between airports ..
