### ISSUE TITLE
flowspec limit-rate mismatch

### ISSUE THREAD

**Issue by azlux** [Exa-Networks/exabgp#456]
Hi,
When we send flowspec rules, the value for the limit-rate isn't the same as the one the router receive. The wiki say both are in bits/s
```
Flow added to neighbor 128.***.***.4 local-ip 37.***.***.250 local-as 12395 peer-as 12395 router-id 37.***.***.250 family-allowed in-open, neighbor 128.***.***.2 local-ip 37.***.***.250 local-as 12395 peer-as 12395 router-id 37.***.***.250 family-allowed in-open : flow destination 8.8.8.8/32 protocol =UDP extended-community rate-limit 125000
```

Output from `show flowspec afi-all`
```
AFI: IPv4
  Flow           :Dest:8.8.8.8/32,Proto:=17
    Actions      :Traffic-rate: 1000000 bps  (bgp.1)
```

Azlux

**Comment by azlux** [comment]
After research, the cisco documentation say : 
The remaining 4 octets carry the rate information in IEEE floating point [IEEE.754.1985] format, units being **bytes per second**. A traffic-rate of 0 should result on all traffic for the particular flow to be discarded.

and with the command `show flowspec afi-all detail`
```
  Flow           :Dest:8.8.8.8/32,Proto:=17
    Actions      :Traffic-rate: 1600 bps  (bgp.1)
    Statistics                        (packets/bytes)
```
The unit is **bytes** too

My conclusion is that ExaBGP multiple the value by 8 because of a unit mistake

**Comment by thomas-mangin** [comment]
[RFC 5575](https://tools.ietf.org/html/rfc5575) says:

```
7.  Traffic Filtering Actions [...]
Traffic-rate: [...]
         The remaining 4 octets carry the rate information in IEEE
         floating point [IEEE.754.1985] format, units being bytes per
         second.  A traffic-rate of 0 should result on all traffic for
         the particular flow to be discarded.
 ```

Both Cisco and Juniper (I believe) mis-implemented the RFC using bits and not bytes.
I think it is noted in the wiki somewhere already .. just need to find it.
