### ISSUE TITLE
Healthcheck crash exabgp when used with systemd

### ISSUE THREAD

**Issue by lchabert** [Exa-Networks/exabgp#461]
Hi,

I use exabgp to announce VIP on my network infrastructure following nginx states. I use packaged (pip) healthcheck, and systemd to start exabgp (running en centos 7.2).

I start nginx, then exabgp service. No issue, route is announced to backbone. When i stop nginx (make some test), exabgp crash (due to an exception on healthcheck). When i run exabgp without systemd (manualy), no issue. Issued appear only when exabgp is started as service.

Please find below stacktrace (just after nginx stopped):
```python
Aug 12 09:49:38 dc4-virt-http-01.test.fr healthcheck-nginx[24884]: Uncatched exception: 'ascii' codec can't decode byte 0xc3 in position 319: ordinal not in range(128)
                                                                     Traceback (most recent call last):
                                                                       File "/usr/lib/python2.7/site-packages/exabgp/application/healthcheck.py", line 463, in main
                                                                         loop(options)
                                                                       File "/usr/lib/python2.7/site-packages/exabgp/application/healthcheck.py", line 392, in loop
                                                                         successful = disabled or check(options.command, options.timeout)
                                                                       File "/usr/lib/python2.7/site-packages/exabgp/application/healthcheck.py", line 317, in check
                                                                         logger.info("Output of check command: {0}".format(stdout))
                                                                     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 319: ordinal not in range(128)
```

I have customized systemd service config file. Same as github repository, but some variable added:
```
[Unit]
Description=ExaBGP
After=network.target
ConditionPathExists=/etc/exabgp/exabgp-%i.conf

[Service]
Environment=exabgp_daemon_daemonize=false
ExecStart=/usr/bin/exabgp --folder /etc/exabgp /etc/exabgp/exabgp-%i.conf
ExecReload=/bin/kill -USR1 $MAINPID

[Install]
WantedBy=multi-user.target
```

Any reasons to have UnicodeDecodeError with systemd ? Any additionnal parameters needed to run python as a service ?

Regards.

**Comment by vincentbernat** [comment]
You should answer your check only outputs ASCII characters. Notably, if you use curl, redirect the output to /dev/null. The check should only display a minimal output. We could also fix the decoding to ignore non-ASCII characters to avoid such problems.

**Comment by vincentbernat** [comment]
Maybe your problem is already fixed with a more recent version of the healthcheck. But it is not part of the 3.4 branch.

**Comment by lchabert** [comment]
Indeed, it works if ```cmd = curl --fail --verbose --max-time 2 http://localhost > /dev/null  2>&1```

**Comment by thomas-mangin** [comment]
@vincentbernat do you want me to backport the master version to 3.4 ?

**Comment by vincentbernat** [comment]
I am not sure that this would fix the issue. No opinion here.
