### ISSUE TITLE
Dynamically learn peer-as of neighbor

### ISSUE THREAD

**Issue by plajjan** [Exa-Networks/exabgp#466]
ITSM that ExaBGP currently needs to have the peer-as of a neighbor defined. For certain situations it can be useful to be able to accept any peer-as. Technically this would work by looking in the BGP OPEN message, read the AS of the peer and use that as the peer-as.

IIRC the end that first sends OPEN is not linked to the end that initiated the TCP connection. Rather the OPEN message is based on DelayOpenTimer, so ExaBGP can initiate the TCP connection but wait for the remote neighbor to send its OPEN message first. This way we don't have to passively wait for an incoming connection. Although not crucial to this, I would appreciate if ExaBGP could be configured rather aggressively regarding initial connections (I'm running it in a CI environment and waiting a minute for BGP means all the testing takes much longer).

**Comment by Lalufu** [comment]
It so happens I just wrote some code for that. It's at the "WFM" stage right now, but it does the job. I'll prepare a pull request.

**Comment by plajjan** [comment]
@Lalufu cool I'd love to have a look!

I should probably switch over to git master in my use as well. Still on ancient 3.4....

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/commit/12186b2b3d88045c7cedc810e9da5bb0cd7a4b5b

Should work .. please feel free to test and report if there is an issue.
