### ISSUE TITLE
Dynamic neighbor addresses

### ISSUE THREAD

**Issue by plajjan** [Exa-Networks/exabgp#467]
ITSM that ExaBGP requires the IP address of a neighbor to be defined in the configuration. For certain scenarios it can be useful to define any IP or that the peer must be within a certain prefix but that we don't have to define each individual neighbor. Some vendors already support this;
- http://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/xe-3sg/irg-xe-3sg-book/irg-dynamic-neighbor.html
- http://www.juniper.net/techpubs/en_US/junos12.1x46/topics/usage-guidelines/routing-configuring-bgp-groups-and-peers.html#id-13213602
- Dont' have reference to ALU/Nokia SROS but they have it
- Arista - search for "listen" - http://aspiringnetworker.blogspot.se/2015/08/bgp-in-arista-data-center_90.html

pmacct supports this, as well as the behaviour described in #466 to automatically setup iBGP sessions to all your routers.

**Comment by thomas-mangin** [comment]
I see multiple ways it could be implemented in ExaBGP, the simplest would be to on reception of the TCP connection generate a 'passive' neighbor and use the content of the OPEN for the ASN.

In my 'nice to have' not yet done list.

**Comment by thomas-mangin** [comment]
I believe this is now in with the 'auto' keyword, which will take the IP from the TCP session and was implemented by @brijohn
