### ISSUE TITLE
support for outbound route filters?

### ISSUE THREAD

**Issue by doddt** [Exa-Networks/exabgp#469]
I'd like to be able to tell exabgp to send ORFs to my peers. I've poked around a bit but it appears this is not currently supported. Is it on the TODO list?

thanks,
tim

**Comment by thomas-mangin** [comment]
Very sorry .. not anytime soon.

**Comment by thomas-mangin** [comment]
Added support for https://tools.ietf.org/html/rfc5292 to #200 - if there is a use case and this is still something I should consider, please let me know.
