### ISSUE TITLE
Issue with ADD-PATH JSON format, fixed in master (will not be backported to 3.4)

### ISSUE THREAD

**Issue by russellkelly** [Exa-Networks/exabgp#473]
Hi Thomas,

I am working with add-path currently and am running across an issue with the withdraw JSON string EXABGP is logging to a file that Python can't parse correctly.

It is only with the withdraw message:

Here is the log line in JSON format:

```
{ "exabgp": "3.4.8", "time": 1472427836, "host" : "epe-demo-server", "pid" : "11896", "ppid" : "11893", "counter": 34, "type": "update", "neighbor": { "ip": "10.164.2.58", "address": { "local": "10.164.1.177", "peer": "10.164.2.58"}, "asn": { "local": "64512", "peer": "64512"}, "message": { "update": { "withdraw": { "ipv4 unicast": { "14.0.0.0/8": { "path-information": "0.0.0.1" }, "14.0.0.0/8": { "path-information": "0.0.0.2" } } } } }} }
```

Running it through a JSON Validator there is a warning error that Duplicate key, names should be unique.[Code 23, Structure 81] - the 14.0.0.0/8 key

```
{
   "exabgp":"3.4.8",
   "time":1472427836,
   "host":"epe-demo-server",
   "pid":"11896",
   "ppid":"11893",
   "counter":34,
   "type":"update",
   "neighbor":{
      "ip":"10.164.2.58",
      "address":{
         "local":"10.164.1.177",
         "peer":"10.164.2.58"
      },
      "asn":{
         "local":"64512",
         "peer":"64512"
      },
      "message":{
         "update":{
            "withdraw":{
               "ipv4 unicast":{
                  "14.0.0.0/8":{
                     "path-information":"0.0.0.1"
                  },
                  "14.0.0.0/8":{
                     "path-information":"0.0.0.2"
                  }
               }
            }
         }
      }
   }
}
```

As a result Python (json.loads) Parses this string as below:

```
{u'counter': 34,
 u'exabgp': u'3.4.8',
 u'host': u'epe-demo-server',
 u'neighbor': {u'address': {u'local': u'10.164.1.177',
                            u'peer': u'10.164.2.58'},
               u'asn': {u'local': u'64512', u'peer': u'64512'},
               u'ip': u'10.164.2.58',
               u'message': {u'update': {u'withdraw': {u'ipv4 unicast': {u'14.0.0.0/8': {u'path-information': u'0.0.0.2'}}}}}},
 u'pid': u'11896',
 u'ppid': u'11893',
 u'time': 1472427836,
 u'type': u'update'}
```

All other update messages are fine - and sometimes I get separate withdraw messages for withdraw and that works fine too - because obviously there are no duplicate keys.

Is this a known issue - can EXABGP split this into 2 updates?  Not sure on the exact method producing the original string above, but python parsing doesn't like it (no error (as the format's valid), just only stores the last value because its not unique)

Thanks
Russ

**Comment by thomas-mangin** [comment]
what version please ? is it still on master?

**Comment by thomas-mangin** [comment]
I tried to replicate the format of the UPDATE packet in 3.4 .. I can not recall if I changed this on master.

**Comment by russellkelly** [comment]
Hi Thomas,

Yes still on the master:

rbutme@epe-demo-server:~$ exabgp -version
ExaBGP : 3.4.16
Python : 2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]
Uname  : #140-Ubuntu SMP Mon Jul 18 21:21:05 UTC 2016

**Comment by thomas-mangin** [comment]
master, not 3.4 stable :)
> git checkout master

**Comment by thomas-mangin** [comment]
But yes, I probably need to backport to 3.4 too

**Comment by russellkelly** [comment]
Sorry - I forgot I changed to 3.4 :)

 1102  git clone https://github.com/Exa-Networks/exabgp.git
 1103  git checkout 3.4

Sorry for the dumb question but, is the master 4.0 now?  I had issues with the conf files with 4.0

**Comment by thomas-mangin** [comment]
No 4.0 is still not ready - still work to do to get it done.

**Comment by russellkelly** [comment]
Hi Thomas,

OK, So I will stay with the 3.4 version I am running.  

Looks like this was tried to be fixed in the 3.4 release from what you said above "I tried to replicate the format of the UPDATE packet in 3.4" - is this what you meant?

Or do you need to work on the fix?  It's easy to replicate - if I take two peers (to the same router) down simultaneously, or remove a route that is withdrawn via multiple peers on the same router simultaneously I see the withdraw message with duplicate keys.

Let me know if you need anything....this is kinda blocking the add-path functionality :)

Thanks
Russ

**Comment by thomas-mangin** [comment]
I am pretty sure this is not the first time I am told about this and this was fixed in the 3.4 branch .. I may only have fixed it on 4.0 as it would cause backward incompatibility issues - I am currently not able to look into it. Please give me a few days to investigate. Converting your config to the format on master (knowing that it will chance) may fix your problem tho.

**Comment by thomas-mangin** [comment]
working on master - as changing the format on 3.4 would beak working code for application with only one path, unsure how move forward ..

**Comment by thomas-mangin** [comment]
After consideration, I will not change the code in 3.4 - the JSON is indeed broken, but I can not 'unbreak' it without changing the format and this would break application on upgrade, which is something I am trying to not do in 3.4

**Comment by thomas-mangin** [comment]
I will also leave this thead so users can easily find about this issue.

**Comment by russellkelly** [comment]
Hi Thomas,

Understood.  All seems to be OK in the master for the record.  

Thanks for looking into this.

**Comment by thomas-mangin** [comment]
closing hopefully people will find this anyway :p
