### ISSUE TITLE
"attempting to accept connections, socket not ready" no listen configured

### ISSUE THREAD

**Issue by tobru** [Exa-Networks/exabgp#474]
Running ExaBGP 3.4.16 spits out the following message:

```
Tue, 30 Aug 2016 12:19:35 | WARNING  | 5078   | network       | attempting to accept connections, socket not ready
```

The process is started like this:
```
sudo -u exabgp /usr/local/bin/exabgp -e /etc/exabgp/exabgp.env /etc/exabgp/bgp_announce.conf
```

Contents of env:
```
[...]

[exabgp.tcp]
acl = false
bind = ''
delay = 0
once = false
port = 179
```

-> So as far as I understand, ExaBGP should not open a listening socket? What does this message mean?

**Comment by tobru** [comment]
Update: This only shows up in the logs if the connection to the peer doesn't work.

**Comment by thomas-mangin** [comment]
Please try, bind = '0.0.0.0' or IP address.

**Comment by thomas-mangin** [comment]
This is a configuration issue please look at the examples in qa/conf for help.

https://github.com/Exa-Networks/exabgp/tree/3.4/qa/conf
or
https://github.com/Exa-Networks/exabgp/tree/master/qa/conf

**Comment by thomas-mangin** [comment]
This is a configuration issue, please look into https://github.com/Exa-Networks/exabgp/tree/3.4/qa/self to see how exabgp connects to itself (or https://github.com/Exa-Networks/exabgp/tree/4.0/qa/self if you are running master from git)

**Comment by thomas-mangin** [comment]
Hi @tobru 

After dealing with peers, exabgp goes to sleep until the next second or until somethings awakes it.
```
	if finished:
		for io in self.ready(list(peers),self.processes.fds(),end-time.time()):
```
Here is looks for data on the peers' socket 
```
	while True:
		try:
			_,w,_ = select.select([],[io,],[],0)
			if not w:
				if not warned and time.time()-start > 1.0:
					logger.network('attempting to accept connections, socket not ready','warning')
					warned = True
				yield False
				continue
```
So the message is indeed confusing as the fact that select returned when there is no data written does not mean it is about incoming connection. will improve the message.

You can safely ignore this.

**Comment by tobru** [comment]
@thomas-mangin Thanks a lot for looking into this and explaining what it's all about.

**Comment by thomas-mangin** [comment]
Sorry - I did not trace the code correctly it was .. def ready (io) called and not self.ready ...
That said, fixed the message anyway as it was wrong:
https://github.com/Exa-Networks/exabgp/commit/51c7680c6d22e12e27a625911c09fe3b64e9839a
