### ISSUE TITLE
Issue With JSON Format Out From EXABGP in Master 4.0.0

### ISSUE THREAD

**Issue by russellkelly** [Exa-Networks/exabgp#476]
Hi Thomas,

I moved over to the Master branch to try to avoid the duplicate key issue in 3.4, however I've run into another issue with an invalid format update for the family mpls-nlri which give me the MPLS labels from BGP-LU

From below you can see the format is invalid - see the bold commas below

New Error EPE Label in Master
------------------------
```
{ "exabgp": "3.5.0", "time": 1472590302.77, "host" : "epe-demo-server", "pid" : 24481, "ppid" : 24476, "counter": 6, "type": "update", "neighbor": { "address": { "local": "10.164.1.177", "peer": "10.164.2.58" }, "asn": { "local": "64512", "peer": "64512" }, "direction": "receive", "message": { "update": { "attribute": { "origin": "igp", "local-preference": 100, "attribute-0x1C-0xE0": "0x00010404ac140204" }, "announce": { "ipv4 nlri-mpls": { "172.20.2.4": [ { "nlri": "192.168.1.20/32", , "label": [ 306016 ] }, { "nlri": "192.168.1.13/32", , "label": [ 305824 ] }, { "nlri": "192.168.1.30/32", , "label": [ 306000 ] } ] } } } } } }
```

```
{
   "exabgp":"3.5.0",
   "time":1472590302.77,
   "host":"epe-demo-server",
   "pid":24481,
   "ppid":24476,
   "counter":6,
   "type":"update",
   "neighbor":{
      "address":{
         "local":"10.164.1.177",
         "peer":"10.164.2.58"
      },
      "asn":{
         "local":"64512",
         "peer":"64512"
      },
      "direction":"receive",
      "message":{
         "update":{
            "attribute":{
               "origin":"igp",
               "local-preference":100,
               "attribute-0x1C-0xE0":"0x00010404ac140204"
            },
            "announce":{
               "ipv4 nlri-mpls":{
                  "172.20.2.4":[
                     {
                        "nlri":"192.168.1.20/32",
**,**
                        "label":[
                           306016
                        ]
                     },
                     {
                        "nlri":"192.168.1.13/32",
**,**
                        "label":[
                           305824
                        ]
                     },
                     {
                        "nlri":"192.168.1.30/32",
**,**
                        "label":[
                           306000
                        ]
                     }
                  ]
               }
            }
         }
      }
   }
}
```

It seems you have added in the format as a list of dictionaries to avoid the duplicate key error, that exists in 3.4.8.  This seems to be fine in resolving the duplicate warning and I can parse the IPv4 unicast announce and withdraw messages that come through correctly (update and withdraw for IPv4 Unicast shown below) 

This BGP-LU update is invalid however, and crashes json.loads  - I am not too sure if the withdraw message suffers the same - I can check if needed.

At this point I'm stuck :)  

Correct IPv4 Unicast Announce  In Master
---------------------------------
```
{
   "exabgp":"3.5.0",
   "time":1472590174.67,
   "host":"epe-demo-server",
   "pid":24279,
   "ppid":24274,
   "counter":12,
   "type":"update",
   "neighbor":{
      "address":{
         "local":"10.164.1.177",
         "peer":"10.164.2.58"
      },
      "asn":{
         "local":"64512",
         "peer":"64512"
      },
      "direction":"receive",
      "message":{
         "update":{
            "attribute":{
               "origin":"igp",
               "as-path":[
                  1
               ],
               "confederation-path":[

               ],
               "local-preference":100,
               "community":[
                  [
                     1,
                     1
                  ]
               ]
            },
            "announce":{
               "ipv4 unicast":{
                  "192.168.1.30":[
                     {
                        "nlri":"13.0.0.0/8",
                        "path-information":"0.0.0.1"
                     },
                     {
                        "nlri":"12.0.0.0/8",
                        "path-information":"0.0.0.1"
                     },
                     {
                        "nlri":"14.0.0.0/8",
                        "path-information":"0.0.0.1"
                     }
                  ]
               }
            }
         }
      }
   }
}
```

Correct IPv4 Unicast Withdraw in Master
----------------------------------
```
{
   "exabgp":"3.5.0",
   "time":1472590892.4,
   "host":"epe-demo-server",
   "pid":24831,
   "ppid":24826,
   "counter":12,
   "type":"update",
   "neighbor":{
      "address":{
         "local":"10.164.1.177",
         "peer":"10.164.2.58"
      },
      "asn":{
         "local":"64512",
         "peer":"64512"
      },
      "direction":"receive",
      "message":{
         "update":{
            "withdraw":{
               "ipv4 unicast":[
                  {
                     "nlri":"14.0.0.0/8",
                     "path-information":"0.0.0.1"
                  },
                  {
                     "nlri":"14.0.0.0/8",
                     "path-information":"0.0.0.2"
                  }
               ]
            }
         }
      }
   }
}
```

**Comment by thomas-mangin** [comment]
So I have two comma one after the other .. ? if so, it is a simple bug.

**Comment by russellkelly** [comment]
Yes it seems so.

**Comment by thomas-mangin** [comment]
please let me know if my latest commit helped:
https://github.com/Exa-Networks/exabgp/commit/a122abcf79f1df17d6837c4d4fa1ec210f8d57c1

I have currently very little time - but hopefully this is it.

**Comment by russellkelly** [comment]
Hi Thomas,

Yes that fixed it.  I have to amend my parser :)  But I see:
'''
{
   "exabgp":"3.5.0",
   "time":1472690879.99,
   "host":"epe-demo-server",
   "pid":29723,
   "ppid":29718,
   "counter":6,
   "type":"update",
   "neighbor":{
      "address":{
         "local":"10.164.1.177",
         "peer":"10.164.2.58"
      },
      "asn":{
         "local":"64512",
         "peer":"64512"
      },
      "direction":"receive",
      "message":{
         "update":{
            "attribute":{
               "origin":"igp",
               "local-preference":100,
               "attribute-0x1C-0xE0":"0x00010404ac140204"
            },
            "announce":{
               "ipv4 nlri-mpls":{
                  "172.20.2.4":[
                     {
                        "nlri":"192.168.1.20/32",
                        "label":[
                           306144
                        ]
                     },
                     {
                        "nlri":"192.168.1.13/32",
                        "label":[
                           305824
                        ]
                     },
                     {
                        "nlri":"192.168.1.30/32",
                        "label":[
                           306160
                        ]
                     }
                  ]
               }
            }
         }
      }
   }
}
'''

**Comment by thomas-mangin** [comment]
Good, thank you for letting me know.
