### ISSUE TITLE
BGP session tear down the session after several hours [3.4.16]

### ISSUE THREAD

**Issue by Zeawiel** [Exa-Networks/exabgp#477]
Hello,
First I'll present what I want to do. I want an overview of the BGPstate of my network. for that I connect exaBGP to several router which have the GRT and recover the whole routes (++ with the add-path capability). I represent around 2M prefix (600k from GRT ++ with addpath) for 1 router.
Then I parse all the received bgp message and put it in a psql DB.

For now I tried with only 1 router, and I get a strange behavior. After a certain time (this can vary) the bgp session get down with this message:
`exabgp: 4353   network       Peer  b.b.b.b ASN xxxx    out loop, peer reset, message [notification sent (4,0)] error[Hold timer expired / Unspecific / problem with network while trying to send keepalive]`

The session reup after a short time, but still ... 
I started a session 17h ago and it gets deconnected 6 times.
There is a firewall between my server and my router, but there is no bad log on it. 
I tried this night to compare with quagga to another router and it doesn't crash. But quagga doesn't meet my needs ... (script on received, add-path ...)

With the session reup, the router re-sent me all its prefix. The graceful restart didn't work. Strange.

Did you already saw this ? 
Regards

My setup:

- OS: Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-71-generic i686)
- exabgp: 
`exabgp --v
ExaBGP : 3.4.16
Python : 2.7.6 (default, Jun 22 2015, 18:00:18)  [GCC 4.8.2]
Uname  : #114-Ubuntu SMP Tue Dec 1 02:35:20 UTC 2015
`
- my conf:

group TestInternet {
    router-id a.a.a.a;
    local-address a.a.a.a;
    local-as xxx;
    add-path receive;
    graceful-restart 300;
    process exabgpdb {
        receive {
            update;
            parsed;
            neighbor-changes;
        }
        encoder json;
        run "/usr/local/bin/exabgpdb";
    }
    neighbor b.b.b.b{
        description "routerb";
        peer-as xxx;
        graceful-restart 300;
    }
}

**Comment by thomas-mangin** [comment]
ExaBGP is overloaded. Can you please split your neighbors in multiple files and run multiple exabgp. The code is single thread single core.

**Comment by Zeawiel** [comment]
I tried to increase the Hold timer on the router, it is set like this now for exabgp:
Active Hold Time     : 180              Active Keep Alive    : 60

For Quagga, it is set the the default value:
Active Hold Time     : 90               Active Keep Alive    : 30

The router is not overloaded (Alcatel 7750sr7) 
But maybe the server, Since the processing of the prefix is quite process consuming (And there is other process running which take ressources). 

Every time it crash, the out loop is increasing
This is the full log trace (I did activate the 'full full' trace, because of the amount of log that it can generate)
exabgp: 4353   network       out loop, intialising
exabgp: 4353   network       Connected to peer neighbor b.b.b.b local-ip a.a.a.a local-as xxxx peer-as xxxx router-id a.a.a.a family-allowed in-open (out)
exabgp: 4353   network       Peer  b.b.b.b ASN xxxx    out loop, peer reset, message [notification sent (4,0)] error[Hold timer expired / Unspecific / problem with network while trying to send keepalive]
exabgp: 4353   network       out loop, intialising
exabgp: 4353   network       Connected to peer neighbor b.b.b.b local-ip a.a.a.a local-as xxxx peer-as xxxx router-id a.a.a.a family-allowed in-open (out)
exabgp: 4353   network       Peer  b.b.b.b ASN xxxx    out loop, peer reset, message [notification sent (4,0)] error[Hold timer expired / Unspecific / problem with network while trying to send keepalive]
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, intialising
exabgp: 4353   network       Connected to peer neighbor b.b.b.b local-ip a.a.a.a local-as xxxx peer-as xxxx router-id a.a.a.a family-allowed in-open (out)
exabgp: 4353   network       Peer  b.b.b.b ASN xxxx    out loop, peer reset, message [notification sent (4,0)] error[Hold timer expired / Unspecific / problem with network while trying to send keepalive]
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, intialising
exabgp: 4353   network       Connected to peer neighbor b.b.b.b local-ip a.a.a.a local-as xxxx peer-as xxxx router-id a.a.a.a family-allowed in-open (out)
exabgp: 4353   network       Peer  b.b.b.b ASN xxxx    out loop, peer reset, message [notification sent (4,0)] error[Hold timer expired / Unspecific / problem with network while trying to send keepalive]
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, intialising
exabgp: 4353   network       Connected to peer neighbor b.b.b.b local-ip a.a.a.a local-as xxxx peer-as xxxx router-id a.a.a.a family-allowed in-open (out)
exabgp: 4353   network       Peer  b.b.b.b ASN xxxx    out loop, peer reset, message [notification sent (4,0)] error[Hold timer expired / Unspecific / problem with network while trying to send keepalive]
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, intialising
exabgp: 4353   network       Connected to peer neighbor b.b.b.b local-ip a.a.a.a local-as xxxx peer-as xxxx router-id a.a.a.a family-allowed in-open (out)
exabgp: 4353   network       Peer  b.b.b.b ASN xxxx    out loop, peer reset, message [notification sent (4,0)] error[Hold timer expired / Unspecific / problem with network while trying to send keepalive]
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, skipping, not time yet
exabgp: 4353   network       out loop, intialising
exabgp: 4353   network       Connected to peer neighbor b.b.b.b local-ip a.a.a.a local-as xxxx peer-as xxxx router-id a.a.a.a family-allowed in-open (out)
exabgp: 4353   reactor       SIG TERM received - shutdown
exabgp: 4353   processes     Error received while sending data to helper program, retrying ([Errno EINTR] [Errno 4] Interrupted system call)
exabgp: 4353   reactor       Performing shutdown
exabgp: 4353   network       Closing the session without notification
exabgp: 4353   network       Peer  b.b.b.b ASN xxxx    graceful restarted negotiated, closing without sending any notification
exabgp: 4353   processes     Terminating process exabgpdb

**Comment by thomas-mangin** [comment]
'With the session reup, the router re-sent me all its prefix.' Graceful-restart makes sure your peer does not drop the routes it knows from the FIB before 'xxx' second after the connection goes down.
On re-esstablishment, the router MUST resend them.

**Comment by thomas-mangin** [comment]
ok - if ExaBGP is too slow to send the keepalive it may be that ALU killed the session. Could you run more than one ExaBGP instance (you can run one peer and AFI/SAFI pair if you want).

**Comment by Zeawiel** [comment]
For now I only work with ipv4 unicast.
What do you want me to test ?

**Comment by thomas-mangin** [comment]
Is there a difference between ExaBGP and Quagga (in term of placement in the network, is one behind a firewall for example).

**Comment by Zeawiel** [comment]
No, both (exabgp & quagga) are running on the same server and peered with router via firewall. The two routers are on the same network.

**Comment by thomas-mangin** [comment]
I could do with a full log .. (not via github obviously) to see what happened before the drop.

**Comment by Zeawiel** [comment]
I find something in the full log: The send timer is negative so it closes the session. Strange !
b.b.b.b is still the router
a.a.a.a is my serveur with exabgp
xxxx is the ASN (same for exabgp and the router)

Do you want the full trace by mail ?

> exabgp: 7423   timers        peer b.b.b.b ASN xxxx    Receive Timer 179 second(s) left
exabgp: 7423   timers        peer b.b.b.b ASN xxxx    Send Timer -306 second(s) left
exabgp: 7423   wire          session 1 outgoing a.a.a.a / b.b.b.b   SENDING  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
exabgp: 7423   wire          session 1 outgoing, closing connection from a.a.a.a to b.b.b.b
exabgp: 7423   wire          session 1 outgoing b.b.b.b problem sending message ([Errno ECONNRESET] [Errno 104] Connection reset by peer)
exabgp: 7423   message       Peer  b.b.b.b ASN xxxx    >> NOTIFICATION (4,0,"problem with network while trying to send keepalive")
exabgp: 7423   network       Peer  b.b.b.b ASN xxxx    out loop, peer reset, message [notification sent (4,0)] error[Hold timer expired / Unspecific / problem with network while trying to send keepalive]
exabgp: 7423   wire          session 1 outgoing, closing connection from a.a.a.a to b.b.b.b
exabgp: 7423   network       out loop, intialising
exabgp: 7423   wire          Attempting connection to b.b.b.b

**Comment by thomas-mangin** [comment]
Yes please.

**Comment by thomas-mangin** [comment]
Are you running on a VM ? if so can you please make sure you synchronise the time and keep it right with ntp. Saw something like that with VM and clock issues.

**Comment by Zeawiel** [comment]
Hum. I'm in a VM yes ..
And yes, my NTP seems to be broken (FWs ....) 

I just sent you the full trace corresponding.

**Comment by thomas-mangin** [comment]
I think we sorted that one: if time slide, exabgp will show a negative time for keepalive (or very long time for the other side). It send will consider the other side dead (or will not send the keepalive and will be considered dead by the peer).
Feel free to re-open if not.

**Comment by Zeawiel** [comment]
Hum. That's embarrassing.
I tried this night after enabled NTP and the error is still there. 

I'll switch my environment to a physical server in a month. Maybe this will fix the issue. I hope.

**Comment by thomas-mangin** [comment]
ntp takes some time to sync the clock if you do not run ntpdate before enabling it .. and may still cause large jumps in times.
