### ISSUE TITLE
Physical interface monitoring support?

### ISSUE THREAD

**Issue by pyke369** [Exa-Networks/exabgp#485]
Hi Thomas,

Is there any support within the ExaBGP code-base for physical interface monitoring? I mean a way to shutdown a directly-connected peer BGP session if the corresponding physical interface goes down (like during a physical fiber-cut or switch/port maintenance), without waiting for the BGP session expiration timer or resorting to short TCP keepalive tricks?

It would be quite beneficial in HA/CLOS scenarii, where all servers maintain a double BGP session towards 2 different switches, and one of the switches crashes (or the attachment port is administratively shut): we would like to remove one of the 2 ECMP outgoing routes as quickly as possible, hence being notified of a "peer down" situation almost instantaneously in this case.

Thanks for your answer and sorry if this is something that's already been asked in the past.

Pierre-Yves

**Comment by thomas-mangin** [comment]
Hi Pierre-Yves,

it is a good idea and I can see how this would be good, but this logic would be ideally placed in the forked process. So sorry work for you not me 😛 

But all is not bad, I have the code in ExaProxy which does the interface monitoring:
https://github.com/Exa-Networks/exaproxy/blob/master/lib/exaproxy/supervisor.py#L228


For the curious, this is how you balance traffic over multiple interface correctly.
Be careful Linux does not balance traffic on IPv6 AFAICS.

/etc/rc.local
---
```
/sbin/ip -4 route delete default
/sbin/ip -4 route add default nexthop via <gateway 1> nexthop via <gateway 2>
```

interfaces
---
```
iface eth0 inet static
       	address <ip 1>
       	netmask <netmask 1>
       	network <network 1>
       	broadcast <broadcast 1>
       	gateway <gateway 1>

       	# extra routes
       	post-up ip route add default via <gateway 1> dev eth0 table 101
       	post-up ip rule add from <network 1>/<netmask 1> lookup 101
       	post-up ip rule add from <network 1>/<netmask 1> to <network 1>/<netmask 1> lookup main

       	pre-down ip rule del from <network 1>/<netmask 1> lookup 101
       	pre-down ip route del default via <gateway 1> dev eth0 table 101
       	pre-down ip rule del from <network 1>/<netmask 1> to <network 1>/<netmask 1> lookup main
```

same thing with the second interface and a different lookup table (like 102 instead of 101)

**Comment by pyke369** [comment]
Understood, thanks Thomas. 

That was my assessment too (better in the co-process than in the core ExaBGP code). Re. your setup above, I played with the multiple-routing-tables" option in the past (a.ka. "howto do VRF in Linux") and preferred to stay away from it... ;-)

I will implement this feature in the exasrv.py co-process then: since we already have the interface corresponding to the BGP session in the configuration file, it shouldn't be hard to simulate a peer announces withdrawal (equivalent to what happens when a BGP peer/BGP session is torn down), leading to the corresponding local routes removal, when the interface is physically inoperative.

I'll close this issue, thanks again for your quick response.
Pierre-Yves.
