### ISSUE TITLE
exabgp do not send update message

### ISSUE THREAD

**Issue by wuxg** [Exa-Networks/exabgp#488]
In my server,ExaBgp has established bgp session with vyatta( with ip 201.3.1.1) successfully, and then the following code is invoked,but there isn't any update message sent out.
    `neighbor 201.3.1.1 announce route 192.41.9.0/24 next-hop 182.129.6.33`

anyone who gives me some hints is appreciated.

**Comment by thomas-mangin** [comment]
did you flush stdout ?

**Comment by thomas-mangin** [comment]
should you need more help, please provide the ExaBGP version you are running and some more information. I am a computer scientist, not a fortune teller :-)
