### ISSUE TITLE
add support for 6PE [RFC4798]

### ISSUE THREAD

**Issue by gklinich** [Exa-Networks/exabgp#490]
I see issue #382 was open and closed, but I'm not clear that RFC4798 is supported in exabgp

family "ipv4 nlri-mpls"  is supported, but family "ipv6 nlri-mpls" is not valid

I would expect "ipv6 nlri-mpls" to be AFI=2, SAFI=4, labeled IPv6 (6PE)

Am I missing something?  

I would like to see ipv6 labeled unicast supported

Thanks

**Comment by thomas-mangin** [comment]
Hi @gklinich 

If it works great, I can not check. If it doesn't please feel free to update this ticket but either way, I will not be able to do much about it in the coming weeks (and if recent trend continues, it may be longer).

Good luck !
