### ISSUE TITLE
Process cannot update as-path with "announce route" command.

### ISSUE THREAD

**Issue by simeonmiteff** [Exa-Networks/exabgp#498]
Updating the as-path in an `announce route` command from a process does not update the as-path in the BGP announced route. I got into this state by having the process send an incorrect as-path first [65000 65000], and then fixing it to subsequently send [65101 65101] without reloading exabgp. Here are log messages after fixing the `announce route`:

```
Sep 21 10:54:46 servicevm exabgp[22664]: Wed, 21 Sep 2016 10:54:46 | INFO     | 22664  | processes     | Command from process radsecproxy-services : announce route 192.0.2.3/32 next-hop self as-path [ 65101 65101 ]
Sep 21 10:54:46 servicevm exabgp[22664]: Wed, 21 Sep 2016 10:54:46 | INFO     | 22664  | reactor       | Route added to neighbor 192.0.2.1 local-ip 192.0.2.2 local-as 65101 peer-as 65100 router-id 192.0.2.2 family-allowed in-open : 192.0.2.3/32 next-hop 192.0.2.2 as-path [ 65101 65101 ]
Sep 21 10:54:47 servicevm exabgp[22664]: Wed, 21 Sep 2016 10:54:47 | INFO     | 22664  | reactor       | Performing dynamic route update
Sep 21 10:54:47 servicevm exabgp[22664]: Wed, 21 Sep 2016 10:54:47 | INFO     | 22664  | reactor       | Updated peers dynamic routes successfully
```

Here is exabgp re-establishing the BGP session, and sending out an update with the incorrect as-path:

```
Sep 21 10:55:20 servicevm exabgp[22664]: Wed, 21 Sep 2016 10:55:20 | INFO     | 22664  | network       | Connected to peer neighbor 192.0.2.1 local-ip 192.0.2.2 local-as 65101 peer-as 65100 router-id 192.0.2.2 family-allowed in-open (out)
Sep 21 10:55:20 servicevm exabgp[22664]: Wed, 21 Sep 2016 10:55:20 | INFO     | 22664  | network       | Peer   192.0.2.1 ASN 65100    out loop, peer reset, message [notification received (3,11)] error[UPDATE message error / Malformed AS_PATH / 0x40020A02020000FDE80000FDE8]
```

Note that in the error message coming back from the peer, 0x0000FDE80000FDE8 is [65000 65000]. Restarting exabgp fixed this. Is the as-path cached and not updated?

I'm running version 3.4.13 from the Ubuntu Xenial package.

**Comment by thomas-mangin** [comment]
My guess would be that it is related to the other issue with route re-announcement and I will look into it. Sorry for the bug !

**Comment by simeonmiteff** [comment]
@thomas-mangin no worries!

Very little pain experienced. Restarting exabgp was OK, since we're bringing up a new service.

I did some code reading and I suspect `exabgp.rib.store.insert_announced()` might be involved. I'm sorry I can't be more helpful at the moment.

**Comment by thomas-mangin** [comment]
Could you please let me know if this patch fixes the issue:
```
diff --git a/lib/exabgp/bgp/message/update/attribute/attributes.py b/lib/exabgp/bgp/message/update/attribute/attributes.py
index 9043935..a322e10 100644
--- a/lib/exabgp/bgp/message/update/attribute/attributes.py
+++ b/lib/exabgp/bgp/message/update/attribute/attributes.py
@@ -379,6 +379,9 @@ class Attributes (dict):
                #        will hash to the same value until repr represents the nh (??)
                return hash(repr(self))

+       def __eq__ (self, other):
+               return self.sameValuesAs(other)
+
        # BaGPipe code ..

        # test that sets of attributes exactly match
```

**Comment by thomas-mangin** [comment]
@tmmorin this change may affect bagpipe

**Comment by thomas-mangin** [comment]
no update, applying the patch as it should be "the right thing to do".
