### ISSUE TITLE
Exabgp send out less measage than print

### ISSUE THREAD

**Issue by wuxg** [Exa-Networks/exabgp#499]
Hi,

When I invoke print in loop, is seems that exabgp lost some message when i print too fast.
I tried to send 1000 update messages at a speed of 100 messages per second, but at last, only 993 update messages were sent out. There was no message lost when I send message at a speed of 50 messages per second.
I am sorry that I can't upload the log file because the network limitation.

**Comment by thomas-mangin** [comment]
Are you ack. every 'done' message before sending the message ? I have never had this issue but then the new feedback message is new - so it could be the cause.

**Comment by wuxg** [comment]
Hi,
It's a shame to say that I don't know how to  ack.  the "done" message. Is there any example?

**Comment by wuxg** [comment]
I just read the "done“ message from stdin and then discard it.

**Comment by thomas-mangin** [comment]
I have currently absolutely no time to hack for fun .. so sorry, can not do much - but if you send me your code per mail I will try to see if I can spot an issue.

**Comment by wuxinggui** [comment]
Hi,

I suspect there is something wrong in my code.My code as follow:
`class exabgpMsgProcesser(threading.Thread):
    def run(self):
        while True:
            try:
                r,_,_ = select.select([sys.stdin,],[],[],0)
                while r:
                    line = sys.stdin.readline()
                    r,_,_ = select.select([sys.stdin,],[],[],0)
            except KeyboardInterrupt:
                continue
            except IOError:
                continue
            except Exception:
                continue

                
exabgpMsgProcesser().start()

#caculate routes
for vyatta in vyattas:
    for route in routes[vyatta]:
        print route
        sys.stdout.flush()
        time.sleep(0.004) #
`

**Comment by azlux** [comment]
Your code don't have any indentation and it's not standalone. (we don't have any example of the vyattas variable)

**Comment by wuxinggui** [comment]
Hi,
My exabgp version is master.
My configure is as follow:

process api-add-remove {
    encoder json;
    run /usr/local/python/bin/python /root/vyatta348/api-add-remove.run;
}

neighbor 201.3.1.1 {
    router-id 201.3.1.1;
    local-address 201.3.254.1;
    local-as 301;
    peer-as 301;
    auto-flush true;
    capability {
        graceful-restart 1;
    }

    api {
        processes [ add-remove ];
    }
}

neighbor 201.3.2.1 {
    router-id 201.3.2.1;
    local-address 201.3.254.1;
    local-as 302;
    peer-as 302;
    auto-flush true;
    capability {
        graceful-restart 1;
    }

    api {
        processes [ add-remove ];
    }
}


The following code can reproduce the problem. Without a sleep in the loop, there isn't any update message sent out, I want to find a way to send update messages as fast as possable.

import os, sys, select, threading, time

time.sleep(10)

for s1 in range(1,255):
    for s2 in range(1,255):
        for s3 in range(1,255):
            print "neighbor 201.3.1.1 announce route 10.%d.%d.%d/32 next-hop 201.3.2.1" % (s1,s2,s3)
            sys.stdout.flush()
            time.sleep(0.1)  #without this line, no message is sent out
            r,_,_ = select.select([sys.stdin,],[],[],0)
            while r:
                line = sys.stdin.readline()
                line = line.strip()
                if line == "done":
                    break
                r,_,_ = select.select([sys.stdin,],[],[],0)

**Comment by wuxinggui** [comment]
Hi,
My exabgp version is master.
My configure is as follow:

process api-add-remove {
     encoder json;
     run /usr/local/python/bin/python /root/vyatta348/api-add-remove.run;
 }

neighbor 201.3.1.1 {
     router-id 201.3.1.1;
     local-address 201.3.254.1;
     local-as 301;
     peer-as 301;
     auto-flush true;
     capability {
     graceful-restart 1;
 }
     api {
         processes [ add-remove ];
     }
}

neighbor 201.3.2.1 {
     router-id 201.3.2.1;
     local-address 201.3.254.1;
      local-as 302;
      peer-as 302;
      auto-flush true;
      capability {
           graceful-restart 1;
      }
     api {
         processes [ add-remove ];
     }
}

The following code can reproduce the problem. Without a sleep in the loop, there isn't any update message sent out, I want to find a way to send update messages as fast as possable.

import os, sys, select, threading, time

time.sleep(10)

for s1 in range(1,255):
     for s2 in range(1,255):
          for s3 in range(1,255):
               print "neighbor 201.3.1.1 announce route 10.%d.%d.%d/32 next-hop 201.3.2.1" % (s1,s2,s3)
               sys.stdout.flush()
               time.sleep(0.1) #without this line, no message is sent out
               r,x,y = select.select([sys.stdin,],[],[],0)
               while r:
                    line = sys.stdin.readline()
                    line = line.strip()
                    if line == "done":
                         break
               r,x,y = select.select([sys.stdin,],[],[],0)

**Comment by wuxinggui** [comment]
Hi,
My exabgp version is master.
My code is as follow:

`import os, sys, select, threading, time

time.sleep(10)

for s1 in range(1,255):
    for s2 in range(1,255):
        for s3 in range(1,255):
            print "neighbor 201.3.1.1 announce route 10.%d.%d.%d/32 next-hop 201.3.2.1" % (s1,s2,s3)
            sys.stdout.flush()
            time.sleep(0.1)
            r,_,_ = select.select([sys.stdin,],[],[],0)
            while r:
                line = sys.stdin.readline()
                line = line.strip()
                if line == "done":
                    break
                r,_,_ = select.select([sys.stdin,],[],[],0)
`

my configure is as follow:
`process api-add-remove {
    encoder json;
    run /usr/local/python/bin/python /root/vyatta348/api-add-remove.run;
}

neighbor 201.3.1.1 {
    router-id 201.3.1.1;
    local-address 201.3.254.1;
    local-as 301;
    peer-as 301;
    auto-flush true;
    capability {
        graceful-restart 1;
    }

    api {
        processes [ add-remove ];
    }
}

neighbor 201.3.2.1 {
    router-id 201.3.2.1;
    local-address 201.3.254.1;
    local-as 302;
    peer-as 302;
    auto-flush true;
    capability {
        graceful-restart 1;
    }

    api {
        processes [ add-remove ];
    }
}
`

**Comment by wuxinggui** [comment]
sorry to say that all indentations are missing after I commit.
I want to find a way to send routes as fast as possable, but I can not send out any message with a sleep in the loop.

**Comment by wuxinggui** [comment]
sorry to say that all indentations are missing after I commit.
 I want to find a way to send routes as fast as possable, but I can not send out any message without a sleep in the loop.

**Comment by thomas-mangin** [comment]
having a quick look - not sure why you have
```
if line == "done":
   break
```
It mean that if the line is "done", you do not try to consume anymore from stdin, which seems wrong to me. 

I would replace these two lines with:
```
if line != "done":
   sys.exit(1)
```

**Comment by wuxinggui** [comment]
Hi，
Thanks for your reply.The break is used for consuming **only one** "done" message in each print loop. I want to send route update messages as fast as possible, is there any suggestion about this?
BTW, do you have some data on the fastest speed of sending messages of exabgp? such as approximate fastest speed.

**Comment by thomas-mangin** [comment]
Hi,

This is totally ill advised. You will not get a 'done' message fast enough, therefore your select will return nothing, and later on, the first command will be acked, and you will read one 'done'.
Over time, a number of message will accumulate on the pipe and things will break as you see.

You do not need to ACK the "done" message before sending the next command. We ack the message in the order the command were sent.

Your code is buggy. Please update it as suggested and AFAICS, the issue you report should vanish !

**Comment by thomas-mangin** [comment]
I take the lack of activity on this issue as a sign all is going. closing. feel free to re-open if required.
