### ISSUE TITLE
Problem with monitoring of outgoing updates

### ISSUE THREAD

**Issue by dalibort** [Exa-Networks/exabgp#500]
Hi Thomas,

I am able to monitor updates received from a neighbor. But I am not able to monitor updates ExaBGP sends to a neighbor. There is what I want:
- using a script (exabgp.cmd) I inject a route/flowspec update to ExaBGP
- ExaBGP sends the update to its neigbors and calls my script which will send the updates to a database. But the script is never called on outgoing updates (either bug in my config or in ExaBGP code)
  I just want to see/log what the ExaBGP is announcing to the neighbors.

I  use this cfg (in the reality there are 2 neighbors with the same CFG)

```
    process service-dynamic {
        run /usr/bin/socat stdout pipe:/var/run/exabgp.cmd;
        encoder text;
    }
    process tcp-control {
        run /usr/bin/python /usr/src/gits/exabgp/etc/exabgp/processes/tcp-server;
        encoder text;
    }
    process http-api {
        run /usr/bin/python /root/exabgp/http-test.py;
        encoder text;
    }
    process mylogger {
        run /usr/local/bin/exabgp2db.php;
        encoder json;
    }

    neighbor x.y.z.1 {
        hold-time 180;
        # local AS number
        local-as 28851;
        # Remote AS number
        peer-as 28851;
        # ID for this ExaBGP router
        router-id 10.0.8.3;
        # Local IP addess which used for connections to this peer
        local-address 10.0.8.3;
        description "ASR_Sitel1";
        family  {
                        ipv4 flow;
                }

        api speaking    {
                        processes [ mylogger ];
                        neighbor-changes;

                        receive {
#                                parsed;
#                                open;
#                                update;
                        }

                        send    {

                                 notification;
                                 open;
                                 update;
                                 operational;
                                 refresh;
                                parsed;
                                keepalive;
                                update;
                        }
                }
}
```

The logger process receives only notification about neighbors going UP (and info about exaBGP going down when I kill it)

Note: I tried to run second ExaBGP on the same server to connect it to the first one as another neighbor (using non-default BGP TCP port) in a hope I will be able to monitor the updates on receiving end. It never worked - the first or second copy of ExaBgp crashed and the BGP connection failed periodically.

Regards
D. Toman

**Comment by thomas-mangin** [comment]
It seems you are not the only one saying it does not send the send updates .. I need to investigate.

**Comment by thomas-mangin** [comment]
fixed with the patch
https://github.com/Exa-Networks/exabgp/commit/9262dbc96aeaa4a8b63252c592f0a45984221563

**Comment by thomas-mangin** [comment]
@dalibort Can I close this issue ?

**Comment by thomas-mangin** [comment]
And again sorry, I did not realise your answer on the patch had not made it to this thread and was just waiting for you to reply ..
