### ISSUE TITLE
Fill in IETF Large BGP Communities feature report

### ISSUE THREAD

**Issue by job** [Exa-Networks/exabgp#502]
Hi Thomas,

Since you are the boss, can you please fill in the feature report on https://trac.tools.ietf.org/wg/idr/trac/wiki/draft-ietf-idr-large-community%20implementations for ExaBGP?

I'll handle the InterOP with other daemons later in a lab, but the implementation specific features such as "dedup", "malformed treat as withdraw", etc questions belong with you! :)

- Job

**Comment by thomas-mangin** [comment]
A good report exists at : https://github.com/pierky/large-bgp-communities-playground/tree/master/tests

**Comment by thomas-mangin** [comment]
https://trac.tools.ietf.org/wg/idr/trac/wiki/draft-ietf-idr-large-community%20implementations updated
