### ISSUE TITLE
Modifying hello/hold timers for neighbors?

### ISSUE THREAD

**Issue by kvicknair** [Exa-Networks/exabgp#505]
exabgp: 9858   network       Peer      10.251.1.1 ASN XXXX   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]

In an attempt to peer with a Juniper acx lab router for testing bgp flowspec. My Juniper keeps sending connection rejects periodically because of mismatch hello and hold timers. I found the syntax to modify hold times per neighbor but wasn't finding anywhere to modify hello timers?

Any feedback would be helpful. Thanks!

**Comment by thomas-mangin** [comment]
hello timer ? this is not something BGP has. Could you please send us the Juniper logs ?

**Comment by kvicknair** [comment]
I was able to get the peer to become stable by setting the juniper to a manual hold-time of 180 sec. However, I would like to modify exabgp instead to match juniper defaults. You may refer to these "hello timers" as Keepalive timers.

Mon, 03 Oct 2016 09:25:18 3670   network       Peer      10.251.1.1 ASN 27294   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]
Mon, 03 Oct 2016 09:25:25 28413  network       Peer      10.251.1.1 ASN 27294   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]
Mon, 03 Oct 2016 09:25:26 3670   network       Peer      10.251.1.1 ASN 27294   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]
Mon, 03 Oct 2016 09:25:35 3670   network       Peer      10.251.1.1 ASN 27294   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]
Mon, 03 Oct 2016 09:25:44 28413  network       Peer      10.251.1.1 ASN 27294   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]
Mon, 03 Oct 2016 09:25:46 3670   network       Peer      10.251.1.1 ASN 27294   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]
Mon, 03 Oct 2016 09:25:59 3670   network       Peer      10.251.1.1 ASN 27294   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]
Mon, 03 Oct 2016 09:26:05 28413  network       Peer      10.251.1.1 ASN 27294   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]
Mon, 03 Oct 2016 09:26:14 3670   network       Peer      10.251.1.1 ASN 27294   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]
Mon, 03 Oct 2016 09:26:30 28413  network       Peer      10.251.1.1 ASN 27294   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]
Mon, 03 Oct 2016 09:26:32 3670   network       Peer      10.251.1.1 ASN 27294   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]
Mon, 03 Oct 2016 09:26:53 3670   network       Peer      10.251.1.1 ASN 27294   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]
Mon, 03 Oct 2016 09:27:00 28413  network       Peer      10.251.1.1 ASN 27294   out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]

**Comment by thomas-mangin** [comment]
keepalive interval time = holdtime /3 - this is defined by the RFC.

**Comment by thomas-mangin** [comment]
The RFC says, a connection can be refused on the basis of a holdtime value. So a router can refuse to establish a very low or very high holdtime if they want.

**Comment by kvicknair** [comment]
Thanks for the clarification Thomas. I was able to get this issue sorted out.
