### ISSUE TITLE
centos 6.8 install exabgp

### ISSUE THREAD

**Issue by bgpkclee** [Exa-Networks/exabgp#507]
1. I would like to install the latest version of exabgp and using the below steps.

git clone https://github.com/Exa-Networks/exabgp.git
git checkout master

2. try to do a health check but seems there's some error?
[root@wg bin]# ./healthcheck
usage: healthcheck.py [-h] [--debug | --silent | --syslog-facility [FACILITY]
                      | --no-syslog] [--name NAME] [--config FILE]
                      [--pid FILE] [--user USER] [--group GROUP]
                      [--interval N] [--fast-interval N] [--timeout N]
                      [--rise N] [--fall N] [--disable FILE] [--command CMD]
                      [--next-hop IP] [--ip IP] [--no-ip-setup]
                      [--label LABEL] [--start-ip N] [--up-metric M]
                      [--down-metric M] [--disabled-metric M] [--increase M]
                      [--community COMMUNITY]
                      [--large-community LARGECOMMUNITY] [--as-path ASPATH]
                      [--withdraw-on-down] [--execute CMD] [--up-execute CMD]
                      [--down-execute CMD] [--disabled-execute CMD]
healthcheck.py: error: unrecognized arguments: --folder /exabgp/etc/exabgp

3. check the version. is this the latest version?

[root@wg sbin]# ./exabgp -v
ExaBGP : master-ff81ce0f906713051fced4cf6365a92f1e020a4e
Python : 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]
Uname  : Linux wg1.hkg.bgp.net 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 00:57:44 UTC 2016 x86_64

**Comment by thomas-mangin** [comment]
This is an `ANCIENT` version. You must have it installed by your OS .. try to remove it with your package manager. It should say 3.4.17

**Comment by thomas-mangin** [comment]
once you have it removed you can run 3.4.17 by running
`pip install exabgp`
it is not master but it is the latest stable.

**Comment by thomas-mangin** [comment]
`python -m exabgp healthcheck --help` 
if you need to use healthcheck

**Comment by bgpkclee** [comment]
Thomas, I installed the "ancient" version by using GIT.
How do i install the latest version 4.xx by using git?

**Comment by thomas-mangin** [comment]
Sorry - going to fast - you are using python 2.6 not exabgp 2.6

**Comment by thomas-mangin** [comment]
There is not yet a version 4.0 - I was a blog who said it did as I used to have a 4.0 branch - as as result I deleted it. This is the latest version.

**Comment by thomas-mangin** [comment]
or was at the time of the pull.

**Comment by thomas-mangin** [comment]
it depends on how it was installed. you can install version 3 using pip

https://pypi.org/project/exabgp/3.4.26/

**Comment by MAK4789** [comment]
Hi Thomas,

Thanks alot for the help. i have installed ExaBGP version 3 now via "> python setup.py install", all looks good now. Can you please confirm that how can we start the exabgp services? as i have tried "systemctl start exabgp" & "systemctl start exabgp-3.4.26" but no luck.

Regards,

Muhammad Ali
+92-346-2750502
________________________________

**Comment by thomas-mangin** [comment]
There is a systemd file in `etc/systemd/exabgp.service`. You will have to install it (update the binary path) to make it work.

**Comment by MAK4789** [comment]
Hi Thomas,

Thank you so much for your support. It helps me to establish iBGP as well. Can you please confirm that how can we run BGP commands on ExaBGP? is it under below path??

cd /etc/exabgp-3.4.26/bin/ ./exabgpcli

Furthermore, can you please also confirm if ExaBGP required any API to run?

Your kind support will be highly appreciated in this regard.

Regards,

Muhammad Ali
+92-346-2750502
________________________________

**Comment by thomas-mangin** [comment]
I do support ExaBGP when something does not work but do not have the time to teach people Unix. I would expect users to have some Unix skills to use ExaBGP. If you are looking for a cli, Bird or Quagga/FRR may be better choices/
