### ISSUE TITLE
exabgp.cfg and exabgp.env not be found after exabgp installation

### ISSUE THREAD

**Issue by zmask37** [Exa-Networks/exabgp#509]
Hello,

I have installed exabgp from git repo. But it seems strange that exabgp.conf and exabgp.env config related files are not be seen in the /etc/exabgp directory

**Comment by thomas-mangin** [comment]
hello @zmask37 - can you please explain to me how you installed it ? There is so many ways 😭 
the best ways are surely:
```
> pip install exabgp
```
or from the code folder from github
```
> python setup.py install
```
then it should look into /etc otherwise it will look in the code folder.

**Comment by zmask37** [comment]
Hello @thomas-mangin . I did  > pip install exabgp. Then i did not see the conf and env file. So i just tried getting it from git
> git clone https://github.com/Exa-Networks/exabgp.git

But still i didn't see the files :fearful:

**Comment by thomas-mangin** [comment]
The files are not created by default.

you can generate a file with the default value with `exabgp --fi > /etc/exabgp/exabgp.env`
then if you edit it and run `exabgp --di` or `exabgp --de` you should see your changes only.

**Comment by zmask37** [comment]
This is great. Thanks for the info. I think this was missing :+1:

**Comment by mattoddy** [comment]
Hi Thomas, from what directory should I be running this command from as I just get '-bash: exabgp: command not found'. Thanks.

**Comment by thomas-mangin** [comment]
This is a different question. I believe your issue with not with ExaBGP but with understanding how pip/git and the bash $PATH work. This is not an issue with the program. You can ask on the mailing list for help. https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path
