### ISSUE TITLE
FIB Manipulation

### ISSUE THREAD

**Issue by lisroach** [Exa-Networks/exabgp#511]
Hello! I am planning on adding FIB manipulation functionality to exaBGP. Any input from the community is appreciated :)

Here are some of my thoughts so far: 

Linux itself has a FIB where we can store the source, destination, next-hop IP's and interface. What we need to create is a BGP-table in addition to that, where we store all of the BGP routes and their metrics. Then a function determines which routes from the BGP-table are the optimal routes and injects those into the FIB table.

There are two libraries I've found to choose from: [IPDB and IPRoute](http://docs.pyroute2.org/ipdb.html#ipdb-vs-iproute). IPDB starts several implicit threads, and keeps a cache of pulled objects, making it better for applications that request lots of objects from the network device. IPRoute is an alternative that essentially does the same things as IPDB, just without starting new threads, and it grabs the whole network object every single time instead of keeping a cache. 

I am leaning towards IPDB for the efficiency gain, but Thomas pointed out that multi-threading could lead to some harder to debug issues.

Those are my thoughts so far, I'm sure I'll have a lot more as I get started coding. 

Thanks,
Lisa

**Comment by thomas-mangin** [comment]
Lisa, I do believe that you are heading in the right direction with IPDB. I think the threading issue are totally manageable (if/when encountered). So I would agree with your assessment (disclaimer, I have not read the code of neither library).

**Comment by thomas-mangin** [comment]
@dpiekacz @pyke369 @vincentbernat @tmmorin @crazed @lazy404 @he32 @job @lochiiconnectivity - Just thought about you 😜

**Comment by vincentbernat** [comment]
Another solution would be to use ZServ from Quagga. You get compatibility with non-Linux OS.

**Comment by doddt** [comment]
Does ZServ support flowspec? AFAICT from online reading, it still does not. I agree that IPDB multithreading issues should be manageable.

**Comment by lisroach** [comment]
I've been thinking about ZServ. I don't have experience with it and the documentation (or lack there-of) is a little daunting, plus I like the idea of keeping exaBGP as Python centric as possible. 

I can't find anything about flowspec support for ZServ either.

**Comment by thomas-mangin** [comment]
Hello @lisroach - it seems that you had some change of career and are therefore no able to work on this project anymore. If this is indeed the case, feel free to close this issue and either way, thank you very much for your work on ExaBGP.

**Comment by lisroach** [comment]
Hey @thomas-mangin, you are right I have had a career change and have not found the time to come back to this :( I will close the issue for now but I hope to come back to it, this is a really fun project and I love ExaBGP!
