### ISSUE TITLE
forward port check

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#513]
check if https://github.com/Exa-Networks/exabgp/pull/512 need to be forward ported

**Comment by brijohn** [comment]
When I created #512 I checked master branch and it appears that it was already defaulting to a zero offset if it was omitted on ipv6 flowspec source and destination matches.

**Comment by thomas-mangin** [comment]
Thank - I was not sure if I had already coded it or not - hence the reminder for me.
