### ISSUE TITLE
ttl-security broken on IPv6 (mea culpa)

### ISSUE THREAD

**Issue by borjam** [Exa-Networks/exabgp#515]
My fix does not apply to IPv6 sockets, as IP_TTL is exclusively an IPv4 option.

The correct option is IPV6_UNICAST_HOPS (per /usr/include/netinet6/in6.h).

Anyway, is it appropiate to use the ttl-security clause for an IPv6 neighbor, or should we use a different, more ipvsixish term, such as "max-unicast-hops"?

If using ttl-security is fine, the network code should apply the right option (IPV6_UNICAST_HOPS) rather than IP_TTL. At least on BSD both have the same numerical value (4) but of course Python is stricter :)

If using ttl-security is not correct, then ttl-security should be rejected for IPv6 neighbors, and a new configuration option should be defined for them.

**Comment by thomas-mangin** [comment]
IMHO, the syntax should not change the name of the option but change the behaviour depending on the family. If the name need to be changed to reflect positive counting instead of hops, happy to change the option semantic on master as it is has not yet seen a stable release.

**Comment by borjam** [comment]
Aye aye Sir!

I'm adding a TTLv6 function rather than overloading the existing TTL for IPv4. The code looks less cluttered I think.

**Comment by borjam** [comment]
Done. Sorry for the noisy pull request.

I've verified with a tcpdump at it works at least on FreeBSD.

Cheers,




Borja.

**Comment by thomas-mangin** [comment]
Thank you - closing :-)
