### ISSUE TITLE
Support for BLACKHOLE BGP Community

### ISSUE THREAD

**Issue by tking** [Exa-Networks/exabgp#516]
Hi Exabgp developers,

could you please add support for the BLACKHOLE BGP community ( https://tools.ietf.org/html/draft-ietf-grow-blackholing-03 ) which will soon be published as RFC 7999?

Could you please add the BLACKHOLE BGP community to the list of well-known BGP communities (e.g., CLI and filtering)?

Best regards,
Thomas

**Comment by thomas-mangin** [comment]
was it not already implemented by @job ?

**Comment by thomas-mangin** [comment]
https://tools.ietf.org/html/rfc7999

**Comment by thomas-mangin** [comment]
Yes was implemented in master
https://github.com/Exa-Networks/exabgp/commit/12ff1f9575172a0872917185df578bce6adc4e18

**Comment by thomas-mangin** [comment]
It should be able to backport to 3.4 if required.

**Comment by thomas-mangin** [comment]
backport done.
