### ISSUE TITLE
forward port IPv6 support for ttl-security

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#519]
Forward port
https://github.com/Exa-Networks/exabgp/pull/518

**Comment by borjam** [comment]
I've added it to the master branch. 

I see that the ttl-security option has been deprecated and now it is outgoing-ttl. 

incoming-ttl (which as far as I know won't work on IPv6, I can't find the relevant socket option) should be used both on incoming and outgoing connections in muy opinion. And anyway, has it even worked? At least on my Python install I don't think MIN_TTL is defined. 

Anyway, creating a pull request for outgoing-ttl for now.

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/pull/520

**Comment by thomas-mangin** [comment]
Happy with the patch as it stands - Thanks.
