### ISSUE TITLE
pip install exabgp failed

### ISSUE THREAD

**Issue by hunter-nl** [Exa-Networks/exabgp#524]
I get this error:
`# pip install exabgp
Collecting exabgp
  Using cached exabgp-3.4.17.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wbybac_8/exabgp/setup.py", line 47
        """
          ^
    SyntaxError: Missing parentheses in call to 'print'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wbybac_8/exabgp/`

python version 2.7.5

I also tried with pip3 (python 3.4.3) resulting in same error.

**Comment by thomas-mangin** [comment]
Hi, just tried on my machine right now and it worked fine (osx). try to run`pip uninstall exabgp` and then reinstall.

**Comment by thomas-mangin** [comment]
`pip3` will not work, exabgp is a `python2` application

**Comment by thomas-mangin** [comment]
without a update - I will assume all is now fine and will close the issue. Feel free to re-open if it is not right.

**Comment by hydratim** [comment]
Why? Python 2 is deprecated https://pythonclock.org
Maintaining Python 2 only code is silly, updating to Python 3 will not break backwards compatibility. A Quick check with 2to3 doesn't (at first glance) hit any issues or create any apparent security risks, so why not start the migration process?

**Comment by thomas-mangin** [comment]
@hydratim

I still have to see if no-one takes on the security support of python2 after 2020, which is quite some time away, but to answer the "why":

It will upset quite a few people running ExaBGP in production when they find out that ONE commit just broke their installation (many people do run master in production).
Also, no user ever asked me for a python3 port. I am asked for features or bug fixes: very few people will care which version of python the code ExaBGP runs on as long as it runs. Finally, BaGPipe uses ExaBGP as its decoding library and they are also python2.

That said, feel free to provide me a patch for python 3 support on master and I will happily merge it for master before the upcoming 4.0.0 release (but I will not change the 3.4 stable branch). I will need to give warning and make sure the breakage is CLEAR when the merging happens too.

**Comment by thomas-mangin** [comment]
@hydratim something much more urgent: update the SSL certificate for https://liquidns.com/ as it is expired ....

**Comment by vincentbernat** [comment]
If Python 2.6 support is dropped, it is easier to have code compatible with both Python 3.3+ and Python 2.7 (without some kind of compatibility layer like "six"). Of course, it still means some work.

**Comment by hydratim** [comment]
@thomas-mangin Hardly, that's a deprecated url for a deprecated service. I think my profile is the only one that still points to that url (changed now).
Why are you still supporting 2.6? That was EOL'd already!

**Comment by vincentbernat** [comment]
EOL upstream, but still supported by some distributions (like RHEL 5). That will be the same thing for Python 2.7. We can't ask users to change their whole OS just to run ExaBGP. In some environment, they have to use only packages distributed by the distribution. This means no Python 3 for RHEL 6/7 either (but users who don't have those restrictions can get them through SCL).

**Comment by thomas-mangin** [comment]
👍 @vincentbernat's answer - he beat me to it of a few seconds :-)

**Comment by thomas-mangin** [comment]
One of the nice things about ExaBGP is that it can just be installed as a binary as it has no dependencies. I would like to keep it that way. Python3 is just starting to become the 'main python' on recent Ubuntu LTS. I guess than in around a year, it would be reasonable to have it python3. I would hope 4.0.0 is released by then 😉
