### ISSUE TITLE
AS-path / Extended length handling problem

### ISSUE THREAD

**Issue by pierky** [Exa-Networks/exabgp#525]
Hello,

I'm encountering a problem with as-path handling:

```
...| message       | Peer       192.0.2.6 ASN 65539   << UPDATE
...| parser        | parsing UPDATE (  49) 0000 0028 4001 0100 5002 000A 0202 0001 0003 0001 0002 4003 04C0 0002 06C0 200C 0001 0002 0000 0001 0000 0001 20CB 0071 1F
...| parser        | withdrawn NLRI none
...| parser        | attribute origin             flag 0x40 type 0x01 len 0x01 payload 00
...| message       | Peer       192.0.2.6 ASN 65539   Could not decode message "2"
...| message       | Peer       192.0.2.6 ASN 65539   unsupported operand type(s) for +: 'int' and 'str'
...| message       | Traceback (most recent call last):
...| message       |   File "/root/exabgp-master/lib/exabgp/reactor/protocol.py", line 208, in read_message
...| message       |     message = Message.unpack(msg_id,body,self.negotiated)
...| message       |   File "/root/exabgp-master/lib/exabgp/bgp/message/message.py", line 181, in unpack
...| message       |     return cls.klass(message).unpack_message(data,negotiated)
...| message       |   File "/root/exabgp-master/lib/exabgp/bgp/message/update/__init__.py", line 269, in unpack_message
...| message       |     attributes = Attributes.unpack(_attributes,negotiated)
...| message       |   File "/root/exabgp-master/lib/exabgp/bgp/message/update/attribute/attributes.py", line 274, in unpack
...| message       |     attributes = cls().parse(data,negotiated)
...| message       |   File "/root/exabgp-master/lib/exabgp/bgp/message/update/attribute/attributes.py", line 366, in parse
...| message       |     return self.parse(left,negotiated)
...| message       |   File "/root/exabgp-master/lib/exabgp/bgp/message/update/attribute/attributes.py", line 321, in parse
...| message       |     length = (length << 8) + data[3]
...| message       | TypeError: unsupported operand type(s) for +: 'int' and 'str'
...| message       |
...| network       | Peer       192.0.2.3 ASN 65537   connection to 192.0.2.3:179 failed
...| message       | Peer       192.0.2.6 ASN 65539   >> NOTIFICATION (1,0,"can not decode update message of type "2"")
...| network       | Peer       192.0.2.6 ASN 65539   out loop, peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]
```

It seems that `data[3]` is a string while it should be an int: I "fixed" it by doing this (just to have a working version of the `.parse` for this scenario):

```
length = (length << 8) + ord(data[3])
```

(but please don't try it at home!)

```
...| routes        | peer 192.0.2.6 ASN 65539   << UPDATE (4) nlri  (   5) 203.0.113.35/32 next-hop 192.0.2.6
...| message       | Peer       192.0.2.6 ASN 65539   << UPDATE
...| parser        | parsing UPDATE (  61) 0000 0034 4001 0100 5002 000A 0202 0001 0003 0001 0002 4003 04C0 0002 06C0 2018 0000 FFFF 0000 0001 0000 0001 FFFF FFFF FFFF FFFF FFFF FFFF 20CB 0071 24
...| parser        | withdrawn NLRI none
...| parser        | attribute origin             flag 0x40 type 0x01 len 0x01 payload 00
...| parser        | attribute as-path            flag 0x50 type 0x02 len 0x0a payload 0202 0001 0003 0001 0002
```

**Comment by thomas-mangin** [comment]
`./sbin/exabgp qa/conf/simple-v4.conf --decode "0000 0034 4001 0100 5002 000A 0202 0001 0003 0001 0002 4003 04C0 0002 06C0 2018 0000 FFFF 0000 0001 0000 0001 FFFF FFFF FFFF FFFF FFFF FFFF 20CB 0071 24" 2>&1 | grep json`

ExaBGP 3.4

`Mon, 31 Oct 2016 18:25:19 | INFO     | 13004  | parser        | update json { "exabgp": "3.4.0", "time": 1477938319, "host" : "ptr-34.212.219.82.rev.exa.net.uk", "pid" : "13004", "ppid" : "95603", "counter": 1, "type": "update", "neighbor": { "ip": "10.0.0.3", "address": { "local": "10.0.0.2", "peer": "10.0.0.3"}, "asn": { "local": "65533", "peer": "65533"}, "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 65539, 65538 ], "confederation-path": [], "attribute-0x20-0xE0": "0x0000ffff0000000100000001ffffffffffffffffffffffff" }, "announce": { "ipv4 unicast": { "192.0.2.6": { "203.0.113.36/32": {  } } } } } }} }`

ExaBGP master

`./sbin/exabgp qa/conf/simple-v4.conf --decode "0000 0034 4001 0100 5002 000A 0202 0001 0003 0001 0002 4003 04C0 0002 06C0 2018 0000 FFFF 0000 0001 0000 0001 FFFF FFFF FFFF FFFF FFFF FFFF 20CB 0071 24" 2>&1 | grep json
Mon, 31 Oct 2016 18:26:59 | INFO     | 13122  | parser        | update json { "exabgp": "3.5.0", "time": 1477938419.01, "host" : "ptr-34.212.219.82.rev.exa.net.uk", "pid" : 13122, "ppid" : 95603, "counter": 1, "type": "update", "neighbor": { "address": { "local": "127.0.0.1", "peer": "127.0.0.1" }, "asn": { "local": "65533", "peer": "65533" }, "direction": "in", "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 65539, 65538 ], "confederation-path": [], "large-community": [ [ 65535, 1 , 1 ], [ 4294967295, 4294967295 , 4294967295 ] ] }, "announce": { "ipv4 unicast": { "192.0.2.6": [ { "nlri": "203.0.113.36/32" } ] } } } } } }`

**Comment by thomas-mangin** [comment]
Thank you for the report and the fix - it was the right one !
