### ISSUE TITLE
Exabgp sends messages with multiple MP_(UN)REACH_NLRI attributes

### ISSUE THREAD

**Issue by brijohn** [Exa-Networks/exabgp#530]
When using flowspec announcements or withdraws we have noticed that when sending ipv4 and ipv6 flowspec rules exabgp will group both families into a single update message by using two MP_REACH or MP_UNREACH path attributes one for each family.

According to Section 5 of RFC4271 this is invalid
> The same attribute (attribute with the same type) cannot appear more
> than once within the Path Attributes field of a particular UPDATE
> message.

When testing this on a Juniper MX router it sends us a notification message back about malformed attribute list. The cisco ASR9k we tested just seems to ignore the second MP_REACH attribute.

[exabgp-malformed-batched-mpreach-nlris-example.pcap.gz](https://github.com/Exa-Networks/exabgp/files/571873/exabgp-malformed-batched-mpreach-nlris-example.pcap.gz)

**Comment by thomas-mangin** [comment]
Hello @brijohn - what version of ExaBGP are you using as this was fixed quite some time ago AFAIR.

**Comment by thomas-mangin** [comment]
The quick fix if it happens on your version is to disable the 'group-updates' feature.

**Comment by brijohn** [comment]
We using version 3.4.16.  Do you know what commit this was fixed in? 

The way I read the group-updates feature is that if that is disabled then each announce/withdraw will be sent in its own UPDATE message packet. This would cause performance and scale issues for us, so if you can point out which commits fixed this issue I can backport them to our branch.

**Comment by thomas-mangin** [comment]
Version 3.4.17
 * Fix: only one MP NLRI is allow per UPDATE
    reported by: subsecond

**Comment by thomas-mangin** [comment]
Sorry - I do not know which commit fix it, I would need to look at things like you would ...
