### ISSUE TITLE
Issue in update neighbors with routes received by application

### ISSUE THREAD

**Issue by ricardo-bennesby** [Exa-Networks/exabgp#533]
Hi everyone,

I am using ExaBGP 3.4.10 to exchange BGP Updates between my application and 6 nodes running Quagga. Each Quagga node is connected only to my aplication running ExaBGP.

When I run this scenario with only 4 Quagga nodes, everything works fine, because Exabgp sends neighbors the updates as soon as they are received. However, with 6 nodes, all updates commands are received by Exabgp but the last updates take a long time to be delivered.

Observing the log messages, I see that the routes are always delivered when reactor  adds the routes to neighbor and performs dynamic route update. The following pattern happens for all the successfully delivered updates:

processes     | Command from process announce-routes : neighbor 192.0.1.136 announce route 122.172.0.0/24 next-hop self origin egp as-path [ 65008 65012  ] 
processes     | Command from process announce-routes :  
reactor       | Command from process not understood : 
processes     | Command from process announce-routes :  
reactor       | Command from process not understood : 
reactor       | Route added to neighbor 192.0.1.136 local-ip 192.0.1.110 local-as 65008 peer-as 65013 router-id 192.0.1.110 family-allowed in-open : 122.172.0.0/24 next-hop 192.0.1.110 origin egp as-path [ 65008 65012 ]
reactor       | Performing dynamic route update
reactor       | Updated peers dynamic routes successfully

processes     | Command from process announce-routes : neighbor 192.0.1.135 announce route 123.172.0.0/24 next-hop self origin egp as-path [ 65008 65013  ] 
processes     | Command from process announce-routes :  
reactor       | Command from process not understood : 
processes     | Command from process announce-routes :  
reactor       | Command from process not understood : 
reactor       | Route added to neighbor 192.0.1.135 local-ip 192.0.1.110 local-as 65008 peer-as 65012 router-id 192.0.1.110 family-allowed in-open : 123.172.0.0/24 next-hop 192.0.1.110 origin egp as-path [ 65008 65013 ]
reactor       | Performing dynamic route update
reactor       | Updated peers dynamic routes successfully

processes     | Command from process announce-routes : neighbor 192.0.1.135 announce route 121.172.0.0/24 next-hop self origin egp as-path [ 65008 65011  ] 
processes     | Command from process announce-routes :  
reactor          | Command from process not understood : 
processes     | Command from process announce-routes :  
reactor          | Command from process not understood : 
reactor          | Route added to neighbor 192.0.1.135 local-ip 192.0.1.110 local-as 65008 peer-as 65012 router-id 192.0.1.110 family-allowed in-open : 121.172.0.0/24 next-hop 192.0.1.110 origin egp as-path [ 65008 65011 ]
reactor          | Performing dynamic route update
reactor       | Updated peers dynamic routes successfully

The last updates was received by ExaBGP but not added to neighbor by reactor. For example:

processes     | Command from process announce-routes : neighbor 192.0.1.135 announce route 125.172.0.0/24 next-hop self origin egp as-path [ 65008 65015  ] 
processes     | Command from process announce-routes :  
reactor       | Command from process not understood : 
processes     | Command from process announce-routes :  
reactor       | Command from process not understood : 

processes     | Command from process announce-routes : neighbor 192.0.1.135 announce route 200.0.0.0/24 next-hop self 
processes     | Command from process announce-routes :  
reactor       | Command from process not understood : 
processes     | Command from process announce-routes :  
reactor       | Command from process not understood : 

processes     | Command from process announce-routes : neighbor 192.0.1.133 announce route 124.172.0.0/24 next-hop self origin egp as-path [ 65008 65014  ] 
processes     | Command from process announce-routes :  
reactor       | Command from process not understood : 
processes     | Command from process announce-routes :  
reactor       | Command from process not understood : 

A long time later the reactor processed the received updates and delivered them to Quagga neighbors:

reactor       | Route added to neighbor 192.0.1.138 local-ip 192.0.1.110 local-as 65008 peer-as 65015 router-id 192.0.1.110 family-allowed in-open : 122.172.0.0/24 next-hop 192.0.1.110 origin egp as-path [ 65008 65012 ]

reactor       | Route added to neighbor 192.0.1.135 local-ip 192.0.1.110 local-as 65008 peer-as 65012 router-id 192.0.1.110 family-allowed in-open : 125.172.0.0/24 next-hop 192.0.1.110 origin egp as-path [ 65008 65015 ]

reactor       | Route added to neighbor 192.0.1.135 local-ip 192.0.1.110 local-as 65008 peer-as 65012 router-id 192.0.1.110 family-allowed in-open : 200.0.0.0/24 next-hop 192.0.1.110

I've tried to change reactor speed from 1 second to 0.5 with command $ env exabgp.reactor.speed=0.5 /usr/local/bin/exabgp with no success, with its value remaining 1 second and the problems persisting.

The complete log file is attached.

Do you think changing reactor speed can solve this problem? If so, how can I do that? I would really appreciate your help in solving this problem.

 Thanks in advance. Best regards.
[exabgp_log_04_11_16.txt](https://github.com/Exa-Networks/exabgp/files/573361/exabgp_log_04_11_16.txt)

**Comment by thomas-mangin** [comment]
Hello @ricardo-bennesby 

First you are running a quite old version of ExaBGP with 3.4.10, many issues were addressed since, I would suggest to upgrade. There was no API change since 3.4.10 so your code and config should just work 'as it'.

Also looking at the logs there is a lot of 
`Thu, 03 Nov 2016 20:20:43 | INFO     | 12916  | processes     | Command from process announce-routes :`
`Thu, 03 Nov 2016 20:20:43 | WARNING  | 12916  | reactor       | Command from process not understood : `

So it looks like you are sending empty lined command - your code surely need checking (and please make sure to flush the stdout after each write. This will take CPU cycles for nothing.

if you want to change the reactor speed, feel free to use values as low as 0.1 and depending on your shell using the "dot" version of the variable can use issue so also use '--de' to make sure it worked. `env exabgp_reactor_speed=0.5 ..`

Otherwise I can not see anything obviously wrong.

What surprises me is this message:
`Thu, 03 Nov 2016 20:20:43 | INFO     | 12916  | network       | Peer     192.0.1.134 ASN 65011   out loop, peer reset, message [notification received (4,0)] error[Hold timer expired / Unspecific]`
which make me think that ExaBGP has not sent any KA message were not sent for a long time.

Could you please run 3.4.17 or master as 3.4.10 is too old for me to investigate.

Thanks.

**Comment by ricardo-bennesby** [comment]
Hello Thomas.

Thank you very much for answering. 

I discovered that my application was sending messages with '\n' in the end of each message. Removing those '\n' solved the problem! Now, each message is correctly processed by reactor, just after it is received by ExaBGP.  For example:

_processes     | Command from process announce-routes : neighbor 192.0.1.133 announce route 123.172.0.0/24 next-hop self origin egp as-path [ 65008 65013  ] 
reactor       | Route added to neighbor 192.0.1.133 local-ip 192.0.1.110 local-as 65008 peer-as 65010 router-id 192.0.1.110 family-allowed in-open : 123.172.0.0/24 next-hop 192.0.1.110 origin egp as-path [ 65008 65013 ]
reactor       | Performing dynamic route update
reactor       | Updated peers dynamic routes successfully

processes     | Command from process announce-routes : neighbor 192.0.1.136 announce route 200.0.0.0/24 next-hop self 
reactor       | Route added to neighbor 192.0.1.136 local-ip 192.0.1.110 local-as 65008 peer-as 65013 router-id 192.0.1.110 family-allowed in-open : 200.0.0.0/24 next-hop 192.0.1.110
reactor       | Performing dynamic route update
reactor       | Updated peers dynamic routes successfully

processes     | Command from process announce-routes : neighbor 192.0.1.133 announce route 124.172.0.0/24 next-hop self origin egp as-path [ 65008 65014  ] 
reactor       | Route added to neighbor 192.0.1.133 local-ip 192.0.1.110 local-as 65008 peer-as 65010 router-id 192.0.1.110 family-allowed in-open : 124.172.0.0/24 next-hop 192.0.1.110 origin egp as-path [ 65008 65014 ]
reactor       | Performing dynamic route update
reactor       | Updated peers dynamic routes successfully

processes     | Command from process announce-routes : neighbor 192.0.1.137 announce route 200.0.0.0/24 next-hop self 
reactor       | Route added to neighbor 192.0.1.137 local-ip 192.0.1.110 local-as 65008 peer-as 65014 router-id 192.0.1.110 family-allowed in-open : 200.0.0.0/24 next-hop 192.0.1.110
reactor       | Performing dynamic route update
reactor       | Updated peers dynamic routes successfully_

No more errors caused by the hold timer expiration were detected, without the need to change reactor speed. I believe that the trouble was caused by the empty messages ExaBGP was trying to process, taking extra CPU time. 

I've been testing it with more complex scenarios and ExaBGP works pretty well. Anyway, I will update it to version 3.4.17, to avoid possible issues already solved by current version.

I really appreciate your help.

Best regards!

**Comment by thomas-mangin** [comment]
@ricardo-bennesby good to hear - I will remind one last time to make sure messages printed are flushed (ie: make sure that the stdout buffer is emptied) after each line but if it works it is likely already done. I am closing this issue but feel free to re-open if a related question comes to light.

**Comment by pooryousefshahrooz** [comment]
Hi ricardo,
can you please help me I define conf files for my quagga bgp daemon in order to announce the received routes from neighbors? I can not do that

**Comment by ricardo-bennesby** [comment]
Hi.

You can define your bgpd conf file as follows:

**hostname r1
password zebra

router bgp 65001
 bgp router-id 192.168.0.101
 network 10.0.0.0/24
 neighbor 192.168.0.141 remote-as 65008
 neighbor 192.168.0.141 route-map set-nexthop out
 neighbor 192.168.0.141 ebgp-multihop
 neighbor 192.168.0.141 next-hop-self**

Observing that in this example your AS number is 65001, your BGP speaker IP is 192.168.0.101, your neighbor AS has IP 192.168.0.141 and AS number 65008 and your AS is advertising the prefix 10.0.0.0/24. To send the announce routes received from neighbor 192.168.0.141 you should add the description of the other neighbor(s) in your conf file and the bgp daemon will do this task.

Hope it helps.

Regards.
