### ISSUE TITLE
exabgp occupies too much memory

### ISSUE THREAD

**Issue by wuxinggui** [Exa-Networks/exabgp#537]
Hi,
    My OS is Centos 6.5 and my exabgp is 3.4.12.
    Exabgp occupies about 10GB memory after sending tens of millions of update messages. I guess exabgp "store" all the update messages it has sent, if it does, how can I make exabgp "forget" or not "store" the messages and release the memory?

**Comment by thomas-mangin** [comment]
Outch - I am surprised to hear it is taking 10Gb.

You can disable the ADJ-RIB-Out - it should do the trick but if the session goes does, the routes will not be re-sent. The options is 'adj-rib-out false' under the neighbor or group.

**Comment by wuxinggui** [comment]
Hi,

Thanks for your reply.
I added 'adj-rib-out false' under the neighbor node, exabgp accepted the configuration, but the problem remains, a lot of memory is taken and never be released.

`   
group controller {
    process send_update {
        encoder json;
        run /usr/local/python/bin/python /root/st424/con.py;
    }
    
neighbor 192.168.244.3 {
       router-id 192.168.244.1 ;
       local-address 192.168.244.1;
       local-as 2;
       peer-as 2;
       adj-rib-out false;
   }
}`

**Comment by thomas-mangin** [comment]
please also change the options `exabgp_cache_attributes` and `exabgp_cache_nexthops` to false via the environment and/or ini file.

**Comment by wuxinggui** [comment]
Hi,

I have used these options, and it doesn't work.
_env exabgp.log.enable=false exabgp.cache.attributes=false exabgp.cache.nexthops=false exabgp splcon.conf_

**Comment by thomas-mangin** [comment]
Can you please check with `env exabgp.log.enable=false exabgp.cache.attributes=false exabgp.cache.nexthops=false exabgp --de` that the environment values are well being set with your shell please.
It has been some time since it was last used but if you look at `--help` there is a option to profile ExaBGP memory. If you can generate that file and provide it to me, I will be able to see where the memory is being used / wasted.

**Comment by wuxinggui** [comment]
It seems that everything is all right:
_env exabgp.log.enable=false exabgp.cache.attributes=false exabgp.cache.nexthops=false exabgp --de 
exabgp.log.enable=false
exabgp.cache.attributes=false
exabgp.cache.nexthops=false_


The follow is taken from version 3.4.12. I will install 3.4 master branch and try again a few days later.

[root@Slave24 st424]# env exabgp.log.enable=false exabgp.cache.attributes=false exabgp.cache.nexthops=false exabgp -s api-add-remove2.conf 
^Cmemory utilisation

tuple                      11139
function                   2893
dict                       1432
wrapper_descriptor         1008
builtin_function_or_method 710
weakref                    528
list                       428
method_descriptor          373
type                       365
getset_descriptor          355
member_descriptor          293
module                     234
instancemethod             193
staticmethod               130
classobj                   85
classmethod                84
instance                   74
Distribution               58
cell                       56
set                        52
None


generating memory utilisation graph

**Comment by wuxinggui** [comment]
I will reopen this issue after I try again later, close issue now.
