### ISSUE TITLE
exabgp crashes with permission denied error.

### ISSUE THREAD

**Issue by ederlf** [Exa-Networks/exabgp#540]
I am trying to run exabgp as root and it is crashing with Errno 13: Permission Denied when it tries to execute

```
process parsed-route-backend {
		run /root/endeavour/iSDX/xrs/client.py;
		encoder json;
                receive-routes;
	}
```

The [code of client.py can be found here](https://github.com/h2020-endeavour/iSDX/blob/master/xrs/client.py).

File permissions:
    
    -rwxrwxrwx 1 root root 1704 Nov  2 12:18 iSDX/xrs/client.py

I read in another issue [#252] about exabgp dropping privileges and I wonder if this can be a related problem.

Here follows the output.
```
ExaBGP version : 3.4.13
Python version : 2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]
System Uname   : #77~14.04.1-Ubuntu SMP Thu Dec 17 23:20:00 UTC 2015
System MaxInt  : 9223372036854775807


-- Traceback


Traceback (most recent call last):
  File "/usr/local/bin/exabgp", line 11, in <module>
    sys.exit(run_exabgp())
  File "/usr/local/lib/python2.7/dist-packages/exabgp/application/__init__.py", line 12, in run_exabgp
    main()
  File "/usr/local/lib/python2.7/dist-packages/exabgp/application/bgp.py", line 221, in main
    run(env,comment,configurations)
  File "/usr/local/lib/python2.7/dist-packages/exabgp/application/bgp.py", line 260, in run
    ok = Reactor(configurations).run()
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/loop.py", line 156, in run
    self.processes.start()
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 170, in start
    self._start(process)
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 164, in _start
    raise ProcessError()
ProcessError


-- Configuration


group rs {
	process parsed-route-backend {
		run /root/endeavour/iSDX/xrs/client.py;
		encoder json;
                receive-routes;
	}

	neighbor 172.0.0.1 {
		description "Virtual AS A";
        	router-id 172.0.255.254;
        	local-address 172.0.255.254;
        	local-as 65000;
        	peer-as 100;
        	hold-time 180;
	}

	neighbor 172.0.0.11 {
		description "Virtual AS B";
                router-id 172.0.255.254;
                local-address 172.0.255.254;
                local-as 65000;
                peer-as 200;
                hold-time 180;
        }
}



-- Logging History


Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |     inet6 mpls-vpn;
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |     inet6 flow;
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |     inet6 flow-vpn;
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |     l2vpn vpls;
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |   }
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |   process {
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |     receive {
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |       update;
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |       parsed;
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |       refresh;
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |     }
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |   }
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration | }
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration |
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | configuration | parsing | group         | '}'
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | reactor       | New peer setup: neighbor 172.0.0.1 local-ip 172.0.255.254 local-as 65000 peer-as 100 router-id 172.0.255.254 family-allowed in-open
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | reactor       | New peer setup: neighbor 172.0.0.11 local-ip 172.0.255.254 local-as 65000 peer-as 200 router-id 172.0.255.254 family-allowed in-open
Wed, 16 Nov 2016 10:31:51 | WARNING  | 872    | configuration | Loaded new configuration successfully
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | processes     | Could not start process parsed-route-backend
Wed, 16 Nov 2016 10:31:51 | INFO     | 872    | processes     | reason: [Errno 13] Permission denied
```

**Comment by ederlf** [comment]
I just found that I need to pass some environment variables to have it working.

    env exabgp.daemon.user=root exabgp.daemon.daemonize=false exabgp

**Comment by thomas-mangin** [comment]
Hi @ederlf - you should really try to not run any code as root, but if it works for you - works me for 😉

**Comment by thomas-mangin** [comment]
ExaBGP normally chown to nobody when it runs so if you make sure your code can be run by the user nobody you should not need to have root privileges.

**Comment by thomas-mangin** [comment]
Mac and linux behave differently, the script will be run even if chmod'ed 000 on OS X

**Comment by thomas-mangin** [comment]
just checked latest versions of 3.4 and master and they report permissions / ownership problem saying 
exabgp will not be able to run this program "/home/thomas/exabgp/qa/conf/api-announcement.run"

**Comment by eddie4** [comment]
I have run into the same error

root@# python -m exabgp -v
ExaBGP : 3.4.18
Python : 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
Uname  : #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017


root@# sudo -u nobody python export.py
announce flow route {match {source xxx/32; destination xxx/32;} then {redirect xxx}}


        process add-routes {
                run /usr/bin/python /root/valid/snorlax/export.py;
                }
        }


Fri, 10 Mar 2017 10:00:42 | INFO     | 6023   | configuration | Loaded new configuration successfully
Fri, 10 Mar 2017 10:00:42 | INFO     | 6023   | processes     | Forked process add-routes
/usr/bin/python: can't open file '/root/valid/snorlax/export.py': [Errno 13] Permission denied
Fri, 10 Mar 2017 10:00:42 | INFO     | 6023   | processes     | Command from process add-routes :
Fri, 10 Mar 2017 10:00:42 | INFO     | 6023   | processes     | Issue with the process' PIPE, terminating it and restarting it
Fri, 10 Mar 2017 10:00:42 | INFO     | 6023   | processes     | Terminating process add-routes
Fri, 10 Mar 2017 10:00:42 | INFO     | 6023   | processes     | Forked process add-routes

**Comment by thomas-mangin** [comment]
Hi,

It is a setup issue and not ExaBGP.

http://lmgtfy.com/?q=%5BErrno+13%5D+Permission+denied <http://lmgtfy.com/?q=[Errno+13]+Permission+denied>

If it does not help, I would advise to look at understanding file system permission and the command 
“chown” and “chmod” on unix.

Good luck,

Thomas

**Comment by pguibert6WIND** [comment]
Hello,
I have a similar setup, but I have following error message


Wed, 14 Mar 2018 18:48:43 | INFO     | 25978  | configuration | Loaded new configuration successfully
Wed, 14 Mar 2018 18:48:43 | INFO     | 25978  | processes     | Could not start process announce-routes

I use exabgp 3.4.17
my config file contains following line:
process announce-routes {
        run ./api-add-remove.run;
}
and even if I chowned to nobody:nogroup, message is the same.
any explanation ?

**Comment by thomas-mangin** [comment]
This is shell 101 not ExaBGP AFAICS - `chmod 755 ./api-add-remove.run`

**Comment by dproc** [comment]
In my case, the permission is not about the script itself but the directory the script reside in. For example I put the script in /root which nobody has no right to step in, so chmod 755 /root helps solve the issue. Just for those who still come across this issue information.

**Comment by thomas-mangin** [comment]
IMHO, this chmod is a bad idea from a security POV, but again this is about filesystem / Unix permissions, but it may indeed fix the issue if no other user was setup to run exabgp and the configuration file are in the root directory.
