### ISSUE TITLE
flowspec multiple action

### ISSUE THREAD

**Issue by pubyun** [Exa-Networks/exabgp#542]
parse two action, and only announce one action to peer:

echo "announce flow route { match { destination 118.184.176.6/32; } then { rate-limit 1250000000; redirect 65001:119; } }" > /var/run/exabgp.cmd

Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | reactor       | flow added to neighbor 61.160.239.2 local-ip 118.184.176.2 local-as 18257 peer-as 18257 router-id 118.184.176.2 family-allowed in-open, neighbor 61.160.239.1 local-ip 118.184.176.2 local-as 18257 peer-as 18257 router-id 118.184.176.2 family-allowed in-open : flow destination-ipv4 118.184.176.6/32 pr
otocol =udp destination-port =80 extended-community rate-limit 0
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | reactor       | responding to anounce-routes : done
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | reactor       | callback | removing
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | reactor       | callback | installing announce_flow
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | reactor       | callback | running
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | configuration | > route            |
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | configuration | > match            |
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | configuration | . destination      | '118.184.176.6/32'
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | configuration | < match            |
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | configuration | > then             |
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | configuration | . rate-limit       | '1250000000'
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | configuration | . redirect         | '65001:119'
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | configuration | < then             |
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | configuration | < route            |
Tue, 22 Nov 2016 10:42:08 | INFO     | 651508 | reactor       | flow added to neighbor 61.160.239.2 local-ip 118.184.176.2 local-as 18257 peer-as 18257 router-id 118.184.176.2 family-allowed in-open, neighbor 61.160.239.1 local-ip 118.184.176.2 local-as 18257 peer-as 18257 router-id 118.184.176.2 family-allowed in-open : flow destination-ipv4 118.184.176.6/32 extended-community rate-limit 1250000000

**Comment by pubyun** [comment]
rate-limit and redirect are all EXTENDED_COMMUNITY.
so the parse code does not allow multiple values.

same ID, so later value discard.

lib/exabgp/bgp/message/update/attribute/attributes.py

	def add (self, attribute, _=None):
		# we return None as attribute if the unpack code must not generate them
		if attribute is None:
			return
		if attribute.ID in self:
			return

		self._str = ''
		self._json = ''

		self[attribute.ID] = attribute

**Comment by thomas-mangin** [comment]
It has been some time since I read the RFC but was under the impression that duplicate attributes was not allowed. It is clearly prohibited for MP in RFC 7606 - for the rest I am not sure now !

**Comment by pubyun** [comment]
RFC 5575:

   These traffic policy mechanisms allow the router to define match
   rules that operate on multiple fields of the packet header.  Actions
   such as the ones described above can be associated with each rule.

cisco and huawei allow multiple action for a flowspec.

if exabgp only allow one action, then how can we do flowing filter:

if match source 10.0.0.1/32, then limit the bandwidth and redirect to VRF 65001:110?

**Comment by thomas-mangin** [comment]
@pubyun Thank you for this information.

I was allowing multiple MP attribute on ExaBGP and it was explicitly forbidden by RFC 7606. Some well-know attribute are also required to only be present once hence why wanted to re-read the RFC - which I had no time for recently.

It is good to know that Cisco and Huawei are allowing it. Would it be possible for you to use ExaBGP and provide me the output of what they send (when using "exabgp -d" does print the content of the packets received on stdout)?

It would allow me to check that I am generating them the same way and make sure all is as should.

**Comment by pubyun** [comment]
sorry, i can't get debug info with "exabgp -d". so i attach a tcpdump cap file.

I only have Huawei router, the 16th packet is the flowspec update message from Huawei to exabgp:

the config file of Huawei:

flow-route flood-ntp
 if-match destination 118.184.176.6 255.255.255.255
 if-match protocol equal udp
 if-match source-port equal 123
 apply traffic-rate 10240
 apply redirect vpn-target 65001:119

[flowspec.cap.zip](https://github.com/Exa-Networks/exabgp/files/614543/flowspec.cap.zip)

I have no flowspec capable device, here is the document of Cisco:

In a given flowspec rule, multiple action combinations can be specified without restrictions.

http://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k_r5-2/routing/configuration/guide/b_routing_cg52xasr9k/b_routing_cg52xasr9k_chapter_011.html

and also:

If a BGP speaker receives a flow-spec route with multiple 'redirect
   to IP' extended communities and this route represents the one and
   only best path, it SHOULD load-share the redirected/copied packets
   across all the 'target addresses' according to its ECMP
   configuration. If the BGP speaker is not capable of redirecting and
   copying the same packet it SHOULD ignore the extended communities
   with C=0. If the BGP speaker is not capable of redirecting/copying a
   packet towards multiple 'target addresses' it SHOULD
   deterministically select one 'target address' and ignore the others.

https://tools.ietf.org/html/draft-ietf-idr-flowspec-redirect-ip-02

**Comment by thomas-mangin** [comment]
```
./sbin/exabgp qa/conf/api-broken-flow.conf --decode ffffffffffffffffffffffffffffffff0055020000003e400101004002008004040000000040050400000064c01010800600004b1c40008008fde900000077900e001200018500000c012076b8b00603811106817b 2>&1 | grep decoded
Sun, 27 Nov 2016 10:36:42 | INFO     | 43684  | parser        | decoded update 1 flow destination-ipv4 118.184.176.6/32 protocol =udp source-port =123 origin igp med 0 local-preference 100 extended-community [ rate-limit 10240000 redirect:65001:119 ]
```

**Comment by thomas-mangin** [comment]
Can you please provide me the configuration file you are using.

**Comment by thomas-mangin** [comment]
ok, so there is ONE extended-community with two values into it. That's fine.

**Comment by thomas-mangin** [comment]
Part of the configuration file, it works, so the issue is with the API parser
https://github.com/Exa-Networks/exabgp/commit/d57966e13871c6ca703456dc007d6e21f99b9c03

**Comment by thomas-mangin** [comment]
As the API use the parsing code to generate the objects, can you please confirm what version of ExaBGP you are using.

**Comment by pubyun** [comment]
i am using master from github

**Comment by pubyun** [comment]
here is my exabgp.conf:

process anounce-routes {
    run /usr/bin/socat stdout pipe:/var/run/exabgp.cmd;
    encoder json;
}

template router {
    router-id 118.184.176.2;
    local-address 118.184.176.2;
    local-as 18257;
    peer-as 18257;

    group-updates false;
    hold-time 180;
    capability {
        graceful-restart 1200;
    }

    family {
        ipv4 unicast;
        ipv4 flow;
    }

    api {
        processes [ anounce-routes ];
    }

neighbor 61.160.239.1 {
    inherit router;
    description "ExaBGP";
    md5-password xxxxxx;
}

**Comment by thomas-mangin** [comment]
Hello @pubyun 

Finally got the time required to correctly look at the code and fix the issue. Thank you very much for reporting the problem (and sorry for the time it took me to write this simple fix).

**Comment by pubyun** [comment]
it works now, thanks
