### ISSUE TITLE
add-path only works in debug mode

### ISSUE THREAD

**Issue by lovedufva** [Exa-Networks/exabgp#544]
Hi!

This is the config we're running: 
```
group yolo {
    neighbor 10.60.2.2 {
        local-as 65001;
        local-address 10.60.2.100;
        group-updates true;
        peer-as 64610;

        family {
            ipv4 unicast;
        }

        capability swag {
            operational enable;
            multi-session disable;
            route-refresh enable;
            graceful-restart 30;
            add-path send/receive;
            asn4 disable;
        }

        process check-nginx_1 {
            run "/etc/exabgp/check.sh -T nginx -H nginx1.example.com/status -t 4 -w nginx_1";
        }

        static {
            route 172.29.29.128/26 next-hop 10.60.32.17 med 100 path-information 0.0.0.149 watchdog nginx_1;
        }
        
        process check-nginx_2 {
            run "/etc/exabgp/check.sh -T nginx -H nginx2.example.com/status -t 10 -w nginx_2";
        }

        static {
            route 172.29.29.128/26 next-hop 10.61.32.17 med 200 path-information 0.0.0.138 watchdog nginx_2;
        }
    }
}
```

It works if we start exabgp by running 'exabgp -d /etc/exabgp/exabgp.conf', but if we use 'sysctl start exabgp' or 'service exabgp start' to start it will only announce the second route (next-hop 10.61.32.17).

We're seeing this behavior in both 3.4.13 and 3.4.17

**Comment by thomas-mangin** [comment]
"-d" can not after the behavior, of the route announcement, so running the command line without -d should/will give you the same behaviour.

Can you look what version of ExaBGP is run when you use sysctl (or more likely systemctl) and what file is reported by ps (ps -axfww).

**Comment by thomas-mangin** [comment]
No update, I assume multiple version of ExaBGP were installed and the wrong one used.
