### ISSUE TITLE
Unable to clone using git

### ISSUE THREAD

**Issue by zmask37** [Exa-Networks/exabgp#555]
Hi,
I am unable to clone the exabgp package using git.
git clone https://github.com/Exa-Networks/exabgp.git
Cloning into 'exabgp'...
fatal: unable to access 'https://github.com/Exa-Networks/exabgp.git/': gnutls_handshake() failed: A TLS packet with unexpected length was received.

**Comment by job** [comment]
This is a problem unrelated to Exabgp .

Please see http://askubuntu.com/questions/186847/error-gnutls-handshake-failed-when-connecting-to-https-servers/251937#251937 for a possible solution.
