### ISSUE TITLE
ipv6 flowspec flowlabel doesn't support 20 bits, only 16bits

### ISSUE THREAD

**Issue by BLAKEMMM** [Exa-Networks/exabgp#561]
Hi, exabgp developers
Does ipv6 flowspec flowlabel support 20bits? range: 0-2^20-1
I try it but the max number is 65535.
I think that function "IOperationByteShort" causes this problem.

**Comment by thomas-mangin** [comment]
The code which perform the conversion (used by the parser is) 

```
def LabelValue (data):
	_str_bad_label = "you tried to filter a flow using an invalid traffic label for a component .."
	number = int(data)
	if number < 0 or number > 0xFFFFF:  # 20 bits 5 bytes
		raise ValueError(_str_bad_label)
	return number
```

So it checks for 20bits, can you please provide more information.

**Comment by thomas-mangin** [comment]
`0xFFFFF ==  1048575`

**Comment by thomas-mangin** [comment]
Thank you for reporting the issue. It should be working.
