### ISSUE TITLE
exabgp crashes when it tries to terminate never created processes

### ISSUE THREAD

**Issue by dontreboot** [Exa-Networks/exabgp#570]
ExaBGP version : 3.4.16
Python version : 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
System Uname   : #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016
System MaxInt  : 9223372036854775807

-- Traceback

Traceback (most recent call last):
  File "/usr/sbin/exabgp", line 9, in <module>
    load_entry_point('exabgp==3.4.16', 'console_scripts', 'exabgp')()
  File "/usr/lib/python2.7/dist-packages/exabgp/application/__init__.py", line 12, in run_exabgp
    main()
  File "/usr/lib/python2.7/dist-packages/exabgp/application/bgp.py", line 221, in main
    run(env,comment,configurations)
  File "/usr/lib/python2.7/dist-packages/exabgp/application/bgp.py", line 260, in run
    ok = Reactor(configurations).run()
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/loop.py", line 192, in run
    self.processes.start(self._reload_processes)
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 169, in start
    self._terminate(process)
  File "/usr/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 75, in _terminate
    self._process[process].terminate()
KeyError: 'test2'

-- Configuration

group exabgp {
    router-id 10.104.23.27;
    neighbor 10.104.23.1 {
        local-address 10.104.23.27;
        local-as 64512;
        peer-as 33047;
    }
   process test {
     run /usr/bin/python -m exabgp healthcheck --ip 89.158.20.7 --disabled-metric 0 --no-ip-setup --withdraw-on-down --cmd true;
   }

   process test2 {
     run /usr/bin/python -m exabgp healthcheck --ip 89.158.20.8 --disabled-metric 0 --no-ip-setup --withdraw-on-down --cmd true;
   }
}

-- Logging History

Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration |     inet6 flow;
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration |     inet6 flow-vpn;
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration |     l2vpn vpls;
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration |   }
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration |   process {
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration |   }
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration | }
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration |
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration |
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration | parsing | group         | 'process' 'test' '{'
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration | parsing | process       | 'run' '/usr/bin/python -m exabgp healthcheck --ip 89.158.20.7 --disabled-metric 0 --no-ip-setup --withdraw-on-down --cmd true' ';'
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration | parsing | process       | '}'
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration | parsing | group         | 'process' 'test2' '{'
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration | parsing | process       | 'run' '/usr/bin/python -m exabgp healthcheck --ip 89.158.20.8 --disabled-metric 0 --no-ip-setup --withdraw-on-down --cmd true' ';'
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration | parsing | process       | '}'
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | configuration | parsing | group         | '}'
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | reactor       | Peer definition identical, updating peer routes if required for neighbor 10.104.23.1 local-ip 10.104.23.27 local-as 64512 peer-as 33047 router-id 10.104.23.27 family-allowed in-open
Sat, 21 Jan 2017 16:59:49 | WARNING  | 105337 | configuration | Loaded new configuration successfully
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | processes     | Terminating process test
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | processes     | Forked process test
Sat, 21 Jan 2017 16:59:49 | INFO     | 105337 | processes     | Terminating process test2

**Comment by thomas-mangin** [comment]
Thank you @dontreboot - I have backported the fix to 3.4
