### ISSUE TITLE
RFC3107 support for AF IPv6

### ISSUE THREAD

**Issue by adrian62** [Exa-Networks/exabgp#575]
Please add RFC3107 support for AF IPv6. RFC 3107 adds the ability to signal labels for non-VPN AFs. 
This RFC doesn't prescribe anything specific to IPv6 and merely extends the NLRI information field with a label stack ahead of the prefix.
Exabgp already contains support for RFC3107 for AF IPv4 thus all the needed functionality to support carrying label information in the NLRI field  appears to already be present but not enabled for AF IPv6.

Relevant RFCs: http://www.ietf.org/rfc/rfc3107.txt

**Comment by thomas-mangin** [comment]
Hello Adrian,

As I am short on time could you please help me by:
 - telling what happens when you try to announce such a route
 - providing me a simple example configuration sending a route (i.e.: what you would have expected to do)

It would really save me time.

Thank you.

**Comment by adrian62** [comment]
First, I am trying to set up a neighbor using address family ipv6 labeled-unicast (in exa labeled unicast is called nlri-mpls):
        neighbor 10.0.0.22 {
                description "example peer for group EXA_AFX1_2_MISRR";
                hold-time 90;
                family {      
                        ipv6 nlri-mpls;
                }             
        }       
     
This fails immediately because the AFi/SAFi combination offered by the peer is not permitted by this list in lib/exabgp/protocol/family.py:
def known_families ():
   # it can not be a generator
   families = [
      (AFI(AFI.ipv4), SAFI(SAFI.unicast)),
      (AFI(AFI.ipv4), SAFI(SAFI.multicast)),
      (AFI(AFI.ipv4), SAFI(SAFI.nlri_mpls)),
      (AFI(AFI.ipv4), SAFI(SAFI.mpls_vpn)),
      (AFI(AFI.ipv4), SAFI(SAFI.flow_ip)),
      (AFI(AFI.ipv4), SAFI(SAFI.flow_vpn)),
      (AFI(AFI.ipv6), SAFI(SAFI.unicast)),
      (AFI(AFI.ipv6), SAFI(SAFI.mpls_vpn)),
      (AFI(AFI.ipv6), SAFI(SAFI.flow_ip)),
      (AFI(AFI.ipv6), SAFI(SAFI.flow_vpn)),
      (AFI(AFI.l2vpn), SAFI(SAFI.vpls))
   ]
   return families

If I try configuring the family on the neighbor I get the error:
Mon, 20 Feb 2017 06:41:17 | ERROR    | 4056   | configuration | Problem with the configuration file, no change done
Mon, 20 Feb 2017 06:41:17 | ERROR    | 4056   | configuration | 
Mon, 20 Feb 2017 06:41:17 | ERROR    | 4056   | configuration | syntax error in section family
Mon, 20 Feb 2017 06:41:17 | ERROR    | 4056   | configuration | line 11: ipv6 nlri-mpls ;

 If I try setting up a route like this:        static { 
                route dead:beef::1/128 {
                        next-hop dead:dead::4;
                        label 220;
                } 
        } 
it is accepted without error, but configuring it is inconsequential since I can't set up a peering relationship with a device speaking ipv6 labeled-unicast (AF/SAFi = 2/4).
Please let me know if I'm not answering your questions correctly.

**Comment by thomas-mangin** [comment]
Can you try to see if this work on master..

```
	convert = {
		'ipv4': {
			'unicast':   	(AFI(AFI.ipv4),SAFI(SAFI.unicast)),
			'multicast': 	(AFI(AFI.ipv4),SAFI(SAFI.multicast)),
			'nlri-mpls': 	(AFI(AFI.ipv4),SAFI(SAFI.nlri_mpls)),
			'mpls-vpn':  	(AFI(AFI.ipv4),SAFI(SAFI.mpls_vpn)),
			'flow':      	(AFI(AFI.ipv4),SAFI(SAFI.flow_ip)),
			'flow-vpn':  	(AFI(AFI.ipv4),SAFI(SAFI.flow_vpn)),
		},
		'ipv6': {
			'unicast':   	(AFI(AFI.ipv6),SAFI(SAFI.unicast)),
			'nlri-mpls': 	(AFI(AFI.ipv6),SAFI(SAFI.nlri_mpls)),
			'mpls-vpn':  	(AFI(AFI.ipv6),SAFI(SAFI.mpls_vpn)),
			'flow':      	(AFI(AFI.ipv6),SAFI(SAFI.flow_ip)),
			'flow-vpn':  	(AFI(AFI.ipv6),SAFI(SAFI.flow_vpn)),
		},
		'l2vpn': {
			'vpls':      	(AFI(AFI.l2vpn),SAFI(SAFI.vpls)),
			'evpn':      	(AFI(AFI.l2vpn),SAFI(SAFI.evpn)),
		},
		'bgpls': {
			'bgp-ls':		(AFI(AFI.bgpls),SAFI(SAFI.bgp_ls)),
			'bgp-ls-vpn':	(AFI(AFI.bgpls),SAFI(SAFI.bgp_ls_vpn)),
		},
	}
```

**Comment by thomas-mangin** [comment]
Can you please try on 3.4.18 the following patch:

```
diff --git a/lib/exabgp/configuration/ancient.py b/lib/exabgp/configuration/ancient.py
index f27002bc..d24d6cec 100644
--- a/lib/exabgp/configuration/ancient.py
+++ b/lib/exabgp/configuration/ancient.py
@@ -1070,6 +1070,8 @@ class Configuration (object):
                        safi = tokens.pop(0)
                        if safi == 'unicast':
                                scope[-1]['families'].append((AFI(AFI.ipv6),SAFI(SAFI.unicast)))
+                       elif safi == 'nlri-mpls':
+                               scope[-1]['families'].append((AFI(AFI.ipv6),SAFI(SAFI.nlri_mpls)))
                        elif safi == 'mpls-vpn':
                                scope[-1]['families'].append((AFI(AFI.ipv6),SAFI(SAFI.mpls_vpn)))
                        elif safi in ('flow'):
diff --git a/lib/exabgp/protocol/family.py b/lib/exabgp/protocol/family.py
index 743151d6..c8c3aa73 100644
--- a/lib/exabgp/protocol/family.py
+++ b/lib/exabgp/protocol/family.py
@@ -201,6 +201,7 @@ def known_families ():
                (AFI(AFI.ipv4), SAFI(SAFI.flow_ip)),
                (AFI(AFI.ipv4), SAFI(SAFI.flow_vpn)),
                (AFI(AFI.ipv6), SAFI(SAFI.unicast)),
+               (AFI(AFI.ipv6), SAFI(SAFI.nlri_mpls)),
                (AFI(AFI.ipv6), SAFI(SAFI.mpls_vpn)),
                (AFI(AFI.ipv6), SAFI(SAFI.flow_ip)),
                (AFI(AFI.ipv6), SAFI(SAFI.flow_vpn)),
```

**Comment by thomas-mangin** [comment]
all good ?

**Comment by adrian62** [comment]
Thomas,
The session is establishing and we receive IPv6 routes from the peer with labels, but I haven't had a chance to look deeper into what the logs with a bunch of hex mean, I copied one below.So I need to investigate a bit further. I am mentoring a school robotics team and yesterday and today are the last days before their robot has to be ready, I had very little sleep, that's why I'm behind. I'll keep you informed.
thanks muchadrian

Tue, 21 Feb 2017 16:21:12 | INFO     | 5158   | routes        | peer 10.0.0.22 ASN 65060   << UPDATE (11) nlri  (61) cafe:1890:127e:25c::/64 next-hop ::ffff:10.0.8.72 label [ 2 ]

Tue, 21 Feb 2017 16:21:12 | INFO     | 5158   | parser        | parsing 2/4 nlri payload  (9059) 5800 0021 CAFE 1890 127E 01DE 5800 0021 CAFE 1890 127E 01DC 5800 0021 CAFE 1890 127E 01DF 5800 0021 CAFE 1890 127E 01DD 5800 0021 CAFE 1890 127E 01E0 5800 0021 CAFE 1890 127E 033A 5800 0021 CAFE 1890 127E F1DD 5800 0021 CAFE 1890 127E 000C 5800 0021 CAFE 1890 127E 01E8 5800 0021 CAFE 1890 127E 01E7 5800 0021 CAFE 1890 127E 01E6 5800 0021 CAFE 1890 127E F1F3 5800 0021 CAFE 1890 127E 01E4 5800 0021 CAFE 1890 127E 01E3 5800 0021 CAFE 1890 127E 033B 5800 0021 CAFE 1890 127E 01E2 5800 0021 CAFE 1890 127E 01E1 5800 0021 CAFE 1890 127E 01DB 5800 0021 CAFE 1890 127E 01DA 5800 0021 CAFE 1890 127E 01D9 5800 0021 CAFE 1890 127E 01D8 5800 0021 CAFE 1890 127E 01D7 5800 0021 CAFE 1890 127E 01D5 5800 0021 CAFE 1890 127E 0005 5800 0021 CAFE 1890 127E 0002 5800 0021 CAFE 1890 127E 0001 5800 0021 CAFE 1890 127E 0003 5800 0021 CAFE 1890 127E 0004 5800 0021 CAFE 1890 127E 0000 5800 0021 CAFE 1890 127E 0014 5800 0021 CAFE 1890 127E F1F4 5800 0021 CAFE 1890 127E 01E5 5800 0021 CAFE 1890 127E 033C 5800 0021 CAFE 1890 127E 033D 5800 0021 CAFE 1890 127E F1DE 5800 0021 CAFE 1890 127E F1DF 5800 0021 CAFE 1890 127E 022F 5800 0021 CAFE 1890 127E 022E 5800 0021 CAFE 1890 127E 022D 5800 0021 CAFE 1890 127E 022C 5800 0021 CAFE 1890 127E 022B 5800 0021 CAFE 1890 127E 021F 5800 0021 CAFE 1890 127E 0229 5800 0021 CAFE 1890 127E 0228 5800 0021 CAFE 1890 127E 0225 5800 0021 CAFE 1890 127E 0224 5800 0021 CAFE 1890 127E 0223 5800 0021 CAFE 1890 127E 0222 5800 0021 CAFE 1890 127E 0221 5800 0021 CAFE 1890 127E 021D 5800 0021 CAFE 1890 127E 0227 5800 0021 CAFE 1890 127E 0220 5800 0021 CAFE 1890 127E 022A 5800 0021 CAFE 1890 127E 0226 5800 0021 CAFE 1890 127E 021E 5800 0021 CAFE 1890 127E 0218 5800 0021 CAFE 1890 127E 0215 5800 0021 CAFE 1890 127E 021B 5800 0021 CAFE 1890 127E 0219 5800 0021 CAFE 1890 127E 0217 5800 0021 CAFE 1890 127E 021C 5800 0021 CAFE 1890 127E 021A 5800 0021 CAFE 1890 127E 0216 5800 0021 CAFE 1890 127E F1E0 5800 0021 CAFE 1890 127E F1E1 5800 0021 CAFE 1890 127E F1E2 5800 0021 CAFE 1890 127E 0209 5800 0021 CAFE 1890 127E 0208 5800 0021 CAFE 1890 127E 01FC 5800 0021 CAFE 1890 127E 01FF 5800 0021 CAFE 1890 127E 01FA 5800 0021 CAFE 1890 127E 01F9 5800 0021 CAFE 1890 127E 01FD 5800 0021 CAFE 1890 127E 01FE 5800 0021 CAFE 1890 127E 0201 5800 0021 CAFE 1890 127E 0205 5800 0021 CAFE 1890 127E 0202 5800 0021 CAFE 1890 127E 0200 5800 0021 CAFE 1890 127E 01F7 5800 0021 CAFE 1890 127E 01F6 5800 0021 CAFE 1890 127E 01F5 5800 0021 CAFE 1890 127E 01F4 5800 0021 CAFE 1890 127E 0204 5800 0021 CAFE 1890 127E 0203 5800 0021 CAFE 1890 127E 01FB 5800 0021 CAFE 1890 127E 0207 5800 0021 CAFE 1890 127E 0206 5800 0021 CAFE 1890 127E 01F8 5800 0021 CAFE 1890 127E 01F1 5800 0021 CAFE 1890 127E 01F3 5800 0021 CAFE 1890 127E 01F2 5800 0021 CAFE 1890 127E 01F0 5800 0021 CAFE 1890 127E 01EF 5800 0021 CAFE 1890 127E 01EE 5800 0021 CAFE 1890 127E 01ED 5800 0021 CAFE 1890 127E 01EB 5800 0021 CAFE 1890 127E 01EC 5800 0021 CAFE 1890 127E 01EA 5800 0021 CAFE 1890 127E 01E9 5800 0021 CAFE 1890 127E F1E3 5800 0021 CAFE 1890 127E 033E 5800 0021 CAFE 1890 127E 033F 5800 0021 CAFE 1890 127E 0340 5800 0021 CAFE 1890 127E F1F5 5800 0021 CAFE 1890 127E F1F6 5800 0021 CAFE 1890 127E 0093 5800 0021 CAFE 1890 127E 0094 5800 0021 CAFE 1890 127E 0030 5800 0021 CAFE 1890 127E 0095 5800 0021 CAFE 1890 127E 0034 5800 0021 CAFE 1890 127E 0031 5800 0021 CAFE 1890 127E 0035 5800 0021 CAFE 1890 127E 0038 5800 0021 CAFE 1890 127E 0032 5800 0021 CAFE 1890 127E 0036 5800 0021 CAFE 1890 127E 0033 5800 0021 CAFE 1890 127E 0037 5800 0021 CAFE 1890 127E 0043 5800 0021 CAFE 1890 127E 0042 5800 0021 CAFE 1890 127E 0044 5800 0021 CAFE 1890 127E 0045 5800 0021 CAFE 1890 127E 004A 5800 0021 CAFE 1890 127E 0047 5800 0021 CAFE 1890 127E 0046 5800 0021 CAFE 1890 127E F04C 5800 0021 CAFE 1890 127E 004C 5800 0021 CAFE 1890 127E 0048 5800 0021 CAFE 1890 127E 004B 5800 0021 CAFE 1890 127E 0049 5800 0021 CAFE 1890 127E F04D 5800 0021 CAFE 1890 127E 004D 5800 0021 CAFE 1890 127E F051 5800 0021 CAFE 1890 127E 0051 5800 0021 CAFE 1890 127E 0058 5800 0021 CAFE 1890 127E 0059 5800 0021 CAFE 1890 127E 005A 5800 0021 CAFE 1890 127E 005B 5800 0021 CAFE 1890 127E 0066 5800 0021 CAFE 1890 127E 0067 5800 0021 CAFE 1890 127E 006D 5800 0021 CAFE 1890 127E 006A 5800 0021 CAFE 1890 127E 0069 5800 0021 CAFE 1890 127E 006C 5800 0021 CAFE 1890 127E 0053 5800 0021 CAFE 1890 127E 0068 5800 0021 CAFE 1890 127E F052 5800 0021 CAFE 1890 127E 006B 5800 0021 CAFE 1890 127E 0052 5800 0021 CAFE 1890 127E 0076 5800 0021 CAFE 1890 127E 0054 5800 0021 CAFE 1890 127E 0075 5800 0021 CAFE 1890 127E 0077 5800 0021 CAFE 1890 127E 0078 5800 0021 CAFE 1890 127E 0079 5800 0021 CAFE 1890 127E 0088 5800 0021 CAFE 1890 127E 0096 5800 0021 CAFE 1890 127E F053 5800 0021 CAFE 1890 127E 0341 5800 0021 CAFE 1890 127E 01D4 5800 0021 CAFE 1890 127E 0342 5800 0021 CAFE 1890 127E 0343 5800 0021 CAFE 1890 127E F1E4 5800 0021 CAFE 1890 127E F1E5 5800 0021 CAFE 1890 127E 0214 5800 0021 CAFE 1890 127E 0213 5800 0021 CAFE 1890 127E 0212 5800 0021 CAFE 1890 127E 0211 5800 0021 CAFE 1890 127E 020B 5800 0021 CAFE 1890 127E 020A 5800 0021 CAFE 1890 127E 020F 5800 0021 CAFE 1890 127E 0210 5800 0021 CAFE 1890 127E 020E 5800 0021 CAFE 1890 127E 020D 5800 0021 CAFE 1890 127E 020C 5800 0021 CAFE 1890 127E F1E6 5800 0021 CAFE 1890 127E 0344 5800 0021 CAFE 1890 127E 0007 5800 0021 CAFE 1890 127E F1E7 5800 0021 CAFE 1890 127E F1D1 5800 0021 CAFE 1890 127E 000B 5800 0021 CAFE 1890 127E F1E8 5800 0021 CAFE 1890 127E F1D7 5800 0021 CAFE 1890 127E F1D8 5800 0021 CAFE 1890 127E F1D4 5800 0021 CAFE 1890 127E F1D5 5800 0021 CAFE 1890 127E F1E9 5800 0021 CAFE 1890 127E F1EA 5800 0021 CAFE 1890 127E F1D9 5800 0021 CAFE 1890 127E 02C8 5800 0021 CAFE 1890 127E 02E4 5800 0021 CAFE 1890 127E 02CB 5800 0021 CAFE 1890 127E 02E8 5800 0021 CAFE 1890 127E 02E9 5800 0021 CAFE 1890 127E 0304 5800 0021 CAFE 1890 127E 02DE 5800 0021 CAFE 1890 127E 0305 5800 0021 CAFE 1890 127E 02F5 5800 0021 CAFE 1890 127E 02F8 5800 0021 CAFE 1890 127E 0306 5800 0021 CAFE 1890 127E 0307 5800 0021 CAFE 1890 127E 02F9 5800 0021 CAFE 1890 127E 02DC 5800 0021 CAFE 1890 127E 02ED 5800 0021 CAFE 1890 127E 0308 5800 0021 CAFE 1890 127E 0309 5800 0021 CAFE 1890 127E 030A 5800 0021 CAFE 1890 127E 0313 5800 0021 CAFE 1890 127E 02F4 5800 0021 CAFE 1890 127E 0314 5800 0021 CAFE 1890 127E 0315 5800 0021 CAFE 1890 127E 02C2 5800 0021 CAFE 1890 127E 02BA 5800 0021 CAFE 1890 127E 0316 5800 0021 CAFE 1890 127E 02D2 5800 0021 CAFE 1890 127E 02B8 5800 0021 CAFE 1890 127E 02BD 5800 0021 CAFE 1890 127E 02F3 5800 0021 CAFE 1890 127E 0317 5800 0021 CAFE 1890 127E 0318 5800 0021 CAFE 1890 127E 0319 5800 0021 CAFE 1890 127E 02CF 5800 0021 CAFE 1890 127E 02BC 5800 0021 CAFE 1890 127E 02C9 5800 0021 CAFE 1890 127E 031A 5800 0021 CAFE 1890 127E 02D4 5800 0021 CAFE 1890 127E 02D8 5800 0021 CAFE 1890 127E 0325 5800 0021 CAFE 1890 127E 0326 5800 0021 CAFE 1890 127E 02BB 5800 0021 CAFE 1890 127E 02D7 5800 0021 CAFE 1890 127E 0327 5800 0021 CAFE 1890 127E 02B9 5800 0021 CAFE 1890 127E 02FA 5800 0021 CAFE 1890 127E 02E3 5800 0021 CAFE 1890 127E 031B 5800 0021 CAFE 1890 127E 0328 5800 0021 CAFE 1890 127E 02E7 5800 0021 CAFE 1890 127E 0329 5800 0021 CAFE 1890 127E 02DB 5800 0021 CAFE 1890 127E 02EC 5800 0021 CAFE 1890 127E 02FB 5800 0021 CAFE 1890 127E 031C 5800 0021 CAFE 1890 127E 02C3 5800 0021 CAFE 1890 127E 02E0 5800 0021 CAFE 1890 127E 02DF 5800 0021 CAFE 1890 127E 02DA 5800 0021 CAFE 1890 127E 031D 5800 0021 CAFE 1890 127E 0324 5800 0021 CAFE 1890 127E 02C5 5800 0021 CAFE 1890 127E 02C4 5800 0021 CAFE 1890 127E 02CA 5800 0021 CAFE 1890 127E 02C0 5800 0021 CAFE 1890 127E 02FC 5800 0021 CAFE 1890 127E 032A 5800 0021 CAFE 1890 127E 032B 5800 0021 CAFE 1890 127E 02C1 5800 0021 CAFE 1890 127E 02BE 5800 0021 CAFE 1890 127E 000F 5800 0021 CAFE 1890 127E 02FD 5800 0021 CAFE 1890 127E 031E 5800 0021 CAFE 1890 127E 02FE 5800 0021 CAFE 1890 127E 031F 5800 0021 CAFE 1890 127E 02EE 5800 0021 CAFE 1890 127E 02FF 5800 0021 CAFE 1890 127E 0300 5800 0021 CAFE 1890 127E 02E1 5800 0021 CAFE 1890 127E 02EA 5800 0021 CAFE 1890 127E 02EB 5800 0021 CAFE 1890 127E 02E5 5800 0021 CAFE 1890 127E 02BF 5800 0021 CAFE 1890 127E 02D5 5800 0021 CAFE 1890 127E 02CD 5800 0021 CAFE 1890 127E 02E6 5800 0021 CAFE 1890 127E 02F6 5800 0021 CAFE 1890 127E 02F0 5800 0021 CAFE 1890 127E 032F 5800 0021 CAFE 1890 127E 02CC 5800 0021 CAFE 1890 127E 02C7 5800 0021 CAFE 1890 127E 000E 5800 0021 CAFE 1890 127E 0011 5800 0021 CAFE 1890 127E 0301 5800 0021 CAFE 1890 127E 0320 5800 0021 CAFE 1890 127E 0302 5800 0021 CAFE 1890 127E 000D 5800 0021 CAFE 1890 127E 0303 5800 0021 CAFE 1890 127E 0321 5800 0021 CAFE 1890 127E 02D9 5800 0021 CAFE 1890 127E 02E2 5800 0021 CAFE 1890 127E 02D6 5800 0021 CAFE 1890 127E 02F2 5800 0021 CAFE 1890 127E 02CE 5800 0021 CAFE 1890 127E 02D3 5800 0021 CAFE 1890 127E 02D0 5800 0021 CAFE 1890 127E 02DD 5800 0021 CAFE 1890 127E 02F1 5800 0021 CAFE 1890 127E 032D 5800 0021 CAFE 1890 127E 032C 5800 0021 CAFE 1890 127E 02D1 5800 0021 CAFE 1890 127E 02C6 5800 0021 CAFE 1890 127E 02F7 5800 0021 CAFE 1890 127E 0330 5800 0021 CAFE 1890 127E 0322

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/commit/d6a8f7090dc8dfbcd5585d5cb7c684ddc964f335
