### ISSUE TITLE
Exabgp is terminating itself due to the respawn limit

### ISSUE THREAD

**Issue by KoljaV** [Exa-Networks/exabgp#577]
Hi!
I am observing that my exabgp process is frequently crashing due to the respawn limit. I think that is kind of an expected behaviour but I don't get why exabgp respawns my healtcheck so often. I am just using s simple "dig"-command as healthcheck.  
Does anyone experienced a similar behaviour ?

These lines are written to syslog:
Feb 21 10:09:13 ...[17555]: processes     Too many respawn for ..... (5) terminating program
Feb 21 10:09:13 ...[17555]: reactor       Problem when sending message(s) to helper program, stopping

Thank you very much and best regards
Kolja

**Comment by thomas-mangin** [comment]
Your helper program is exiting when it should not. Please look in the QA folder for some examples.

**Comment by thomas-mangin** [comment]
ping ?

**Comment by KoljaV** [comment]
What do you mean with "ping" ?

**Comment by thomas-mangin** [comment]
Can I close the question ?

**Comment by KoljaV** [comment]
yes please
