### ISSUE TITLE
api config section only applied to one neighbor if defined as part of a template

### ISSUE THREAD

**Issue by brijohn** [Exa-Networks/exabgp#584]
Logging this issue since I don't have time to chase it down currently and there is a workaround we can use in the mean time.

When defining the API config section within a template and then having multiple neighbors inherit that template only one of those neighbors will pick up the api config. 

In our case we have a backend process which handles logging of outgoing routes using the following config:

api {
    processes [ logger ];
    send {
        update;
        packets;
    }
 }

When placed in a template to allow all neighbors to use the same api config we are only receiving route information from one neighbor. A workaround for this issue is to simply place the api config section in each neighbor definition which then seems to correctly send route information from each neighbor.

**Comment by thomas-mangin** [comment]
@brijohn I need two things fixed/done before the release of 4.0.0:
 - full python 2/3 compatibility
 - move the template for neighbour in a neighbour section under template 

I will look at fixing this api issue at the same time. It may be that I create an API section under template and then have the neighbour reference it, or allow nesting. I have not given it any thought.

What I mean if you are using master - be careful when updating in the incoming weeks.

**Comment by thomas-mangin** [comment]
@brijohn I think I fixed this issue some time ago but never updated this entry ...

**Comment by brijohn** [comment]
@thomas-mangin Unless this was fixed in the last couple of days it still seems to be an issue in master. 

When the api section is set under a template-neighbor section and multiple neighbors inherit the same template, then the information is only send to the first neighbor configured and not any of the others.

**Comment by thomas-mangin** [comment]
That must be a simple fix once I get my head around it .. Thank you for testing ..

**Comment by brijohn** [comment]
@thomas-mangin Tested this and setting the api section in a template does seem to work now.

**Comment by thomas-mangin** [comment]
Fantastic - just fixed a few more things today .. hopefully the new code is now bug free.

**Comment by thomas-mangin** [comment]
(and yes the neighbor code was updated)

**Comment by brijohn** [comment]
There seem to still be bugs with the code for displaying the api section for neighbors. 

If I define  a template that contains an API section and create 2 neighbors that inherit that template, then when I execute  a show neighbors api command each neighbor block prints out the api section twice. The number of times the api section is printed for a neighbor increases for each neighbor added.

**Comment by thomas-mangin** [comment]
@brijohn - do you have a test lab I can use - it would make testing easier - but if not easy I will replicate.

**Comment by thomas-mangin** [comment]
@brijohn is this still an issue please - I am trying to get 4.0.2 and if this is still the case this is a blocker.

**Comment by thomas-mangin** [comment]
tada ! 162b6c95
