### ISSUE TITLE
Unavailable article in Readme

### ISSUE THREAD

**Issue by merlineus** [Exa-Networks/exabgp#590]
http://blog.iweb-hosting.co.uk/blog/2012/01/27/using-bgp-to-serve-high-availability-dns/ is no longer available. Does anybody have a copy of this article?

**Comment by thomas-mangin** [comment]
I do not have a copy (and will remove the link if it is dead later on).

**Comment by vincentbernat** [comment]
It's available here:
 - http://web.archive.org/web/20150627105230/https://www.iweb-hosting.co.uk/blog/using-bgp-to-serve-high-availability-dns.html
 - http://archive.is/zkfe9

**Comment by thomas-mangin** [comment]
removed from wiki (commented)
