### ISSUE TITLE
How to restart exabgp if process died?

### ISSUE THREAD

**Issue by amarao** [Exa-Networks/exabgp#594]
##### ISSUE TYPE

 - Feature Idea
 - Documentation Report

##### OS
ubuntu 14.04

##### VERSION
```
ExaBGP : 3.4.18
Python : 2.7.6 (default, Oct 26 2016, 20:30:19)  [GCC 4.8.4]
Uname  : #152-Ubuntu SMP Fri Dec 2 15:37:11 UTC 2016

```

##### CONFIGURATION
```
      process add_route {
                run /usr/bin/announce-processor-wrapper;
                encoder text;
                receive {
                        update;
                        parsed;
                }
                neighbor-changes;
        }
```

##### SUMMARY
Exabgp may respawn process if it dies. It sounds OK for most cases, but we want exabgp to stop itself (die) if that process stopped (instead of restarting it).

Can exabgp do this?

**Comment by azlux** [comment]
For my case, I use [ **Supervisor** ](http://supervisord.org/) to do the work. It will try to restart exabgp 10 time. You can program action if died and there are a lot of feature with this program.

Conf example :
```bash
[program:exa]
command=exabgp /root/exabgp/custom.exaBGP.conf
autostart=true
autorestart=true
stderr_logfile=/var/log/exa.err.log
stdout_logfile=/var/log/exa.out.log
startretries=10
startsecs=10
stopwaitsecs=10
stopsignal=INT
```

**Comment by amarao** [comment]
@azlux, I afraid Supervisor is not a proper solution here. I don't need some reaction on exabgp death. Systemd can handle it without any problems. I need some way to kill exabgp when helper process exited. For now I wrote a two-line patch to do this, but official feature is definitively better than a crude patch.

**Comment by thomas-mangin** [comment]
now it can: https://github.com/Exa-Networks/exabgp/commit/7e19b93d8d7f039e6cccb5e3131565fce7ef8f05

**Comment by amarao** [comment]
Thank you very much!

**Comment by thomas-mangin** [comment]
@amarao  Feel free to re-open the issue if it did not work as expected (no reason but testing was minimal)
