### ISSUE TITLE
Question about the performance of exaBgp

### ISSUE THREAD

**Issue by LiMinggang** [Exa-Networks/exabgp#595]
##### ISSUE TYPE
 - Documentation Report

##### OS
N/A

##### VERSION
Latest in Git

##### ENVIRONMENT 
Fedora core 22 64bit

##### CONFIGURATION
N/A

##### SUMMARY
How faster exaBGP can send out the simple IPv4 routes with limited attributes? About 120 bytes per routes? Eg:

A V Destination        P Prf   Metric 1   Metric 2  Next hop        AS path
* N 1.0.4.0/24         B 170        100                             7018 6939 4637 1221 38803 56203 I
  unknown                                          >12.0.1.1
  N                    B 170        100                             7018 6939 4637 1221 38803 56203 I
  unknown                                          >12.0.1.1
  N                    B 170        100                             7018 6939 4637 1221 38803 56203 I
  unknown                                          >12.0.1.1
  N                    B 170        100                             7018 6939 4637 1221 38803 56203 I
  unknown                                          >12.0.1.1
  N                    B 170        100                             7018 6939 4637 1221 38803 56203 I
  unknown                                          >12.0.1.1
  N                    B 170        100                             7018 6939 4637 1221 38803 56203 I
  unknown                                          >12.0.1.1
  N                    B 170        100                             7018 6939 4637 1221 38803 56203 I
  unknown                                          >12.0.1.1
  N                    B 170        100                             7018 6939 4637 1221 38803 56203 I
  unknown                                          >12.0.1.1
  N                    B 170        100                             7018 6939 4637 1221 38803 56203 I
  unknown                                          >12.0.1.1
  N                    B 170        100                             7018 6939 4637 1221 38803 56203 I
  unknown                                          >12.0.1.1
  N                    B 170        100                             7018 6939 4637 1221 38803 56203 I
  unknown                                          >12.0.1.1
  N                    B 170        100                             7018 6939 4637 1221 38803 56203 I
  unknown                                          >12.0.1.1

**Comment by thomas-mangin** [comment]
for the best performance, make sure update grouping is enabled, use the API and the syntax:
`announce attribute next-hop ... community ... nlri <nlri> <nlri> ...`

more info about how to better use ExaBGP for large announcement here:
https://github.com/Exa-Networks/exabgp/issues/586

**Comment by LiMinggang** [comment]
Hi, Thomas, 
Thanks for your quick response.  I read the issue #586, which is mainly for memory. Do you have any data on how fast it can send out the routes?

I've about 640K routes to be sent and most of then have different attributes which can not be merge in to one update with multiple NLRI.

Did I miss some information in #586?

Thanks in advance.

**Comment by LiMinggang** [comment]
I'll do some estimation on the effort to convert the routes to exaBGP's. I'll be back with the data if I did the test finally.
Thanks!

**Comment by JustinAzoff** [comment]
@LiMinggang hey!

Since I had the tests setup for testing 150k routes it was easy enough to test it with 640k routes.

On the receiver exabgp process I used this script:
```
#!/usr/bin/env python

import time
import sys

count = 0

start = time.time()

while True:
        line = sys.stdin.readline()
        if not line:
            break
        if 'announce' in line or 'with' in line:
                count += 1
                if count == 1:
                    first = time.time()
                if count%2000 == 0:
                    now = time.time()
                    sys.stderr.write('received %-10d first=%ds total=%ds\n' % (count, first - start, now - start))
                    sys.stderr.flush()
```

If I start up the sender exabgp first with no receiver it takes about 21s to inject 640k routes one at a time into itself.  Note: changing the log level to NOTICE is a must, otherwise it spends 90% of its time logging the route announcements.  Injecting 50 at a time takes 2s. Injecting 2 at a time takes 12s.. so really any amount of grouping you can do will speed up the process.

Once the sending side is running with 650k routes injected one at a time, if I start up the receiver I get the following result:

    received 640000     first=5s total=92s
 
If I inject 10 at a time I get

    received 640000     first=6s total=36s

If I inject 50 at a time I get

    received 640000     first=13s total=36s

So.. it looks like, worst case of injecting 640k routes one at a time ends up taking (on my boxes between 2 exabgp processes) about a minute and a half.

**Comment by LiMinggang** [comment]
@JustinAzoff Thanks a lot! 
What the routes you used, I mean, do they have same attributes like you did for the 150K routes test? Or, everyone has different attributes from others?

**Comment by thomas-mangin** [comment]
@JustinAzoff on what hardware was this test performed - knowing that ExaBGP only uses one CPU/core.

**Comment by JustinAzoff** [comment]
@LiMinggang 

Ah, they were all the same:

    announce attribute next-hop self community [ 65101:666 no-export ] nlri 1.2.3.4/32

The sender was a vm on a Intel(r) Xeon(r) CPU E3-1220 v3 @ 3.10GHz and the receiver was bare metal on Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz.

**Comment by thomas-mangin** [comment]
To make sure it was said, if you are using 3.4 please please please enable "group-updates" on the peer as it will make a massive speed difference too for it when parsing the received update (and update generation will also be faster).

**Comment by JustinAzoff** [comment]
I had `group-updates;` on the sender but not the receiver. adding it to the receiver doesn't appear to have changed the results... removing it from the sender sure makes things worse though.

the batchsize of 50 ended up taking 3x longer at a little over a minute.

the one at a time run went from 90s to 180s or so.. but only got up to 628000 routes before it hung.

**Comment by thomas-mangin** [comment]
group-update affects how packets are generated (so it only affect packets sent), and will indeed have no effect on the receiving end.
@JustinAzoff It should never hang. If you can reproduce, can you please open an new issue about this and provide me (per mail if you want) the output of `exabgp -d` (it will be quite big, I really need the few hundred first lines and the few hundred last if it helps )
