### ISSUE TITLE
reload problem with USR1

### ISSUE THREAD

**Issue by pubyun** [Exa-Networks/exabgp#596]
exabgp, version git master,

/usr/bin/python /usr/bin/exabgp  conf/template.conf

ps to find PID of exabgp, 790856, and send signal:

kill -USR1  790856

Sun, 02 Apr 2017 21:30:59 790856 network       Peer       127.0.0.1 ASN 65533   connection to 127.0.0.1:179 failed
Sun, 02 Apr 2017 21:31:04 790856 reactor       SIG USR1 received - reload configuration
Sun, 02 Apr 2017 21:31:04 790856 reactor       performing reload of exabgp 4.0.0
Sun, 02 Apr 2017 21:31:04 790856 configuration > template         |
Sun, 02 Apr 2017 21:31:04 790856 configuration > neighbor         | 'test'
Sun, 02 Apr 2017 21:31:04 790856 configuration problem with the configuration file, no change done
Sun, 02 Apr 2017 21:31:04 790856 configuration problem parsing configuration file line 3
Sun, 02 Apr 2017 21:31:04 790856 configuration error message: the name "test" already exists in template-neighbor

**Comment by thomas-mangin** [comment]
Hello @pubyun - I am not sure I am going to keep the signals in master / 4.0. It may indeed be broken.

**Comment by brijohn** [comment]
@pubyun @thomas-mangin 

I didn't notice this existing issue when i patched this bug, but this problem should be fixed by commit 62e122269bf.
