### ISSUE TITLE
4.0.0 release date ?

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#598]
Hello,

The only change holding back the release of ExaBGP 4.0.0 is python3 support (lots was already done by @tmmorin with six).

It seems that the big'gy will be the conversion of all the string used for encoding / decoding into b"" string.

Once this is completed, I am "happy" to release. Help welcomed !

**Comment by tmmorin** [comment]
Do you have a process on which we could iterate ?
(test with py3, fix an issue, validate with py2/py3, rince & repeat...)

**Comment by thomas-mangin** [comment]
@tmmorin: sounds like the plan 😃

**Comment by tmmorin** [comment]
Yes, but the existing unit test suite does already pass with python3.
What do you suggest running to test the rest ?

(the other plan would be: run 2to3, but not to modify the source, which would become non-python2 compatible, but to see all the places that can be changed for python3.  But filtering all the suggested changes, to keep only the ones that are strictly needed, is cumbersome...)

**Comment by thomas-mangin** [comment]
When I ran the code "by hand" it fails so I assume the test suite is broken ... again ...

**Comment by tmmorin** [comment]
In fact, the only test suite I had been running for the initial python3 work was qa/tests/*.py

I've now a work branch in my repo which is passing much more tests from qa/bin.
I still have issues running some qa/bin/conversation tests, but there are issues with py2 as well as py3.

**Comment by thomas-mangin** [comment]
@tmmorin do you want to share/merge your branch - so I can make sure that any regression in the test suite is fixed in both p2 and p3 please ?

**Comment by tmmorin** [comment]
I had a few more things to merge first, but now here is the branch:
https://github.com/tmmorin/exabgp/tree/py3

some more tests pass with my proposed fix for #613, but not all of them

**Comment by tmmorin** [comment]
the whole test suite (except qa/bin/conversation tests that seem hard to pass in python2 as well) seem to be happy with python3

anything else missing for releasing a 4.0.0beta ?

**Comment by thomas-mangin** [comment]
I need to change a few things ( version reported for JSON and TEXT interface ), but I should be able to release in the next few days.

**Comment by thomas-mangin** [comment]
4.0.0 was released !
