### ISSUE TITLE
is it possible to block GRE with flowspec in v 3.4.13 ?

### ISSUE THREAD

**Issue by GlassRod** [Exa-Networks/exabgp#604]
# VERSION
3.4.13

# SUMMARY
We have a customer wanting to block GRE traffic using flowspec. is it possible with this version ? if so what is the config ?

**Comment by thomas-mangin** [comment]
The protocol for GRE is 0x2F (47), You can use the `protocol gre` or `protocol [ gre ]` option to do so if not `protocol 47` or `protocol [ 47 ]`.

See https://github.com/Exa-Networks/exabgp/blob/master/qa/conf/flow.conf for many examples

Should work with most versions of exabgp (3.x)

**Comment by thomas-mangin** [comment]
With no feedback, I assume it did the trick / closing the issue.
