### ISSUE TITLE
md5 options behave extemely wierd

### ISSUE THREAD

**Issue by amarao** [Exa-Networks/exabgp#605]
##### ISSUE TYPE

 - Bug Report

##### OS
Linux, 4.4, Ubuntu Trusty

##### VERSION

```
ExaBGP : 3.4.17
Python : 2.7.6 (default, Oct 26 2016, 20:30:19)  [GCC 4.8.4]
Uname  : #96~14.04.1-Ubuntu SMP Thu Apr 20 11:06:30 UTC 2017
```

##### ENVIRONMENT 

```
exabgp --di

[exabgp.daemon]
user = 'exabgp'
```

##### CONFIGURATION
```
group ALL_PEERS {
        router-id 78.140.148.33;
        local-address 78.140.148.33;
        process add_route {
                run /usr/bin/announce-processor-wrapper;
                encoder text;
                receive {
                        update;
                        parsed;
                }
                neighbor-changes;
        }
        neighbor 8.8.8.8 {
            local-as 40824;
            peer-as 46786;
                        md5-password ZGIwMzk3MmEtMjljMC0xMWU3LWJiMDMtY2IzYTM5NjJkNDdk;
                        md5-base64 true;
                }
        }

```

##### SUMMARY

This configuration cause exabgp to set md5 variable in exabgp/reactor/network/tcp.py (MD5 function) to `'-base64 true'`, which cause problems with authorization. Same applied if I use `'md5-password "mypassword"'` - in this case md5 would become `'-password "mypassword"'`, which is clearly wrong.

We spend few hours trying to understand why md5 auth does not work. We set it up according to this link:https://github.com/Exa-Networks/exabgp/blob/4d11197e0ad950f0173d4da0f5a35a1b6cc301bf/qa/conf/md5.conf

**Comment by brijohn** [comment]
The options md5-password and md5-base64 are options introduced in ExaBGP version 4.x.  You seem to be using 3.4.17 which  uses md5: "mypassword"; and does not support base64 encoding of the password.

**Comment by amarao** [comment]
Hello. I've checked branches and tags for this repo, but all versions are 3.x. Where are those 4.x versions you mentioned?

**Comment by brijohn** [comment]
4.x is the master branch.  It has yet to be officially released, so there is not tag for it yet.

**Comment by thomas-mangin** [comment]
Hello George,

Brian just added this feature to master. For 3.4 just using your normal password "db03972a-29c0-11e7-bb03-cb3a3962d47d" as this can be reverse engineered in one line of python, it is not really a security feature but just a convenience feature.

```
$ python
>>> "ZGIwMzk3MmEtMjljMC0xMWU3LWJiMDMtY2IzYTM5NjJkNDdk".decode('base64')
'db03972a-29c0-11e7-bb03-cb3a3962d47d'
```

**Comment by amarao** [comment]
I think that exabgp behavior is strange. Why it consumes "-password 'xxxx'" as key from configuraiton line  md5-password 'xxxx' instead of complaining about wrong option?

**Comment by thomas-mangin** [comment]
Sorry - I can not understand your question .. Could you please re-phrase it ?

**Comment by amarao** [comment]
When exagbp 3.xx run with config above, it uses string after md5 as password, even if it looks for human eye as part of option name.

when I see config md5-password ZGIwMzk3MmEtMjljMC0xMWU3LWJiMDMtY2IzYTM5NjJkNDdk;
I expects that it will use 'Z...dk' as password, or will print error if 'md5-password' is not valid option in config.

In reality exa will use string `-password  ZGIwMzk3MmEtMjljMC0xMWU3LWJiMDMtY2IzYTM5NjJkNDdk` as password. It found this weird.

**Comment by thomas-mangin** [comment]
ok - understood - so nothing related to the change.

**Comment by thomas-mangin** [comment]
@brijohn we could change the code to try to MD5 decode the password and if it does use that information - i.e.: automatic ?

**Comment by thomas-mangin** [comment]
the new md5-option could have "yes/no/auto" and make "auto" the default behaviour ?

**Comment by brijohn** [comment]
@thomas-mangin The password isn't MD5 encoded, do you mean try and Base64 decode it? 

That won't work well since the only time trying to Base64 decode a string in python will faill is due to incorrect padding, otherwise it will succeed just fine. This would make it impossible for us to determine if the string is actually a base64 encoded string or not without explicitly telling exabgp that it uses Base64 encoding.

**Comment by thomas-mangin** [comment]
@brijohn sorry, yes, I meant Base64 ..

What I was trying to say is to allow people to provide the string as a base64 string (as currently it only allow the plain text one) by having another option indicating how to handle the string.

It should be possible to check if the string is base64, by adding "=" and "==" and seeing if any of the three strings decode ... we could be (un)lucky and find that it does when the password is not, but it is going to be the odd one out but it would allow to have 'auto' as default and allow people to explicitly set it out if we guess wrongly. 

Happy to leave things as it that said.

**Comment by thomas-mangin** [comment]
ok - that should do what people want. check if the data is formatted as base64 "automagically".
https://github.com/Exa-Networks/exabgp/commit/ce5ab8573cafac42d3dd85559971f135803d36f1

**Comment by ekoyle** [comment]
This is actually kind of unexpected... base64 is a fairly simple encoding, and any string using the correct character set ([`A-Za-z0-9+/`]) with an appropriate length (anything but `4n+1`, so invalid lengths would be 1, 5, 9, 13, ...) will be misinterpreted as base64.

If you were to remove the code that adds `=` and `==`,  then anything with a length divisible by 4 could be improperly interpreted as base64 -- and people tend to use multiples of 4 for password lengths.

**Comment by thomas-mangin** [comment]
there is a option `md5-base64` which can be used to say if the password is plain text or base64 encoded.
