### ISSUE TITLE
Programmatically trigger route refresh

### ISSUE THREAD

**Issue by JonasGroeger** [Exa-Networks/exabgp#606]
Hello!

I have exabgp running using this configuration:

```
...SNIP...
    process stdout {
        run "/usr/bin/process_data";
        encoder json;

        receive {
            parsed;
            update;
        }
    }
...SNIP...
```
In `/usr/bin/process_data` I read stdin to receive BGP messages. Now I would like to trigger a route refresh. As far as I know this is possible by first configuring a

```
capabilities {
    route-refresh;
}
```
section and then sending something to stdout, right? Since I'm using a json encoder, how would I instruct the other peer to do a route-refresh? What is the format on stdout? I couldn't find anything in the docs.

I'm using ExaBGP 3.4.13 on Debian.

**Comment by thomas-mangin** [comment]
we have no "json" for command, we only support the "text".
The command is: "announce route-refresh"

**Comment by thomas-mangin** [comment]
You should be able to send this command even if you are using JSON  ... never tried tho

**Comment by JonasGroeger** [comment]
I'm testing this right now.

**Comment by thomas-mangin** [comment]
@JonasGroeger all working - can close ?

**Comment by JonasGroeger** [comment]
Oh, yeah. Can be closed. I documented by use here: https://github.com/JonasGroeger/notes/blob/master/0-GoBGP-and-ExaBGP.md

**Comment by thomas-mangin** [comment]
@Jonas - Can you please add this information to the wiki ?

**Comment by JonasGroeger** [comment]
@thomas-mangin The text is more of a brain dump and rather low quality. sure you want that in the wiki?

**Comment by thomas-mangin** [comment]
Yes please :-)
