### ISSUE TITLE
Announcing example flow route causes session to drop (UPDATE message error / Invalid Network Field)

### ISSUE THREAD

**Issue by robdn** [Exa-Networks/exabgp#611]
##### ISSUE TYPE

 - Bug Report

##### OS

CentOS 7

##### VERSION

```
ExaBGP : 3.4.18
Python : 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
Uname  : #1 SMP Wed Apr 12 15:04:24 UTC 2017

```

##### ENVIRONMENT 

```
(none)
```

##### SUMMARY

Sessions dropped by MX480 (running recommended: 14.1R6.4) when flow route announced.

##### STEPS TO REPRODUCE

Run configuration as the above with Junos 14.1.R6.4

##### EXPECTED RESULTS

Flow route installed in Juniper router

##### ACTUAL RESULTS

Juniper:
```
rpd[1662]: bgp_rcv_nlri:9024: NOTIFICATION sent to 10.1.1.254 (Internal AS 65000): code 3 (Update Message Error) subcode 10 (bad address/prefix field), Reason: peer 10.1.1.254 (Internal AS 65000) update included invalid route zero-len/0 (0 of 33)
```
ExaBGP: 
```
exabgp: 2770   network       Connected to peer neighbor 10.1.1.1 local-ip 10.1.1.254 local-as 65000 peer-as 65000 router-id 10.1.1.254 family-allowed in-open (out)
exabgp: 2770   network       Peer     10.1.1.1 ASN 65000   out loop, peer reset, message [notification received (3,10)] error[UPDATE message error / Invalid Network
```

Session dropped

##### IMPORTANCE

Issue affecting implementation stage

**Comment by stoffi92** [comment]
Can you please also share the flow-spec route you are announcing towards the MX. I think I saw something very similar in our recent lab sessions. In our case this was a Juniper-Bug but I can tell you immediately once you share the flow that you are announcing.

Christoph

**Comment by thomas-mangin** [comment]
Hello @robdn 

If you can please run exabgp with the "-d" option which will start logging the packets exchanged between the routers and provide the _whole_ output. It will include the configuration, the OPEN message exchanged AND the UPDATE messages are required for us to diagnose what is happening.

If you prefer to not share this data here, feel free to send it to my personal email which is my first name @ family name .com

Sincerely,

Thomas

**Comment by thomas-mangin** [comment]
referencing @stoffi92 very good paper on flow-spec interop
http://p4.tix.at/~cl/fs/loibl-bacher-bgp-flowspec-interop-012017.pdf

**Comment by thomas-mangin** [comment]
No information. Closing as I do not believe the bug to be with ExaBGP.
