### ISSUE TITLE
Make ExaBGP fit for draft-ietf-idr-rfc5575bis-01

### ISSUE THREAD

**Issue by stoffi92** [Exa-Networks/exabgp#612]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

I promised to write a short summary of what I think is needed to make ExaBGP fit for RFC5575bis. Note that draft-ietf-idr-rfc5575bis-01 is only draft status. However the required changes should not break compatibility with existing implementations.

### My Summary:

(I am referring to the current draft-ietf-idr-rfc5575bis-01 section numbers)

**Section 4.2.3**

The possible comparision bit combinations for the numeric operator (lt, gt, eq)
have been explicitly defined (RFC 5575 leaves this open). 

ExaBGP may need to add !=, true, false.   

**Section 4.2.3, 4.2.4, 4.2.5, 4.2.6, 4.2.7, 4.2.8, 4.2.10, 4.2.11**

Those sections (flow components) use the exact same numeric operator. The
allowed length (len) of the value is defined in each of those sections:
```
4.2.3 Type3-IP Protocol = 1 byte (len = 00) 
4.2.4 Type4-Port = 1 or 2 byte 
4.2.5 Type5-Dest-Port = 1 or 2 byte 
4.2.6 Type6-Src-Port = 1 or 2 byte 
4.2.7 ICMP-Type =1 byte 
4.2.8 ICMP-Code = 1 byte 
4.2.10 Packet-Length = 1 or 2 byte 
4.2.11 DSCP = 1 byte
```
ExaBGP may need to encode BGP-flow-updates with the correct length.  This is
completely compatible with RFC5575 only that the use of the length field is  now
more restrictive.

**Section 4.2.9, 4.2.12**

Those sections (flow components) use the same bitmask operator defined in 4.2.9

**Section 7 (and 7.2)**

A new traffic filtering action (traffic-rate-packets) has been introduced.

Since there is no ext-community assigned yet there is nothing to do.

**Section 7.6**

This is entirely new. It defines how updates shall be handled if they contain
interfering  actions. (like ie. rate-limit 0 _and_ rate-limit 1000000 in the
same update).

I am not sure if this is relevant to ExaBGP since you do not implement a RIB. 

**Section 7.3** 

This section also makes a reference to Section 7.6 but may not relevant to
ExaBGP

All the changes are completely compatible with current implementations but fill
the gap where RFC5575 was unclear and implementations tended to behave
differently.

**Comment by thomas-mangin** [comment]
Analysing the information

**Section 4.2.3**

true and false were implemented for NumericString following the discussion in 438.

**Length of generated data**

```
4.2.3 Type3-IP Protocol = 1 byte (len = 00)   Yes: IOperationByte
4.2.4 Type4-Port = 1 or 2 byte                        Yes: IOperationByteShort
4.2.5 Type5-Dest-Port = 1 or 2 byte               Yes: IOperationByteShort
4.2.6 Type6-Src-Port = 1 or 2 byte                 Yes: IOperationByteShort
4.2.7 ICMP-Type =1 byte                                  Yes: IOperationByte
4.2.8 ICMP-Code = 1 byte                                Yes: IOperationByte
4.2.10 Packet-Length = 1 or 2 byte                 Yes: IOperationByteShort
4.2.11 DSCP = 1 byte                                        No : IOperationByteShort
```

The decoding of IOperationByteShort is marked as known as buggy and need fixing.

**Section 4.2.9, 4.2.12**

I believe the code already complies with this.

**Section 7 (and 7.2)**

TODO when ext-community is  assigned

**Section 7.3**
**Section 7.6**

ExaBGP takes no action based on the data so it does not require any change.

**Comment by thomas-mangin** [comment]
AFAICS - now bis compliant .. until the ext-community is assigned.
