### ISSUE TITLE
some qa/bin/conversation tests broken by c7be8670967a228fe0e86dab899238e2a5b38ad0

### ISSUE THREAD

**Issue by tmmorin** [Exa-Networks/exabgp#613]
The change introduced by c7be8670967a228fe0e86dab899238e2a5b38ad0 is breaking the qa/bin/conversation test suite for some tests. The API process for the test is restarted when it shouldn't.

For instance, with the qa/conf/api-check.conf test:

> 
> ~/prog/openstack/exabgp% client=8 ./qa/bin/conversation                                                                                                                                            
> :: env exabgp_debug_configuration=true exabgp_tcp_port=1830 exabgp_tcp_once=true exabgp_debug_rotate=true exabgp_tcp_bind='' /home/teom7365/prog/openstack/exabgp/sbin/exabgp -d -p /home/teom7365/prog/openstack/exabgp/qa/conf/api-check.conf
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | reactor       | performing reload of exabgp py3-0c3589eec117ed14a5d245bc7b8e83997d412343
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | > process          | 'check-and-announce'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . run              | 'api-check.run'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . encoder          | 'text'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | < process          | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | > template         | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | > neighbor         | 'controler'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | > family           | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . ipv4             | 'unicast'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . ipv6             | 'unicast'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | < family           | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | > api              | 'connection'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . processes        | '[' 'check-and-announce' ']'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . neighbor-changes | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | > receive          | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . parsed           | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . update           | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | < receive          | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | > send             | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . parsed           | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . update           | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | < send             | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | < api              | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | > static           | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . route            | '::1/128' 'next-hop' '::1'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . route            | '127.0.0.1/32' 'next-hop' '127.0.0.2'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | < static           | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | < controler        | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | < template         | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | > neighbor         | '127.0.0.1'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . inherit          | 'controler'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . local-as         | '65512'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . peer-as          | '65512'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . hold-time        | '30'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . local-address    | '127.0.0.1'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | . router-id        | '10.0.0.139'
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | < neighbor         | 
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | reactor       | new peer: neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 65512 peer-as 65512 router-id 10.0.0.139 family-allowed in-open
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | configuration | loaded new configuration successfully
> Mon, 08 May 2017 12:39:23 | INFO     | 28411  | processes     | Forked process check-and-announce
> Mon, 08 May 2017 12:39:23 | DEBUG    | 28411  | network       | out loop, intialising
> Mon, 08 May 2017 12:39:24 | DEBUG    | 28411  | wire          | attempting connection to 127.0.0.1:1830
> 
> exabgp:neighbor 127.0.0.1 connected
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100', 'neighbor 127.0.0.1 receive update end']
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            SENDING  (  53) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0035 0104 FFE8 001E 0A00 008B 1802 0601 0400 0100 0102 0601 0400 0200 0102 0641 0400 00FF E8
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   >> OPEN version=4 asn=65512 hold_time=30 router_id=10.0.0.139 capabilities=[Multiprotocol(ipv4 unicast,ipv6 unicast), ASN4(65512)]
> 
> exabgp:
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            RECEIVED  (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0035 01
> local-preference 100', 'neighbor 127.0.0.1 receive update end']
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            RECEIVED  (  34) 04FF E800 1E0A 0000 8C18 0206 0104 0001 0001 0206 0104 0002 0001 0206 4104 0000 FFE8
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   << OPEN
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   << OPEN version=4 asn=65512 hold_time=30 router_id=10.0.0.140 capabilities=[Multiprotocol(ipv4 unicast,ipv6 unicast), ASN4(65512)]
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 59 second(s) left
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            SENDING  (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   >> KEEPALIVE (OPENCONFIRM)
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            RECEIVED  (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   << KEEPALIVE
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 29 second(s) left
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | network       | Connected to peer neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 65512 peer-as 65512 router-id 10.0.0.139 family-allowed in-open (out)
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            RECEIVED  (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0031 02
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            RECEIVED  (  30) 0000 0015 4001 0100 4002 0040 0304 7F00 0001 4005 0400 0000 6420 0000 0000
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   << UPDATE
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | parsing UPDATE (  30) 0000 0015 4001 0100 4002 0040 0304 7F00 0001 4005 0400 0000 6420 0000 0000
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | withdrawn NLRI none
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | attribute origin             flag 0x40 type 0x01 len 0x01 payload 00
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | attribute as-path            flag 0x40 type 0x02 len 0x00
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | attribute next-hop           flag 0x40 type 0x03 len 0x04 payload 7F00 0001
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | attribute local-preference   flag 0x40 type 0x05 len 0x04 payload 0000 0064
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | NLRI      ipv4 unicast       without path-information     payload 2000 0000 00
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | announced NLRI 0.0.0.0/32 next-hop 127.0.0.1
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 29 second(s) left
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | routes        | peer 127.0.0.1 ASN 65512   << UPDATE (1) (   3)  attributes origin igp local-preference 100
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | routes        | peer 127.0.0.1 ASN 65512   << UPDATE (1) nlri  (   5) 0.0.0.0/32 next-hop 127.0.0.1
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | parsing UPDATE (  59) 0000 0037 4001 0100 4002 0040 0504 0000 0064 800E 2600 0201 1000 0000 0000 0000 0000 0000 0000 0000 0100 8000 0000 0000 0000 0000 0000 0000 0000 01
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | withdrawn NLRI none
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | attribute origin             flag 0x40 type 0x01 len 0x01 payload 00
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | attribute as-path            flag 0x40 type 0x02 len 0x00
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | attribute local-preference   flag 0x40 type 0x05 len 0x04 payload 0000 0064
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | attribute mp-reach-nlri      flag 0x80 type 0x0e len 0x26 payload 0002 0110 0000 0000 0000 0000 0000 0000 0000 0001 0080 0000 0000 0000 0000 0000 0000 0000 0001
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | NLRI      ipv6 unicast       without path-information     payload 8000 0000 0000 0000 0000 0000 0000 0000 01
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | announced NLRI none
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            SENDING  (  78) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 004E 0200 0000 3740 0101 0040 0200 4005 0400 0000 6480 0E26 0002 0110 0000 0000 0000 0000 0000 0000 0000 0001 0080 0000 0000 0000 0000 0000 0000 0000 0001
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | parsing UPDATE (  30) 0000 0015 4001 0100 4002 0040 0304 7F00 0002 4005 0400 0000 6420 7F00 0001
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | withdrawn NLRI none
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | attribute origin             flag 0x40 type 0x01 len 0x01 payload 00
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | attribute as-path            flag 0x40 type 0x02 len 0x00
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | attribute next-hop           flag 0x40 type 0x03 len 0x04 payload 7F00 0002
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | attribute local-preference   flag 0x40 type 0x05 len 0x04 payload 0000 0064
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | NLRI      ipv4 unicast       without path-information     payload 207F 0000 01
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | parser        | announced NLRI 127.0.0.1/32 next-hop 127.0.0.2
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            SENDING  (  49) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0031 0200 0000 1540 0101 0040 0200 4003 047F 0000 0240 0504 0000 0064 207F 0000 01
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   >> 2 UPDATE(s)
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            RECEIVED  (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   << KEEPALIVE
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 29 second(s) left
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            SENDING  (  23) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0017 0200 0000 00
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   >> EOR ipv4 unicast
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            SENDING  (  30) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 0200 0000 0790 0F00 0300 0201
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   >> EOR ipv6 unicast
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | peer 127.0.0.1 ASN 65512   >> EOR(s)
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            RECEIVED  (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   << KEEPALIVE
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 29 second(s) left
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            RECEIVED  (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   << KEEPALIVE
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 29 second(s) left
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            RECEIVED  (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   << KEEPALIVE
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 29 second(s) left
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            RECEIVED  (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
> Mon, 08 May 2017 12:39:25 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   << KEEPALIVE
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 29 second(s) left
> Mon, 08 May 2017 12:39:25 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 29 second(s) left
> Mon, 08 May 2017 12:39:26 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 29 second(s) left
> Mon, 08 May 2017 12:39:26 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Send Timer 9 second(s) left
> 
> exabgp:neighbor 127.0.0.1 up
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100', 'neighbor 127.0.0.1 receive update end']
> Mon, 08 May 2017 12:39:27 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 28 second(s) left
> Mon, 08 May 2017 12:39:27 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Send Timer 8 second(s) left
> 
> exabgp:
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100', 'neighbor 127.0.0.1 receive update end']
> Mon, 08 May 2017 12:39:28 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 27 second(s) left
> Mon, 08 May 2017 12:39:28 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Send Timer 7 second(s) left
> 
> exabgp:neighbor 127.0.0.1 receive update start
> 
> left ['neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100', 'neighbor 127.0.0.1 receive update end']
> Mon, 08 May 2017 12:39:29 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 26 second(s) left
> Mon, 08 May 2017 12:39:29 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Send Timer 6 second(s) left
> 
> exabgp:neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100
> 
> left ['neighbor 127.0.0.1 receive update end']
> Mon, 08 May 2017 12:39:30 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 25 second(s) left
> Mon, 08 May 2017 12:39:30 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Send Timer 5 second(s) left
> 
> exabgp:neighbor 127.0.0.1 receive update end
> 
> left []
> Mon, 08 May 2017 12:39:31 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 24 second(s) left
> Mon, 08 May 2017 12:39:31 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Send Timer 4 second(s) left
> Mon, 08 May 2017 12:39:32 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 23 second(s) left
> Mon, 08 May 2017 12:39:32 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Send Timer 3 second(s) left
> Mon, 08 May 2017 12:39:33 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 22 second(s) left
> Mon, 08 May 2017 12:39:33 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Send Timer 2 second(s) left
> Mon, 08 May 2017 12:39:33 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 22 second(s) left
> Mon, 08 May 2017 12:39:33 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Send Timer 2 second(s) left
> Mon, 08 May 2017 12:39:33 | INFO     | 28411  | processes     | Command from process check-and-announce : neighbor 127.0.0.1 announce route 1.2.3.4 next-hop 5.6.7.8 
> Mon, 08 May 2017 12:39:33 | WARNING  | 28411  | reactor       | callback | handling 'neighbor 127.0.0.1 announce route 1.2.3.4 next-hop 5.6.7.8' with announce route

The problem arises here:

> Mon, 08 May 2017 12:39:33 | INFO     | 28411  | processes     | Issue with the process, terminating it and restarting it
> Mon, 08 May 2017 12:39:33 | INFO     | 28411  | processes     | Terminating process check-and-announce
> Mon, 08 May 2017 12:39:33 | INFO     | 28411  | processes     | Forked process check-and-announce

> Mon, 08 May 2017 12:39:33 | INFO     | 28411  | reactor       | callback | installing announce_route
> Mon, 08 May 2017 12:39:33 | INFO     | 28411  | reactor       | callback | running
> Mon, 08 May 2017 12:39:33 | INFO     | 28411  | configuration | . route            | '1.2.3.4' 'next-hop' '5.6.7.8'
> Mon, 08 May 2017 12:39:33 | INFO     | 28411  | reactor       | route added to neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 65512 peer-as 65512 router-id 10.0.0.139 family-allowed in-open : 1.2.3.4/32 next-hop 5.6.7.8
> Mon, 08 May 2017 12:39:33 | INFO     | 28411  | reactor       | responding to check-and-announce : done
> Mon, 08 May 2017 12:39:33 | INFO     | 28411  | reactor       | callback | removing
> 
> exabgp:done
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100', 'neighbor 127.0.0.1 receive update end']
> Mon, 08 May 2017 12:39:34 | INFO     | 28411  | reactor       | performing dynamic route update
> Mon, 08 May 2017 12:39:34 | INFO     | 28411  | reactor       | updated peers dynamic routes successfully
> Mon, 08 May 2017 12:39:34 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Receive Timer 21 second(s) left
> Mon, 08 May 2017 12:39:34 | DEBUG    | 28411  | timers        | peer 127.0.0.1 ASN 65512   Send Timer 1 second(s) left
> Mon, 08 May 2017 12:39:34 | INFO     | 28411  | parser        | parsing UPDATE (  30) 0000 0015 4001 0100 4002 0040 0304 0506 0708 4005 0400 0000 6420 0102 0304
> Mon, 08 May 2017 12:39:34 | INFO     | 28411  | parser        | withdrawn NLRI none
> Mon, 08 May 2017 12:39:34 | INFO     | 28411  | parser        | attribute origin             flag 0x40 type 0x01 len 0x01 payload 00
> Mon, 08 May 2017 12:39:34 | INFO     | 28411  | parser        | attribute as-path            flag 0x40 type 0x02 len 0x00
> Mon, 08 May 2017 12:39:34 | INFO     | 28411  | parser        | attribute next-hop           flag 0x40 type 0x03 len 0x04 payload 0506 0708
> Mon, 08 May 2017 12:39:34 | INFO     | 28411  | parser        | attribute local-preference   flag 0x40 type 0x05 len 0x04 payload 0000 0064
> Mon, 08 May 2017 12:39:34 | INFO     | 28411  | parser        | NLRI      ipv4 unicast       without path-information     payload 2001 0203 04
> Mon, 08 May 2017 12:39:34 | INFO     | 28411  | parser        | announced NLRI 1.2.3.4/32 next-hop 5.6.7.8
> Mon, 08 May 2017 12:39:34 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 / 127.0.0.1            SENDING  (  49) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0031 0200 0000 1540 0101 0040 0200 4003 0405 0607 0840 0504 0000 0064 2001 0203 04
> Mon, 08 May 2017 12:39:34 | INFO     | 28411  | message       | Peer       127.0.0.1 ASN 65512   >> 1 UPDATE(s)
> 
> exabgp:neighbor 127.0.0.1 send update start
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100', 'neighbor 127.0.0.1 receive update end']
> Mon, 08 May 2017 12:39:35 | DEBUG    | 28411  | wire          | session 1 outgoing, closing connection from 127.0.0.1 to 127.0.0.1
> Mon, 08 May 2017 12:39:35 | DEBUG    | 28411  | wire          | session 1 outgoing 127.0.0.1 lost TCP session with peer
> Mon, 08 May 2017 12:39:35 | INFO     | 28411  | network       | only one attempt to connect is allowed, stopping the peer
> 
> exabgp:neighbor 127.0.0.1 send update announced 1.2.3.4/32 next-hop 5.6.7.8 origin igp local-preference 100
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100', 'neighbor 127.0.0.1 receive update end']
> 
> exabgp:neighbor 127.0.0.1 send update end
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100', 'neighbor 127.0.0.1 receive update end']
> 
> exabgp:
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100', 'neighbor 127.0.0.1 receive update end']
> exabgp:
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100', 'neighbor 127.0.0.1 receive update end']
> 
> exabgp:
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100', 'neighbor 127.0.0.1 receive update end']
> 
> exabgp:
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100', 'neighbor 127.0.0.1 receive update end']
> 
> exabgp:
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.0.0.0/32 next-hop 127.0.0.1 origin igp local-preference 100', 'neighbor 127.0.0.1 receive update end']
> 
> exabgp:
> 
> left ['neighbor 127.0.0.1 receive update start', 'neighbor 127.0.0.1 receive update announced 0.

**Comment by tmmorin** [comment]
The issue is made worse by the fact there is no sleep in the first while loop of qa/conf/api-check.run, which loops eating 100% CPU the second time it is started.

**Comment by thomas-mangin** [comment]
As @brijohn done this change - and it was fixing an issue I can not replicate - I would like to get his input before trying to devise a solution.

**Comment by tmmorin** [comment]
Two things:
- it is indeed correct that the file/socket is closed if readline returns an empty string
- with python3, for the test above, without change c7be867, the CPU goes into a 100% CPU loop
- with python2 it does not happen (in my setup at least), but I havent investigated why yet

**Comment by tmmorin** [comment]
On my setup, I seem to see cases where readline returns '', while the process is still alive. I think this might be because the process stdout file descriptor is set to NON_BLOCK.  Somehow, the behavior with python3 is different.

**Comment by tmmorin** [comment]
Ok, I have one part of the answer perhaps.

http://bugs.python.org/issue1175#msg56041  is a bug where Guido (himself) explains that:

> readline() goes through C stdio which makes it impossible to get
non-blocking I/O right. You should be using raw os.read() calls (until
python 3000 which will remove Python's reliance on C stdio).

Which I guess explains the troubles we are having.

On my setup in python3, readline() on a process that is sleeping returns '', and exabgp (wrongly) concludes that the process has died. 

I guess this needs to be refactored to use read() .
