### ISSUE TITLE
multi next hop configuration for the same network

### ISSUE THREAD

**Issue by yevgeniyo** [Exa-Networks/exabgp#617]
##### ISSUE TYPE

 - Bug Report

##### VERSION

```
ExaBGP : 3.4.18
Python : 2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]
Uname  : #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 201
```

##### ENVIRONMENT 

```
[exabgp.daemon]
daemonize = true
user = 'root'

[exabgp.log]
configuration = false
destination = '/var/log/exabgp.log'
```

##### SUMMARY

Hi, I will be happy to get your help.
My issue is:

Let's assume I have advertised this line:
announce route 20.1.1.0/24 next-hop 2.2.2.3 community [ 19551:1 19551:2 666 ] local-preference 200 origin igp

Now I want to add ADDITIONAL next hop to this network, like
announce route 20.1.1.0/24 next-hop 2.2.2.4 community [ 19551:1 19551:2 666 ] local-preference 200 origin igp

But ExaBGP overwrite my first route....

I have seen here that solution run additional ExaBGP service, do you have more elegant solution for it?

BR, Yevgeniy

**Comment by thomas-mangin** [comment]
This is BGP normal behaviour, nothing ExaBGP specific. The only way around is to use AddPath if your router supports it.

**Comment by thomas-mangin** [comment]
Or as you noted, use multiple BGP speakers ..

**Comment by yevgeniyo** [comment]
hi Thomas, thank you for your help, can you advise with add-path configuration:

My ExaBGP configuration:

neighbor 198.143.46.209 {
router-id 198.143.46.211;
local-address 198.143.46.211;
local-as 19551;
peer-as 19551;
group-updates false;

capability {
add-path send/receive;
}

family {
ipv4 unicast;
}

static {
route 45.60.100.0/24 path-information 198.143.46.211 next-hop 1.1.1.1 community 19551:1;
route 45.60.100.0/24 path-information 198.143.46.211 next-hop 1.1.1.2 community 19551:1;
}
}


Logs:

May 14 09:20:44 searr1 exabgp[25469]: wire          Attempting connection to 198.143.46.209
May 14 09:20:46 searr1 exabgp[25469]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  SENDING  (132) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0035 0104 4C5F 00B4 C68F 2ED3 1802 0601 0400 0100 0102 0645 0400 0101 0302 0641 0400 004C 5F
May 14 09:20:46 searr1 exabgp[25469]: message       Peer  198.143.46.209 ASN 19551   >> OPEN version=4 asn=19551 hold_time=180 router_id=198.143.46.211 capabilities=[Multiprotocol(ipv4 unicast), ASN4(19551), AddPath(send/receive ipv4 unicast)]
May 14 09:20:46 searr1 exabgp[25469]: timers        peer 198.143.46.209 ASN 19551   Receive Timer 59 second(s) left
May 14 09:20:47 searr1 exabgp[25469]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  RECEIVED  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 003B 01
May 14 09:20:47 searr1 exabgp[25469]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  RECEIVED  (99) 044C 5F00 5A6B 9A0E F21E 0206 0104 0001 0001 0202 8000 0202 0200 0204 4002 0078 0206 4104 0000 4C5F
May 14 09:20:47 searr1 exabgp[25469]: message       Peer  198.143.46.209 ASN 19551   << OPEN
May 14 09:20:47 searr1 exabgp[25469]: message       Peer  198.143.46.209 ASN 19551   << OPEN version=4 asn=19551 hold_time=90 router_id=107.154.14.242 capabilities=[Multiprotocol(ipv4 unicast), Route Refresh, Graceful Restart Flags 0x0 Time 120 , ASN4(19551), Route Refresh]
May 14 09:20:47 searr1 exabgp[25469]: timers        peer 198.143.46.209 ASN 19551   Receive Timer 59 second(s) left
May 14 09:20:47 searr1 exabgp[25469]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  SENDING  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
May 14 09:20:47 searr1 exabgp[25469]: message       Peer  198.143.46.209 ASN 19551   >> KEEPALIVE (OPENCONFIRM)
May 14 09:20:47 searr1 exabgp[25469]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  RECEIVED  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
May 14 09:20:47 searr1 exabgp[25469]: message       Peer  198.143.46.209 ASN 19551   << KEEPALIVE
May 14 09:20:47 searr1 exabgp[25469]: timers        peer 198.143.46.209 ASN 19551   Receive Timer 89 second(s) left
May 14 09:20:47 searr1 exabgp[25469]: network       Connected to peer neighbor 198.143.46.209 local-ip 198.143.46.211 local-as 19551 peer-as 19551 router-id 198.143.46.211 family-allowed in-open (out)
May 14 09:20:47 searr1 exabgp[25469]: timers        peer 198.143.46.209 ASN 19551   Receive Timer 89 second(s) left
May 14 09:20:47 searr1 exabgp[25469]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  SENDING  (137) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0037 0200 0000 1C40 0101 0040 0200 4003 0401 0101 0240 0504 0000 0064 C008 044C 5F00 0118 2D3C 64
May 14 09:20:47 searr1 exabgp[25469]: message       Peer  198.143.46.209 ASN 19551   >> 1 UPDATE(s)
May 14 09:20:48 searr1 exabgp[25469]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  RECEIVED  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
May 14 09:20:48 searr1 exabgp[25469]: message       Peer  198.143.46.209 ASN 19551   << KEEPALIVE
May 14 09:20:48 searr1 exabgp[25469]: timers        peer 198.143.46.209 ASN 19551   Receive Timer 89 second(s) left
May 14 09:20:48 searr1 exabgp[25469]: timers        peer 198.143.46.209 ASN 19551   Send Timer 29 second(s) left
May 14 09:20:48 searr1 exabgp[25469]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  SENDING  (57) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0017 0200 0000 00
May 14 09:20:48 searr1 exabgp[25469]: message       Peer  198.143.46.209 ASN 19551   >> EOR ipv4 unicast
May 14 09:20:48 searr1 exabgp[25469]: message       peer 198.143.46.209 ASN 19551   >> EOR(s)


In my router (Juniper) I'm seeng just one range:

mx> show route receive-protocol bgp 198.143.46.211 hidden

inet.0: 219291 destinations, 441921 routes (219290 active, 0 holddown, 3 hidden)
  Prefix		  Nexthop	       MED     Lclpref    AS path
  45.60.100.0/24          1.1.1.2                      100        I

inet6.0: 37474 destinations, 107109 routes (37338 active, 0 holddown, 139 hidden)


Ho can I configure that ExaBGP will send network 45.60.100.0/24 with different next hop...

Appreciate your help

**Comment by thomas-mangin** [comment]
This is not the same question. This is a closed ticket. Please open a new issue. 
Also this is not a bug/issue with ExaBGP - please read more about add-path and check support for your Juniper router.

**Comment by yevgeniyo** [comment]
no, I just wanted to understand that my exabgp configuration is correct.... is it?
