### ISSUE TITLE
qa: api-broken-flow test seems inconsistent

### ISSUE THREAD

**Issue by tmmorin** [Exa-Networks/exabgp#621]
I've tried to see why api-broken-flow and api-flow tests do not work, and I'm facing the following questions:
- in api-broken-flow.run: announce_flow_1 and announce_broken_1 are actually identical
- in .run: I don't understand the exact intent behind the "to catch if a withdraw 2 is sent" comment
- in .sequence: the last raw line does not seem to match its description (same desc as first raw flow, but different description), is it supposed to be the withdraw ? if yes, then the encoding seems wrong (type of MPUNREACH_NLRI attribute is not 0F like in a withdraw)
- in .sequence: each line only is here once, but in the .run some actions (e.g. announce_flow_1) are there many times

Comments ?

**Comment by thomas-mangin** [comment]
fixed all tests - took quite some work.
