### ISSUE TITLE
Changes to SPEC for git build-rpm

### ISSUE THREAD

**Issue by leleobhz** [Exa-Networks/exabgp#626]
Hello!

At master, git build-rpm does not work w/o the following modifications:

```
diff --git a/redhat/python-exabgp.spec b/redhat/python-exabgp.spec
index ef7deb9..83c816d 100644
--- a/redhat/python-exabgp.spec
+++ b/redhat/python-exabgp.spec
@@ -42,10 +42,11 @@ Find what other users have done with it. Current documented use cases include DD
 %{__python2} setup.py install -O1 --root ${RPM_BUILD_ROOT}
 
 # fix file locations
+install bin/healthcheck ${RPM_BUILD_ROOT}%{_bindir}
 mv ${RPM_BUILD_ROOT}%{_bindir} ${RPM_BUILD_ROOT}%{_sbindir}
 mv ${RPM_BUILD_ROOT}%{_sbindir}/healthcheck ${RPM_BUILD_ROOT}/%{_sbindir}/exabgp-healthcheck
 install -d -m 744 ${RPM_BUILD_ROOT}/%{_sysconfdir}/
-mv ${RPM_BUILD_ROOT}/usr/etc/exabgp ${RPM_BUILD_ROOT}/%{_sysconfdir}/
+mv ${RPM_BUILD_ROOT}/usr/share/exabgp/etc ${RPM_BUILD_ROOT}/%{_sysconfdir}/exabgp
 
 install -d %{buildroot}/%{_unitdir}
 install etc/systemd/exabgp.service %{buildroot}/%{_unitdir}/
@@ -76,6 +77,7 @@ install doc/man/exabgp.conf.5 %{buildroot}/%{_mandir}/man5
 %attr(755, root, root) %{_sbindir}/exabgp
 %attr(755, root, root) %{_sbindir}/exabgp-healthcheck
 %dir %{_sysconfdir}/exabgp
+%attr(744, root, root) %{_prefix}/share/exabgp/*
 %attr(744, root, root) %{_sysconfdir}/exabgp/*
 %{_unitdir}/exabgp.service
 %doc COPYRIGHT CHANGELOG README.md
```

Its possible to create a spec for master to be used with https://github.com/iovation/git-build-rpm/ ?

Thanks!

**Comment by thomas-mangin** [comment]
Happy to accept a PR for SRPM and have it in the repo.

**Comment by thomas-mangin** [comment]
Does the other spec file still need fixing ?

**Comment by lukehinds** [comment]
I made some comments over on the patch...do you plan to maintain the SPEC going forward @leleobhz ?

**Comment by leleobhz** [comment]
@lukehinds I've sent a new PR ( https://github.com/Exa-Networks/exabgp/pull/629 )  fixing what you asked for. If you like, more "agressive" approachs to RPM packing can be used, like https://github.com/dgoodwin/tito

Also, i did this .spec.git with git build-rpm. This spec, alone, violates rpmbuild, but git build-rpm will complete the needed informations.

I can mantain it if I receive issues about it someway. I'm using exabgp in production stage at CentOS/Fedora servers at the company i work on, so I can test and deploy it if needed.

**Comment by thomas-mangin** [comment]
I have commented on the PR.

**Comment by lukehinds** [comment]
hi @leleobhz sounds good to me. I plan to submit the SPEC to Fedora, so I will feedback findings here and replicate those upstream. Sounds good?

**Comment by leleobhz** [comment]
Hello!

AFAIK, a SPEC to Fedora Upstream will require a tar.gz, so I suggest keep 2 .specs - one in a acceptable format for FC/RHEL Upstream versions with lattest stable exabgp and other to build rpms from git HEAD (Helping bleeding edge users do not suffer too much).

I know more about Debian/ubuntu packaging than Fedora - but I'll attempt to create a good spec soon.

**Comment by lukehinds** [comment]
@leleobhz , that's ok for me. It will be a copy of your spec rather then a direct line / reference, so I can maintain the variations in Fedora.

**Comment by thomas-mangin** [comment]
@lukehinds how can I make sure than any change you do match ? As if we can't I would rather not have the file duplicated.

**Comment by leleobhz** [comment]
@lukehinds I'll find ways to make this spec a bit more portable.
