### ISSUE TITLE
BGP poisoning announcement with as-set

### ISSUE THREAD

**Issue by jaepark** [Exa-Networks/exabgp#628]
##### OS

Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-112-generic x86_64)

##### VERSION

```
ExaBGP : 3.4.18
Python : 2.7.6 (default, Oct 26 2016, 20:30:19)  [GCC 4.8.4]
```

##### ENVIRONMENT 

```

```

##### SUMMARY

Hi, I would like to get some help using exaBGP to announce BGP poisoning announcements with as-sets.
```
group test {
    neighbor 100.69.128.1 {
        local-as 47065;
	peer-as 47065;

        static {
            route 184.164.224.0/24 {
                next-hop 100.71.128.1;
                as-path [ 1103 47065 ];
            }
        }
    }
}
```
For instance, in the configuration file, exaBGP successfully announces AS path "47065 1103 47065" for the prefix 184.164.224.0/24.

My goal is to announce AS path "47065 {ASN1, ASN2} 47065" for the prefix in exaBGP, where {ASN1, ASN2} are AS-sets. How would I be able to achieve this goal?

Any help will be greatly appreciated.
Thanks.

**Comment by thomas-mangin** [comment]
I do not know why you qualified your question as "Bug Report" ...
Please could you reword and clarify your question, I do not understand what you are trying to achieve.

**Comment by jaepark** [comment]
Hi, this is just a question, not a bug report (sorry about that). I reworded the question. Hope this clarifies my question. Thanks for taking a look!

**Comment by thomas-mangin** [comment]
In master the configuration format is:
`as-path [ <as-sequence-asn> | ( <as-set > ) ];` 

In think it is the same in 3.4

**Comment by thomas-mangin** [comment]
something like:
`as-path [ 1103 47065  ( 1103 47065 ) ];`
or:
`as-path [ ( 1103 47065 ) ];`

**Comment by thomas-mangin** [comment]
Feel free to re-open
