### ISSUE TITLE
Add path configuration question

### ISSUE THREAD

**Issue by yevgeniyo** [Exa-Networks/exabgp#633]
Add path configuration question

##### ISSUE TYPE

- question

##### VERSION

```
3.4.18
```

##### ENVIRONMENT 

```

```

##### SUMMARY

I have question about add-path configuration, my ExaBGP configuration is:

neighbor 198.143.46.209 {
router-id 198.143.46.211;
local-address 198.143.46.211;
local-as 551;
peer-as 551;
group-updates false;

capability {
add-path send/receive;
}

family {
ipv4 unicast;
}

static {
route 45.60.100.0/24 path-information 198.143.46.211 next-hop 1.1.1.1 community 551:1;
route 45.60.100.0/24 path-information 198.143.46.211 next-hop 1.1.1.2 community 551:1;
}
}

On the side of router add-path configured as well, could you please tell me that my configuration of ExaBGP is correct? In practice I'm seeing just last announced route with next ho 1.1.1.2

Logs are:

May 14 11:16:09 searr1 exabgp[4002]: network       out loop, intialising
May 14 11:16:10 searr1 exabgp[4002]: wire          Attempting connection to 198.143.46.209
May 14 11:16:12 searr1 exabgp[4002]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  SENDING  (132) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0035 0104 4C5F 00B4 C68F 2ED3 1802 0601 0400 0100 0102 0645 0400 0101 0302 0641 0400 004C 5F
May 14 11:16:12 searr1 exabgp[4002]: message       Peer  198.143.46.209 ASN 551   >> OPEN version=4 asn=551 hold_time=180 router_id=198.143.46.211 capabilities=[Multiprotocol(ipv4 unicast), ASN4(551), AddPath(send/receive ipv4 unicast)]
May 14 11:16:12 searr1 exabgp[4002]: timers        peer 198.143.46.209 ASN 551   Receive Timer 59 second(s) left
May 14 11:16:13 searr1 exabgp[4002]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  RECEIVED  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 003B 01
May 14 11:16:13 searr1 exabgp[4002]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  RECEIVED  (99) 044C 5F00 5A6B 9A0E F21E 0206 0104 0001 0001 0202 8000 0202 0200 0204 4002 0078 0206 4104 0000 4C5F
May 14 11:16:13 searr1 exabgp[4002]: message       Peer  198.143.46.209 ASN 551   << OPEN
May 14 11:16:13 searr1 exabgp[4002]: message       Peer  198.143.46.209 ASN 551   << OPEN version=4 asn=551 hold_time=90 router_id=107.154.14.242 capabilities=[Multiprotocol(ipv4 unicast), Route Refresh, Graceful Restart Flags 0x0 Time 120 , ASN4(551), Route Refresh]
May 14 11:16:13 searr1 exabgp[4002]: timers        peer 198.143.46.209 ASN 551   Receive Timer 59 second(s) left
May 14 11:16:13 searr1 exabgp[4002]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  SENDING  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
May 14 11:16:13 searr1 exabgp[4002]: message       Peer  198.143.46.209 ASN 551   >> KEEPALIVE (OPENCONFIRM)
May 14 11:16:13 searr1 exabgp[4002]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  RECEIVED  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
May 14 11:16:13 searr1 exabgp[4002]: message       Peer  198.143.46.209 ASN 551   << KEEPALIVE
May 14 11:16:13 searr1 exabgp[4002]: timers        peer 198.143.46.209 ASN 551   Receive Timer 89 second(s) left
May 14 11:16:13 searr1 exabgp[4002]: network       Connected to peer neighbor 198.143.46.209 local-ip 198.143.46.211 local-as 551 peer-as 551 router-id 198.143.46.211 family-allowed in-open (out)
May 14 11:16:13 searr1 exabgp[4002]: timers        peer 198.143.46.209 ASN 551   Receive Timer 89 second(s) left
May 14 11:16:13 searr1 exabgp[4002]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  SENDING  (137) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0037 0200 0000 1C40 0101 0040 0200 4003 0401 0101 0240 0504 0000 0064 C008 044C 5F00 0118 2D3C 64
May 14 11:16:13 searr1 exabgp[4002]: message       Peer  198.143.46.209 ASN 551   >> 1 UPDATE(s)
May 14 11:16:14 searr1 exabgp[4002]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  RECEIVED  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
May 14 11:16:14 searr1 exabgp[4002]: message       Peer  198.143.46.209 ASN 551   << KEEPALIVE
May 14 11:16:14 searr1 exabgp[4002]: timers        peer 198.143.46.209 ASN 551   Receive Timer 89 second(s) left
May 14 11:16:14 searr1 exabgp[4002]: timers        peer 198.143.46.209 ASN 551   Send Timer 29 second(s) left
May 14 11:16:14 searr1 exabgp[4002]: wire          session 1 outgoing 198.143.46.211 / 198.143.46.209  SENDING  (57) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0017 0200 0000 00
May 14 11:16:14 searr1 exabgp[4002]: message       Peer  198.143.46.209 ASN 551   >> EOR ipv4 unicast
May 14 11:16:14 searr1 exabgp[4002]: message       peer 198.143.46.209 ASN 551   >> EOR(s)

Router Configuration:

show configuration | match rr.1 | display set
set protocols bgp group rr.1 type internal
set protocols bgp group rr.1 import from-rr
set protocols bgp group rr.1 family inet unicast add-path receive
set protocols bgp group rr.1 export to-rr
set protocols bgp group rr.1 peer-as 551
set protocols bgp group rr.1 graceful-restart
set protocols bgp group rr.1 multipath
set protocols bgp group rr.1 neighbor 198.143.46.211

##### ACTUAL RESULTS

show route receive-protocol bgp 198.143.46.211 hidden

inet.0: 219297 destinations, 441931 routes (219296 active, 0 holddown, 4 hidden)
  Prefix		  Nexthop	       MED     Lclpref    AS path
  45.60.100.0/24          1.1.1.2                      100        I

**Comment by thomas-mangin** [comment]
From the open messages we are well indicating that we support add-path:
sending: ```capabilities=[Multiprotocol(ipv4 unicast), ASN4(551), AddPath(send/receive ipv4 unicast)]``
however the Juniper tells us that it is not configured for it / or can not do it
receiving: ```capabilities=[Multiprotocol(ipv4 unicast), Route Refresh, Graceful Restart Flags 0x0 Time 120 , ASN4(551), Route Refresh]```

So please check that your router both support add-path and that your configuration is correct for JunOS.

Your question is not about ExaBGP but about BGP. I will invite you to read on the net and make sure you understand how BGP works (inc capacity negotiation). If you can not see `AddPath(receive ipv4 unicast)` and the OPEN message we receive (second one starting with ```<<```) There is nothing I can do.

Sincerely. Thomas.

**Comment by yevgeniyo** [comment]
Thank you Thomas, I'have understood my issue, "path-information 198.143.46.211" was the same for both entries
