### ISSUE TITLE
Flow-parsing error raises uncaught exception

### ISSUE THREAD

**Issue by stoffi92** [Exa-Networks/exabgp#635]
##### ISSUE TYPE

 - Bug Report

##### OS

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

##### VERSION

```
ExaBGP version : 4.0.0
Python version : 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
System Uname   : #1 SMP Wed Apr 12 15:04:24 UTC 2017
System MaxInt  : 9223372036854775807

```

##### ENVIRONMENT 

```

[exabgp.daemon]
pid = '/var/run/exabgp/exabgp.pid'
user = '_bgpd'

[exabgp.log]
all = true
daemon = false
destination = '/var/log/exabgp/exabgp.log'
message = true
parser = true

```

##### SUMMARY

Head cloned from today crashes when receiving a flow route from the API. Since the API may have changed from 3.x to head (PRE-4.x) the input received via the stdin may be invalid, however crashing exabgp on receiving invalid input from stdin is still a bug.

##### STEPS TO REPRODUCE

Run exabgp (latest greatest) and input the flow-string showed in the debug output via the API.

##### EXPECTED RESULTS

The daemon either accepting the route, or complaining about faulty input via the API. But *not* crashing.

##### ACTUAL RESULTS

ExaBGP crashes with traceback below. A side-effect from this is, that the spawned process is not terminated. 

-- Traceback

Traceback (most recent call last):
  File "/bin/exabgp", line 9, in <module>
    load_entry_point('exabgp==4.0.0', 'console_scripts', 'exabgp')()
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/application/__init__.py", line 12, in run_exabgp
    main()
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/application/bgp.py", line 246, in main
    run(env,comment,configurations)
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/application/bgp.py", line 281, in run
    ok = Reactor(configurations).run()
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/reactor/loop.py", line 274, in run
    scheduled = self.schedule()
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/reactor/loop.py", line 406, in schedule
    six.next(self._running)  # run
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/reactor/api/command/text.py", line 559, in callback
    changes = self.parser.api_flow(command)
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/reactor/api/parser/text.py", line 91, in api_flow
    if not self.configuration.partial('flow',line):
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/configuration.py", line 414, in partial
    if self.section(section) is not True:
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/configuration.py", line 491, in section
    and self.dispatch(name) \
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/configuration.py", line 468, in dispatch
    if self._enter(name):
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/configuration.py", line 438, in _enter
    if not self.section(self._structure[name]['sections'][location]):
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/configuration.py", line 491, in section
    and self.dispatch(name) \
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/configuration.py", line 468, in dispatch
    if self._enter(name):
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/configuration.py", line 438, in _enter
    if not self.section(self._structure[name]['sections'][location]):
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/configuration.py", line 491, in section
    and self.dispatch(name) \
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/configuration.py", line 463, in dispatch
    if self._run(name):
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/configuration.py", line 454, in _run
    if not self.run(name,command):
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/configuration.py", line 498, in run
    return self._structure[name]['class'].parse(name,command)
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/core/section.py", line 81, in parse
    for adding in insert:
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/flow/parser.py", line 174, in source_port
    for _ in _generic_condition(tokeniser,FlowSourcePort):
  File "/usr/lib/python2.7/site-packages/exabgp-4.0.0-py2.7.egg/exabgp/configuration/flow/parser.py", line 164, in _generic_condition
    raise ValueError("Invalid flow route data" % data)
TypeError: not all arguments converted during string formatting

-- Configuration

-- Logging History

Mon, 15 May 2017 20:15:53 26111  processes     Forked process fs_automitigation
Mon, 15 May 2017 20:15:53 26111  daemon        Created PIDfile /var/run/exabgp/exabgp.pid with value 26111
Mon, 15 May 2017 20:15:53 26111  network       out loop, intialising
Mon, 15 May 2017 20:15:54 26111  wire          attempting connection to 10.0.0.2:179
Mon, 15 May 2017 20:15:58 26111  network       Peer        10.0.0.2 ASN 1764    connection to 10.0.0.2:179 failed
Mon, 15 May 2017 20:15:58 26111  wire          session 1 outgoing, closing connection from <HIDDEN> to 10.0.0.2
Mon, 15 May 2017 20:15:58 26111  network       out loop, intialising
Mon, 15 May 2017 20:15:58 26111  processes     Command from process fs_automitigation : announce flow route {\nmatch {\ndestination 10.120.120.128/25;\nprotocol =6 =17;\ndestination-port =10 =30;\nsource-port >=10&<=19;\n}\nthen {\nrate-limit 62500000;\n}\n}\n\n 
Mon, 15 May 2017 20:15:58 26111  reactor       callback | handling 'announce flow route {\nmatch {\ndestination 10.120.120.128/25;\nprotocol =6 =17;\ndestination-port =10 =30;\nsource-port >=10&<=19;\n}\nthen {\nrate-limit 62500000;\n}\n}\n\n' with announce_flow
Mon, 15 May 2017 20:15:58 26111  processes     Command from process fs_automitigation : announce flow route {\nmatch {\ndestination <HIDDEN>/32;\nprotocol =6 =17;\ndestination-port =10 =30;\nsource-port >=10&<=19;\n}\nthen {\nrate-limit 62500000;\n}\n}\n\n 
Mon, 15 May 2017 20:15:58 26111  reactor       callback | handling 'announce flow route {\nmatch {\ndestination <HIDDEN>/32;\nprotocol =6 =17;\ndestination-port =10 =30;\nsource-port >=10&<=19;\n}\nthen {\nrate-limit 62500000;\n}\n}\n\n' with announce_flow
Mon, 15 May 2017 20:15:58 26111  processes     Command from process fs_automitigation : announce flow route {\nmatch {\nsource 192.168.0.1/32;\ndestination 10.120.120.129/32;\nprotocol >=1&<=5 =19;\ndestination-port >=10&<=20 =90;\nsource-port >=1&<=10 =80;\nicmp-type >=1&<=4 >=10&<=20;\nicmp-code >=1&<=5 =10 >=20&<=30;\ntcp-flags =3;\npacket-length >=20&<=39 =576 >=1501&<=65535;\ndscp =23 =24 =26 =30;\n}\nthen {\nrate-limit 3706250;\n}\n}\n\n 
Mon, 15 May 2017 20:15:58 26111  reactor       callback | handling 'announce flow route {\nmatch {\nsource 192.168.0.1/32;\ndestination 10.120.120.129/32;\nprotocol >=1&<=5 =19;\ndestination-port >=10&<=20 =90;\nsource-port >=1&<=10 =80;\nicmp-type >=1&<=4 >=10&<=20;\nicmp-code >=1&<=5 =10 >=20&<=30;\ntcp-flags =3;\npacket-length >=20&<=39 =576 >=1501&<=65535;\ndscp =23 =24 =26 =30;\n}\nthen {\nrate-limit 3706250;\n}\n}\n\n' with announce_flow
Mon, 15 May 2017 20:15:58 26111  reactor       callback | installing announce_flow
Mon, 15 May 2017 20:15:58 26111  reactor       callback | running
Mon, 15 May 2017 20:15:58 26111  configuration > route            | 
Mon, 15 May 2017 20:15:58 26111  configuration > match            | 
Mon, 15 May 2017 20:15:58 26111  configuration . destination      | '10.120.120.128/25'
Mon, 15 May 2017 20:15:58 26111  configuration . protocol         | '=6' '=17'
Mon, 15 May 2017 20:15:58 26111  configuration . destination-port | '=10' '=30'
Mon, 15 May 2017 20:15:58 26111  configuration . source-port      | '>=10&<=19'

##### IMPORTANCE

Only testing. But may crash production environments sooner than later.

**Comment by stoffi92** [comment]
This may be related (but easier to reproduce):

A flow configuration like this gets loaded successful:

```     
    flow {
         route {
            match {
               source-port [>=10&<=19];
            }
            then {
               redirect 30740:12345;
            }
         }
      }
```
While such a config (below) leads to an error (which may be perfectly ok - since I did not read how the new 4.0.0 configuration is supposed to look like). However when a invalid config is received via the API a traceback+crash is not really the desired behaviour:

```
      flow {
         route {
            match {
               source-port >=10&<=19;
            }
            then {
               redirect 30740:12345;
            }
         }
      }
```

Btw: `source-port =90 >=10&<=19;` (without brackets works fine again. :-)

**Comment by thomas-mangin** [comment]
Thank you - should now work as expected .. silly mistake when the code was rewritten (was applying to all flow components)

**Comment by thomas-mangin** [comment]
Now sure how the code can work with `source-port =90 >=10&<=19;` it should fails and when I tried it did fail. Did you use the API or config ?

**Comment by stoffi92** [comment]
`source-port =90 >=10&<=19;` <- you are right this is not meaningful. the 4.x head that I just cloned does not complain when you put something like this into the config file (however I do not know what the actual result is). 

Regarding the issue with the daemon crashing on an invalid API command, this has been resolved. Thanks.

**Comment by thomas-mangin** [comment]
`source-port =90 >=10&<=19;` means source port is 90 or source port is in the range 10-19

**Comment by stoffi92** [comment]
This is what I meant - sorry to be unclear - I think the issue itself has been resolved and you may close this.
