### ISSUE TITLE
Allow (numeric-)ranges for ICMP-type/code

### ISSUE THREAD

**Issue by stoffi92** [Exa-Networks/exabgp#636]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Only for 4.xx! (because configuration parsing seems to be more complex in 3.x, and more changes are required to achive the same):

As discussed previously flow-spec encoding for icmp-type/code is pretty much the same as IP-protocol. This way of encoding allows to go for ranges of icmp-type/code (like already implemented for IP-protocol in exabgp 4.x - no reason to restrict icmp-type/code to only a selection of _named_ codes/types).

Configurations like this should be perfectly acceptable:

```
icmp-type [ >=1&<=4 >=10&<=20 ] ;
or
icmp-type [ >echo-reply&<echo-request >=10&<=20 ] ;
or 
icmp-type [ >echo-reply&<5 >=10&<=20 ] ;
```

For me this seems to do what I currently need (in 4.x):

```
--- a/lib/exabgp/bgp/message/update/nlri/flow.py
+++ b/lib/exabgp/bgp/message/update/nlri/flow.py
@@ -403,14 +403,14 @@ class FlowSourcePort (IOperationByteShort,NumericString,IPv4,IPv6):
 class FlowICMPType (IOperationByte,NumericString,IPv4,IPv6):
        ID = 0x07
        NAME = 'icmp-type'
-       converter = staticmethod(converter(ICMPType.named))
+       converter = staticmethod(converter(ICMPType.named,ICMPType))
        decoder = staticmethod(decoder(_number,ICMPType))
 
 
 class FlowICMPCode (IOperationByte,NumericString,IPv4,IPv6):
        ID = 0x08
        NAME = 'icmp-code'
-       converter = staticmethod(converter(ICMPCode.named))
+       converter = staticmethod(converter(ICMPCode.named,ICMPCode))
        decoder = staticmethod(decoder(_number,ICMPCode))
``` 

##### IMPORTANCE

low - testing

**Comment by thomas-mangin** [comment]
It works on master BUT only if the value you used are mapped to value ICMP codes ..
```
Tue, 16 May 2017 14:42:42 | INFO     | 83745  | configuration | . icmp-type        | '[' '>=0&<=4' '>=10&<=30' ']'
Tue, 16 May 2017 14:42:42 | INFO     | 83745  | configuration | . icmp-type        | '[' '>echo-reply&<echo-request' '>=10&<=30' ']'
Tue, 16 May 2017 14:42:42 | INFO     | 83745  | configuration | . icmp-type        | '[' '>echo-reply&<5' '>=10&<=30' ']'
```
Using a value like 20 for example will cause an issue.

**Comment by stoffi92** [comment]
Correct (if the above comment was a question). With the patch I provided above it also works for all values on master.

**Comment by thomas-mangin** [comment]
To explain what the code as it is now (not taking a position on possible change). 

Using range on what are effectively enums (code), is practical (and surely more effective than listing all values) but does it make sense to allow the test to have arbitrary values ??

**Comment by stoffi92** [comment]
I see no reason why exabgp (or any other BGP implementation) should waste time on semantics of the flowspec (or most of the other bits and pieces, flags, attributes, communities, ...). This is something the user should take care of. (I think you really do not want to put any semantics into this, then we may start arguing if a flow containing icmp-codes and tcp-flags at the same time will make sense since such a flow will never match any packet).

However, in our case we are actually doing something meaningfull and intercepting flow-routes between Juniper and Arbor. Both implementations do not put any restrictions what so ever on the types that support this "numeric-string" operator (ports, protocol, icmp-type, icmp-code, length). So, when we receive such a configuration from Arbor or Juniper (ie. icmp-type 1-100) we end up iterating thru 1,2,3,4,5, ... 100 (and even this configuration is not supported since only "names" are currently allowed).

Example (from Juniper config):
```
{master}[edit routing-options flow route BLA]
cl@R06.FLE.xxx# show    
match {
    protocol 1-10;
    icmp-type 20-30;
    icmp-code [ 1-5 20-30 ];
}
```

**Comment by stoffi92** [comment]
btw: I very much appreciate what you are doing here, and I am really *not* doing this to keep you busy all day. (Even if today this seemed a little like this).

**Comment by thomas-mangin** [comment]
Ok - if other vendors do it, it makes sense to match the behaviour as we are going to see flows that way in the wild. Added support for named port .. as I was at it and it made sense to just add this "as I was at it".

**Comment by stoffi92** [comment]
While reading over that patch... do you think that there is something that needs changing also the decoder for ip-protocol or for icmp-type/code?

```
class FlowIPProtocol (IOperationByte,NumericString,IPv4):
	ID  = 0x03
	NAME = 'protocol'
	converter = staticmethod(converter(Protocol.named,Protocol))
	decoder = staticmethod(decoder(ord,Protocol))


class FlowNextHeader (IOperationByte,NumericString,IPv6):
	ID  = 0x03
	NAME = 'next-header'
	converter = staticmethod(converter(Protocol.named,Protocol))
	decoder = staticmethod(decoder(ord,Protocol))
```
while the icmp-types/codes decoder look like this (sorry this is only pattern matching on my side - no real deep programatical understanding): `decoder = staticmethod(decoder(_number,ICMPType))`

**Comment by stoffi92** [comment]
I was just reasoning and doing "stupid" pattern matching... on the decoder lines of FlowIPProtocol FlowNextHeader and FlowICMPType FlowICMPCode:

decoder = staticmethod(decoder(ord,Protocol)) <- Protocol
decoder = staticmethod(decoder(ord,Protocol)) <- NextHeader
decoder = staticmethod(decoder(_number,ICMPType)) <- ICMPType
decoder = staticmethod(decoder(_number,ICMPCode)) <- ICMPCode

This is why I thought (again without actually 100% understanding what is going on there) that maybe the Protocol decoder lines should look like:

decoder = staticmethod(decoder(_number,Protocol))

But again - this is a guess without understanding what is going on in the code.

**Comment by stoffi92** [comment]
And this is the last thing that I wrote for the next weeks - I promise. :-) Thanks for all the help.
