### ISSUE TITLE
Update the prefix-sid patch

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#640]
The following command:
```
route 198.51.100.101/32 next-hop 198.51.100.2 label [ 800002 ] bgp-prefix-sid [ 300, [ ( 800000,4096 ), ( 1000000,5000 ) ] ];
```
is decoded as:
```
route 198.51.100.101/32 next-hop 198.51.100.2 label [ 800002 ] bgp-prefix-sid sr-label-index 300, sr-srgbs [(1000000, 5000), (800000, 4096)]
which in turn can not be re-parsed by ExaBGP. The format must be bi-directional. Could you please change this ?
```
which result in the following JSON output:
```
{ "exabgp": "4.0.0", "time": 1495359723.9699042, "host" : "ptr-41.212.219.82.rev.exa.net.uk", "pid" : 19802, "ppid" : 13720, "counter": 1, "type": "update", "neighbor": { "address": { "local": "127.0.0.1", "peer": "127.0.0.1" }, "asn": { "local": "65000", "peer": "65000" }, "direction": "in", "message": { "update": { "attribute": { "origin": "igp", "local-preference": 100, "bgp-prefix-sid": { "sr-label-index": "300", "sr-srgbs": "[(1000000, 5000), (800000, 4096)]" } }, "announce": { "ipv4 nlri-mpls": { "198.51.100.2": [ { "nlri": "198.51.100.101/32", "label": [ 800002 ] } ] } } } } } }
```

which prefix part is:
```
"bgp-prefix-sid": { 
   "sr-label-index": "300", 
   "sr-srgbs": "[(1000000, 5000), (800000, 4096)]"
}
```

sr-label-index is a number, not a string (easy fix), however sr-srgbs is an opaque string. 

The JSON should be fully parsed to not required any hard work from clients.

I would really appreciate if you could update the code. I will then release 4.0.1.

**Comment by thomas-mangin** [comment]
@ruissalo I created this is issue as a follow up to your PR.

**Comment by ruissalo** [comment]
Hi, @thomas-mangin I'll fix it this week. Thanks for reviewing the patch.

**Comment by thomas-mangin** [comment]
hello @ruissalo - I am sure you are very busy - just a quick poke to try to understand if you will be able to spend some time of this fix soon or if live is taking over :-p

**Comment by ruissalo** [comment]
Hi @thomas-mangin I'll do my best to care of this in the next few days, I haven't forgotten ;)

**Comment by thomas-mangin** [comment]
to not have to dig it everytime - initial patch #638

**Comment by ruissalo** [comment]
@thomas-mangin just to let you know that I'm currently working on this fix, will push probably tomorrow evening or on Saturday.
