### ISSUE TITLE
Can't setup IPv6 peering between ExaBGP and Quagga

### ISSUE THREAD

**Issue by githubpol** [Exa-Networks/exabgp#643]
##### ISSUE TYPE
 - Bug Report

##### OS
FreeBSD 10.3-RELEASE-p19

##### VERSION
exabgp --version doesn't output anything at all, but the exabgp version is 3.4.18, installed with "pkg install exabgp"

##### ENVIRONMENT 
exabgp --di also outputs nothing

##### CONFIGURATION
Quagga:
router bgp x
  neighbor y.y.y.y remote-as y
  neighbor y:y:y:y::y remote-as y
  no neighbor y:y:y:y::y activate
  address-family ipv6
  neighbor y:y:y:y::y activate

ExaBGP:
(I have tried several different variations, but this is the one that seems most logical to me.)
group IPv4 {
  neighbor x.x.x.x {
    router-id y.y.y.y;
    local-as y;
    peer-as x;
    family {
      ipv4 unicast;
    }
    static {
      route z.z.z.0/24 next-hop y.y.y.y;
    }
  }
}
group IPv6 {
  neighbor x:x:x::x {
    router-id y:y:y:y::y;
    local-as y;
    peer-as x;
    family {
      ipv6 unicast;
    }
    static {
      route z:z:z::/48 next-hop y:y:y:y::y;
    }
  }
}

##### SUMMARY
The IPv4 peering works fine, and the IPv4 route is announced from ExaBGP to Quagga.
But the IPv6 peering never comes up.

##### IMPORTANCE
Medium. (This is not a critical issue at the moment, but if there doesn't seem to be a solution I will have to change from ExaBGP to Quagga, which would be unnecessary as I don't need to receive routes, I just need to announce one IPv4 route and one IPv6 route.)

Thanks!

**Comment by brijohn** [comment]
Looking at your configuration it seems you are using an ipv6 address for the router id. This is actually an invalid configuration since in BGP the router-id is a 32 bit number. 

Try setting it to the same ip address used for your v4 peer and see if that works any better for you.

**Comment by githubpol** [comment]
Thanks! I had tried that before, but at that time I hadn't realized that I needed ebgp-multihop at the Quagga end. After your comment I tried changing router-id again, and now everything works fine in both IPv4 and IPv6. Thanks very much!

**Comment by thomas-mangin** [comment]
@brijohn Thank you very much for helping ! Much appreciated. I assume the error messages went to syslog ...

**Comment by akilnath** [comment]
Quagga
hostname SoftBGP
password zebra987
enable password zebra987
log file /var/log/quagga/bgpd.log

debug bgp events
debug bgp filters
debug bgp fsm
debug bgp keepalives
debug bgp updates

router bgp 65530
bgp router-id 172.16.0.18
bgp log-neighbor-changes

neighbor 172.16.0.26 remote-as 65501

ExaBGP
group Core_v4 {
    hold-time 180;
    local-as 65501;
    peer-as 65530;
    router-id 172.16.0.26;
    graceful-restart 1200;
    static {
        route 10.10.10.1/32 next-hop 172.16.0.26 community 65501:666;
    }
    neighbor 172.16.0.18 {
        local-address 172.16.0.26;
        description "Quagga";
    }
}

Run ExaBGP
**sudo env exabgp.daemon.user=root exabgp.daemon.daemonize=true exabgp.daemon.pid=/var/run/exabgp.pid exabgp.log.destination=/var/log/exabgp.log exabgp /etc/exabgp_blackhole.conf**

exabgp: 137982 configuration environment file missing
exabgp: 137982 configuration generate it using "exabgp --fi > /usr/etc/exabgp/exabgp.env"


Output ExaBGP
**sudo cat /var/log/exabgp.log**
exabgp: 137982 network       Peer     172.16.0.18 ASN 65530   out loop, peer reset, message [notification sent (1,1)] error[Message header error / Connection Not Synchronized / waited for open too long, we do not like stuck in active]
exabgp: 137982 network       Peer     172.16.0.18 ASN 65530   out loop, peer reset, message [closing connection] error[the TCP connection was closed by the remote end]
exabgp: 137982 network       Peer     172.16.0.18 ASN 65530   out loop, peer reset, message [notification sent (1,1)] error[Message header error / Connection Not Synchronized / waited for open too long, we do not like stuck in active]
exabgp: 137982 network       Peer     172.16.0.18 ASN 65530   out loop, peer reset, message [closing connection] error[the TCP connection was closed by the remote end]
exabgp: 137982 network       Peer     172.16.0.18 ASN 65530   out loop, peer reset, message [notification sent (1,1)] error[Message header error / Connection Not Synchronized / waited for open too long, we do not like stuck in active]
exabgp: 137982 network       Peer     172.16.0.18 ASN 65530   out loop, peer reset, message [closing connection] error[the TCP connection was closed by the remote end]
exabgp: 137982 network       Peer     172.16.0.18 ASN 65530   out loop, peer reset, message [closing connection] error[the TCP connection was closed by the remote end]

Run Quagga
**/etc/init.d/quagga restart**

Output Quagga
**sudo vtysh -d bgpd -c "show ip bgp summary"**
BGP router identifier 172.16.0.18, local AS number 65530
RIB entries 0, using 0 bytes of memory
Peers 1, using 4568 bytes of memory

Neighbor        V         AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
172.16.0.26     4 65501       8      16        0    0    0 never    Active     

Total number of neighbors 1
