### ISSUE TITLE
Large communities in 3.4.*

### ISSUE THREAD

**Issue by wydrych** [Exa-Networks/exabgp#645]
Hi,
Will large communities be backported to the 3.4 branch?

-Piotr

**Comment by thomas-mangin** [comment]
the patch by Job is nearly 100% right - I just had to do one to two fixes (in some of the follow up patches) so it should not be too hard but I would expect 4.0 to become the new stable very soon so I am not very motivated to backport the work when there is quite a few other things I need to fix first.

**Comment by thomas-mangin** [comment]
I decided that I was lazy (well everyone around me knew that - I am just admitting it publicly) therefore I will not backport the code. I will however accept and review a backport if someone does it.
