### ISSUE TITLE
When 4.0.0 is planned to be announced for production?

### ISSUE THREAD

**Issue by YuriyAr** [Exa-Networks/exabgp#647]
##### ISSUE TYPE

Documentation Report

##### SUMMARY

Hi Thomas, just a quick question.
Following a previous inquiry on issue 588, can you estimate the plans to announce 4.0.0 as stable for production deployments? I saw that py3 issues are fixed already...
Thanks, Yuriy.

**Comment by thomas-mangin** [comment]
Hello, even if I work directly in master (and you can see that I fix bug just introduced once in a while). I try to keep master workable. Many people use it in production it seems ... I would call them mad but for a long time I did not really gave them the choice ;p

I would expect to stabilise things quickly now. Before the next stable I would like to see #640 completed - a wink @ruissalo who provided us many good patches and features - #407 fixed and adding per family static route #625 .. perhaps #410 as it is not an hard one . but that's it.

**Comment by YuriyAr** [comment]
Thanks Thomas that's great!
Looking forward to this.

**Comment by thomas-mangin** [comment]
#625 is now done ... just a few to go ...

**Comment by YuriyAr** [comment]
Thanks Thomas you're great.

**Comment by thomas-mangin** [comment]
Hum ... compliments ... Do you want something ????? 🤣

**Comment by YuriyAr** [comment]
Funny :)
Just the version to be stable and released :)
We have a couple of customers waiting for a few features...

**Comment by thomas-mangin** [comment]
would you mind telling me off-github how you use exabgp please (I am just curious) ?

**Comment by YuriyAr** [comment]
Of course, with pleasure.
Adding you to LinkedIn. Let me know if you want to talk by other means.
Yuriy.

**Comment by thomas-mangin** [comment]
I just found out that one good code cleanup would require a little more work than required. So while 4.0.1 is still planned for very soon. stable 4.0 is going to take a little bit longer.

**Comment by YuriyAr** [comment]
Thanks for the update Thomas.
In the meanwhile we discovered that protocol numbers work in FlowSpec in exabgp 3.4, which is great for us.
However, range is not supported (e.g., cannot say protocols ">=16&<=18", need to say something like "=16 =17 =18").
Can you hint if this is supported in the upcoming 4.0?

**Comment by thomas-mangin** [comment]
@YuriyAr you should have opened a new issue to ask this question, it is not related to the release. Never tried it may work on master. If it does an not on 3.4 - no I will not backport - too much changed in the code base.

master now passes all it qa test .. there was quite some "hidden" breakage to fix. So next is to fix @ruissalo code and 4.0.1 is next.

**Comment by YuriyAr** [comment]
Ok thanks Thomas.

**Comment by nidotech** [comment]
btw, when will 4.0.1 be pushed to pypi?

**Comment by thomas-mangin** [comment]
Look at the fury of commit on master. the answer is : as soon as it stops as everything is fixed.

**Comment by thomas-mangin** [comment]
4.0.1 is released. This is not yet considered ready for production as the API command and configuration are still going to change but the code quality should meet production need.

**Comment by thomas-mangin** [comment]
API changes so the CLI can be considered stable and we are getting there. I will then release 4.0.2 with the goal to have 4.0.3 as stable.
