### ISSUE TITLE
Guide to help users migrating from 3.4 to 4.0

### ISSUE THREAD

**Issue by imperalix** [Exa-Networks/exabgp#650]
##### ISSUE TYPE

 - Documentation Report

##### VERSION

```
3.4.x
```

##### SUMMARY

Provide a guide to help users migrating from 3.4 to 4.0, due to breaking changes in configuration.

**Comment by thomas-mangin** [comment]
Until this issue is resolved - please look at the examples in the qa/conf folder:
https://github.com/Exa-Networks/exabgp/tree/master/qa/conf

**Comment by thomas-mangin** [comment]
files now moved to etc/exabgp  https://github.com/Exa-Networks/exabgp/tree/master/etc/exabgp

**Comment by thomas-mangin** [comment]
started https://github.com/Exa-Networks/exabgp/wiki/Migration-from-3.4-to-4.0

**Comment by thomas-mangin** [comment]
@imperalix commit to improve it welcomed but it covers the basics.
