### ISSUE TITLE
please add support for RFC5549

### ISSUE THREAD

**Issue by ruben-herold** [Exa-Networks/exabgp#651]
hi,

it would be nice if exabgp would support RFC5549 so that it is no longer needed to 
have ipv4 adresses on the link to the nexthop.

**Comment by thomas-mangin** [comment]
Indeed, the reason I never implemented this feature is that I have no way to test it. If you have some pcap of conversation using it, it would allow me to check the parser and make sure the code generation does what is expected.

**Comment by ruben-herold** [comment]
As far as I know (I'm in the moment in the phase to search which equipment will support it) arista eos has support for it. You can freely download an test it with virtualbox for example. For configuration if you have a login ( It's free). 

https://eos.arista.com/eos-4-17-0f/rfc-5549-ipv4-unicast-with-ipv6-next-hop-support/
https://eos.arista.com/eos-4-17-0f/ip-addressless-forwarding-changes-for-bgp-v6-nexthop-for-v4-routes/

Also https://frrouting.org/ has support for it. If I reach the testing phase I will sen you some pcap

**Comment by jllorente** [comment]
I am also very interested in this feature! It would be superb to have it available in exabgp.
Has there been any progress in this? If not, maybe I can try to setup some virtual environment an produce the PCAP files @thomas-mangin  requested :)

**Comment by thomas-mangin** [comment]
I am struggling to find time for dev atm .. So please do not expect this feature in 2018 ... sorry!

**Comment by thomas-mangin** [comment]
Just took a few years 😇 but it is now done.
