### ISSUE TITLE
performance of RIB for different AFs

### ISSUE THREAD

**Issue by adrian62** [Exa-Networks/exabgp#652]
##### ISSUE TYPE
performance enhancement

##### OS
Ubuntu 16.04LTS 64bit

##### VERSION

```
3.4.18
```

##### ENVIRONMENT 
```

```
##### CONFIGURATION
```

```
##### SUMMARY
Sending route updates over the API slows down as the RIB-out grows for AF vpnv6. With an empty RIB-out I measured a rate ~750/second. When the RIB is at 100K updates are processed at 1/second.
Conversely, for vpnv4 I measured ~1200/sec with the empty RIB and up to 100K entries, no noticeable slowdown.

##### STEPS TO REPRODUCE
Define at least one peer for the AF under test and measure the rate of processing routes injected through the API and sent towards the peer.

##### EXPECTED RESULTS
I would expect the performance to be closer between the AFs vpnv4 and vpnv6, understanding that vpnv6 will cost more to process. 

##### IMPORTANCE
Blocker for introducing the software in a production environment for AF vpnv6.

**Comment by thomas-mangin** [comment]
This behaviour would be consistent with a check in a large list - which is o(n).
I reviewed the RIB code and I can not find any reason why it would behave that way.

**Comment by thomas-mangin** [comment]
Do you have any way to check if the issue is still present on master please ?

**Comment by thomas-mangin** [comment]
I fixed the profiling in 3.4, could you please use `--profile stdout` and `--profile filename` to see where the CPU cycles are wasted please.

**Comment by adrian62** [comment]
I tried to replicate the problem in a different environment and it didn't manifest. I did see it happen consistently in the QA environment, so I'll have to go back and find out why it only happens there.I'll keep you posted.
thanks

**Comment by adrian62** [comment]
Two profiel files attached, one was obtained before the issue was recreated, to serve as a baseline; the second is with the issue recreated. Initially we bring up exabgp and send 100K vpnv6 route commands on the API; after we see that all routes have been successfully delivered to the peer defined in the configuration and things quieted down we send again the same set of routes on the API. That is the trigger for the issue, the exabgp process begins consuming most of the CPU and processes very slowly.

[afxprofile-goodrun.txt](https://github.com/Exa-Networks/exabgp/files/1076212/afxprofile-goodrun.txt)
[afxprofile-issuecreated.txt](https://github.com/Exa-Networks/exabgp/files/1076211/afxprofile-issuecreated.txt)

**Comment by thomas-mangin** [comment]
Thank you, problem understood. Not sure how to fix it yet but at least I understand why .. And I was blind last time I looked !

**Comment by thomas-mangin** [comment]
I think the difference comes from having very different attibutes for the routes, which cause the loops in updates to be much longer. Not fixed yet.

**Comment by thomas-mangin** [comment]
I have backported the current master code to 3.4 on my personal tree.
https://github.com/thomas-mangin/exabgp/tree/3.4
Could you please check that the problem is still present there - if so I will fix on master.

**Comment by thomas-mangin** [comment]
I done a massive refactor of the code on master for the RIB. Backport possible if the issue is gone.

**Comment by adrian62** [comment]
Does this update _require_ Python 3?

Adrian

**Comment by thomas-mangin** [comment]
No it will work with python 2 if you set the env value `INTERPRETER` to your favorite python2 binary.

**Comment by adrian62** [comment]
My configuration file's topmost section is group ... When I run this release of exa I see something like:

Mon, 19 Jun 2017 18:30:07 | ERROR    | 4372   | configuration | syntax error in section 
Mon, 19 Jun 2017 18:30:07 | ERROR    | 4372   | configuration | line 1: group EXA_AFX1_2_MISRR {
Mon, 19 Jun 2017 18:30:07 | ERROR    | 4372   | configuration | 
Mon, 19 Jun 2017 18:30:07 | ERROR    | 4372   | configuration | section group is invalid in root,

I vaguely recollect that i once tried the 4.0 branch and it might have done something similar. I looked at /doc/man/exabgp.conf.5 and didn't get any clue if the config hierarchy must be different.

**Comment by thomas-mangin** [comment]
The configuration on 4.0 / master changed a little - can you please look at the examples in qa/conf to update your config (should only take a few minutes).

**Comment by adrian62** [comment]
Please take a look at the attached file; original config and converted config to 4.x (one variant, I tried several). Exa comes up, establishes to the peer, the process recRoute.sh is spawned but I don't get the updates from the API. The only thing i get is the notification when I shut down. With the 3.x config I get the updates from the peer.
[exa3vs4config.txt](https://github.com/Exa-Networks/exabgp/files/1087112/exa3vs4config.txt)

**Comment by thomas-mangin** [comment]
Up to last night there was some bug with neighbor templates. It is not fixed and my work is to make sure 4.0.1 passes all the unit test of 3.4 (as many need to be adapted to the changes).
I also changed enormously the RIB code in the last days. The current release ef4a7bfad7d88e4e1bfe2df762c7d622f8b43f48 should be much less CPU intensive.

**Comment by adrian62** [comment]
I have been unable to verify whether the current release improves upon the RIB management; I issue 50K route announcements on the API; after about 12K+ get processed the exabgp logs go quiet,  and the peer reports keepalive timer expired. I have to SIGKILL it out of this state.

**Comment by thomas-mangin** [comment]
I just updated both master and 3.4 to make sure all NLRI had `__hash__` function. Could you please just retry ? If not please give me an example of a route you are announcing and I will try to replicate.

**Comment by adrian62** [comment]
See attached log files. We get a crash when the first route command is processed, which is a vpnv4. The other log shows the vpnv6 route commands also, but the code crashes before getting to work on them, I left them in as the example you asked for.
[afx-testing-1.txt](https://github.com/Exa-Networks/exabgp/files/1095651/afx-testing-1.txt)
[afx-testing-2.txt](https://github.com/Exa-Networks/exabgp/files/1095650/afx-testing-2.txt)

**Comment by thomas-mangin** [comment]
Sorry, I did not update the issue, this bug was fixed in master three days ago.
commit f0d02ed6d0a848c8fb77610f9ee93121829d1b90

For the performance, I have added `__hash__` function to the NLRI which should help performance.

**Comment by adrian62** [comment]
We are experiencing the same problem reported 5 days ago, where exabgp appears to lockup after processing a certain number of routes, we tried various numbers and combinations of vpnv4 and vpnv6 as follows:
1.  5k v4;  5k v6 routes entered on API; Results: all routes processed and sent to peer; after processing all routes see KEEPALIVE messages 
2. 10k  v4; 10k v6 routes; Results:  all v4 routes processed/sent to peer; after 3,060 v6 routes exa stop sending routes to peer, no KEEPALIVEs from exa after processing stopped; BGP session expires
3. 200k v4; 100k v6  routes; Results: after 12,835 v4 routes exa stop sending routes to peer, no KEEPALIVEs after processing stopped; BGP session expires

Let me know if you need any logs, tests done etc.

**Comment by thomas-mangin** [comment]
I need to create a lab and try to reproduce. If you have the script which generate these route for me to use, that would be of great help.

**Comment by thomas-mangin** [comment]
Can you confirm that this behaviour is seen on master.

**Comment by adrian62** [comment]
Confirmed, seen on master, more accurately:
Tue, 27 Jun 2017 00:27:39 | error    | 84840  | version       | 4.0.1-065deca1

I will upload a file that you can playback, since this is not generated it's real data coming through.

**Comment by adrian62** [comment]
Unrelated probably, I donwloaded the latest version and I see this error when I start:
 Could not find the named pipes for the cli in any of /run/65534/exabgp, /run/exabgp, /var/run/65534/exabgp, /var/run/exabgp, /home/exabgp-4.0.1-4501ddf3/run/65534/exabgp, /home/exabgp-4.0.1-4501ddf3/run/exabgp, /home/exabgp-4.0.1-4501ddf3/var/run/65534/exabgp, /home/exabgp-4.0.1-4501ddf3/var/run/exabgp

[playback20k.txt.gz](https://github.com/Exa-Networks/exabgp/files/1106409/playback20k.txt.gz)

**Comment by thomas-mangin** [comment]
oh - git can not stop fifo ....
```
mkfifo ./run/exabgp.in
mkfifo ./run/exabgp.out
```

**Comment by adrian62** [comment]
I have a feeling that the issue reported more recently in this thread where exabgp stops processing API commands and not sending keepalives to the peer after a certain number of routes is different than what I originally reported.
Because I can run the playback20k file (uploaded previously) against 3.4.19 and it processes it fast and reliable. The same file run against 4.0.1 stops somewhere after 12800-13000 routes. Whereas the original issue with 3.4 was at an order+ of magnitude higher and it wasn't a lockup, it just slowed down to a trickle and the peering session stayed alive.

**Comment by thomas-mangin** [comment]
Oops - yes, API processing could take 100% of the CPU time, not allowing for KEEALIVEs ... 
fixed with 5de2aeb3

**Comment by thomas-mangin** [comment]
result of investigations: on master commands are "asked" with a "done" or "error" message. The pipe buffer must allow to buffer 13k of these message before causing the write on the pipe to block (funnily it is noted in the code as such). The option exabgp.api.ack=false make 4.x behave like 3.4 not sending message unless the command is one which asks for it.

**Comment by thomas-mangin** [comment]
master: implemented NLRI comparaison for predictable ordering

**Comment by adrian62** [comment]
Tests with 200K vpnv4 and 50K vpnv6 routes show substantially improved rib-out performance. 
Will this be backported to the 3.x branch? [Exploratory question since we are considering sticking with 4.x, stability issues in 4.x notwithstanding].

**Comment by thomas-mangin** [comment]
The biggest changes for 4 are nearly all in, back porting would be difficult. I expect to release 4.0.2 and from there on work on any stability issues if any but I am pretty happy with the state of the code atm

**Comment by thomas-mangin** [comment]
But adding all the families to the announce part of the config & API and tidying up the API for the cli, 4.0 I'd ready.

**Comment by thomas-mangin** [comment]
Can I close this issue ?

**Comment by thomas-mangin** [comment]
For performance you should try to use "announce attributes <attributes> nlri <nlris>" it is MUCH faster for announcement as it reduces the parsing enormously.

**Comment by adrian62** [comment]
Please clarify:

- what the effect of this configuration setting is?
- show a config sample, as it appears the individual attributes must be listed?
- at what level of the config may this setting be applied (global, template, neighbor, AF?)

**Comment by thomas-mangin** [comment]
This is an API command (like the one you are using) which allows to associate multiple NLRI with a single attribute definition. It reduce the parsing required for each NLRI and therefore is faster.

This is not a configuration setting and examples are in the repo: https://github.com/Exa-Networks/exabgp/blob/master/etc/exabgp/api-attributes.conf and https://github.com/Exa-Networks/exabgp/blob/master/etc/exabgp/run/api-attributes.run

**Comment by adrian62** [comment]
Thanks, will look into using this trick to further the performance. BTW, pushed to 1M vpnv4 and 100K vpnv6, looked good.
