### ISSUE TITLE
Exabgp 4 : How to prevent a process from receiving shutdown almost immediately after starting

### ISSUE THREAD

**Issue by aallamaa** [Exa-Networks/exabgp#657]
Hello

I am using ExaBGP : 4.0.0-0478a014

I have a very simple process which is supposed to announce or withdraw a network based on some internal healthcheck. The main issue i have faced though is that almost immediately after sending intial messages, the process is receiving a shutdown:
```
{ "exabgp": "4.0.0", "time": 1497312444.5, "host" : "core-router-2", "pid" : 31227, "ppid" : 29943, "type": "notification", "notification": "shutdown" }\n'
```

How can i prevent this shutdown from happening and get a shutdown only when exabgp process is trying to terminate itself.

conf is the following:

```
process add-remove {
	run /nexthop.py;
	encoder json;

}

neighbor xxx {          # Remote neighbor to peer with
         router-id yyy;
         local-address yyy;    # Our local update-source
         local-as yyid;              # Our local AS
         peer-as xxid;               # Peer's AS

	api {
		processes [ add-remove ];
	}
}
```

**Comment by thomas-mangin** [comment]
Sorry this is a configuration issue and not a bug in ExaBGP: your peer is sending ExaBGP this shutdown.

I will invite you to look at the example in the qa/conf/ folder of ExaBGP to figure out how to configure ExaBGP and look at the router logs which should explain why the router at the remote end terminated the session.

Good luck.
