### ISSUE TITLE
Incorrect neighbor state

### ISSUE THREAD

**Issue by plajjan** [Exa-Networks/exabgp#658]
##### ISSUE TYPE

 - Bug Report

##### OS

Ubuntu Linux in a docker container.

##### VERSION

```
root@7d66cda62e1c:/# exabgp --version
ExaBGP : 3.4.18
Python : 2.7.9 (default, Jun 29 2016, 13:08:31)  [GCC 4.9.2]
Uname  : #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017
```

##### ENVIRONMENT 

```
root@7d66cda62e1c:/# exabgp --di
root@7d66cda62e1c:/#
```

##### SUMMARY

I'm trying to determine neighbor state by looking at the structured log from ExaBGP but it doesn't seem to be deterministic. Should this be possible?

##### STEPS TO REPRODUCE

The bug might have something to do with connection collisions, so tell ExaBGP to listen (not just connect actively). Wait until you get a connection collision (you might have to reset many times) and then look at the log to see if you can successfully determine the internal state of the neighbor in ExaBGP.

Here's an example log:
```
{ "exabgp": "3.4.8", "time": 1497427266, "host" : "36a4017b1b97", "pid" : "18", "ppid" : "1", "counter": 1, "type": "state", "neighbor": { "ip": "192.168.41.2", "address": { "local": "192.168.41.1", "peer": "192.168.41.2"}, "asn": { "local": "41", "peer": "2792"}, "state": "down", "reason": "connection to peer failed"} }

{ "exabgp": "3.4.8", "time": 1497427274, "host" : "36a4017b1b97", "pid" : "18", "ppid" : "1", "counter": 2, "type": "state", "neighbor": { "ip": "192.168.41.2", "address": { "local": "192.168.41.1", "peer": "192.168.41.2"}, "asn": { "local": "41", "peer": "2792"}, "state": "down", "reason": "connection to peer failed"} }

{ "exabgp": "3.4.8", "time": 1497427274, "host" : "36a4017b1b97", "pid" : "18", "ppid" : "1", "counter": 3, "type": "state", "neighbor": { "ip": "192.168.41.2", "address": { "local": "192.168.41.1", "peer": "192.168.41.2"}, "asn": { "local": "41", "peer": "2792"}, "state": "connected"} }

{ "exabgp": "3.4.8", "time": 1497427276, "host" : "36a4017b1b97", "pid" : "18", "ppid" : "1", "counter": 4, "type": "state", "neighbor": { "ip": "192.168.41.2", "address": { "local": "192.168.41.1", "peer": "192.168.41.2"}, "asn": { "local": "41", "peer": "2792"}, "state": "up"} }

{ "exabgp": "3.4.8", "time": 1497427277, "host" : "36a4017b1b97", "pid" : "18", "ppid" : "1", "counter": 5, "type": "state", "neighbor": { "ip": "192.168.41.2", "address": { "local": "192.168.41.1", "peer": "192.168.41.2"}, "asn": { "local": "41", "peer": "2792"}, "state": "connected"} }

{ "exabgp": "3.4.8", "time": 1497427278, "host" : "36a4017b1b97", "pid" : "18", "ppid" : "1", "counter": 6, "type": "state", "neighbor": { "ip": "192.168.41.2", "address": { "local": "192.168.41.1", "peer": "192.168.41.2"}, "asn": { "local": "41", "peer": "2792"}, "state": "down", "reason": "out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]"} }
```
as can be seen, we reach state `up` in the fourth line but then on the fifth it says `connected` again and sixth message it says we are down. If I look from the other side (a JUNOS router) I can see that the neighbor is indeed up.

Since I'm looking at this state output to then cache it in a separate data structure (outside of ExaBGP), it will show the wrong thing. It doesn't mirror the actual state of the BGP neighbor.

Some warn to not run "show neighbors" on production ExaBGP as it stops processing - 
https://git.framasoft.org/luc/erco/blob/master/utilities/bin/exabgp-ws-client.pl#L117 - is this a valid concern?

##### EXPECTED RESULTS

I don't expect the neighbor state to read `connected` or `down` just because one connection attempt (in or out) was failed during the time when we had already established a different TCP connection to the neighbor.

##### ACTUAL RESULTS

See above.

**Comment by thomas-mangin** [comment]
The FSM code was changed recently in master. There is no change to fix 3.4 (it would be too intrusive). Can you please test master (I did change quite a lot since 4.0.0 in this area).
4.0.1 should be released soon.

**Comment by thomas-mangin** [comment]
I mean no chance to correctly fix it the FSM - the connected/up state is surely do-able.

**Comment by thomas-mangin** [comment]
>Some warn to not run "show neighbors" on production ExaBGP as it stops processing -
https://git.framasoft.org/luc/erco/blob/master/utilities/bin/exabgp-ws-client.pl#L117 - is this a valid concern?

On master it is a non-issue. It should not cause issues anymore on 3.4 as the code are async callbacks neither but the reactor is still a bit weird.

**Comment by thomas-mangin** [comment]
Sorry missed this for 3.4.20 - will fix for 3.4.21

**Comment by thomas-mangin** [comment]
Or could you upgrade to master ?

**Comment by thomas-mangin** [comment]
@plajjan can I close this issue ?

**Comment by thomas-mangin** [comment]
fixed on master - will backport if issue is re-opened.
