### ISSUE TITLE
Announce immediately followed by withdraw route is being dropped

### ISSUE THREAD

**Issue by ravikumar727** [Exa-Networks/exabgp#661]
##### ISSUE TYPE
 - Bug Report

##### OS
Oracle 7.3

##### VERSION

```
ExaBGP : 3.4.18
Python : 2.7.5 (default, Sep  5 2016, 02:30:38)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-9)]
Uname  : #1 SMP Wed Apr 12 10:03:19 PDT 2017
```

##### ENVIRONMENT 

```
Output is empty
```

##### SUMMARY

When the labelled route is withdrawn and announced with different next-hop and within few milliseconds, ExaBgp is ignoring the announce and is sending only the withdraw to the Bgp peer.

##### STEPS TO REPRODUCE

1. withdraw route 216.58.217.4/32 rd 44:1000000 next-hop 10.0.42.3 extended-community [ target:44:1000000 ] label 44
2. announce route 216.58.217.4/32 rd 44:1000000 next-hop 10.0.44.7 extended-community [ target:44:1000000 ] label 44
The commands are sent to ExaBgp within few milliseconds.

##### EXPECTED RESULTS

Bgp peer should have been sent with the route with the new next-hop

##### ACTUAL RESULTS

Bgp peer received only the withdraw and not the announce that followed.

##### IMPORTANCE

It is impacting our production environment.

**Comment by thomas-mangin** [comment]
This issue should be fixed in master. I will look into changing this in 3.4 but it will cause some behavioural change ...

**Comment by ravikumar727** [comment]
@thomas-mangin Would you be able to point me to the change that addressed this?

**Comment by thomas-mangin** [comment]
@ravikumar727 a full rewrite of the RIB code I started in the last few days ... 

If you delete that block of code it should achieve the same result but I have not tested it:
https://github.com/Exa-Networks/exabgp/blob/3.4/lib/exabgp/rib/store.py#L166-L189

**Comment by ravikumar727** [comment]
@thomas-mangin May I know when are you targeting to publish the next 3.4 version?

**Comment by thomas-mangin** [comment]
I was not in a rush but if this change fixes your issue - I may do a release - I am however cautious as this change the behaviour of ExaBGP (trying to not send withdrawal when possible). However trying to make this work correctly on master, I found that while the code has been broken for ages, the issue you raise does exists.

**Comment by thomas-mangin** [comment]
@ravikumar727 did the change fix your issue ?

**Comment by thomas-mangin** [comment]
ping ? Did deleting these lines fix your issue ?

**Comment by ravikumar727** [comment]
We will be testing that on 06/26 and will let you know as soon as we find if we are good with it. Thanks for the follow up.

**Comment by ravikumar727** [comment]
@thomas-mangin 
The change you suggested doesn't seem to fix the issue of ignoring the announcement if the messages are sent quick. Please let me know if I am missing something.

```python
#!/usr/bin/env python

from sys import stdout
from time import sleep

messages = [
'announce route 1.2.3.4/32 rd 12345:1000000 next-hop 10.65.96.17 extended-community [ target:12345:1000000 ] label 725020',
'announce route 1.2.3.4/32 rd 12345:1000000 next-hop 10.129.44.3 extended-community [ target:12345:1000000 ] label 725020',
'announce route 1.2.3.4/32 rd 12345:1000000 next-hop 10.129.104.33 extended-community [ target:12345:1000000 ] label 725068',
'announce route 1.2.3.4/32 rd 12345:1000000 next-hop 10.129.46.19 extended-community [ target:12345:1000000 ] label 725076',
'announce route 1.2.3.4/32 rd 12345:1000000 next-hop 10.65.100.9 extended-community [ target:12345:1000000 ] label 725100',
'announce route 1.2.3.4/32 rd 12345:1000000 next-hop 10.65.58.7 extended-community [ target:12345:1000000 ] label 725110',
'announce route 1.2.3.4/32 rd 12345:1000000 next-hop 10.65.58.17 extended-community [ target:12345:1000000 ] label 725019',
'announce route 1.2.3.4/32 rd 12345:1000000 next-hop 10.64.132.25 extended-community [ target:12345:1000000 ] label 725113',
'announce route 1.2.3.4/32 rd 12345:1000000 next-hop 10.64.142.31 extended-community [ target:12345:1000000 ] label 725116',
'announce route 1.2.3.4/32 rd 12345:1000000 next-hop 10.65.28.7 extended-community [ target:12345:1000000 ] label 725024',
]

# Iterate through messages
for message in messages:
    stdout.write(message + '\n')
    stdout.flush()
    # with sleep, the bgp peer is getting the route with next-hop 10.65.28.7. 
    # without sleep, bgp peer is getting the route with next-hop 10.129.44.3
    sleep(1)

# Loop endlessly to allow ExaBGP to continue running
while True:
    sleep(1)
```

**Comment by ravikumar727** [comment]
@thomas-mangin ,
I have created a pull request with the fix for this issue. Please take a look and merge when possible. 
https://github.com/Exa-Networks/exabgp/pull/671

Also it would be great if you could release the next version with this change so that it would resolve the issue we are dealing with.

Thanks
Ravi

**Comment by thomas-mangin** [comment]
@ravikumar727 yes, this fix is the correct way to sort the issue, I implemented it on master a few weeks ago but did not consider back porting it. I merged. Thank you for the work.

**Comment by thomas-mangin** [comment]
3.4.20 is out - just for you .. and the rest of the internet :p

**Comment by ravikumar727** [comment]
Thanks a ton @thomas-mangin. Your help and quick turn around is much appreciated.

**Comment by thomas-mangin** [comment]
I noticed that I did not delete the store.py#L166-L189 - if this was required, I will need a new release.

**Comment by ravikumar727** [comment]
I had tested with those lines (store.py#L166-L189) on & off. In both the cases, this fix yielded the resolution for the bug. So we don't have to delete for this purpose unless you really want it.

**Comment by ravikumar727** [comment]
@thomas-mangin, looks like the fix you had proposed to remove store.py#L166-L189 is needed. we ran into an issue due to that. i will send a pull request with that change.
