### ISSUE TITLE
Invalid JSON encoding

### ISSUE THREAD

**Issue by tysonclugg** [Exa-Networks/exabgp#685]
Tested on 4.0.3 and master, with Python 3.6.1

##### ISSUE TYPE
 - Bug Report

##### OS
Ubuntu 16.04 LTS

##### VERSION

```
ExaBGP : 4.0.2-1c737d99
Python : 3.6.1 (default, Apr 22 2017, 20:17:23)  [GCC 5.4.0 20160609]
Uname  : Linux HP840G3 4.10.0-27-generic #30~16.04.2-Ubuntu SMP Thu Jun 29 16:07:46 UTC 2017 x86_64
Root   : /home/tclugg/.virtualenvs/mw-exabgp-daemon
```

##### ENVIRONMENT 

```
[exabgp.api]
cli = false

[exabgp.log]
all = true

[exabgp.tcp]
bind = '[0.0.0.0]'
port = 1179
```

##### SUMMARY
Invalid JSON sent to process:
```
{ "exabgp": "4.0.1", "time": 1500898540.8180687, "host" : "HP840G3", "pid" : 13703, "ppid" : 15954, "counter": 78, "type": "state", "neighbor": { "address": { "local": "192.168.3.97", "peer": "192.168.3.254" }, "asn": { "local": 65001, "peer": 64570 } , "state": "down", "reason": peer reset, message [closing connection] error[the TCP connection was closed by the remote end] } }
```
JSONDecodeError('Expecting value: line 1 column 282 (char 281)',)

##### STEPS TO REPRODUCE
Disconnect a peer, observe process stdin.

##### EXPECTED RESULTS
Valid JSON

##### ACTUAL RESULTS
Invalid JSON

**Comment by thomas-mangin** [comment]
You meant tested with 4.0.2 .. or you have a time machine and I am jealous - but then we just created a paradox as 4.0.3 will not have the bug ...

**Comment by tysonclugg** [comment]
<sarcasm>
Very funny.  Trust me, I'm LOL'ing around all over the place.
</sarcasm>

The bug exists in 4.0.2.  I also tested with current master.

**Comment by thomas-mangin** [comment]
It is still in master after the patch I just pushed ?

**Comment by tysonclugg** [comment]
@thomas-mangin Looks good to me, seems to have worked.  Thanks!  :smiley:
