### ISSUE TITLE
invalid keyword "receive-routes"

### ISSUE THREAD

**Issue by abreu75** [Exa-Networks/exabgp#693]
##### ISSUE TYPE

 - Bug Report

##### OS
Linux 

##### VERSION
```
ExaBGP : 4.0.2-1c737d99
Python : 2.7.12+ (default, Aug  4 2016, 20:04:34)  [GCC 6.1.1 20160724]
Uname  : Linux pikachu 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64
Root   : /usr/local
```

##### ENVIRONMENT 
```
(empty)
```

##### CONFIGURATION

```
process {
        encoder json;
        run /home/abreual/scripts/readroutes.py;
        receive-routes;
}

neighbor a.b.c.d {
        router-id w.x.y.z;
        local-address w.x.y.z;
        hold-time 180;
        local-as 11111;
        peer-as 11111;
        family {
                ipv4 unicast;
        }
}
```

##### SUMMARY

The config generates this:

16:05:14 | 3586   | configuration | problem with the configuration file, no change done
16:05:14 | 3586   | configuration |         
16:05:14 | 3586   | configuration | syntax error in section process
16:05:14 | 3586   | configuration | line 4: receive-routes ;
16:05:14 | 3586   | configuration |         
16:05:14 | 3586   | configuration | invalid keyword "receive-routes"

Apparently only run and encoder are being accepted. I'm new at exabgp so I'm prepared for this being a basic rookie mistake but neither the documentation or examples have helped me sort this out. Thanks for your help.

AA

##### STEPS TO REPRODUCE
just run "exabgp 'config file'"

##### EXPECTED RESULTS

Documentation states this and other valid commands for process:
https://github.com/Exa-Networks/exabgp/wiki/Controlling-ExaBGP-:-possible-options-for-process

The following options are valid under the process subsection :

run program-name;
encoder valid-encoder ( PLEASE - do NOT rely on the default encoder)
neighbor-changes
receive-routes
receive-packets
send-packets
experiemental : receive-operational

##### ACTUAL RESULTS
doesn't load config, complaining about invalid keyword

##### IMPORTANCE
important - exabgp not coming up

**Comment by thomas-mangin** [comment]
This is not a valid 4.0 configuration. Please look at the examples in the etc folder.
