### ISSUE TITLE
exabgpcli makes exabgp pin 100% CPU

### ISSUE THREAD

**Issue by chantra** [Exa-Networks/exabgp#704]
##### ISSUE TYPE

- Bug Report

##### OS
- Debian 9
- CentOS 7

##### VERSION
```
root@exabgp:~# INTERPRETER=python /mnt/hgfs/devtools/exabgp/sbin/exabgp --version
ExaBGP : 4.0.2-1c737d99
Python : 2.7.13 (default, Jan 19 2017, 14:48:08)  [GCC 6.3.0 20170118]
Uname  : Linux exabgp 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64
Root   : /mnt/hgfs/devtools/exabgp
```

##### ENVIRONMENT 

```
root@exabgp:~# INTERPRETER=python /mnt/hgfs/devtools/exabgp/sbin/exabgp --di

[exabgp.daemon]
drop = false
user = 'root'

[exabgp.tcp]
bind = '[0.0.0.0]'
```

##### CONFIGURATION
```
template {
  neighbor all {
    router-id 192.168.3.9;
    local-as 64400;
    hold-time 20;
    capability {
      graceful-restart;
    }
  }
}

process foo {
  run '/mnt/hgfs/devtools/exabgp/bin/showadjrib.py';
  encoder text;
}

neighbor 192.168.3.8 {
 inherit all;
  local-address 192.168.3.9;
  family {
    ipv4 unicast;
  }
  peer-as 64300;
}
```

##### SUMMARY

when using any command with `exabgpcli`, the exabgp process will start busy spinning the cpu.

##### STEPS TO REPRODUCE
Given the previous config and a peer configured properly, sending any command (valid or not) with `exabgpcli`:
```
exabgpcli help
```

##### EXPECTED RESULTS

`exabgp` should not pin a CPU

##### ACTUAL RESULTS

exabgp pins a CPU at 100%

##### IMPORTANCE
`exabgpcli` is pretty much useless as it would potentially prevent prevent exabgp from properly operating.

**Comment by chantra** [comment]
So basically, once exabgpcli has written to exabgp.in fifo, because the fifo is open os.O_RDONLY. Once the writer (exabgpcli) closes its end, after we have read the content, select will always report that the fifo is ready but all we get from it is EOF. 

I suppose one quick work around would be to close and re-open the fifo upon EOF (self.r_pipe in lib/exabgp/application/control.py)

**Comment by thomas-mangin** [comment]
hello @chantra, I do not see this behaviour at all on my mac but I was diagnosing the same issue for another user and had pined the issue to a bad FD for select, and it seems you found the reason before me !

As you are able to replicate and seems to have an idea on how to fix it could you please provide me with a patch (if it is not perfect I will massage it) ? The solution you are proposing seems like the right one.

**Comment by thomas-mangin** [comment]
I also received that patch but do not know if it is related .. 
https://github.com/Exa-Networks/exabgp/pull/689

**Comment by thomas-mangin** [comment]
And for information, I want to tidy up the API too to have all commands behaving with a `neighbor` prefix (as currently the RIB commands are .. quite lacking .. for example).

**Comment by thomas-mangin** [comment]
@chantra

Thank for for the fix. getting things working as should is always my priority.

Now I am wondering if another solution to the issue would be to modify `read_on` to detect the EOF and handle it correctly?

I have limited access to my computer ATM and can not spend the time I would like to debug this issue for at least until the end of next week.

**Comment by chantra** [comment]
> Now I am wondering if another solution to the issue would be to modify read_on to detect the EOF and handle it correctly?

Well, this would involved re-opening the fifo upon EOF (e.g when `read` returns `''`) over and over when reading from the fifo. This was my first quick fix actually. Using RDWR makes it behave more like a stream we are reading from. I don't have strong opinions though but failure to re-open the fifo will need to be properly handled. Most likely by logging the error and falling back into the mode with the control api disabled.

**Comment by thomas-mangin** [comment]
ok - it seems this simplifies the handling of error so I will keep the patch as it. Once again thank you for your help.
