### ISSUE TITLE
tcp.once exit doesn't reap child processes 

### ISSUE THREAD

**Issue by dhammika** [Exa-Networks/exabgp#712]
##### ISSUE TYPE
 - Bug Report

##### OS
Linux/Debian 8.9

##### VERSION
```
ExaBGP : 4.0.2-1c737d99
Python : 3.4.2 (default, Oct  8 2014, 10:45:20)  [GCC 4.9.1]
```

##### ENVIRONMENT 
```
```

##### CONFIGURATION
```
process morebacon {
	encoder json;
	run /usr/bin/morebacon;
}

neighbor 10.1.1.2 {
    description "10.1.1.2";
    router-id 10.1.1.1;
    local-address 10.1.1.1;
    peer-as 666;
    local-as 666;
    hold-time 720;
    group-updates;
    capability {
	    asn4 enable;
	    add-path disable;
	    route-refresh enable;
    }
    family {
	    ipv4 unicast;
    }
    api {
	    processes [morebacon];
	    neighbor-changes;
	    receive {
	        parsed;
	        update;
	    }
    }
}
```

##### SUMMARY
tcp.once exits without reaping child processes. 

##### STEPS TO REPRODUCE
Start exa from long running daemon process with tcp.once flag.

##### EXPECTED RESULTS
Expect exa to shutdown gracefully on bgp session termination.

##### ACTUAL RESULTS
Exa exits without reaping child processes, leaving behind zombies. 

##### IMPORTANCE
Accumulation of zombies over time is causing devops to panic.

**Comment by thomas-mangin** [comment]
Thank you for the fix. I assume this issue can now be closed ?

**Comment by dhammika** [comment]
Sure, thanks.
