### ISSUE TITLE
Exabgp becomes unresponsive / crashes at startup

### ISSUE THREAD

**Issue by michelpy** [Exa-Networks/exabgp#716]
##### ISSUE TYPE

 - Bug Report

##### OS

3.16.0-4-untangle-amd64 #1 SMP Debian 3.16.7-2untangle7 (2016-07-08) x86_64 GNU/Linux

##### VERSION

```
ExaBGP : 4.0.2-1c737d99
Python : 2.7.9 (default, Jun 29 2016, 13:08:31)  [GCC 4.9.2]
Uname  : Linux untangle.example.com 3.16.0-4-untangle-amd64 #1 SMP Debian 3.16.7-2untangle7 (2016-07-08) x86_64
Root   : /usr/local

```

##### ENVIRONMENT 

```

[exabgp.tcp]
bind = '[192.168.228.4]'

```

##### SUMMARY

This was working before. I adapted the conf file to the new syntax.

It starts running testcbbc.py but stops before the initial blacklist.conf file is processed. It never reaches the point that says Loop endlessly to allow ExaBGP to continue running. It never reaches the ins.close() statement.
When pressing CTRL-C, it does acknowlege the CTRL-C but never ends. It will never return to the shell prompt.
There are some 80K entries in the file; it stops after about 14K. The BGP session with the peer is initially established. The peer initially sees the prefixes but the session dies probably because of timeout.

The flush within the for line in ins: loop was a futile try, was not originally there and does not do anything.
Of course, executing testcbbc.py directly works as expected, it finishes the initial announce and then gets into the loop. Below is the testcbbc.py file; keep in mind that it does not finish the initial
with open("/etc/exabgp/ip-blacklist.conf", "r") as ins:

Was working fine with an earlier version of exabgp.

[root @ untangle] /etc/exabgp # cat testcbbc.py
#!/usr/bin/env python

from sys import stdout
from time import sleep
from subprocess import call
import os

with open("/etc/exabgp/ip-blacklist.conf", "r") as ins:
    for line in ins:
        line2 = line.rstrip('\n')
        line3 = line2.rstrip('\r')
        stdout.write( 'announce route ' + line3 + ' next-hop 192.0.2.1 community [65532:666]' + '\n')
        stdout.flush()
ins.close()
stdout.flush()

#Loop endlessly to allow ExaBGP to continue running

while True:
    sleep (5)
    # stdout.write('# toto is happy\n')
    # stdout.flush()
    # stdout.flush()
    if os.path.isfile('/etc/exabgp/ip-deltafile.conf'):
        sleep(10)
        with open("/etc/exabgp/ip-deltafile.conf", "r") as ins:
            for line in ins:
                if line.startswith('-'):
                    line2 = line.rstrip('\n')
                    line3 = line2.rstrip('\r')
                    line4 = line3.lstrip('-')
                    stdout.write( 'withdraw route ' + line4 + ' next-hop 192.0.2.1' + '\n')
                    stdout.flush()
                else:
                    line2 = line.rstrip('\n')
                    line3 = line2.rstrip('\r')
                    stdout.write( 'announce route ' + line3 + ' next-hop 192.0.2.1 community [65532:666]' + '\n')
                    stdout.flush()
        ins.close()
        call (["rm", "/etc/exabgp/ip-deltafile.conf"])
#

##### STEPS TO REPRODUCE

There is no fault, it just stops.

##### EXPECTED RESULTS

At least the initial loop to succeed.

##### ACTUAL RESULTS

Stops after 14K prefixes are announced.

##### IMPORTANCE

It's only semi-production, low priority.

**Comment by thomas-mangin** [comment]
Hello Michel, Could you please check https://github.com/Exa-Networks/exabgp/wiki/Migration-from-3.4-to-4.0 The part about the API ack message change should fix your issue.

**Comment by michelpy** [comment]
Thanks, this solves one problem and reveals another one.
Now that I have passed the ack issue, my python code acts strangely (only when used from ExaBGP, not when running in the shell). This is very simple code, when it is used by exabgp, what happens is that if the incremental update is detected, it acts like it restarts the python script testcbbc.py from the start, never deletes the incremental file, and loops announcing the large file.
I don't understand why.

[testcbbc.py.txt](https://github.com/Exa-Networks/exabgp/files/1288608/testcbbc.py.txt)

**Comment by thomas-mangin** [comment]
nothing obvious but the fact the os.remove could fail .. rewrote the code that way .. and please do use os.rename when you generate the file .. 10 second may not be enough for the generation. Also I flush stdout after each command and wait for the initial configuration file forever without doing anything is not.

```python
#!/usr/bin/env python

import os
from sys import stdout, stderr
from time import sleep
# from subprocess import call

def handle_content (generator,known):
    for line in generator:
        ip = line.strip()
        if ip.startswith('-'):
            if ip in known:
                del known[ip]
                stdout.write('withdraw route ' + ip[1:] + ' next-hop 192.0.2.1' + '\n')
                stdout.flush()
            # finished or trying to remove a ip we did not announce
            continue

        key = '-' + ip
        command = 'announce route ' + ip + ' next-hop 192.0.2.1 community [65532:666]' + '\n'
        known[key] = command
        stdout.write(command)
        stdout.flush()


seen = {}
filename = '/etc/exabgp/ip-blacklist.conf'

# Loop endlessly as it is what ExaBGP needs, and do nothing until a configuration is generated
while True:
    # using stderr for text as stdout is for exabgp commands only ...
    stderr.write('thomas is happy ... most of the time\n')
    stderr.flush()

    if os.path.isfile(filename):
        # Allow process creating the file to finish
        # ----------------
        # ugly .. the file should be generated with another name and then moved when completed (which is atomic).
        sleep(10)
        # ----------------
        with open(filename, "r") as line_generator:
            handle_content(line_generator,seen)

        # if we just started, we should delete previous delta if any as not relevant
        filename = '/etc/exabgp/ip-deltafile.conf'
        try:
            os.remove(filename)
        except:
            pass

    # Check every 5 seconds if an incremental update is available
    sleep (5)
```

**Comment by michelpy** [comment]
Thanks, will try ASAP. I actually replaced the entire thing with new code yesterday, works fine.
I understand my python is ugly, this was one of my first tries at it. By looking at your code I learned a lot, thanks for the education.

Why import stdout ? my logic what to import only if the command was not found ?

The think that I still don't understand is why it believes differently in exabgp 4.0 than it does with 3.4 or with the shell. What is different in the exabgp 4.0 environment ?

Thanks again,
Michel.

**Comment by thomas-mangin** [comment]
> Why import stdout ? my logic what to import only if the command was not found ?
I do not understand why you ask ..

There is difference in the API parsing code between 3.4 and 4.0 - getting things working the same on all OSes is a challenge - Python does not behave the exact same way everywhere.

I will look into it - but flushing after each write is really a must ...

**Comment by thomas-mangin** [comment]
I assume all is fine and I can just close this issue - if not, please feel fee to re-open it.
