### ISSUE TITLE
Error building debian package

### ISSUE THREAD

**Issue by fser** [Exa-Networks/exabgp#724]
##### ISSUE TYPE

 - Bug Report

##### OS

Debian 9

##### VERSION

```
root@137d6bfc873a:/exabgp/debian# git branch -v
* master ef31ff9b Merge pull request #719 from chantra/exabgp_fix_py3_cli
```

##### ENVIRONMENT 

```
Not relevant
```

##### SUMMARY

Trying to create a debian package using `debuild -us -uc` (didn't find any documentation on how what to do).

##### EXPECTED RESULTS

Find a debian package.

##### ACTUAL RESULTS

```
env INTERPRETER=python ./qa/bin/conversation
env: './qa/bin/conversation': No such file or directory
debian/rules:11: recipe for target 'override_dh_auto_test' failed
make[1]: *** [override_dh_auto_test] Error 127
make[1]: Leaving directory '/exabgp'
debian/rules:4: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1116:
dpkg-buildpackage -rfakeroot -us -uc failed
```

I tried changing `conversation` to `conversation.serial` which actually exists, but the process gets stucked.

##### IMPORTANCE

It would be great to fix this to provide debian packages instead of pip packages.

**Comment by vincentbernat** [comment]
Is your branch for ExaBGP 4.x or 3.x? In the former case, take the Debian packaging from the debian/sid branch. The master branch hasn't been updated yet.

**Comment by fser** [comment]
For 4.x. Let me try that branch.

**Comment by thomas-mangin** [comment]
4.x does not force python3 - it default to it but python2 still works

**Comment by fser** [comment]
Shouldn't print function be used in that case?

**Comment by fser** [comment]
@thomas-mangin could you please provide some hints on how you build the package? I can't manager to specify only python2 at the moment. I've created a [wiki entry](https://github.com/Exa-Networks/exabgp/wiki/Building-debian-package) for that purpose.

**Comment by thomas-mangin** [comment]
@fser while I built some .rpm a .deb quite some time ago for myself, I have not followed all packaging work done by @vincentbernat - from my POV, it is simply black magic which works :-)

if you run `env INTERPRETER=/path/to/python2 ./sbin/exabgp` this will force python2

**Comment by vincentbernat** [comment]
Which `print` are we talking about? This doesn't seem to be related with the packaging.

If you want to force Python 2 while running ExaBGP with systemd, you can do:

```
systemctl edit exabgp.service
```

Then add:

```
[Service]
Environment=INTERPRETER=/usr/bin/python2
```

Not tested, but should work.

**Comment by fser** [comment]
When (trying to) building the deb file (again, using `debuild -us -uc`), I get the following error:
```
continue anyway? (y/n) y
 dpkg-buildpackage -rfakeroot -us -uc
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: info: source package exabgp
dpkg-buildpackage: info: source version 4.0.0-1
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by James Page <james.page@ubuntu.com>
 dpkg-source --before-build exabgp
dpkg-buildpackage: info: host architecture amd64
dpkg-source: info: applying failing-unittests.patch
 fakeroot debian/rules clean
pyversions: missing X(S)-Python-Version in control file, fall back to debian/pyversions
pyversions: missing debian/pyversions file, fall back to supported versions
py3versions: no X-Python3-Version in control file, using supported versions
dh clean --with python2,python3 --buildsystem=pybuild
   dh_testdir -O--buildsystem=pybuild
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/exabgp'
pyversions: missing X(S)-Python-Version in control file, fall back to debian/pyversions
pyversions: missing debian/pyversions file, fall back to supported versions
py3versions: no X-Python3-Version in control file, using supported versions
dh_auto_clean --buildsystem=pybuild
I: pybuild base:184: python2.7 setup.py clean 
running clean
removing '/exabgp/.pybuild/pythonX.Y_2.7/build' (and everything under it)
'build/bdist.linux-amd64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
I: pybuild base:184: python3.5 setup.py clean 
  File "setup.py", line 47
    """
      ^
SyntaxError: Missing parentheses in call to 'print'
E: pybuild pybuild:283: clean: plugin distutils failed with: exit code=1: python3.5 setup.py clean 
dh_auto_clean: pybuild --clean --test-nose -i python{version} -p 3.5 returned exit code 13
debian/rules:29: recipe for target 'override_dh_auto_clean' failed
make[1]: *** [override_dh_auto_clean] Error 25
make[1]: Leaving directory '/exabgp'
debian/rules:9: recipe for target 'clean' failed
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
debuild: fatal error at line 1116:
dpkg-buildpackage -rfakeroot -us -uc failed
```
I have put the whole process in a [dockerfile + script](https://gist.github.com/fser/a3bd2bd7d750b7524a44ceebdb660b33).

**Comment by vincentbernat** [comment]
OK. I'll have to fix that. What you can do is checkout master (or the version your want) and take debian directory from debian/sid.

```
git checkout 4.0.2
git checkout debian/sid -- debian
dch -v 4.0.2-0 "New upstream release"
```

**Comment by thomas-mangin** [comment]
Should I remove the Debian folder from master ?

**Comment by vincentbernat** [comment]
If removed, users won't know how to get Debian packages. And there can be slight differences with the packaging in debian/sid. On the other hand, removing it is less work for me. I still plan to work on packaging real soon and I'll update master then.

**Comment by fser** [comment]
@vincentbernat doing so also fails to build (from master):
```
 dpkg-source -b exabgp
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../exabgp_4.0.2.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -b exabgp gave error exit status 255
debuild: fatal error at line 1116:
dpkg-buildpackage -rfakeroot -us -uc failed
```

Almost same message from 4.0.2 though.

**Comment by vincentbernat** [comment]
`rm debian/source/format` and retry.

**Comment by fser** [comment]
Better, but still won't build :)
```
running install_scripts
Installing exabgp script to /root/exabgp/debian/python3-exabgp/usr/bin
rm -rf /root/exabgp/debian/exabgp/usr/etc /root/exabgp/debian/python*-exabgp/usr/share/exabgp
mkdir -p /root/exabgp/debian/python-exabgp/usr/sbin /root/exabgp/debian/python3-exabgp/usr/sbin
mv /root/exabgp/debian/python-exabgp/usr/bin/exabgp /root/exabgp/debian/python-exabgp/usr/sbin/python2-exabgp
mv /root/exabgp/debian/python3-exabgp/usr/bin/exabgp /root/exabgp/debian/python3-exabgp/usr/sbin/python3-exabgp
make[1]: Leaving directory '/root/exabgp'
   dh_install -O--buildsystem=pybuild
dh_install: Cannot find (any matches for) "qa/conf/*" (tried in "." and "debian/tmp")
dh_install: exabgp-common missing files: qa/conf/*
dh_install: missing files, aborting
debian/rules:9: recipe for target 'binary' failed
make: *** [binary] Error 255
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1116:
dpkg-buildpackage -rfakeroot -us -uc failed
```

The only conf I have in `qa/` folder are:
```
root@38329ee9b641:~/exabgp# ls qa/**/*.conf
qa/ci/skip-large-mp.conf  qa/ci/skip-large.conf  qa/new/simple.conf
```

**Comment by vincentbernat** [comment]
Remove the corresponding lines from `debian/exabgp-common.install`.

**Comment by fser** [comment]
It works! I've updated the [wiki entry](https://github.com/Exa-Networks/exabgp/wiki/Building-debian-package). Thanks!

I don't close the issue, because for now, the repository is still kind of broken.

**Comment by thomas-mangin** [comment]
Thank you very so much for this wiki page - this is much appreciated.

**Comment by thomas-mangin** [comment]
@vincentbernat updated the Debian folder with a new README file - closing this issue. Thank you @fser for creating the wiki entry (and @vincentbernat for maintaining the Debian packaging)
