### ISSUE TITLE
BGP-LS failing

### ISSUE THREAD

**Issue by AndrewAlston** [Exa-Networks/exabgp#729]
##### ISSUE TYPE

 - Bug Report

##### VERSION

```
ExaBGP : 4.0.2-1c737d99
Python : 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
Uname  : Linux home-server 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64
Root   : /usr/local

```

##### ENVIRONMENT 

```
It's empty
```

##### SUMMARY

Session is dropping when enabling BGP-LS towards latest JunOS Beta due to what looks like unsupported flags
##### STEPS TO REPRODUCE

Turn up BGP-LS to a 17.4 beta JunOS version running SR - session will drop when receiving generic flags of ISIS_ADJ_SR_FLAGS.

14:21:56 | 21613  | peer-1          | << UPDATE #152
14:21:56 | 21613  | peer-1          |    UPDATE #152 nlri  (   2) { "ls-nlri-type": 2, "l3-routing-topology": 0, "protocol-id": 2, "local-node-descriptors": { "autonomous-system": 30844, "router-id": "1111111111" }, "remote-node-descriptors": { "autonomous-system": 30844, "router-id": "11111111111" }, "interface-address": { "interface-address": "197.155.94.144" }, "neighbor-address": { "neighbor-address": "333.333.33.333" } }
14:21:56 | 21613  | outgoing-3      | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 00EC 02
14:21:56 | 21613  | outgoing-3      | received TCP payload ( 217) 0000 00D5 4001 0100 4002 0040 0504 0000 0064 801D 6D04 4000 0400 0000 0004 4100 044E 9502 F904 4200 0400 0000 0004 4300 2000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0004 4400 0400 0000 0A04 4700 0300 000A 044C 000D 7000 0000 1971 5509 4120 00F1 D304 4C00 0D30 0000 0019 7155 0941 2000 F1E8 900E 0053 4004 4704 293C E123 0000 0200 4602 0000 0000 0000 0000 0100 0012 0200 0004 0000 787C 0203 0006 1971 5509 4102 0101 0013 0200 0004 0000 787C 0203 0007 1971 5509 4102 0701 0300 04C5 9B5E FE01 0400 04C5 9B5E FE
14:21:56 | 21613  | outgoing-3      | << message of type UPDATE
14:21:56 | 21613  | parser          | parsing UPDATE ( 217) 0000 00D5 4001 0100 4002 0040 0504 0000 0064 801D 6D04 4000 0400 0000 0004 4100 044E 9502 F904 4200 0400 0000 0004 4300 2000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0004 4400 0400 0000 0A04 4700 0300 000A 044C 000D 7000 0000 1971 5509 4120 00F1 D304 4C00 0D30 0000 0019 7155 0941 2000 F1E8 900E 0053 4004 4704 293C E123 0000 0200 4602 0000 0000 0000 0000 0100 0012 0200 0004 0000 787C 0203 0006 1971 5509 4102 0101 0013 0200 0004 0000 787C 0203 0007 1971 5509 4102 0701 0300 04C5 9B5E FE01 0400 04C5 9B5E FE
14:21:56 | 21613  | parser          | withdrawn NLRI none
14:21:56 | 21613  | parser          | attribute origin             flag 0x40 type 0x01 len 0x01 payload 00
14:21:56 | 21613  | parser          | attribute as-path            flag 0x40 type 0x02 len 0x00
14:21:56 | 21613  | parser          | attribute local-preference   flag 0x40 type 0x05 len 0x04 payload 0000 0064
14:21:56 | 21613  | parser          | attribute bgp-ls             flag 0x80 type 0x1d len 0x6d payload 0440 0004 0000 0000 0441 0004 4E95 02F9 0442 0004 0000 0000 0443 0020 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0444 0004 0000 000A 0447 0003 0000 0A04 4C00 0D70 0000 0019 7155 0941 2000 F1D3 044C 000D 3000 0000 1971 5509 4120 00F1 E8
14:21:56 | 21613  | outgoing-3      | could not decode message "2"
14:21:56 | 21613  | outgoing-3      | type object 'LsGenericFlags' has no attribute 'ISIS_ADJ_SR_FLAGS'
14:21:56 | 21613  | outgoing-3      | Traceback (most recent call last):
14:21:56 | 21613  | outgoing-3      |   File "/home/aalston/.local/lib/python2.7/site-packages/exabgp/reactor/protocol.py", line 229, in read_message
14:21:56 | 21613  | outgoing-3      |     message = Message.unpack(msg_id,body,self.negotiated)
14:21:56 | 21613  | outgoing-3      |   File "/home/aalston/.local/lib/python2.7/site-packages/exabgp/bgp/message/message.py", line 188, in unpack
14:21:56 | 21613  | outgoing-3      |     return cls.klass(message).unpack_message(data,negotiated)
14:21:56 | 21613  | outgoing-3      |   File "/home/aalston/.local/lib/python2.7/site-packages/exabgp/bgp/message/update/__init__.py", line 199, in unpack_message
14:21:56 | 21613  | outgoing-3      |     attributes = Attributes.unpack(_attributes,negotiated)
14:21:56 | 21613  | outgoing-3      |   File "/home/aalston/.local/lib/python2.7/site-packages/exabgp/bgp/message/update/attribute/attributes.py", line 292, in unpack
14:21:56 | 21613  | outgoing-3      |     attributes = cls().parse(data,negotiated)
14:21:56 | 21613  | outgoing-3      |   File "/home/aalston/.local/lib/python2.7/site-packages/exabgp/bgp/message/update/attribute/attributes.py", line 384, in parse
14:21:56 | 21613  | outgoing-3      |     return self.parse(left,negotiated)
14:21:56 | 21613  | outgoing-3      |   File "/home/aalston/.local/lib/python2.7/site-packages/exabgp/bgp/message/update/attribute/attributes.py", line 384, in parse
14:21:56 | 21613  | outgoing-3      |     return self.parse(left,negotiated)
14:21:56 | 21613  | outgoing-3      |   File "/home/aalston/.local/lib/python2.7/site-packages/exabgp/bgp/message/update/attribute/attributes.py", line 384, in parse
14:21:56 | 21613  | outgoing-3      |     return self.parse(left,negotiated)
14:21:56 | 21613  | outgoing-3      |   File "/home/aalston/.local/lib/python2.7/site-packages/exabgp/bgp/message/update/attribute/attributes.py", line 370, in parse
14:21:56 | 21613  | outgoing-3      |     decoded = Attribute.unpack(aid,flag,attribute,negotiated)
14:21:56 | 21613  | outgoing-3      |   File "/home/aalston/.local/lib/python2.7/site-packages/exabgp/bgp/message/update/attribute/attribute.py", line 282, in unpack
14:21:56 | 21613  | outgoing-3      |     instance = cls.klass(attribute_id,flag).unpack(data,negotiated)
14:21:56 | 21613  | outgoing-3      |   File "/home/aalston/.local/lib/python2.7/site-packages/exabgp/bgp/message/update/attribute/bgpls/linkstate.py", line 56, in unpack
14:21:56 | 21613  | outgoing-3      |     klass = cls.registered_lsids[scode].unpack(data[4:length+4],length)
14:21:56 | 21613  | outgoing-3      |   File "/home/aalston/.local/lib/python2.7/site-packages/exabgp/bgp/message/update/attribute/bgpls/link/sradjlan.py", line 52, in unpack
14:21:56 | 21613  | outgoing-3      |     flags = LsGenericFlags.unpack(data[0:1],LsGenericFlags.ISIS_ADJ_SR_FLAGS)
14:21:56 | 21613  | outgoing-3      | AttributeError: type object 'LsGenericFlags' has no attribute 'ISIS_ADJ_SR_FLAGS'

##### IMPORTANCE

Critical for beta testing work I'm doing

**Comment by thomas-mangin** [comment]
@ruissalo - can you look of should I ?

**Comment by ruissalo** [comment]
I'll take a look later today.

**Comment by ruissalo** [comment]
there seems to be a typo, it should be ISIS_SR_ADJ_FLAGS  instead of ISIS_ADJ_SR_FLAGS.

I need to check with @thomas-mangin on the best way to add unit tests to this.

Will push a fix this weekend.

**Comment by ruissalo** [comment]
@AndrewAlston this should be fixed now. Please use the latest master to test.

**Comment by ruissalo** [comment]
@AndrewAlston I'd also suggest you get in touch with your JTAC team if you have a support contract, it seems like the box is duplicating the Adjacency LAN Attribute.

0440 0004 0000 0000 0441 0004 4E95 02F9 0442 0004 0000 0000 0443 0020 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0444 0004 0000 000A 0447 0003 0000 0A04 4C00 0D70 0000 00**19 7155 0941 2000 F1**D3 044C 000D 3000 0000 **1971 5509 4120 00F1** E8
