### ISSUE TITLE
Python3 question

### ISSUE THREAD

**Issue by jmauro** [Exa-Networks/exabgp#733]
Hello,

The issue is more a question than a report. 
I must confess I am a bit confused with the use of `python2`and `python3`. Let's say, I want to create a brand new architecture based on ExaBGP, am I supposed to create an RPM package (yes I'd rather have a distribution package for now) with python2 or python3, should I stay to version 3.4.XX or version 4.XX.XX?

Could someone give me some insight?

Regards,
JM

**Comment by thomas-mangin** [comment]
3.4 is the "stable" version and is python 2 only 
4.0 will be python 2 and 3 compatible but development switched from python centric 2 to python 3 centric
version 5.0 will drop support for python 2 support.

4.0 will become the new stable version soon - hope it helps.

**Comment by thomas-mangin** [comment]
assuming it answered the question - if not: 'reopen is your friend'

**Comment by jmauro** [comment]
Yes the explanation is clear

**Comment by tmmorin** [comment]
Note that there are Fedora RPMs for ExaBGP: http://rpmfind.net/linux/rpm2html/search.php?query=exabgp
I believe this is python2.
