### ISSUE TITLE
Exabgp produces invalid JSON

### ISSUE THREAD

**Issue by aabdnn** [Exa-Networks/exabgp#746]
##### ISSUE TYPE
 - Bug Report

##### OS
CentOS 6.9, with exabgp running under pypy 2.0.2

##### VERSION
```
ExaBGP : 3.4.15
Python : 2.7.3 (f66246c46ca30b26a5c73e4cc95dd6235c966b8f, Jul 30 2013, 09:27:06) [PyPy 2.0.2 with GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]
Uname  : #1 SMP Wed Jul 12 14:17:22 UTC 2017
```

##### ENVIRONMENT 
```
[exabgp.api]
highres = true

[exabgp.cache]
attributes = false
nexthops = false

[exabgp.log]
configuration = false
destination = 'syslog'
```

##### CONFIGURATION
```
group multi_neighbor {
    process receive-routes {
        encoder json;
        run /opt/exabgp/bin/queuer.py /export/exabgp/message-queues-rabbit/4 /export/exabgp/message-queues-kafka/4;
        neighbor-changes;
        receive {
            update;
            parsed;
            packets;
            consolidate;
            open;
            keepalive;
            notification;
        }
    }
    process control-socket {
        run /opt/exabgp/bin/control_socket.run /var/run/exabgp/control_instance_4.sock;
    }
    process beacon {
        run /opt/exabgp/bin/beaconhandler.py /opt/exabgp/etc/exabgp/beacon_instance_4.conf /var/run/exabgp/beacon_4.state /opt/exabgp/etc/exabgp/bgp-beacon.def;
    }
    family {
        ipv4 unicast;
        ipv6 unicast;
    }
    neighbor 2001:7f8:24::5a {
        router-id 91.206.52.253;
        local-address 2001:7f8:24::fd;
        local-as 12654;
        peer-as 59414;
 
        static {
        }
 
    }
}
```

There are more peers in the config, but I've only left in the one that's triggering this bug.

##### SUMMARY
When exabgp receives an update from this peer, the resulting JSON contains control characters. When exabgp passes this JSON to the "receive-routes" process, that process dies with an exception.

##### STEPS TO REPRODUCE
I don't know if this can be easily reproduced. However, I'm attaching a file here containing the JSON produced from an update from this peer. The thing of note is that there is a key called "raw", and this contains control characters.

[rrc20-exabgp-broken-json.txt](https://github.com/Exa-Networks/exabgp/files/1496002/rrc20-exabgp-broken-json.txt)

##### EXPECTED RESULTS
Properly escaped JSON.

##### ACTUAL RESULTS
The JSON structure contains a key called "raw" with control characters in it.

##### IMPORTANCE
This is causing a problem in production, because this update causes the receive-routes process to die, and this in turn causes exabgp to die.

**Comment by thomas-mangin** [comment]
So this open contain a capability of type 73 which is draft-walton-bgp-hostname-capability-02 .. and the data is `{ "name": "unknown", "iana": "unassigned", "value": 73, "raw": "r2-zrh1" } } } } `

ExaBGP used to send this but not anymore and I am not aware of any vendor having this on ..
So the question is which peers of yours is sending this !!

Hopefully this will prevent the issue: https://github.com/Exa-Networks/exabgp/commit/afbf7d65430d0a2462cd77d8acdd01f52215a139
