### ISSUE TITLE
Handling Multi Neighbor Scenario

### ISSUE THREAD

**Issue by SivaKesava1** [Exa-Networks/exabgp#754]
In the parse-dual -neighbor.conf can we have:

process announce-routes{
run (path to python) example.py
}

With "announce" routes in example.py

and in only in one  neighbor  if we have:
 api {
        processes [announce-routes];
    }

But the routes are announced to both the neighbors if we don't add "neighbor" to "announce route" so is it that way even if we ask to execute the file only in one neighbor?

One more questions:

Where does this received BGP messages? I am not able to see them printed on STDOUT. 
api {
			processes [ my-process ];
			neighbor-changes;
			receive {
				parsed;
				packets;
				update;
			}
	}

**Comment by thomas-mangin** [comment]
You do not provide the requested information about the version - please use 4.0.

**Comment by thomas-mangin** [comment]
Please look at the wiki for example of API use, if it is still not clear re-open the issue.
