### ISSUE TITLE
Permission Denied Error

### ISSUE THREAD

**Issue by ChesterCh** [Exa-Networks/exabgp#756]
I keep getting the permission denied error when I try to open a file and write to that file in ExaBgp. This is what is printed when I run exabgp with a conf file:

19:16:36 | 9926   | welcome       | Thank you for using ExaBGP
19:16:36 | 9926   | version       | 4.0.2-1c737d99
19:16:36 | 9926   | interpreter   | 3.4.3 (default, Nov 28 2017, 16:41:13)  [GCC 4.8.4]
19:16:36 | 9926   | os            | Linux  3.13.1-031301-generic #201401291035 SMP Wed Jan 29 15:37:43 UTC 2014 x86_64
19:16:36 | 9926   | installation  |         
19:16:36 | 9926   | cli           | could not find the named pipes (exabgp.in and exabgp.out) required for the cli
19:16:36 | 9926   | cli           | we scanned the following folders (the number is your PID):
19:16:36 | 9926   | cli control   |  - /run/1000/
19:16:36 | 9926   | cli control   |  - /run/
19:16:36 | 9926   | cli control   |  - /var/run/1000/
19:16:36 | 9926   | cli control   |  - /var/run/
19:16:36 | 9926   | cli control   |  - /run/1000/
19:16:36 | 9926   | cli control   |  - /run/
19:16:36 | 9926   | cli control   |  - /var/run/1000/
19:16:36 | 9926   | cli control   |  - /var/run/
19:16:36 | 9926   | cli control   | please make them in one of the folder with the following commands:
19:16:36 | 9926   | cli control   | > mkfifo /home/user/Desktop/exabgp_Trial/run/exabgp.{in,out}
19:16:36 | 9926   | cli control   | > chmod 600 /home/user/Desktop/exabgp_Trial/run/exabgp.{in,out}
19:16:36 | 9926   | cli control   | > chown 1000:1000 /home/user/Desktop/exabgp_Trial/run/exabgp.{in,out}
19:16:36 | 9926   | configuration | performing reload of exabgp 4.0.2-1c737d99
19:16:36 | 9926   | reactor       | loaded new configuration successfully
^C19:16:39 | 9926   | reactor       | ^C received
19:16:39 | 9926   | reactor       | performing shutdown
Traceback (most recent call last):
  File "/home/user/Desktop/exabgp_Trial/readstdin.py", line 13, in <module>
    print ('******************', line,file=open("error", "a"))
PermissionError: [Errno 13] Permission denied: 'error'

readstdin.py:
while True:
    sleep(1)
    line = sys.stdin.readline().strip()
    print ('******************', line,file=open("error", "a"))

I even created a var folder and ran the commands it said but even then I was not able to write to a file.

**Comment by thomas-mangin** [comment]
ExaBGP drop permission to nobody when it runs - it is a unix permission issue as your code is being executed by ExaBGP AFTER dropping root privilege (for security reason).

You can look at the option to run ExaBGP as another user which have the right to write to that location.
