### ISSUE TITLE
exabgp is missing its setuptools config file

### ISSUE THREAD

**Issue by sanfern** [Exa-Networks/exabgp#757]
##### ISSUE TYPE

 - Feature Idea

##### OS

Ubuntu 16.04
##### VERSION

```
ubuntu@exabgp-demo:~$ exabgp --version
ExaBGP : 4.0.2-1c737d99
Python : 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
Uname  : Linux exabgp-demo 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64
Root   : /usr/local
ubuntu@exabgp-demo:~$
```

##### ENVIRONMENT 

```
empty
```

##### EXPECTED RESULTS

Installation of cli tools

**Comment by thomas-mangin** [comment]
Hello, this is a statement. Not sure what I should do with it ...

**Comment by thomas-mangin** [comment]
oh ! I guess it should read `exabgpcli` and not `exabgp` and `is missing from the setupools` .. in that case the bug was fixed some time ago .. as the current setuptools file shows:

```
        entry_points={
                'console_scripts': [
                        'exabgp = exabgp.application:run_exabgp',
                        'exabgpcli = exabgp.application:run_cli',
                ],
```

if not please re-open the issue 😛 if I misunderstood.
