### ISSUE TITLE
NOTIFY does not include peer information or raw body/header

### ISSUE THREAD

**Issue by spakka** [Exa-Networks/exabgp#758]
Hi Thomas,

##### ISSUE TYPE
 - Bug Report

##### OS
CentOS release 6.9 (Final)

##### VERSION

```
ExaBGP : 3.4.23
Python : 2.7.3 (f66246c46ca30b26a5c73e4cc95dd6235c966b8f, Jul 30 2013, 09:27:06) [PyPy 2.0.2 with GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]
Uname  : #1 SMP Wed Jul 12 14:17:22 UTC 2017
```

##### ENVIRONMENT 

```
[exabgp.api]
highres = true

[exabgp.cache]
attributes = false
nexthops = false

[exabgp.log]
configuration = false
destination = 'syslog'
```

##### CONFIGURATION

```
    process receive-routes {
        encoder json;
	run /opt/exabgp/bin/queuer.py;
        neighbor-changes;
        receive {
            update;
            parsed;
            packets;
            consolidate;
            open;
            keepalive;
            notification;
        }
    }
```

##### SUMMARY
When Exabgp 3.4.23 receives a notify message from its peer, the received message does not include the 'neighbor' structure that contains the details about which peer the notify was sent from. It is also missing the 'body' and 'header' sections that we use to get the original raw message. These are present on Open, Update and Keepalive, but not Notify.

##### STEPS TO REPRODUCE
Configure a peering session towards a BGP neighbor that is not configured to accept the session.
Some implementations will accept the TCP connection, exchange OPEN messages, and then reply with a NOTIFY (error[Cease / Connection Rejected])

##### ACTUAL RESULTS
```
{
  "notification": {
    "subcode": 5,
    "code": 6,
    "data": "0605"
  },
  "counter": 531,
  "pid": "27552",
  "exabgp": "3.4.8",
  "host": "rrc20.ripe.net",
  "time": 1513869151.32,
  "ppid": "1",
  "type": "notification"
}
{
  "counter": 532,
  "pid": "27552",
  "exabgp": "3.4.8",
  "host": "rrc20.ripe.net",
  "neighbor": {
    "reason": "out loop, peer reset, message [notification received (6,5)] error[Cease / Connection Rejected]",
    "ip": "2001:7f8:24::47",
    "state": "down",
    "asn": {
      "peer": "34288",
      "local": "12654"
    },
    "address": {
      "peer": "2001:7f8:24::47",
      "local": "2001:7f8:24::fd"
    }
  },
  "time": 1513869151.32,
  "ppid": "1",
  "type": "state"
}
```
##### IMPORTANCE
It is not a major problem because the subsequent state-change message tells us to reset the state for this peer. But it means we are not recording the notify messages as we do not know which peer they came from.

**Comment by thomas-mangin** [comment]
@spakka from the top of my head, this was already fixed on master. If this is not an issue for you, I will be a very lazy bee :bee: and just pretend I did not see this issue  ...  Happy to accept a patch which fixes the problem tho 😁

**Comment by omuravskiy** [comment]
I would also like to point out that this implementation of the "notification" section is conflicting with the previous definition of the "notification" in the exabgp shutdown message.
Both messages have
> "type": "notification"

but in a shutdown message the "notification" is a string:
> "type": "notification",
"notification": "shutdown"

 while in the notification message it is an object:
> "type": "notification",
"notification": {
    "subcode": 5,
    "code": 6,
    "data": "0605"
  }

 This breaks any JSON parser that relies on schema-based parsing.

I'm happy to change either of these to the opposite type in our schema, but I can't have them both :(

**Comment by thomas-mangin** [comment]
🤦‍♂️ thank you for reporting this ... 🤕

**Comment by thomas-mangin** [comment]
@andrekampert thank you for your help - appreciated.
Please keep in mind that 3.4 is a stable branch and I can't change the JSON object in a way which would cause existing code to break. Adding information is fine.

**Comment by andrekampert** [comment]
Thanks for the heads up. I've already changed the structure for the notification message to match the other messages for the sake of consistency, but as this is a breaking change, I'll try another route.

In that case, would it make sense to write the ident parameter as a header field?

**Comment by thomas-mangin** [comment]
> In that case, would it make sense to write the ident parameter as a header field?
Not sure what you mean that this ...

**Comment by thomas-mangin** [comment]
Sure, adding the neighbour structure is not an issue.

**Comment by andrekampert** [comment]
@thomas-mangin Can you please make a new release containing the merged changes to fix this issue?
