### ISSUE TITLE
Is there a single place that shows how to set this up on different systems?

### ISSUE THREAD

**Issue by CodyKochmann** [Exa-Networks/exabgp#764]
A coworker and I have been trying to play with this software and haven't had too much luck getting things to work correctly yet. We've tried on both macOS and CentOS 7 and haven't been able to make things happy. 

We're running on clean VMs that haven't had any modification other than whats needed for bgp operations, have clean fully installed python virtual environments so everything is as python development friendly as possible and yet the package really seems to not like what we're doing. 

So is there a place that just simply shows a demo install on a vanilla system? Or a doc that mentions what tweaks we need to make to various systems? Or even a doc that lists all the things you need set up and running on the system before you get started?

Maybe we're just looking in the wrong place because this repo seems extremely established and it looks like other people aren't having issues setting up instances running this.

Thanks in advance for your help.

**Comment by thomas-mangin** [comment]
please have a look at the wiki which has lots of example for 3.4 (keep in mind that 4.0 syntax is different) ! Good luck !

**Comment by thomas-mangin** [comment]
@CodyKochmann I will close the issue but should you not be able to find what you need on the wiki, please feel free to re-open the thread with some more specific information.
