### ISSUE TITLE
ExaBGP 4 and python 3 support

### ISSUE THREAD

**Issue by chantra** [Exa-Networks/exabgp#768]
Currently, ExaBGP 4 is supporting python 3 and python 2 (even though it should not be relied upon).

> ExaBGP 4.0 and later are targeting python3 when ExaBGP 3.4 and previous versions are python2 applications. At the moment, it is possible to run ExaBGP 4.0 using python2.7 but this backward compatibility should not be relied upon.

While in many cases supporting both version can be straightforward, I believe that for ExaBGP case, supporting py3 only would make things easier has:
* you wont be forced in supporting slight language differences
* bytes vs strings will be much more straightforward
* the event loop could move to a natively supported framework (asyncio) vs building your own
* IP parsing could benefit from ipaddress module which ships by default with py3
* testing also becomes easier

Overall, python 3 is widely deployed in most distros. Python 3.5 supports the new syntactic sugar that makes asyncio easier, adds type hints support.

I appreciate that python 2.7 could be supported, but I think the project would benefit from only supporting 1 python version for simplicity.
Not a bug, but just wanted to raise this in case.

**Comment by thomas-mangin** [comment]
I agree with all point but as said, py3 only support is planned for version 5 .. That said I do not expect 4.0 to be as long lived as 3.x was.

**Comment by chantra** [comment]
yeah, I still think that this may make getting v4 for prime time harder by keeping backward compatibility support because it will need to carry code to handle both versions which is going to cause issue every so often.
