### ISSUE TITLE
Debian 8 build fails on 3.4.21 tests flow.conf and flow-redirect.conf

### ISSUE THREAD

**Issue by Kegeruneku** [Exa-Networks/exabgp#781]
##### ISSUE TYPE
 - Bug Report

##### OS
Build: Debian 9 "stretch"
Target: Debian 8 "jessie"

##### VERSION
Not built yet, but using exabgp-3.4.21.tar.gz as source

##### ENVIRONMENT 
None yet

##### CONFIGURATION
None yet

##### SUMMARY
I am trying to build exabgp using the sources, the sources debian/ directory and pbuilder, and the build fails during the test stage on the flow.conf and flow-redirect.conf tests.

##### STEPS TO REPRODUCE
```
cd $(mktemp -d)
curl -L https://github.com/Exa-Networks/exabgp/archive/3.4.21.tar.gz | tar zvx
cd exabgp-3.4.21
pbuilder --create --distribution jessie
pdebuild
```

##### EXPECTED RESULTS
A debian .deb package is to be created in /var/cache/pbuilder/result/

##### ACTUAL RESULTS
The build crashed: https://gist.github.com/Kegeruneku/eda45e74dda387948b8a7ab523612b62

##### IMPORTANCE
We are trying to build a recent release package to test if a very annoying bug (relative to unexpected route withdrawal during reload) has been solved (we currently use `3.4.13-1~bpo8+1`)

**Comment by Kegeruneku** [comment]
Trying to build the master branch fails on the exact same tests (`conf-flow.conf` and `conf-flow-redirect.conf`), might be an environmental issue maybe ?

**Comment by vincentbernat** [comment]
I didn't have time to investigate the problem with those tests but I also got them. You can just run `pdebuild` with `DEB_BUILD_OPTIONS=nocheck pdebuild` or comment out the test section in `debian/rules` to work around that.

**Comment by thomas-mangin** [comment]
Possible some test are failing - it is often not an issue but due to how the update are encoded you can encode things differently while all valid ...

**Comment by Kegeruneku** [comment]
OK !

@vincentbernat FYI `ifeq (,$(filter nocheck,$(DEB_BUILD_OPTIONS)))` is not present in 3.4.21's debian/rules so I monkey patched mine, I see that the debian/sid branch stops at `3.4.17-3` in the changelog, which branch are the latest 3.4 builds based on ?

**Comment by vincentbernat** [comment]
For Debian, we are now pushing ExaBGP 4. The 3.4 branch on GitHub still has its own `debian/` directory.

**Comment by Kegeruneku** [comment]
OK ! thank you :)

**Comment by thomas-mangin** [comment]
@vincentbernat thank you for you help !
