### ISSUE TITLE
What should a normal exabgp return code be with systemctl stop?

### ISSUE THREAD

**Issue by martbhell** [Exa-Networks/exabgp#788]
##### ISSUE TYPE

 - Bug Report

##### OS

 - CentOS 7.4
 - python2

##### VERSION

```
# exabgp --version
ExaBGP : 3.4.23
Python : 2.7.5 (default, Aug  4 2017, 00:39:18)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Uname  : #1 SMP Thu Jan 4 01:06:37 UTC 2018
```

##### ENVIRONMENT 

```
# exabgp --di

[exabgp.log]
short = true

```

##### SUMMARY

When exabgp service is stopped with systemd then it returns return code 1.

Is return code 1 a normal exit? If it is I can make a PR to update the systemd service file :)

Setting SuccessExitStatus in the systemd service file makes systemd status happy:
 
<pre>
[Service]
SuccessExitStatus=1
</pre>
##### STEPS TO REPRODUCE

systemctl stop exabgp

##### EXPECTED RESULTS

systemctl status says the system OK, not degraded because of a failed service (exabgp)

<pre>
# systemctl status ceph-radosgw@obfusc.service
● ceph-radosgw@obfusc.service - Ceph rados gateway
   Loaded: loaded (/usr/lib/systemd/system/ceph-radosgw@.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2018-02-21 14:23:46 EET; 8min ago
  Process: 14006 ExecStart=/usr/bin/radosgw -f --cluster ${CLUSTER} --name client.%i --setuser ceph --setgroup ceph (code=exited, status=0/SUCCESS)
 Main PID: 14006 (code=exited, status=0/SUCCESS)
</pre>

##### ACTUAL RESULTS

<pre>
# systemctl status exabgp
● exabgp.service - ExaBGP
   Loaded: loaded (/etc/systemd/system/exabgp.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-02-21 14:31:26 EET; 1s ago
     Docs: https://github.com/Exa-Networks/exabgp/wiki
 Main PID: 16938 (exabgp)
   CGroup: /system.slice/exabgp.service
           ├─16938 /usr/bin/python2 /bin/exabgp /etc/exabgp/exabgp.conf
           └─16941 /usr/bin/python -m exabgp healthcheck --config /etc/exabgp/healthcheck_ipv4.conf

# systemctl stop exabgp

# systemctl status exabgp
● exabgp.service - ExaBGP
   Loaded: loaded (/etc/systemd/system/exabgp.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2018-02-21 14:31:45 EET; 1s ago
     Docs: https://github.com/Exa-Networks/exabgp/wiki
  Process: 16938 ExecStart=/bin/exabgp /etc/exabgp/exabgp.conf (code=exited, status=1/FAILURE)
 Main PID: 16938 (code=exited, status=1/FAILURE)
</pre>

**Comment by thomas-mangin** [comment]
Thanks for the report - it should probably not return with 1 (which is a sign of an error) if it was SIGTERM'ed.

**Comment by aabdnn** [comment]
I just noticed this myself, that exabgp exits with code 1 when sent a normal TERM signal (or I press CTRL-C on the keyboard). Under systemd, this is determined to be an abnormal failure, and looks wrong.

**Comment by thomas-mangin** [comment]
On my TODO ..

**Comment by thomas-mangin** [comment]
should be working as requested now.

**Comment by aabdnn** [comment]
Hi Thomas. Thanks for fixing it. I tried to apply this patch to 3.4.26, because we still use 3.4, but it failed to apply. Is the patch only meant to fix the 4.x branch?

**Comment by thomas-mangin** [comment]
Yes the patch will not apply on 3.4 I will backport when I have a little
time. If I closed the issue feel free to reopen it.

**Comment by thomas-mangin** [comment]
backported to 3.4

**Comment by aabdnn** [comment]
Thank you Thomas! We just tested it, and it appears to be exiting correctly with code 0 when sent a TERM signal. Systemd no longer thinks that the service has failed.

**Comment by zxaos** [comment]
I'm still seeing this behaviour on 4.2.1. I originally thought it was healthcheck process related however it still occurs even if the healtcheck is never started. Any ideas?

```
Nov 20 22:05:30 cdn-test1 systemd[1]: Stopping ExaBGP...
Nov 20 22:05:30 cdn-test1 exabgp[28427]: reactor       SIGTERM received
Nov 20 22:05:30 cdn-test1 exabgp[28427]: reactor       scheduling shutdown
Nov 20 22:05:30 cdn-test1 exabgp[28427]: reactor       performing shutdown
Nov 20 22:05:30 cdn-test1 exabgp[28427]: process       terminating process api-internal-cli-d38ef9ca
Nov 20 22:05:30 cdn-test1 systemd[1]: exabgp.service: Main process exited, code=exited, status=1/FAILURE
Nov 20 22:05:32 cdn-test1 systemd[1]: Stopped ExaBGP.
Nov 20 22:05:32 cdn-test1 systemd[1]: exabgp.service: Unit entered failed state.
Nov 20 22:05:32 cdn-test1 systemd[1]: exabgp.service: Failed with result 'exit-code'.
```

**Comment by badrabubker** [comment]
Hello, 
i could still reproduce this on 4.0.8 and exabgp was existing with the status _unknown_.
Looking at the code when receiving SIGTERM or SIGHUP SHUTDOWN was received and shutdown function was called but the return code was never set.
Cheers
