### ISSUE TITLE
IBGP Peering on Loopback addresses?

### ISSUE THREAD

**Issue by SivaKesava1** [Exa-Networks/exabgp#789]
##### ISSUE TYPE
How to write EXABGP config file if the nodes are using ibgp?
##### OS
Ubuntu 14

##### SUMMARY

```
|--------------| 2.0.19.1/24       2.0.19.2/24       |-----------------|
|    Node A    |------------------------------------ |    Node B       |
| lo:1.0.1.1   |                                     |                  |
|--------------|                                      |-----------------|

```
Consider Node A and Node B directly connected with the ip addresses shown above. If we have Node A in Quagga with the configuration as:
```

router bgp 200 
 bgp router-id 172.0.2.1
 network 2.102.0.0/24
 neighbor 2.0.19.2 remote-as 700
 neighbor 2.0.19.2 update-source lo
```

Node B Quagga:

```
router bgp 700
 bgp router-id 2.45.55.5
 neighbor 1.0.1.1 remote-as 200
```

If I am creating the topology in Mininet and then run Quagga service in Node A and if I want to make Node B as exabgp node how should the config look like?
 
I tried 
```
 neighbor 1.0.1.1 {                
    router-id 2.0.19.2;             
    local-address 2.0.19.2;          
    local-as 700;                   
    peer-as 200;         
    api {
         processes [announce-routes1];
        }             
      
}

```
but I get the following error
##### ENVIRONMENT 
16:59:15 | 62     | reactor         | initialising connection to peer-1
16:59:15 | 62     | outgoing-1      | attempting connection to 10.0.2.1:179
16:59:15 | 62     | outgoing-1      | outgoing-1 2.0.19.2-1.0.1.1, closing connection
16:59:15 | 62     | outgoing-1      | connection to 1.0.1.1:179 failed, Could not connect to peer 10.0.2.1:179 ([Errno ENETUNREACH] [Errno 101] Network is unreachable)

How do we write the Exabgp config file for Node B?

**Comment by he32** [comment]
> If I am creating the topology in Mininet and then run Quagga
> service in Node A and if I want to make Node B as exabgp node
> how should the config look like?
>  
> I tried 
> ```
>  neighbor 1.0.1.1 {                
>     router-id 2.0.19.2;             
>     local-address 2.0.19.2;          
>     local-as 700;                   
>     peer-as 200;         
>     api {
>          processes [announce-routes1];
>         }             
>       
> }
> 
> ```

You need an IGP-style route (static, ospf, etc.) to 1.0.1.1,
otherwise exabgp will rightfully complain that 1.0.1.1 is
unreachable.

Regards,

- Håvard

**Comment by thomas-mangin** [comment]
A few things:
 * all IP used must be present and configured on the OS (ExaBGP does not perform any network configuration)
 * the firewall must allow the TCP port 179 connection 
 * the routing between IP must work

**Comment by SivaKesava1** [comment]
Yes, I buy your points, suppose we are reversing the roles and Node A is emulated in Exabgp then will the config look like this?

```
neighbor 2.0.19.2 {                
    router-id 2.0.19.2;             
    local-address **1.0.1.1;**      
    local-as 200;                   
    peer-as 700;         
    api {
         processes [announce-routes1];
        } }
```
Then will the local-address be my loopback address? Assuming we have the ip routing tables configured and met all the conditions @thomas-mangin  mentioned is this the correct config?

**Comment by thomas-mangin** [comment]
in BGP the address on both side are the end points of a TCP connection - they should be reciprocal.
