### ISSUE TITLE
neighbor become flapping 

### ISSUE THREAD

**Issue by treemanzhou** [Exa-Networks/exabgp#795]
##### ISSUE TYPE

 - Bug Report

##### OS

CentOS release 6.7 (Final)
##### VERSION

```
ExaBGP : 4.0.2-1c737d99
Python : 2.7.12 (default, Mar  2 2017, 10:26:20)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]
Uname  : Linux l20-253-111 2.6.32-504.30.3.el6.x86_64 #1 SMP Wed Jul 15 10:13:09 UTC 2015 x86_64
Root   : /usr/local
```

##### ENVIRONMENT 

```
[exabgp.daemon]
daemonize = true
pid = '/var/run/exabgp.pid'
user = 'root'

[exabgp.log]
destination = '/var/log/exabgp.log'
```

##### SUMMARY

the router 's neighbor the exabge  become flapping when i run segmentrouting  feather in my igp .

router：
RP/0/RSP0/CPU0:Mar 12 14:02:56.520 : bgp[1058]: %ROUTING-BGP-5-ADJCHANGE : neighbor 10.20.200.1 Down - BGP Notification received, invalid length for attribute (VRF: default) (AS: 65000) 
RP/0/RSP0/CPU0:Mar 12 14:03:03.593 : bgp[1058]: %ROUTING-BGP-5-ADJCHANGE : neighbor 10.20.200.1 Up (VRF: default) (AS: 65000) 
RP/0/RSP0/CPU0:Mar 12 14:03:08.661 : bgp[1058]: %ROUTING-BGP-5-ADJCHANGE : neighbor 10.20.200.1 Down - BGP Notification received, invalid length for attribute (VRF: default) (AS: 65000) 
RP/0/RSP0/CPU0:Mar 12 14:03:17.729 : bgp[1058]: %ROUTING-BGP-5-ADJCHANGE : neighbor 10.20.200.1 Up (VRF: default) (AS: 65000) 

exabgp:
14:21:13 | 22138  | welcome       | Thank you for using ExaBGP
14:21:13 | 22138  | version       | 4.0.2-1c737d99
14:21:13 | 22138  | interpreter   | 2.7.12 (default, Mar  2 2017, 10:26:20)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]
14:21:13 | 22138  | os            | Linux 20-200-1 2.6.32-504.30.3.el6.x86_64 #1 SMP Wed Jul 15 10:13:09 UTC 2015 x86_64
14:21:13 | 22138  | installation  |         
14:21:13 | 22138  | cli           | could not find the named pipes (exabgp.in and exabgp.out) required for the cli
14:21:13 | 22138  | cli           | we scanned the following folders (the number is your PID):
14:21:13 | 22138  | cli control   |  - /run/0/
14:21:13 | 22138  | cli control   |  - /run/
14:21:13 | 22138  | cli control   |  - /var/run/0/
14:21:13 | 22138  | cli control   |  - /var/run/
14:21:13 | 22138  | cli control   |  - /run/0/
14:21:13 | 22138  | cli control   |  - /run/
14:21:13 | 22138  | cli control   |  - /var/run/0/
14:21:13 | 22138  | cli control   |  - /var/run/
14:21:13 | 22138  | cli control   | please make them in one of the folder with the following commands:
14:21:13 | 22138  | cli control   | > mkfifo /root/bgp_conn/run/exabgp.{in,out}
14:21:13 | 22138  | cli control   | > chmod 600 /root/bgp_conn/run/exabgp.{in,out}
14:21:13 | 22138  | configuration | performing reload of exabgp 4.0.2-1c737d99
14:21:13 | 22138  | configuration | > process          | 'parsed-route-backend'
14:21:13 | 22138  | configuration | . run              | 'linkstate.py'
14:21:13 | 22138  | configuration | . encoder          | 'json'
14:21:13 | 22138  | configuration | < process          | 
14:21:13 | 22138  | configuration | > neighbor         | '192.168.255.10'
14:21:13 | 22138  | configuration | . local-address    | '10.20.200.1'
14:21:13 | 22138  | configuration | . local-as         | '65000'
14:21:13 | 22138  | configuration | . peer-as          | '65000'
14:21:13 | 22138  | configuration | > family           | 
14:21:13 | 22138  | configuration | . bgp-ls           | 'bgp-ls'
14:21:13 | 22138  | configuration | < family           | 
14:21:13 | 22138  | configuration | > api              | 
14:21:13 | 22138  | configuration | . processes        | '[' 'parsed-route-backend' ']'
14:21:13 | 22138  | configuration | > receive          | 
14:21:13 | 22138  | configuration | . parsed           | 
14:21:13 | 22138  | configuration | . update           | 
14:21:13 | 22138  | configuration | < receive          | 
14:21:13 | 22138  | configuration | < api              | 
14:21:13 | 22138  | configuration | < neighbor         | 
14:21:13 | 22138  | reactor       | new peer: neighbor 192.168.255.10 local-ip 10.20.200.1 local-as 65000 peer-as 65200 router-id 10.20.200.1 family-allowed in-open
14:21:13 | 22138  | reactor       | loaded new configuration successfully
14:21:13 | 22138  | process       | forked process parsed-route-backend

**Comment by thomas-mangin** [comment]
Hello @treemanzhou 

You are not providing your configuration and the output of ExaBGP with the option -d 

I have no idea what route you sent, and what could have gone wrong, but the fact that your router consider one of the route received as invalid.

I can not help you without more information.

**Comment by treemanzhou** [comment]
i added the -d  option  and  there is no detail output  .
here is my command , and the output is the same as before i presented.
./exabgp -d bgp_bgpls.conf

**Comment by thomas-mangin** [comment]
You are still not providing me with what your program generated as command AND the output of exabgp -d .. Therefore I still can not help you.
If there was not detailed output, it probably mean that you are using a packaged version of ExaBGP which is sending the logs to syslog .. if so, please use the latest version from GitHub.

**Comment by treemanzhou** [comment]
Hi thomas  
    i git the latest version  and run  exabgp -d bgp.conf exabgp ,still no detail output ........

![image](https://user-images.githubusercontent.com/20250698/37379531-d1614440-276e-11e8-9e35-e9f17c02d3e3.png)
![image](https://user-images.githubusercontent.com/20250698/37379539-db701682-276e-11e8-9e53-7d4cbb7756a4.png)
![image](https://user-images.githubusercontent.com/20250698/37379546-e7d9df48-276e-11e8-8a60-a0686985bf26.png)

anything else I  can do to fix this  ?

**Comment by treemanzhou** [comment]
[exabgp.log](https://github.com/Exa-Networks/exabgp/files/1813905/exabgp.log)

**Comment by ruissalo** [comment]
Hi @treemanzhou,

What version of IOS XR are you using?

From what I can see the flags the router is sending to ExaBGP are these:
{'E': 0, 'L': 0, 'N': 1, 'P': 0, 'R': 0, 'V': 0, 'RSV': 0}

If those are indeed the flags, then I'm afraid it's an IOS-XR bug, unless my interpretation of the draft is incorrect. Quoting the draft:

```
      SID/Index/Label: according to the V and L flags, it contains
      either:

      *  A 4 octet index defining the offset in the SID/Label space
         advertised by this router using the encodings defined in
         Section 3.1.  In this case the V and L flags MUST be unset.

      *  A 3 octet local label where the 20 rightmost bits are used for
         encoding the label value.  In this case the V and L flags MUST
         be set.
```
In this case ExaBGP complains about the index being only 3 octets long, instead of 4, as it should be because both V and L are unset.

Let me know what the BGP dissector in Wireshark is telling you and I'll check if we're parsing the TLV incorrectly if you're not seeing the same flags and prefix length as I mentioned above(look at the UPDATE message right before the NOTIFICATION sent by ExaBGP)

cheers,
Evelio

**Comment by treemanzhou** [comment]
Hi @ruissalo  
    First thanks for your reply ， The version of my router box is  "Cisco IOS XR Software, Version 
           6.1.4[Default] " . I run segment routing  on  my  production environments.
     As the pcap below . that's might be a bug , can i work around it ?
###########################################

![image](https://user-images.githubusercontent.com/20250698/37450703-e7fb28d2-2869-11e8-905b-591af74f380f.png)

**Comment by thomas-mangin** [comment]
@treemanzhou - I did not write the part of the code .. but .. you could modify the code in`lib/exabgp/bgp/message/update/attribute/bgpls/prefix/srprefix.py` to accept a TLV length <> 4 and see if it works for you.
```
				if len(data) != 4:
					# Cisco IOS XR Software, Version 6.1.1.19I is not
					# correctly setting the flags
					raise Notify(3,5, "SID/Label size doesn't match V and L flag state")
```

**Comment by treemanzhou** [comment]
@thomas-mangin @ruissalo  
             it works !!   really appreciate!  that's great help

**Comment by ruissalo** [comment]
thank you @thomas-mangin :)

**Comment by thomas-mangin** [comment]
@ruissalo no - thank YOU - for helping 👍 but let's end the bromance here 🤣
