### ISSUE TITLE
empty pipe on subprocess restart

### ISSUE THREAD

**Issue by chantra** [Exa-Networks/exabgp#811]
##### Summary

Some explaination is available here: https://gitter.im/Exa-Networks/exabgp?at=5ae9fb0cb37eab7d0460f616

> @thomas-mangin actually, I have some racy condition where it may help....
basically, the subprocess dies (for whatever reason) while exabgp was still answering to a command with a lot of content (say "show adj-rib out extensive" with many routes). Upon restart of the subprocess, the stdin pipe is going to be filled/filling up with the answers from the previous command. Given that the rest of the program assumes an interaction of sending/recving command behind a lock, so everything being sequential, this messes everything up because essentially the first command would read the remaining content from the command before dying until it reads done/error, the second command would read the reply of the first command, the 3rd of the 2nd ...
one of the idea is to bootstrap the subprocess with a "version" command and read from the pipe until we see somehting that starts with "exabgp "

##### OS

```
Linux CentOS 7

```

##### Version

```
ExaBGP : 4.0.2-1c737d99
Python : 2.7.11
Uname  : 4.6
```

##### Steps to reproduce

* exabgp spin up subprocess
* subprocess triggers a command with a lot of outputs (such as "show adj-rib out extensive" with a lot of routes)
* subprocess dies just after sending the command and before finishing reading ALL the content in the pipe
* exabgp restarts the subprocess
* exabgp may still send data to the pipe from the previous command
* the newly restarted subprocess will get the content from the old command the next time it reads from the pipe. Say the command "version" is sent, the next time the subprocess access the pipe, it will get the old content form "show adj-rib out extensive" which has not been read yet.

One way to solve this is to empty the pipe upon starting up. This involved playing with select and non-blocking file as well as potentially allowing some seconds to pass before we can be sure that exabgp will not write more content to the pipe from older commands.

**Comment by thomas-mangin** [comment]
Now eating all potential left over data before issuing a command

**Comment by chantra** [comment]
Nice. Iirc in our experiments, we had to handle timing out. The issue is that you may empty the pipe but exabgp will continue writing to it until the command is over. I can share the code that we used to work around this from the process side. Cc @newEZ

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chantra** [comment]
Here is what we do from the subprocess side
```python
def empty_stdin_buffer(stdin_timeout):	
    """Discard garbage in previous stdin buffer, called when process restart"""	
    orig_fl = fcntl.fcntl(sys.stdin, fcntl.F_GETFL)	
    fcntl.fcntl(sys.stdin, fcntl.F_SETFL, orig_fl | os.O_NONBLOCK)	
	
    buffer = ''	
    while True:	
        r, _, _ = select.select([sys.stdin, ], [], [], stdin_timeout)	
        if not r:	
            break	
        else:	
            buffer += sys.stdin.read()	
	
    fcntl.fcntl(sys.stdin, fcntl.F_SETFL, orig_fl)	
    return buffer	

```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thomas-mangin** [comment]
8dab8c55660d902a9ebe5af7b550d0a9915cfef8 should be what was needed.

**Comment by chantra** [comment]
We took the timeout approach as a middle ground to ensure the pipe is not being written to by exabgp for a previous command and not having to care about handling potentially multiple answers being written back to the pipe.
I think the marker are optional though. Don’t they only get written when you tell exabgp to ack messages? Doesn’t your code work only when tracking is set and will block otherwise?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
