### ISSUE TITLE
String representation of extended communities occasionally empty

### ISSUE THREAD

**Issue by mwichtlh** [Exa-Networks/exabgp#825]
##### Summary

When dumping messages in JSON format, the string representation of extended communities is occasionally empty.

```
"extended-community": [ { "value": 615035021822126, "string": "target:12127:2222" }, { "value": 217861631974049025, "string": "" } ]
```

##### OS

```
Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64
```

```
Linux <XXX> 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 GNU/Linux
```

##### Version

```
ExaBGP : 4.0.6-daa3d6ba
Python : 2.7.9 (default, Jun 29 2016, 13:08:31)  [GCC 4.9.2]
Uname  : Linux <XXX> 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64
Root   : /usr/local
```

##### Installation

```
git clone && python setup.py (if I remember correctly).
```

##### Environment 

```
[exabgp.api]
encoder = text
respawn = false

[exabgp.daemon]
user = 'exabgp'
```

##### Configuration

```
process log-routes {
  run bash -c 'cat >> /home/<XXX>/bgp.log';
  encoder json;
}
neighbor <XXX> {
  router-id <XXX>;
  local-address <XXX>;
  local-as <XXX>; # IGP, local and peer AS are the same
  peer-as <XXX>;
  hold-time 240;
  adj-rib-in false;
  capability {
    add-path receive;
  }
  api {
    processes [log-routes];
    neighbor-changes;
    receive {
      parsed;
      update;
    }
  }
}

```

##### Program output

I have a huge dump from which I extracted the debug and json information. The contained data is customer sensitive, so I would like to share the data privately. Feel free to provide a mail address in the comments where I can send the relevant information.

##### Steps to reproduce

I haven't found a way to reproduce the bug up to now. It is probably related to some multithreading or timing issue. I guess, this is triggered by the if statement in lib/exabgp/bgp/message/update/attribute/community/extended/community.py, line 93. However, my knowledge of the sources is not deep enough to further debug this.

```
        def json (self):
                h = 0x00
                for byte in self.community:
                        h <<= 8
                        h += ordinal(byte)
                s = self.klass.__repr__(self) if self.klass else ''
                return '{ "value": %s, "string": "%s" }' % (h,s)
```

##### Importance

This bug is affecting our productive environment because we are relying on the decoded string representation for further processing. We could decode the  community from the value field ourselves, but would prefer a proper solution in the ExaBGP code base.

**Comment by thomas-mangin** [comment]
Hi @mwichtlh,

Please tell me how this particular number should be represented as it is not not any of the usual suspect and do no know how to decode it, hence why I always provide the value.

**Comment by thomas-mangin** [comment]
Looking at https://www.iana.org/assignments/bgp-extended-communities/bgp-extended-communities.xhtml I can not see how 0x306000000000501 should be decoded.
