### ISSUE TITLE
Not able to install ExaBGP on Ubuntu 16.04

### ISSUE THREAD

**Issue by prtomasi** [Exa-Networks/exabgp#830]
Hello, 

Installation on Ubuntu 16.04 gave me errors.
I've followed the instructions from https://fastnetmon.com/docs/exabgp_integration/
In the last step it showed me these errors:

root@fastnetmon:/etc# env exabgp.daemon.user=root exabgp.daemon.daemonize=true exabgp.daemon.pid=/var/run/exabgp.pid exabgp.log.destination=/var/log/exabgp.log exabgp /etc/exabgp_blackhole.conf
**exabgp: 20045  configuration environment file missing
exabgp: 20045  configuration generate it using "exabgp --fi > /usr/local/etc/exabgp/exabgp.env"**
root@fastnetmon:/etc#

root@fastnetmon:/etc# uname -a
Linux fastnetmon 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

root@fastnetmon:/etc# exabgp --version
ExaBGP : 3.4.20
Python : 2.7.12 (default, Nov 20 2017, 18:23:56)  [GCC 5.4.0 20160609]
Uname  : #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017

##### Environment 
the command showed an empty result:

root@fastnetmon:/etc# exabgp --di
root@fastnetmon:/etc#

##### Program output
no configuration file provided

The configuration file is located at /etc/exabgp_blackhole.conf
What did I miss?

**Comment by thomas-mangin** [comment]
@prtomasi could you please ask this on the fastnetmon issue tracker. I can not really help you here.

For information:
```
exabgp: 20045 configuration environment file missing
exabgp: 20045 configuration generate it using "exabgp --fi > /usr/local/etc/exabgp/exabgp.env"
```

Is not an error just a warning and you could get rid of it doing what it suggests.

**Comment by prtomasi** [comment]
Thanks, I will annoy Pavel Odintsov.

xD
