### ISSUE TITLE
Check for sub-call data consumption in node.py bgp-ls module seems off

### ISSUE THREAD

**Issue by he32** [Exa-Networks/exabgp#831]
##### Summary
The error check for "does sub-call consume data" in the bgp-LS node.py file
looks a bit strange.  The code says:

``` 
                values = data[13: 13 + node_length]

                node_ids = []
                while values:
                        # Unpack Node Descriptor Sub-TLVs
                        node_id, left = NodeDescriptor.unpack(values, proto_id)
                        node_ids.append(node_id)
                        if left == data:
                                raise RuntimeError("sub-calls should consume data")
                        values = left
```
I would have thought the test should be `if left == values:` instead?

##### Version
Looking at 4.0.1-4501ddf3

##### Steps to reproduce
Code inspection.

##### Importance
Not very...  Would like to know if I read this correctly, though.

**Comment by thomas-mangin** [comment]
@ruissalo do you have time to comment ?

**Comment by he32** [comment]
> @ruissalo do you have time to comment ?

BTW, I think I found another instance of the same pattern, I'll
see if I can re-locate it...

- Håvard

**Comment by thomas-mangin** [comment]
@he32 thanks for the code review 👍

**Comment by he32** [comment]
And ... the other occurrance I found is in prefixv4.py, where the code says:
```
			if tlv_type == 256:
				values = tlvs[4: 4 + tlv_length]
				local_node = []
				while values:
					# Unpack Local Node Descriptor Sub-TLVs
					# We pass proto_id as TLV interpretation
					# follows IGP type
					node, left = NodeDescriptor.unpack(values, proto_id)
					local_node.append(node)
					if left == tlvs:
						raise RuntimeError("sub-calls should consume data")
```
and that last test should probably be `if left == values:`.

**Comment by ruissalo** [comment]
+1 
it's a bug indeed. Could you pls send the patch? Otherwise I'll do it this weekend. Ideally we should write a test for this ;(

thank you!

**Comment by he32** [comment]
I created pull request #834 for this.
No test for what would happen if sub-calls don't consume data, though.
