### ISSUE TITLE
Understanding API command 'announce|withdraw attribute' for vpn families

### ISSUE THREAD

**Issue by adrian62** [Exa-Networks/exabgp#850]
##### Summary
Announce attribute syntax is useful when large numbers of routes share attributes and improve performance by obviating the need to parse the common attributes for each route.
However, this syntax appear to treat fields like route-distinguisher or labels as attributes, when in fact they aren't. They are part of the NLRi information of the update.

##### OS

```
Linux Ubuntu 16.04.2 LTS
```

```
Linux afx1 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

##### Version

```
ExaBGP : 3.4.26
Python : 2.7.12 (default, Dec  4 2017, 14:50:18)  [GCC 5.4.0 20160609]
Uname  : #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017
```

##### Installation

```
standalone install
```

##### Environment 

```
[empty]
```

##### Configuration

```
group EXA_AFX1 {
        local-as 100;
        peer-as 100;
        hold-time 90;
        adj-rib-out false;
        router-id 10.0.99.11;
        family {
          ipv4 unicast;
          ipv4 mpls-vpn;
        }
        local-address 10.0.99.11;
#
        process received-routes {
            run /etc/afx/testAPIattr/attr.py;
        }
        neighbor 198.18.0.5 {
                description "listening for unicast updates";
        }
        neighbor 198.18.0.1 {
                description "listening for vpn updates";
        }

}
```

##### Program output
Below is the log of a successful command using the 'attribute' syntax for 2 VPN paths. However, this syntax only works if all paths have the same rd, next-hop and labels.
This also affects labeled-unicast AFs because the only paths that can be grouped using it are the ones with a common label. If label per prefix is used (for good reasons) all the routes with common attrbutes cannot be combined --and often there are a lot of common  attrbutes: communities, AS-paths etc).
Is lumping in the NLRI fields (except for prefix) with the attributes the expected behavior? Would it be possible to alter it allowing the NLRI fields to be specified along with each prefix?
Something along the lines of:
'''announce attribute origin incomplete next-hop self nlri 1.2.3.4/32 rd 100:2 label 200300 nlri 5.6.7.8/32 rd 200:4 label 400600 '''

```
Oct 03 10:58:17 afx1 exabgp[1388]: Wed, 03 Oct 2018 10:58:17 | INFO     | 1388   | processes     | Command from process received-routes : announce attribute origin incomplete rd 100:2 label 200300 next-hop self nlri 1.2.3.4/32 5.6.7.8/32
Oct 03 10:58:17 afx1 exabgp[1388]: Wed, 03 Oct 2018 10:58:17 | INFO     | 1388   | reactor       | Route added to neighbor 198.18.0.1 local-ip 10.0.99.11 local-as 100 peer-as 100 router-id 10.0.99.11 family-allowed in-open, neighbor 198.18.0.5 local-ip 10.0.99.11 local-as 100 peer-as 100 router-id 10.0.99.11 family-allowed in-open : 1.2.3.4/32 next-hop 10.0.99.11 origin incomplete
Oct 03 10:58:17 afx1 exabgp[1388]: Wed, 03 Oct 2018 10:58:17 | INFO     | 1388   | reactor       | Route added to neighbor 198.18.0.1 local-ip 10.0.99.11 local-as 100 peer-as 100 router-id 10.0.99.11 family-allowed in-open, neighbor 198.18.0.5 local-ip 10.0.99.11 local-as 100 peer-as 100 router-id 10.0.99.11 family-allowed in-open : 5.6.7.8/32 next-hop 10.0.99.11 origin incomplete
Oct 03 10:58:18 afx1 exabgp[1388]: Wed, 03 Oct 2018 10:58:18 | INFO     | 1388   | reactor       | Performing dynamic route update
Oct 03 10:58:18 afx1 exabgp[1388]: Wed, 03 Oct 2018 10:58:18 | INFO     | 1388   | reactor       | Updated peers dynamic routes successfully
```

##### Steps to reproduce

```
Any syntax attempting to put NLRI fields next to the prefix give an error or crash.
```

##### Importance

```
Performance enhancing feature is essential in order to be able to use the product in an environment with a lot of routes.
```

**Comment by adrian62** [comment]
Just a follow up, when large numbers of routes share an RD and Label the presently-available attribute syntax can still be useful for VPN AFs. But, there may be a defect in the way the label field is treated, because it will ignore it. Without a label a VPN update is not valid.
In the example below 2 routes are announced on the API using the attribute syntax. The command is accepted by the API but the log shows that the label is ignored; the result being that the rotes aren't actually announced. Incidentally, the label is accepted on withdrawing
using the attribute syntax.
'''Oct 08 08:56:39 afx1 exabgp[1165]: Mon, 08 Oct 2018 08:56:39 | INFO     | 1165   | processes     | Command from process received-routes : announce attribute route-distinguisher 63333:100 label [ 110 ] next-hop 10.0.99.12 origin igp as-path [100, 500] local-preference 100 extended-community 0:0 originator-id 10.0.99.12 nlri 128.0.64.0/18 128.0.0.0/18
Oct 08 08:56:39 afx1 exabgp[1165]: Mon, 08 Oct 2018 08:56:39 | INFO     | 1165   | reactor       | Route added to neighbor 198.18.0.2 local-ip 10.0.99.11 local-as 100 peer-as 100 router-id 10.0.99.11 family-allowed in-open : 128.0.64.0/18 next-hop 10.0.99.12 origin igp as-path [ 100 500 ] local-preference 100 originator-id 10.0.99.12 extended-community target:0:0.0.0.0
Oct 08 08:56:39 afx1 exabgp[1165]: Mon, 08 Oct 2018 08:56:39 | INFO     | 1165   | reactor       | Route added to neighbor 198.18.0.2 local-ip 10.0.99.11 local-as 100 peer-as 100 router-id 10.0.99.11 family-allowed in-open : 128.0.0.0/18 next-hop 10.0.99.12 origin igp as-path [ 100 500 ] local-preference 100 originator-id 10.0.99.12 extended-community target:0:0.0.0.0'''

**Comment by thomas-mangin** [comment]
Thank you for the information - I will try to see why this is in the next few days.

**Comment by adrian62** [comment]
Any chance looking at this?

**Comment by thomas-mangin** [comment]
Sorry for the delay.

**Comment by thomas-mangin** [comment]
Sorry for the time it took.
