### ISSUE TITLE
no multiple sources/destinations with flowspec since 3.1

### ISSUE THREAD

**Issue by arnevt** [Exa-Networks/exabgp#851]
##### Summary
flowspec does not allow anymore to send multiple sources/destinations in 1 update/flow, although we used this in 3.1 and our juniper MX"es accepted those flows

in 3.1 this was still possible, somewhere in 3.2 we found suddenly in lib/exabgp/configuration/ancient.py a rule reporting "Flow can only have one source" (same for destinations).
In 4.X this code disappeared and we don't get any error anymore, but only 1 source and/or destination is sent via bgp

##### OS
debian 9.4

```
Linux
```

```
Linux ***** 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u5 (2018-09-30) x86_64 GNU/Linux
```

##### Version
```
ExaBGP : master-4a0689d013af7a0117209d5c1acb5639e36d4777
Python : 3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]
Uname  : ******* 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u5 (2018-09-30) x86_64
Root   : /usr/local/exabgp-git
```

##### Installation
```
working in git source directory
```

##### Environment 

```
empty output
```

##### Configuration
```
                route brute-force-SSH {
                        match {
                                source 1.2.3.4/32;
                                source 5.6.7.8/32;
                                destination-port =22;
                        }
                        then {
                                discard;
                        }
                }

```

##### Program output
```
Fri, 05 Oct 2018 14:59:53 | ERROR    | 76637  | configuration | Problem with the configuration file, no change done
Fri, 05 Oct 2018 14:59:53 | ERROR    | 76637  | configuration | 
Fri, 05 Oct 2018 14:59:53 | ERROR    | 76637  | configuration | syntax error in section match
Fri, 05 Oct 2018 14:59:53 | ERROR    | 76637  | configuration | line 22: source 1.2.3.4/32 ;
Fri, 05 Oct 2018 14:59:53 | ERROR    | 76637  | configuration | 
Fri, 05 Oct 2018 14:59:53 | ERROR    | 76637  | configuration | Flow can only have one source


```

##### Steps to reproduce

```
add a flow (like above) in the flow section, with multiple sources
```

##### Importance
```
If we want to upgrade from 3.1 to 3.4 or 4.0 we must expand all our defined flows and change or MO, no impact yet
```

**Comment by thomas-mangin** [comment]
I will have to check if my current understanding of the RFC is correct. Many labs have been performed with ExaBGP to test interoperability and this is a surprise to me.

**Comment by arnevt** [comment]
I understand what you are saying, off course lab test will not have failed because this "simplification" (only 1 source and only 1 destination) will be allowed by all vendors.

also, this change was also noticeable between 3.1 and 3.4 (but we never gave it any attention, so kept running 3.1, until now we really want to upgrade)

Please keep me posted, I will also reread the rfc from my side
