### ISSUE TITLE
Can't find conf.ini in the root path 

### ISSUE THREAD

**Issue by donudi** [Exa-Networks/exabgp#857]
Hi,

Sorry, I'm quite new to exabgp. and I need your help to start discovering it. 
I'm running Ubuntu 18 in VMware, and now I have installed exabgp using pip3. All process went well so far, then, I started to configure BGP information which should be in a file called "confi.ini", but the problem is I couldn't find the file itself.

exabgp info
-------------
root@osboxes:-# exabgp -version
ExaBGP : 4.0.8-793a2931
Python : 3.6.6
Uname : linux osboxes 4.15.0-36-generic #39-Ubuntu SMP mon Sep 24 16:19:09 UTC 2018 X86_64
Root : /usr/local

root@osboxes:-# exabgp --di   // The output is empty 

root@osboxes:-# exabgp -d
no configuration file provided 

Thanks in advance.
Cheers.

**Comment by thomas-mangin** [comment]
`exaBGP --help` will show where the file should be created. It will run without it.
