### ISSUE TITLE
Cannot get MD5 authentication working (v 3.4.21 on FreeBSD)

### ISSUE THREAD

**Issue by Phenomanan** [Exa-Networks/exabgp#859]
##### Summary
I'm having trouble getting md5 authentication to work with my BIRD router, with the config/env pasted below. Note that everything works fine if I simply remove the "md5" field from exaBGP and "password" field from BIRD, all the routes come in and everything, which is why I'm certain that this part is the only issue... however when trying to use md5 exaBGP eventually fails to bind on the IP/port.

Thank you

##### OS
FreeBSD 11.1

##### Version
ExaBGP **3.4.21** (Edited - incorrectly listed 3.4.25 at first...)

##### Installation
Latest FreeBSD package (installed via pkg install)

##### Environment 
exabgp --di output is **empty**. Actually, all exabgp terminal commands, including the debug ones don't seem to work on freebsd, but worked when I tested on redhat. FreeBSD also can't seem to run exabgp on a conf file like "exabgp /usr/local/etc/exabgp/exabgp_second.conf", I have to just have the one exabgp.conf and start the service. Must just be a difference due to OS? Anyway we ultimately do need it working on FreeBSD, as much as it seems to work better on rhel

Here is the exabgp.env file though:

```
[exabgp.api]
encoder = json
highres = false
respawn = false
socket = ''

[exabgp.bgp]
openwait = 60

[exabgp.cache]
attributes = true
nexthops = true

[exabgp.daemon]
daemonize = false
drop = true
pid = '/var/run/exabgp/exabgp.pid'
user = '_bgpd'

[exabgp.log]
all = true
configuration = false
daemon = true
destination = '/tmp/exabgp.log'
enable = true
level = INFO
message = false
network = true
packets = false
parser = false
processes = true
rib = false
routes = false
short = false
supervisor = true
timers = false

[exabgp.pdb]
enable = false

[exabgp.profile]
enable = false
file = ''

[exabgp.tcp]
acl = false
bind = '10.30.166.13'
delay = 0
```

##### Configuration

```
neighbor 10.25.80.78 {
        description "Virtual BIRD router for testing";
        router-id 10.30.166.13;
        local-address 10.30.166.13;
        local-as 5001;
        peer-as 5001;
        md5 "poweroverwhelming";

        capability {
                graceful-restart;
        }

        process announce {
                run /usr/local/etc/exabgp/announcer.run;
                encoder text;
        }
}
```

And here is the relevant bit from bird.conf if it helps:

```
protocol bgp exaBGP {
        description "FreeBSD with ExaBGP";
        strict bind on;
        ipv4 { import all; export all; };
        ipv6 { import all; export all; };
        flow4 { import all; export all; };
        flow6 { import all; export all; };
        source address 10.25.80.78;
        local 10.25.80.78 as 5001;
        neighbor 10.30.166.13 as 5001;
        password "poweroverwhelming";
}
```

##### Program output

exabgp: 80376  reactor       New peer setup: neighbor 10.25.80.78 local-ip 10.30.166.13 local-as 5001 peer-as 5001 router-id 10.30.166.13 family-allowed in-open
exabgp: 80376  configuration Loaded new configuration successfully
exabgp: 80376  reactor       Can not bind to 10.30.166.13:179, you may need to run ExaBGP as root
exabgp: 80376  reactor       unset exabgp.tcp.bind if you do not want listen for incoming connections
exabgp: 80376  reactor       and check that no other daemon is already binding to port 179

Again, if I remove the passwords, the last three lines do not show up and the routes make it into 10.25.80.78... please advise

##### Importance

Testing this with BIRD routers for now, but ultimately going to be used with real routers in our environment, which will of course need to be md5 protected. Honestly the rest of the setup has been really smooth, mostly able to sort out any other hiccups from the Wiki or other closed issues, this is the only one remaining, but it's kind of a big one.

**Comment by thomas-mangin** [comment]
Hello,

I only support fixes / bugs on the latest stable and development version and code - and for the code I wrote. 

I did not add MD5 support for FreeBSD and there is some kernel magic to perform to make it work so I am sorry but I can not help.

**Comment by Phenomanan** [comment]
Thanks for the quick response. And gotcha... first thing I'll do is upgrade to 3.4.25 and see if it helps. Other than that, would you be able to point me in the right direction as to how I can start debugging the md5 authentication? If not, I understand.

**Comment by thomas-mangin** [comment]
I am working with OSX and Ubuntu .. I am a passable sysadmin with Linux but no much BSD skills here :-(

**Comment by Phenomanan** [comment]
Gotcha, no problem. Will try to install and test with a non-BIRD router to see whether maybe the problem was just from BIRD's side and not exaBGP. Will update here if that happens to be the case. Thanks!

**Comment by Phenomanan** [comment]
Tested with a different router (which had better logging than BIRD) - confirmed that the md5 is never being sent, so definitely an issue with the "md5" argument in ExaBGP 3.4.21 for FreeBSD. Hopefully the issue does not exist on 3.4.25. Closing this thread now though.
