### ISSUE TITLE
FlowSpec traffic-rate dosen't support 2-bytes as？

### ISSUE THREAD

**Issue by aimuwai** [Exa-Networks/exabgp#863]
Hi，developers of exabgp
When I use the rate-limit function of flowspec，it dosen't support set a 2-byte as.
Is there any plan to support it?
Thank you!

Configuration example:
then {
                // one action only
                rate-limit <ratelimit>;

According to RFC 5575:
        +--------+--------------------+--------------------------+
        | type   | extended community | encoding                 |
        +--------+--------------------+--------------------------+
        | 0x8006 | traffic-rate       | 2-byte as#, 4-byte float |
        | 0x8007 | traffic-action     | bitmask                  |
        | 0x8008 | redirect           | 6-byte Route Target      |
        | 0x8009 | traffic-marking    | DSCP value               |
        +--------+--------------------+--------------------------+

   Traffic-rate:  The traffic-rate extended community is a non-
      transitive extended community across the autonomous-system
      boundary and uses following extended community encoding:
         The first two octets carry the 2-octet id, which can be
         assigned from a 2-byte AS number.  When a 4-byte AS number is
         locally present, the 2 least significant bytes of such an AS
         number can be used.  This value is purely informational and
         should not be interpreted by the implementation.

**Comment by thomas-mangin** [comment]
Hello @aimuwai, you pointed the exact right part of the RFC, the last sentence being:
```
This value is purely informational and should not be interpreted by the implementation.
```
So the two bytes are "padding" and are suggested to be based on the ASN. WHY? I have no idea, but clearly, this is not a MUST requirement of the specification and even worse, there is a should - given lower cased - saying that implementation should ignore it !

As this value can not be relied on. Our code contains this:

```
def discard (tokeniser):
	# README: We are setting the ASN as zero as that what Juniper (and Arbor) did when we created a local flow route
	return ExtendedCommunities().add(TrafficRate(ASN(0),0))
```

So why would you want to specify the ASN ?

**Comment by thomas-mangin** [comment]
For clarity, our code set the ASN to zero when creating this extended community, which is what Juniper, who authored the RFC, did with their early implementations.

**Comment by aimuwai** [comment]
Hi, Thomas
Thanks for your reply.
I have no use of this ASN. I ask this because RFC says that and I want to know why exabgp dosen't support to specify it. 
: )

**Comment by thomas-mangin** [comment]
ok, in that case I will close the issue :-)

**Comment by eitanick** [comment]
Hey Thomas,
I have a private project in which I've been trying to configure the AS value of traffic rate.
Luckily this record existed and luckily I found it:)
I am using your EXABGP version 3.4.23, and was wondering whether there has been an update regarding this.
Do you know of any way of setting the router AS through the exabgp.conf?
Communities: traffic-rate:0:1000 is the line I want to set.
thanks,

**Comment by thomas-mangin** [comment]
Can you please open a new issue for that question ( you can link to this one ) but your question is not related to this thread.
