### ISSUE TITLE
exabgp 4.0.10 freezes after announcing more than ~12600 with super-smash-brogp

### ISSUE THREAD

**Issue by aecro** [Exa-Networks/exabgp#867]
##### Summary

When using super-smash-brogp, exabgp freezes after announcing ~12600 prefixes to my Cisco router. The way the script works is, after startup it does a default announce of 10000 random prefixes, then enters a loop which announces 5000-7000 random prefixes and then withdraws 1% of total announced prefixes. All those values are configurable. At the end I included a table with tests after tuning those numbers. The outcome varies a bit, but not much.
When exabgp freezes, the only way to stop it is sending it a kill -9.
```
19:23:36 | 16181  | reactor       | ^C received
19:23:36 | 16181  | reactor       | performing shutdown
19:24:56 | 16181  | reactor       | SIGTERM received
19:24:56 | 16181  | reactor       | scheduling shutdown
```
Those have no effect.

I included the stdout flushing fix that @thomas-mangin submitted to the super-smash-brogp devs.

I also did a test announcing 10.0.0.0/8 next-hop self split /24, which successfully announced all 65536 prefixes.

##### OS

```
Linux hostname 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

##### Version

```
ExaBGP : 4.0.10-a8462350
Python : 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]
Uname  : Linux hostname 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64
Root   : /home/username/.local
```

##### Installation

```
pip3
```

##### Environment 

```
[exabgp.daemon]
user = 'exabgp'
```

##### Configuration

```
process announce-routes {
    run /usr/bin/python2 /home/username/git/super-smash-brogp/ssbgp.py 172.16.0.2 200 config_files/ssbgp/v4_conf.yaml;
    encoder json;
}

neighbor 172.16.0.2 {
    peer-as 100;
    local-as 200;
    local-address 172.16.0.7;
    router-id 172.16.0.7;
    group-updates true;
    hold-time 180;

    family {
        ipv4 unicast;
    }

    capability {
        asn4 enable;
        route-refresh enable;
        graceful-restart 60;
    }

    api {
        processes [ announce-routes ];
    }
}
```

##### Program output

```
19:39:08 | 18867  | configuration | . route            | '71.54.64.0/19' 'next-hop' 'self' 'as-path' '[' '200' '54108' '35760' '28569' '6887' '40643' ']'
19:39:08 | 18867  | api           | route added to neighbor 172.16.0.2 local-ip 172.16.0.7 local-as 200 peer-as 100 router-id 172.16.0.7 family-allowed in-open : 71.54.64.0/19 next-hop self as-path [ 200 54108 35760 28569 6887 40643 ]
19:39:08 | 18867  | process       | responding to announce-routes : done
19:39:08 | 18867  | configuration | . route            | '24.49.185.0/24' 'next-hop' 'self' 'as-path' '[' '200' ']'
19:39:08 | 18867  | api           | route added to neighbor 172.16.0.2 local-ip 172.16.0.7 local-as 200 peer-as 100 router-id 172.16.0.7 family-allowed in-open : 24.49.185.0/24 next-hop self as-path [ 200 ]
19:39:08 | 18867  | process       | responding to announce-routes : done
19:39:08 | 18867  | configuration | . route            | '128.0.168.0/21' 'next-hop' 'self' 'as-path' '[' '200' '10420' '37692' '42871' '4497' '17458' '60497' '2113' '20341' '1417' ']'
19:39:08 | 18867  | api           | route added to neighbor 172.16.0.2 local-ip 172.16.0.7 local-as 200 peer-as 100 router-id 172.16.0.7 family-allowed in-open : 128.0.168.0/21 next-hop self as-path [ 200 10420 37692 42871 4497 17458 60497 2113 20341 1417 ]
19:39:08 | 18867  | process       | responding to announce-routes : done
19:39:08 | 18867  | configuration | . route            | '170.202.244.0/24' 'next-hop' 'self' 'as-path' '[' '200' '20051' '55853' '4444' '15568' '64337' '34571' ']'
19:39:08 | 18867  | api           | route added to neighbor 172.16.0.2 local-ip 172.16.0.7 local-as 200 peer-as 100 router-id 172.16.0.7 family-allowed in-open : 170.202.244.0/24 next-hop self as-path [ 200 20051 55853 4444 15568 64337 34571 ]
19:39:08 | 18867  | process       | responding to announce-routes : done
^C19:41:11 | 18867  | reactor       | ^C received
19:41:11 | 18867  | reactor       | performing shutdown
19:41:11 | 18867  | outgoing-1    | stop, message [shutting down]
19:41:11 | 18867  | outgoing-1    | outgoing-1 172.16.0.7-172.16.0.2, closing connection
19:41:25 | 18867  | reactor       | SIGTERM received
19:41:25 | 18867  | reactor       | scheduling shutdown
Traceback (most recent call last):
  File "/home/username/git/super-smash-brogp/ssbgp.py", line 123, in <module>
[1]    18867 killed     ~/.local/bin/exabgp -d config_files/exabgp/test.conf
    main()
  File "/home/username/git/super-smash-brogp/ssbgp.py", line 117, in main
    available_as_paths, conf['NUM_DIFFERENT_AS_PATHS'], conf['NEXT_HOP'])
  File "/home/username/git/super-smash-brogp/ssbgp.py", line 82, in announce_prefixes
    ' '.join(as_path))
IOError: [Errno 32] Broken pipe
```

##### Steps to reproduce

```
Just run exabgp with the default settings of super-smash-brogb. 
```

##### Importance

```
Just trying to do some load testing with a router, nothing important.
```

##### Additional data
**10000 initial, 5000-7000 each loop, 1% withdrawal each loop**
_(note: withdrawal doesn't matter, because exabgp crashes before the first withdrawal)_
12608 prefixes, BGP using 2435608 total bytes of memory
12616 prefixes, BGP using 2438376 total bytes of memory

**15000 initial, 5000-7000 each loop, 1% withdrawal each loop**
_(note: withdrawal doesn't matter, because exabgp crashes before the first withdrawal)_
12714 prefixes, BGP using 2457088 total bytes of memory
12613 prefixes, BGP using 2437836 total bytes of memory

**1000 initial, 1000 each loop, no withdrawal**
13043 prefixes, BGP using 2520500 total bytes of memory
13048 prefixes, BGP using 2520452 total bytes of memory

**12500 initial, 100 each loop, no withdrawal**
13100 prefixes, BGP using 2530628 total bytes of memory
13100 prefixes, BGP using 2530636 total bytes of memory
_(I noticed after this test, that after it announced 13100, the loop starts again and exabgp says it added 5 more prefixes before stopping, but those didn't reach the router.)_

**Comment by trisight** [comment]
Similar problem we encounted. After announced about 4000 prefixes, my exabgp stopped response, the only way is to restart the program.  It happens every time.

**Comment by thomas-mangin** [comment]
This is a very weird issue and I will need quite some time to figure out what is happening .. Hopefully something to keep me companies over the xmas break.

**Comment by thomas-mangin** [comment]
PS: The patch I wrote is incomplete as there is many print's which are not flushed and I need to redo it.

**Comment by trisight** [comment]
the program blocks in _write function in process.py:
 
`self._process[process].stdin.write(bytes_ascii('%s\n' % string))`


It looks try to set ack to false, everything goes to ok.

**Comment by thomas-mangin** [comment]
Ah ! Yes, there is a difference of API behaviour between 3.4 and 4.0 and the messages need to be asked. Turning it off should fix the issue :-)
