### ISSUE TITLE
[exabgpcli] merge (or not) exabgpcli and exabgpctl

### ISSUE THREAD

**Issue by ahmet2mir** [Exa-Networks/exabgp#871]
Hello Folks,

We intensively use exabgp and everyday we grep/cat/awk/for/touch/journalctl to get which process is present, if the node is up etc.

Sometime we need to debug what's going bad so we did some check to neighbor, check healthcheck etc.

So I create a tool "exabgpctl" which manage exabgp on user/admin side.

https://github.com/ahmet2mir/exabgpctl
https://exabgpctl.readthedocs.io/en/latest/

I works with exabgp < 4 with python 2.7 and exabgp >=4 with python >=3

tested with python 27,34,35,36,37

But I think it will better to merge it to exabgpcli and don't maintain separately from exabgp.

But the CLI interact with the API and this tool only with conf files.

Any thought on this ?

**Comment by thomas-mangin** [comment]
Now on the README, a bit too much code to integrate but once again thanks for your work, I am sure users of ExaBGP will find it useful.
