### ISSUE TITLE
Regression: deleting neighbor from configuration and reloading configuration causes "show neighbor summary" to hang

### ISSUE THREAD

**Issue by longmalx** [Exa-Networks/exabgp#873]
##### Summary
I upgraded my system to 4.0.10 and spotted this regression from 4.0.6:

- Start ExaBGP with 2 neighbors
- Remove one of the neighbors from the configuration
- Reload configuration with SIGUSR1
- Use exabgpcli to run 'show neighbors summary' - this now hangs!

##### OS
CentOS Linux release 7.5.1804 (Core) 
Linux server 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### Version
[root@cms vconsole]# exabgp --version
ExaBGP : 4.0.10-a8462350
Python : 2.7.5 (default, Jul 13 2018, 13:06:57)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Uname  : Linux server 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64
Root   : /usr

##### Installation
RPM compiled with .spec file in repository.

##### Environment 
[exabgp.api]
ack = true
chunk = 1
cli = true
compact = false
encoder = json
pipename = 'exabgp'
respawn = true
terminate = false

[exabgp.bgp]
openwait = 60

[exabgp.cache]
attributes = true
nexthops = true

[exabgp.daemon]
daemonize = false
drop = true
pid = ''
umask = '0137'
user = 'nobody'

[exabgp.log]
all = false
configuration = true
daemon = true
destination = 'stdout'
enable = true
level = INFO
message = false
network = true
packets = false
parser = false
processes = true
reactor = true
rib = false
routes = false
short = false
timers = false

[exabgp.pdb]
enable = false

[exabgp.profile]
enable = false
file = ''

[exabgp.reactor]
speed = 1.0

[exabgp.tcp]
acl = false
bind = ''
delay = 0
once = false
port = 179

##### Configuration
[root@cms vconsole]# cat /etc/exabgp/exabgp.conf 
template {
    neighbor rtbh-provider {
        adj-rib-in false;
        local-as 60000;
        router-id 192.168.0.2;
    }
}
neighbor 1.1.1.1 {
    inherit rtbh-provider;
    peer-as 60001;
}
neighbor 192.168.0.1 {
    inherit rtbh-provider;
    peer-as 60000;
}
[root@cms vconsole]# 

##### Program output
[mdodds@athena longmalx-exabgp]$ ./sbin/exabgp exabgp.conf -d
08:11:35 | 1405   | welcome       | Thank you for using ExaBGP
08:11:35 | 1405   | version       | (detached-2a88e236ecc2dbb09e5c233adf132b042015e75c
08:11:35 | 1405   | interpreter   | 3.4.1 (default, Sep 24 2015, 20:41:10)  [GCC 4.9.2 20150212 (Red Hat 4.9.2-6)]
08:11:35 | 1405   | os            | Linux athena 4.1.13-100.fc21.x86_64 #1 SMP Tue Nov 10 13:13:20 UTC 2015 x86_64
08:11:35 | 1405   | installation  | /homes/mdodds/build/longmalx-exabgp
08:11:35 | 1405   | advice        | environment file missing
08:11:35 | 1405   | advice        | generate it using "exabgp --fi > /homes/mdodds/build/longmalx-exabgp/etc/exabgp/exabgp.env"
08:11:35 | 1405   | cli control   | named pipes for the cli are:
08:11:35 | 1405   | cli control   | to send commands  /homes/mdodds/build/longmalx-exabgp/run/exabgp.in
08:11:35 | 1405   | cli control   | to read responses /homes/mdodds/build/longmalx-exabgp/run/exabgp.out
08:11:35 | 1405   | configuration | performing reload of exabgp (detached-2a88e236ecc2dbb09e5c233adf132b042015e75c
08:11:35 | 1405   | configuration | > neighbor         | '192.168.1.1'
08:11:35 | 1405   | configuration | . local-as         | '64512'
08:11:35 | 1405   | configuration | . peer-as          | '64512'
08:11:35 | 1405   | configuration | . router-id        | '192.168.1.1'
08:11:35 | 1405   | configuration | < neighbor         | 
08:11:35 | 1405   | configuration | > neighbor         | '192.168.1.2'
08:11:35 | 1405   | configuration | . local-as         | '64512'
08:11:35 | 1405   | configuration | . peer-as          | '64513'
08:11:35 | 1405   | configuration | . router-id        | '192.168.1.2'
08:11:35 | 1405   | configuration | < neighbor         | 
08:11:35 | 1405   | reactor       | new peer: neighbor 192.168.1.1 local-ip None local-as 64512 peer-as 64512 router-id 192.168.1.1 family-allowed in-open
08:11:35 | 1405   | reactor       | new peer: neighbor 192.168.1.2 local-ip None local-as 64512 peer-as 64513 router-id 192.168.1.2 family-allowed in-open
08:11:35 | 1405   | reactor       | loaded new configuration successfully
08:11:35 | 1405   | process       | forked process api-internal-cli-674f7a76
08:11:35 | 1405   | reactor       | initialising connection to peer-1
08:11:35 | 1405   | reactor       | initialising connection to peer-2
08:11:35 | 1405   | outgoing-1    | attempting connection to 192.168.1.1:179
08:11:35 | 1405   | outgoing-2    | attempting connection to 192.168.1.2:179
08:11:36 | 1405   | network       | attempting to establish connection
08:11:36 | 1405   | network       | attempting to establish connection
08:11:40 | 1405   | process       | command from process api-internal-cli-674f7a76 : show neighbor summary 
08:11:40 | 1405   | reactor       | async | api-internal-cli-674f7a76 | show neighbor summary
08:11:40 | 1405   | process       | responding to api-internal-cli-674f7a76 : Peer            AS        up/down state       |     #sent     #recvd
08:11:40 | 1405   | process       | responding to api-internal-cli-674f7a76 : 192.168.1.1     64512        down active                0          0
08:11:40 | 1405   | process       | responding to api-internal-cli-674f7a76 : 192.168.1.2     64513        down active                0          0
08:11:40 | 1405   | process       | responding to api-internal-cli-674f7a76 : done
08:11:41 | 1405   | reactor       | SIGUSR1 received
08:11:41 | 1405   | reactor       | scheduling reload of configuration
08:11:41 | 1405   | configuration | performing reload of exabgp (detached-2a88e236ecc2dbb09e5c233adf132b042015e75c
08:11:41 | 1405   | configuration | > neighbor         | '192.168.1.1'
08:11:41 | 1405   | configuration | . local-as         | '64512'
08:11:41 | 1405   | configuration | . peer-as          | '64512'
08:11:41 | 1405   | configuration | . router-id        | '192.168.1.1'
08:11:41 | 1405   | configuration | < neighbor         | 
08:11:41 | 1405   | reactor       | removing peer: neighbor 192.168.1.2 local-ip 10.20.50.77 local-as 64512 peer-as 64513 router-id 192.168.1.2 family-allowed in-open
08:11:41 | 1405   | outgoing-2    | outgoing-2 10.20.50.77-192.168.1.2, closing connection
08:11:41 | 1405   | outgoing-2    | connection to 192.168.1.2 closed
08:11:41 | 1405   | reactor       | peer definition identical, updating peer routes if required for neighbor 192.168.1.1 local-ip None local-as 64512 peer-as 64512 router-id 192.168.1.1 family-allowed in-open
08:11:41 | 1405   | reactor       | loaded new configuration successfully
08:11:41 | 1405   | process       | terminating process api-internal-cli-674f7a76
08:11:41 | 1405   | process       | forked process api-internal-cli-6aefb902
08:11:43 | 1405   | process       | command from process api-internal-cli-6aefb902 : show neighbor summary 
08:11:43 | 1405   | reactor       | async | api-internal-cli-6aefb902 | show neighbor summary
08:11:43 | 1405   | process       | responding to api-internal-cli-6aefb902 : Peer            AS        up/down state       |     #sent     #recvd
08:11:43 | 1405   | process       | responding to api-internal-cli-6aefb902 : 192.168.1.1     64512        down active                0          0
08:11:43 | 1405   | reactor       | async | api-internal-cli-6aefb902 | problem with function
08:11:43 | 1405   | reactor       | async | api-internal-cli-6aefb902 | 'complete'

##### Steps to reproduce
- Start ExaBGP with 2 neighbors
- Remove one of the neighbors from the configuration
- Reload configuration with SIGUSR1
- Use exabgpcli to run 'show neighbors summary' - this now hangs!

##### Importance
It blocks use of 4.0.10

**Comment by longmalx** [comment]
I tracked it down to this pull request added in 4.0.9:
https://github.com/Exa-Networks/exabgp/pull/845

**Comment by longmalx** [comment]
This patch appears to fix the issue:
```
[mdodds@athena longmalx-exabgp]$ git diff
diff --git a/lib/exabgp/reactor/peer.py b/lib/exabgp/reactor/peer.py
index 630c8ff..1700a69 100644
--- a/lib/exabgp/reactor/peer.py
+++ b/lib/exabgp/reactor/peer.py
@@ -149,7 +149,7 @@ class Peer (object):
                        self._neighbor = None
 
        def _stop (self, message):
-               self.generator = False
+               self.generator = None
                if self.proto:
                        self.proto.close('stop, message [%s]' % message)
                        self.proto = None
```

**Comment by thomas-mangin** [comment]
I looked into it and it seems to be fine.
