### ISSUE TITLE
BGP Identifier collision for ranged neighbor

### ISSUE THREAD

**Issue by wenxin-wang** [Exa-Networks/exabgp#877]
##### Summary
If an exabgp instance is configured with ip range as neighbor ip (passive neighbor), when a neighbor tries to connect, the bgp session fails to establish due to "BGP Identifier collision" (need to run with `-d`):

```01:08:27 | 21339  | incoming-3    | << message of type OPEN
01:08:27 | 21339  | incoming-3    | << OPEN version=4 asn=65000 hold_time=180 router_id=172.16.2.2 capabilities=[Multiprotocol(ipv4 unicast,ipv4 multicast,ipv4 nlri-mpls,ipv4 mpls-vpn,ipv4 rtc,ipv4 flow,ipv4 flow-vpn,ipv6 unicast,ipv6 multicast,ipv6 nlri-mpls,ipv6 mpls-vpn,ipv6 flow,ipv6 flow-vpn,l2vpn vpls,l2vpn evpn,bgp-ls bgp-ls,bgp-ls bgp-ls-vpn), Extended Message(65535), ASN4(65000)]
01:08:27 | 21339  | ka-incoming-3 | receive-timer 60 second(s) left
01:08:27 | 21339  | incoming-3    | sending TCP payload ( 109) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 006D 0302 0342 4750 2049 6465 6E74 6966 6965 7220 636F 6C6C 6973 696F 6E2C 2073 616D 6520 726F 7574 6572 2D69 6420 2831 3732 2E31 362E 322E 3229 206F 6E20 626F 7468 2073 6964 6573 206F 6620 7468 6973 2049 4247 5020 7365 7373 696F 6E
01:08:27 | 21339  | incoming-3    | >> NOTIFICATION (2,3,"b'BGP Identifier collision, same router-id (172.16.2.2) on both sides of this IBGP session'")
01:08:27 | 21339  | incoming-3    | peer reset, message [notification sent (2,3)] error[OPEN message error / Bad BGP Identifier / BGP Identifier collision, same router-id (172.16.2.2) on both sides of this IBGP session]
```

##### Environment

exabgp on current git master branch, run directly using `sbin/exabgp`, running on ArchLInux:

```
ExaBGP : master-c7d48c67842740aab787ce7e9a99a0b282ffa797
Python : 3.7.2 (default, Jan 10 2019, 23:51:51)  [GCC 8.2.1 20181127]
Uname  : Linux archie 4.20.8-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 13 00:06:58 UTC 2019 x86_64
Root   : /home/wenxin/Projects/network/exabgp
```

##### Configuration
The crashed exabgp instance
```
neighbor 172.16.2.0/24 {
    router-id 172.16.2.1;
    local-address 172.16.2.1;
    listen 179;
    local-as 65000;
    peer-as 65000;
    passive true;
}
```

The passive neighbor
```
neighbor 172.16.2.1 {
    router-id 172.16.2.2;
    local-address 172.16.2.2;
    local-as 65000;
    peer-as 65000;
}
```

##### Cause

In [`exabgp.reactor.listener.Listener.new_connections(self)`](https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/reactor/listener.py#L212), the `listener` creates a `Peer`, but setting its `router_id` member using `connection.local` (the peer's ip) instead of `connection.peer` (current socket ip).

To fix this issue, change [that line](https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/reactor/listener.py#L212) to

```python
                new_neighbor.router_id = RouterID.create(connection.peer)
```

However, in the ranged neighbor config the user may already have configured `router-id`, we may well use that value (which is implicitly set on [Line 207](https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/reactor/listener.py#L207)), so maybe the following is better:

```python
                if not new_neighbor.router_id:
                                new_neighbor.router_id = RouterID.create(connection.peer)
```

I am wondering if I should add this to https://github.com/Exa-Networks/exabgp/pull/876. Thank you!

**Comment by thomas-mangin** [comment]
Thank you for the patch - much appreciated.
