### ISSUE TITLE
ExaBGP syntax question for encoding TCP flags (bitwise OR / bitwise AND /  bitwise MATCH) in FlowSpec routes

### ISSUE THREAD

**Issue by stowlake** [Exa-Networks/exabgp#883]
##### Summary
Hi,

RFC 5575 (BGP FlowSpec) supports encoding TCP flags for any of following 3 semantics:

1. Bitwise OR 
2. Bitwise AND
3. Bitwise MATCH

I interpret the above as follows (using an example):

1. Bitwise OR [ syn ack] --> means if either SYN or ACK is set in TCP flags field of the packet.

2. Bitwise AND [syn ack] --> means if both SYN and ACK are set in TCP flags field of the packet.

3. Bitwise MATCH [syn ack] --> means if only SYN and ACK are set in TCP flags field of the packet.

So 1 and 2 differ with 3 in the following sense: 

For (1) and (2), other bits in TCP flags field of packet might be set but route would still be a match. But for (3), only the specified flags in the flowspec route should be set in the TCP flags field of the packet.

Assuming above is accurate, could you give an example on how to specify the tcp-flags [] for each of above cases in announce/withdraw commands to exabgp.

For example:

_Command from process announce-routes : announce flow route { match { destination 1.1.1.1/32; protocol [ TCP ]; tcp-flags [ syn  ack  ]; } then { discard; } }__ 

results in following:

_Flow added to neighbor ::ffff:10.128.10.129 local-ip ::ffff:10.128.10.160 local-as 1 peer-as 1 router-id 255.255.255.255 family-allowed in-open : flow destination 1.1.1.1/32 protocol =tcp **tcp-flags [ =syn =ack ]** extended-community rate-limit 0_

I don't know if the above is being advertised for bitwise OR , bitwise AND , bitwise MATCH?

##### OS

```
Linux 3.10.0-862.14.4.el7.ve.x86_64 #1 SMP 2019 x86_64 x86_64 x86_64 GNU/Linux
```

##### Version

```
[root@nsoni-60:Active:Standalone] images # exabgp --version
ExaBGP : 3.4.22
Python : 2.7.5 (default, Mar 20 2019, 16:35:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Uname  : #1 SMP Wed Mar 20 15:57:11 PDT 2019
```

##### Installation

```
Not known
```

##### Environment 

```
Empty
```

##### Configuration

```
group rtdom-0 {
	group-updates;
	neighbor ::ffff:10.128.10.129 {
		local-address ::ffff:10.128.10.160;
		local-as 1;
		peer-as 1;
		family {
			ipv4 unicast;
			ipv4 flow;
			ipv6 unicast;
			ipv6 flow;
		}
		router-id 255.255.255.255;
		hold-time 90;
		capability {
			asn4;
			route-refresh;
		}
	}
	process announce-routes {
		run /usr/bin/python /usr/lib/python2.7/f5/flowspec/exabgp_pipe.py /var/flowspecd/exabgp.pipe.0 > /dev/null 2>&1;
	}
}
```

##### Program output

```

```

##### Steps to reproduce

```

```

##### Importance

```

```

**Comment by stowlake** [comment]
Forgot to mention that I tried following commands (different syntax for tcp-flags) for announce but all of these failed due to ExaBGP parsing:

announce flow route { match { destination 1.1.1.1/32; protocol [ TCP ]; tcp-flags [ syn | ack  ]; } then { discard; } }

 announce flow route { match { destination 1.1.1.1/32; protocol [ TCP ]; tcp-flags [ syn & ack  ]; } then { discard; } }

 announce flow route { match { destination 1.1.1.1/32; protocol [ TCP ]; tcp-flags [ syn && ack  ]; } then { discard; } }
 
announce flow route { match { destination 1.1.1.1/32; protocol [ TCP ]; tcp-flags [ syn || ack  ]; } then { discard; } }

**Comment by thomas-mangin** [comment]
I will need to re-read the code to be able to answer.

**Comment by thomas-mangin** [comment]
From the "comments" in the code :

```
		'destination-port [ =80 =3128 >8080&<8088 ]',
		'packet-length [ >200&<300 >400&<500 ]',
		'tcp-flags [ 0x20+0x8+0x1 #name-here ]  # to check',
 ```

So the "&" can be used to "or" group a number of "and" grouped checks.

**Comment by stowlake** [comment]
Thanks! 

Hmm... I am using version 3.4.22 (which does not seem to have this).

So, before I upgrade to 4.0, please correct me if I am off here:

a) tcp-flags [ syn ack fin]  --> means SYN **or** ACK **or** FIN
b) tcp-flags [ syn+ack] --> means SYN **and** ACK
c) tcp-flags [ syn+ack fin] --> means (SYN **and** ACK) **or** FIN

Also, do we support bitwise MATCH syntax and if so how to specify this syntactically?
Per RFC, for TCP flags, 

m -   Match bit.  If set, this is a bitwise match operation
               defined as "(data & value) == value"; if unset, (data &
               value) evaluates to TRUE if any of the bits in the value
               mask are set in the data.

**Comment by stowlake** [comment]
Also, one more question:

Instead of upgrading to 4.0, is it possible to patch in the specific CL to 3.4.22 based version?

**Comment by thomas-mangin** [comment]
Hi, 

I believe correct answers are:
a) tcp-flags [ syn ack fin] --> means SYN or ACK or FIN
b) tcp-flags [ syn&ack] --> means SYN and ACK
c) tcp-flags [ syn&ack fin] --> means (SYN and ACK) or FIN

This should work with 3.4.

**Comment by stowlake** [comment]
ExaBGP version 3.4.22 does not seem to support syntax for (b) or (c).

Any suggestions?

----
exabgp: Mon, 22 Apr 2019 14:16:14 25114  processes     Command from process announce-routes : announce flow route { match { destination 1.1.1.1/32; protocol [ TCP ]; tcp-flags [ syn&ack  ]; } then { discard; } }\n 
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration loading | route {
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration loading |  match {
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration loading |  destination 1.1.1.1/32;
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration loading |  protocol [ TCP ];
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration loading |  tcp-flags [ syn&ack ];
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration loading |  }
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration loading |  then {
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration loading |  discard;
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration loading |  }
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration loading |  }
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration loading | 
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration parsing | flow          | 'route' '{'
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration parsing | flow-route    | 'match' '{'
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration parsing | flow-match    | 'destination' '1.1.1.1/32' ';'
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration parsing | flow-match    | 'protocol' '[' 'tcp' ']' ';'
exabgp: Mon, 22 Apr 2019 14:16:14 25114  configuration parsing | flow-match    | 'tcp-flags' '[' 'syn&ack' ']' ';'
exabgp: Mon, 22 Apr 2019 14:16:14 25114  reactor       Command could not parse flow in : announce flow route { match { destination 1.1.1.1/32; protocol [ TCP ]; tcp-flags [ syn&ack ]; } then { discard; } }\n

**Comment by thomas-mangin** [comment]
Only to use version 4

**Comment by stowlake** [comment]
OK thanks. I will experiment with ExaBGP version 4 for the above.

Any specific 4.x version that is considered stable enough? I have been using 3.4.22 for sometime and have had no major issues!

Besides this, could you tell if ExaBGP version 4 supports Bitwise MATCH and NOT semantics for TCP flags? I will try it out anyways but would be good to know if you know off top of your head :)

**Comment by thomas-mangin** [comment]
4.0 is nearly ready to replace 3.4. The know issue is that it does not scale as well as 3.4 and the root cause has not yet been identified.

**Comment by thomas-mangin** [comment]
I never use the feature for TCP flags myself, the code should work as AFAIK it was tested/used by some users ...

**Comment by stowlake** [comment]
Thank you for patiently answering the questions.
I will go ahead and close this issue now.

**Comment by stowlake** [comment]
FYI - for 3.4.22 version, I am made a (quick) minor change to allow the following syntax for tcp-flags:

_tcp-flags [ syn & ack ];_

Looking at rest of the code, encoding/decoding NLRI should work (as the AND semantics are similar to other match types - e.g ports / protocols)

So, with this change, it seems to work with ExaBGP as both sender / receiver entities..
need to confirm interoperability with routers (Cisco/Juniper).

**Comment by thomas-mangin** [comment]
Happy to review PR if you already have done the work.

**Comment by stowlake** [comment]
will send the PR soon..
