### ISSUE TITLE
Exabgp API response

### ISSUE THREAD

**Issue by the-c0d3r** [Exa-Networks/exabgp#884]
Currently I have been using exaBGP with the named pipe approach to announce flows to `pipename.in` and reading back the success or error from `pipename.out`. This way of doing things seems very synchronous, and does not seem to be able to handle multiple users, as for each request (announcement) I need to wait for the output (error/success) from output pipe. 

I need to fulfill a few requirements for exaBGP. 

1. Get the status of the request (success/errror)
2. support multiple users in one go

Can anyone please advice me on how to handle multiple requests in one go? Is there any asynchronous approach? The current named pipe output does not contain any identifiable ID to link back to the flow request, so the commands needs to be sequential and synchronous right now. 

If there is no such feature right now, I can put in effort for a **PR** to implement this. Please let me know what do you think about this. 

I'd also like to know if exaBGP can tell me if the flowspec rules I published to exaBGP is propagated to the PE router or not.

**Comment by thomas-mangin** [comment]
The named pipe are for ExaBGP cli and should really not be used by applications. You can find examples on how to use your own application in the [qa folder](https://github.com/Exa-Networks/exabgp/tree/master/qa).

Version 4 is providing an answer to command so this is implemented already, it can however be disabled to allow compatibility with version 3 scripts.

There is indeed no ID from the command and reply as they are expected to be synchronous (some command will return as soon as accepted, so it is sync but not blocking).

Happy to take PR with improvements as long as backward compatibility is kept in mind.

**Comment by thomas-mangin** [comment]
could you please explain why you mean when you ask for "support multiple users in one go" please.

**Comment by the-c0d3r** [comment]
Thanks for the response. I was using the named pipe, since that was the only way I found from the examples which is able to return the status back (success/error). The api examples are all just writing to stdout and do not return a status. 
What I meant for "support multiple users in one go" is to have an API that allows the response status, as well as being asynchornous. Named pipe current is synchronous when returning the success/error status, (as there is no ID to link back to the request) which means my application has to rate limit the requests to go through one by one and wait for the status to be passed back. 
Is the named pipe approach not suitable for this case?
May I also ask if there are any other ways to publish flowspec to exaBGP and get back a status (success/error, etc).

**Comment by thomas-mangin** [comment]
The example were probably written for ExaBGP 3.

**Comment by thomas-mangin** [comment]
ExaBGP returns success / error on the command acceptance, so it is "kind of" async.

**Comment by the-c0d3r** [comment]
I've been using the version 4 apparently, that's probably why there is success/error response. May I ask a few more questions.

Should I be looking out for response or just fire and forget it?
How many flowspec rule announcement per second can exaBGP handle? 
And how long does it take to send flowspec from exaBGP to the router?
Is there any recommended ways to use the API? (apart from using named pipes) The documentations does not have clear picture on how to use the various APIs and how many various APIs are there.

**Comment by thomas-mangin** [comment]
> Should I be looking out for response or just fire and forget it?

You can disable the response. But if the request is correct you should just be able to fire and forget.

> How many flowspec rule announcement per second can exaBGP handle?

I do not have any benchmark. 4 is not as good as 3 for some reason when it comes with high perf. There was a few issues open about this topic, I can just invite you to see what other users said.

> And how long does it take to send flowspec from exaBGP to the router?

It depends on your HW ... From ExaBGP POV it will be very much sub second .. very much so.

> Is there any recommended ways to use the API? (apart from using named pipes) 

If you read the wiki, talk I did or the code there is PLENTY of examples, please have a look.

> The documentations does not have clear picture on how to use the various APIs and how many various APIs are there.

Documentation is indeed lacking at best.

**Comment by the-c0d3r** [comment]
Thank you for the comments. In this case, I'll proceed with the fire and forget approach through the named pipes approach. I'll have to test out the performance soon, so I'll post back the results after that.

**Comment by thomas-mangin** [comment]
@the-c0d3r If you use named pipe you need to read the answer, if you do not everything will stop at around 10k message when the buffer on the pipe fills and becoming blocking.
