### ISSUE TITLE
Introduce new BGP attribute in ExaBGP 3.4

### ISSUE THREAD

**Issue by PHadem** [Exa-Networks/exabgp#889]
I am working on a research problem. I need to introduce a custom BGP attribute similar to MULTI_EXIT_DISC (MED). Can you pls guide me how to achieve this in ExaBGP 3.4
OS: Ubuntu 14 LTS.

Thanks
Hadem

##### OS

```
Linux
MacOS
FreeBSD
Other (please specify)
```

```

```

##### Version

```

```

##### Installation

```
pip
pip with virtualenv
latest OS package
other (please specify)
```

##### Environment 

```

```

##### Configuration

```

```

##### Program output

```

```

##### Steps to reproduce

```

```

##### Importance

```

```

**Comment by thomas-mangin** [comment]
This patch (and the few ones after) should give you a good idea of what is required.

https://github.com/Exa-Networks/exabgp/commit/3761ca81abebabff12045388657abe20ceb9ce59

**Comment by PHadem** [comment]
Thanks Thomas,
This is just what i needed.

Thanks
Hadem

**Comment by thomas-mangin** [comment]
git clone - work into the folder - all should be obvious if you read the code.

**Comment by PHadem** [comment]
Hi Thomas,
I am still facing issue in registering a new BGP attribute in ExaBGP after adding the new attribute as below and following the steps in [3761ca8](https://github.com/Exa-Networks/exabgp/commit/3761ca81abebabff12045388657abe20ceb9ce59)
 lib/exabgp/bgp/message/update/attribute/attribute.py
@@ -60,6 +60,7 @@ class CODE (int):
               COMMUNITY          = 0x08
		# RFC 4456
		ORIGINATOR_ID      = 0x09
		CLUSTER_LIST       = 0x0A  # 10
	+ 	SMITE		   = 0x0B  # 11 
		# RFC 4760
		MP_REACH_NLRI      = 0x0E  # 14	
@@ -85,6 +85,7 @@ class CODE (int):
                        ORIGIN:             'origin',
			AS_PATH:            'as-path',
			NEXT_HOP:           'next-hop',
			MED:                'med',              # multi-exit-disc
		+	SMITE:		    'smite',		# smite
			LOCAL_PREF:         'local-preference',
			ATOMIC_AGGREGATE:   'atomic-aggregate',
Also Changes were made to:
lib/exabgp/bgp/message/update/attribute/attributes.py
@@ -56,6 +56,7 @@ class Attributes (dict):
                Attribute.CODE.ORIGIN:             ('string',  '', 'origin',             '%s',     '%s'),
		Attribute.CODE.AS_PATH:            ('multiple','', ('as-path','as-set','confederation-path','confederation-set'), '%s',     '%s'),
		Attribute.CODE.NEXT_HOP:           ('string',  '', 'next-hop',           '%s',     '%s'),
		Attribute.CODE.MED:                ('integer', '', 'med',                '%s',     '%s'),
	+	Attribute.CODE.SMITE:              ('integer', '', 'smite',              '%s',     '%s'),
		Attribute.CODE.LOCAL_PREF:         ('integer', '', 'local-preference',   '%s',     '%s'),
		Attribute.CODE.ATOMIC_AGGREGATE:   ('boolean', '', 'atomic-aggregate',   '%s',     '%s'),
		Attribute.CODE.AGGREGATOR:         ('string',  '', 'aggregator',         '( %s )', '%s'),

Other required changes have also been incorporated according to patch 3761ca8
However the new attribute is not getting registered. 
My attribute 'smite' is not listed in attributes.py @@ Ln: 301
           if Attribute.registered(aid,flag):
Whereas all the other attributes are listed here. Pls advice.

Thanks
Hadem

**Comment by thomas-mangin** [comment]
@PHadem The simplest way for your test would be to change the ID of MED and use MED to send what you need.

**Comment by thomas-mangin** [comment]
Also as made is a known attribute (please read the BGP spec) you may need to change the MED class to reflect what you want the attribute to be.

**Comment by PHadem** [comment]
Thanks Thomas,

Will try your suggestion.

Thanks

**Comment by PHadem** [comment]
Hi Thomas,

Can you elaborate more on this.
In lib/exabgp/bgp/message/update/attribute/attribute.py
<https://github.com/Exa-Networks/exabgp/commit/3761ca81abebabff12045388657abe20ceb9ce59#diff-d09ef9b20e41faeec8ca6c6017be7008>
@@ -50,6 @@ class CODE (int):
ORIGIN           = 0x01
AS_PATH        = 0x02
NEXT_HOP     = 0x03
MED                = 0x04
LOCAL_PREF         = 0x05
ATOMIC_AGGREGATE   = 0x06

should i change MED to my desired attribute name(e.g SMITE) OR should i
change 0x04 to 0x0B?.
And then what about all the other files which has reference to the MED
attribute?.

Thanks
Hadem

**Comment by thomas-mangin** [comment]
Hadem , 

This will be my last comment on this issue: you should indeed change the code from 0x04 to 0x0B, and change the flag definition in the class

```
class MED (Attribute):
	ID = Attribute.CODE.MED
	FLAG = Attribute.Flag.OPTIONAL 
        ^--- change this to what you want as flags
```

Use 'med' in the configuration like it was your attribute. If it is not is not clear enough, I can only invite you to read the RFC. 

Good luck.
