### ISSUE TITLE
Healthcheck repeats announces

### ISSUE THREAD

**Issue by Marlinc** [Exa-Networks/exabgp#895]
Hey there,

We have noticed that our healthcheck checks keep re-announcing the prefix that they are testing over and over again. This without a change in the up/down status reported by the command run in `cmd`.

This only occurs when running the healthcheck as part of the ExaBGP daemon in a `process` section. Not when manually running the healthcheck (whether through root or the exabgp user). It doesn't appear to be a permission issue as the issue is also happening while using the exabgp user.

I have tested this on the version of ExaBGP as provided by Ubuntu 18.04 LTS 4.0.2-1c737d99 and the latest stable release 4.0.10

Here is some output when stracing one of the healthcheck processes, this appears to repeat every `--timeout` as expected. The only unexpected part is that it outputs the announce keyword every time it runs.

```
select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=889073}) = 0 (Timeout)
pipe2([5<pipe:[25555656]>, 6<pipe:[25555656]>], O_CLOEXEC) = 0
fstat(5<pipe:[25555656]>, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
ioctl(5<pipe:[25555656]>, TCGETS, 0x7ffea9f19ae0) = -1 ENOTTY (Inappropriate ioctl for device)
lseek(5<pipe:[25555656]>, 0, SEEK_CUR)  = -1 ESPIPE (Illegal seek)
pipe2([7<pipe:[25555657]>, 8<pipe:[25555657]>], O_CLOEXEC) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f427b7cfa10) = 14643
close(8<pipe:[25555657]>)               = 0
close(6<pipe:[25555656]>)               = 0
read(7<pipe:[25555657]>, "", 50000)     = 0
close(7<pipe:[25555657]>)               = 0
rt_sigaction(SIGALRM, {sa_handler=0x62ff10, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f427b203f20}, {sa_handler=0x62ff10, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f427b203f20}, 8) = 0
alarm(5)                                = 0
lseek(5<pipe:[25555656]>, 0, SEEK_CUR)  = -1 ESPIPE (Illegal seek)
fstat(5<pipe:[25555656]>, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
read(5<pipe:[25555656]>, "8.8.8.8\n", 8192) = 8
read(5<pipe:[25555656]>, "", 8184)      = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=14643, si_uid=114, si_status=0, si_utime=0, si_stime=0} ---
close(5<pipe:[25555656]>)               = 0
wait4(14643, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 14643
alarm(0)                                = 5
getpid()                                = 684
sendto(3<UNIX:[11127342->12103]>, "<30>healthcheck[684]: send annou"..., 60, 0, NULL, 0) = 60
write(1<pipe:[11127272]>, "announce route x.x.x.x/3"..., 56) = 56
read(0<pipe:[11127271]>, "done\n", 8192) = 5
select(0, NULL, NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
pipe2([5<pipe:[25555861]>, 6<pipe:[25555861]>], O_CLOEXEC) = 0
fstat(5<pipe:[25555861]>, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
ioctl(5<pipe:[25555861]>, TCGETS, 0x7ffea9f19ae0) = -1 ENOTTY (Inappropriate ioctl for device)
lseek(5<pipe:[25555861]>, 0, SEEK_CUR)  = -1 ESPIPE (Illegal seek)
pipe2([7<pipe:[25555862]>, 8<pipe:[25555862]>], O_CLOEXEC) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f427b7cfa10) = 14667
close(8<pipe:[25555862]>)               = 0
close(6<pipe:[25555861]>)               = 0
read(7<pipe:[25555862]>, "", 50000)     = 0
close(7<pipe:[25555862]>)               = 0
rt_sigaction(SIGALRM, {sa_handler=0x62ff10, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f427b203f20}, {sa_handler=0x62ff10, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f427b203f20}, 8) = 0
alarm(5)                                = 0
lseek(5<pipe:[25555861]>, 0, SEEK_CUR)  = -1 ESPIPE (Illegal seek)
fstat(5<pipe:[25555861]>, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
read(5<pipe:[25555861]>, "8.8.8.8\n", 8192) = 8
read(5<pipe:[25555861]>, "", 8184)      = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=14667, si_uid=114, si_status=0, si_utime=0, si_stime=0} ---
close(5<pipe:[25555861]>)               = 0
wait4(14667, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 14667
alarm(0)                                = 5
getpid()                                = 684
sendto(3<UNIX:[11127342->12103]>, "<30>healthcheck[684]: send annou"..., 60, 0, NULL, 0) = 60
write(1<pipe:[11127272]>, "announce route x.x.x.x/3"..., 56) = 56
read(0<pipe:[11127271]>, "done\n", 8192) = 5
select(0, NULL, NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
```

##### OS
Ubuntu 18.04 LTS

uname: ` Linux auth01 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64`
Python: `3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]` 

##### Version
`4.0.2-1c737d99` and `4.0.10`

##### Installation
Tried using Ubuntu 18.04 LTS package provided in the universe repo and using a Python3 virtualenv.

##### Environment 

```
[exabgp.daemon]
user = 'exabgp'
```

##### Configuration
```
# Control pipe
process v4-ip1 {
  run python3 -m exabgp healthcheck --cmd "dig @x.x.x.x domainname.tld. a +short +tries=1 +time=1" --ip x.x.x.x --label v4-ip1 --config /etc/exabgp/healthcheck.conf;
  encoder text;
}
process v6-ip1 {
  run python3 -m exabgp healthcheck --cmd "dig @y:y:y::y domainname.tld. a +short +tries=1 +time=1" --ip y:y:y::y --label v6-ip1 --config /etc/exabgp/healthcheck.conf;
  encoder text;
}
process v6-ip2 {
  run python3 -m exabgp healthcheck --cmd "dig @y:y:y::y domainname.tld. a +short +tries=1 +time=1" --ip y:y:y::y --label v6-ip2 --config /etc/exabgp/healthcheck.conf;
  encoder text;
}

# IPv6 template
template {
  neighbor v6 {
    local-as 64521;
    peer-as 64500;
    hold-time 180;
    router-id <router id>;
    group-updates false;
    local-address <local address>;
    capability {
      graceful-restart 120;
    }
    family {
      ipv6 unicast;
    }
    api {
      processes [ v6-ip1 v6-ip2 ];
    }
  }
}

# IPv4 template
template {
  neighbor v4 {
    local-as 64521;
    peer-as 64500;
    hold-time 180;
    router-id <router id>;
    group-updates false;
    local-address <local address>;
    capability {
      graceful-restart 120;
    }
    family {
      ipv4 unicast;
    }
    api {
      processes [ v4-ip1 ];
    }
  }
}

# Neighbours

neighbor y:y:y::y {
  inherit v6;
  description "neighbor 1";
}

neighbor x.x.x.x {
  inherit v4;
  description "neighbor 1";
}
```

`healthcheck.conf`

```
sudo
interval = 2
fast-interval = 1
fall = 2
withdraw-on-down
```

##### Steps to reproduce

Not sure how to a reproducible setup.

##### Importance

Since this is a cause of concern it does hold back the project before going to production.

**Comment by thomas-mangin** [comment]
Thanks for taking this issue from slack to here. 

Should it be a failure of the health check program, full logging should have shown the process being restarted. I am not the author of healthcheck so I had to read the code but I noticed the following comment.

```
        # Send announces. We announce them on a regular basis in case
        # we lose connection with a peer.
```

The code does seems to indeed announce the route after each check. This is a most likely a "protection" for users disabling the ADJ-RIB-OUT and not realising what it will do.
Should the BGP session drop and come back, healthcheck will then re-announce promptly the route, in usual setups ExaBGP will notice that the route was already announced and just ignore the command as it will have been re-announced on reconnection.

As you do not provide the content of your `/etc/exabgp/healthcheck.conf` I can not check things as you do, but it seems that regular message from healthcheck to ExaBGP are normal.
what is surprising to me is that you are saying that `This only occurs when running the healthcheck as part of the ExaBGP daemon`.

**Comment by thomas-mangin** [comment]
@vincentbernat I notice that healthcheck allows to `drop_privileges` but at this point the user running healthcheck may be unable to perform the change. Should a check performed before attempting the change and a warning be logged if it is not possible ?

**Comment by Marlinc** [comment]
Hey @thomas-mangin,

Thank you for looking at this so quickly, I have attached the `healthcheck.conf` contents to the issue description. I didn't include it at first as its rather simple.

I wish I knew of a different way of checking that would explain the different behaviour when running healthcheck from within in a shell.

**Comment by Marlinc** [comment]
It appears I forgot to include the strace I mentioned, I have added that now.

**Comment by thomas-mangin** [comment]
The strace looks good. having it "announce ..." is normal. Is it not working as expected ? AFAICS all is as should.

**Comment by thomas-mangin** [comment]
@vincentbernat .. healthcheck is not consuming the "done" message that will cause issue !

**Comment by thomas-mangin** [comment]
@Marlinc please setup `exabgp.api.ack=false` as otherwise healthcheck will fail after some time. ExaBGP 4.0 replies to command when ExaBGP 3.4 does not. This message will at some point become blocking and cause ExaBGP to lock up otherwise.

**Comment by vincentbernat** [comment]
❦ 13 juin 2019 15:04 -07, Thomas Mangin <notifications@github.com>:

> The code does seems to indeed announce the route after each check.
> This is a most likely a "protection" for users disabling the
> ADJ-RIB-OUT and not realising what it will do.

This was done before ADJ-RIB-OUT was implemented. Maybe this could be
optional?

**Comment by vincentbernat** [comment]
❦ 13 juin 2019 15:06 -07, Thomas Mangin <notifications@github.com>:

> @vincentbernat I notice that healthcheck allows to `drop_privileges`
> but at this point the user running healthcheck may be unable to
> perform the change. Should a check performed before attempting the
> change and a warning be logged if it is not possible ?

As dropping privileges is an explicit request from the user, I don't
think it is wise to just go on if we can't drop privileges.

**Comment by vincentbernat** [comment]
There is:

```python
sys.stdin.readline()
```

To consume the done message.

**Comment by thomas-mangin** [comment]
@Marlinc please ignore my comment about `exabgp.api.ack` .. It was late and I missed the read !

**Comment by thomas-mangin** [comment]
@vincentbernat should the code have something like this to always work ?

```
	r = True
	while r:
			try:
				r,_,_ = select.select([sys.stdin], [], [], 1.0)
			except select.error:
				raise KeyboardInterrupt('SIGNAL received in select')
		if r:
			sys.stdin.readline()
```

**Comment by Marlinc** [comment]
@thomas-mangin you are right on manually typing ´enter'. Doing that does result in healthcheck returning an announce on the next check interval.

**Comment by vincentbernat** [comment]
@thomas-mangin I don't know, isn't it a recipe to create some heisenbugs when ExaBGP slows down for some reason? We could use `sys.stdin.isatty()` instead, but then, we would get a different behaviour when piping through `grep` for example. Maybe a flag `--no-ack` would be cleaner?

**Comment by thomas-mangin** [comment]
@vincentbernat all the code does is to clear any data on the pipe to make sure the write can not become blocking on ExaBGP's side, it just cause a 0.01 second wait, but no I do not expect this to cause any issue at all. What possible issues do you have in mind please ?

This was just an example I wrote quickly, some production code may look more like this ..

```python
errno_block = set((
	errno.EINPROGRESS, errno.EALREADY,
	errno.EAGAIN, errno.EWOULDBLOCK,
	errno.EINTR, errno.EDEADLK,
	errno.EBUSY, errno.ENOBUFS,
	errno.ENOMEM,
))

# errno_fatal = set((
# 	errno.ECONNABORTED, errno.EPIPE,
# 	errno.ECONNREFUSED, errno.EBADF,
# 	errno.ESHUTDOWN, errno.ENOTCONN,
# 	errno.ECONNRESET, errno.ETIMEDOUT,
# 	errno.EINVAL, errno.ENOTSUP,
# 	errno.EPERM,
# 	errno.ECONNREFUSED, errno.EHOSTUNREACH,
# ))

def clear_pipe()
	while True:
		try:
			r,_,_ = select.select([sys.stdin], [], [], 0.01)
		except select.error:
			raise KeyboardInterrupt('SIGNAL received in select')
		except IOError as exc:
			if exc.args[0] in errno_block:
				return
			else:
				logger.warn("unexpected error during select : %s" % str(exc))
				sys.exit(1)

		if not r:
			return
		sys.stdin.readline()
```

**Comment by thomas-mangin** [comment]
@Marlinc I assume this solves your mystery and that all is good from your point of view ?

**Comment by vincentbernat** [comment]
I fear the ExaBGP process can become CPU starved for some reason (CPU stolen by another VM). The healthcheck process would randomly skip reading the acks and after some iterations, ExaBGP process would block because there are two many acknowledgments not read. This seems a high risk just to let the user run the script manually without pressing enter. Detecting a TTY or using a flag (which could be useful for people running without acks) would be safer, I think.

**Comment by thomas-mangin** [comment]
@vincentbernat it would take a few thousand message to fill the pipe buffer. At this point, if the processes are CPU starved to that level, it is very likely that BGP session will be also unstable, but I can accept your argument and using `isatty` would be prevent this kind of surprise just fine.

**Comment by Marlinc** [comment]
Yes @thomas-mangin my mystery has been resolved, thank you very much both of you

**Comment by thomas-mangin** [comment]
@vincentbernat thank you - hopefully all good now :-)
