### ISSUE TITLE
Add an ExaBGP cli to introspect / control the daemon

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#90]
A la Quagga / BIRD.

**Comment by thepacketgeek** [comment]
I'm trying to find a relevant open issue, but something that might be necessary for this to be implemented is the ability to add/remove neighbors via API without need to reload the conf file and close current BGP sessions.

**Comment by thomas-mangin** [comment]
This is a common request that I will be able to add once the new configuration code is completed. Please feel free to open a new feature request.

**Comment by realpdm** [comment]
This would be extremely useful I believe. The current way of interacting with the API is less than ideal for me being able to debug my control program. If my program has an exception and dies for some reason there is also no mechanism for it to restart automatically. 

A model where the control program run separate from exabgp and can interact with it with a connectable API or a CLI  would work much better for my use case at least. 

I look forward to this!

**Comment by thomas-mangin** [comment]
exabgpcli is now a feature of master. command api not stable yet but for command line tool it should not matter too much
