### ISSUE TITLE
Fix CI to Pass 

### ISSUE THREAD

**Issue by cooperlees** [Exa-Networks/exabgp#900]
I'd love to help with and see ✅ again on the CI.

TravisCI:
- Get passing again
- Add in an allowed failed job on Python 3.8 (to see if we have any incompatibilities) - e.g. https://github.com/pypa/bandersnatch/blob/master/.travis.yml

Scrutinizer:
- Possibly remove?

**Comment by thomas-mangin** [comment]
Happy to remove Scrutinizer

**Comment by thomas-mangin** [comment]
All the test fail on bionic - so I can try to reproduce

**Comment by thomas-mangin** [comment]
Got it .. psutil seems to be python3 only (even if installed with pip install on bionic) and import fails even if pip was run before hand. 
Coverting the code to python3

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/commit/6ec1f15da093ad395527919c93444ec50b7bcdca

**Comment by thomas-mangin** [comment]
work on bionic - works on Mac - does not work on travis - find the mistake !

**Comment by thomas-mangin** [comment]
I have build a brand new Ubuntu machine following the steps in the CI files and it works.

**Comment by thomas-mangin** [comment]
Two issues:
 - `pip install psutil` does not (always) work on the travis-ci VM ! for some reason
 - the docker image has no IPv6 loopback !

**Comment by thomas-mangin** [comment]
Now now need to convert print format from python2 to python3 but unlocked

**Comment by thomas-mangin** [comment]
Now passing

**Comment by cooperlees** [comment]
Nice work! I’ll now have more confidence when changing things in the future.

**Comment by cooperlees** [comment]
Can we please turn off the other failing CI? 🤞🏼 _(screenshot from head's CI runs)_
![Screen Shot 2019-07-16 at 1 38 05 PM](https://user-images.githubusercontent.com/3005596/61328031-0d04d480-a7cf-11e9-8d1a-e5e40af1ff39.png)
- continuous-integration/codeship
- Scrutinizer

I am sure these will be GUI clicking.

**Comment by thomas-mangin** [comment]
I will try to get scrutiniser working to see if it is work keeping as in the past it found some bug doing linting.
