### ISSUE TITLE
TravisCI not always running venv python

### ISSUE THREAD

**Issue by cooperlees** [Exa-Networks/exabgp#905]
I was trying to add Python 3.8 + nightly builds to ExaBGP CI, and found that `pypy` CI is not always actually running with Travis Environment's version as:
- `command -v python3` etc.

This lead to you needing the system apt installs. I'd like to remove (and will have a PR coming) to address this.

An example is the Python2 version was actually running with system Python 3.5:
```
$ sbin/exabgp --version
ExaBGP : (HEAD-b38529f31cb75097b72d125caf50d1a32f3526a4
Python : 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
Uname  : Linux travis-job-926aa7d8-30c3-41df-8372-4725b27a24a7 4.15.0-1028-gcp #29~16.04.1-Ubuntu SMP Tue Feb 12 16:31:10 UTC 2019 x86_64
Root   : /home/travis/build/Exa-Networks/exabgp
The command "sbin/exabgp --version" exited with 0.
```

**Comment by thomas-mangin** [comment]
@cooperlees I assume we can not close this.

**Comment by cooperlees** [comment]
Yeah, this is solved. Just need to see what bug PyPy and Python 2 are hitting.

**Comment by thomas-mangin** [comment]
It looks like timing issue with the testing code ... sigh ! Not easy to change of fix.

**Comment by cooperlees** [comment]
Why doesn’t it effect Python 3?

**Comment by thomas-mangin** [comment]
it does affect all python. I had some times pypy fails and some other python2. It seems python3 behave a little bit better !
