### ISSUE TITLE
Is there a way to test cfg file?

### ISSUE THREAD

**Issue by sincerywaing** [Exa-Networks/exabgp#910]
current `--test` parameter does not support to check what's behind `run`, for example:

```
run /usr/bin/python healthcheck -F abc.cfg;
```
it does not check if `/usr/bin/python healthcheck -F abc.cfg` success or fails, or the syntax inside abc.cfg.

Is there any workaround to check if above works or not?

**Comment by vincentbernat** [comment]
This doesn't seem possible. How would it be able to check if an arbitrary binary would work correctly without executing it?

**Comment by thomas-mangin** [comment]
@sincerywaing I agree with @vincentbernat and as it has been a week since the reply, I am closing this issue. Feel free to reopen if needed.
