### ISSUE TITLE
Does Exabgp have "write config" in command 

### ISSUE THREAD

**Issue by andy19910403** [Exa-Networks/exabgp#911]
Hi all:
I announced routes by Exabgp demon ,
After restarting Exabgp server, the announced routes are disappeared in Exabgp demon 
How can I keep routes when I restart server

Thanks~

**Comment by thomas-mangin** [comment]
Hello Andy,

You should add them in the configuration file if you want them available upon restart. Routes announced via the API (or CLI) are not saved. You will have to take care of this persistence.

Perhaps https://erco.xyz is what you want ?
