### ISSUE TITLE
exabgp full internet table

### ISSUE THREAD

**Issue by mattoddy** [Exa-Networks/exabgp#916]
Hi, I have been able to advertise the full internet table using the old 'announce route' syntax however I believe there is a more efficient way to do this. I can see in the article that there is an 'announce attributes' syntax. https://github.com/Exa-Networks/exabgp/wiki/Large-Configuration-File 

I have used the command:
```
python /usr/local/lib/python2.7/dist-packages/mrtparse/examples/mrt2exabgp.py -G -P latest-bview.gz  > fullbgptable.py
```

When I run this command the process hangs and does that send any output to the file. If I omit the -G then the command works but I end up with the old syntax.

I understand that this is an mrtparse issue and not exabgp but if anyone has any an experience with getting this working then any help would be appreciated.

Thanks.

**Comment by thomas-mangin** [comment]
@mattoddy no personal experience with the tool. Hopefully the author can look at what is wrong. Happy to answer questions if help is needed.

**Comment by mattoddy** [comment]
Thanks Thomas. I've raised an issue on the mrtparse Github.

**Comment by thomas-mangin** [comment]
I will close - feel free to re-open if you need anything.
