### ISSUE TITLE
Installation Guide for GIX LG

### ISSUE THREAD

**Issue by MAK4789** [Exa-Networks/exabgp#919]
##### Summary
 I have installed ExaBGP on my machine having Centos 7 but unable to find the next step for GIX LG. Can any one help me out?

##### OS
CentOS Linux release 7.7.1908
```
Linux
MacOS
FreeBSD
Other (please specify)
```

```
Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```

##### Version

```
ExaBGP : 4.1.2-d006a34a
Python : 2.7.5 (default, Aug  7 2019, 00:51:29)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Uname  : Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64
Root   : /usr

```

##### Installation
pip
```
pip
pip with virtualenv
latest OS package
other (please specify)
```

##### Environment 

```
its empty
```

##### Configuration

```

```

##### Program output

```

```

##### Steps to reproduce

```

```

##### Importance

```
not yet
```

**Comment by thomas-mangin** [comment]
Please could you ask GIXLG Author for help here. Also please keep in mind that his code was written (AFAIK) for version 3 and therefore will likely not work with ExaBGP version 4.

**Comment by MAK4789** [comment]
Hi Thomas,

Thanks alot for your support. Can you please share ExaBGP version 3 with me? as i am unable to find it over internet.

Regards,

Muhammad Ali
+92-346-2750502
________________________________

**Comment by thomas-mangin** [comment]
https://pypi.org/project/exabgp/3.4.26/
