### ISSUE TITLE
Slack invite link outdated

### ISSUE THREAD

**Issue by elindsey** [Exa-Networks/exabgp#922]
The Slack invite link in the README (under the support section here - https://github.com/Exa-Networks/exabgp/blob/master/README.md) is outdated. 

I'm not sure if Slack is still used, but that link leads to a page that says: "This invite link is no longer active. Please check with the person who shared it with you to see if there's a new link available."

(if you update it, might remove the G+ link too - RIP G+).

**Comment by thomas-mangin** [comment]
The link is not supposed to expire !

**Comment by thomas-mangin** [comment]
Thank you for reporting the issue ..
