### ISSUE TITLE
API commands response

### ISSUE THREAD

**Issue by arbaldin** [Exa-Networks/exabgp#924]
Hi there.

It's not really a problem, just a question. I've been read everything I could about exabgp API, but unfortunately I was unable to figure out an answer.

Using sample code I found around the internet, I was able to create a python script that receive command through http. I can use it to send route announce and withdraw an it work great. I can also send other commands, like version (this the first I' trying), and in exabgp log I see it was accepted and executed. My question is regarding the output of the command: how can I read the output of the command and return it back to the script? Does it return to stdin or stdout? Other command than version, with more lines of response, how can I read all lines?

I couldn't find (or could not understand) any example that reads response from API commands.

Thanks for your help.

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/wiki/Migration-from-3.4-to-4.0#api

**Comment by thomas-mangin** [comment]
with version 4 all the commands now return like version does.

**Comment by thomas-mangin** [comment]
The program is forked and the STDIN of your program is connected to the output of ExaBGP. You just need to read it.
