### ISSUE TITLE
[exabgp 3.4.17 ] scalability / can not run more than 1024 bgp sessions on same host

### ISSUE THREAD

**Issue by pguibert6WIND** [Exa-Networks/exabgp#929]
On a test setup, it is not possible to run more than 1K peers.
The system is a Linux machine.
Even when reconfiguring the 'ulimit -n setting', the limit is still visible.

it is possible to leverage that limit ?

```
<type 'exceptions.ValueError'>
filedescriptor out of range in select()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 607, in _run                                                          
    for action in self._[direction]['code']():
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 368, in _connect                                                      
    connected = generator.next()
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/protocol.py", line 100, in connect                                                   
    connected = generator.next()
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/network/outgoing.py", line 47, in establish                                          
    connected = generator.next()
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/network/tcp.py", line 187, in ready                                                  
    _,w,_ = select.select([],[io,],[],0)
ValueError: filedescriptor out of range in select()
```

**Comment by thomas-mangin** [comment]
`ulimit -n` should indeed be do the right thing ... if it does not then it must be a limitation in the python select interface or OS.

It also may be wise to try to use async I/O in python to handle over 1k peers on a single core (as python can not take advantage of multiple cores) .. unless you are only planning on sending un-regular updates ..

I would recommend breaking the configuration in blocks and just run exabgp multiple times. If you do not bind but just connect out, you can run as many as you need without penalties.

**Comment by thomas-mangin** [comment]
You can use `exabgp <conf1> <conf2> ..` ExaBGP will fork another process for each configuration but for the 1024 limit, it is within select - which is the only system call portable, the only way to raise the limit would be to use poll/epoll/kqueue.

**Comment by thomas-mangin** [comment]
Unless it is really an issue, I wont work on this. You could place BIRD configured as route reflector as a frontend to exabgp if this kind of scalability matter.

**Comment by thomas-mangin** [comment]
implemented poll instead of select for network and api pipe.

**Comment by thomas-mangin** [comment]
but not yet for the one you encountered 🤦‍♂

**Comment by pguibert6WIND** [comment]
@thomas-mangin , thanks for the update provided with the new patch.
actually, I did not use it, I am on 4.2.13.
I am using 1700 clients per config.
And I use it like that:
```
ip netns exec wan1 exabgp --env /tmp/env1.env /tmp/exabgp1.cfg
ip netns exec wan2 exabgp --env /tmp/env2.env /tmp/exabgp2.cfg
ip netns exec wan3 exabgp --env /tmp/env3.env /tmp/exabgp3.cfg
```
It appears there is some memory leak
(the number that increases is VIRT and RES)
at startup:
```
root@ucpe-vm:~# top -n 1 | grep exabgp
 7383 exabgp    20   0 3689276 3.461g   5232 R  88.9 19.7   7:00.44 exabgp                                                                                            
 7394 exabgp    20   0 3694492 3.466g   5120 R  88.9 19.7   6:42.58 exabgp                                                                                           
 7482 exabgp    20   0 1128836 1.019g   5236 R  88.9  5.8   1:34.04 python3  
```

after a few minutes:
```
root@ucpe-vm:~# top -n 1 | grep exabgp
 7394 exabgp    20   0 4761812 4.484g   5120 R  87.5 25.5  26:26.53 exabgp                                                                                           
 7383 exabgp    20   0 4758228 4.481g   5232 R  81.2 25.5  26:50.10 exabgp                                                                                           
 7482 exabgp    20   0 4513728 4.248g   5236 R  81.2 24.2  21:52.77 python3  
```


on a previous setup, I have been stopped by an OOM killer.
any updates on memory leaks?

**Comment by thomas-mangin** [comment]
@pguibert6WIND 1700 clients per config  .. ExaBGP is some Python async code running on one core .. AARGHH. This is indeed beyond what was ever considered possible with the codebase.

I am working on a new implementation in Go, I may be able to share it soon as I am near something useful. I think we should take this discussion outside GitHub. I am near having something which may allow you to do what you want for scalability testing.

please email me at first_name @ last_name . com
