### ISSUE TITLE
[exabgp4] Reloading exabgp rise an error if api in template section of exabgp.cfg

### ISSUE THREAD

**Issue by arozhentsev** [Exa-Networks/exabgp#937]
##### Summary
Hello, Everyone!
Reloading exabgp rise an error if api in template section of exabgp.cfg.
"the name "services" already exists in api"

##### OS
Linux debian10 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

##### Version
ExaBGP : 4.0.8-793a2931

##### Installation
pip
latest OS package

##### Environment 
exabgp.env
+++++++++++++++++++++++++++++++++++
[exabgp.api]
encoder = text

[exabgp.cache]
attributes = true
nexthops = true

[exabgp.daemon]
daemonize = true
pid = ''
user = 'exabgp'

[exabgp.log]
enable = true
destination = 'syslog'
level = WARNING
all = false
configuration = true
daemon = true
message = true
network = true
packets = false
parser = false
processes = true
rib = false
routes = false
short = false
supervisor = true
timers = false

[exabgp.pdb]
enable = false

[exabgp.profile]
enable = false
file = ''

[exabgp.tcp]
once = false
timeout = 1
+++++++++++++++++++++++++++++++++++

##### Configuration
exabgp.cfg
+++++++++++++++++++++++++++++++++++
template {
    neighbor exabgp4 {
        local-as 319;
        peer-as 171;
        hold-time 15;
        router-id 169.254.0.31;
        api listening {
            services [ exabgp_shutdown ];
            neighbor-changes;
        }
    }
}

neighbor 169.254.0.41 {
    inherit exabgp4;
    local-address 169.254.0.31;
    group-updates;
    static {
        route 10.0.0.1/32 next-hop self med 10;
    }
}

process exabgp_shutdown {
    run /scripts/exabgp/exabgp_shutdown.sh;
    encoder text;
}
+++++++++++++++++++++++++++++++++++
##### Program output
17:46:58 | 7872   | welcome       | Thank you for using ExaBGP
17:46:58 | 7872   | version       | 4.0.8-793a2931
17:46:58 | 7872   | interpreter   | 3.7.3 (default, Apr  3 2019, 05:39:12)  [GCC 8.3.0]
17:46:58 | 7872   | os            | Linux debian10 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64
17:46:58 | 7872   | installation  |
17:46:58 | 7872   | cli control   | named pipes for the cli are:
17:46:58 | 7872   | cli control   | to send commands  /run/exabgp.in
17:46:58 | 7872   | cli control   | to read responses /run/exabgp.out

After systemctl reload i recieve

Nov 28 18:04:10 debian10 systemd[1]: Reloading ExaBGP.
Nov 28 18:04:10 debian10 exabgp[8881]: reactor       SIGUSR1 received
Nov 28 18:04:10 debian10 exabgp[8881]: reactor       scheduling reload of configuration
Nov 28 18:04:10 debian10 systemd[1]: Reloaded ExaBGP.
Nov 28 18:04:10 debian10 exabgp[8881]: configuration problem with the configuration file, no change done
Nov 28 18:04:10 debian10 exabgp[8881]: configuration problem parsing configuration file line 8
Nov 28 18:04:10 debian10 exabgp[8881]: configuration error message: the name "services" already exists in api

And process /scripts/exabgp/exabgp_shutdown.sh is no more.

##### Steps to reproduce
Use config with api in template section and related process. After exabgp start with no errors, execute systemctl reload exabgp.

##### Importance
Without reload i must use restart and all connections is broke obviously. In our organisation we have thousands connections per second and  this issue is critical to us.

**Comment by thomas-mangin** [comment]
This should have been fixed with one of the latest configuration change.

**Comment by thomas-mangin** [comment]
Closing due to lack of feedback and as it is likely already fixed.
