### ISSUE TITLE
Random crashes because of "^C received" (Reactor `elif event & select.POLLHUP`)

### ISSUE THREAD

**Issue by pierky** [Exa-Networks/exabgp#942]
##### Summary
I'm experiencing some random crashes which, after troubleshooting, I was able to pinpoint to Reactor's `_wait_for_io` method, these `if` case:
https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/reactor/loop.py#L118-L119

I changed the string used in line https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/reactor/loop.py#L119 to "^C PIERKY received" to make it different than the one used in the other `if` clause, and actually I got it printed in the message which is logged during the failure conditions.

I'd like to ask your help to better determine the root cause and to understand what can trigger that part of the script.

##### OS
Ubuntu 18.04.3 LTS

Linux exabgp-eu-west-1 4.15.0-1047-aws #49-Ubuntu SMP Fri Aug 23 09:02:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

##### Version
```
ExaBGP : 4.1.2-d006a34a
Python : 3.6.8 (default, Oct  7 2019, 12:59:55)  [GCC 8.3.0]
Uname  : Linux exabgp-eu-west-1 4.15.0-1047-aws #49-Ubuntu SMP Fri Aug 23 09:02:45 UTC 2019 x86_64
```

##### Installation
`git clone`

##### Environment 
```
[exabgp.daemon]
user = 'exabgp'

[exabgp.log]
destination = '/var/log/exabgp/exabgp.log'
message = true
packets = true
parser = true
```

##### Configuration
```
process announce-routes {
    run python3 /etc/exabgp/processes/exabgp_parser.py;
    encoder json;
}
process detect-bgp-flap {
    run python3 /etc/exabgp/processes/exabgp_flaps.py;
    encoder json;
}

template {
    neighbor MY_TEMPLATE {
        local-as 111111;
        peer-as 111111;
        hold-time 30;
        local-address 10.1.2.3;
        router-id 10.1.2.3;
        capability {
            route-refresh;
        }
        adj-rib-in false;
        family {
            ipv4 unicast;
            ipv6 unicast;
        }
        api {
            processes [ detect-bgp-flap ];
            neighbor-changes;
        }
        api {
            processes [ announce-routes ];
        }
    }
}


neighbor 1.2.3.4 {
    inherit MY_TEMPLATE;
    description "bla bla";
}
```

A total of 42 sessions like this one

##### Program output
```
Dec 21 10:18:17 21797  api           route added to neighbor 1.1.1.1 local-ip 10.1.2.3 local-as 111111 peer-as 111111 router-id 10.1.2.3 family-allowed in-open : 2001:db8::6/128 next-hop 2001:db8::2959 local-preference 450 community no-export

Dec 21 10:18:17 21797  api           route added to neighbor 1.1.1.1 local-ip 10.1.2.3 local-as 111111 peer-as 111111 router-id 10.1.2.3 family-allowed in-open : 2001:db8::7/128 next-hop 2001:db8::2959 local-preference 450 community no-export

Dec 21 10:18:28 21797  outgoing-1444 outgoing-1444 10.1.2.3-11.22.33.255, closing connection

Dec 21 10:18:28 21797  outgoing-1444 outgoing-1444 10.1.2.3-11.22.33.255 11.22.33.255 problem sending message ([Errno ECONNREFUSED] [Errno 111] Connection refused)

Dec 21 10:18:28 21797  outgoing-1444 outgoing-1444 10.1.2.3-11.22.33.255, closing connection
Dec 21 10:18:51 21797  reactor       ^C received
Dec 21 10:18:51 21797  reactor       performing shutdown
Dec 21 10:18:51 21797  outgoing-27   outgoing-27 10.1.2.3-11.22.55.31, closing connection
Dec 21 10:18:51 21797  outgoing-40   outgoing-40 10.1.2.3-11.22.33.254, closing connection
Dec 21 10:18:51 21797  outgoing-43   outgoing-43 10.1.2.3-11.22.44.254, closing connection
```

##### Steps to reproduce
N/A

##### Importance
Production

**Comment by thomas-mangin** [comment]
@pierky thanks for this report, I just recently converted all the select calls to poll and must not have noticed this issue.

**Comment by pierky** [comment]
Oh @thomas-mangin thanks for the quick reply!

Looking forward to testing the solution or any workaround that you'll propose, although I'm not sure I'll be able to do it in the next days.

**Comment by thomas-mangin** [comment]
@pierky - ok, I understand what I did (failed to read man poll) and  this patch should fix the issue you had.

**Comment by thomas-mangin** [comment]
oops the patch need more work 📦

**Comment by thomas-mangin** [comment]
@pierky all good ?

**Comment by pierky** [comment]
Oh, I haven't noticed the update indeed :) I'll be able to check it after Jan 7th...

**Comment by thomas-mangin** [comment]
ping ? can you please confirm this is fixed. If so I will release a new version.

**Comment by pierky** [comment]
Hi @thomas-mangin, I've been actually able to start testing this in advance, and it has been stable for 6 days now. So far so good, the random crashes were used to happen more frequently than every 6 days!
