### ISSUE TITLE
clarification on config default

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [Exa-Networks/exabgp#945]
It looks like not all default in config parser classes are being used

https://github.com/Exa-Networks/exabgp/blob/d006a34a/lib/exabgp/configuration/neighbor/__init__.py#L114

`adj-rib-out` actually has default true in 4.1.2-d006a34a, not matching class `ParseNeighbor` definition. 

Am I missing something or default is not implemented for some parser?

**Comment by thomas-mangin** [comment]
Taking a neighbour without adj-rib configured:
```>./bin/exabgpcli s n c | grep 'adj-rib
  adj-rib-in true;
  adj-rib-out true;
```

Because this code is indeed misleading:

https://github.com/Exa-Networks/exabgp/blob/d006a34a/lib/exabgp/configuration/neighbor/__init__.py#L159
