### ISSUE TITLE
Error building 4.2.0 FreeBSD package (missing setup.cfg)

### ISSUE THREAD

**Issue by ocochard** [Exa-Networks/exabgp#947]
##### Summary

Updating FreeBSD port tree with this last version (4.2.0), but package generation failed.

##### OS
```

FreeBSD
```

##### Version

Source from 4.2.0

##### Program output

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 18, in <module>
    conf_dict = read_configuration('./setup.cfg', find_others=True)
  File "/usr/local/lib/python3.7/site-packages/setuptools/config.py", line 45, in read_configuration
    'Configuration file %s does not exist.' % filepath)
distutils.errors.DistutilsFileError: Configuration file /wrkdirs/usr/ports/net/exabgp/work-py37/exabgp-4.2.0/setup.cfg does not exist.
*** Error code 1
```
##### Workarround

Dirty fix: Removing line 17&18 fix it.

**Comment by thomas-mangin** [comment]
@ocochard this line was a left over test ! it was already removed on master. I will release 4.2.1 very soon.

**Comment by thomas-mangin** [comment]
You should also add this if you can not wait for 4.2.1 
https://github.com/Exa-Networks/exabgp/commit/0760a24eb9ed1ab3e04ef3c1d2a379bce9f13369

**Comment by thomas-mangin** [comment]
releasing now so it is done
