### ISSUE TITLE
Flowspec: redirect-to-nexthop-ietf sending same NH for all updates

### ISSUE THREAD

**Issue by topranks** [Exa-Networks/exabgp#949]
### Short description

ExaBGP always sends the same IPv4 next-hop address for all flowspec redirect routes.

### Environment

Ubuntu 18.04  ExaBGP from git as follows:

    root@exa:~/exabgp-git/sbin# ./exabgp --version
    ExaBGP : master-57f5c1ec81afafc96c32af4e6a04cf8a2555bbd5
    Python : 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
    Uname  : Linux exa 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64
    Root   : /home/ubuntu/exabgp-git

### Steps to reproduce

Define multiple flowspec routes with different "redirect-to-nexthop-ietf" addresses as per this [exabgp.conf.txt](https://github.com/Exa-Networks/exabgp/files/4074609/exabgp.conf.txt) file.

### Expected Behaviour

ExaBGP sends 3 BGP flowspec updates with different next-hop IPs encoded in an extended community attribute as per [draft-simpson-idr-flowspec-redirect-02](https://tools.ietf.org/html/draft-simpson-idr-flowspec-redirect-02).

### Actual behaviour

Starting ExaBGP with verbose output you will see something similar to the attached _exabgp_output_ file:

[exabgp_output.txt](https://github.com/Exa-Networks/exabgp/files/4074617/exabgp_output.txt)

3 updates do get sent, but if you look at the hex representation of the separate updates you can see the same HEX seuqence ("C6 1203 03", corresponding to 198.18.3.3,) in all of them.  Indeed decoding them with ExaBGP shows the same extcommunity value on all of them:

` "extended-community": [ { "value": 75653074420695040, "string": "redirect-to-nexthop-ietf" } ] }`

The updates do appear to be properly formed and my router receives and installs them without problem, but obviously all going to the same next-hop:

```
sixwind> show bgp ipv4 flowspec detail
BGP flowspec entry: (flags 0x418)
	Source Address 198.18.1.189/32
	NH:198.18.3.187:0
	received for 00:00:06
	installed in PBR (match0x55cfc3bb51f0)
BGP flowspec entry: (flags 0x418)
	Source Address 198.18.1.188/32
	NH:198.18.3.187:0
	received for 00:00:06
	installed in PBR (match0x55cfc3bb51f0)
BGP flowspec entry: (flags 0x418)
	Source Address 198.18.1.187/32
	NH:198.18.3.187:0
	received for 00:00:06
	installed in PBR (match0x55cfc3bb51f0)

Displayed  3 flowspec entries
```

# Other information

I've included a pcap file also:

[exabgp_flowspec_same_nh.pcap.tar.gz](https://github.com/Exa-Networks/exabgp/files/4074657/exabgp_flowspec_same_nh.pcap.tar.gz)

**Comment by thomas-mangin** [comment]
Reproduced :
```
template {
    neighbor FLOW {
        router-id 198.18.1.134;
        local-address 127.0.0.1;
        local-as 2110;
        peer-as 2110;

        family {
            ipv4 flow;
        }
    }
}

neighbor 127.0.0.1 {
    inherit FLOW;
    description sixwind;

    flow {
        route {
            match {
                source 198.18.1.187/32;
            }
            then {
                redirect-to-nexthop-ietf 198.18.1.10;
            }
        }

        route {
            match {
                source 198.18.1.188/32;
            }
            then {
                redirect-to-nexthop-ietf 198.18.3.3;
            }
        }


        route {
            match {
                source 198.18.1.189/32;
            }
            then {
                redirect-to-nexthop-ietf 198.18.3.187;
            }
        }
    }
}
```
ran with 
```
env exabgp_tcp_bind='' exabgp_tcp_port=1790 INTERPRETER=/usr/local/bin/python3 ./sbin/exabgp -d -p FILE
./qa/sbin/bgp --port 1790 --echo
```
```
> exabgpcli s a o e
command: show adj-rib out extensive
neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 2110 peer-as 2110 router-id 198.18.1.134 family-allowed in-open ipv4 flow flow source-ipv4 198.18.1.187/32 extended-community redirect-to-nexthop-ietf 198.18.1.10
neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 2110 peer-as 2110 router-id 198.18.1.134 family-allowed in-open ipv4 flow flow source-ipv4 198.18.1.188/32 extended-community redirect-to-nexthop-ietf 198.18.3.3
neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 2110 peer-as 2110 router-id 198.18.1.134 family-allowed in-open ipv4 flow flow source-ipv4 198.18.1.189/32 extended-community redirect-to-nexthop-ietf 198.18.3.187
```

```
./qa/sbin/bgp --port 1790 --echo                                                                                                                                                                                 
echo mode - send us whatever, we can parrot it ! :p

     127.0.0.1 49675 received 0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:0013:04:
     127.0.0.1 49675 sent     0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:0013:04:
     127.0.0.1 49675 received 0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC612010A0000800E0C0001850000060220C61201BB
     127.0.0.1 49675 sent     0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC612010A0000800E0C0001850000060220C61201BB
     127.0.0.1 49675 received 0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC61203030000800E0C0001850000060220C61201BC
     127.0.0.1 49675 sent     0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC61203030000800E0C0001850000060220C61201BC
     127.0.0.1 49675 received 0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC61203BB0000800E0C0001850000060220C61201BD
     127.0.0.1 49675 sent     0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC61203BB0000800E0C0001850000060220C61201BD
     127.0.0.1 49675 received 0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:001E:02:00000007900F0003000185
     127.0.0.1 49675 sent     0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:001E:02:00000007900F0003000185
     127.0.0.1 49675 connection closed
```

```
> ./sbin/exabgp FILE --decode FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC61203030000800E0C0001850000060220C61201BC
[...]
10:34:40 | 91303  | parser        | decoded update 1 flow source-ipv4 198.18.1.188/32 origin igp local-preference 100 extended-community redirect-to-nexthop-ietf 198.18.3.3
10:34:40 | 91303  | parser        | update json { "exabgp": "4.0.1", "time": 1579257280.5713449, "host" : "ThomasMBP.local", "pid" : 91303, "ppid" : 89131, "counter": 1, "type": "update", "neighbor": { "address": { "local": "127.0.0.1", "peer": "127.0.0.1" }, "asn": { "local": 2110, "peer": 2110 } , "direction": "in", "message": { "update": { "attribute": { "origin": "igp", "local-preference": 100, "extended-community": [ { "value": 75653074420695040, "string": "redirect-to-nexthop-ietf 198.18.3.3" } ] }, "announce": { "ipv4 flow": { "no-nexthop": [ { "source-ipv4": [ "198.18.1.188/32" ], "string": "flow source-ipv4 198.18.1.188/32" } ] } } } } } }
```

**Comment by thomas-mangin** [comment]
So I can not reproduce. Can you help ?

**Comment by topranks** [comment]
Great thanks a million for looking at this Thomas.

First up I am thinking my environment might be a bit messed up, I installed from Ubuntu repo first then removed, then pypi and removed and finally used tar.

So let me scrap my VM and fire up a new one with clean build and make sure I see the exact same thing.  If I do I will try to run the same commands as you have above and post them here.  After that I am happy to help with any other outputs or debugs etc.  I will get back to you shortly.

**Comment by topranks** [comment]
Ok so I get the same with a clean install of 4.2.3.

When I show the rib-out no next-hop IP address is shown:

```
root@ubuntu:~/exabgp-4.2.3/bin# ./exabgpcli s a o e
command: show adj-rib out extensive
neighbor 198.18.1.133 local-ip 198.18.1.134 local-as 2110 peer-as 31984 router-id 198.18.1.134 family-allowed in-open ipv4 flow flow source-ipv4 198.18.1.187/32 extended-community redirect-to-nexthop-ietf
neighbor 198.18.1.133 local-ip 198.18.1.134 local-as 2110 peer-as 31984 router-id 198.18.1.134 family-allowed in-open ipv4 flow flow source-ipv4 198.18.1.188/32 extended-community redirect-to-nexthop-ietf
neighbor 198.18.1.133 local-ip 198.18.1.134 local-as 2110 peer-as 31984 router-id 198.18.1.134 family-allowed in-open ipv4 flow flow source-ipv4 198.18.1.189/32 extended-community redirect-to-nexthop-ietf
```

I noticed something similar in the decoder output of the routes sent on the wire, actual IP of the next hop seems to be missing from the end of the string.

```
12:10:23 | 83652  | parser        | decoded update 1 flow source-ipv4 198.18.1.187/32 origin igp as-path [ 2110 ] extended-community redirect-to-nexthop-ietf
12:10:23 | 83652  | parser        | update json { "exabgp": "4.0.1", "time": 1579263023.7946365, "host" : "exa", "pid" : 83652, "ppid" : 80539, "counter": 1, "type": "update", "neighbor": { "address": { "local": "198.18.1.134", "peer": "198.18.1.133" }, "asn": { "local": 2110, "peer": 31984 } , "direction": "in", "message": { "update": { "attribute": { "origin": "igp", "as-path": [ 2110 ], "confederation-path": [], "extended-community": [ { "value": 75653074420695040, "string": "redirect-to-nexthop-ietf" } ] }, "announce": { "ipv4 flow": { "no-nexthop": [ { "source-ipv4": [ "198.18.1.187/32" ], "string": "flow source-ipv4 198.18.1.187/32" } ] } } } } } }
```

This also appears to happen when I add routes at the command line - *in quick succession* - but not if I delay them slightly.  For instance if I do this I end up with the same next-hop for both:

```
echo "announce flow route source-ipv4 198.18.2.210/32 redirect-to-nexthop-ietf 198.18.3.10" > exabgp.in && \
echo "announce flow route source-ipv4 198.18.2.220/32 redirect-to-nexthop-ietf 198.18.3.20" > exabgp.in 
```

Whereas if I do this the two next-hops are different:

```
echo "announce flow route source-ipv4 198.18.2.210/32 redirect-to-nexthop-ietf 198.18.3.10" > exabgp.in && \
> sleep 2 && \
> echo "announce flow route source-ipv4 198.18.2.220/32 redirect-to-nexthop-ietf 198.18.3.20" > exabgp.in
```

If you look at the attached PCAP (packets you can see that in both of these cases (when routes were added via exabgp.in) the announcements were sent in separate packets.  You can see in packets 6 through 9 that the IP is always set to 198.18.3.20.  Only in packets 10 and 11 (where there is a gap of 2 seconds) are the next-hop IPs different.

[exabgp_test.pcap.tar.gz](https://github.com/Exa-Networks/exabgp/files/4077326/exabgp_test.pcap.tar.gz)

I also notice when the next-hop is wrong, it is always set to the last next-hop of any flow routes pushed.  So in this case it was always 198.18.3.20, the IP in the second echo statement.  Or in the ones sent based on the conf file statements it's always the IP of the last route definition in the file.

I'm not 100% sure what else I can maybe test for you.  This is the decoded output I see:

```
root@ubuntu:~/exabgp-4.2.3# ./qa/sbin/bgp --echo

echo mode - send us whatever, we can parrot it ! :p

     198.18.1.134 38947 received 0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:0013:04:
     198.18.1.134 38947 sent     0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:0013:04:
     198.18.1.134 38947 received 0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC61203BB0000800E0C0001850000060220C61201BB
     198.18.1.134 38947 sent     0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC61203BB0000800E0C0001850000060220C61201BB
     198.18.1.134 38947 received 0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC61203BB0000800E0C0001850000060220C61201BC
     198.18.1.134 38947 sent     0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC61203BB0000800E0C0001850000060220C61201BC
     198.18.1.134 38947 received 0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC61203BB0000800E0C0001850000060220C61201BD
     198.18.1.134 38947 sent     0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC61203BB0000800E0C0001850000060220C61201BD
     198.18.1.134 38947 received 0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:001E:02:00000007900F0003000185
     198.18.1.134 38947 sent     0: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:001E:02:00000007900F0003000185
```
The parser output of these is interesting... again doesn't show the next-hop IP:

```
root@ubuntu:~/exabgp-4.2.3/sbin# ./exabgp --decode xx FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC61203BB0000800E0C0001850000060220C61201BB
[...]
15:06:48 | 46840  | parser          | decoded update 1 flow source-ipv4 198.18.1.187/32 origin igp local-preference 100 extended-community redirect-to-nexthop-ietf
```
The IP is in the message though - C6 12 03 BB / 198.18.3.187.

![image](https://user-images.githubusercontent.com/4465905/72622731-c047b500-393b-11ea-976f-b1dd3705ec35.png)

That's about all I can think to do right now.  Anything else I can look at?

**Comment by topranks** [comment]
Also one last thing.... I ran the exact same command you ran in your instance on mine - to decode the HEX you seen in your test.  On my version it doesn't show the next hop - it did on yours?

```
root@ubuntu:~/exabgp-4.2.3# ./sbin/exabgp ./etc/exabgp.conf  --decode FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003F:02:000000284001010040020040050400000064C01008010CC612010A0000800E0C0001850000060220C61201BB | grep parser
fatal: not a git repository (or any of the parent directories): .git
12:15:06 | 63796  | parser          | decoded update 1 flow source-ipv4 198.18.1.187/32 origin igp local-preference 100 extended-community redirect-to-nexthop-ietf
```

**Comment by topranks** [comment]
Got the same result running with Python 3.7 also.

**Comment by topranks** [comment]
One last observation:

If I add the routes with the time delay between each one, then as above the next-hop encoded in the community string is different on each one, and everything is ok.

If I then reset the BGP peer, when the session comes back up ExaBGP announces all the UPDATEs again, but this time the next-hop is the same on them all.

**Comment by thomas-mangin** [comment]
@topranks the next-hop requires the patch listed above "display the next-hop of redirect flow Exa-Networks#949" you will only find it on master. I will now look at the data you provided.

**Comment by thomas-mangin** [comment]
"This also appears to happen when I add routes at the command line - in quick succession - but not if I delay them slightly. For instance if I do this I end up with the same next-hop for both" - thank you this is very useful information.

**Comment by thomas-mangin** [comment]
Looking at the RIB code - this patch may indeed have already fixed the bug by representing the strings for both community differently. Could you please pull master and verify it is indeed already fixed :-) ?

**Comment by topranks** [comment]
Thomas,

Thank you for the feedback.  I can confirm that everything works ok with the latest version from master.  Looks like your fix corrected what is sent on the wire as well as just the parser output.

Testing I now see:

```
root@ubuntu:~/exabgp/bin# ./exabgpcli s a o e
command: show adj-rib out extensive
neighbor 198.18.1.133 local-ip 198.18.1.134 local-as 2020 peer-as 31984 router-id 198.18.1.134 family-allowed in-open ipv4 flow flow source-ipv4 198.18.1.10/32 extended-community redirect-to-nexthop-ietf 198.18.1.10
neighbor 198.18.1.133 local-ip 198.18.1.134 local-as 2020 peer-as 31984 router-id 198.18.1.134 family-allowed in-open ipv4 flow flow source-ipv4 198.18.1.20/32 extended-community redirect-to-nexthop-ietf 198.18.1.20
```

And my receiving router shows the different next-hops for each route:

```
sixwind> show bgp ipv4 flowspec detail
BGP flowspec entry: (flags 0x418)
        Source Address 198.18.1.20/32
        NH:198.18.1.20:0
        received for 00:05:58
        installed in PBR (match0x560d43cd8560)
BGP flowspec entry: (flags 0x418)
        Source Address 198.18.1.10/32
        NH:198.18.1.10:0
        received for 00:05:58
        installed in PBR (match0x560d43cd89a0)
```

Thank you so much for the great help with this.  And thanks in general for ExaBGP it is an amazing project we are very grateful for it!
