### ISSUE TITLE
Issue with process in exabgp.conf

### ISSUE THREAD

**Issue by Flygarfisken** [Exa-Networks/exabgp#956]
Hi,

### I need help to redistribute Server loopback: 1.1.1.3 over exabgp but can't get the process working

I have been working with this for a while now and tried all kind of different syntaxes and such... it is making me crazy.
I am trying to setup Ubuntu Anycast DNS setup with bind9 and exabgp and I know that others have done it before

Router: 1.1.1.1
Server: 1.1.1.2
Server loopback: 1.1.1.3

I have a Ubuntu 18.04 with Bind9 and Exabgp installed
apt-get install bind9
apt-get install exabgp

**/etc/bind/named.conf.options**
>           acl enet-networks {
>                  127.0.0.1;
>                  ::1;
>           };
>          logging {
>                  channel simple_log {
>                          file "/var/log/named/bind.log" versions 10 size 5m;
>                          severity warning;
>                          print-time yes;
>                          print-severity yes;
>                          print-category yes;
>                           };
>                  category default{
>                 simple_log;
>                  };
>           };
>           options {
>                  directory "/var/cache/bind";
> 
>         // If there is a firewall between you and nameservers you want
>         // to talk to, you may need to fix the firewall to allow multiple
>         // ports to talk.  See http://www.kb.cert.org/vuls/id/800113
> 
>         // If your ISP provided one or more IP addresses for stable
>         // nameservers, you probably want to use them as forwarders.
>         // Uncomment the following block, and insert the addresses replacing
>         // the all-0's placeholder.
> 
>          forwarders {
>               8.8.8.8;
>               8.8.4.4;
>               1.1.1.1;
>          };
> 
>           dnssec-validation auto;
> 
>         auth-nxdomain no;    # conform to RFC1035
>        listen-on-v6 { any; };
> 
>         version "Version not shown";
> 
>        # test
>         server-id "test";
>         query-source address 1.1.1.2;
> 
>         listen-on {
>                 1.1.1.3;
>         };
> 
>         allow-query { networks; };
>         recursion yes;
>         allow-recursion { networks; };
>         allow-transfer { none; };
>         statistics-file "/var/log/named/named_stats";
>          };

**/etc/exabgp/exabgp.conf**
> neighbor 1.1.1.1 {
>     router-id 1.1.1.2;
>     local-address 1.1.1.2;
>     local-as 65511;
>     peer-as 65510;
>     group-updates;
> }
> #process watch-dns {
> #run python -m exabgp healthcheck --cmd "dig -b 127.0.0.1 @1.1.1.3 www.google.com soa";
> #}

The processes is built from this https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/application/healthcheck.py

When using the hastag on the process = the process is obviously not used and the BGP between my router and ubuntu is established

> #show bgp vrf inet neighbors 1.1.1.2
> Thu Feb 20 12:50:39.324 CET
> 
> BGP neighbor is 1.1.1.2, vrf inet
>  Remote AS 65511, local AS 65510, external link
>  Remote router ID 1.1.1.2
>   BGP state = Established, up for 00:00:05

But when removing the hashtags -> exiting root -> systemctl restart exabgp -> systemctl status exabgp -> then I get this:

**/etc/exabgp/exabgp.conf without hashtags**
> neighbor 1.1.1.1 {
>     router-id 1.1.1.2;
>     local-address 1.1.1.2;
>     local-as 65511;
>     peer-as 65510;
>     group-updates;
> }
> process watch-dns {
> run python -m exabgp healthcheck --cmd "dig -b 127.0.0.1 @1.1.1.3 www.google.com soa";
> }

> ● exabgp.service - ExaBGP
>    Loaded: loaded (/lib/systemd/system/exabgp.service; disabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Thu 2020-02-20 11:53:47 UTC; 1s ago
>      Docs: man:exabgp(1)
>            man:exabgp.conf(5)
>            https://github.com/Exa-Networks/exabgp/wiki
>   Process: 1693 ExecStart=/usr/sbin/exabgp /etc/exabgp/exabgp.conf (code=exited, status=1/FAILURE)
>  Main PID: 1693 (code=exited, status=1/FAILURE)
> 
> Feb 20 11:53:47 sto-dc01dns03 exabgp[1693]: 11:53:47 | 1693   | cli control     | > chmod 600 //run/exabgp.{in,out}
> Feb 20 11:53:47 sto-dc01dns03 exabgp[1693]: 11:53:47 | 1693   | configuration   | performing reload of exabgp 4.0.2-1c737d99
> Feb 20 11:53:47 sto-dc01dns03 exabgp[1693]: 11:53:47 | 1693   | configuration   | problem with the configuration file, no change done
> Feb 20 11:53:47 sto-dc01dns03 exabgp[1693]: 11:53:47 | 1693   | configuration   |
> Feb 20 11:53:47 sto-dc01dns03 exabgp[1693]: 11:53:47 | 1693   | configuration   | syntax error in section process
> Feb 20 11:53:47 sto-dc01dns03 exabgp[1693]: 11:53:47 | 1693   | configuration   | line 10: }
> Feb 20 11:53:47 sto-dc01dns03 exabgp[1693]: 11:53:47 | 1693   | configuration   |
> Feb 20 11:53:47 sto-dc01dns03 exabgp[1693]: 11:53:47 | 1693   | configuration   | unset process sections: encoder
> Feb 20 11:53:47 sto-dc01dns03 systemd[1]: exabgp.service: Main process exited, code=exited, status=1/FAILURE
> Feb 20 11:53:47 sto-dc01dns03 systemd[1]: exabgp.service: Failed with result 'exit-code'.

**Comment by thomas-mangin** [comment]
The syntax is invalid for exabgp 4.x
https://github.com/Exa-Networks/exabgp/blob/master/etc/exabgp/api-add-remove.conf

**Comment by Flygarfisken** [comment]
I do not have such deep knowledge and would love to get assistance... been struggling with this for weeks now
Really thankful for the help!

**Found this healthcheck file**
> root@sto-dc01dns03:~# find / -name healthcheck.py
> /usr/lib/python3/dist-packages/exabgp/application/healthcheck.py

**Should I use it like this?**
> process watch-dns {
>     run /usr/lib/python3/dist-packages/exabgp/application/healthcheck.py;
>     encoder json;
> }
> neighbor 172.16.1.1 {
>     router-id 172.16.1.2;
>     local-address 172.16.1.2;
>     local-as 65511;
>     peer-as 65510;
>     group-updates;
>     capability {
>         graceful-restart;
>     }
>     api {
>         processes watch-dns;
>     }
> }



admin@test:~$ systemctl status exabgp
● exabgp.service - ExaBGP
   Loaded: loaded (/lib/systemd/system/exabgp.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-02-20 13:43:03 UTC; 1s ago
     Docs: man:exabgp(1)
           man:exabgp.conf(5)
           https://github.com/Exa-Networks/exabgp/wiki
  Process: 1832 ExecStart=/usr/sbin/exabgp /etc/exabgp/exabgp.conf (code=exited, status=1/FAILURE)
 Main PID: 1832 (code=exited, status=1/FAILURE)

Feb 20 13:43:03 sto-dc01dns03 exabgp[1832]: 13:43:03 | 1832   | cli control     | > chmod 600 //run/exabgp.{in,out}
Feb 20 13:43:03 sto-dc01dns03 exabgp[1832]: 13:43:03 | 1832   | configuration   | performing reload of exabgp 4.0.2-1c737d99
Feb 20 13:43:03 sto-dc01dns03 exabgp[1832]: 13:43:03 | 1832   | configuration   | problem with the configuration file, no change done
Feb 20 13:43:03 sto-dc01dns03 exabgp[1832]: 13:43:03 | 1832   | configuration   |
Feb 20 13:43:03 sto-dc01dns03 exabgp[1832]: 13:43:03 | 1832   | configuration   | syntax error in section process
Feb 20 13:43:03 sto-dc01dns03 exabgp[1832]: 13:43:03 | 1832   | configuration   | line 2: run /usr/lib/python3/dist-packages/exabgp/application/healthcheck.py ;
Feb 20 13:43:03 sto-dc01dns03 exabgp[1832]: 13:43:03 | 1832   | configuration   |
Feb 20 13:43:03 sto-dc01dns03 exabgp[1832]: 13:43:03 | 1832   | configuration   | exabgp will not be able to run this program "/usr/lib/python3/dist-packages/exabgp/application/healthcheck.py"
Feb 20 13:43:03 sto-dc01dns03 systemd[1]: exabgp.service: Main process exited, code=exited, status=1/FAILURE
Feb 20 13:43:03 sto-dc01dns03 systemd[1]: exabgp.service: Failed with result 'exit-code'.

**Comment by thomas-mangin** [comment]
This should work
```
process watch-dns {
  run /usr/lib/python3/dist-packages/exabgp/application/healthcheck.py;
  encoder json;
}
neighbor 172.16.1.1 {
  router-id 172.16.1.2;
  local-address 172.16.1.2;
  local-as 65511;
  peer-as 65510;

  api {
    processes [ watch-dns ];
  }
}
```

**Comment by thomas-mangin** [comment]
But you need to pass the right parameters to healthcheck.py

**Comment by Flygarfisken** [comment]
I have tried with both of your commands and I get this when I try to do systemctl restart exabgp - haven't touched the healthcheck.py file - this was installed when exabgp was installed
[healthcheck.py.txt](https://github.com/Exa-Networks/exabgp/files/4231588/healthcheck.py.txt)

> root@sto-dc01dns03:~# exabgp --version
> ExaBGP : 4.0.2-1c737d99
> Python : 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
> Uname  : Linux sto-dc01dns03 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64
> Root   :
> root@sto-dc01dns03:~# python --version
> Python 2.7.17
> root@sto-dc01dns03:~# python3 --version
> Python 3.6.9

admin@sto-dc01dns03:~$ systemctl status exabgp
● exabgp.service - ExaBGP
   Loaded: loaded (/lib/systemd/system/exabgp.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-02-20 15:26:43 UTC; 1s ago
     Docs: man:exabgp(1)
           man:exabgp.conf(5)
           https://github.com/Exa-Networks/exabgp/wiki
  Process: 1831 ExecStart=/usr/sbin/exabgp /etc/exabgp/exabgp.conf (code=exited, status=1/FAILURE)
 Main PID: 1831 (code=exited, status=1/FAILURE)

Feb 20 15:26:43 sto-dc01dns03 exabgp[1831]: 15:26:43 | 1831   | cli control     |  - /var/run/
Feb 20 15:26:43 sto-dc01dns03 exabgp[1831]: 15:26:43 | 1831   | cli control     | please make them in one of the folder with the following commands:
Feb 20 15:26:43 sto-dc01dns03 exabgp[1831]: 15:26:43 | 1831   | cli control     | > mkfifo //run/exabgp.{in,out}
Feb 20 15:26:43 sto-dc01dns03 exabgp[1831]: 15:26:43 | 1831   | cli control     | > chmod 600 //run/exabgp.{in,out}
Feb 20 15:26:43 sto-dc01dns03 exabgp[1831]: 15:26:43 | 1831   | configuration   | performing reload of exabgp 4.0.2-1c737d99
Feb 20 15:26:43 sto-dc01dns03 exabgp[1831]: 15:26:43 | 1831   | configuration   | problem with the configuration file, no change done
Feb 20 15:26:43 sto-dc01dns03 exabgp[1831]: 15:26:43 | 1831   | configuration   | problem parsing configuration file line 2
Feb 20 15:26:43 sto-dc01dns03 exabgp[1831]: 15:26:43 | 1831   | configuration   | error message: invalid syntax
Feb 20 15:26:43 sto-dc01dns03 systemd[1]: exabgp.service: Main process exited, code=exited, status=1/FAILURE
Feb 20 15:26:43 sto-dc01dns03 systemd[1]: exabgp.service: Failed with result 'exit-code'.

**Comment by Flygarfisken** [comment]
I FOUND IT!
You wrote like this

> run "python3 -m exabgp healthcheck  --cmd "dig -b 127.0.0.1 @1.1.1.3 www.google.com soa";

But there is a tiny " before python3 and when I removed it I got it to work!

Omg thank you so very very much!
