### ISSUE TITLE
section receive is invalid in process, process

### ISSUE THREAD

**Issue by mitradir** [Exa-Networks/exabgp#959]
Hi!

I installed exabgp with pip and tried to use the process section as described in the [wiki](https://github.com/Exa-Networks/exabgp/wiki/Configuration-:-Process). Here is part of my config:

```
process consumer {
        run "./route-consumer.py";
        encoder json;
        receive {
                neighbor-changes;
                parsed;
        }
}
```
But when I tried to run exabgp I'm got the next message:

19:31:45 | 13937  | configuration | performing reload of exabgp 4.2.6
19:31:45 | 13937  | configuration | not reloaded, no change found in the configuration
19:31:45 | 13937  | configuration |         
19:31:45 | 13937  | configuration | syntax error in section process
19:31:45 | 13937  | configuration | line 14: receive {
19:31:45 | 13937  | configuration |         
19:31:45 | 13937  | configuration | section receive is invalid in process, process

I will be glad if you can assist me in overcoming this issue.

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/blob/master/etc/exabgp/api-api.conf

**Comment by thomas-mangin** [comment]
What you are using is indeed not a valid version 4 syntax
