### ISSUE TITLE
aggregator attribute syntax

### ISSUE THREAD

**Issue by thomas955** [Exa-Networks/exabgp#961]
##### Summary
Aggregator statement in configuration marked as syntax error if spaces missing after "(" and before ")" : 
e.g. `route 1.1.1.0/24 ... aggregator (29736:2.2.2.2)`
It is working if i insert spaces `( 29736:2.2.2.2 )`.

It is possible to announce the route in both ways with or without spaces via exabgpcli:

`./exabgpcli announce route 1.1.1.0/24 ... aggregator (29736:2.2.2.2)` <- working as well as
`./exabgpcli announce route 1.1.1.0/24 ... aggregator ( 29736:2.2.2.2 )`

##### OS
```
Linux Ubuntu 18.04
```

##### Version

```
fa410e5df2f86ba5006c9c8fe14c10e5a191a027
```

##### Installation

```
git checkout
```

##### Program output

```
12:04:18 | 63464  | configuration | syntax error in section neighbor/static
12:04:18 | 63464  | configuration | line 13: route 193.95.82.0/24 next-hop 194.25.5.161 as-path [ 3257 2609 5438 37671 ] originator-id 194.25.5.161 local-preference 100 atomic-aggregate aggregator (37671:193.95.79.237) ;
12:04:18 | 63464  | configuration |         
12:04:18 | 63464  | configuration | invalid aggregator

```

##### Steps to reproduce
load confguration with 
```
neighbor 1.2.3.4 {
    router-id 1.2.3.1;
    local-address 1.2.3.1;
    local-as 3333; 
    peer-as 3333; 
    hold-time 180;
    group-updates false;
    family {
        ipv4 unicast;
        ipv6 unicast;
    static {
        route 193.95.82.0/24 next-hop 194.25.5.161 as-path [ 3257 2609 5438 37671 ] originator-id 194.25.5.161 local-preference 100 atomic-aggregate aggregator (37671:193.95.79.237);
    }
}
```

**Comment by thomas-mangin** [comment]
Thank you very much for reporting the issue. Fixed :-D
