### ISSUE TITLE
v4.2.6: exabgp stuck at read(0,

### ISSUE THREAD

**Issue by sincerywaing** [Exa-Networks/exabgp#965]
exabgp 4.2.6

config:

```

        process b {
        run xxx;
        }

        process a {
        run xxxx;
        }

template {

    neighbor router_v4 {
        description "something to announce";
        local-as 567898;
        peer-as 12345;
        hold-time 10;
        group-updates true;
    family {
        ipv4 unicast;
    }
    api {
    processes [
        a,
         b,
            ];
    }
}

}

neighbor x.x.x.x {
	inherit router_v4;
	router-id x.x.x.x;
	local-address x.x.x.x;
}
```
I don't see anything wrong but it errors out: syntax error in section process on line x: }

**Comment by thomas-mangin** [comment]
Starting exabgp this way will help:
`env exabgp.debug.configuration=1 ./sbin/exabgp config -d CONFIG`

`encoder json;` missing in the process section.

**Comment by sincerywaing** [comment]
cool thanks Thomas.

I managed to get it work.

btw is there any change on v4 that use the healthcheck command? the same config file with `command=some command` does not work in exabgpv4 while it works in v3. basically it seems no longer doing what specified in `command`

**Comment by thomas-mangin** [comment]
healthcheck will now only issue the route once I believe. There is a wiki entry for converting from 3 to 4.

**Comment by thomas-mangin** [comment]
`exabgp --de` to see if the option is correctly set

**Comment by sincerywaing** [comment]
```
exabgp.api.ack=false
exabgp.api.respawn=false
exabgp.api.encoder=text
```

looks like correct.

**Comment by sincerywaing** [comment]
my situation looks a lot like below 

```
The API now ack message sent with a 'done' or 'error' string back. program written for ExaBGP 3.4 will not expect to have to handle it.

If enough message are sent without being consumed by the api application, the PIPE can become blocking, resulting in ExaBGP stopping to do anything.

The solution is to make sure the environment value exabgp.api.ack is set to false, either using then environment like env exabgp.api.ack=false exabgp configuration or adding it the .env environment file.

If an application written for ExaBGP 3.4 or earlier does not consume the acknowledgement messages sent in response to API command and if ExaBGP is started without the exabgp.api.ack option, at some point this will cause ExaBGP to lock.

```

but I thought since I have ack=false, I shouldn't have the issue.

**Comment by sincerywaing** [comment]
> healthcheck will now only issue the route once I believe. There is a wiki entry for converting from 3 to 4.

my `command = python some.py` is actually doing some curl to an application and logging to a file. but the log stops around 20s after exabgp starts up. in 3.4 it logs every `internval`.

**Comment by sincerywaing** [comment]
it turned out issue with init file. close for now

**Comment by sincerywaing** [comment]
tried shuffle things around but it still stuck after running about 20s. strace shows stuck at read(0,

**Comment by sincerywaing** [comment]
I think I know why. though in env I set ack=false, I have sudo directive in the config as I need take out the vip. and these parameters are exclusive to each other. do we know why is that? any workaround?

**Comment by thomas-mangin** [comment]
Hi @sincerywaing 

You have a problem with blocking IO. Please use the `ack=false` if you do not know about to write async IO code.

https://github.com/Exa-Networks/exabgp/blob/master/etc/exabgp/example-api-program.run

**Comment by sincerywaing** [comment]
@thomas-mangin Thanks. the thing is that I already have ack=false set in env file (see previous discussion). but I took a look at code it’s conflict with sudo? any workaround on this?

**Comment by thomas-mangin** [comment]
And if you use read (which is a blocking call) on 0 aka stdin (which is what ExaBGP sends back)  when there is no data to be read, it will stay there forever. Do not read from ExaBGP if you are not sure there is thing to read, and there will be nothing to read if you use `ack=false`

**Comment by sincerywaing** [comment]
sounds good. one last question - isn’t ack=false the default setting? is it conflict with sudo?

**Comment by sincerywaing** [comment]
> And if you use read (which is a blocking call) on 0 aka stdin (which is what ExaBGP sends back) when there is no data to be read, it will stay there forever. Do not read from ExaBGP if you are not sure there is thing to read, and there will be nothing to read if you use `ack=false` (at least for announce / withdraw commands)

btw how do I know when I use read? my script does not read anything...

**Comment by thomas-mangin** [comment]
You wrote 
```
strace: Process 39221 attached
read(0,
```

You are telling me your code does.

**Comment by sincerywaing** [comment]
ah I thought this is what exabgp does... essentially my code is not doing anything but curl...

**Comment by sincerywaing** [comment]
@thomas-mangin my configuration is essentially the same as https://github.com/Exa-Networks/exabgp/blob/e9fa7ced7a4867b7ff7ca72e20a305d7231894c3/etc/exabgp/example-healthcheck.conf

**Comment by sincerywaing** [comment]
more logs when I reload exabgp

```
Uncaught exception: reentrant call inside <_io.BufferedReader name='<stdin>'>
                                                                                      Traceback (most recent call last):
                                                                                        File "python3.7/site-packages/exabgp/application/healthcheck.py", line 653, in main
                                                                                          loop(options)
                                                                                        File "python3.7/site-packages/exabgp/application/healthcheck.py", line 611, in loop
                                                                                          checks, state = one(checks, state)
                                                                                        File "python3.7/site-packages/exabgp/application/healthcheck.py", line 598, in one
                                                                                          exabgp(state)
                                                                                        File "python3.7/site-packages/exabgp/application/healthcheck.py", line 522, in exabgp
                                                                                          sys.stdin.readline()
                                                                                        File "python3.7/site-packages/exabgp/application/healthcheck.py", line 605, in sigterm_handler
                                                                                          exabgp(states.EXIT)
                                                                                        File "python3.7/site-packages/exabgp/application/healthcheck.py", line 522, in exabgp
                                                                                          sys.stdin.readline()
                                                                                      RuntimeError: reentrant call inside <_io.BufferedReader name='<stdin>'>

```

**Comment by sincerywaing** [comment]
I managed to fix this by adding some code in https://github.com/Exa-Networks/exabgp/issues/895#issuecomment-502030892
@thomas-mangin do you recommend this code as a separate process (in a while loop) or integrate it inside an existing process? e.g. run clear_pipeline() after the each time the main func run.

**Comment by sincerywaing** [comment]
more on strace:

```
read(5, "", 4096)                       = 0
wait4(26787, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 26787
close(5)                                = 0
sendto(3, "<30>healthcheck-announce[26602]:"..., 71, 0, NULL, 0) = 71
write(1, "announce route 1.2.3.4/3"..., 56) = 56
ioctl(1, TCGETS, 0x7ffc027d97f0)        = -1 ENOTTY (Inappropriate ioctl for device)
read(0, 
```

**Comment by sincerywaing** [comment]
looks like indeed `ack=true` fixed my problem. it seems exabgp is waiting for `done\n' from process, while having `ack=true` can send it.

**Comment by thomas-mangin** [comment]
need to update the doc to be clearer.
