### ISSUE TITLE
change of static route in config file causes update and afterwards withdrawal after reload

### ISSUE THREAD

**Issue by arnevt** [Exa-Networks/exabgp#972]
##### Summary
hi,

in our exabgp setup (long running 4.0.9, but also tested on latest 4.1 and 4.2 released) we announce a static route via
```
route 1.2.3.0/24 next-hop 5.6.7.8 community [762:762 762:22110 762:22140 762:22130 762:22020 774:50524];
```
if we change that to e.g.
```
route 1.2.3.0/24 next-hop 5.6.7.8 community [762:762];
```
and issue a systemctl reload (kill -USR1) we have the symptom that the route disappears from our network. Looking via tcpdump tells me we see a BGP update for the new (changed) route, but afterwards an BGP withdrawal for the same prefix (causing our junipers to delete the route, like it should after receiving a withdrawal)

##### OS
```
Linux (debian 9.4)

```

Linux exabgp001  4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux
```

```

##### Version
fatal: Not a git repository (or any of the parent directories): .git
ExaBGP : 4.2.5
Python : 3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]
Uname  : Linux exabgp001 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64
Root   : /usr/local/exabgp-4.2.5
```

```

##### Installation
```
downloaded tar.gz and extracted to /usr/local
```

##### Environment 
```
fatal: Not a git repository (or any of the parent directories): .git

[exabgp.log]
message = true
parser = true
```

##### Configuration
since this is a production environment, I cannot disclose the real config file however here are some snippets
```
process parsed-route-backend {
    encoder text;
    run /etc/exabgp/blacklist_dynamic.py;
}

process syslog {
    encoder text;
    run /etc/exabgp/run/syslog-1.py;
}

template {
    neighbor CORE {
        local-as 65535;
        peer-as 762;
        capability {
            graceful-restart 5;
        }

        family {
            ipv4 unicast;
            ipv4 flow;
            ipv6 unicast;
        }

        api {
            processes [ parsed-route-backend ];
        }

            flow {
              route brute-force-RDP {
                match {
                        source 6.6.6.0/22;
                    source 7.7.17.0/22;
                    destination-port =3389;
                }
                then {
                    discard;
                }
              }
            }
           static {
                route 1.2.3.0/24 next-hop 5.6.7.8 community [762:762 762:22110 762:22140 762:22130 762:22020 774:50524];
           }
     }
}

neighbor 5.5.5.5 {
        inherit CORE;
        router-id 5.5.5.4;
        local-address 5.5.5.4;
        description "RTR1";
}

neighbor 5.5.5.6 {
        inherit CORE;
        router-id 5.5.5.4;
        local-address 5.5.5.4;
        description "RTR2";
}

(in total 5 such neighbours)
```

##### Program output
```
when running exabgp -d we see a lot of updates, but no details on exact content of bgp messages, so rather useless
```

##### Steps to reproduce
```
add a route in the static entry
start exabgp
change some communities in that static entry the config file (going from 1 to more or from more to 1 community)
reload (via -USR1)
```

##### Importance
```
this is a setup running in production, but not causing any issues (for the moment)
```

**Comment by thomas-mangin** [comment]
Argh, I feel like killing the SIG feature .. It was written before there was a way to control exabgp externally and it is a pain ..

**Comment by thomas-mangin** [comment]
A way around the issue is to use graceful-restart with 10 seconds and restart exabgp, it will give the router 10s to get the new routes before removing the old ones as stale.

**Comment by sincerywaing** [comment]
if I remember correctly I had set the graceful restart to default 60s already.but I can double check.

Any way we can test this? i.e. release a 4.2.6.1?

**Comment by thomas-mangin** [comment]
pip install git+https://github.com/Exa-Networks/exabgp.git should work but I started to change master in view of releasing exabgp 5 so there is lots of change. The configuration format is still the same atm but the command line did change a bit

**Comment by arnevt** [comment]
going to try in a few days, don't wanna run this in production and our staging/dev network is occupied by dev ATM :)

**Comment by thomas-mangin** [comment]
no news for two years is good news.
