### ISSUE TITLE
Question - Exabgp deployment recommendation

### ISSUE THREAD

**Issue by mnanduri** [Exa-Networks/exabgp#979]
What do you  guys recommend to run exabgp on if you want to receive 3-5 million routes and establish 100 to 150 BGP sessions wrt memory/cpu and cores?

**Comment by thomas-mangin** [comment]
Can I ask your use case please ?

**Comment by mnanduri** [comment]
predominantly as route collector.

**Comment by thomas-mangin** [comment]
ExaBGP is written in Python which by default can only use a single core. The code is not super fast neither. That said, it should never drop connection even when busy so if speed is not an issue and your BGP peers are not going to complain as ExaBGP is slow to update it will not matter.

If you use ExaBGP to connect outbound (and not accept connection), you can also break the configuration in smaller chunks and have multiple instances running if they all feed a single DB for example.

Once established the churn is low and 150 connections should be fine. It will just take all the CPU for quite some time until it does. Memory wise, make sure to disable the ADJ-RIB (not sure what is the default nowdays) to not eat lots of memory. Caching will improve perf but be ready to though quite a few Gb of memory at it.

Alternatively, you could try to have another OSS BGP (Bird/FRR) in front and negotiate AddPath, which will still give you all the routes from all the peer but then the heavy BGP lifting is done there.

**Comment by mnanduri** [comment]
Thanks for the information, appreciate it.
