### ISSUE TITLE
4.2.7 doesn't support "python -m exabgp healthcheck"

### ISSUE THREAD

**Issue by shaoberry** [Exa-Networks/exabgp#980]
python -m exabgp healthcheck -F unicast-ip4.cfg
python: No module named `exabgp.__main__`; 'exabgp' is a package and cannot be directly executed

I found ```exabgp/__main__.py``` is missing. is it deprecated, or deleted in 4.2.7 by mistake?

**Comment by thomas-mangin** [comment]
A mistake from my part when I was trying to get zipapp working - resolved with 4.2.8 just out now
