### ISSUE TITLE
Question - status of bgp session

### ISSUE THREAD

**Issue by verthais** [Exa-Networks/exabgp#982]
I've been using a docker image with exabgp and my rest api - which holds flask app with class holding stdout stream - to issue commands to it. I've wanted to receive some information from exabgp and I've encoutered some dificulties:
1) I can't seem to find the command to check the status of connection to bgp.
2) struggle to understand how to parse output of exabgp.

Can you please support me with some tips?

**Comment by thomas-mangin** [comment]
hi @verthais 

(1) You can have a look at exabgpcli .. you should be able to do a "show bgp summary" to know the peers.
(2) it is either plain text or JSON - you are right the format is not documented as should .. one mor thing on the long todo  ...

**Comment by verthais** [comment]
I must admint I'm quite a newbie in terms of communication with bgp and exabgp thus when i do
`echo "show bgp summary" >> /run/exabgp/exabgp.in`
the message is printed:
`# 09:08:49 | 28     | api           | command from process not understood : show bgp summary`
and on the `tail -f /run/exabgp/exabgp.out` 
`error`
I found some infromation with `show neighbour extensive` command:
```
  Session                         Local
   local                    10.97.3.100                                
   state                           IDLE                                
   down for                     0:11:55  
```
and I'm wondering if this are the one I'm looking for.

**Comment by thomas-mangin** [comment]
Yes, this is what you are looking for. You should really have a look at the examples in the etc folder of the repository and read the wiki entry about converting scripts from version 3 to version 4.
