### ISSUE TITLE
Issue with the process' PIPE, terminating it and restarting it

### ISSUE THREAD

**Issue by ldong2014** [Exa-Networks/exabgp#991]
Exabgp not work,  logging as the below

uter-id 202.112.20.6 family-allowed in-open
Thu, 03 Sep 2020 17:50:12 | INFO     | 10705  | configuration | Loaded new configuration successfully
Thu, 03 Sep 2020 17:50:12 | INFO     | 10705  | processes     | Forked process service-dynamic
Thu, 03 Sep 2020 17:50:13 | INFO     | 10705  | processes     | Command from process service-dynamic :  
Thu, 03 Sep 2020 17:50:13 | INFO     | 10705  | processes     | Issue with the process' PIPE, terminating it and restarting it
Thu, 03 Sep 2020 17:50:13 | INFO     | 10705  | processes     | Terminating process service-dynamic
Thu, 03 Sep 2020 17:50:13 | INFO     | 10705  | processes     | Forked process service-dynamic
Thu, 03 Sep 2020 17:50:13 | INFO     | 10705  | processes     | Command from process service-dynamic :  
Thu, 03 Sep 2020 17:50:13 | INFO     | 10705  | processes     | Issue with the process' PIPE, terminating it and restarting it
Thu, 03 Sep 2020 17:50:13 | INFO     | 10705  | processes     | Terminating process service-dynamic
Thu, 03 Sep 2020 17:50:13 | INFO     | 10705  | processes     | Forked process service-dynamic
Thu, 03 Sep 2020 17:50:14 | INFO     | 10705  | processes     | Command from process service-dynamic :  
Thu, 03 Sep 2020 17:50:14 | INFO     | 10705  | processes     | Issue with the process' PIPE, terminating it and restarting it
Thu, 03 Sep 2020 17:50:14 | INFO     | 10705  | processes     | Terminating process service-dynamic
Thu, 03 Sep 2020 17:50:14 | INFO     | 10705  | processes     | Forked process service-dynamic
Thu, 03 Sep 2020 17:50:14 | INFO     | 10705  | network       | Connected to peer neighbor 202.112.20.5 local-ip 202.112.20.6 local-as 65500 peer-as 64512 router-id 202.112.20.6 family-allowed in-open (out)
Thu, 03 Sep 2020 17:50:14 | INFO     | 10705  | processes     | Command from process service-dynamic :  
Thu, 03 Sep 2020 17:50:14 | INFO     | 10705  | processes     | Issue with the process' PIPE, terminating it and restarting it
Thu, 03 Sep 2020 17:50:14 | INFO     | 10705  | processes     | Terminating process service-dynamic
Thu, 03 Sep 2020 17:50:14 | INFO     | 10705  | processes     | Forked process service-dynamic
Thu, 03 Sep 2020 17:50:15 | INFO     | 10705  | processes     | Command from process service-dynamic :  
Thu, 03 Sep 2020 17:50:15 | INFO     | 10705  | processes     | Issue with the process' PIPE, terminating it and restarting it
Thu, 03 Sep 2020 17:50:15 | INFO     | 10705  | processes     | Terminating process service-dynamic
Thu, 03 Sep 2020 17:50:15 | INFO     | 10705  | processes     | Forked process service-dynamic
Thu, 03 Sep 2020 17:50:15 | CRITICAL | 10705  | processes     | Too many respawn for service-dynamic (5) terminating program
Thu, 03 Sep 2020 17:50:15 | ERROR    | 10705  | reactor       | Problem when sending message(s) to helper program, stopping
Thu, 03 Sep 2020 17:50:15 | INFO     | 10705  | reactor       | Performing shutdown
Thu, 03 Sep 2020 17:50:15 | INFO     | 10705  | network       | Peer    202.112.20.5 ASN 64512   out loop, stop, message [shutting down]
Thu, 03 Sep 2020 17:50:15 | INFO     | 10705  | processes     | Terminating process service-dynamic

** Bug Report **

We are sorry that you are experiencing an issue with ExaBGP.

Before opening this issue could you please:
 - make sure the problem was not already reported to avoid duplicates.
 - check if the problem is still present on the latest version (master)
 - provide an full output of exabgp running with the "-d" option, including any stacktrace
   (please provide the full output - even if long)

**Describe the bug**

**To Reproduce**

- Please include a way to reproduce the issue if possible.
- we use `sudo ./qa/sbin/bgp --port 179 --echo` to similate an IBGP peer

**Expected behavior**

**Environment (please complete the following information):**

 - OS: [e.g. OSX, Ubuntu, ..]
 - Version [e.g. master, pip version installed, ... ]

**Additional context**

**Comment by ldong2014** [comment]
Is there anyone can help me?

**Comment by thomas-mangin** [comment]
Not really as you do not provide the information requested, no configuration file, etc. Also `Too many respawn for service-dynamic (5) terminating program` means that the program you are running is ending (when it should not) and therefore not working as should, this is what you need to debug. Good luck!
